### DISCUSSION TITLE
Portal cooldown

### DISCUSSION THREAD

**Discussion by LogGits** [Zrips/CMI#1125] [Enhancement]
**Description of issue or feature request:** CMI Cooldown per portal. Whereby it allows users to add a cooldown to a portal with a cooldown message when they cant use it.
`You can use this portal in X seconds.`

This would also need a bypass permission.

I know this is currently possible:
```yaml
  rtp:
    Loc: -1219.0:79.0:1170.0:-1218.0:89.0:1176.0
    enabled: true
    effect: explode
    showParticles: true
    particleAmount: 8
    particleHide: 0
    activationRange: 24
    commandsWithoutTp: true
    commands:
    - cooldown:200! cmi effect [playerName] blindness 2 1 -s
    - cooldown:200! fromConsole! cmi rt [playerName] world2
```
However it doesn't give a cooldown message and if it did, this would provide 2 cooldown messages.
I am proposing two new variables, `cooldown` and `cooldownMessage`. `cooldown` is defaulted to `-1` which is off, and `cooldownMessage` is defaulted to "You can use this portal in X seconds" where `X` is the time formatted into `d days h hours m minutes s seconds`.
