### DISCUSSION TITLE
CMI death taxes

### DISCUSSION THREAD

**Discussion by Mrs-Feathers** [Zrips/CMI#1307] [Feature Requests]
since the plugins discussion page is basically all just unanswered questions - mine included, i thought it best to ask here. this isn't a bug report or suggestion. just a question.

does CMI have a death tax for money and exp? i know that CMI handles money and a lot of other respawning stuff.. so i think it'd be within reason for it to include something that takes money when you die. if this is in the plugin, what's the config option called? and if not, well, consider this a suggestion then.

**Comment by TheWranger** [comment]
Adding on to the issue - it would be nice if we could take a percentage of the players money instead of taking a fixed amount, I want to charge richer players more when they die as it can help take that money out of the economy.

**Comment by mercurialmusic** [comment]
In case you haven't seen it, you can at least do a fixed amount now with an eventCommands entry, but not a percentage (yet).

**Comment by Mrs-Feathers** [comment]
Yeah. That’s what I have going right now. Just a flat 500. But with jobs and such by the same author players earn a lot later. So flat rate it’s either make noobs fear death or take all their money by making ranked up people not want to spam kill themselves. So I guess it’s ok. But still a percentage would do a lot more good. Even a “/money take [playerName] 15 percent” would be an epic addition. Just like how you can specify “levels” at the end of any exp command. Now and it gives you levels instead of exp amount. You know?

**Comment by mercurialmusic** [comment]
Yup. The money command would make the feature more flexible as well.

**Comment by Mrs-Feathers** [comment]
would allow for a lot more than death taxes too. for stuff that you'd need sometimes like the /heal command or something.. players can use it and it costs money to use.. but once you rank up in jobs and start earning a bunch of money, what stops a player from abusing that in PvP? the only easy way is to tax the command in percentage instead of flat. right? and theres lots of commands that are there for players but shouldn't be abused...and to make /rankup "quests" easier to write, instead of saying "you much earn this much money" because again, some players can just abuse the system.. have it "you must earn this much [from a percentage of your money, having taken it into account once you ranked up last time] or something. that might be a bit too much.. but i mean, a percentage command would be useful for a lot of other things too, not just death taxes.

**Comment by mercurialmusic** [comment]
With a placeholder for %cmi_user_balance_[percentage]% so they know how much they'll be charged. :3

**Comment by CloudeLecaw** [comment]
Death taxes can be done allready

this all can be added by EventCommands.yml. 
We also made this on the server, works without issues.
Waht it does: -> Death cost X money and X exp of  themoney and exp the player has. (if he has)
The Taxrate is defineable for each group.
_**To work. players need regular permission to keep all xp on death.  (cmi.keepexp)**_

and because i love you all so much ^^...  i share my EventCommands.yml part that does this with you.

```
playerDeath:
  Enabled: true
  Commands:
  - check:%cmi_user_group%==Gast! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/1000000% -s
  - check:%cmi_user_group%==Gast! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/1% -s
  - check:%cmi_user_group%==TuTDone! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/1000000% -s
  - check:%cmi_user_group%==TuTDone! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/1% -s
  - check:%cmi_user_group%==Spieler! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/10% -s
  - check:%cmi_user_group%==Spieler! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/10% -s
  - check:%cmi_user_group%==TestGamer! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/10% -s
  - check:%cmi_user_group%==TestGamer! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/10% -s
  - check:%cmi_user_group%==VIP! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==VIP! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==VIPV! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==VIPV! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==VIPmini! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==VIPmini! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==Guard! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==Guard! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==Mod! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==Mod! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==Builder! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==Builder! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==Senior! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/20% -s
  - check:%cmi_user_group%==Senior! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/20% -s
  - check:%cmi_user_group%==Admin! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/10% -s
  - check:%cmi_user_group%==Admin! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/10% -s
  - check:%cmi_user_group%==CoOwner! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/1000% -s
  - check:%cmi_user_group%==CoOwner! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/1000% -s
  - check:%cmi_user_group%==Owner! asConsole! cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance}/10000% -s
  - check:%cmi_user_group%==Owner! asConsole! cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/10000% -s
  SourceCommands: []
playerRespawn:
  Enabled: true
  Commands:
  - check:%cmi_user_meta_moneydeath%!=0! asConsole! cmi money take [playerName] %cmi_user_meta_moneydeath% -s
  - check:%cmi_user_meta_expdeath%!=0! asConsole! cmi exp [playerName] take %cmi_user_meta_expdeath% -s
  - check:%cmi_user_meta_moneydeath%==0! check:%cmi_user_meta_expdeath%!=0! asConsole! cmi titlemsg [playerName] You died. %subtitle% &fYou lost &2&l%cmi_user_meta_expdeath% &2XP&f.
  - check:%cmi_user_meta_moneydeath%!=0! check:%cmi_user_meta_expdeath%==0! asConsole! cmi titlemsg [playerName] You died. %subtitle% &fYou lost &e&l%cmi_user_meta_moneydeath% &e⛁&f.
  - check:%cmi_user_meta_moneydeath%!=0! check:%cmi_user_meta_expdeath%!=0! asConsole! cmi titlemsg [playerName] You died. %subtitle% &fYou lost &e&l%cmi_user_meta_moneydeath% &e⛁ &fand &2&l%cmi_user_meta_expdeath% &2XP&f.
  - delay! 1
  - asConsole! cmi usermeta [playerName] remove moneydeath -s
  - delay! 1
  - asConsole! cmi usermeta [playerName] remove expdeath -s
```
