### DISCUSSION TITLE
Request: Additional rankup options

### DISCUSSION THREAD

**Discussion by Drewflav** [Zrips/CMI#172] [Feature Requests]
Hi Zrips

Would it be possible to add support for MythicMobs in your rankup options? The config could be organized as something like:

```
MyRank:
  Enabled: true
  DisplayName: "&8{&2MyRank&8}"
  DefaultRank: false
  AutoRankup: true
  RankupConfirmation: false
  PermissionRequirement:
  NextRanks:
  - MyRank2
  MoneyCost:
  ExpCost:
  Commands:
  StatsRequirements:
  McMMORequirement:
  MythicMobKillRequirement:
  - "Bandit:5"
  - "SuperCowMob:5"
```

This would practically make this an all-in-one plugin for RPG servers. Your consideration of this idea would be greatly appreciated!
