### DISCUSSION TITLE
Some feature requests

### DISCUSSION THREAD

**Discussion by p82183645** [Zrips/CMI#1823] [Feature Requests]
1. add /cmi data , Change item data
Uses: Convenient to make material package item
Example: DIAMOND_SWORD:5

2. add Maximum enchantment limit
Example: Efficiency III
The server does not appear to exceed the efficiency III

3. armor_stand edit gui , add remove Button ( Sometimes armor can't be removed )

4. /cmi reload , can reload SavedItems.yml 
Manual editing is more convenient

5. Kit condition , add play time condition
Example: This player has been playing for 7 days in total to receive this kit.

thank , please add

**Cmi Version (using`/cmi version`):** 8.6.3.2

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** 1.13.2

**Comment by mrfloris** [comment]
2. I believe you can set max limits in the config.yml
```
Enchanting:
  enchantLimits:
    # By disabling this, no limitation to enchanting will be applied
    Enabled: false
    MaxLevel:
      protection_fire: 4
      damage_all: 5
      arrow_fire: 1
      water_worker: 1
      arrow_knockback: 2
      loyalty: 3
      depth_strider: 3
      vanishing_curse: 1
      durability: 3
      knockback: 2
      luck: 3
      binding_curse: 1
      loot_bonus_blocks: 3
      protection_environmental: 4
      dig_speed: 5
      mending: 1
      frost_walker: 2
      lure: 3
      loot_bonus_mobs: 3
      protection_explosions: 4
      damage_undead: 5
      fire_aspect: 2
      channeling: 1
      sweeping_edge: 3
      thorns: 3
      damage_arthropods: 5
      oxygen: 3
      riptide: 3
      silk_touch: 1
      protection_projectile: 4
      impaling: 5
      protection_fall: 4
      arrow_damage: 5
      arrow_infinite: 1
```

3. if the armour stand is set to be invincible or invisible, it will be hard to remove, you can toggle those and then break it , this works for me. never had one i couldn't' break. 

5. yes pls! if not already possible.
