### DISCUSSION TITLE
[Implemented] Mystery Spawner option

### DISCUSSION THREAD

**Discussion by mrfloris** [Zrips/CMI#1962] [Feature Requests]
It would be quite fantastic now that CMI is capable of dealing with spawner (types) and settings, that it gets one more cool new feature. The ability to give a player a Mystery Spawner. I don't know if i can use the current system to achieve this (in that case, this turns from suggestion to support) but being able to run a console command to give a player a spawned called mystery spawner, that we can set to be a random one of a specific type..would complete the picture.
```
mystery-spawners: #allows the following types
- skeleton
- zombie
- silverfish
- panda
- fox
```

**Comment by mrfloris** [comment]
This is implemented: /cmi give spawner:random
it is a configurable whitelist via `cmilib/config.yml`
```yml
Spawners:
  # List of spawners to pick from while using spawner:random variable
  mysterySpawners:
  - skeleton
  - zombie
  - silverfish
  - panda
  - fox
 ```
