### DISCUSSION TITLE
Add blacklist for /hat

### DISCUSSION THREAD

**Discussion by blek-id** [Zrips/CMI#2174] [Feature Requests]
**Description of feature/improvement request:**
Can we add a list of items that we should whitelist / blacklist to be able to put on /hat?
---
### Detailed explanation of what it should do, when and in what situation: ###
Config format should look like this
```yaml
Hat:
  # List of materials to block from being placed on head with /hat command
  BlackList:
  - diamond_chestplate
  - diamond_helmet
  - dirt
  - glass
  # When set to true, black list becomes whitelist and will allow placing material defined in blacklist only
  BlackToWhiteList: true
```
### Basic explanation as to why this feature is needed and/or useful to have: ###
I currently have a plugin that could make a custom item with custom stats. Players would exploit /hat and use something that shouldn't be placed on their hat. For example: Applying a chestplate on their head with /hat, which would give the player a lot of extra defense from the plugin.

And I think there's a lot of Whitelist system already implemented on other features for CMI, such as scavange, and GroundClean. So I think adding this would be easy (I hope)
