### DISCUSSION TITLE
Off Caps Lock in chat filter

### DISCUSSION THREAD

**Discussion by Fiks75** [Zrips/CMI#2764] [Feature Requests]
Please add Caps Lock protection to the chat filter.

So that players can not write in capital letters.

**Comment by Va1a** [comment]
you can add this yourself... chat filters are customizable. if you're not sure how to use regex, there are numerous tutorials online.

**Comment by CloudeLecaw** [comment]
This allready exists...
 ```
  Caps:
    # When nebaled we will try to prevent chat messages with multiple capitalized letters by defined criteria
    # Can be bypassed with cmi.chatfilter.capbypass permission node
    Filter: true
    # Defines amount of letters we can ignore
    # For example ':DDD' would be made of 2 letters with 3 capitalized letters which would make it 75% capitalized
    IgnoreUnder: 6
    # Amount in percentage of capitalized letters we should not cross over.
    # In example 'GOOD thing' would be 4 capitalized and 5 not, spaces gets ignored, whic makes it 44% capitalized and passes check
    Percentage: 75
    # List of commands you want to perform when player uses too many caps
    Commands:
    - asConsole! cmi titlemsg [playerName] CAPS-Warnung&f:&f \n&f&lKlemmt deine CAPS-Taste?.....-in:20
      -out:20 -keep:30
    # List of messages, excluding color codes, player can use even if it 100% capitalized
    WhiteList:
    - AFAIK
    - AFK
    - BRB
    - IMHO
    - OMG
    - ROFL
    - ROFLMAO
    - LQTM
    - LSMH
    - LMHO`
 ```
