### DISCUSSION TITLE
Add command editing to scheduler

### DISCUSSION THREAD

**Discussion by glorying16** [Zrips/CMI#3309] [Feature Requests]
It would be great to be able to edit the announcer in the schedule.yml with ingame commands. This would allow my staff to be able to make edits as needed, without needing console access. 

Something like /schedule announcer add|remove|edit blahblahblah. There could be a corresponding number to each message making it easier to select for removing or editing. Or even JSON editing. Perhaps also have a preview option, to list out all the messages and how they look?

**Comment by CloudeLecaw** [comment]
pls addmore gui thx........
lets see we need command for alias, eventcommands, interactiv commands, modules, config, lanfgile, playtimerewards, schedules, tablist, worth and customtexts..
.
.
.
lol really.. the shedueller..
.... it was allready a bit overmade that he created one for customalias to owners dont need to do fileediting anymore...
a bit of textediting cant be wrong and the rest is jsut a /cmi reload can also customtexts.

scheduler should not be able to create ingame. and an announcer u can create in the shedueler really easy by yourself...

```
Announcer:
  Randomize: true
  Enabled: true
  Delay: 300
  Repeat: true
  Commands:
  - msg! [allPlayer] There is so much to do
  - msg! [allPlayer] Meassage 2
  - msg! [allPlayer] Meassage 3
```

**Comment by glorying16** [comment]
I could be reading into this, or just not understanding from some of the broken english, but that seemed like a fairly hostile comment. I am simply making a "feature request" which is part of the development of this plugin. Zrips can add and not add what they want, its their choice, but that doesnt mean I (or others) cant ask for a feature. And, though I dont know much about developing a plugin, I dont feel im asking for a huge thing. If I knew how to do it myself I would, as im sure most people would with any feature of any plugin. I also dont see where I asked for GUI...

As I said in the original post, I would like my staff to be able to make these edits themselves (with chat based commands) without me having to do it personally. I do not just give out console access, and I do not want to. But we run events that change phases on specific days and the announcer lets the players know about these changes, and serve as reminders. These would be part of a normal auto broadcast, or "scheduled announcement". Unfortunately I am not always able to be here to change it when it needs to be changed, seeing as I work a fulltime, and part time job, and do occasionally like to do things outside of the server and work, like spend time with my family. I obviously know about the announcer because im asking for a change to be made to it. Im personally not asking for command support to all of the scheduler because I personally dont see a need for it other than the announcer. Which honestly, the announcer could be separated from the scheduler if that was an issue. Most of the suggestions I made were based off of an old (and obsolete) super basic plugin that we used before. Which seeing as its obsolete, is why I now have a need for the feature. Of course like most, I would rather use less plugins, and have smaller features incorporated into larger plugins.

**Comment by CloudeLecaw** [comment]
What i mean is there is allready an announcer in the Shedule u just need to enable it
look inside shedulers.yml and simpls add this

```
Announcer:
  Randomize: true
  Enabled: true
  Delay: 300
  Repeat: true
  Commands:
  - msg! [allPlayer] Lucky Da today free gift for all
  - msg! [allPlayer] Have you ever tried the help &6/help
  - msg! [allPlayer] If u got stuck dont be shy to ask an admin or mod for help
```

When you reload CMI u have an announcer that is Announcing all 300 secounds one of the lines listed in commands, this also can be broadcasts if you like this more.
You can add as much lines as you want to this announcer. these 3 are just to show the example

You are 100 times faster if u edit the file then trying to remove/add old/new announcerwith a command
