### DISCUSSION TITLE
Add world specific command warmups

### DISCUSSION THREAD

**Discussion by Feeriix** [Zrips/CMI#3544] [Feature Requests]
**Description of feature/improvement request:**
Define a command warmup to a specific world.
---
### Detailed explanation of what it should do, when and in what situation: ###
Command warmups should apply to specified world in config. 
Example config:

```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - tp:7:false
  - back:7:true
  - cmi spawn:10:false:world
  - cmi home :3:false:world_nether
  - cmi home :15:false:world_the_end
```
