### DISCUSSION TITLE
Tablist Sorting based on Group

### DISCUSSION THREAD

**Discussion by Ayymoss** [Zrips/CMI#3571] [Feature Requests]
**Description of feature/improvement request:**

---
I want the ability to sort players based on their group list and would rather not use some 3rd party plugin when CMI does 90% of the TAB list functionality I want, except for sorting.

You even have `cmi.tablist.X` except there's no useful way to use this because you can't do like `%cmi_tablist_sort_by_weight%` or something.

Please allow us to sort the tablist by `cmi.tablist.X` permission or some other method that's in-house.

https://i.imgur.com/hFYqTG5.png

**Comment by thecenters** [comment]
I second this.

**Comment by CloudeLecaw** [comment]
Yeah i know what you mean you want a sorted tablist where owners and admins are listed first andnmay mods after and after this may Vips and players at the end. Right? Maybe a hook witch the permission system would be possible to sort by your permission groups.  This also may be a nice solution then sorting with the current tab group permission.

**Comment by Ayymoss** [comment]
> Yeah i know what you mean you want a sorted tab list where owners and admins are listed first andnmay mods after and after this may Vips and players at the end. Right? Maybe a hook witch the permission system would be possible to sort by your permission groups. This also may be a nice solution then sorting with the current tab group permission.

There's already a permission node in CMI "cmi.tablist.X" replacing X with the weight you want. It has no use from what I can tell.

Give each group a different weight.

if there was some placeholder %cmi_tablist_sort_by_weight% which you put before your name prefix in `PlayerName` in TabList, then easy. Done. 

I don't mind how it's done, but it makes no sense to me to go out of my way to get a 3rd party plugin when this does 90% of the functionality already.

**Comment by CloudeLecaw** [comment]
cmi.tablist.X is a permission that allows you to have differnt differnt tabs design to each group.
its no weight. ifa player has more then one ID (so like admins with '*' permission then the biggest number is taken. so i recomment to define the admin tab with the highest number.
You see this feature has nothing to dowith players weight in a general tab. this would be a new feature and i also would like to welcomed this to have it to sort the players in the tablist :)
Take a look into the tabList.yml for now may you find a nice design for your admins
The numbers behind the numerbs are animations numbers.
so you can change the design of a tab from Design1 to an other Tabdeisgn jsut in one group. like
a litte animation. you can define as much animtionnumbers as wanted for each group for each section
```
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 1
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: true
    OnTeleport: false
    OnNickChange: true
  # When set to false we will not add header text to tablist
  addTabListHeader: true
  # When set to false we will not add footer text to tablist
  addTabListFooter: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '[playerDisplayName]'
    Header:
      '1':
      - '&3------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&3------------------------------------'
      '2':
      - '&2------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&2------------------------------------'
      '3':
      - '&1------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&1------------------------------------'
    Footer:
      '1':
      - '&1------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&1------------------------------------'
      '2':
      - '&2------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&2------------------------------------'
      '3':
      - '&3------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&3------------------------------------'
  useGeneralName: false
  # When this set to true, in case you dint defined PlayerName, Header or Footer in GroupFormat, then default one from GeneralFormat will be used
  useGeneralHeader: false
  useGeneralFooter: false
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  GroupFormat:
    '1':
      PlayerName: '&2{&r[playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'

```
permission cmi.tablist.1 would be group players maybe
permission cmi.tablist.2 would be group admins maybe
So players and admins see a differnt tab :)
