### DISCUSSION TITLE
Warp create Fee

### DISCUSSION THREAD

**Discussion by mark-sheremeta** [Zrips/CMI#3579] [Feature Requests]
**Description of feature/improvement request:**
The ability to add a fee for creating a warp

**Comment by mercurialmusic** [comment]
You can kind of do this already by using a [custom alias](https://www.zrips.net/cmi/commands/custom-alias/) with [specialized commands](https://www.zrips.net/cmi/commands/specialized/) that handle the fee. It's not a perfect solution since in order to create the warp in the first place they would need the permission (which would also then allow them to set the warp normally) but if you disable the default `/setwarp` alias in Alias.yml (so that they'd have to use `/cmi setwarp` in order to get around the fee, which is effective if they're not aware of that) then set the alias you want along with the specialized commands in the CustomAlias.yml. Setting that warp creation alias to something other than `/setwarp` might further throw them off the scent. 

This is such an edge case otherwise that it seems unlikely to be added. Fair number of security issues giving regular players access to warp admin commands. Keep in mind this will still open the warp GUI for them upon creation. If you do implement I'd highly recommend using the limitation of the number each user can create: cmi.command.setwarp.[anypositivenumber].

**Comment by CloudeLecaw** [comment]
Your wrong. You dont need to give them the permission to it. You also can define a command to be executed in the customalais as op and with the moneycost to be executed. If you execute a command with bypass the permission

to limit amount of warps a player can ahs use
**cmi.command.setwarp.[anypositivenumber]** – Allows to have defined amount of warps

Here a little example for the customalais setwarp with a cost of 50 Dollar
```
CustomAlias:
  setwarp:
    Cmds:
    - hasmoney:50#! msg! [playerName] You dont have 50 Dollar to create a warp.
    - hasmoney:50! !bperm:cmi.command.setwarp cmi setwarp $1
    - hasmoney:50! msg! [playerName] Your warp with name $1 has beed created.
    - hasmoney:50! asConsole! cmi money [playerName] take 50 -s
```
only reason here: player can execute command if he has the money but allready reached hit limit - hen no warp will be created but take the money

dont forget to disbale setwarp in alias.yml
as admin for free warp use /cmi setwarp then or creat a new alias for it :)
to use the command the player needs: cmi.customalais.setwarp
.
.
.
.
what else would be usefull? not to have a single setwarp cost
to have a list where you can list all possible commands for money requierments
this could look like this:

```
CommandsWithMoneyCost: # define it with - command-moneycost:[value]
# example - cmi heal-moneycost:30
# admins can bypass with cmi.bypass.commandmoneycost
 - cmi heal-moneycost:30
 - cmi setwarp-moneycost:50
```
_note this is a sugestion not a allready working feature_
