### DISCUSSION TITLE
Custom permission in portals

### DISCUSSION THREAD

**Discussion by Arkobat** [Zrips/CMI#3636] [Enhancement]
## Custom permission in portals  
Currently, we have a `true/false` option to use permission in portals.
What I suggest, is access to have custom permissions, instead of `cmi.command.portal.<portalName>`
The way I suggest this implementation, is similar to the way it works now, but instead of a `true/false` option, it should be a String.
The config would then look like something like, where we have 3 portals with same permission node:
```yaml
  EndPortal1:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
  EndPortal2:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
  EndPortal3:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
```

**Breaking current portals?**  
I'm aware that this will break existing portals. I therefore suggest that all new portals would be created with the default permission node, instead of true/false. (`requiresPerm: cmi.command.portal.<portalName>`)  
All old portals could either be renamed at first startup or have `true` fallback to de default permission node.

---  
### Properly unnecercery stuff  
As this is a suggestion, this is properly unnecessary, but I've supplied it regardless.
**Cmi Version (using`/cmi version`):** 8.6.20.6  
**Server Type (Spigot/Paperspigot/etc):** Paperspigot  
**Server Version (using `/ver`):** 1.13.2 (git-Paper-653)

**Comment by CloudeLecaw** [comment]
you are not asking for permission strings, your asking for a Portalbreaker for many servers ;-)
*joking* I see what your asking for. you want to designt some more portals into a group and then give
a single permssion to the group instead of each permission for each portal.
So here is a suggetion for you as an addition that should not break old existing portals like your idea would do this.

**Suggestion for your request:** - New Extansion for /cmi portals - portalGroups
like **/cmi portals group (add|delete|list) (portalname) (groupname)**
(**permissions: cmi.portals.group.add|delete|list**)

Example:
- You have Portals TestA and Portal TestB and TestC
- You just wanne give he users access to TestA and TestB with a single permission
- you type /cmi portals group add PortalPlayerGroup TestA
- you type /cmi portals group add PortalPlayerGroup TestB
- now TestA and TestB are in a group. All Players have access to this group with the permission
**_cmi.portals.group.PortalPlayerGroup_**

What are the befineits of this Kind of GroupManagement for Portals?
- You can define as much portals as you want in a group and even you have 20 portals in a group
- you can deny the useage of single portal even if he has the group permission for single players if needed.
- you dont breake other servers current portalsystems
- you can give the permissions to your groups so they can use all Portals of the group

In the **PortalsGUI** there should be a **new icon** "Group: this sould **show the Groupename** the portal belogs - none if its no group. maybe a placholder thing like %cmi.portal.groupname% or something like that.
The Portalconfig would changeto this look:
```
  EndPortal1:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true/false
    group: <groupName/none>
    informOnMissingPerm: true/false
  EndPortal2:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true/false
    group: <groupName/none>
    informOnMissingPerm: true/false
  EndPortal3:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true/false
    group: <groupName/none>
    informOnMissingPerm: true/false
```
in your case:
```
  EndPortal1:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true
    group: PortalEnd
    informOnMissingPerm: false
  EndPortal2:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true
    group: PortalEnd
    informOnMissingPerm: false
  EndPortal3:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: true
    group: PortalEnd
    informOnMissingPerm: false
```

What does this mean?
you created 4 permissions here.
cmi.portals.portal.endportal1, cmi.portals.portal.endportal2, cmi.portals.portal.endportal3 and cmi.portals.group.portalend
If you give someone cmi.portals.group.portalend he can use all portals of the group without needing the extra single portal permisions of each. but you can negate the singleonce for players
This allow you give someone acces to the portalgroup but still reject to a single portals by negating the singleporal permission. while all other players/permgroups have full access to all portals of the group
