### DISCUSSION TITLE
Multiple Condisitions for CMI EventCommands and Sheduler

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#3691] [Feature Requests]
```
joinServer:
  Enabled: true
  Commands:
  - check:%cmi_user_name%==Player1! cmi flyspeed Blueeyestar 5 -s
  - check:%cmi_user_name%==Player2||Player2! cmi flyspeed Blueeyestar 2 -s
  - check:%cmi_user_name%!=Player1||Player2||Player3! cmi flyspeed [playerName] 1 -s
```
The command should be executed on Join..ok therefor is eventcommands.yml.. fine
The first Check - Is it player1? If yes give flyspeed 5 - this will effect Player1
The secound Check - Is it player2 or player3? If yes give flyspeed 2 - this will effect Player2 and player3 but not player 1
The thrid check - is it NOT player1 or player2 or player3? if yes then give flyspeed 1 - this will effect all other players just not player1 player2 and player3

At the moment this does not work :(
at the momen everyone gets lfyspeed 1 execpt player 1 he gets flyspeed5 before...
i dont know  if this is a bug or a missing feature..
but you assumed to us the variable ==  so the others shoulld work too

https://de.wikibooks.org/wiki/Java_Standard:_Operatoren

I hope this can be added,fixed soon :)
