### DISCUSSION TITLE
/spawn and /warp warm-ups

### DISCUSSION THREAD

**Discussion by Srborjaa** [Zrips/CMI#3795] [Feature Requests]
**Description of feature/improvement request:** Warm-ups (like for the tpa and tpahere ones) for /spawn and /warp commands.

---
### Detailed explanation of what it should do, when and in what situation: ###  
It's been discussed in #3794 

### Basic explanation as to why this feature is needed and/or useful to have: ### 
With that feature **all the players' teleport commands** could have the possibility to be set a warm-up in the config or not.

**Comment by Zrips** [comment]
But you already have entire section for thing like that
```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: false
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
What else do we need? 
and just FYI tpa and tpahere have separate options because they are controlled in slightly different and more unique way, as for those commands we are applying warmup for tpaaccept command and not for request sending.
