### DISCUSSION TITLE
Exclusion of players from /whowas

### DISCUSSION THREAD

**Discussion by EthanTheYam** [Zrips/CMI#3820] [Feature Requests]
/whowas is always activating for every player who joins, with no exceptions. However this is also showing for any admin staff who have changed their name in the past to those with perms to /whowas.
---
### Detailed explanation of what it should do, when and in what situation: ###
Moderators and lower staff ranks have access to /whowas for moderation sakes and keeping track of players, however this also means any admin staff who have formerly changed their names, even if they're in vanish, are shown to join to these ranks despite having the permission 'cmi.messages.disablelogin'. Therefore it would be ideal to have /whowas not announce prior names if the player has the permission.
### Basic explanation as to why this feature is needed and/or useful to have: ###
It would allow the admin staff ranks to resume their duties without being disturbed by/exposed to being online to other players, meaning certain duties harder to fulfill.

**Comment by CloudeLecaw** [comment]
there is allready a whowas


> cmi whowas [playerName]
>permission: cmi.command.whowas
> Shows players previous names

you can setup that its shows on login of a player and this player also can see it if he has permission to it. others doesnt
i would setup a staff message here so all staff members get informed on login of players

```
# Checks and shows on players login if he have been changed hes name over Mojang
# Looks to be working only with online servers, duhhhh
CheckForNameChange:
  OnLogin: false
  AmountToShow: 3
  OnInfoShow: true
  # Do you want to perform commands
  PerformCommandsOnNewName: true
  # Command list to be performed in case player logs in with new name
  NameChangeCommands:
  - 'asConsole! cmi broadcast !&2[oldname] logged in with new name: [newname]'
```
something like
  - 'asConsole! cmi staffmsg &2[oldname] logged in with new name: [newname]'
