### DISCUSSION TITLE
Whitelist Worlds

### DISCUSSION THREAD

**Discussion by AlfreDGR** [Zrips/CMI#3838] [Feature Requests]
**Description of feature/improvement request:**

---
### Basic explanation as to why this feature is needed and/or useful to have: ###

In eventcommands you could add in the playerWorldChange section a list of worlds in which the assigned commands work. I say this because on my server I use it to remove the fly when they go to the nether world but of course if I have other normal worlds the fly is also removed and it would be a relief for them that they are not putting / fly all the time instead of only in the nether and in the end

**Comment by CloudeLecaw** [comment]
you can do this allready with a simple check before the command execution :)
Lets say you wanne a command that just get execued when someone joins the normal nether and end world by default this worldname of the main default world nether and end is world_nether and world_the_end
Look to your worldfolders if these names matched with your nether and end

```
playerWorldChange:
  Enabled: true
  Commands:
  - ifinworld:world_nether! cmi fly [playerName] false -s
  - ifinworld:world_the_end! cmi fly [playerName] false -s
```
you could try this one is first case

.
.
Also its a good idea to use a plugin like PerWorldInventory or Multiverse to manage what should happen when this world is entered (like loosing fly mode or gamemode , etc

Dont forget to close the request if this idea fits your needs :)
Because this usually works fine i dont think a whitelist is needed.
