### DISCUSSION TITLE
Dedicated Info Page for CMI Bungee

### DISCUSSION THREAD

**Discussion by SinsOfSolitude** [Zrips/CMI#3862] [Feature Requests]
**Description of feature/improvement request:**

A dedicated tab/page/section about the CMI BungeeCord plugin on zrips.net and spigot.org, which has more detailed information on how it works, what the features are and how to use it correctly.
---
### Detailed explanation of what it should do, when and in what situation: ###

The page should give detailed information on the exact features CMIB provides, that includes permissions, commands, config options, etc. Information on how the Bungee chat and Tab list works, if it can support placeholders, prefixes/suffixes from rank plugins such as LuckPerms, etc.

### Basic explanation as to why this feature is needed and/or useful to have: ###

Since BungeeCord is widely used, having a detailed information page on CMIB would be quite helpful, and could also attract new users. As currently there's barely any information on this, I am unable to to write up a more detailed list of things what the page should contain, and also unable to use CMIB to its full capabilities.

**Comment by mrfloris** [comment]
What I had already posted in the admin channel, but i can put it here as well so it can be found again:

It would be nice if there's a dedicated /bungee/ or /cmib/ page on zrips.net's CMI page
This way it can be explained what CMI-Bungee is, what it can (and not do). A quick example on how to set it up, if MySQL database(s) can be shared or not, and some basic BungeeCord commands (and permissions/placeholders).

The information it is a bit spread out, and is rather limited. People buy CMI and setup a Bungee network, hearing there's a Bungee addon for CMI to find out it's global chat and maybe not economy.

And then they are not sure how to use `cmi placeholders`,  `cmi checkperm bungee` or `cmi checkcommand bungee` to find bungee related stuff. 

The `cmi checkcommand` shows server, but there's of course also `/cmi bbroadcast`. (to name an example), it would be nice if other bungee related commands could be spit out if there are any. 
And the same for permissions.

**Comment by mrfloris** [comment]
Placeholders:
```
%cmi_user_bungeeserver%
%cmi_bungee_total_spawn%
%cmi_bungee_current_spawn%
%cmi_bungee_motd_spawn%
%cmi_bungee_onlinestatus_spawn%
```

Commands: 
```
cmi server [serverName] (playerName) (-f) (Connects [playerName] to bungeecord server)
cmi serverlist (Show server list)
cmi bbroadcast (!) [message] (-s:[serverName,serverName]) (Sends special message to all players on all servers)
cmi sendall [serverName] (Send all online players to target server)
(and through CMI chat: /msg, /r, /staffmsg, .. i assume?)
```

Permissions:
```
cmi.bungee.publicmessages.[servername]
cmi.command.server 
cmi.command.sendall 
```

config.yml:
```
  # Attention! This will require you to have CMI Bungee plugin which can be found at zrips.net
  # Or direct download https://www.zrips.net/cmi/
  # Do you want to enable private messaging over bungeecord
  BungeeMessages: false
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: false
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: false

BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: false
  # When set to true player names from entire bungee network will be included into tab complete
  NamesInTabComplete: false
```

Installation instructions: (from what i gathered)
- Buy cmi for the network
- install cmi on each server
- get cmi bungee jar and put it on the proxy
- configure cmi properly, use cmi chat, and enable bungee as per above config things.

I do not believe there's any modules.yml things that need to get enabled.

I have a FAQ entry on my personal github, that can also be found as a pinned msg on the zrips discord, but explains once cmi chat is installed properly, how to cmi bungee chat: <https://github.com/mrfdev/CMI/blob/master/Resources/FAQ/cmi-bungee.md>

FAQ:
```
- if i run 2 servers and they're not in the same network, do i need two licenses? yes, basically you do.
- if i run 3 servers and they're all on the same network, do i need three licenses? no, from what i gather that license covers the network, i dont know the official stance on this though
- is chat global? yes
- can i sync up economy on all servers? no, probably not
- can all the /warps be the same on all servers? not that i am aware of.
- are my inventories shared between servers? i doubt it, you probably need a bungee-inventory plugin dedicated to this
- can i use 1 database for all cmi instances? no, default is sqlite, use mysql, and make sure they all use a unique prefix. Using 1 user table for every server for example will very very very likely cause massive issues.
```
