### DISCUSSION TITLE
Make Votes to be able to reset every month

### DISCUSSION THREAD

**Discussion by KarlPro123** [Zrips/CMI#3945] [Feature Requests]
**Description of feature/improvement request:**

Right now, the vote counting module counts all the votes that player does without reseting any of them, however I'd quite like it, if every month, vote counts for every player could reset, so we could give out Extra Rewards for players each 10, 20, 30 votes etc.

---
### Detailed explanation of what it should do, when and in what situation: ###

It should reset the vote count for every player every month (start from 0).
Here's how it would look like

```
Votifier:
  # When set to true votifier votes will be counted for player
  CountVotes: true
  # When set to true the vote count for players will be reset each month (useful for giving players items every 10 or so votes in the ExtraRewards section)
  ResetMonth: true
```

### Basic explanation as to why this feature is needed and/or useful to have: ###

Its useful, because then we can give out Extra Rewards every 10, 20 or so votes, that player does (configurable of course).
