### DISCUSSION TITLE
Voting extra rewards do not seem to be given?

### DISCUSSION THREAD

**Discussion by dragontekgaming** [Zrips/CMI#3974] [Q&A]
**Question: **
I seem to be having a problem with players not getting their extra vote rewards. I'm wondering if I did this wrong, or if there is an issue?

```
Votifier:
  # When set to true votifier votes will be counted for player
  CountVotes: true
  # Number of votes one IP can make in last 24 hours
  # Set it to 0 to have unlimited amount
  MaxVotesInADay: 0
  # Cooldown between votes from same service
  # In most cases voting service will have its own cooldown setup
  # But if you need extra one to prevent rapid voting you can define time in seconds over here
  GeneralCooldown: 0
  # When set to false, commands on sucessfull vote will not be performed
  PerformCommands: true
  # Defines commands to be performed when player votes
  # Supports specialized commands and placeholders
  # [serviceName] variable can be used to insert address
  CommandsOnVote:
  - cmi msg [playerName] &eThank you for your voting on &5[serviceName], &6[playerDisplayName]!
  - crate givekey [playerName] vote 1
  # Keep it at false if you dont want to give out extra rewards
  ExtraRewardsEnabled: true
  # Commands will be performed when player collect determined amount of votes
  ExtraRewards:
    '21':
    - crate givekey [playerName] weekly 1
    '84':
    - crate givekey [playerName] monthly 1
    '50':
    - lp user [playerName] permission set deluxetags.tag.VoteBasic true
    '100':
    - lp user [playerName] permission set deluxetags.tag.VoteSilver true
    '500':
    - lp user [playerName] permission set deluxetags.tag.VoteGold true
    '1000':
    - lp user [playerName] permission set deluxetags.tag.VoteDiamond true
  # List of players to be excluded from top voter list
  ExcludeList:
  - None
```
CMI 8.7.6.0
git-Spitot-9639cf7-8fb6585 (1.16.1)
