### DISCUSSION TITLE
[Suggestion] Allow for rectangular random teleportation

### DISCUSSION THREAD

**Discussion by Tencryn** [Zrips/CMI#4044] [Feature Requests]
**Description of feature/improvement request:**

Currently, the random teleportation feature of CMI will only teleport players within a square (more specifically, a square donut). `MinRange` and `MaxRange` applies to both X and Z which is perfectly fine if your world is a square, however, mine is not. My world is a rectangle.

It would be nice to have, albeit optionally, `MinRangeX` `MaxRangeX` `MinRangeZ` and `MaxRangeZ`.

---
### Detailed explanation of what it should do, when and in what situation: ###

Take the following configuration:

```yaml
RandomTeleportation:
    world:
      Enabled: true
      MaxRangeX: 9500
      MinRangeX: 500
      MaxRangeZ: 5500
      MinRangeZ: 500
      ...
```

When performing `/rt` in `world`, it will teleport you to a location between `x:-9500 to +9500` and `z:-5500 to +5500` while excluding -500 to +500 on both axis.

Alternatively, as both minimum ranges are the same, you could write your configuration like this:

```yaml
RandomTeleportation:
    world:
      Enabled: true
      MaxRangeX: 9500
      MaxRangeZ: 5500
      MinRange: 500
      ....
```

This would take MinRange (which has no axis specified) and apply it to both X and Z. You could similarly do `MaxRange` without a specified axis to also apply to X and Z as is the current behavior.

### Basic explanation as to why this feature is needed and/or useful to have: ###

This improvement would allow for players to be able to randomly teleport within a given rectangle. My world is 20K by 12K in size, but currently the furthest I can teleport players is -12K to +12K on both axis as CMI doesn't support rectangles.
