### DISCUSSION TITLE
Can i somehow use the currency as way to buy items like a shop?

### DISCUSSION THREAD

**Discussion by QueenOfDancingStars** [Zrips/CMI#4078] [Q&A]
**Question: **
I've seen other servers have signs on a chest that you can click, and it'll automatically take money out of your balance, and you get the item.
I want to set up a better way to buy things in shops, so it this possible?

**Comment by CloudeLecaw** [comment]
You speak of plugisn like ChestShop and ShopChest
This is not a part of cmi ;)

what you can do with CMI:

Attach commands to item in hand: (executeable on left,right clickck, with limited useage or at constume, or endless usegae

design interactive commands that are attached to signs or any other items/blocks/entities in the world
what they could do to simulate a shop...
- Check if you have X amount of money - then take Money and give you X amount of item
- Check if you have X amount of item - then Take the Item and give you X amount of money

These can be used as AdminShop   NOT as Playershops

Example for a SellSign - 64 Emeralds
```
Sell64:
  Locations:
  - world;400.0;77.0;518.0
  Commands:
  - hasitem:emerald-64! msg! [playerName] &fYYou sold &a&l64 Emeralds&7 for &e&l64 Dollar&f.
  - item:emerald-64#! cmi money give [playerName] 64 -s
  - msg! [playerName] &fYour New balance is &e&l%cmi_user_balance_formatted%&f.
  SignLines:
  - '&lSell:'
  - '&a&lEmerald x 64'
  - '&lGet:'
  - '&6&l64 Dollar'
  Public: false
  ReqPerm: false
```
Example for a buy sign - Mending book
```
BuyMendingBook:
  Locations:
  - world;93.0;71.0;393.0
  Commands:
  - hasmoney:1444.99! msg! [playerName] &fYou bought a &c&lMendingbook&7 for &e&l1499,99 Dollarr&f.
  - moneycost:1499.99#! cmi give [playerName] enchanted_book {StoredEnchantments:[{id:mending,lvl:1}]}  1
  - msg! [playerName] &Your new balance is &e&l%cmi_user_balance_formatted%&f.
  SignLines:
  - '&lEnchantbooks:'
  - '&7&lMending'
  - '&lPrice:'
  - '&6&l1499,99 Dollar'
  Public: false
  ReqPerm: false
```

And here are Buy/Sell sign like known from admins shops of other plugins *lol*

```
BuySellEneralds32:
  Locations:
  - world;-36.0;65.0;318.0
  Commands:
  - click:left! hasmoney:32! msg! [playerName] &fYou bought&a&l32 Emeralds&7 for &e&l32 Dollar&f.
  - click:left! moneycost:32#! cmi give [playerName] emerald 32
  - click:left! msg! [playerName] &fYour new balance is &e&l%cmi_user_balance_formatted%&f.
  - click:right! hasitem:emerald-32! msg! [playerName] &fYou sold &a&l32 Emeralds&7 for &e&l32 Dollar&f.
  - click:right! item:emerald-32#! cmi money give [playerName] 20 -s
  - click:right! msg! [playerName] &fYour new balance is &e&l%cmi_user_balance_formatted%&f.
  SignLines:
  - ''
  - '&a&lEmderlds 32'
  - '&lB:32 | S:20:'
  - ''
  Public: false
  ReqPerm: false
```
