### DISCUSSION TITLE
Cooldown command

### DISCUSSION THREAD

**Discussion by WIBOR2002222** [Zrips/CMI#4079] [Q&A]
Hello, how can I put a 3 seconds cooldown before a player teleports with, for example, /home or/spawn ? During these 3 seconds, the player will not be able to move so no he will not be teleported

**Comment by CloudeLecaw** [comment]
you dont mean cooldown

you mean warmup :)

ou have a whole section in config for warmups

```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: false
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
