### DISCUSSION TITLE
Improvement of vanish

### DISCUSSION THREAD

**Discussion by WIBOR2002222** [Zrips/CMI#4101] [Feature Requests]
Hello, is it possible to make a system for when a staff member is in vanish, he can right click on the player to see his inventory?

Is it also possible to make it easier for staff members to switch to spectator gamemode (for example, setting a double shift in vanish and it passes the person in spectator gamemode)

**Comment by CloudeLecaw** [comment]
I like the idea of this rightclick thing. But at the Moment there answer is.. 
No its not ;) your statt members should be simply allow to have cmi inv others permission. And for faster setting to Game Mode i recimment to create short custom alias for gm 1 2 3 0 for them. The Minecraft Code has no real targeting for this klick rightclickplayer think. The player is no Block.

So without massives New lines of Code that add this Feature it will not be possible. You really think Zrips has this much amount of free time for this at the Moment?

**Comment by WIBOR2002222** [comment]
Ok, no problem, it's only a suggestion

**Comment by CloudeLecaw** [comment]
Well maybe Zrips found the time on time :)

**Comment by broken1arrow** [comment]
You can use a item for this (is not the nice´s way to do it, but is faster an use command).

**Comment by CloudeLecaw** [comment]
A good idea. Create a kit or custom alais that gives the items. There you can define different commands on left and right click. Also you can setup permission so only your staff can use it an get the item

**Comment by broken1arrow** [comment]
> 
> 
> A good idea. Create a kit or custom alais that gives the items. There you can define different commands on left and right click. Also you can setup permission so only your staff can use it an get the item

Only downside is if spectator can go back to creative again or not (if the item still working in spectator).

**Comment by Hazugg** [comment]
They would also have to improve the vanish system, since at the moment there are players who can tell, for the reason that animals or mobs can look at you even when you are in vanish

**Comment by CloudeLecaw** [comment]
What mobs does this? This really should be fixed then, because you should not get targeted in vanish like in. Specatormode.. 
So the Mob target you in gm 1 too?

**Comment by broken1arrow** [comment]
> 
> 
> What mobs does this? This really should be fixed then, because you should not get targeted in vanish like in. Specatormode..
> So the Mob target you in gm 1 too?

In gmc mobs and villgers target you (not try latest version). gmsp mobs do not target you,what i try out (not test in latest version yet).

**Comment by Hazugg** [comment]
I have tested it with most animals and as you will see in the photos ps I am in vanish and they can still see me, it is how the players discover that I am watching them, I have not tried it with most of the mobs but how will you see the zombies in the image tbm can still  see me, and if tbm happens the same in gm 1, but that does not worry me more than anything is the vanish that should not

![image](https://user-images.githubusercontent.com/31551514/91636642-d1739c80-e9c7-11ea-82ed-177ae7133d92.png)
![image](https://user-images.githubusercontent.com/31551514/91636656-ec461100-e9c7-11ea-8be2-148a0ed6086b.png)
![image](https://user-images.githubusercontent.com/31551514/91636665-05e75880-e9c8-11ea-9bb0-bc540ab4e901.png)
![image](https://user-images.githubusercontent.com/31551514/91636677-1f88a000-e9c8-11ea-8cfc-914fd5218e4d.png)
![image](https://user-images.githubusercontent.com/31551514/91636714-742c1b00-e9c8-11ea-8c57-82a7dcc126e8.png)

**Comment by CloudeLecaw** [comment]
ok that is really strengh
what your vanish section is tellinh:
here i could post mine:
```
Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: false
    PrivateMessages: false
    relogDisable: false
    noMessages: false
    fakeJoinLeave: false
```

i thought it has to do with     mobAggro: false  or  interaction: false
but maybe im wrong. may this needs a whole need option for vanish or maybe it cant befixed?
Lets see what Zrips will sa to this :3
