### DISCUSSION TITLE
/sell command to OPEN menu instead of selling item in hand

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#4271] [Feature Requests]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you please add option or add is as default to open menu (gui - sell gui) via /sell command?

### Basic explanation as to why this feature is needed and/or useful to have: ###
The problem is that my player wanted to try it, executed /sell and it sold him Netheritte pickaxe with silk touch.... He though that it will opens menu. I think that this will be better solution than instantly selling item, atleast config option for it.

**Comment by CloudeLecaw** [comment]
a more simple solution to not effect all servers with this single wantage is creating a custom alias and disable default alias.


edit in Alias.yml
```
  # /cmi sell $1-
  /sell: false
```

add to CustomAlias.yml
```
  sell:
    Cmds:
    - cmi sell gui
```

now all players that use /sell get the sell GUI opened... well...done^^

renember: they need permission `cmi.command.sell.gui`

**Comment by bobhenl** [comment]
I can't, because then /sell hand, /sell blocks etc. stop work.

**Comment by CloudeLecaw** [comment]
U havent thought full about it
Just create a secound custom alais called /sell hand  and a thrid /sell blocks  that executes the commands for /cmi sell blocks and /cmi sell hand its just Importent that these come before the /sell custom alias. Didnt u know that custom alais can have arguments? So you can have a /sell, /sell hand /sell blocks and all do different things + all are tab completed
So at the end u can use /sell [TAB] with these tree custom alias. 
On our server i Designed the full /help with all its Arguments that way
Should i write you the sell custom aliases for you sell Problem or wanne try it alone first? :)

**Comment by CloudeLecaw** [comment]
So here is is, add to custom alais:

add to CustomAlias.yml
```
  sell all:
    Cmds:
    - cmi sell all
  sell block:
    Cmds:
    - cmi sell blocks
  sell hand:
    Cmds:
    - cmi sell hand
  sell same:
    Cmds:
    - cmi sell same
  sell gui:
    Cmds:
    - cmi sell gui
  sell normal
    Cmds:
    - cmi sell
  sell:
    Cmds:
    - cmi sellgui 
```

after server restart its full tabcompleted=)

**Comment by bobhenl** [comment]
Hey it almost work, except it's not tab completed 😅 /sell command is, but arguments aren't

**Comment by CloudeLecaw** [comment]
Maybe because i forget the : at /sell normal.?
Usually it should i will build this one in an hour when i am at home and check where is the problem, because it should work that way.

Like i said i builded a whole /help with all subsites that way i will tell you if i see any issues when i have rebuilded the sell one at home.

**Comment by bobhenl** [comment]
I noticed you forget it but I added it there before and it still didn't work.

**Comment by CloudeLecaw** [comment]
Dont worry i will check. Maybe its just because of the disabling in alias.yml i will check what wents wrong here 🙃
At the moment i havent tested the sell was just write it in memory how i did it with /help

**Comment by CloudeLecaw** [comment]
ok i solved the problem *lol* u wont belive it what it was^^ well i will post you the result

Alias.yml
```
  #  
  # /cmi sell $1-
  /sell: false
```
Customalias.yml
```
  sell all:
    Cmds:
    - asPlayer! cmi sell all
  sell block:
    Cmds:
    - asPlayer! cmi sell blocks
  sell hand:
    Cmds:
    - asPlayer! cmi sell hand
  sell same:
    Cmds:
    - asPlayer! cmi sell same
  sell gui:
    Cmds:
    - asPlayer! cmi sell gui
  sell normal:
    Cmds:
    - asPlayer! cmi sell
  sell:
    Cmds:
    - asPlayer! cmi sell gui
```

Problem was u need to extra write it asPlayer! else it cmi will take its own process on it form CMI and is searching what is allowed for cmi sell and when you enable it in alias.yml then cmi knows /sell has the strucute of cmi sell. you walk arround this by adding  asPlayer! infront of it

i noticed this when looking at my help designs that i used it also there infront in each command like. and then i was renembering  why ;)

**Comment by CloudeLecaw** [comment]
Oh one last thing may its usefull may not
If you wish that when someone writes something behind help that is not in the list above like **/sell MyDreamBlocks** and the gui should open in that case then simply add the ? to the last sell custom alias. ( so change sell: to sell ?: )
normal /sell still works then. The little bad thing is that the ? is also shown then as chooseable argument in the TABcompletation
but if if its choosen then it opens the GUI too.
```
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui
```

**Comment by bobhenl** [comment]
Yeah, thank you very much.

But it's a bit weird when you use for ex.   /sell MyDreamBlocks  then it doesn't open GUI normally, but use normal /sell. Why, when there's set:
```
  sell:
    Cmds:
    - asPlayer! cmi sell gui
```
It's a little bit weird, but ok, I added there ?

**Comment by CloudeLecaw** [comment]
if your using "/sell ?": you dont need the extra alias "/sell"
its important that /sell ?  is the last of the /sell customaliases

**Comment by bobhenl** [comment]
Yeah I know, but I meant when if I don't use sell ?, then it's weird it doesn't open menu when you write there something.

**Comment by CloudeLecaw** [comment]
when you have /sell ?  and you u writee /mydreamblock then gui should open because the ? stand for "everthing" this is why its important that this is the last /sell customalais because it checks the once above first if you use for example /sell normal
```
  sell all:
    Cmds:
    - asPlayer! cmi sell all
  sell block:
    Cmds:
    - asPlayer! cmi sell blocks
  sell hand:
    Cmds:
    - asPlayer! cmi sell hand
  sell same:
    Cmds:
    - asPlayer! cmi sell same
  sell gui:
    Cmds:
    - asPlayer! cmi sell gui
  sell normal:
    Cmds:
    - asPlayer! cmi sell
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui
```
that is the one i use in my test.
try /sell mydreambooks  the gui should open

**Comment by bobhenl** [comment]
And now still question... Do you think there could be added option to disable selling items with enchantments and special tags like name and lores.... or should I remove for now way to sell tools, weapons and armors? If still players use /sell all, it's for VIP and they use it sometimes, but I don't know, what's better, if the better will be when I remove these items from worth.list, or if I replace sell all with sell blocks like you mentioned.

**Comment by CloudeLecaw** [comment]
someone asked this questen before.  in a anther thread, at the moment the normal sell command cant do that because it used just vanilla names :\

this specially is annoing when someone usses the sell all commands and forgot that he has imporant items in his inventory

like in the other thread i just can recommand here to just give them the GUI, and sell blocks permission.
All items that you dont have in worth.yml cant be slod because they count as worthless. (this would be an option if you still allow sellall and also prevent them by misstakeing enchanted gear into the GUI while using the gui)

So i recomment taking gear from worthlist and maybe allow them to use /cmi scavenge for free to may get back materials that they can sell then.

Maybe Zrips will add a bit more here on day that we can handle this better.
and prevent selling of special items specialy with enchants and lores like a permission we can negate

**Comment by bobhenl** [comment]
Or maybe confirmation when when using /sell all as warning

**Comment by CloudeLecaw** [comment]
this also would be a nice idea if this could be added

**Comment by CloudeLecaw** [comment]
If you dont use it at the moment what about blocking selling of gear (remove from worth.yml) and give them

access to /cmi scavange
there they can enter their items in a gui and get back some materials if they want. (and of curs sell these then)
also you can deinfe the price and chances for it in the config
Scavange is a really flexible tool in its options

```
Scavenge:
  ItemBreak:
    # Defined percentage for item to break when salvaging it
    # Value can be from 0 to 100, where 100 means that each time player extract enchant, item breaks
    # This can allow player to extract enchantments without breaking item itself
    # Set it to 100 if you want to always break item
    # Keep in mind that broken item will go throw ingredient return process
    # Attention! Items without enchants will have 100% break chance
    Base: 8.0
    # Adds extra chance to break item depending on how many enchants item has
    # In example having base chance of 8% and having this set to 2 while having item with 3 enchants will result into 8+(2*3)=14% chance to break item
    ForEachEnchant: 2.0
    # Adds extra chance to break item depending on enchant level
    # This will take into consideration enchantment max and current levels
    # Having this set to 7.5 means, that enchantment at max level will have 7.5% extra chance to to break item
    # But if you have sharpness 2 which has max level of 5, then only 3% fail chance will be added
    ForEachEnchantLevel: 2.0
    # Defines in percentage a max chance to break item when extracting enchants
    # This can limit chance to particular one in case it gets to 100% and it would always break
    MaxBreakChance: 100.0
    # Value between 0 and 100 which defines extra fail chance when items doesnt have max durability
    # Having this set to 50 will mean that item at 1 left durability will have fail chance increase by 50%
    # Items which are not damaged will not experience any fail chance increase
    BreakDurabilityCheck: 50.0
    # When set to true, items durability will be taken into consideration when extracting ingredients
    # In example if item has 100 max durability and current is at 50, then only half of ingredients will be considered for extraction
    # This doesnt mean that player gets 50% of them, it only means that half of posible ingredients will go throw IngredientReturn process
    DurabilityCheck: true
    IngredientReturn:
      # Defines in percentage a max chance to return ingredients of item if it fails extraction process
      # This will apply for each ingredient that item has
      # Recipe to make that item should exist in database, or it will not return any ingredients
      Base: 25.0
  EnchantExtractionFail:
    # Adds base chance to fail enchantment extraction
    # When enchantment fails, player will not get enchant book with appropriate enchantment
    Base: 10.0
    # Adds extra chance to fail enchantment extraction depending on enchantment level
    # This will take into consideration enchantment max and current levels
    # Having this set to 75 means, that enchantment at max level will have 75% chance to fail extraction process
    # But if you have sharpness 2 which has max level of 5, then only 30% chance to fail will get applied
    # While enchants like Aquaaffinity will always have max fail chance as you can only have it at level 1
    ForEachLevel: 10.0
    # Defines in percentage a max chance to fail enchantment extraction
    # This can limit chance to particular one in case it gets to 100% and it would always fail
    MaxFailChance: 75.0
    LevelLower:
      # Defines a chance lowering enchant level if it fails extraction
      # This is secondary step when extraction fails and will only apply when it does
      # If Enchant is at level 1 already, then player will not get enchanted book at all
      # If you want to avoid lowering level of enchant when it fails extraction, set this to 100
      # If you want to always lower level down when extracting enchantments, then set EnchantExtractionFail.Base to 100 and set this to 100
      Base: 50.0
      # Will adjust level lowering chance depending on enchant level to defined max amount at max level
      # This will mean that higher levels will have higher chance to be lowered
      ForEachLevel: 5.0
      # Will adjust level lower chance depending on enchant level to defined max amount at max level
      MaxChance: 75.0
  Cost:
    # Defined base cost of extraction. Set to 0 if you want to make it free
    Base: 100.0
    # Extra cost which depends on enchantment worth which can be defined with /cmi setenchantworth 
    # This value is in percentage from worth value of that each enchantment and item
    # So if you have base cost of 100, extra cost of 5% and you are trying to extract sharpness 5 which worth is 1000 and item sell hand worth is 100, then you will have to pay 155 for extraction process
    Extra: 5.0
  # List of materials to block from being scavenged
  BlackList:
  - diamond
  - ironingot
  - goldingot
  - coal
  # When set to true, balck list becomes whitelist and will allow scavanging of items defined in a blacklist only
  BlackToWhiteList: false
  # When set to false while player have open scavange UI they will not be able to pickup item from ground
  AllowItemPickups: false
```
