### DISCUSSION TITLE
ramdom timed scheduler timings needed

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#4276] [Feature Requests]
We want to annaonce a random schedule announcer that broadcasts once each day. 
We want the broadcasts to be posts in random intervalces therefore wer would need something like
a random timer or random preform.
This would need two things
1. allow the cmi random placeholder for Delay to have a random time where it reacts.
2. a resetOption where you can set when this timer should be reseted

it could look like this
This example shows a broadcaster that gets execued between 12 and 24 hours.
The counter for this gets reseted each day at 20:00
```
RandomAnnouncer:
  Enabled: true
  MinPlayers: 1
  Delay: %cmi_random_43200_86400%
  Repeat: true
  ResetOn:
    '1':
      Hour: 20
  Randomize: true
  Commands:
  - broadcast! &eRules can be found at &e/rules
  - broadcast! &eKits can be accesed with &e/kits
  - broadcast! &eIf you need help, ask staff
  - broadcast! &eAdvertisement of other servers will be punished
```
With this there could be many many things made like
Somethine Each hour but starting in a random interval of 5 and 40 minutes.
