### DISCUSSION TITLE
Flight Charge world blacklist/whitelist, or something similar

### DISCUSSION THREAD

**Discussion by DaveDevil** [Zrips/CMI#4373] [Feature Requests]
**Description of feature/improvement request:**

Flight Charge world blacklist/whitelist, or something similar
---
### Detailed explanation of what it should do, when and in what situation: ###

A config section in the config, or a specific permission checked every second, that can allow the server to enable/disable the flight charge in certain worlds, or inside regions (in the case of a permission)

### Basic explanation as to why this feature is needed and/or useful to have: ###

I do not want players to fly in certain areas/worlds

**Comment by kawalain** [comment]
Sorry for doing necroposting but I found out this can be done by permission context and `eventCommands.yml`

first, you have to limit `cmi.command.flightcharge` permission per world. because player can ignore `flyc` status with charging from zero.

if you are using a LuckPerms try this command:
```
> lp group default permission set cmi.command.flightcharge true world=allowed_world
> lp group default permission set cmi.command.flightcharge true world=allowed_world2
...
```

and add this commands to `playerWorldChange` in `eventCommands.yml`

```yaml
playerWorldChange:
  Enabled: true
  Commands:
  - cmi flyc [playerName] false -s
  - ifinworld:allowed_world! cmi flyc [playerName] true -s
  - ifinworld:allowed_world2! cmi flyc [playerName] true -s
```

and reload cmi with `cmi reload` command.

walla it worked!
