### DISCUSSION TITLE
Regex Chat Filter - Multi Pass

### DISCUSSION THREAD

**Discussion by Leo-Alexa** [Zrips/CMI#4396] [Feature Requests]
**Description of feature/improvement request:**
Regex Chat Filtering Improvements - Catchall
---
### Detailed explanation of what it should do, when and in what situation: ###
Currently the way the Regex chat filtering works within CMI, is it runs one pass over an enabled filter and if it hits a match, removes any instances of this matching within the text. This then goes onto the next block filter. This results in words that should match potentially getting missed if simply placed on multiple lines of Regex separated by -.

Example:
`Swearing:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - (?=\S*[fF\*]+[uUvV\*]+[kKcC\*]+(?!us|hs))\S+
        - (?=\S*[b6B8\*]+[eE3iI1!\*]+[tT7\*]*[cC\*]+[hH4\*]+)\S+
        ReplaceWith: '&4Naughty&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4swearing with: &r[message]'
        Commands:
        - msg [senderName] &eDo not use bad words!`

In the above example there are two regex statements to remove both Fuck and Bitch. In instances where there is a match to the first word, then all instances of that word will be removed by Regex but the second word will appear throughout the sentence, only replacing the caught word.

The alternative workaround at the moment is to do the following:
`Swearing1:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - (?=\S*[fF\*]+[uUvV\*]+[kKcC\*]+(?!us|hs))\S+
        ReplaceWith: '&4Naughty&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4swearing with: &r[message]'
        Commands:
        - msg [senderName] &eDo not use bad words!
Swearing2:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - (?=\S*[b6B8\*]+[eE3iI1!\*]+[tT7\*]*[cC\*]+[hH4\*]+)\S+
        ReplaceWith: '&4Naughty&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4swearing with: &r[message]'
        Commands:
        - msg [senderName] &eDo not use bad words!`

As the above is a separate block the pass is run separately and both words are picked up and removed, but as each contain their own msgToStaff and command run, a sentence with potentially 5 - 7 different curse words immediately generates quite a lot of spam for the users.

Two potential solutions to this would be either to run a pass against each Regex within the single block to ensure there is a catch all on the Regex, the other would be to create a msgToStaff and Commands per group, so that any blocks that share the same grouping triggered can send a single message for the group opposed to singular for each instance (reusing the permission group variable already input).

### Basic explanation as to why this feature is needed and/or useful to have: ###
This would improve upon the great foundations already put in place for chat filtering to ensure users are not forced to choose between words slipping through the cracks or potentially spamming their staff in instances of certain users flagging multiple filters. It would allow servers to effectively ensure all words they wish to filter out simply would be done so and then stored in a single prompt per message.

**Comment by CloudeLecaw** [comment]
here an example of the swearregex we using (its a german swear word filter)

```
      schimpfworte:
        Enabled: true
        Group: schimpfworte
        InformConsole: true
        Regex:
        - Ϟ
        - 卍
        - 卐
        - \b(?i)(h+(\W|_?)+u+(\W|_?)+r+(\W|_?)+e+(\W|_?)+n+(\W|_?)+s+(\W|_?)+o+(\W|_?)+h+(\W|_?)+n+)
        - \b(?i)(h+(\W|_?)+u+(\W|_?)+r+(\W|_?)+e+)
        - \b(?i)(n+(\W|_?)+u+(\W|_?)+t+(\W|_?)+t+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+l+(\W|_?)+a+(\W|_?)+m+(\W|_?)+p+(\W|_?)+e+)
        - \b(?i)(f+(\W|_?)+o+(\W|_?)+t+(\W|_?)+z+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+i+(\W|_?)+e+(\W|_?)+g+)\s+(?i)(h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+l+)
        - \b(?i)(h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+l+)\s+(?i)(h+(\W|_?)+(i?)+(\W|_?)+(t?)+(\W|_?)(l?)+(\W|_?)(e?)+(\W|_?)+r+)
        - \b(?i)(h+(\W|_?)+i+(\W|_?)+t+(\W|_?)+l+(\W|_?)+e+(\W|_?)
        - \b[aA]+[sS]+[sS]
        - \b(?i)(a+(\W|_?)+s+(\W|_?)+s+(\W|_?)+h+(\W|_?)+o+(\W|_?)+l+(\W|_?)+e+)
        - \b(?i)(a+(\W|_?)+r+(\W|_?)+s+(\W|_?)+c+(\W|_?)+h+)
        - \b(?i)(d+(\W|_?)+r+(\W|_?)+e+(\W|_?)+c+(\W|_?)+k+(\W|_?)+s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+)
        - \b(?i)(f+(\W|_?)+u+(\W|_?)+c+(\W|_?)+k+)
        - \b(?i)(f+(\W|_?)+i+(\W|_?)+c+(\W|_?)+k+)
        - \b(?i)(f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        - \b(?i)(g+(\W|_?)+e+(\W|_?)+f+(\W|_?)+i+(\W|_?)+c+(\W|_?)+t+(\W|_?)+e+(\W|_?)+s+)
        - \b(?i)(i+(\W|_?)+d+(\W|_?)+i+(\W|_?)+o+(\W|_?)+t+)
        - \b(?i)(j+(\W|_?)+u+(\W|_?)+d+(\W|_?)+e+)
        - \b(?i)(l+(\W|_?)+e+(\W|_?)+c+(\W|_?)+k+)\s+(?i)(m+(\W|_?)+i+(\W|_?)+c+(\W|_?)+h+)
        - \b(?i)(m+(\W|_?)+a+(\W|_?)+u+(\W|_?)+l+)
        - \b(?i)(n+(\W|_?)+a+(\W|_?)+z+(\W|_?)+i+)
        - \b(?i)(n+(\W|_?)+i+(\W|_?)+g+(\W|_?)+g+(\W|_?)+e+(\W|_?)+r+)
        - \b(?i)(p+(\W|_?)+e+(\W|_?)+n+(\W|_?)+i+(\W|_?)+s+)
        - \b(?i)(p+(\W|_?)+e+(\W|_?)+n+(\W|_?)+n+(\W|_?)+e+(\W|_?)+r+)
        - \b(?i)(p+(\W|_?)+i+(\W|_?)+m+(\W|_?)+m+(\W|_?)+e+(\W|_?)+l+)
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+(\W|_?)+g+(\W|_?)+e+(\W|_?)+s+(\W|_?)+i+(\W|_?)+c+(\W|_?)+h+(\W|_?)+t+)
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+(\W|_?)+f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+s+(\W|_?)+s+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+ß+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+ß+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+w+(\W|_?)+a+(\W|_?)+n+(\W|_?)+z+)
        - \b(?i)(w+(\W|_?)+t+(\W|_?)+f+)
        ReplaceWith: '*****'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - cmi msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert und bekommst 20 Staffpunkte.
        - cmi warn [playerName] Fluchen -s
```
Result: the line is printed the swearword in it get ****** and the player gets 20 warning points

Our filter founds words like F I CK, fick, ffffiiiiiiCCCCkKK and even F_I_CCC__K and of course f#i c_k .e+n

Some little problems may still remain if the word is to simliar to the filtered one
Exanple: We filter for "Fresse" and if someone would say Fressen (the first one is a swear world the other descripts how animals eat... well i think there is nothing we can do if a word is to simlar to the filter. If you just scan for the correct work player will start writing HeFUcKHe  so not get censorted in the word fuck.
Well player notice fast what words are allowed and whtich not. and they get muted only when they collected enough points as first reason. so so can dealwith this.
I hope our filter can give you a little suggestion for yours :)

you can use as much swear words as you want in one line they all will be censored with ***** in all cases the player get 20 warning point because this is one block.
Of cusre you can design more blocks all of same group to have one bypasspermission for all - thats the sense of the groups (same group name - same bypass permission for admins)

**Comment by Leo-Alexa** [comment]
The issue I have found with the above is not the issue of whether or not it picks up a single swear word or multiple of a single word, but the issue in which it picks up different words in a single chat message.

For example, in your filter you've created, if someone were to type the following:
```I like this symbol: 卐```
It would result in:
```I like this symbol: *****```

Likewise the below:
```I like ass.```
Becomes:
```I like *****.```

But if someone wrote:
```If you use the symbol 卐 then you're an ass.```
It would result in:
```If you use the symbol ***** then you're an ass.```

This is because it takes the first match and blocks all instances of it within the message, meaning additional results are then not matched against it.

I've found a workaround for the time being by putting them all on a single line separated by or Regex, however I don't know how long a string it'll support when checking Regex so I'll see if it holds up as I'm adding new words.

To clean up your Fresse / Fressen problem, you can replace the line:
```\b(?i)(f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)```
With the following:
```(?=\S*[fF]+[rR]+[eE]+[sS]+[eE]+(?![nN]))\S+```

What that'll do is if anyone writes any combination of the word as follows:
```Frese, FResse, FrEsSe, Ffffrrreesssee, etc```
Regardless of case, it will be blocked by your filter, however if the word is followed by an n or N in any combination, it will not block and allow the word:
```Fressen, FRESSEN, FrEsEn, Freeeesssseeeen, etc```

Thanks for the assistance anyway. It's appreciated. :)

**Comment by CloudeLecaw** [comment]
i know this problem when you have 2 works from one filter... currently i found no solution for this - only adding one word for one filter..While this is still posible with my 20 words, it becomes a bit thick when you may have arround 100.. 

Here  The Filter (the first once i have not included now... but u see where it ende if you want all words and post them double
The bad thing...you get informed for each different catch @.@

![image](https://user-images.githubusercontent.com/12080017/96460660-baad3180-1223-11eb-840a-5d5a183a50f2.png)


Maybe Zrips can add/fix this one so if you have two words in one filter and both got catch that both get scensored 👍 As log as there isno fix, i may stay with the 1word/filter methode
Even if these are many fitlers that spread the config a bit... they can be bypassed alll with just one permission if they all are in the same group (in my case Group: Swearing - permission: cmi.bypass.chatfilter.Swearing  -> dont forget to negate for all with * permissionsfor cmi, else the filter do not work for them ;)

Here a little example with some i used before. woth these you can mix the sword words like you want all get censored
these are not included in the example (
        - Ϟ
        - 卍
        - 卐
        - \b(?i)(h+(\W|_?)+u+(\W|_?)+r+(\W|_?)+e+(\W|_?)+n+(\W|_?)+s+(\W|_?)+o+(\W|_?)+h+(\W|_?)+n+)
        - \b(?i)(h+(\W|_?)+u+(\W|_?)+r+(\W|_?)+e+)
        - \b(?i)(n+(\W|_?)+u+(\W|_?)+t+(\W|_?)+t+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+l+(\W|_?)+a+(\W|_?)+m+(\W|_?)+p+(\W|_?)+e+)
        - \b(?i)(f+(\W|_?)+o+(\W|_?)+t+(\W|_?)+z+(\W|_?)+e+)
        - \b(?i)(s+(\W|_?)+i+(\W|_?)+e+(\W|_?)+g+)\s+(?i)(h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+l+)
        - \b(?i)(h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+l+)\s+(?i)(h+(\W|_?)+(i?)+(\W|_?)+(t?)+(\W|_?)(l?)+(\W|_?)(e?)+(\W|_?)+r+)
        - \b(?i)(h+(\W|_?)+i+(\W|_?)+t+(\W|_?)+l+(\W|_?)+e+(\W|_?))
but the otehrsare
```
      swearing1:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b[aA]+[sS]+[sS]
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing2:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(a+(\W|_?)+s+(\W|_?)+s+(\W|_?)+h+(\W|_?)+o+(\W|_?)+l+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing3:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(a+(\W|_?)+r+(\W|_?)+s+(\W|_?)+c+(\W|_?)+h+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing4:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(d+(\W|_?)+r+(\W|_?)+e+(\W|_?)+c+(\W|_?)+k+(\W|_?)+s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing5:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_?)+u+(\W|_?)+c+(\W|_?)+k+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing6:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_?)+i+(\W|_?)+c+(\W|_?)+k+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing7:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing8:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(g+(\W|_?)+e+(\W|_?)+f+(\W|_?)+i+(\W|_?)+c+(\W|_?)+t+(\W|_?)+e+(\W|_?)+s+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing9:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(i+(\W|_?)+d+(\W|_?)+i+(\W|_?)+o+(\W|_?)+t+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing10:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(j+(\W|_?)+u+(\W|_?)+d+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing11:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(l+(\W|_?)+e+(\W|_?)+c+(\W|_?)+k+)\s+(?i)(m+(\W|_?)+i+(\W|_?)+c+(\W|_?)+h+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing12:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(m+(\W|_?)+a+(\W|_?)+u+(\W|_?)+l+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing13:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(n+(\W|_?)+a+(\W|_?)+z+(\W|_?)+i+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing14:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(n+(\W|_?)+i+(\W|_?)+g+(\W|_?)+g+(\W|_?)+e+(\W|_?)+r+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing15:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(p+(\W|_?)+e+(\W|_?)+n+(\W|_?)+i+(\W|_?)+s+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing16:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(p+(\W|_?)+e+(\W|_?)+n+(\W|_?)+n+(\W|_?)+e+(\W|_?)+r+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing17:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(p+(\W|_?)+i+(\W|_?)+m+(\W|_?)+m+(\W|_?)+e+(\W|_?)+l+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing18:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+(\W|_?)+g+(\W|_?)+e+(\W|_?)+s+(\W|_?)+i+(\W|_?)+c+(\W|_?)+h+(\W|_?)+t+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing19:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+(\W|_?)+f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing20:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+a+(\W|_?)+c+(\W|_?)+k+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing21:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+s+(\W|_?)+s+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing22:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing23:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+ß+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing24:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+e+(\W|_?)+i+(\W|_?)+ß+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing25:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(s+(\W|_?)+c+(\W|_?)+h+(\W|_?)+w+(\W|_?)+a+(\W|_?)+n+(\W|_?)+z+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
      swearing26:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(w+(\W|_?)+t+(\W|_?)+f+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde darüber
          informiert!
```
