### DISCUSSION TITLE
Afk - > way to send player to limbo server?

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#4401] [Feature Requests]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, couldn't be possible to send (create) limbo server, when player is kicked due to afk? Then, when he'll move, he'll be sent back. But it won't be normal server, just void around, same mechanism that is used for ex. by https://www.spigotmc.org/resources/autoreconnect-bungeecord-reconnect.62729/ plugin. I also saw that one afk used it. So player won't be on server, from where he was kicked, he will be somewhere on proxy (any server, it's limbo), and after movement he'll be connected back.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Because now we're kicking players to Lobby or from whole game mostly, this way we won't lose players and they'll be somewhere in proxy.

**Comment by CloudeLecaw** [comment]
When your plugins can do this. You can execute any command on afk, afkkick and afkback in config

**Comment by bobhenl** [comment]
No I don't have plugins that could do this.

**Comment by mrfloris** [comment]
```
  # Defines commands to be performed when player enters afk mode automatically while idling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi server limbo [playerName] -f
  - cmi broadcast !&6 * &l[playerDisplayName]&r &ehas gone AFK &7(Automatically)

  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi server limbo [playerName] -f
  - cmi broadcast !&6 * &l[playerDisplayName]&r &ehas gone AFK &7(%cmi_user_afk_msg%)
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - asPlayer! cmi back
  - 'cmi ctellraw all <T>&6 * &l[playerDisplayName] &ehas returned from AFK &7(%cmi_user_afk_msg%)</T><H>&7Has
    been away for: %cmi_user_afk_for%</H>'
```

CMI has the option to run commands, you can utilize this on a bungee server to send them to another server
