### DISCUSSION TITLE
!warmup:[timeInSec]:[true|flase]:(particel|0)! for specialized commands like the option in config

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#4426] [Feature Requests]
related to this ticket https://github.com/Zrips/CMI/issues/4420
i noticed that none seems to have ever suggested a warmup for specialiased commands
it could be a really nice thing in some cases (ex. you want a warmup in a custom alias because u allready have it in the config but you cant use the config because it cotains things like asConsole! or [playerName], etc...

how it should work:
**warmup:[timeInSec]:[true|flase]:(particle|0)**
timeInSec is the time for the warmup
true/false defines if the placer is not allow to move or not while the warmup is counting (so like in config this is done allready) :-)
if the value for particle is set to 0 then this means no particle example  !warmup:5:false:0!

example: you want a warmup for 5 secounds for a special command and player should not be allow to moved while this command: - here /creative - 
```
  creative:
    Cmds:
    - asConsole! mv tp [playerName] Creative
    Perm: true
```
adding the custom alias creative in the warmup in config would result in not working (what may is a bug?)

how the custom alias would look with this new feature then?:
```
  creative:
    Cmds:
    - !warmup:5:false:GylphHead! asConsole! mv tp [playerName] Creative
    Perm: true
```

The particles like GylphHead will be taken from the config where they are defined at the moment.
