### DISCUSSION TITLE
Chatfilter expansion

### DISCUSSION THREAD

**Discussion by ghost** [Zrips/CMI#4501] [Feature Requests]
(Apologies for how poorly written this is, I'm too busy to proofread right now.)
**Description of feature/improvement request:**
Ability to add chat filters to CMI commands, or alternatively, some way to check if something is clean for the chat filter or not, along with a way to alert staff if it is not "clean".

---
### Detailed explanation of what it should do, when and in what situation: ###
Imagine you have /afk setup so anyone can give an afk reason, using something such as;
```yml
AFK:
  ManualAfkCmds:
    - check:"%formatter_text_join_-_{cmi_user_afk_msg}%"==""! cmi broadcast !&c&l‹ &d[playerDisplayName]
    &7is now afk.
    - check:"%formatter_text_join_-_{cmi_user_afk_msg}%"!=""! cmi broadcast !&c&l‹ &d[playerDisplayName]
    &7is now afk. (&d%cmi_user_afk_msg%&7)
```
(Optional afk reasons ^)
But doing this; Anyone can bypass the chat filter making it useless. You _could_ use another plugin with support for this, or just use additional placeholders so every chat filter you have would be included in every single command output, but, well, yeah.

My idea is something like this;
1. Include a way to message a group of people with a permission node, example being anyone with `cmi.chatfilter.inform`.
2. Include a placeholder? That can use all chat filters, or specific ones (Maybe?) so you're able to check true / false state and block the message yourself in a custom alias.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Not only would this be able to help CMI commands, but you could add aliases to add CMI's chat support to any command you want.

**Comment by CloudeLecaw** [comment]
i agree to you, everywhere where you choose leave a meassage should be able to scanned by the filter
(but pls make it setupable - in our case it would break many command because we designed smilies as preplacers fpr chat like :) or -.-  or >.< or :O
on our server we made a hover afk meassage
means u see the normal afk measssage and you can hover over the meaasge to see deeper information

```
  AutoAfkCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName]
    wurde durch zulanges rumstehen AFK gesetzt.</H>
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName]
    hat folgenden Grund angegeben: %cmi_user_afk_msg%</H>'
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist nicht mehr AFK.</T><H>[playerDisplayName]
    war AFK wegen %cmi_user_afk_msg% für %cmi_user_afk_for%.</H>
```

So my idea to your sggestion:
a list in config where we can add commands that get scanned for the chat filter
