### DISCUSSION TITLE
Ability to define required arguments in custom alias

### DISCUSSION THREAD

**Discussion by DrakePork** [Zrips/CMI#4552] [Feature Requests]
**Description of feature/improvement request:**
As the title says, the ability to define how many arguments needs to be included for the custom alias command to run.

---
### Detailed explanation of what it should do, when and in what situation: ###
After creating a custom alias called "/example", and adding a command for it to run, lets say "/lp user $1 permission set $2", you can then specify that there needs to be 2 additional variables after /example, and maybe also the ability to add like a custom incorrect usage message.

### Basic explanation as to why this feature is needed and/or useful to have: ###
This would be useful to have so that commands that gets run by a custom alias only gets run if the correct amount of variables has been added.

**Comment by CloudeLecaw** [comment]
sorry for the late delay :-P i found your thread pointed from an other so i replay you the same here :-)

---------------------------------------------------------------------------------

sure just add a null check for the argumentnumber you wish to have.
for example you want that your command has mini 4 arugments
So add the check `check:$4!=null!` into your commands
now add an extra line with something like `check:$4==null! msg! [playerName] &cSorry, But you need to use at least 4 words!`

**here a little example:**
(permission for it is: _cmi.customalias.pm_)
the example send a private meassae to a player but only if he used at least 4 words. Elese it give him a feedback he did not use enough words.

```
  pm:
    Cmds:
    - check:$4!=null! cmi msg $1-
    - check:$4!=null! msg! [playerName] &aThe Meassage was sendet successfully!
    - check:$4==null! msg! [playerName] &cSorry, But your meassage was not sendet. You need to use at least 4 words!
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername]'
```
