### DISCUSSION TITLE
[Question] What does AutoReconnect, UseSSL, and ServerCertificate do in databaseinfo.yml?

### DISCUSSION THREAD

**Discussion by AZFire1** [Zrips/CMI#4592] [Q&A]
**Question: **
What does AutoReconnect, UseSSL, and ServerCertificate do in bungeeinfo.yml?

**Comment by bobhenl** [comment]
Where did you find this file please? I have
```
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true
```
and can't see this file anywhere, even any folder from CMIB on proxy.

**Comment by AZFire1** [comment]
Sorry, I meant databaseinfo.yml

**Comment by CloudeLecaw** [comment]
Generatena new databaseinfo.yml you will see there are no bungecord settings in it.they are part of config

Here the databaseinfo.yml
```
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: xxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxx
  hostname: xxxxxxxxxxxxxxx
  database: server
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: true
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: true
```
