### DISCUSSION TITLE
Make cooldown work only if the first part is same?

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#4714] [Q&A]
**Question: **
Hello, how could I make this cooldown work only if the first part of whole command - player name, is same? cause the second one is always something another, and that's probably why this cooldown doesn't work as I expect. I wanna it per-player cooldown.
```
  btruhlabohatsinezkral:
    Cmds:
    - check:%cmi_random_1_100%<=10! ptarget:$1! asConsole! cooldown:3600?#! cmi ctellraw all <T>&c&lTruhly &f» &eHráč &f$1 &eotevřel truhlu &f&lBohatší než král &ea získal z ní &f$2 $3 $4&e. Klíč lze získat třeba ze &c/store&e či &c/loterie&e.</T>
    Perm: true
```

**Comment by CloudeLecaw** [comment]
Could you descripe what you tried to create (only in Englisch pls) its hard to read the code if your using that foring language other then english in it. 
Where you create your random value?
If u creates a value before a random one then use
 %cmi_lastrandom_[playerName]% to see the value it created for the player before.
This value needes to be created before.. i mostly use a little msg or something before, what the player gets before where IT generates the random number.

**Comment by bobhenl** [comment]
Yeah, this command is for specialized crate plugin, where you open crate and there's 10% chance on broadcast to prevent spam, because it's lottery crate. Then I wanted to make cooldown that the one player can make this message only once, but the problem is, that second argument is always different, cause it's reward. Btw I changed it to $2- instead of $2, $3 etc.

Translated to english:
```
  bcratelottery:
    Cmds:
    - check:%cmi_random_1_100%<=10! ptarget:$1! asConsole! cooldown:3600?#! cmi ctellraw all <T>&c&lCrates &f» &ePlayer &f$1 &eopened crate &f&lLottery &eand got &f$2-&e. Key could be optained from &c/store&e or &c/lottery&e.</T>
    Perm: true
```
and where exactly should I put %cmi_lastrandom_[playerName]% please?

**Comment by CloudeLecaw** [comment]
%cmi_lastrandom_[playerName]% can  only be used if you generated a random before
Then you could check with
    - check:%cmi_lastrandom_[playerName]%<=10!  what the last random was and excute something if it was lower or equal to 10...
You cant check for a random like your trying it because its not generated before
Normaly before this check you needba command that generates a random. I mostly use a msg! Where the player got told a random Number before. (Something like 
```
  bcratelottery:
    Cmds:
    - cooldown:90#! msg! [playerName] Your lucky lottery number is %cmi_random_1_100%.
    - check:%cmi_lastrandom_[playerName]%<=10! ptarget:$1! asConsole! cooldown:3600?#! cmi ctellraw all <T>&c&lCrates &f» &ePlayer &f$1 &eopened crate &f&lLottery &eand got &f$2-&e. Key could be optained from &c/store&e or &c/lottery&e.</T>
    Perm: true
```
May u find a better way to generate thennumber before...
I also added the cooldown that breaks up everything if its not passed you can add a ? before the #. Then the player gets informed that the command is in cooldown.

**Comment by bobhenl** [comment]
Ok, but I don't like so much Msg way, cause I don't wanna spam players, do you think it could be done silently somehow?

**Comment by CloudeLecaw** [comment]
Hm maybe a little cheat arround
It must bea command where a random value can be used and it should be something that can be executed silently. So here a little trick they will not noticed ingame :)
Give them a random amount of money silently and take it one command later with samenamoun. Then you have your random number generated :)

```
  bcratelottery:
    Cmds:
    - cooldown:90#! asConsole! cmi money give [playerName] %cmi_random_1_100% -s
    - asConsole! cmi money take [playerName] %cmi_lastrandom_[playerName] -s
    - check:%cmi_lastrandom_[playerName]%<=10! ptarget:$1! asConsole! cooldown:3600?#! cmi ctellraw all <T>&c&lCrates &f» &ePlayer &f$1 &eopened crate &f&lLottery &eand got &f$2-&e. Key could be optained from &c/store&e or &c/lottery&e.</T>
    Perm: true
```
Maybe to let it work u may need asFakeOp! instead of asConsole! This could work because asFakeOp! should work for the cmi commands itself

**Comment by bobhenl** [comment]
@CloudeLecaw  it doesn't work :/ Tried 90% to see if cooldown does work, but it doesn't.
```
  btruhlabohatsinezkral:
    Cmds:
    - asConsole! cmi money give [playerName] %cmi_random_1_100% -s
    - asConsole! cmi money take [playerName] %cmi_lastrandom_[playerName] -s
    - check:%cmi_lastrandom_[playerName]%<=90! ptarget:$1! cooldown:3600?#! asFakeOp!
      cmi ctellraw all <T>&c&lTruhly &f» &eHráč &f$1 &ezískal z &f&lBohatší než král
      &f$2-&e. Klíč třeba ze &c/store&e či &c/loterie&e.</T>
    Perm: true
```

**Comment by CloudeLecaw** [comment]
I noticed that cooldown sometimes not work if asConsole or asPlayer is used after. This is allready Report here on git allready as an issue.
You took if the cooldown from your example?

**Comment by bobhenl** [comment]
Sorry for late response, but how do you mean:

> You took if the cooldown from your example?

Simply, cooldown still doesn't work and doesn't count.

**Comment by CloudeLecaw** [comment]
```
  btruhlabohatsinezkral:
    Cmds:
    - cooldown:90#! asConsole! cmi money give [playerName] %cmi_random_1_100% -s
    - asConsole! cmi money take [playerName] %cmi_lastrandom_[playerName] -s
    - check:%cmi_lastrandom_[playerName]%<=90! ptarget:$1! cooldown:3600?#! asFakeOp!
      cmi ctellraw all <T>&c&lTruhly &f» &eHráč &f$1 &ezískal z &f&lBohatší než král
      &f$2-&e. Klíč třeba ze &c/store&e či &c/loterie&e.</T>
    Perm: true
```
