### DISCUSSION TITLE
Hiding ? when disabling tab / custom tab alias in customalias.yml

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#4739] [Q&A]
**Question: **
Hi, I have question, I've made this custom alias sell ? to always open sell gui menu even when player type for ex. /sell sss, then it will open him menu. But I wanna try to hide ?, if it's possible. As I saw with new addition of custom tab completion / disabling the one, it may be possible now? But I don't know how, so that's why I'm asking here. So I wanna disable this ? in /sell tab completion:
![image](https://user-images.githubusercontent.com/18662086/101990010-6b740200-3ca4-11eb-9461-6c19bb2580e6.png)

Tried this:
```
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui
    Tab: false
```
But didn't work. Or may there will be better solution now to make what I want?  Here is why I did this method https://github.com/Zrips/CMI/issues/4271.

**Comment by CloudeLecaw** [comment]
i can agree and also have this problem. but at the moment the answer is no u cant hide it

**Comment by bobhenl** [comment]
Even with newly added features to custom aliases? I though it could be possible somehow :/

**Comment by CloudeLecaw** [comment]
no changes in that section

**Comment by mrfloris** [comment]
You can set custom tabs for a custom alias command.

**Comment by CloudeLecaw** [comment]
i suggest creating a bew alais without the ? we now have the | what makes the ? unnessary.

here an example.
```
  help:
    Cmds:
    - check:$1!=null|chat|discord|geld|home|jobs|kompass|köpfe|limits|lululandaufgaben|luluwiki|menü|news|regeln|rezepte|smilie|spawnnavigator|ticket|vote|weltkarte|wiki|zonen! asConsole! cmi ctext help [playerName]
    - check:$1==chat! asConsole! cmi ctext chat [playerName]
    - check:$1==discord! asConsole! cmi ctext discord [playerName]
    - check:$1==geld! asConsole! cmi ctext geld [playerName]
    - check:$1==home! asConsole! cmi ctext home [playerName]
    - check:$1==jobs! asConsole! cmi ctext jobs [playerName]
    - check:$1==kompass! asConsole! cmi ctext kompass [playerName]
    - check:$1==köpfe! asConsole! cmi ctext koepfe [playerName]
    - check:$1==limits! asConsole! cmi ctext limits [playerName
    - check:$1==lululandaufgaben! asConsole! cmi ctext lululandaufgaben [playerName]
    - check:$1==luluwiki! asConsole! cmi ctext luluwiki [playerName]
    - check:$1==menü!asConsole! cmi ctext menue [playerName]
    - check:$1==news! asConsole! cmi ctext news [playerName]
    - check:$1==null! asConsole! cmi ctext help [playerName]
    - check:$1==regeln! asConsole! cmi ctext regeln [playerName]
    - check:$1==rezepte! asConsole! cmi ctext rezepte [playerName]
    - check:$1==smilie! asConsole! cmi ctext smilie [playerName]
    - check:$1==spawnnavigator! asConsole! cmi ctext spawnnavigator [playerName]
    - check:$1==ticket! asConsole! cmi ctext ticket [playerName]
    - check:$1==vote! asConsole! cmi ctext vote [playerName]
    - check:$1==weltkarte! asConsole! cmi ctext weltkarte [playerName]
    - check:$1==wiki! asConsole! cmi ctext luluwiki [playerName]
    - check:$1==zonen! asConsole! cmi ctext zonen [playerName]
    Perm: false
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
```
