### DISCUSSION TITLE
Give rewards after restart to these who were there before restart and joined after

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#4792] [Q&A]
Hi, could I somehow give rewards to players which were online before restart and then connected after it, for ex. 30s after it?
I've tried it somehow with cooldown, but didn't get it... Could you please help me?
```
  restart:
    Cmds:
    - broadcast! &a&l*********************************************** \n&c&lRestart
      &f» &fServer is restarting for 5 &fseconds!\n&e&lFor getting reward don't leave!\n&a&l***********************************************
    - delay! 5
    - title! &c&lRestart
    - subtitle! &aCome back for reward
    - delay! 5
    - asConsole! stop
    - asConsole! give [whatNow] exp_bottle 32
    - delay! 200
    - asConsole! cmi ctellraw [whatNow] <T>&c&lServer &f» &fCause you weren't left server you're getting reward!</T>
    Perm: true
```

Tried just small delays... the first one should be broadcast about restart, then restart title, then restart, then it should give me exp bottles and the last should send me message after 200s.... but it didn't work probably and it give every players not depending on when they join after restart.... Any idea on how to make it?

I should probably use allPlayers! somewhere, but don't know where exactly. Maybe before give and ctellraw... but as mentioned, I need delay be "clopped" after restart and count previously online players.
