### DISCUSSION TITLE
Add the ability to use placeholders in ranks.yml

### DISCUSSION THREAD

**Discussion by DrakePork** [Zrips/CMI#4794] [Enhancement]
As the title says, add the ability to use placeholders in the ranks.yml file, for example under MoneyCost to have different MoneyCost for players.

Ex:
```
ExampleRank1:
  Enabled: true
  DisplayName: '&eExample 1'
  DefaultRank: false
  AutoRankup: false
  RankupConfirmation: true
  NextRanks:
  - ExampleRank2
  MoneyCost: %cmi_equationint_{cmi_user_meta_rankCost}*10%
```
