### DISCUSSION TITLE
Suggestion: Force player to ignore someone // separate 2 players

### DISCUSSION THREAD

**Discussion by x1p** [Zrips/CMI#4801] [Enhancement]
I would like to make a separate command.
This comes in handy when 2 players are arguing for eternity.

Therefore I need to force a player to ignore the other.

The input should be:
`/separate player1 player2`

I was thinking about a custom alias:
```yaml
CustomAlias:
  separate [playername] [playername]:
    Cmds:
    - cmi ignore $1- $2- -s
    - cmi ignore $2- $1- -s
```
But this can't be done due to the lack of:
- ingore only accepting only 1 argument
- only the player himself can execute /ignore
- staff member can't execute it for the player
- Silent argument is not available
- permission like cmi.command.ignore.others

Are there alternative methods using existing commands?
Is it possible to implement this?
As a new function or perhaps as arguments to implement it myself using customalias.
