### DISCUSSION TITLE
Better  explanation of Custom Tab Completes

### DISCUSSION THREAD

**Discussion by broken1arrow** [Zrips/CMI#4839] [General]
It say what you can use https://www.zrips.net/cmi/commands/custom-alias/ but not how to use it. 

For example "There is option to ether disable tab completes entirely or to use custom ones. " how can you turn it off and how do you add it to custom alias?

**Comment by CloudeLecaw** [comment]
here an example for you.

```
CustomAlias:
  speedstop:
    Cmds:
    - asConsole! cmi titlemsg all Neustart in 5 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - asConsole! cmi titlemsg all Neustart in 4 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - asConsole! cmi titlemsg all Neustart in 3 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - asConsole! cmi titlemsg all Neustart in 2 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - asConsole! cmi titlemsg all Serverneustart! %subtitle% &4&lDer Server startet nun neu.
    - asConsole! rp save-all
    - delay! 1
    - asConsole! minecraft:save-all
    - delay! 5
    - kickall! &eDer Server ist gleich wieder online!
    - asConsole! restart
    Perm: true
    Tab: false
    CustomTabs:
    - ''
  help:
    Cmds:
    - check:$1!=null|chat|discord|geld|home|jobs|kompass|köpfe|limits|lululandaufgaben|luluwiki|menü|news|regeln|rezepte|smilie|spawnnavigator|ticket|vote|weltkarte|wiki|zonen! asConsole! cmi ctext help [playerName]
    - check:$1==chat! asConsole! cmi ctext chat [playerName]
    - check:$1==discord! asConsole! cmi ctext discord [playerName]
    - check:$1==geld! asConsole! cmi ctext geld [playerName]
    - check:$1==home! asConsole! cmi ctext home [playerName]
    - check:$1==jobs! asConsole! cmi ctext jobs [playerName]
    - check:$1==kompass! asConsole! cmi ctext kompass [playerName]
    - check:$1==köpfe! asConsole! cmi ctext koepfe [playerName]
    - check:$1==limits! asConsole! cmi ctext limits [playerName
    - check:$1==lululandaufgaben! asConsole! cmi ctext lululandaufgaben [playerName]
    - check:$1==luluwiki! asConsole! cmi ctext luluwiki [playerName]
    - check:$1==menü!asConsole! cmi ctext menue [playerName]
    - check:$1==news! asConsole! cmi ctext news [playerName]
    - check:$1==null! asConsole! cmi ctext help [playerName]
    - check:$1==regeln! asConsole! cmi ctext regeln [playerName]
    - check:$1==rezepte! asConsole! cmi ctext rezepte [playerName]
    - check:$1==smilie! asConsole! cmi ctext smilie [playerName]
    - check:$1==spawnnavigator! asConsole! cmi ctext spawnnavigator [playerName]
    - check:$1==ticket! asConsole! cmi ctext ticket [playerName]
    - check:$1==vote! asConsole! cmi ctext vote [playerName]
    - check:$1==weltkarte! asConsole! cmi ctext weltkarte [playerName]
    - check:$1==wiki! asConsole! cmi ctext luluwiki [playerName]
    - check:$1==zonen! asConsole! cmi ctext zonen [playerName]
    Perm: false
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
``` 
or here two with some checks
  ```
vip:
    Cmds:
    - check:$1==null|info! check:$2==null! msg! [playerName] &6Gültigkeit Deiner VIP-Ränge
    - check:$1==null|info! check:$2==null! msg! [playerName] &6===========================
    - check:$1==null|info! check:$2==null! msg! [playerName] &6 &6
    - check:$1==null|info! check:$2==null! msg! [playerName] &aRang &a:&b     &eläuft ab in
    - check:$1==null|info! check:$2==null! msg! [playerName] &6 &6
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_TestVIP%
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_VIPmini%
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_VIP%
    - check:$1==info! check:$2!=null! check:$3==null! perm:cmi.customalias.vip.info! ptimer info $2
    - check:$1==info! check:$2!=null! check:$3==big|mini|test! perm:cmi.customalias.vip.info! perm:cmi.customalias.vip.give@! msg! [playerName] &c Du hast nicht die Berechtigung die Befehlsargumente big&c|&fmini&c|&ftest&c zu benutzen.
    - check:$1==info! check:$2!=null! check:$3==big|mini|test! perm:cmi.customalias.vip.info! perm:cmi.customalias.vip.give! msg! [playerName] &c Die Befehlsargumente big&c|&fmini&c|&ftest&c funktionieren nur mit dem give Argument. \n Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4] \n &f Es wird der normale Infobefehl ausgeführ    
    - check:$1==info! check:$2!=null! check:$3!=null|big|mini|test! perm:cmi.customalias.vip.info! ptimer info $2
    - check:$1==info! check:$2!=null! perm:cmi.customalias.vip.info@! msg! [playerName] &c Du hast nicht Berechtigung die VIP Info anderer Spieler auszulesen.
    - check:$1==give! check:§2==null! perm:cmi.customalias.vip.give@! msg! [playerName] &c Du hast nicht Berechtigung das give Argument zu benutzen.
    - check:$1==give! check:$2==null! perm:cmi.customalias.vip.give! msg! [playerName] &c Du hast vergessen einen Spielernamen anzugeben! Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4]
    - check:$1==give! check:$2!=null! check:$3!=big|mini|test! perm:cmi.customalias.vip.give! msg! [playerName] &c Du musst einen gültigen VIP Rang eingeben. Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4]    
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! asConsole! cmi kit VIP $2 -s
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! asConsole!ptimer give $2 VIP
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! msg! $2 &e Als Dank für deine Spende hast Du &b&l100 Votis &ein dein Inventar bekommen.&4 &c&4
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! msg! [playerName] &e Du hast &2&l$2 &b&l10 Votebarren &ein das Inventar gegeben.
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big@! msg! [playerName] &c Du hast nicht die Berechtigung den VIPRang zu vergeben.
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! asConsole! cmi kit miniVIP $2 -s
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! asConsole! ptimer give $2 VIPmini
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! msg! $2 &e Als Dank für deine Spende hast Du &b&l50 Votis &ein dein Inventar bekommen.&4 &c&4
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! msg! [playerName] &eDu hast &2&l$2 &b&l5 Votebarren &ein das Inventar gegeben.
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini@! msg! [playerName] &c Du hast nicht die Berechtigung den Mini-VIPRang zu vergeben.
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test! asConsole! ptimer give $2 TestVIP
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test! msg! [playerName] &eDu hast &2&l$2 &eden Rang &bTestVIP &efür eine Stunde gegeben.
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test@! msg! [playerName] &c Du hast nicht die Berechtigung den Test-VIPRang zu vergeben.
    Perm: true
    Tab: true
    CustomTabs:
    - 'info, [playername]'
    - 'give, [playername], big,mini,test'
  pongg:
    Cmds:
    - check:$1==null! msg! [playerName] &cDu musst einen Spielernamen als Ziel hinzufügen.
    - check:$1==0! asConsole! cmi broadcast !&2 Leider hat kein Spieler innerhalb der Zeit mit einem &4&lPONG&2 geantwortet. Daher verfällt der Preis dieses Mal. Vielleicht seid Ihr das nächste Mal ja schneller. =)
    - check:$1!=null|0! asConsole! cmi usermeta $1 add pingponggewinn %cmi_random_1_99% -s
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=1! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=33! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt zwei &5&lMystery Boxen&5&l✩✩✩&2. &eHerzlichen Glückwunsch!
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=34! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=66! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt 20 &5&lLulumanten&2. &eHerzlichen Glückwunsch!
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=67! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=99! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt 30 &6&lTaler&2. &eHerzlichen Glückwunsch!
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=1! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=33! asConsole! gmysteryboxes give $1 2 3 msg=false
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=34! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=66! asConsole! mysterydust add $1 20 msg=false
    - check:$1!=null|0! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=67! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=99! asConsole! cmi money give $1 30 -s
    - check:$1!=null|0! asConsole! cmi usermeta $1 remove pingponggewinn -s
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername],0' 
```

at least read then to try to understand how they work <3
