### DISCUSSION TITLE
Add per world support to totem config.

### DISCUSSION THREAD

**Discussion by DrakePork** [Zrips/CMI#4863] [Enhancement]
Atm the totem config is:
```
Totem:
  RemoveFromInventory: false
  Cooldown:
    Use: true
    Time: 3600
  Warmup:
    Use: false
    Time: 10
  ProtectFromVoid: true
  Effects:
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```
and this takes effect in every world, however I would like for there to be like a "worlds" section, where you can define totem settings per world, and a "default" section for worlds that arent specified, like this:
```
Totem:
  Default:
    RemoveFromInventory: false
    Cooldown:
      Use: true
      Time: 3600
    Warmup:
      Use: false
      Time: 10
    ProtectFromVoid: true
    Effects:
      Regeneration: 45
      FireResistance: 40
      Absorbtion: 5
  Worlds:
    world_nether:
      RemoveFromInventory: true
      Cooldown:
        Use: true
        Time: 10
      Warmup:
        Use: true
        Time: 10
      ProtectFromVoid: false
      Effects:
        Regeneration: 12
        FireResistance: 21
        Absorbtion: 13
```
