### DISCUSSION TITLE
CMI Vote

### DISCUSSION THREAD

**Discussion by Fargus-Van-Crystal-de-Mindark** [Zrips/CMI#4877] [Q&A]
Good Morning,

I saw that CMI has commands like

/cmi vote

I was asking... what this feature is? it is not showen in the wikipedia... And how we can use it ... I didn't find it in the config file...

It will replace a voting plugin? how it works?

Thanks in advance

**Comment by variananora** [comment]
It can replace voting plugin for basic things, but if you want some advanced stuff you can still use VotingPlugin and disable CMI's vote system on modules.yml

**Reply by Fargus-Van-Crystal-de-Mindark** [reply]
The problem is.... that votifier modutle is set on true
but there is actually no configuration module in my CMI folder...
where I can set all the things?

Could you show me, there is a lot of things and maybe I didn't find it?
could u be so kind to show me the right area?

Not speaking about this:
```
Votifier:
  # When set to true votifier votes will be counted for player
  CountVotes: true
  # Number of votes one IP can make in last 24 hours
  # Set it to 0 to have unlimited amount
  MaxVotesInADay: 1000
  # Cooldown between votes from same service
  # In most cases voting service will have its own cooldown setup
  # But if you need extra one to prevent rapid voting you can define time in seconds over here
  GeneralCooldown: 86400
  # When set to false, commands on sucessfull vote will not be performed
  PerformCommands: true
  # Defines commands to be performed when player votes
  # Supports specialized commands and placeholders
  # [serviceName] variable can be used to insert address
  CommandsOnVote:
  - cmi broadcast !&6[playerDisplayName] &evoted!
  - cmi give [playerName] diamond
  # Keep it at false if you dont want to give out extra rewards
  ExtraRewardsEnabled: true
  # Commands will be performed when player collect determined amount of votes
  ExtraRewards:
    '10':
    - cmi heal [playerName]
    - cmi money give [playerName] 100
    '100':
    - cmi heal [playerName]
    - cmi money give [playerName] 1000
    - cmi give [playerName] diamond 32
  # List of players to be excluded from top voter list
  ExcludeList:
  - None
  ```
  
  Normally to works it need to be attached to the query of the website
  like the host, the port, the token and the private and public key to be set on minecraft website where player go to vote

thanks

**Reply by variananora** [reply]
You still need NuVotifier or something like that to recieve the query from a voting website tho. CMI just take NuVotifier vote event and process it according to the player.

**Reply by Fargus-Van-Crystal-de-Mindark** [reply]
Oh thanks to tell me this.

**Comment by mrfloris** [comment]
Just copy-pasting the pinned msg i have in discord, hopefully it helps someone 
**CMI can handle Votes**, this is the recommended setup that works well on Spigot/Paper 1.16.4 to counts, display, and reward players voting.

- Buy and Install CMI (<https://www.spigotmc.org/resources/3742/>)
- Get NuVotifier (<https://www.spigotmc.org/resources/13449/>)

- Next, confirm that NuVotifier works properly, see incoming votes appear in the console.

- You must enable the CMI Module:
In `modules.yml`, find the following, and make sure it's set to `true`:
```yaml
# Handles votifier system
# Applies for servers from 1.7.x and up
votifier: true
```

- Then, make sure CMI is properly configured for your server, so please read and go through the `Votifier:` section and adjust accordingly.
In `config.yml`, find the following, and make sure it's set to `true`:
```yaml
Votifier:
  # When set to true votifier votes will be counted for player
  CountVotes: true
```

- Optinally, you can limit votes per IP per day, exclude playernames from top list, set a cooldown, set it to perform certain commands, and configure additional rewards. 

- Commands: (Note: If you want /votes, instead of /cmi votes, then set the command to true in Alias.yml) 
```
Player commands:
/cmi votes
/cmi votetop

Staff commands:
/cmi votes (playerName)
/cmi votetop (playerName)
/cmi voteedit (playerName) [add/set/take/clear] [amount] (-s)
```

- CMI Permissions: 
```
Recommended for players:
cmi.command.votes - Check players vote count
cmi.command.votetop - Check top vote list

To be considered for staff:
cmi.command.voteedit - Manage players votes
cmi.command.voteedit.others
cmi.command.votetop.others
cmi.command.votes.others
```

- CMI Placeholders: (Note: Placeholders can be used in holograms, in-game chat, tablist, interactive commands, dynamic signs, etc.)
```
%cmi_user_votecount%
%cmi_votetop_[1-10]%
%cmi_votetopcount_[1-10]%
```

- And finally; `/stop` the server, and start it up again to guarantee that everything's working properly. More information on <https://www.zrips.net/cmi/>
