### DISCUSSION TITLE
How to check for a condition, before decrementing/running attatched command?

### DISCUSSION THREAD

**Discussion by dkalaxdk** [Zrips/CMI#5054] [Q&A]
When using any of the following commands, the usage of the item is decremented, even though the perm:cmi.command.fly is not true for the player.
 ` /attachcommand perm:cmi.command.fly!;;!limiteduse:50!;;!cc!_internalfly [playerName]`
  (_internalfly is just an alias)
Is there any way for this to be checked before running the attached commands? 
(I have tried moving perm:cmi.command.fly to different locations in the command, and changing it to perm:cmi.command.fly#?! instead, none of these had any effect)

**Comment by CloudeLecaw** [comment]
run the alias and check it there :3

**Reply by dkalaxdk** [reply]
But that would still decrement the limited use, wouldn't it?
So even though they can't use it, they still lose durability?

**Comment by CloudeLecaw** [comment]
**your commandstructure seems to be a bit wrong..**
`/attachcommand perm:cmi.command.fly!;;!limiteduse:50!;;!cc!_internalfly [playerName]`
let me try to understand what might went wrong here...
u ordert a limited use of 50 for .... right nothing...
may u can try if this one works for you:
is the _ in your command reeally needed? better would be to change it if possible to interalfly
`/attachcommand !limiteduse:50!;;perm:cmi.command.fly!!cc!_internalfly [playerName]`
u also can try
`/attachcommand perm:cmi.command.fly;;!limiteduse:50!!cc!_internalfly [playerName]`
finally your just executing one command to a sperating with ;; is not needed.
**to be honest im not sure if check connditions work in attached commands...**
i took them to the custom alias to make sure they work..
So renember:
- ! - new condition
      a condition allways ends with a ! after. That is why u often see !! when having more then one condition (end current condition - start new condition)
- ;; - new command
- when creating a usage condistion or consumtion it counts as command.... why ever... ask Zrips... it would be easier to understand if thes condition also would need no ,, speration. maybe because its a special and no real condition... who knows..

well here a little example what we a doing
```
/cmi attachcommand !limiteduse:5!;;!cc!ptimer give [playerName] DrachenStock cmi.command.vipdrachenstock 4;;!left!!silent!drachen;;!right!!silent!drachenentfernen
```

what the command does:
- give timed permission if useage is not 0
---> execute command 1 if it was triggered by leftclick
---> execute command 2 if it was triggered by rightclick

both command are executed silently what means u have no console feedback. this is to keep the look cleaner :)
well you could also optimize this with just limiting the useage for one command if needed...

and the customalias to it:
```
  drachen:
    Cmds:
    - perm:cmi.command.customalias.drachen@! msg! [playerName] &cDu kannst keinen Drachen rufen.
    - perm:cmi.command.customalias.drachen#! asConsole! cmi panimation circle;effect:reddust;dur7;pitchc:10;part:10;offset:0,1,0;radius:1.5;yawc:5;color:r;target:[playerName]
    - perm:cmi.command.vipdrachenstock#! cooldown:5?#! asConsole! cmi broadcast !&6 [playerDisplayName] &6zaubert eine mächtige Kreatur!
    - delay! 7
    - asConsole! ptimer give [playerName] DrachenRufen petdragon.command.spawn 4
    - asPlayer! dragon spawn
  drachenentfernen:
    Cmds:
    - perm:cmi.command.customalias.drachen#! msg! [playername] &6Du schickst deinen Drachen weg.
    - perm:cmi.command.vipdrachenstock#! cooldown:4?#! asConsole! cmi shoot endersignal [playerName]
    - asConsole! ptimer give [playerName] DrachenEntfernen petdragon.command.remove 4
    - delay! 1
    - asPlayer! dragon remove 15
```

Effekt: the player has an item that he can use 2 times to call a dragon ride with left click.   with rightclick he can remove the called dragon.
May u see the useage has 2 requirments.
the first one they get from their group. i called it **cmi.command.drachen**
the secound one they get for 4 secounds from using the item: i called it **cmi.command.vipdrachenstock**
in both cases the player is executing the command to call a dragon, ride but if one of the permissions is missing then the customalias cancels.

may this can help you to design your thing :)
