### DISCUSSION TITLE
How do you give reasons on afk command?

### DISCUSSION THREAD

**Discussion by redalpha123123** [Zrips/CMI#5116] [Q&A]
I use /cmi aft Bathroom but it just puts me in AFK mode. Why can't I give a reason?

**Comment by CloudeLecaw** [comment]
you can give a reason if u defined it in config: you need to edit the basic lines in afk section of the config for this. the placeholder u need to work with is called `%cmi_user_afk_msg%`

here an example how it could look like with a hover for afk reason and time beeing afk when comeint back, while the official measage is not so detailed:
this is good if someone writes for example "/afk im going to work now and if i am back i will do something dont be shy to pm me while i am afk, i will responce soon i am back"  and avoid a spammy design in chat ;)

```
  AutoAfkCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eis now AFK.</T><H>[playerDisplayName] was not interacting for over 10 minuites and is set to AFk for that..</H>
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eis now AFK.</T><H>[playerDisplayName] has given the following reason: %cmi_user_afk_msg%</H>
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eis not longer AFK.</T><H>[playerDisplayName] was AFK for %cmi_user_afk_msg% about %cmi_user_afk_for%.</H>
```
