### DISCUSSION TITLE
Portal Command on Missing Permission

### DISCUSSION THREAD

**Discussion by jiajunmao** [Zrips/CMI#5256] [Feature Requests]
Hey, just wondering that it is possible to add a feature where I can define a set of commands to be executed upon denial entry to a portal for missing a permission node. Currently all portal share the same deny message and it would be great if we can customize deny command for each custom portal (send a cmi ctext, teleport elsewhere, etc., etc.)

**Comment by CloudeLecaw** [comment]
you can costumize the executes command by asking if player has permission for it before starting a command.
You also can creat as massive deny meassages as u want by this for all groups uwant
disable the regular portal target location and set a teleport/warp-command to the wanted location

Here a little example - player needs to have 3 permissions to enter. he get one info for each permission that is missing:

```
  SercetPlot:
    Loc: -333.0:189.0:293.0:-331.0:192.0:295.0
    enabled: true
    effect: Crit
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 3
    particleHide: 0
    activationRange: 25
    commandsWithoutTp: true
    commands:
    - perm:cmi.portal.permission1@! msg! [playerName] Your not part of this group. You cant enter.
    - perm:cmi.portal.permission2@! msg! [playerName] Your are just a regular player. You cant enter.
    - perm:cmi.portal.permission3@! msg! [playerName] You wish to enter? Ask an admin!
    - perm:cmi.portal.permission1#! perm:cmi.portal.permission2#! perm:cmi.portal.permission3#! cmi warp secretplot [playername] -s
```
example 2:
```
  SercetPlot:
    Loc: -333.0:189.0:293.0:-331.0:192.0:295.0
    enabled: true
    effect: Crit
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 3
    particleHide: 0
    activationRange: 25
    commandsWithoutTp: true
    commands:
    - perm:cmi.command.portal.secretplot@! msg! [playerName] Your not part of this group. You cant enter.
    - perm:cmi.command.portal.secretplot#! msg! [playerName] Looks like you have permission to enter - have fun!
    - cmi tpopos [playerName] 100 60 100 world 90 90
```

you also can set requresPerm to true. but in that case no commands would be executed and you dont get ported. Permission is cmi.command.portal.[portalname]
