### DISCUSSION TITLE
Add Most Differentiation for Vanish

### DISCUSSION THREAD

**Discussion by ItLucifer-MRPG** [Zrips/CMI#5512] [Feature Requests]
When you give a player the perm to see vanished people, you can see their whole body, and it can be hard to tell who is vanished and who isnt, If you could add something to show they are vanished, like make their body invisible but you're able to see their head, and maybe change how you see their name in tab by making it translucent or something (gray it out). I would make seeing who is vanished and who isnt alot easier, especially in a server where you give players vanish as a perk of a rank, etc.

**Comment by CloudeLecaw** [comment]
u allready can do this
its called the vanished state ;)

You can have it everwhere
as a prefix or in Tablist...as name temple

This placeholder also jsut can be shown when your vanished else its simply "null - means nothing"
Also it does not matter that all players would have this. why? if player is vanished u also no able to see his vanished tag or tab. etc

If you dont wanne change something now u also can check it by command
simply do /cmi list  it shows all players also vanished once with an [H] by default. (lso can be changed in langfile).
Or you can use /cmi vanish list. this lists all player that are vanished.

You can set a nametemplae too beore or after the playernames if wanted.
here u use the **%cmi_user_afk_symbol%**

**%cmi_user_afk_symbol%** is the placeholder you work with here

Here  a little example how you could add it to your Tablist
file. tabList.yml . look for the like PlayerName - the rest doesnt matter here..
```
    PlayerName: '  [prefix]&b[playerDisplayName]&e [prefix][playerDisplayName] %cmi_user_afk_symbol%'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Wellcome to Server'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome%'
      - '&f------------------------------------'
```

The vanish symbol u define in your langfile - you also could define one if someone is not vanished...if that makes sense...
```
  vanishSymbolOn: '&8[&7Vanish&8]&r'
  vanishSymbolOff: ''
```
