### DISCUSSION TITLE
Way to delete money & sell logs after specific period?

### DISCUSSION THREAD

**Discussion by bobhenl** [Zrips/CMI#5563] [Enhancement]
Hi, I wanna suggest new option to delete money & sell logs after configured period. Would be useful to clear logs, exactly in money one.

**Comment by CloudeLecaw** [comment]
Also would be nice to be able to exclude jobs money from the log. So it would be eaiser just to log real money transactions. Currently the moneylog is getting very very long when you have jobs enabled on the server. The logfile logs each incoming of jobs for all players. So we often have logs about 500KB each day.

This is how it could look in the config

```
  LogEnabled: true
  log:
    Unknown: true
    Transfer: true
    Jobs: true
    #Remove Moneylog After X Amount of Days. Set to 0 to disable Removing of Moneylog
    removeLogAfter: 7
```
