### DISCUSSION TITLE
CMI KACK transmission command without countdown

### DISCUSSION THREAD

**Discussion by Dazzle-sys** [Zrips/CMI#5687] [Enhancement]
I need a countdown for the transmission type command. Can I add it myself? What should I do instead?

**Comment by dkalaxdk** [comment]
The teleport commands?
If so, add them at the warmup section of config.yml.

```yml
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: false
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: false
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
  - cmi spawn:3:false
 ```
  
  Also:
```yml
# Defines time in seconds for player being teleported after tpa or tpahere is being accepted
TpaWarmup: 3
# Defines if player can move when tpa or tpahere is being accepted
TpaMove: false
```
