### DISCUSSION TITLE
Discord event

### DISCUSSION THREAD

**Discussion by NightLife-SG** [Zrips/CMI#5950] [Enhancement]
Make a option for discordsrv

When ever a player get banned,tempban,kick,mute,cuff all this kind of action

Get record into discord automatically with embed meassage whenever those action is being triggered with reason

:)

**Comment by Ultrasonic1209** [comment]
feel like it would be a better idea to simply add eventCommands for kicks, bans, mutes, etc and let the server admin bind `discord broadcast` to them

**Comment by CloudeLecaw** [comment]
You can do this allready

Create the channels you need in your discord
And define it in discordsrv alerts.yml

Here an Example for ban where ban using is landing inside report channel. The executer needs to have the defined permission.
Note: bans from console dont get postet there

```
  - Trigger: PlayerCommandPreprocessEvent
    Channel: report
    Conditions:
      - message.startsWith("/cmi ban")
      - '#player.hasPermission("cmi.command.ban") == true'
    Embed:
      Color: "#00ff00"
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: "{name} - date: {date} has banned a player. - command: ${#allArgs}"
```
