### DISCUSSION TITLE
Add itemshop can buy

### DISCUSSION THREAD

**Discussion by DarrienNN** [Zrips/CMI#5962] [Feature Requests]
Suggest to add buy in itemshops like sell, it looks cool and simple :D

**Comment by CloudeLecaw** [comment]
You know you easily can create own single item buy Shops, with hologrammm too.

You also can create signs like known from chestshop plugins that is used on many servers.
Wanne see some little example? ;p

Here an example of a BuySellSign for Emeralds that you can Connect via IC to a sign
with left click you would 1 emerald
with righclick you would sell 1 emerald
with shift left click you  would buy a stack emeralds
with shift right click you would sell a stack emeralds

```
buySellTestSignEmeralds:
  Locations:
  - world;1730.0;70.0;1635.0
  Commands:
  - click:left! cooldown:1#! hasmoney:1@! msg! [playerName] &fYou need at least &e&l1 dollar &fon your account, to buy &2&l1 emerald &f. Currently you just got &e&l%cmi_user_balance_formatted% Dollar&f.
  - click:left! hasmoney:1! msg! [playerName] &fYou bought &a&l1 emerald&f for &e&l1 dollar&f gekauft.
  - click:left! moneycost:1#! cmi give [playerName] emerald 1
  - click:left! msg! [playerName] &fYour new balance is:&e &e&l%cmi_user_balance_formatted% dollar&f.
  - click:right! cooldown:1#! hasitem:emerald-1@! msg! [playerName] &fYou need at least &2&l1 emerald&f, to sell them for &e&l1 dollar&f.
  - click:right! hasitem:emerald-1! msg! [playerName] &fYou sold &a&l1 emerald &ffor &e&l1 dollar&f.
  - click:right! item:emerald-1#! cmi money give [playerName] 1 -s
  - click:right! msg! [playerName] &fYour new balance is:&e &e&l%cmi_user_balance_formatted% dollar&f.
  - click:leftshift! cooldown:1#! hasmoney:64@! msg! [playerName] &fYou need at least &e&l64 dollar &fon your account, to buy &2&l64 emeralds &f. Currently you just got &e&l%cmi_user_balance_formatted% Dollar&f.
  - click:leftshift! hasmoney:64! msg! [playerName] &fYou bought &a&l64 emeralds&f for &e&l64 dollar&f gekauft.
  - click:leftshift! moneycost:1#! cmi give [playerName] emerald 64
  - click:leftshift! msg! [playerName] &fYour new balance is:&e &e&l%cmi_user_balance_formatted% dollar&f.
  - click:rightshift! cooldown:1#! hasitem:emerald-64@! msg! [playerName] &fYou need at least &2&l64 emeralds&f, to sell them for &e&l64 dollar&f.
  - click:rightshift! hasitem:emerald-64! msg! [playerName] &fYou sold &a&l64 emeralds &ffor &e&l64 dollar&f.
  - click:rightshift! item:emerald-64#! cmi money give [playerName] 64 -s
  - click:rightshift! msg! [playerName] &fYour new balance is:&e &e&l%cmi_user_balance_formatted% dollar&f.
  SignLines:
  - ''
  - '&2&lEmerald'
  - '&6&lB:1 | S:1'
  - ' '
  ReqPerm: false
```
