### DISCUSSION TITLE
Combat Mode on selected mobs only

### DISCUSSION THREAD

**Discussion by EkonC** [Zrips/CMI#6034] [Enhancement]
Hey, I'd like to ask you if you'd add a feature that would put you into combat mode when fighting certain mobs only (mob whitelist). This is how the config could look like

```
  Mob:
    DisableFlight: true
    DisableFallDamage: true
    ShowBossBar: true
    BlockCommands: true
    AllowedCommands:
    - msg
    - r
    - tell
    MakeBlackList: false
    MobWhitelist:
      Enabled: true
      MobList:
      - Ender_Dragon
      - Wither
      MakeBlackList: false
```
