### DISCUSSION TITLE
Match /mail settings added in EssentialsX (temporary mails)

### DISCUSSION THREAD

**Discussion by TomLewis** [Zrips/CMI#6111] [Enhancement]
https://github.com/EssentialsX/Essentials/pull/3710

A temporary mail feature was added to Ess, which would be very handy, please follow suit.

**Comment by mrfloris** [comment]
<img width="341" alt="Screenshot 2021-09-08 at 09 12 05" src="https://user-images.githubusercontent.com/28841349/132463136-1606987e-cd6e-466d-b64c-d2c4bde26053.png">

CMI already stores the timestamp for an email, so this can work backwards as well. It would be nice to have a global config.yml for /mail to automatically expire.

```yml
Mail:
  # Automatically purge /cmi mail from all users in the database on start of server? 
  # False is how it's always been, so doesn't affect existing servers, true would purge old mail over x days on start of server.
  - enabled: false
  # Amount is in days, should be higher than 1 and default to something like 3 years to be reasonable. Set to -1 to disable
  - purge: 1000
```

And optionally the ability for a flag parameter in `/cmi mail` _syntax_ to support `-expire` after x days. Which for all I care is either a custom amount per mail or another global amount.

```
  # If /mail -expire is used in mails, this will expire them on player-join event or something logical (number is in days)
  - purge-on-expiry: 90
```

Anyway, I haven't taken a look at EssentialsX in a while, might do that next time to get a better idea of what is expected. I also don't kno how server heavy it is on start to auto purge through a whole database.

**Comment by TomLewis** [comment]
Auto expire is a good idea. I have players that just leave all their mail as they are lazy, as long as it tells people when it will expire.

**Comment by Zrips** [comment]
To be fair, we do have 
```yml
PlayerMail:
  # For how long to keep players mail in days
  ExpiresIn: 30
```
But will add option to send specific temporary mails in case you want additional control over some specific ones
