### DISCUSSION TITLE
Placeholder for last Money Action and Last exp Action Value +  % of total XP

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#6190] [Enhancement]
Players on our Server have the option to store their Money and XP inside a Bank
I want to setup above if they didnt saved their XP or money and died like known from many MMOs
The Idea is that they losse a %value of what they have and carry with them.

For the Money this is allready possible.
For the XP i just found the amount and random value but no %ofTotal  This would be needed
To style the shown meassage better it would be great to be able to setup a msg with own Format
The Problem is that we have no placeholder that show the Value of the last money and exp command used on a player.
So two placeholders like `cmi_user_lastexp` and `cmi_user_lastmoney` would be needed that return the value
of last used money and exp command.

```
playerDeath:
  Enabled: true
  Commands:
  - cmi money take [playerName] 10% -s
  - cmi exp take [playerName] 10% -s
  - msg! [playerName] Your Death took its Price. You lost %cmi_user_lastmoney% Dollar and %cmi_user_lastexp% XP.
  SourceCommands: []
```

So could you add `cmi_user_lastexp`, `cmi_user_lastmoney` and the abillitie to give and take % of total xp?

If the Placeholders are not able to add i could life with just writting them something like
You lost 10% of Your Money and XP... would be so detailed but still possible.
