### DISCUSSION TITLE
Hides invisible (/vanish) players in the tablist

### DISCUSSION THREAD

**Discussion by M4h45amu7x** [Zrips/CMI#6302] [Feature Requests]
It's the same as in the title.

**Comment by CloudeLecaw** [comment]
This is allready done by permission.
There is a permission that allows u to see vanished ppl in tablist.
Negate the permission if u have all others and u dont see vanished people anymore.
Create a custom alais that does tablistupdate if your regular tab intervall update is set to low.

**Comment by AlternativeSoap** [comment]
Where is the perm to "ONLY" see vanished players in tablist?

My players can see in tab whenever I get vanished, I don't want that.

**Comment by CloudeLecaw** [comment]
- first lower Tab list update if needed... (we didnt do this and just let it update on login,logoff.afk,unafk, and all 30 secounds, but its an option to lower the delay time between tablist updates)
- secound: make sure the normal players dont have the permission **cmi.seevanished**
- thrid: Create a custom alias that updates your tablist when you get vanished.


here is the custom alias we made for vanish (it overwirtes the /vanish if u taken it from cmi in alias.yml
We use it to solve the delayed tabupdate where people can see you until the tablist updates

```
  vanish:
    Cmds:
    - perm:cmi.command.vanish@! msg! [playerName] &cThe command does not exist or you have no permission to use it.
    - perm:cmi.command.vanish#! check:$1==%cmi_user_name%! asPlayer! cmi vanish
    - check:$1==null! asPlayer! cmi vanish
    - check:$1!=%cmi_user_name%! asPlayer! cmi vanish $1 
    - delay! 0.1
    - asConsole! cmi tablistupdate
    Tab: true
    CustomTabs:
    - '[playername]'
```
