### DISCUSSION TITLE
Pay for entering portal

### DISCUSSION THREAD

**Discussion by Bloodlex** [Zrips/CMI#6321] [Enhancement]
Could you please add to GUI to set price for using a portal?

**Comment by CloudeLecaw** [comment]
U can use hasmoney and hasmoney andncombine them innyour portal instead of exit cords.
Here is an example portal where u have to pay 64 Dollar to use the portal.

```
  Testpportal:
    Loc: -729.0:10.0:-2788.0:-729.0:12.0:-2787.0
    enabled: true
    effect: Reddust
    showParticles: false
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - hasmoney:64@! msg! [playerName] &fYou need at least 64 dollar to use this portal.
    - hasmoney:64! msg! [playerName] &fYou used the portal for 64 Dollar.
    - hasmoney:64#! moneycost:64! cmi tppos [playerName] -732.85 20.0 -2786.91 world -11.4 2.87 -s
```
