### DISCUSSION TITLE
[Request] Ability to define pickaxe types for breaking spawners

### DISCUSSION THREAD

**Discussion by TheWranger** [Zrips/CMI#641] [Feature Requests]
A list in the config of pickaxe types that can break spawners with silktouch and pick it up. Similar to what SilkSpawners has.

**Comment by CloudeLecaw** [comment]
why this would be needed?
you can set it up the the Itmes Needs some enchant liek Silktouch II and this you can let your Players craft themself with CMIs custom Recripe Editor...

For example:
my Players Need 6 Diamaonds and 3 Obsidian in the Right Shape to Craft the a Silktouch 2 Stoneaxe and only with this axe (because of silktouch 2) they can collect the mined spawner if they have enough charges (charges also can be disabled if u dont work with them)

**Comment by TheWranger** [comment]
I don't know why you're bringing up custom recipes or silk touch levels.
I simply want to be able to select which types of pickaxes can pick up spawners (wood, stone, gold, iron, diamond).

**Comment by CloudeLecaw** [comment]
why bring this up? custom recipes with silktouch 2 items? Because that is how it simply works for the Moment and a itemlist is not really nessesary here, look in the spawners configs Shows u that we have millions of config otpion for getting the spawners allready, so why an extra itemlist now?
Create your items that can do it, and ist simply done.  pls dont say "i want to be more vanilla",-> in vanilla u cant mine spawners just break them. and i see no reason why a may simply crafting recipe that allow your Players getting the silktouch 2 should not be allowed?
U have no other extas from having silktouch 2 - the only difference to silktouch 1 is that 2 allows u to mine the spawns if u setted this up.

```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # When set tp fa;se, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 2
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: true
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: false
  Interact:
    # When set to true, players trying to change spawner with monster egg will require approrpiate permission node
    # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
    EggRequiresPermission: true
  # If set to true, spawners will have chance to be dropped when destroying with tnt
  TnTExplosionDrop:
    use: false
    # Chance in percentage for spawner to drop
    Chance: 30
  # If set to true, spawners will have chance to be dropped when destroyed by creeper
  CreeperExplosionDrop:
    use: false
    Chance: 30
  Charges:
    # When enabled players will be assigned to particular spawner charges group who have cmi.spawners.charge.[groupName] permission node
    # Players will be limited to how many spawners they can mine
    # StartingCharge will determine how many charges they will have on first time joining group
    # MaxCharge will limit to how many charges you can have at one time
    # Cooldown determines how often new charge will be given
    # Bonus is optional and it will determine by how many seconds to lower cooldown for next charge when placing spawner
    # Option to bypass limitations with cmi.spawners.charge.bypass
    Use: true
    # If set to true when player runs out of spawner charges spawner will be destroyed without droping it
    BreakWithoutCharge: false
    List:
      spieler:
        Use: true
        StartingCharge: 1
        MaxCharge: 2
        Cooldown: 500
        Bonus: 10
      mod:
        Use: true
        StartingCharge: 30
        MaxCharge: 50
        Cooldown: 200
        Bonus: 50
  Proximity:
    # Allws to limit how tight spawners can be placed from each other
    Use: true
    # Radius in blocks from blaced block. Max range is 16
    # Can bypass with cmi.spawners.proximity.bypass
    Range: 3
```
