### DISCUSSION TITLE
[Request] Permission node tablist sorting

### DISCUSSION THREAD

**Discussion by TheWranger** [Zrips/CMI#653] [Feature Requests]
Sort players on the tablist depending on what permission node they have.
Something like `cmi.tablistsort.[number]`
The higher the number, the higher on the tablist they will be at. Higher numbers should override lower numbers if they have multiple permission nodes.

If people don't want to use this, they can just not give the permission nodes to people.

**Comment by CloudeLecaw** [comment]
why other Players should be listet higher?
To have admins on first place allways?
Why not working with ranks prefix or Color or other Things? ;)

> 

> If people don't want to use this, they can just not give the permission nodes to people.

your forgot admins they would have all existing tablistsortnumbers even if u didnt gave them to them

so it would be better if a tablistsorting can be disabled in config if not used
the option could be added somehwere here in the config:
```
TabList:
  # Enable or disable tab list management
  Enabled: false
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: false
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 60
    OnJoin: false
    OnLeave: false
    afkStateChange: false
    OnWorldChange: false
    OnDeath: false
    OnTeleport: false
    OnNickChange: false
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In adition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '[playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome to &fLtCraft &7server'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  # If player has more than one permission node, then biggest one will be used
  GroupFormat:
    '1':
      PlayerName: '&2{&r[playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
```
