### DISCUSSION TITLE
Player Tag improvement

### DISCUSSION THREAD

**Discussion by alexandrosmagos** [Zrips/CMI#6844] [Enhancement]
I currently use other plugins for chat mentions as I had for a long time, and would like to switch to CMI's one.

An option that would be great is to disable the @ requirement for the tag to work.

Also I like when someone is tagged, the name in the chat to be bold and aqua. But for that to work, the player has to have the aqua chat permission, which not all groups have and don't want to give it to the default group. It'd be great if the plugin automatically used the &b&l without the player actually having the chat color & bold perms.

These are my two suggestions that I'd love to have and would make me remove my other plugin for chat mentions :)

**Comment by CloudeLecaw** [comment]
> An option that would be great is to disable the @ requirement for the tag to work

This can be done in config allready
Look the note in tag: ->  hardcoremode
The sender that wants to tag others needs the permission **cmi.tag.color**.
The tag Option should be enabled in cmi options

> Also I like when someone is tagged, the name in the chat to be bold and aqua

For tag color use the color for it and adjust cmis colormmangement to be used in color section
U see u can define the tag name color here in the tag section in config

In addition to this u can use multiple commands to be preform if someone is taged. might useful to play an sound that the taged on gets.

Oh and in addition to that u can remove the crazzy @ in the chat result with the taged name if wanted
```
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: true
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&b&l'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound block_note_block_harp:1:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```
