### DISCUSSION TITLE
Baltop config toggle and/or hover for nickname

### DISCUSSION THREAD

**Discussion by mrfloris** [Zrips/CMI#6859] [Enhancement]
Hey, it would be kinda nice if either we get a global toggle in the economy section of config.yml for baltop to not show nicknames:
```yaml
Economy:
 #when enabled, always show the ign, not a displayname and/or nickname if set. (defaults to false)
 always-show-ign-in-baltop: true
 #when enabled, always show the ign, when they hover mouse over nicknames in baltop output (defaults to false)
 show-real-ign-on-hover-in-baltop: true
```
