### DISCUSSION TITLE
/cmi options gui - additional options (control the gui request)

### DISCUSSION THREAD

**Discussion by mrfloris** [Zrips/CMI#6865] [Enhancement]
Hey, I hereby kindly request to please expand the CMI GUI features in various of CMI's GUIs, such as homes, warps, kits, and options. Since options is still fairly new and now has settings in config.yml I focus on it (first).

Could it please be possible to get an alike /homes control over the gui bevel, and option to add an info button and a back button that we can link to a main menu (besides close).

Bevel: 1
Default how it is now, with the black glass panes as a bevel around it all.
Bevel: 0 or 2
Option to change it to 0 to remove the bevel and only show the icons, or even set it to 2, and make the bevel thicker. (so any "menu" on the gui at the bottom is more separated.

Can we add additional buttons to the menu of the gui, i see we can set a close button, can we add a menu button or info button?
```yaml
Player:
  Options:
    CloseButton:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - closeinv!

    OptionsInfo:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - cmi ctext optionsinfo [playerName]

    BackToMenu:
      Use: true
      Slot: 55
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - bossshoppro open menu [playerName]

```

How do we add extra options to toggle if we have them, we might have something from other plugins like mcMMO or Jobs or mcPerks, and some account preferences, .. it would be nice if we can have /options actually list all sorts of toggles. 
```yaml
OptionCommands:
- mcmmo: 
   - enabled: true
   - slot: auto (or 12 or 13 or 14..)
   - title: Remove mcMMO Scoreboard
   - lore: Toggles between mcMMO Scoreboard
   - status: %mcmmo_some_placeholder%
   - material: diamond_pickaxe
   - command: mcsb clear
- jobs: 
   - enabled: true
   - slot: auto (or 12 or 13 or 14..)
   - title: Auto Display Jobs Progress Bar
   - lore: Enabled means every 5 minutes we auto-show progress bars
   - status: %jobs_some_placeholder%
   - material: diamond_pickaxe
   - command: lp user [playerName] permission set something.toggle.something true
```
(made up examples of course).

Could we also get an override for the global glass pane, so if we want diamonds to display we can set the border-override to diamonds, replacing the black glass pane in just this /options menu?

Side note: Can we get /options status, which lists all the options status as an overview?
