### DISCUSSION TITLE
[Suggestion] InventoryRollback module

### DISCUSSION THREAD

**Discussion by TheRobLP** [Zrips/CMI#6868] [Feature Requests]
So, recently I made a big mistake by clearing a wrong inventory. When this happens it is very hard to get the inventory restored. It would be so good if CMI would have a setting to save the players inventory on certain events, such as /clear or on Join, Death, Quit etc. Can this be added please? Thanks in advance for any reply.

**Comment by CloudeLecaw** [comment]
Players inventory can be saved on death in config. And if you want this yoi could also trigger it as eventcommand by command in eventcommands.yml
In config u define the amount of saved inventories. These can be read by admins with permission in a guu and restore it to theirself or the player. Also they see the death cords and deathreason in the gui and can tp there. Oh and the hunger and xp the people had + time.

**Comment by CloudeLecaw** [comment]
Seeting in config for deathsave

```
inv:
  # Do you want to save the player's inventory on his death
  SaveOnDeath: true
  # When set to true, empty inventories (no items in inventory) will not be saved on players death
  IgnoreEmpty: true
  # If set to true then player should have cmi.saveinv permission node for inventory to be saved on death
  RequiresPermission: false
  # How many inventories, we will keep for each player
  SavedInventories: 50
```

And commands.for manuell useage or eventcomamnds.yml
For saving
**cmi invsave (playerName) (id) (-s)**
If u dont set an id the next free id is used

And for restore

**cmi invlist (playerName)**  to load the table of saved inventories to show them in a nice gui (klick on it)
Or
**cmi invload (sourceName) (targetName) [id/last**]
To load inventory directly for u  or other player if u know the id or know it was his last.
