### DISCUSSION TITLE
Cmi warps/homes, Custom gui items

### DISCUSSION THREAD

**Discussion by Rafalll1** [Zrips/CMI#6919] [Enhancement]
My suggestion is to add my items to the gui in the config. This would allow us, the server owners, to create our own unique gui for warps or homes. I think this is a suggestion that will please most people who use this plugin, the default warp gui look is ugly to me

InfoButton and  InfoButton2
https://pastebin.com/FRcnVq0Q

**Comment by izimen** [comment]
This is a great proposition! I would also like to have this option. It would be very useful.

**Comment by eightballz** [comment]
Great Suggestion! If you really want this right now, check out the great plugin, CommandPanels and just use warp/home commands in your custom GUI.

**Comment by mrfloris** [comment]
cmi/settings/homes.yml has this now
```yaml
      Infill: WHITE_STAINED_GLASS_PANE
      InfoButton:
        # Extra button to be used in case you want to provide any aditional information when clicking on it
        Use: false
        Slot: 1
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ==
        Commands:
        - closeinv!
      CloseButton:
        Use: true
        Slot: 9
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
        Commands:
        - closeinv!
      bedButton:
        Use: true
        Slot: 4
        Material: LIGHT_BLUE_BED
      homeButton:
        Use: true
        Slot: 5
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJkN2E3NTFlYjA3MWUwOGRiYmM5NWJjNWQ5ZDY2ZTVmNTFkYzY3MTI2NDBhZDJkZmEwM2RlZmJiNjhhN2YzYSJ9fX0=
      deathButton:
        Use: true
        Slot: 6
        Material: TOTEM_OF_UNDYING
      prevButton:
        Slot: 46
      middleButton:
        Slot: 50
      nextButton:
        Slot: 54
```

kits in config.yml
```yaml
Kits:
  # When set to true, kit list will be shown in GUI instead of chat list
  GUI: true
  # When set to true, kit selection gui empty fields will get filled with definet item
  FillEmptyFields: true
  Buttons:
    Cooldown: Watch
    Usages: STONE_PLATE
    Money: GOLD_INGOT
    Exp: EXP_BOTTLE
    Desc: WOOL:13
    Back: Fence
  Complex:
    CloseButton:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - closeinv!
    InfoButton:
      # Extra button to be used in case you want to provide any aditional information when clicking on it
      Use: false
      Slot: 1
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ==
      Commands:
      - closeinv!
```
and warps in config.yml
```yaml
Warps:
  # When set to true, warps list will be shown in GUI instead of chat list
  GUI: true
  # Automatically opens GUI when created new warp point
  GUIOnCreation: true
  # Minimal length of warp name
  MinLength: 4
  # Maximal length of warp name
  MaxLength: 16
  # How many warps to show in each page
  perPage: 50
  # Do you want to show creator in warp list
  showCreator: false
  # When set to true, new warps by default will require permission node to use them
  requirePerm: false
  Complex:
    CloseButton:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - closeinv!
    InfoButton:
      # Extra button to be used in case you want to provide any aditional information when clicking on it
      Use: false
      Slot: 1
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ==
      Commands:
      - closeinv!
```

Hopefully a few more things solve some of the desires, but I agree, there are enough locations where i'd love to nitpick the item and it's location, etc.
