### DISCUSSION TITLE
clear command

### DISCUSSION THREAD

**Discussion by ava852546** [Zrips/CMI#6936] [Feature Requests]
Can the clear command support custom items like the give command?
ex clear playername stone n &cstonea l &bstoneb

**Comment by mrfloris** [comment]
Not sure this helps, but here's the current info of what I know clear can do, I remember it getting nbt exclude as well
```yaml
    Clear:
      # When set to true, /cmi clear comamnd will require confirmation for it to be finalized
      Confirmation: true
      # List of NBT paths we should check before removing item from inventory. Each line should start with NBT: this is for the future updates which will involve aditional optional checks
      Exclude:
      - NBT:ItemJoin Name
      - NBT:ItemJoin.Name
```
<img width="572" alt="Screen-Shot 2022-10-15 at 09 36 36" src="https://user-images.githubusercontent.com/28841349/195975199-41fc9705-d204-438b-b57d-c5e6a375c7ec.png">

Cleartype could be used perhaps to limit it to things. 

And the `item:`
