### DISCUSSION TITLE
l

### DISCUSSION THREAD

**Discussion by ghost** [Zrips/CMI#7010] [Feature Requests]

**Comment by mrfloris** [comment]
You can perhaps already do this, using the combination of eventcommands.yml and specialized commands. 

```yaml
quitServer:
  Enabled: false
  Commands:
  - cmi msg [playerName] This is event command example!
  - cmi actionbarmsg [playerName] This is event command example!
```

You can enable this, and then use CMI's SC features: <https://www.zrips.net/cmi/commands/specialized/> like check: to check against a placeholder or something, maybe ifinworld:pvp!  .. something like that. 

A placeholder you can try: `%cmi_user_inpvp%`

The question of course is, if they are quitting, how VALID are these placeholders and checks, do they check BEFORE they leave or is the data then 'offline user', and you can't even kill them ?

If we have the answer to that, we can perhaps do something like 
```yaml
- 'check:%cmi_user_inpvp%==true! ifinworld:pvp! asFakeOp! cmi kill [playerName]'
```
UNTESTED, I am just thinking out loud here
