### DISCUSSION TITLE
Chat format

### DISCUSSION THREAD

**Discussion by jugandomiguel** [Zrips/CMI#7130] [Feature Requests]
a chat format to show the initial of the world where a user is. Let me explain 
[world] player: test
[W] player: test  < I want like this

**Comment by CloudeLecaw** [comment]
So sounds like a list where you can define own Alias for worlds where the player is in.

This would need a whole new list inside the config where we can define the alias.

So i suggest placeholder **%cmi_user_world_alias%**
When used, for example in chat format then the alias defined for this world is parsed
if no alias exist in the list then simply the real worldnameshould shown, to be compatible in case a world was forgotten to add.
or if new worlds found it may could auto add this world and set the first Letter of it by default if the user does not change it. (may optional config) Adding Colorcodes and may hex? should be supported
How this could look like in config:

```
#define worldalias shown with placeholder %cmi_user_world_alias%
WorldAlias:
  autoAddWorlds: true
  #set worlds: [] if you have no worlds where an alias is used
  worlds:
    #you can add more worlds here. &-Colorscodes, {#Hexcolors} and CMIs gradient useage are supported
    - world:{#green}W
    - world_nether:&cWN
    - world_the_end:{#red>}WND{#yellow<}
```
