### DISCUSSION TITLE
Idea for cmi

### DISCUSSION THREAD

**Discussion by AugustDeplazza1** [Zrips/CMI#7185] [Enhancement]
1. Add a scoreboard to the cmi plugin with the function of changing the scoreboard by region example: Location world, location lumberjack, location mine. 2. Add a backup system with support for Google drive, Yandex drive and other types of storage.

**Comment by dan28000** [comment]
1. might happen someday 
2. no

**Comment by mrfloris** [comment]
i would love for a super basic scoreboard in cmi, that has hex color support, and like 10 configurable lines that take placeholders, and that's it.. 

```yaml
scoreboards:
 # true = shows scoreboard
 enabled: true
 # show when the player logs in? (false means they can perhaps still toggle it on, but wont show by default - if per player is false, it will show on login regardless of true/false)
 show-login: true
 # true means the player can /cmi scoreboard toggle|true|false, false means it will always show
 per-player: true
 # config (how it looks)
 divider-line: "-------"
 default-title: "cmi scoreboard"
 show-online-players?: true
 show-world?: true
 show-pos?: true
 show-balance?: true
 show-jobsreborn-levels?: true
 show-mcmmo-powerlevel?: true
 # custom-config:
 line-1: ""
 line-2: ""
 line-3: ""
 line-4: "<<divider>>"
 line-5: "don't forget to vote;;asConsole! votelink [playerName]"
 line-6: "join our discord;;asConsole! cmi msg [playerName] {#gold}discord.gg/floris"
 line-7: "<<divider>>"
```
