### DISCUSSION TITLE
CMI Portals - Cooldown Period

### DISCUSSION THREAD

**Discussion by VimaMT** [Zrips/CMI#7218] [Feature Requests]
On my wish list:  A cool-down period that can be used with each CMI portal per player. This would prevent players from using the RTP functions attached to the portals to bypass the configured RTP cooldown periods.

**Comment by MrCrazys** [comment]
> On my wish list: A cool-down period that can be used with each CMI portal per player. This would prevent players from using the RTP functions attached to the portals to bypass the configured RTP cooldown periods.

You can just add `cooldown:[timeInSec]! [command]` to the portal's commands. Unless I've misunderstood you.

**Comment by CloudeLecaw** [comment]
Well see here..we use a delay as last one, that works also like a cooldown ;)

```
  ANI-PortalWithoutUse:
    Loc: -80.0:63.0:270.0:-80.0:70.0:270.0
    enabled: true
    effect: Reddust
    color: 8224125
    showParticles: false
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - msg! [playerName] §f You run over a goldblock...
    - delay! 2
    - msg! [playerName] &f You hear a noise......
    - cmi sound block_amethyst_block_fall [playerName] -s
    - delay! 1
    - cmi sound block_amethyst_block_fall [playerName] -s
    - delay! 1
    - cmi sound block_amethyst_block_fall [playerName] -s
    - delay! 2
    - check:%cmi_iteminhand_type%!=stone_sword! msg! [playerName] &f ...but nothing happens....
    - check:%cmi_iteminhand_type%==stone_sword! cmi sound entity_lightning_bolt_thunder:1:1 -all -s
    - delay! 114
```
u will see after you used it. you cant use it aggain until the delay is over.
