### DISCUSSION TITLE
Random Teleporting respecting player claims

### DISCUSSION THREAD

**Discussion by mrfloris** [Zrips/CMI#7258] [Enhancement]
It would really help if /cmi rt would respect claims - and avoid them (or allow them), in betterrtp I currently use something like this:
```yaml
  Respect:
    hClaims: false
    GriefDefender: false
    UltimateClaims: false
    KingdomsX: false
    Lands: false
    Residence: false
    FactionsUUID: false
    WorldGuard: true
    GriefPrevention: false
    Towny: false
    RedProtect: false
```
Which makes sure that someonecan land nearby a region, but the rt attempt will skip the location if it's part of a region from say worldguard or residence or lands, etc.
