### DISCUSSION TITLE
Trash Command

### DISCUSSION THREAD

**Discussion by FrancyMak** [Zrips/CMI#7310] [Feature Requests]
One thing that is missing, in my opinion, is the /trash command. Currently if you want to get it you have to download another plugin and some servers want to give this command to VIPs.

It is a simple GUI where you enter objects and, with a little timer, they are deleted.
It would be yet another plugin that CMI incorporates.

**Comment by T14D3** [comment]
/dispose is exactly that, if you want it to be /trash just create a custom alias

**Comment by mrfloris** [comment]
How to make a trash bin: https://faq.cmi.support/trash

**Reply by FrancyMak** [reply]
I had forgotten to respond.

I had forgotten that CMI had this command as well, I have studied it quite a bit and among all the things in my head about it I must have missed it.

I really didn't remember that there was a dispose command hahaah.

**Reply by mrfloris** [reply]
you can even use interactive command signs feature with [trash] on it, that will open the cmi dispose GUI :) 

```yaml
InteractiveCommands:
  # Regex used in recognizing public interactive commands used in signs
  # Default format is [ic:[icName]] in example [ic:trash]
  # If you want clean format use regex like: (\[([a-zA-Z0-9]+)\])
  SignRegex: (\[([a-zA-Z0-9]+)\])
```
`config.yml`

```yaml
trash:
  Locations:
  - cave;261.0;64.0;-508.0
  - wild;1309.0;80.0;1485.0
  - wild;1324.0;95.0;1552.0
  - wild;1333.0;72.0;1483.0
  - wild;1313.0;93.0;1604.0
  - general;11797.0;64.0;-12358.0
  - wild;1325.0;92.0;1602.0
  - wild;1341.0;94.0;1538.0
  - wild;1283.0;80.0;1464.0
  - general;-6179.0;11.0;-2814.0
  - wild;1393.0;73.0;1484.0
  - general;-16495.0;72.0;11642.0
  - wild;1326.0;126.0;1461.0
  - wild;1263.0;75.0;1483.0
  - wild;1374.0;81.0;1535.0
  - wild;1344.0;100.0;1495.0
  - wild;3585.0;59.0;3353.0
  - wild;1331.0;111.0;1469.0
  - wild;1336.0;110.0;1477.0
  - wild;1282.0;80.0;1487.0
  - cave;-256.0;64.0;6.0
  - wild;1297.0;80.0;1602.0
  - general;12032.0;65.0;19098.0
  - general;-14778.0;69.0;12450.0
  - general;-12601.0;63.0;-12149.0
  - general;12752.0;32.0;12008.0
  - general;12701.0;77.0;-18303.0
  - wild;1263.0;75.0;1484.0
  - wild;3582.0;63.0;3345.0
  - general;10275.0;13.0;-751.0
  - general;12192.0;70.0;11800.0
  - wild;1341.0;82.0;1463.0
  - wild;1418.0;94.0;1538.0
  - wild;1278.0;81.0;1489.0
  - general;12423.0;79.0;-5300.0
  - wild;1314.0;92.0;1599.0
  - wild;1398.0;75.0;1462.0
  Commands:
  - click:rightclick! asConsole! cmi dispose [playerName]
  SignLines:
  - '{#Cerulean}[trash]'
  - '{#Edward}~~~~~~~~~~~~'
  - '{#Feijoa}Double-check'
  - '{#Feijoa}what you dispose'
  Public: true
  ReqPerm: false
```
`interactiveCommands.yml`

<img width="1219" alt="Screen-Shot 2022-10-19 at 17 31 57" src="https://user-images.githubusercontent.com/28841349/196737504-6fd1ed89-19cb-4086-92d3-e6fcc8a4de46.png">

(the locations in that code is just for my live server, you only need 1 first)
