### DISCUSSION TITLE
A config options for Jail command

### DISCUSSION THREAD

**Discussion by shovelbug** [Zrips/CMI#7319] [Feature Requests]
would be nice to disable a few things about the jail command, such as making it so jailed players can interact with chests and their inventory and to be able to place and break blocks while in the jailed area......I am trying to make a jail where they all have their individual cell which the plugin is great for, i want a perma jail the plugin makes it so they can never leave the jail area but can leave their cells which is also perfect, but i want to have my perma jailed player have stuff to do such as farm crops and cook food, and equip and unequip smuggled goods.....and handle mail room duty....its also perfect because the chat limits their range within the chat so only nearby players can hear them which is awesome.....i found a way to enable pvp within the jail which is perfect

**Comment by CloudeLecaw** [comment]
you allready have this:

```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 20
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true
  # Do you want to prevent players damage while he is in jail
  PreventDamage: false
  # Do you want to prevent players hunger while he is in jail
  PreventHunger: false
  Commands:
    # Commands to be performed when player gets jailed
    OnJail:
    - asConsole! cmi usermeta [playerName] add pexrang %cmi_user_group% -s
    - asConsole! pex user [playerName] group set Gefangener
    - delay! 1
    - asConsole! cmi tablistupdate
    # Commands to be performed when player gets unjailed
    OnUnJail:
    - asConsole! pex user [playerName] group set %cmi_user_meta_pexrang% -s
    - asConsole! cmi usermerta [playerName] remove pexrang -s
    - delay! 1
    - asConsole! cmi tablistupdate
  WhiteListedCmds:
  - cmi msg
  - w
  - pm
  - whisper
  - tell
  - say
  - msg
  - help
  - ticket
  - wiki
```
+ you have command when jails and unjailed.

If your players can break or place blocks in your jail it looks more like a misconfigrated protection zone from your protection plugin...

**Reply by shovelbug** [reply]
the issue is by default players in jail cannot interact with blocks at all (build or place blocks, they cannot receive damage but if i put PreventDamage: false they can deal damage but damage cannot be dealt to them i want my prisoners to be able to fight eachother, i want prisoners to be able to mine blocks in the mines and tend to farms i basically only want the option to force them to stay in the area active and the commands to run on /jail and /unjail i want to disable the other protections (i also like the proximity options for the chat) i can also enable hunger for them but they cannot eat food that is in their inventory and cant pickup items that are on the ground

**Reply by shovelbug** [reply]
when i go to use /cmi kill playername here, on a jailed player it tells me i need to do /cmi kill playername -forced because they are protected, which shows me the jail is putting them in a sort of godmode while they are jailed

**Reply by shovelbug** [reply]
im asking that we get more options for configuring the jail command as there is only so much we can do with the current /jail, i want my jailed players to not be bored in the jail but still feel punished......also a side note is there a way to exempt prisoners from the discordsrv relay because their messages still come through there i want no one to see what they say unless they are in that 20block radius

**Comment by CloudeLecaw** [comment]
well on our server we puted them in a jail where they can do all things like the other.
but when they die they respawn in the jail because they are in the prisioner group as long as they are jailed.
the commands to set them to this group are done by the jail command and they get back to normal when they are unjailed. (their original rank is stored in a usermeta set with cmi to the player as long as they are jailed.)
So all the limitations u spoke of are technicly just a question of your protection plugin and its areas.
the rest needs to be done by your permission system.
all you do with cmis jail in this case it set a respawn point for a jail group that is defind in your permission system ans save the rank in a usermata as long they are jailed so you can move them to an other permissiongroup and back later on unjailing. what they can do now and what not would only be a thing of your setted permissions.
check the settings for the ChatRange in the jails config and set it to 20 to have your 20 blocks arround the player

**Reply by shovelbug** [reply]
i literally just tested my only protection plugin is worldguard, i can show you if you dont beleive me upon being jailed (and i made a new jail just to test this) and i made sure it wasnt in a worldguard region i tested and player damage works in the area before being jailed and i can pickup and throw items before being jailed, but 100% upon being jailed i can deal damage but cannot receive damage, i cannot pickup or drop items, only difference was being jailed

**Reply by shovelbug** [reply]
and once again if i use /cmi kill it says "Can't kill, protected by another plugin, game/god mode. Use -forced variable

**Comment by CloudeLecaw** [comment]
and set preventdamage  and hunger to false

**Reply by shovelbug** [reply]
i did, with hunger to false they get hungry but with damage to false they can hit other players but still cannot receive damage

**Comment by shovelbug** [comment]
can i dm you on the discord? i can send you photos and if your up to it you could check out the issue on the server

**Reply by shovelbug** [reply]
i can also try to make a video of the issue with my config and examples of someone unjailed and jailed in the same area

**Comment by shovelbug** [comment]
```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 20
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true
  # Do you want to prevent players damage while he is in jail
  PreventDamage: false
  # Do you want to prevent players hunger while he is in jail
  PreventHunger: false
  Commands:
    # Commands to be performed when player gets jailed
    OnJail:
    - skinsrestorer:skin set %player_name% prison
    # Commands to be performed when player gets unjailed
    OnUnJail:
    - ''
  WhiteListedCmds:
  - cmi msg
  - cmi reply
```
