### DISCUSSION TITLE
Temp Nicknames that auto expire after X time

### DISCUSSION THREAD

**Discussion by TomLewis** [Zrips/CMI#7350] [Enhancement]
Off the back off this https://github.com/Zrips/CMI/discussions/7347

Can we also please have temporary nicknames, ones that expire after X time, so that we can set and forget and it'll automatically remove them for us.

This could be used in a plethora of ways.
- Temp nicks until a player changes their nickanme as they have to wait 30 days
- Events, where we have something happen where we want a nickname to be on for a short time

**Comment by MrCrazys** [comment]
You could probably use a custom alias for this, maybe with a delay?

**Comment by TomLewis** [comment]
How would that work? What plugin would be tracking the time until removal?

**Reply by MrCrazys** [reply]
> How would that work? What plugin would be tracking the time until removal?

Well, you could probably use a custom alias like:
```yaml
  tempnick:
    Cmds:
    - statement:check1! check:$1!=null!
    - if:check1! check:$2!=null! check:$3!=null! asConsole! cmi nick $1 $2
    - delay! $3
    - asConsole! cmi nick off $2
    - 'if:check1@! msg! [playerName] {#gold}Correct usage: /$0 <nickname> <player>
      <time>'
    - 'check:$2==null! msg! [playerName] {#gold}Correct usage: /$0 <nickname> <player>
      <time>'
    - 'check:$3==null! msg! [playerName] {#gold}Correct usage: /$0 <nickname> <player>
      <time>'
    Perm: true
 ```
Might just need a little bit of tweaking, depending on your needs. I just made it in 5 minutes.

The only real problem is that you can only run it once. I suppose `/cmi tempnick` could be useful in this case.
