### DISCUSSION TITLE
Cmi overrides Litebans

### DISCUSSION THREAD

**Discussion by rageyh** [Zrips/CMI#7362] [Feature Requests]
Hi, I noticed that the ban / warn commands of cmi override those of Litebans, is it possible to disable the punishments of CMI so that I can use those of Litebans? Thank you

**Comment by SickProdigy** [comment]
It's in the default config to disable the commands.
```
Warnings:
  Default:
    LifeTime: 86400
    Points: 1
    DefaultReason: '&7Violated server rules'
  Categories:
    Swear:
      LifeTime: 86400
      Points: 3
      DefaultReason: '&7Swearing'
    Grief:
      LifeTime: 86400
      Points: 10
      DefaultReason: '&7Griefing'
    Bug:
      LifeTime: 86400
      Points: 30
      DefaultReason: '&7Using bugs'
    Cheat:
      LifeTime: 86400
      Points: 50
      DefaultReason: '&7Using cheats'
  Perform:
    '3':
    - cmi mute [playerName] 10m
    - cmi msg [playerName] !&cMuted for &710 &cminutes for getting &73 &cwarnings!
    '5':
    - cmi kick [playerName] &cKicked for getting 5 warnings!
    '10':
    - cmi tempban [playerName] 5m &cTemporary banned for getting 10 warnings!
```

Just change the last lines to look like so

```
  Perform:
    '3': []
    '5': []
    '10': []
```


And it won't perform the command after warns were used.
but why use liteban over cmi really? CMI has everything integrated together.

If i'm not mistaken there are ways to load different plugins in certain orders so 1 will have precedence or weight over the other.

Hope this helps.
