### DISCUSSION TITLE
Prevent items from Renaming

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7372] [Enhancement]
Currently we allready have a protection that allows us to set names that are forbitten to set as name.

In this example the Stonesword is forbitten to be called Maltes Schwert. This allredy allows us to not rename a vanilla item into a rare item. 
```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # Defines maximum length of item name excluding color codes for itemname command
  # Set it to 0 if you want to remove restrictions
  MaxLength: 64
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
  - ender_chest
  - chest
  - stone_sword:(Maltes Schwert)
```

What this does not prevent is that you gave a rare item an other name like sADasfdd and may destory the rare item this way.
A lot of plugins look for the itemname and lore and if one of both does not match the item become invailed.

So what i want is a secound list that forbit renaming of choosen items.
This is how it could look in config
```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # Defines maximum length of item name excluding color codes for itemname command
  # Set it to 0 if you want to remove restrictions
  MaxLength: 64
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
  - ender_chest
  - chest
  - stone_sword:(Maltes Schwert)
    # items on the Blacklist are prevented from renaming. this is usefull if you got rare items that you want to prevent from renaming completly
  Blacklist:
  - stone_sword:(Maltes Schwert)
```

In this premade example the stonesword called Maltes Schwert cant be renamed (only with the bypass permission) to anything else because its on the blacklist.

+ **the old function that allready exist** -> noone without the bypasss permission can rename the stonesword to Maltes Schwert (except ranks with bypass permission)

+ **the new thing that would be needed** -> noone can rename a stonesword if its called Maltes Schwert (except ranks with bypass permission)
