### DISCUSSION TITLE
Or (|] Feature for Custom Alias to define multiple commands for one Custom Alias

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7380] [Enhancement]
I want to create a custom alias that can be run by one of the 3 different command and all should do the same.
in this examples i call them:
/1
/2
/3

at the moment this would lead us to a Custom Alias creation like this:

```
  1:
    Cmds:
    - cmi helpop $1-
    Perm: false
    Tab: false
    CustomTabs:
    - ''
  2:
    Cmds:
    - cmi helpop $1-
    Perm: false
    Tab: false
    CustomTabs:
    - ''
    Cmds:
    - cmi helpop $1-
    Perm: false
    Tab: false
    CustomTabs:
    - ''
```

Shorter and smater would be if we had the option to define a | (OR) so we could give more aliases to one Custom Alias like this

```
  1|2|3:
    Cmds:
    - cmi helpop $1-
    Perm: false
    Tab: false
    CustomTabs:
    - ''
```

It happens very often that you define 2 or more CAs that do the same thing just to have an other optional /command
Examples: own made /help wiki     and  /wiki     and may  /wikipedia       3 command that would printout the wiki url.
