### DISCUSSION TITLE
Required arguments in custom alias

### DISCUSSION THREAD

**Discussion by Bloodlex** [Zrips/CMI#7381] [Feature Requests]
Hey,

I'd like to ask if there is any possibility to set required number of arguments for a Custom Alias? 🙂 

I've seen this discussion, but seems nobody replied:
[https://github.com/Zrips/CMI/discussions/4552](https://github.com/Zrips/CMI/discussions/4552)

Thanks for your help!

**Comment by CloudeLecaw** [comment]
sure just add a null check for the argumentnumber you wish to have.
for example you want that your command has mini 4 arugments
So add the check `check:$4!=null!` into your commands
now add an extra line with something like `check:$4==null! msg! [playerName] &cSorry, But you need to use at least 4 words!`

**here a little example:**
(permission for it is: _cmi.customalias.pm_)
the example send a private meassae to a player but only if he used at least 4 words. Elese it give him a feedback he did not use enough words.

```
  pm:
    Cmds:
    - check:$4!=null! cmi msg $1-
    - check:$4!=null! msg! [playerName] &aThe Meassage was sendet successfully!
    - check:$4==null! msg! [playerName] &cSorry, But your meassage was not sendet. You need to use at least 4 words!
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername]'
```
