### DISCUSSION TITLE
Custom Alias multiple words custom tab autocomplete

### DISCUSSION THREAD

**Discussion by Bloodlex** [Zrips/CMI#7595] [Q&A]
Hey,

I'd like to create a CustomAlias for "**/jobs join jobName**" command in order to translate it and autocomplete.

praca dolacz:
    Cmds:
    - jobs join $1
    AddTabs: true
    CustomTabs:
    - Drwal
    - Farmer

But the autocomplete doesn't work and doesn't suggest this after "**praca dolacz HereShouldBeAutocomplete**"

The general question is, if I can have autocomplete custom tab after a command consisting of 2 words.

Is it possible to do? Thanks so much for your help! 🙂

**Comment by CloudeLecaw** [comment]
this is allready possible
here an example
```
  examplecmd:
    Cmds:
    - msg! [playerName] $1-
    Tab: true
    CustomTabs:
    - '[playername],11,12,13, 21,22,23, 31,32,33' 
```
it works like
Word1forArg1,Word2forArg2, Word1forArg2,Word2forArg2

a comma after the first worrd means its for the same Argument. if you use a space after the comma then you set the words for next Argument

word,word,word, word2,word2,word2,etc..
