### DISCUSSION TITLE
Improvents of | for hasitem check

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7644] [Enhancement]
hasitem:[value][@][?][#]!

I want to create a fastcooking command that cooks every cookable item from the whole inventory.

it works with the hasitem check to check if it still should contain cooking by repepeating the command.
what sound cool in first moment and works if you only have may 500 of items is a bit horrible in the way i released it because in worst case it runs to many instanced what can result in cmi fails to continue the alias.

This is the current one.
```
  test_cook:
    Cmds:
    - item:beef-1! asConsole! cmi give [playerName] cooked_beef 1 -s
    - item:rabbit-1! asConsole! cmi give [playerName] cooked_rabbit 1 -s
    - item:mutton-1! asConsole! cmi give [playerName] cooked_mutton 1 -s
    - item:chicken-1! asConsole! cmi give [playerName] cooked_chicken 1 -s
    - item:potato-1! asConsole! cmi give [playerName] baked_potato 1 -s
    - item:cod-1! asConsole! cmi give [playerName] cooked_cod 1 -s
    - item:salmon-1! asConsole! cmi give [playerName] cooked_salmon 1 -s
    - hasitem:beef-1 asPlayer! test_cook
    - hasitem:rabbit-1 asPlayer! test_cook
    - hasitem:mutton-1 asPlayer! test_cook
    - hasitem:chicken-1 asPlayer! test_cook
    - hasitem:potato-1! asPlayer! test_cook
    - hasitem:cod-1 asPlayer! test_cook
    - hasitem:salmon-1! asPlayer! test_cook
    Perm: true
    Tab: false
```

what would be much smarter if i could have an | check for has item like we have it for the regular check argument to avoid running massive amount of multiple instances in worst case.

The alias could run with one instance only and look like this:
```
  test_cook:
    Cmds:
    - item:beef-1! asConsole! cmi give [playerName] cooked_beef 1 -s
    - item:rabbit-1! asConsole! cmi give [playerName] cooked_rabbit 1 -s
    - item:mutton-1! asConsole! cmi give [playerName] cooked_mutton 1 -s
    - item:chicken-1! asConsole! cmi give [playerName] cooked_chicken 1 -s
    - item:potato-1! asConsole! cmi give [playerName] baked_potato 1 -s
    - item:cod-1! asConsole! cmi give [playerName] cooked_cod 1 -s
    - item:salmon-1! asConsole! cmi give [playerName] cooked_salmon 1 -s
    - hasitem:beef-1|rabbit-1|mutton-1|chicken-1|potato-1|cod-1|salmon-1! asPlayer! test_cook
    Perm: true
    Tab: false
```

So i wanne ask if you could add this | check for hasitem <3
