### DISCUSSION TITLE
need item rename blacklist

### DISCUSSION THREAD

**Discussion by ProtoGhost** [Zrips/CMI#7725] [Feature Requests]
Hi, I'd like to request you to add a feature where we can blacklist certain names in itemrename. We use plugins that make use of itemnames for its property. so it seems like players with rename access can easily exploit it. So can u please add the said feature? will be really helpful. Thanks!

**Comment by CloudeLecaw** [comment]
Whats with this feature? (Config)

```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
  - ender_chest
  - chest
```

**Comment by ProtoGhost** [comment]
ItemRenaming: # When set to true, players will be denyied from renaming defined items in anvil or with itemname command # Option to define specific name by using regex format # Can be bypassed with cmi.anvil.itemrename.bypass Prevent: true # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material # This can be bypassed with previous permission node 
GlobalDisable: false # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else 
List: - mobspawner:([A-z]+ (?i)\w*spawner) - ender_chest - chest
names-blacklist:
          names: [] #names can be added as string to either blacklist those names from being named or only whitelist those names
           whitelist: #when set to true all above given strings will be added as a whitelist so items can only be renamed to those given strings.. When set to false given strings will act as a blacklist 

MAIN USE - Helps to deny people from naming explicit names to items

**Comment by mrfloris** [comment]
Why can't you use the existing blacklist?
Do you want a "chat filter" for item names? So they can't use hate speech or sexual explicit names on *any* item in the game?

**Comment by CloudeLecaw** [comment]
Its allready possible to blacklist items with its name there
you just need to enter the right regex.

Here an Example
![Snag_2c154d1](https://user-images.githubusercontent.com/12080017/158039799-a1f82b59-6719-4293-8671-319a53917f8f.png)

This is your Unique Item  called "Maltes Sword"
you want to block that noone can rename it.
First u need to know the sword is a stone sword..
well thats all what cmi needs

```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - stone_sword:(Maltes Schwert)
```

Now the Renameing of and to - the stone sword Maltes Sword is blocked for players

**Comment by Kiran-GC** [comment]
Hi , i'm an admin from the issue creator's server ( @ProtoGhost ) . The main reason we asked for the said feature is to block some existing exploits on our server. Yes i am aware that i can blacklist names for specific materials. But the issue is that one of the plugins we use makes use of ItemName to give the said powers of the item ignoring the material. Yes ik its the dumbest thing I've ever seen. So in short the plugin only checks for itemnames and not the material. which means that anyone can rename the item and get the effect of the item.(I hope this explained what  i meant.) We already did report this issue to the plugin dev but i also asked for a feature here just cause i thought it will be good to have a blacklisting feature for names since many players tend to add explicit names for items. Hope this cleared every doubts.

**Comment by CloudeLecaw** [comment]
outch..
The thing your plugin does is really one of the worst solutions i ever heared of.
But ok in this case i can unterstand why you wanee block just an itemname to give instead of renaming a choosen item

Welll still no nice behave of that plugin. your might really should ask the dev to add a material scan too.
be able to rename any item just to get effects can be dangerouse..

Well on our server we used Colored Items names for this and forbit our players renaming with the choosen color.

### **So let me clearfy your suggestion:**

What we would need is a new varriable for this Blacklist:
Something like: **_itemName:(Name)_**

This is how it could look to block whole name for all items

```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  # Use itemName(Name) to block the renamng for  all items
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
  - itemName:(Maltes Sword)
```
