### DISCUSSION TITLE
Enhancement of maintenance.

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7767] [Enhancement]
Currently when you mainten your sever then you just see the login meassage on login but no change of favion or servermodt so player woulds see ..ok server is not there before..
may it also would be nice to have a statusbar that tells the owners "server is in maintenance"
And it would be nice to have a own server picture taken for the maintenance.
when maintenance is running this picture (saved in image folder of cmi) should be seen instead of the default logo you see normaly.  when the maintanance ended. the default logo server-icon.png that is placed in the servers mainfolder normaly should be shown.

a placeholder that shows defined status depending if maintenance is on or not called
 `%cmi_servermaintenance_status%`
the placeholder could be used for design elements.

when hover in the servermodt line over the loggedin amount you normaly see the players logged in.
here when maintanence is turned on a little line should be shown instead if current name of logged in players.

Some actions for config:
```
servermaintenance:
  Enabled: false
  #Servericon shown when servermaintenance is on
  ServerMaintenanceIcon: maintenance-icon.png
  #Should ppl that allowed to stay/join the server see ActionbarInfo while servermaintenance is on
  showActionbar: true
  #Should player get kicked when servermaintenance is aktived?
  KickOnServerMaintenance: true
```

some strings for the langfile:
```
  serverMaintenanceSymbolOn: 'MAINTANCE ON'
  serverMaintenanceSymbolOff: ''
.
.
.
  serverMaintenance:
    serverMaintebanceMotd: '&c&nServer is in servermaintenance.'
    serverMaintenanceBar: '&c&nServer is in servermaintenance.'
    serverMaintanceKickMessages: '&c&nThe Server is now in maintenance'
    serverMaintanceVersionInfo: 'We are back soon!'
```

What is serverMaintenanceVersionInfo?  When you hover over the Pingbar off the Server then you see this line when server is in 
servermaintance mode.

We really need more options for the maintenance =)

The servermaintenance icon should be 64x64 pixel in png (like the one that can be used in the servers main folder)
