### DISCUSSION TITLE
Permission for TagCommands

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7834] [Enhancement]
Currently the Tag Feature can look like this:

```
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: true
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&e&l'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound block_note_block_harp:1:1 [playerName] -s
    - delay! 0.2
    - asConsole! cmi sound block_note_block_harp:1:1 [playerName] -s
    - delay! 0.2
    - asConsole! cmi sound block_note_block_harp:1:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```

i noticed. So see the name in the color in chat the player needs the permission:  cmi.tag.color
BUT to eecute the commands on Tag there is no permission...mean everyone can use them.
It would be nice to have a permssion like **cmi.tag.command** that is needed before the commands
get executed. So when Player1 writes the Names of Player2 then Player2 doent see the color and also
dont get effected by the commands. and when Player 2( that has the permission) writes the name of Player1
Player1's name gets markted and the commands get executed for him..

Instead of a new permission an other option would be that the commands would be part of the existing permission
cmi.tag.color.. but would make more sense in understanding it with a new one cmi.tag.command.

currently you have no option to not allow the tag commands get triggered for someone.. so pls extant this feature a bit <3
