### DISCUSSION TITLE
Option to enable disable scheduler by command expansion of the cmi schedule command.

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#7916] [Enhancement]
In some cases like when the server is in maintenance or some event where running. it would be nice to be able to
enable or disable choosen scheduler like defined announcers or processes you dont want in for some certain time.
when a scheduler could be turned on / off (enable thisable) this could be also added to automatism owners made on there server.

we allready have command called: `cmi schedule [scheduleName]` to trigger a schedule.
This might could be extanted a bit like `cmi schedule [scheduleName] (enable|disable)`
if the coammand is used like `cmi schedule [scheduleName]` then the schedule is triggered like it is now.

**Expansion with an command argument:**
When the command is used like `cmi schedule [scheduleName] disable`
then this disables the choosen schedule by setting the enable value in its setting to false.
When the command is used like `cmi schedule [scheduleName] enable`
then this enables the choosen schedule by setting the enable value in its setting to true.

The process after the command execution should be done "live" so it would need no /cmi reload or server restart to take effect.

**Comment by Dagrond** [comment]
This would be really nice enhancement. We could create even more complicated things with CMI!

**Comment by CloudeLecaw** [comment]
Well created a work arround for this to be able to do this with a plugin that creates placeholders
see here:

The Custom Alias:
```
  luluprotips:
    Cmds:
    - check:$1!=an|aus|null! msg! [playerName] &c Falscher Befehlsyntax. Benutzung&c:&c /luluprotips [an|aus]
    - check:$1==null! msg! [playerName] &c Falscher Befehlsyntax. Benutzung&c:&c /luluprotips [an|aus]
    - check:$1==an! phc setsilent LuluProTips true
    - check:$1==an! msg! [playerName] &e Die Lululand Protips wurden &baktiviert&e.
    - check:$1==aus! phc setsilent LuluProTips false
    - check:$1==aus! msg! [playerName] &e Die Lululand Protips wurden &cdeaktiviert&e.
    Perm: true
    Tab: true
    CustomTabs:
    - 'an,aus'
```

and here the schulder
```
BroadcastRandomLuluProtips:
  Enabled: true
  MinPlayers: 1
  FeedBack: false
  Delay: 5143
  Repeat: true
  Randomize: true
  Commands:
  - check:%phc_LuluProTips%==true! cmi ctellraw all <T>&b&l█&c  Luluprotipp  &b&l█  &eTiere können mit Hilfe einer &6Lululeine &6NUR &eaus der Farmwelt auf euer Grundstück geholt werden. Andere Transportwege und Transportrichtungen sind nicht möglich!</T>
  - check:%phc_LuluProTips%==true! cmi ctellraw all <T>&b&l█&c  Luluprotipp  &b&l█  &eDie &6Lululeine &ewird jedes mal verbraucht verbraucht, wenn ihr das gefangene Lebewesen wieder frei lasst. Ihr müsst euch dannach eine neue &6Lululeine &eerwerben.</T>
 ```

with the command we can change the placeholder...  what enables or disables the scheduler. but still it would be nice to have
a simple one command solution instead of our once.
