### DISCUSSION TITLE
'Musical' Mob Head Drops

### DISCUSSION THREAD

**Discussion by mercurialmusic** [Zrips/CMI#7953] [Enhancement]
As of 1.20 mob heads now have the ability to play a sound when placed on a note block. This is also fully customizable using vanilla mechanics, for example the following command:

```/give @p player_head{SkullOwner:{Id:[I;599583683,-557823658,-1930556164,-1165866836],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGU4YTM4ZTlhZmJkM2RhMTBkMTliNTc3YzU1YzdiZmQ2YjRmMmU0MDdlNDRkNDAxN2IyM2JlOTE2N2FiZmYwMiJ9fX0="}]}},BlockEntityTag:{note_block_sound:"minecraft:entity.ghast.death"}} 1```

will give you a player head with a ghast texture that plays the ghast death sound (incidentally this command also supports resource packs). It would be super cool if this ability could be integrated into CMI's CustomHeads.yml, with a sound variable under each EntityHead type, e.g.:

```
EntityHeads:
  creeper:
    DropChance: 0.1
    LowerWithEachDrop: 0.0
    Sound: "minecraft:entity.creeper.death"
    Heads:
    - 100:c-unpowered:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQyNTQ4MzhjMzNlYTIyN2ZmY2EyMjNkZGRhYWJmZTBiMDIxNWY3MGRhNjQ5ZTk0NDQ3N2Y0NDM3MGNhNjk1MiJ9fX0=
    - 100:c-powered:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjJjZWIzOWRkNGRlMjRhN2FkZmUyOTFhM2EwY2ZjN2NmNGY2NDVkZTU5YjYwM2ZjZmUwNmM2YjVhMDZlMjYifX19
```

Thanks for the consideration and for all your hard work!
