### DISCUSSION TITLE
Afk anpassen

### DISCUSSION THREAD

**Discussion by Michel13xx** [Zrips/CMI#8067] [Q&A]
Guten Tag

wo kann ich das anpassen oder gibt es das noch nicht?

![image](https://github.com/Zrips/CMI/assets/69007790/a2aa16ad-d874-47a5-bf6c-dca3b7e63d32)

würde das gerne auf deutsch an passen

**Comment by CloudeLecaw** [comment]
Also erstmal in englisch bitte.^^ Wir sind eine englisch sprachlich bevorzuge Community.
Und zweitens - nun zu deiner Frage: Doch, es lässt sich anpassen und sogar deaktivieren, wie du das magst.


So lets take a look at the translation file of CMI in the afk command translation part.

```
  afk:
    help:
      info: '&eToggle afk mode. Reason could be provided'
      args: (-p:playerName) (reason) (-s)
    info:
      # This only determines message in title message and not message shown in chat. For chat message check config.yml file
      afkTitle: '&eYou are now AFK'
      afkSubTitle:
      - '&2Don''t eat to much cookies!'
      - '&2Nice day for fishing'
      - '&2Afk, again?'
      - '&2Where are you?'
```

In config.yml - afk section your able to enable or disable the title and subtilte like you desire.
```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: false
  # When enabled shows random subtitle message
  SubTitleMessage: false
```

In adition you can send other messages and command defined in the config.yml afk section.

```
  AutoAfkCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName] wurde durch zulanges rumstehen AFK gesetzt.</H>
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName] hat folgenden Grund angegeben: %cmi_user_afk_msg%</H>'
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist nicht mehr AFK.</T><H>[playerDisplayName] war AFK wegen %cmi_user_afk_msg% für %cmi_user_afk_for%.</H>
```

----------------------------------------------------------------

Dont eat to muuch cookies! xD
