### DISCUSSION TITLE
The Midnight Schedule

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#8111] [Q&A]
Well i often got ask: "How do i define a schedule at midnight at a specific day of the month"

Well to be honest.. im not sure about this..

Does the CMI Schedule preform the midnight as 24:00:00  or as 0:00:00?
Does midnight itself counts for the end of the day or for the beginning of the next day?

So mostly it results in making me suggest to make a scheduler 1 secound after midnight or at 23:59:59 the day before starting with a delay of 1 secound :d

So lets say i want a schedule at 15th at midnight. normaly i would suggest
```
  PerformOn:
    '1':
      Day: 14
      Hour: 23
      Minute: 59
      Second: 59
  Commands:
  - delay! 1
  - command 1
```
```
or
  PerformOn:
    '1':
      Day: 15
      Hour: 0
      Minute: 0
      Second: 1
  Commands:
  - command 1
```

-----------------------------------------------------------------------------------

so how it would be for excacly midnight?
This one? (14th at 24'clock what is equal to 0'clock - end of the day)
```
  PerformOn:
    '1':
      Day: 14
      Hour: 0
      Minute: 0
      Second: 0
  Commands:
  - command 1
```
or
this one? (15th at midnight 0'clock - start of the day...)
```
  PerformOn:
    '1':
      Day: 15
      Hour: 0
      Minute: 0
      Second: 0
  Commands:
  - command 1
```

So the question here at least is - does the day for minecraft and its schulers starts at 0`clock or does it end at 24`clock?

Well would be nice to answer + with an example of the correct PreformOn Schedule.

Have a Nice day <3

**Comment by daoshii** [comment]
24:00:00 doesn't exist in cmi schedule or real life. That would be 00:00:00, which is the next day.
23:59:58 -- > 23:59:59 -- > 0:00:00

**Reply by daoshii** [reply]
And if you want a schedule, 1 second after midnight, that would be 00:00:01

**Reply by CloudeLecaw** [reply]
well i know about the one secound after one.. im using this one or the 23:59:59 one

So 0:00:00  would be automaticly the next day because 23:59:59 is the last secound of the day right?

So in that case
```
  PerformOn:
    '1':
      Day: 15
      Hour: 0
      Minute: 0
      Second: 0
  Commands:
  - command 1
```
would be at the beginning of the 15th and NOT at the end of the 15th

Is that right?

**Reply by daoshii** [reply]
You can tell time now.

**Reply by CloudeLecaw** [reply]
> You can tell time now.

We solved this with a work arround. we preform at 23:59:59 the day before and set a delay of 1 secound :D

So technicallythis one:
```
  PerformOn:
    '1':
      Day: 14
      Hour: 23
      Minute: 59
      Second: 59
  Commands:
  - delay! 1
  - command 1
```

 or this one:

```
  Delay: 1
  PerformOn:
    '1':
      Day: 14
      Hour: 23
      Minute: 59
      Second: 59
  Commands:
  - command 1
```
