### DISCUSSION TITLE
Command execution of Flightcharge reset

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#8118] [Enhancement]
Some Servers reported they have sometimes problems with the flightcharge
It sometimes happens to them that when their players reached flycharge of 0 that their players still can turn on flying until relog.

So i would suggest a command that can be set in flightcaharges config when the charges reach 0

This way we could define a command like turn of flight with the fly command when the charges reach 0 to guarantee that players flymode allways turns off.

To be compatible with current system it might should have a enable setting as well.

How this could look in the config.
```
FlightCharge:
  FlightChargeEnd:
    # When set to true a command is executed when flightcharges reaches 0
    Enabled: true
    # command to execute When Flightchanges reached 0 When FlightChargeEndCommand is enabled
    Command:
      - cmi fly [playername] false -s
```
