### DISCUSSION TITLE
Use locale for economy number format

### DISCUSSION THREAD

**Discussion by ErikSzabo** [Zrips/CMI#8135] [Enhancement]
So the main issue is that while you can specify the java decimal format (and even switch places option), you can't cover all languages with just these two options.

For example in the Hungarian language 10000.12 would look like this: 10 000,12
while in English US it is 10,000.12
switch places would turn this into: 10.000,12 which is better but still not what I need.
In java for example the Hungarian decimal format can only be achieved by specifying the locale as hu-HU or HU or something like that.
So an option for that would be really nice.

**Comment by CloudeLecaw** [comment]
you can edit the money format to your needs in config

```
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: ⛁
    # Format used for displaying money
    MoneyFormat: '###,###.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # This format is only for amounts which gets defines suffix like '1.23k' while numbers lover than 1k will use MoneyFormat
    shortNumbersFormat: '###,##0.0'
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: true
    # Placing of currency symbol
    Placing: '[money] [symbol]'
```
so if you need an other money format change it in the MoneyFormat line.

and if you need dots instead of comma and commas instead of dots you can use the setting.
SwitchPlaces

so if you want to use 1000000.22 then try out
`MoneyFormat: '######.00'` or just
`MoneyFormat: '#.00'`
