### DISCUSSION TITLE
ChatFilter censor (ChatFilter upgrade)

### DISCUSSION THREAD

**Discussion by JohnKillswitch** [Zrips/CMI#8147] [Enhancement]
Add option to disable seeing of swearing.

For example:
if player type "Hello SWEAR its me!" in chat for everybody who enable chat censor this message appear like "hello ***** its me!" but everybody who dont enable this feature can see a swear

**Comment by CloudeLecaw** [comment]
that is allready possible.
you can inform the swearer
you can disable the whole message
you can just replace the swaer word.
and also staff can gets informed.

**Comment by JohnKillswitch** [comment]
> that is allready possible
In this case, can you tell me how?

**Comment by CloudeLecaw** [comment]
```
   swearing02:
      Enabled: true
      Group: swearing
      InformConsole: true
      Regex:
      - \b(?i)(a+(\W|_?)+s+(\W|_?)+s+(\W|_?)+h+(\W|_?)+o+(\W|_?)+l+(\W|_?)+e+)
      ReplaceWith: ✪✪✪✪✪
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4hat geflucht.'
      Commands:
      - cmi msg [senderName] &eYou sweared with [message]
```
      # possible: none, others, all
      # Where 'none' means everyone will receive this message
      # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
      # 'all' means that no one will receive sent message
you see these settings if you use other thenthe swearer does not see that he sweared and if you want to inform the swearer you can do this in the command and use [message] in the command.
