### DISCUSSION TITLE
Head Username Blacklist /head Blacklist

### DISCUSSION THREAD

**Discussion by DeEthria** [Zrips/CMI#8176] [Feature Requests]
Good day.
Before I express my wish: Yes, I know that there is a permission to prohibit other players from creating a head of other players. But players should be allowed to do that.

My wish is that certain team member names cannot be created as a head. Team members are supposed to have value (economic servers), so a blacklist would be desirable.

For example:
head blacklist:
-xTronix
-Bloodymind

Players should receive the message “Unfortunately, you cannot create this head.”

Greetings xTronix

**Comment by CloudeLecaw** [comment]
well it would be nice of corse :D

in the mean time you could use the custom alias we talked about in discord :-)

```
CustomAlias:
  gethead:
    Cmds:
    - check:$1==Peter|ZergonxXx|Cloude_Lecaw! msg! [playerName] &cYou cant get &b$1s&c head!
    - check:$1!=Peter|ZergonxXx|Cloude_Lecaw#! check:$1==null! asConsole! cmi give [playerName] player_head{SkullOwner:[playerName]} 1
    - perm:cmi.customalias.gethead.others@! check:$1!=null! msg! [playername] &cYou dont have permission to get other players head!
    - perm:cmi.customalias.gethead.others! check:$1!=null! check:$2==null! asConsole! cmi give [playerName] player_head{SkullOwner:$1} 1
    - perm:cmi.customalias.gethead.others! check:$1!=null! check:$2!=null! asConsole! cmi give [playerName] player_head{SkullOwner:$1} $2
    Perm: true
    Tab: true
    CustomTabs:
    - '[playerName], 1,2,4,5,10,16,32,64'
``` 
permission: _cmi.customalias.gethead_  and   _cmi.customalias.gethead.others_
Command: _/gethead (playername) (amount)_
 Playername and amount is optional
