### DISCUSSION TITLE
needed Placeholders in delay of Specilazed Commands

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#8178] [Enhancement]
We often work with placeholders on our server.

We use many custom alias and others where we could benefit if delay! would allow to be combined with a numerical placeholder.

An Example:
The Placeholder %thisnumber% is prased with the 9 (a static placeholder)
The custom alias now should have a break between two commands depensing on the value of the placeholder.

It woulc look like this:
```
CustomAlias:
  TheCommand:
    Cmds:
    - broadcast! 1
    - delay! %thisnumber%
    - broascast! 2
    Perm: true
    Tab: false
```

With this the broadcast 2 would come 9 secounds after broadcast 1.

Currently its only possible to set a fixed delay number.

So it would be nice if we could use papisupported numerical placeholders for this feature. :-)
