### DISCUSSION TITLE
Books, signs and anvils' filter

### DISCUSSION THREAD

**Discussion by borjxrroyo** [Zrips/CMI#8185] [Enhancement]
**Description of issue or feature request:**

As the chat filter blocks words from the chat, it could be a great idea to block them in books, signs and anvils.

It could also be a good idea to replace all the phrase if it contains a bad word. So, for example:

If I write "Hello, bitch" the plugin could send "Replacement message" instead of "Hello, replacement".

**Comment by CloudeLecaw** [comment]
----------------------------------------------------------------------
> As the chat filter blocks words from the chat, it could be a great idea to block them in books, signs and anvils.

you mean a simliar to the plugin 
[Chat Filter - Sign Books and Anvils](https://www.spigotmc.org/resources/chat-filter-signs-books-and-anvils.81652/) just as extansion for the allready existring filers? 
This would be a nice to have inside CMI too :)
- in case of books it should replace the word if you close it
- in case of signs it should block placement and break sign if you modfi the text later
- in case of anvil it should cancel/breakup renaming of you try to take the item out of the anvil
----------------------------------------------------------------------
.
.

----------------------------------------------------------------------
> It could also be a good idea to replace all the phrase if it contains a bad word. So, for example:
> If I write "Hello, bitch" the plugin could send "Replacement message" instead of "Hello, replacement".

a full replacement is possible allready :-)
you can do this allready with cancel the meassage with blocktype all and execute a command for that like  `cmi sudo [playerName] c:I wanne tell you something` what will let the player say this chat meassage =)

here a little example:
```
      swearwordass:
        Enabled: true
        Group: swearing
        InformConsole: true
        Regex:
        - \b[aA]+[sS]+[sS]
        ReplaceWith: '*****'
        BlockType: all
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - cmi sudo [playerName] c:I wanne tell you something.
```
as vars for the comand you can use [playerName] or [senderName] in this case too, its upto you :-)


Description from the config:
```
      ipBlock:
        # If not set to true, this filter will not be used
        Enabled: false
        # Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
        Group: Advertising
        # When set to true, each time player triggers filter, console will receive information about who triggered it, which filter and with what message
        InformConsole: false
        # Regex expression to filter by. How to use regex https://regexone.com/
        Regex:
        - ''
        # With what we need to replace word, if not defined found expression will not be changed
        ReplaceWith: ''
        # possible: none, others, all
        # Where 'none' means everyone will receive this message
        # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
        # 'all' means that no one will receive sent message
        BlockType: none
        # When enabled rule will be applied to private messages
        includePrivateMessages: true
        # Players with cmi.chatfilter.inform permission will receive defined message when rule is broken
        msgToStaff: '&4!&6[playerName] &4advertising with: &r[message]'
        # List of commands to perform when rule is broken. Use [senderName] to include message sender name. Supports global variables same as locale file
        Commands: []
```
>
----------------------------------------------------------------------
