### DISCUSSION TITLE
Attempting to get left/right click to work with interactive holograms.

### DISCUSSION THREAD

**Discussion by Marotheit** [Zrips/CMI#8190] [Q&A]
Hi there.

I'm attempting to make an interactive shop hologram.

When the player left clicks, I would like to message the player some information about the item, and when the player shift right clicks, I would like to sell them the item if they meet the requirements. This is the hologram below, but I can't seem to get it to work. It seemed to be working just fine until I added in the left/right click statements, so I assume that's where the issue lies.

```
TestShop:
  Loc: Sanctuary;38.3;79.62;-41.46
  HoverParticles:
    Effect: COLOURED_DUST
    Count: 10
  Range: 8
  RangeExtra: 16
  Spacing: 0.24
  Interactable: true
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: CENTER
    TAlpha: 255
    Shadow: true
    Yaw: 270
    Pitch: 0
    Double: false
    BColor: '{#Black}'
    BAlpha: 0
    SL: 15
    BL: 15
  Commands:
  - statement:clicktype! click:left!
  - statement:requirements! click:rightshift! hasmoney:40! perm:weight.20!
  - if:clicktype! msg! [playerName] Here is some information about the item.
  - if:requirements! msg! [playerName] Thanks for your purchase!
  - if:requirements@! msg! [playerName] You do not meet the requirements to purchase this item.
  Lines:
  - '&6Test Item'
```

Any help would be greatly appreciated!

**Comment by CloudeLecaw** [comment]
this type of statement will not work in the hologram :3

well here a little example with the old methode. dont know if this alsoworks for the new display methode.

here is how it would look on our server..

```
IconRPBankerOpener:
  Loc: world;1725.0;70.5;1633.0
  Interval: 0.1
  LOSInterval: 0.1
  ShowParticles: false
  PageInterval: 0.1
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 3
  RangeExtra: 3
  Spacing: 0.24
  Interactable: true
  NewMethod: false
  RequiresPermission: true
  Commands:
  - '!leftclick! msg! [playerName] Here is some information about the item.'
  - '!shiftrightclick! hasmoney:40@! perm:weight.20! mag! [playerName] You do not meet the requirements to purchase this item.
  - '!shiftleftclick! hasmoney:40#! perm:weight.20! msg! [playerName] Thanks for your purchase!'
  - '!shiftrightclick! hasmoney:40! perm:weight.20@! mag! [playerName] You do not meet the requirements to purchase this item.
  Lines:
  - Banker
  - ICON:LODESTONE-1
```

Note: New Methode is for the clicking behave in holos it has not to do with the New DisplayMode
