### DISCUSSION TITLE
Add an optional permission requirement for PlayTime Rewards

### DISCUSSION THREAD

**Discussion by SenorFlamingo** [Zrips/CMI#8276] [Enhancement]
Even though you could technically do this already with specializedcommands, I think it would look cleaner if you could add an optional Permission option in the config files to check whether a player is eligible for a specific PlayTime Reward.

So if you were to implement a permission called plugin.lorem.ipsum for PlayTime Rewards, you would go from this:

```
hourly1:
  DisplayName: "&7Hourly reward"
  AutoClaim: true
  Description:
  - "&2Get reward for every hour you are online"
  - "&2Free heal and 20 bucks into your pocket"
  PayEvery: 3600
  Commands:
  - perm:plugin.lorem.ipsum! asConsole! cmi heal [playerName] -s
  - perm:plugin.lorem.ipsum! asConsole! cmi money give [playerName] 20
```

to this:

```
hourly1:
  DisplayName: "&7Hourly reward"
  PermissionReq: plugin.lorem.ipsum
  AutoClaim: true
  Description:
  - "&2Get reward for every hour you are online"
  - "&2Free heal and 20 bucks into your pocket"
  PayEvery: 3600
  Commands:
  - asConsole! cmi heal [playerName] -s
  - asConsole! cmi money give [playerName] 20
```
