### DISCUSSION TITLE
Warmup when entities are in X range

### DISCUSSION THREAD

**Discussion by MC-MrBirdy** [Zrips/CMI#8327] [Enhancement]
Having the option to enable a warmups when a specific entity type or group is within a certain range. This could allow specific commands to get a warmup in situations like potential danger, like how beds don't allow you to sleep when [enemies](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Enemy.html) are within 16 blocks. 

E.g. something like:
```
WarmUps:
  # [command]:[time]:[canmove]:[glyph]:[entity/group]:[range]
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: true
  showBossBarInfo: false
  List:
  - cmi tp:14:true
  - cmi back:14:false:null:phantom:32
  - cmi warp :7:false:null:enemy:16
  - cmi home :7:false:GlyphHead:enemy:16
```
