### DISCUSSION TITLE
numercial placeholder for scheduler delay

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#8390] [Enhancement]
We allready got the option to use a numercial placeholder in delay of speciazed commands.
It would be nice to have  also this option for Schedulers delays to have a random timer for some schedules.

Currently its not possible. the console trows a big error on reload if you try this (i asume because it does not exist for now)

Example:
```
BroadcastRandomLuluProtips:
  Enabled: true
  MinPlayers: 1
  FeedBack: false
  Delay: %cmi_random_1_10%
  Repeat: true
  Randomize: true
  Commands:
```
