### DISCUSSION TITLE
Schedules Announcer hover clickable

### DISCUSSION THREAD

**Discussion by ghost** [Zrips/CMI#8424] [Q&A] [answered]
Is it possible to create a Schedules containing a clickable hover? 
I tried using the MOTD variables but they don't work

![Captura de tela 2024-01-23 111326](https://github.com/Zrips/CMI/assets/134793210/44e9ce9e-3411-4c4e-a486-31abe4d710a8)

**Comment by CloudeLecaw** [comment, marked as answer]
use cmis ctellraw instead of broadast to have clickable messages.
The normal broadcast command was not made for these type of messages you desire.

Here is a little example for an announcers eah 10 minutes to show you how the cmi ctellraw can be used for it.

```
RandomAnnouncer:
  Enabled: true
  MinPlayers: 1
  FeedBack: false
  Delay: 600
  Repeat: true
  Randomize: true
  Commands:
  - cmi ctellraw all <T>&b&l█&c  Protip  &b&l█  &eJoin Our website today.</T><T>&b&l📋</T><H>Click here to get the link to our website.</H><URL>http://www.google.com</URL>
  - cmi ctellraw all <T>&b&l█&c  Protip  &b&l█  &eTo tade with other people use please use the trading channel</T><T>&b&l/Handel TEXT📋</T><H>click here to write into our trading channel.</H><SC>/handel </SC>
  - cmi ctellraw all <T>&b&l█&c  Protip  &b&l█  &eIf you forgot the way to the end, nether or farmworld you can use short commands to lead you a tour from spawn to the related portals.\n (These just can be used in the main world!&e:)\n</T><T>&eommands for starting the tour&e:&e</T><T>&b&l /farmworld📋</T><H>Click here to start your tour to the farmwolrd portal.</H><C>/farmworld</C><T>&e, </T><T>&b&l/nether📋</T><H>Click here to start your tour to the nether portal.</H><C>/nether</C><T>&e, </T><T>&b&l/end📋</T><H>Click here to start your tour to the end portal.</H><C>/end</C><T>&e.</T>
```

more infos about cmi ctext and cmi ctellraw you find here:
https://www.zrips.net/cmi/custom-text/
