### DISCUSSION TITLE
Add boolean placeholder for nickname

### DISCUSSION THREAD

**Discussion by NoltoxGit** [Zrips/CMI#8468] [Feature Requests]
Hello,
Can you add a new placeholder to know if the player have a nickname please ?

Usage of placeholder :
New `%cmi_user_nick%` return `true` if the player have a custom nickname.
 New `%cmi_user_nick%` return `false` if the player doesn't have a custom nickname.

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/discussions/new?category=enhancement

**Comment by CloudeLecaw** [comment]
here a little workarround if the placeholder you requested might not get added....
You could work with cmis usermetas on sever login of a player (eventCommands) to create a placeholder like you want.

```
joinServer:
  Enabled: true
  Commands:
  - check:%cmi_user_nickname%==%cmi_user_name%! asConsole! cmi usermeta [playerName] add nicked false -s
  - check:%cmi_user_nickname%!=%cmi_user_name%! asConsole! cmi usermeta [playerName] add nicked true -s
```
you also could use `%cmi_user_cleannickname%` instead of `%cmi_user_nickname%` to exclude colorcodes from this check so players could color their name and it still would count as playerName..

at least with this at joinServer, after the player loged in you could use `%cmi_user_meta_nicked%` to get a true/false result parsed from it.
You can also check the cmi usermeta list of a player by using the command `/cmi usermeta Playername list`
