### DISCUSSION TITLE
cmi_user_meta and cmi_user_metaint placeholder for other players

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#8544] [Enhancement]
currently we need to use papi expansions like parseother to get the usermeta into of an other player in checks.

here an example
```yml
  pongg_consolepart:
    Cmds:
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=1! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=33! asConsole! cmi broadcast !&4&l $1&2 hat als erstes die richtigen Wörter genannt und erhällt zwei &5&lMystery Boxen&5&l✩✩✩&2. &eHerzlichen Glückwunsch!
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=34! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=66! asConsole! cmi broadcast !&4&l $1&2 hat als erstes die richtigen Wörter genannt und erhällt 20 &5&lLulumanten&2. &eHerzlichen Glückwunsch!
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=67! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=99! asConsole! cmi broadcast !&4&l $1&2 hat als erstes die richtigen Wörter genannt und erhällt 30 &6&lTaler&2. &eHerzlichen Glückwunsch!
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=1! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=33! asConsole! gmysteryboxes give $1 2 3 msg=false
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=34! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=66! asConsole! mysterydust add $1 20 msg=false
    - check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%>=67! check:%parseother_{$1}_{cmi_user_meta_pingponggewinn}%<=99! asConsole! cmi money give $1 30 -s
    - asConsole! cmi usermeta $1 remove pingponggewinn -s
    Perm: true
    Tab: false
    CustomTabs:
    - ''
 ```
  It would be nice and more simple placeholder from CMI side to be able to parse out the meta of other players in checks for example.

therefor we would need an expansion of the two placeholders like  
**%cmi_user_meta_[METANAME]_[playerName]%**  and   **%cmi_user_metaint_[METANAME]_[playerName]%** 

the benefit i would see from these two placeholders would be the ability to not need other plugins or expansions for these
kinds of operations. specialy where cmis user mets are used more and more often in the process of all cmi tasks.

we have much much more crazzy commands where we read the meta of other players (mostly something like $1 if arument was set.
So i see a big benefit on having an option like this without the papi expansions that sometimes work not so fawless as wanted... when the placeholder is parsed.
