### DISCUSSION TITLE
Add cmi.command.gm.others theres no second permission for setting GM on other people.

### DISCUSSION THREAD

**Discussion by TomLewis** [Zrips/CMI#8606] [Enhancement]
On my creative, I give people access to /gm to test things as survival or check in spectate, but there's no permission to prevent them changing someone elses gamemode! can we get `cmi.command.gm.others`

**Comment by Zrips** [comment]
There is permission requirement already which is cmi.command.gm.others.[gameMode] you might have given players wild card permission node which give access to all gm actions which included option to change game more for someone else

**Comment by TomLewis** [comment]
Aha maybe the docs need updating then, wasnt in the permissions in the docs

I just set it like this;
```
- cmi.command.gm:
    value: true
    server: creative
- cmi.command.gm.survival:
    value: true
    server: creative
- cmi.command.gm.creative:
    value: true
    server: creative
```

Re-tested and it is working fine, I must have been on the wrong account testing as OP!
