### DISCUSSION TITLE
[Suggestion]  Hat Detection

### DISCUSSION THREAD

**Discussion by Nokrato** [Zrips/CMI#8639] [Feature Requests]
A good way to detect hats can be with Lore or NBT

```
DetectWorld:
  enable: true
  - "[HAT]"
  - "HAT" 
  - "&fhat"   
DetectNBT:
  enable: true
  - "hat:true"
  - "wear:true" 
```
