### DISCUSSION TITLE
Please add hex-colors to /afk

### DISCUSSION THREAD

**Discussion by Leahcimkrob** [Zrips/CMI#8797] [Feature Requests]
Please add hex-colors to your afk-modul.
![image](https://github.com/Zrips/CMI/assets/70509359/ab1d9060-f7bb-4130-b0ea-1be97e3ebde2)

**Comment by CloudeLecaw** [comment]
you can do thiss by using the command of afk and unafk
just use as command something like
`cmi ctellraw all <T>Your text</T>` the cmi ctellraw completly supports the cmi hex :-)
https://www.zrips.net/cmi/hex-colors/



on our server we made it like this:

```
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName] wurde durch zulanges rumstehen AFK gesetzt.</H>'
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName] hat folgenden Grund angegeben: %cmi_user_afk_msg%</H>'
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist nicht mehr AFK.</T><H>[playerDisplayName] war AFK wegen %cmi_user_afk_msg% für %cmi_user_afk_for%.</H>'
```

at least it looks like your hex format is wrong
