### DISCUSSION TITLE
Improvement usermetas feature.

### DISCUSSION THREAD

**Discussion by NoltoxGit** [Zrips/CMI#9039] [Enhancement]
Hello,
I use a lot of usermetas but i've a lot of problem too with this...

### 1. Have a file allow to define the basic value of a usermetas.
  - For example, I would like to have a file in `CMI/Saves/usermetas.yml`, and in this file I can define the `MY_CUSTOM_VALUE` and the default value for the placeholder `%cmi_user_meta_MY_CUSTOM_VALUE%`.
Exemple of this file:
```yml
# usermetas.yml file:
usermetas:
  MY_CUSTOM_VALUE:
    default_value: "0"
```

### 2. Improvement in the database.
- I use a lot of usermetas on my server, and getting them into my database is hell :c
  - Would it be possible to create a table just for usermetas, for example `CMI_users_usermeta`, and make a column for each existing usermeta?
