### DISCUSSION TITLE
warmups to aliases.

### DISCUSSION THREAD

**Discussion by illyrius666** [Zrips/CMI#9296] [Enhancement]
```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you don't want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5:false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  BossBarInfo:
    Enabled: false
    Color: purple
    # Options: 1, 6, 10, 12, 20
    Segments: '1'
  List:
  - cmi home :6:false:tpaWarmup
  - cmi rt:6:false:tpaWarmup
  - cmi warp :6:false:tpaWarmup
```
  
  when defining a alias like rtp for rt it bypasses the warmup set for rt.

**Comment by Zrips** [comment]
![image](https://github.com/user-attachments/assets/c39eac78-5673-4ede-bfe0-8c3c5005a066)
No issues as of testing with your example and custom alias as 
```
  rtp:
    Cmds:
    - cmi rt
```

**Reply by illyrius666** [reply]
aaaa i see, might have to do with this:
```
  rtp:
    Cmds:
    - rt $1-
```

**Reply by illyrius666** [reply]
okay it works now thanks!

**Comment by illyrius666** [comment]
another thing that i would need help with is this:
```
      "13":
        material: BLAZE_ROD
        customdata: 5
        stack: 1
        name: "&4&lThe Underworld"
        lore:
          - "&8▶ &7Click the item to rtp &8◀"
          - ""
          - "&8✖ &7Information:"
          - "   &3Environment: &6normal"
          - "   &3Gamemode: &dSURVIVAL"
          - "   &3Size: &63200&8x&63200"
          - "   &3Difficulty: &4HARD"
          - "   &3Claims: &cFalse"
          - "   &3PVP: &aTrue"
        commands:
          - rt world_nether
          - cpc   
```
          
          its a thing from commandpanels, should i add cmi in front of this to make it use the warmup?
