### DISCUSSION TITLE
Add the Ability to Ride Players via Right-Click

### DISCUSSION THREAD

**Discussion by BAD7777** [Zrips/CMI#9366] [Enhancement]
#### Suggestion:
Currently, players can use the `/ride` command to mount onto an entity, but I would like to suggest adding the ability to ride another player by right-clicking on them. This change would make it easier for players to mount onto others without needing to type the `/ride` command. Additionally, it would eliminate the need for the second player to use `/shakeitoff` since pressing `SHIFT` could still dismount the rider.

#### Proposed Implementation:
- Add an option in the settings to enable right-click riding of players.
- Allow a player to mount onto another by right-clicking on them, simplifying the process.
- Implement a configuration setting that limits the number of players that can ride a single player at the same time.

#### Example Settings for Configuration:
```yaml
Animations:
  # Enable riding players by right-clicking on them
  RightClickRide: true
  # Limit the number of players allowed to ride a single player at once
  MaxPlayersOnRide: 2
  # Remove player from the ride on damage or certain actions
  RemoveFromRideOnDamage: true
  # Optional: Allow players to dismount by holding SHIFT
  DismountWithShift: true
```

This would make the riding feature much more intuitive and user-friendly, enhancing the overall experience.
