### DISCUSSION TITLE
[Request] More maintenance design

### DISCUSSION THREAD

**Discussion by CloudeLecaw** [Zrips/CMI#983] [Enhancement]
Currently when you mainten your sever then you just see the login meassage on login but no change of favion or servermodt so player woulds see ..ok server is not there before..
may it also would be nice to have a blinking statusbar action that tells the owners "server is in maintanance"
And it would be nice to have a servermaintancesymbol as placeholder like for vanished/afk

Sone actions for config:
```
servermaintance:
  Enabled: false
  #Servericon shown when servermaintance is on
  Favicon: maintenance-icon.png
  #Should ppl that allowed to stay/join the server see ActionbarInfo whiles ervermaintance is on
  showActionbar: true
  #Should player get kicked when servermaintance is aktived?
  KickOnMaintenance: true
```

some strings for the langfile:
```
  servermaintanceSymbolOn: 'MAINTANCE ON'
  servermaintanceSymbolOff: ''
.
.
.
  servermaintance:
    servermaintanceMotd: '&c&nServer is in servermaintance.'
    servermaintanceBar: '&c&nServer is in servermaintance.'
    servermaintanceKickMessages: '&c&nThe Server is now in maintance'
    servermaintanceVersion: 'we are back soon'
```

What is servermaintanceVersion?  When you hover over the Pingbar off the Server then you see this line when server is in 
servermaintance mode.

We really need more options for this.

The servermaintance icon should be 64x64 pixel in png or this new Base64 format that is often used for head plugins too :)
