### ISSUE TITLE
Question: Jail Area Definition

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#1005]
How do I define a jail area so I can add cells to it? 

I have tried both selecting the area with the wood shovel and using world edit, but that doesn't work.
I can't create cells, because I'm not "in a jail area' even though I just created it.

**Comment by LogGits** [comment]
Cmi uses
```yaml
Selection:
  # Tool id to use for selection actions
  Tool: wood_hoe
```

Aka use a wooden hoe to select a region using cmi.

**Comment by Phyther** [comment]
This was the default I had... Unfortunately, this doesn't appear to be working. I define the area, Jails says the area is redefined, but when I try to make a cell, it says I'm not standing in the jail area.

```yml
Selection:
  # Tool id to use for selection actions
  Tool: wooden_shovel
```
