### ISSUE TITLE
bad jail config in config.yml

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#101]
Upgraded from 7.3.18.0 to 7.4.0.0 and see this in config.yml now.  Looks like check interval and command whitelist got smushed together...

```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval:
  - cmi msg
  - cmi reply
  # Defines default jail time when time is not povided with command
  DefaultTime: 300

```
