### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1015]
**Description of issue or feature request:**
When someone goes in /gmsp they automatically get permanent night vision. Can be toggled on and off via config. This would make it easy for staff members while watching potential xrayers/hackers in general.

**Comment by LogGits** [comment]
This can be done using AliasEditor or customalias.yml:
```yaml
  gmsp:
    Cmds:
    - gm 3 $1
    - cmi effect $1 night_vision 10000000 1
```
