### ISSUE TITLE
Portals - How to use with Bungee

### ISSUE THREAD

**Issue by JohOply** [Zrips/CMI#1024]
Hi guys

**Description of issue or feature request:**

First of all, i created some portals which work fine (from somewhere in my world to somewhere else, in the same server)

Now, I want to create a portal from my HUB to my other servers (for instance: GAMES).
I tried to create it like it explains here https://www.spigotmc.org/wiki/cmi-portals/

> Portals will work over bungeecord network and you can teleport players across your servers. How to setup portal? It cant be simpler. Make portal, open portal UI, click on set location button and you will get message in chat box. Travel to desired location, same server or on bungee (both servers should have CMI) and click on that message. You are done. Thats it... Travel to location and click on chat. No commands, nothing. Just like that.

I think I made something wrong because the behaviour is weird...

1/ I created portal without destination point (and without delay too). I was teleport to other server, so  it works fine. BUT, when player comeback to the HUB server, he is into the portal so it is not aesthetic.

2/ I edited the portal to add destination point (config below), the problem is I was not teleport to other server but to destination point only.. 

What I want:
- player is teleported through bungeecord
- when player comebacks to HUB, he is at his last location BUT NOT into the portal (before, I used AncientGates and it was the default behaviour)

I hope anyone has an idea :)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
Hub:
  H-E:
    Loc: -3.0:70.0:-29.0:3.0:77.0:-29.0
    enabled: true
    effect: reddust
    showParticles: false
    Tp:
      ==: org.bukkit.Location
      world: Hub
      x: 0.47350174544434487
      y: 70.0
      z: -24.470570804707176
      pitch: -4.200012
      yaw: -0.4510245
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - execute [playerName] ~ ~ ~ /playsound ENTITY.ENDERMEN.TELEPORT player [playerName]
    - delay! 1
    - send [playerName] games
#####################################
```
---

**Cmi Version (using`/cmi version`):** 8.0.21.2

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Thanks for reading
