### ISSUE TITLE
Forced SpawnOnJoin ignores YAW

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1029]
**Description of issue or feature request:**
Forced Join on spawn ignores its YAW position
The player spawns on the right position but wrong direction
This only happens if the player has `cmi.command.fly.safelogin` permission!

`/spawn` works normally
Pitch works normally too. Only YAW is affected.

**CONFIG SECTION:**
```
SpawnOnJoin: true
  Main:
    World: world
    X: 0.5
    Y: 64.0
    Z: 0.5
    Pitch: -8.0
    Yaw: 180.0
    RespawnLocation: true
    Rng: 0
```

**Cmi Version (using`/cmi version`):** 
CMI 8.0.21.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot 1.13.2
