### ISSUE TITLE
Login/Logout Not Changing

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#1048]
**Description of issue or feature request:**
I modified the Login/Logout messages and the message in-game is still the default message when a player logs in or logs out.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
LOCAL_EN.yml
  LogoutCustom: '&7[&c-&7] [&e[playerDisplayName] &cleft the game'
  LoginCustom: '&7[&a+&7] &e[playerDisplayName] &ajoined the game'

```

---

**Cmi Version (using`/cmi version`):** 
8.0.21.4
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
428
**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
Make sure you have changed this section in the config.yml to false (`Disabled: false`)
```yaml
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: false
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: false
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: false
  DeathMessage:
    # Defines number of players from which to automatically start hiding death messages
    # Set to -1 to disable this
    AutoHideFrom: -1
```
