### ISSUE TITLE
Auto-tab-complete hide command if player has no permission

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1092]
**Description of issue or feature request:**
Players who don't have access to specific commands are able to tab complete them in 1.13.x
Players see much commands they should not be able to see using /(tab). This should not happen.

(I'm not a dev but it's been said that the secret lies in the setup of plugin.yml)
Is it technically possible that this can be solved?

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Version independant

**Comment by LogGits** [comment]
Heya broski, I think this is what you are looking for:
```yaml
Alias:
  # When set to true, commands like /heal will not longer be accesible with tabcomplete for players without permision to use /cmi heal command
  ClearBaseCommands: true
```
