### ISSUE TITLE
ItemRename weird format

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1100]
**Description of issue or feature request:**
I noticed some item rename prevention issues. It adds `§r` at the front and a random `f` at the end. You will have to test this to see. This is a minor thing at most but i am just reporting it to keep track, incase we want to fix it in the future.
```yaml
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items
  # Option to define specific name by using regex format
  Prevent: true
  List:
  - mobspawner:((?i).+)
```
https://gyazo.com/5275615cc66d6c7e3c00ddb3630817f0
https://gyazo.com/69f4cfc78382f8c1761e3ce4294d6762

---

**Cmi Version (using`/cmi version`):** 8.2.0.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** build 456 1.13.2
