### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#1124]
Scheduler is not working
When i run the scheduler manually it works, but automatically on tge date it dont.

```
christmas_event_day2:
  Enabled: true
  PerformOn:
  1:
    Month: 12 
    Day: 2  
  Commands:
  - 'lp group default permission settemp wtk.event.christmas2 true 2d'

```
cmi  8.1.0.0
Spigot 1.13.2

**Comment by Zrips** [comment]
Its has wrong format, correct one should look something like
```
christmas_event_day2:
  Enabled: true
  PerformOn:
    '1':
      Month: 12
      Day: 2
  Commands:
  - lp group default permission settemp wtk.event.christmas2 true 2d
```
