### ISSUE TITLE
[Feature Request] Run command on first join

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#114]
Can you please add the feature to run a command through console on first player join

**Comment by LogGits** [comment]
Refer to the "eventCommands.yml" file:
```yaml
firstJoinServer:
  Use: false
  List: []
```
By default cmi runs these commands as console 🙂 
Example:
```yaml
firstJoinServer:
  Use: false
  List: 
    - kick [playerName] I like cats.
```
