### ISSUE TITLE
[Suggestion] Togglable Safe Teleportation for each TP command

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1171]
You should add a configurable toggle to enable/disable the feature that CANCELS teleportation if destination is unsafe (some server owners could use CMI for minigames, and maybe they want to spawn people in the air/lava) and a configurable toggle for the safe-teleportation cancelling the teleport event for each teleportation command in this fashion:

```
Safe-Teleport:
  tp: true # < true means it is enabled and it will cancel teleport on unsafe location
  tppos: false # < false means it will teleport regardless of the safety of the location
  tphere: false
```

You could add an API method to allow unsafe teleportation if you do not want to make it configurable, so that developers at least have control over this feature.

Cheers.
