### ISSUE TITLE
[Bug] Chat duplicates public messages over BungeeCord

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1183]
**Description of issue or feature request:**
I seem to have some problem with chat and BungeeCord. When I recieve the chat from another server it can spam sometimes, send the public message multiple times. Look at the image

![image](https://user-images.githubusercontent.com/19745447/50058502-72311280-0179-11e9-81ed-61936929377f.png)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```YAML
Chat:
  ModifyChatFormat: true
  ClickHoverMessages: true
  DiscordSRVPublicChat: false
  DynMapChat: false
  ReplyToLastMessenger: false
  LastMessengerTimeOut: 120
  LinkRegex2: (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  HoverItems: false
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
  BungeeMessages: true
  BungeePublicMessages: true
  GeneralFormat: '{prefix}{displayName}{suffix}&f: {message}'
  GeneralRange: -1
  ShoutRange: 200
  ShoutCost: 0
```

---

**Cmi Version (using`/cmi version`):** 8.2.5.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 476 (MC: 1.13.2)
