### ISSUE TITLE
Tag not generating sound

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#1189]
Chat Tag is enabled.

When a player tag someone, the one tagged dont head any sound.

Here is the config.
```


  Tag:
    # Enable or not tag system. This will inform player with hies name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&c'
    Sound:
      # Sound name
      Name: BLOCK_NOTE_BLOCK_HARP
      Volume: 1
      Pitch: 1
      # Will play tag sound only when player is afk
      OnlyWhenAfk: true
    # When set to true, @ simbol will be removed
    RemoveEta: false
```

Spigot 1.13.2

CMI 8.2.6.0

Thanks
