### ISSUE TITLE
[Suggestion] Choose what saves to SQL

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#1206]
**Description of issue or feature request:**

This feature would add a section in the top of the config.yml which will allow you to choose what is stored on the SQL database and what should be stored locally. This would be helpful for things like /homes or local balances, which is useful for servers that run multiple types of gamemodes where the currencies change their value, or if you want to seperate homes between each server, all while still having the option to share these things, rather than having to disable them completely and use another plugin.

Code example:
```
storage:
  # storage method, can be MySQL or sqlite
  method: MySQL
mysql:
  username: example_user
  password: 1234
  hostname: cmi.test.com
  database: cmiTest_cmi
  tablePrefix: CMI_
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
storageOptions:
  # here you can define what will be stored locally and what will be updated to the SQL database. (Leave empty if you dont use SQL.)
  # true means it will be stored on the SQL
  # false means it will be stored locally in the .db file.
  nickNames: true
  economy: false
  homes: false
  playTime: true
  playTimeReward: false
  inventories: false
  glow: false
  notes: true
  # add more options here...
```
---
