### ISSUE TITLE
Interactive commands sign lines don't work

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1209]
**Description of issue or feature request:**
WHen doing a interactive command that use sign lines, and click over it, it don't work.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
test:
  Commands:
  - say hello world
  SignLines:
  - test
  - ' '
  - ' '
  - ' '
#####################################
```

---

**Cmi Version (using`/cmi version`):**  8.2.8.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot 1.8.9 but it happen also with 1.13.2
