### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1212]
**Description of issue or feature request:**
The issue is that if there if you stand on soul sand and you are in area with 2 blocks of space. And a player teleports to you he get's teleported to the top and get suffocated to death in nether  (He basicly teleport to top of bedrock
Image of example:
![2018-12-25_12 28 29](https://user-images.githubusercontent.com/1558228/50422324-8c39b780-0841-11e9-85db-cf574a3fcbdf.png)

If I place a cobblestone instead of soul sand it will be fine but if it's soul sand ehh it's not fine.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```
```
  Teleport:
    # When true then while checking for safe location, we will try to determin it goind down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: false
    # Set this to true if you having issues with entities not being teleported with you
    # Keep in mind that this is work arround for some plugins (AKA Towny) and can have undesired results in some situations
    VehicleWorkArround: false
    # Set to true if you want to use tp commands as /cmi tp [WhoYouWantToTeleport] [WhereToTeleport] when its false, its /cmi tp [whereToTeleport] [WhoYouWantToTeleport]
    SwitchPlaces: true
    # Applies for tpa, tpahere and tpaall only
    # If set to true then player will be teleported to current player position after accepting teleport request
    # If set to false then player will be teleported to player at which teleport request was issued
    CurrentLoc: true
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 50
    # Defines time in seconds for accepting tpa or tpahere requests
    TpaTime: 60
    # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
    TpaWarmup: 4
    # Defines if player can move when tpa or tpahere is being accepted
    TpaMove: false
    # Defines time in seconds for blocking player teleport offers after denying their request
    TpaBlock: 120
    # Defines time in seconds for bypassing prevented teleportation to unsafe location
    TpBypass: 30
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in hies inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    # Back location will not be triggered if player teleports closer than defined amount of blocks
    BackMinDistance: 5
```
---

**Cmi Version (using`/cmi version`):** 
8.2.8.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot 1.13.2(#488)
**Server Version (using `/ver`):** 
1.13.2
