### ISSUE TITLE
Holograms not working with ICON, working with SICON only

### ISSUE THREAD

**Issue by Dampen59** [Zrips/CMI#1230]
Hello

I can't display hologram floating icons, only static ones

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Static icon works well 👍 

Test:
  Loc: world;0.22;69.65;-29.85
  Interval: 0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - SICON:%itemInHand%
  - TestValue - Text is showing properly
  DownOrner: true

What's not working 👎 

Test:
  Loc: world;0.22;69.65;-29.85
  Interval: 0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - ICON:%itemInHand%
  - TestValue - Text is showing properly
  DownOrner: true

```

---

**Cmi Version (using`/cmi version`):** 
8.2.8.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.8.8-R0.1-SNAPSHOT
