### ISSUE TITLE
I Need Help

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#125]
I want to add a sound when a Player walks thru a Portal but every which way I have tried with execute command, sends it to all the players. How can I add ender tp sound to Portal when a player walks thru?
```
world:
  Spawn:
    Loc: -1219.0:87.0:1112.0:-1219.0:91.0:1113.0
    enabled: true
    effect: largesmoke
    showParticles: true
    Tp:
      ==: org.bukkit.Location
      world: world
      x: 629.6505985378916
      y: 67.9375
      z: -490.544689665408
      pitch: -2.2501726
      yaw: 18.899536
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands:
    - cmi effect [playerName] blindness 2 1 -s
```
I know this command or any variation of it sends the sound to all players...not good :(
```
    - execute @a ~ ~ ~ /playsound ENTITY.ENDERMEN.TELEPORT block @p
```
It would be nice if it were this simple.
```
- cmi playsound [playerName] ENTITY.ENDERMEN.TELEPORT
```
