### ISSUE TITLE
Interactive commands file fail to be loaded and require /cmi reload for work

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1278]
**Description of issue or feature request:**
Ocasionally cmi commands list is not loaded, or npc (citiizens) or any interactive block disapear, and it require /cmi reload for fix it, please fix is pretty critical for my server

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
repair:
  Location:
  - ==: org.bukkit.Location
    world: ASkyBlock
    x: 8004.0
    y: 118.0
    z: -18001.0
    pitch: 0.0
    yaw: 0.0
  - ==: org.bukkit.Location
    world: ASkyBlock
    x: 17798.0
    y: 132.0
    z: -9801.0
    pitch: 0.0
    yaw: 0.0
  Commands:
  - cmi repair hand [playername]
  - msg! [playername] &2Oggetto riparato!
  SignLines:
  - Riparazione
  - Clicca qui
  - per
  - riparare
  Public: true
#####################################
```

---

**Cmi Version (using`/cmi version`):** 8.3.4.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  1.8.9, Happen also with 1.13.2
