### ISSUE TITLE
[Bug] PlayTimeRewards not consistent

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1279]
**Description of issue or feature request:**

---
I noticed that PlayerRewards is executed often when I just join the server. Although it should be executed when 15 minutes of playtime has passed. It happens all too often that its executed within 1 minute after joining. Coincidence? Maybe. But sometimes, after 2-3 minutes it is executed another time!!!!
After that it runs fine.
So it's not consistent.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
none
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Config.yml:
```
PlaytimeRewards:
  Enabled: true
  ExcludeAfk: true
  RewardInform: 15
  OneTimeAmount: 2
```
PlayTimeRewards.yml:
```
15min:
  DisplayName: "&7Payout"
  AutoClaim: true
  Description:
  - "&a50 coins per 15 min online time"
  PayEvery: 900
  Commands:
  - asConsole! cmi money give [playerName] 50 -s
  - msg! [playerName] You earned &350 &ecoins for &315 &eminutes onlinetime.
```

---

**Cmi Version (using`/cmi version`):** 
8.3.4.0 but this is present for a while
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2
