### ISSUE TITLE
/nick "OnNickChange" does not update [displayname] in chat or tablist.

### ISSUE THREAD

**Issue by FlakMagnet** [Zrips/CMI#1335]
**Players issuing the /nick command do not have their new nickname updated up in the tablist or in the in-game chat even though "OnNickChange" is set.  Both update immediately if any of the other update conditions are met such as joining, leaving, AFK state changes, world changes, etc... or when the AutoInterval elapses.  The behaviour/bug persists even after setting "Async" to "false".**

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
TabList:
  Enabled: true
  Async: true #Issue persists even if set "false"
  UpdateTabListNames: true
  GroupedEnabled: true
  Updates:
    AutoInterval: 300
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
```

---

**Cmi Version (using`/cmi version`):  CMI plugin version: 8.3.8.1** 

**Server Type (Spigot/Paperspigot/etc):  PaperSpigot** 

**Server Version (using `/ver`): git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 ** 

**Relevant plugins (Delete if this isn't needed):  ChatManager version 3.3.0**
