### ISSUE TITLE
Playtime Rewards Errors

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#1337]
**Description of issue or feature request:**
Having a strange thing happen with playtime rewards, even stranger because it's only happening on one of our 3 servers and more so with older players, not with newer ones -- but several of them aren't receiving the hourly reward anymore, and when we they use /prewards to check it it shows:
`1. 'Hourly reward' reward in 99 days 5 hours 57 mins 58 sec`

To test it I tried changing the 'PayEvery:' listed below to 1000 and all it did was shave a few minutes off the 99 days listed above. I checked out actual play time and all seemed normal. 

My attention was only drawn to it last night, but some of our staff said they noticed it about the middle of last week.

Thanks!

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
hourly1:
  DisplayName: "&7Hourly reward"
  AutoClaim: true
  Description:
  - "&2Get 1 Loyalty Point for every hour you are online"
  PayEvery: 3600
  Commands:
  - tokenmanager give [playerName] 1
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-f56e2e7-1a64d4a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
