### ISSUE TITLE
Flight charge is depleted

### ISSUE THREAD

**Issue by tianji1993** [Zrips/CMI#1341]
player always get "Flight charge is depleted" while using flyc command, the player has enough exp and OP permission. how can they use this normally? 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Flight charge is depleted
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
FlightCharge:
  # Do you want to enable flight charge feature
  Enabled: true
  # When set to true, each time player gets flight charge or relogs, his fly mode will be toggled on
  # If set to false, then players will have to manualy turn on flight with /cmi flyc
  EnabledByDefault: false
  # When set to true, in event of player changing his game mode from survival/adventure to creative/spectator his flight charge  mode will get disabled
  # Same applies when changind game mode from creative/spectator to survival/adventure
  AutoSwitch: true
  # How much it costs for one recharge point in exp points. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  ExpRechargeCost: 1.0
  # How much it costs for one recharge point. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  MoneyRechargeCost: 0
  # Defines maximum amount of charge player can have
  # One charge is one traveled block while flying
  # if player dosent move, then one charge for each second while hovering
  MaxChargeLevel: 1000
  # Defines multiplier when player doesnt move but is hovering. For each second player hovers.
  # Set to 0 to disable
  DeductOnIdling: 0
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penealty from jumping from clifs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 2
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: true
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false

```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper(507) 1.13.2-R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):** 
LuckPerms-Bukkit-4.3.73.jar
