### ISSUE TITLE
[Request] Portals support ranks system

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1345]
It would be nice to decide if a portal can be used by only one type of rank or more.

In addition, those who try to enter the portal and don't have the right rank, an error message appears with written which ranks can access.
This message would be nice to be able to customize it

Possible formatting to add in the portal.yml
```
 allowRanks: true/false
      ranksAccess:
      - A
      - C
      - etc...
     wrongRanksMessage: &4 Only rank A and C are allowed. Come back when you get one of these
```
