### ISSUE TITLE
Problem with Kits custom variables

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1361]
The variables
{USERNAME} {DISPLAYNAME} {WORLDNAME} {KITNAME} {RANDOMPLAYER} don't work in the armor that they wear directly when they withdraw the kit.

Instead, It works if the pieces of armor are given in inventory.
http://prntscr.com/mdbgp3

Don't work
```
    Boots:
      v: 1631
      type: DIAMOND_BOOTS
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §3{USERNAME} - {DISPLAYNAME}
```
Works
```
  Items:
    '35':
      v: 1631
      type: DIAMOND_BOOTS
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §3{USERNAME} - {DISPLAYNAME}
```
---

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13.2
