### ISSUE TITLE
Question: Head drop

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1402]
In the eventcommands.yml, I have this

  - cmi give [sourceName] head playername 

I've tried a few different ways to make it so when a player is killed, they will drop their head(ideally), or simply give it to the player who killed them. Also, to make it a 5% chance, do I do %rand/5-5%, or %rand/5%, or just %5%?

**Comment by TheWranger** [comment]
You don't need to add it as an eventcommand, CMI has it's own built-in mechanic that makes players drop their heads on death.
```
Combat:
  # Defines combat timer to be used in particular features
  Timer: 15
  Heads:
    Player:
      Drop: false
      # Percentage from 0 to 100 for head to be dropped. Decimals are acceptable, like 0.2
      # 100 will mean that head will be dropped every time player kills another player
      # 1 will mean that there is 1% that player will drop head if he is killed by another player
      Percentage: 1.0
      # Percentage from 0 to 100 for lowering chance in getting second head of same player
      # This will reset on each server restart
      LowerChanceOfterDrop: 50.0
    Mob:
      # Enables custom mob heads dropping from mobs with particular chance
      # Check customHeads.yml for customization by entityType
      Drop: false
```
