### ISSUE TITLE
[Support] How to place spawners of a certain type?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1407]
Hi there,

It appears that players can get the permissions for a certain spawner type to be placed, 
```
cmi.placespawner - Allows to place spawner and keep its type
cmi.placespawner.[entitytype] - Allows to place spawner by particular type and keep its type
```
And it appears there are other spawner entity type permissions for say silk touching them, dropping, picking up, and whatnot.

But it seems upon placing that they are not a chicken or cow spawner, they always resolve to a pig spawner. 

Is this a bug (that a '/cmi give player spawner:cow' with the permission to place the cow spawner), doesn't place as the spawner type it's set to? Or is this not a bug, but requires a third party spawner plugin to achieve that? I think by vanilla mc it always places as a pig, but i was hoping cmi would handle the type as it implies.

**Comment by mrfloris** [comment]
```
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: true
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: true
```

For some reason when I set this to true the first time, and restarted, this was false again. I think I might have forgotten to safe the file.. ugh.. 

Trying again
