### ISSUE TITLE
[Cuff's Issue] Allowed Commands don't work

### ISSUE THREAD

**Issue by Angelfox28** [Zrips/CMI#1409]
I added cmi helpop in the list of allowed commands, but it doesn't works when you're cuffed
Obviously I added the permission cmi.command.helpop

```
Cuff:
  # When set to false will allow players to talk who is cuffed
  Mute: true
  AllowedCommands:
  - msg
  - r
  - tell
  - cmi helpop
```

**Cmi Version (using`/cmi version`):** 8.3.10.0

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):**  Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT
