### ISSUE TITLE
Custom warmpups not loading properly

### ISSUE THREAD

**Issue by ydu80** [Zrips/CMI#1422]
Setting up custom warmup doesn't work. Here is an example with only 3 warmpups being loaded while there is 9.

---
```
[05:15:35 INFO]: [CMI] Loaded (3) cooldowns into memory. Took 9ms
[05:15:35 INFO]: [CMI] Loaded (3) warmups into memory. Took 0ms
```

```
WarmUps:

  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  List:
  - tp:7:false
  - back:7:true
  - cmi spawn:7:false
  - cmi home :7:false
  - k home:7:false
  - spawn:7:false
  - cmi home :7:false
  - cmi warp :7:false:GlyphHead
  - cmi warp spawn:7:false:GlyphHead
  - rtp:7:false:GlyphHead 
```

---

**Cmi Version (using`/cmi version`):** 8.4.0.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 

**Server Version:** Paper(1593) 1.12.2-R0.1-SNAPSHOT
