### ISSUE TITLE
[Bug] AFK Bypass

### ISSUE THREAD

**Issue by Drc-DEV** [Zrips/CMI#1448]
**Description of issue or feature request:** A user found an afk-machine that bypasses cmi afk detection. Can you please fix this? Because I think it will spread really fast on my servers.

![2019-02-20_02-33-06](https://user-images.githubusercontent.com/33911680/53060109-8ebf3300-34b9-11e9-80c8-84f549302017.gif)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Afk:
  Enabled: true
  PreventJumping: true
  PreventDamage: true
  CheckInterval: 10
  StopPlayTime: true
  AutoAfkIn: 300
  AutoAfkCmds: []
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eis not AFK!
  AutoKickIn: -1
  RepeatingAutoKickInterval: 300
  RepeatKickCommand: false
  AutoKickCmds: []
  DisableOnInteract: true
  SmartInteractCheck: true
  AntiAfkMachines: true
  DisableOnInventoryClick: true
  DisableOnCommand: true
  DisableOnPublicChat: true
  DisableOnPrivateChat: true
  DisableOnMove: true
  DisableItemPickup: false
```

---

**Cmi Version (using`/cmi version`):**  8.4.0.2
**Server Type (Spigot/Paperspigot/etc):** PaperSpigot
**Server Version (using `/ver`):**  Paper(1596) 1.12.2-R0.1-SNAPSHOT
