### ISSUE TITLE
jail time not counting down while offline

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/CMI#1469]
even if that option is set to true in the config

**Comment by melinstagibson** [comment]
So am i the only one having this issue? because i dont know how to confirm it otherwise, its not like im making it up... and its sort of a real pain since i now have to either use a different plugin for jailing or manually make lists of whenj to unjail people

**Comment by melinstagibson** [comment]
Can this please get fixed, i have the same issue on my second server now aswell
latest version of CMI, this is the config part
```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 20
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: true
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
```
