### ISSUE TITLE
Sleeping Issues

### ISSUE THREAD

**Issue by graywolf336** [Zrips/CMI#1526]
**Description of issue or feature request:**

When there are two players on the server and one of them starts sleeping the speed up starts. When the second person starts sleeping (aka 100%), they then both wake up and it is still night instead of morning.

Another issue related to this is when one person stays sleeping all the way through, the time speeds up and when it hits morning they wake up. However, it stays eternally morning.

---

**CONFIG SECTION:**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 50%
```

---

**Cmi Version (using`/cmi version`):** 8.5.1.3

**Server Type (Spigot/Paperspigot/etc):** `Spigot`

**Server Version (using `/ver`):** `1.13.2-R0.1-SNAPSHOT` & `git-Spigot-3cb9dcb-77ca7ca`
