### ISSUE TITLE
Teleport /tp cooldown is not working

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1531]
**Description of issue or feature request:**
The cooldown for the command /tp or /cmi tp is not working, meaning not matter what cooldown time I put, players will still be able to use the command repeatedly without waiting for the cooldown.
Other commands put on cooldown are working fine, only tp is not working.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No Error
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.command.[comandName].cooldownbypass permission node
  # Always use full command name and not its alias
  Enabled: true
  List:
  - plot h:3
  - home:3
  - spawn:3
  - cmi spawn:3
  - cmi heal:600
  - cmi feed:300
  - cmi repair:180
  - cmi repair all:420
  - cmi actionbarmsg:300
  - cmi tp: 180
  - cmi tfly:300
  - tp: 180
```

---

**Cmi Version (using`/cmi version`):** 
8.5.1.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
spigot 1.8.8 R01 snapshot
**Relevant plugins (Delete if this isn't needed):**
