### ISSUE TITLE
Sorting issue with colors on tab

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#1567]
**Description of issue or feature request:**
---
If the feature: Sorting is enabled the colors in tab no longer works, and it don't shows the rank for player.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Sorting:
    # EXPERIMENTAL! Enable or disable tab list sorting. This will sort tablist by defined criteria
    Enabled: true
    # Defines type by which you want to sort tablist. Possible options: Group, CustomGroup, Name, NickName, Balance, World
    # Group sorting will sort by player permission group name, in most cases main group name will be used
    Type: Name
    # Order of sorting. Can be ASC or DESC options
    Order: ASC
    # Arranged list of permission groups by which you want to sort player in tablist.
    # Players with a group not mentioned in this list will be placed at bottom in one list sorted by name
    CustomGroup:
    - wlasciciel
    - glownyadmin
    - admin
    - glownymoderator
    - moderator
    - helper
    - rekrut
    - vip
    # Interval in seconds to automatically resort tablist
    # In case you are sorting by a group name, you might want to update tablist from to time
    # This should be over 60 seconds as there is no point in adding extra load on server for something like this
    AutoUpdate: -1
    # Minimal interval in seconds to resort tablist when you are sorting by balance.
    # Keep this in reasonable amount as we dont need frequent resorting, especially if players are gaining money constantly
    BalanceInterval: 10
```
---

**Cmi Version (using`/cmi version`):** 
8.5.4.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):**
