### ISSUE TITLE
[Bug?] config.yml random teleport location errors when set to false

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1571]
Sorry for the confusing title, .. not sure how to word it.

When you have various worlds that are 'temporary' worlds, and we don't want to use teleport in them, we set the random teleport location enabled to false in config.yml

When the world is unloaded, and you restart the server, it still errors on startup that the values are invalid, etc.

```
    halloween:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

```
[16:00:38 INFO]: [CMI] Random teleport location is out of minimal world border X coordinate bounds for halloween world. Please update values.
```

Yes, the world constantly changes, and we have it turned off, does it really need to check it then?
