### ISSUE TITLE
[BUG] Cooldown command TPA

### ISSUE THREAD

**Issue by Xardas88** [Zrips/CMI#1575]
**Description of issue or feature request:**
Hi. 
seems that the "tpa" and "tpaccept" commands share the same cooldown while the "tpdeny" command does not affect.
I tried setting tpaccept at 5 seconds but it doesn't work

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
 Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.command.[comandName].cooldownbypass permission node
  # Always use full command name and not its alias
  Enabled: true
  List:
  - cmi tpa:3600
  - cmi tpaccept:5
  - cmi tpdeny:5 

```

**Cmi Version (using`/cmi version`):** 
8.5.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 
**Server Version (using `/ver`):** 
1.13.2-R0.1-SNAPSHOT
