### ISSUE TITLE
DiscordSRV incompatibility with DontSendCanceledChatEvents setting true

### ISSUE THREAD

**Issue by BlightedBlue** [Zrips/CMI#1583]
**Description of issue or feature request:**
I have DontSendCanceledChatEvents set to true in my DiscordSRV config. I need it to be set to true. However, when it is, chat messages aren't sent to the discord channel, besides achievements/deaths/joins/quits etc.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
  # Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true
  # Enables support for DynMap web chat
  DynMapChat: true
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: false
  # If ReplyToLastMessenger is set to false, then timeOut will be taken into consideration to who you should reply
  # If you had conversation in last 120 seconds (default) then even receiving message from 3rd person, you will still reply to original player
  # If you had conversation in longer then 120 seconds period, then you will reply to latest person who send you a message
  LastMessengerTimeOut: 120
  # Defines regex when replacing url in chat with short word
  # Examples:
  # (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  LinkRegex2: ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  # When set to true, particular variables in chat will be translated into items player are holding. List of variables belove
  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
  # Do you want to enable private messaging over bungeecord
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: true
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: true
  # Used for simple chat messages. Optional variables: {world} {prefix} {suffix} {group}. Supporting PlaceHolderAPI variables like %player_server%
  GeneralFormat: ''
  # Defines range of regular messages to travel
  # Set to -1 to disable range restriction
  GeneralRange: -1
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.chat.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  GroupFormat:
    '1': '%uperms_prefixes% &f{displayName}&f: &r{message}'
    '2': '%uperms_prefixes% &6{displayName}&f: &r{message}'
    '3': '%uperms_prefixes% &e{displayName}&f: &r{message}'
    '4': '%uperms_prefixes% &b{displayName}&f: &r{message}'
    '5': '%uperms_prefixes% &a{displayName}&f: &r{message}'
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      books: false
      # List of strings to ignore when checkign chat for color codes player cant use.
      # This will bypass players colorcode restrictions and will allow usage of particular chat formats
      # Applies only for public and private messages
      WhiteList:
      - '&c❤&7'
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true

  # Enables DiscordSRV plugin support for messages
  DiscordSRVSupport: true
```

---

**Cmi Version (using`/cmi version`):** 8.5.1.1 

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 1.13.2-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** CMI, DiscordSRV
