### ISSUE TITLE
Command Blocker + Tab Completion support

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#1598]
**Description of feature request:**

Not sure if this would be too large of an addition, so don't worry if it is. This addition would add a file such as blocked.yml which would allow a user to add a command to "hide" from the server. It would have options such as: per-world support, custom message per command, custom permission per command and an option to allow that command to be tab-completed (would be off by default).

Example template of what the file would look like:

```
BlockedCommands:
  bukkit%colon%about:
    Permission: 'bukkit.command.about'
    Message: 'Unknown command. Type "/help" for help.'
    # Choice of tab-completion. "true" means the command is hidden for anyone without the permission, "false" means anyone can still see this command
    No-Tab-Complete: true
    # Methods: Whitelist allows the command in certain worlds. Blacklist blocks the command only in the worlds listed.
    Method: Blacklist
    Worlds:
    - world
    - world_nether

  aackick:
    Permission: 'aac.kick'
    Message: 'Unknown command. Type "/help" for help.'
    # Choice of tab-completion. "true" means the command is hidden for anyone without the permission, "false" means anyone can still see this command
    No-Tab-Complete: true
```

---
