### ISSUE TITLE
The plugin keep adding the default configs to my customHead.yml

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#1623]
**Description of issue or feature request:**

I wish to set it to only drop head for certain mobs but the plugin keep adding the default mobs back into the config

---

**Cmi Version (using`/cmi version`):** 

8.5.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
Try this:
```
  ender_dragon:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads: []
```
