### ISSUE TITLE
zombie_pigman not working in custom head drop

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#1624]
**Description of issue or feature request:**
zombie_pigman will not work in custom head config but pig_zombie will
---

Cmi Version (using/cmi version):

8.5.6.0
Server Type (Spigot/Paperspigot/etc):
Spigot
Server Version (using /ver):
This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
You suggest that the default file contains a `zombie_pigman` somewhere. Can you quote the part/version where it says just that? Because my default file says:
```
  pig_zombie:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:Default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzRlOWM2ZTk4NTgyZmZkOGZmOGZlYjMzMjJjZDE4NDljNDNmYjE2YjE1OGFiYjExY2E3YjQyZWRhNzc0M2ViIn19fQ==
```
