### ISSUE TITLE
Bug - Hologram's NextPage feature not working on recent update

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1642]
I'm having trouble with the latest update of CMI. Hologram now can't go to next page somehow. It only go one page forward or backwards. They can't go more than that. I have pasted the hologram for the config. And also they didn't safe "Big Button" config on the hologram. Everytime the server restarts, the hologram's big button option became true again.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Main hologram
```
rules:
  Loc: spawn;-218.1;16.82;-164.82
  Interval: -1.0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - '&61. No Griefing'
  - '&eDilarang mengubah bentuk dari'
  - '&eproperti pemain tanpa seijin'
  - '&eatau sepengetahuan pemilik properti.'
  - '!nextpage!'
  - '&62. No Trespassing'
  - '&eDilarang masuk kedalam properti'
  - '&epemain tanpa seijin atau sepengetahuan'
  - '&epemilik properti.'
  - '!nextpage!'
  - '&63. No Stealing / Scamming'
  - '&eDilarang mencuri barang atau'
  - '&eatau menipu pemain lain.'
  - '!nextpage!'
  - '&64. No Cheats, Hack Clients, Bug or Glitches'
  - '&eDilarang menggunakan aplikasi 3rd'
  - '&eparty yang dapat menyebabkan kecurangan.'
  - '!nextpage!'
  - '&65. Fair Play'
  - '&eDilarang menggunakan AFK Fishing, AFK Spawner, dll'
  - '&eKalau anda dipanggil saat melakukan kegiatan,'
  - '&etetapi tidak menjawab. Maka anda akan dihukum!'
  - '&eHormati sesama pemain dan staff.'
  - '!nextpage!'
  - '&66. Chat Behavior'
  - '&eJangan menghina dan menganggu player lain'
  - '&eKata kasar diperbolehkan. Tapi jangan berlebihan'
  - '!nextpage!'
  - '&67. No Advertising'
  - '&eDilarang mengiklankan server lain.'
  DownOrner: true
  Interactable: false
```

Next-page hologram
```
rules_next:
  Loc: spawn;-217.67;15.17;-165.29
  Interval: -1.0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - '&fNext Page'
  - '&f(klik saya untuk ke halaman selanjutnya)'
  DownOrner: true
  Interactable: true
  Commands:
  - cmi hologrampages rules [playerName] next
```

---

**Cmi Version (using`/cmi version`):** 8.5.6.1

**Server Type (Spigot/Paperspigot/etc):** Paper 614

**Server Version (using `/ver`):** 1.13.2
