### ISSUE TITLE
Extra event sounds

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1662]
**Description of issue or feature request:**
Sounds for:
- /tpa request (if you receive a tpa request)
- /mail (if you receive a mail) (if you are online and someone types `/mail send {urUsername} {message}`)
```yaml
# If you want to disable particular sound entirely, set it to "" 
Sounds:
  Enabled: true
  WarpGuiOpen: entity_bat_takeoff:0.5:1
  TeleportHome: block_beacon_ambient:2:1
  TeleportWarp: entity_enderman_teleport:0.5:1
  TeleportFail: entity_villager_no:2:1
  PrivateMessage: ''
  TeleportUp: entity_enderman_teleport:2:1
  TeleportDown: entity_enderman_teleport:0.2:1
```
