### ISSUE TITLE
Players can tell when I'm vanished

### ISSUE THREAD

**Issue by smellyonionman** [Zrips/CMI#1669]
A player told me today that when he sleeps on the server and nobody is around, he gets vanilla sleep mechanics - but if I am present and vanished, he gets the bed gui reading "1/1" and "100%."

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    Enabled: true
    InfoType: title
    ExcludeAfk: true
    BaseSpeed: 100
    MinSpeed: 5
    MinBeforeSpeeding: 1
```

**Cmi Version (using`/cmi version`):** 
CMI version 8.5.6.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.13.2 Build 624
