### ISSUE TITLE
/cmi rt wil drop players into void when used in the end in latest versions

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#1707]
**Description of issue or feature request:**
When using /cmi rt in versions 8.6.1.0 and 8.6.1.1 in the end, players are dropped into the void.  This did NOT happen in 8.5.6.1.  No console error.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world_the_end:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 1000
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 
Without problem:
-------------------------------------------------- 
CMI plugin version: 8.5.6.1-> 8.6.1.1
Server version: Paper(624) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.2-b107 07.05 05:34:20 [Server] INFO --------------------------------------------------
With problem:
 -------------------------------------------------- 
CMI plugin version: 8.6.1.1 
Server version: Paper(624) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.2-b107 
--------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
You are running the latest version
