### ISSUE TITLE
[Bug] Random teleport - Teleports you outside the predefined borders

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1713]
**Description of issue or feature request:**
Random teleport does not teleport you inside the definitions set in the config file. Most of my players die because they teleport outside my worldborder.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
RandomTeleportation:
  Worlds:
    world:
      Enabled: true
      MaxRange: 9500
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 8.6.1.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(624) 1.13.2-R0.1-SNAPSHOT
