### ISSUE TITLE
[BUG] Command /hologrampages wrong behaviour

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#1766]
**Description of issue or feature request:**
Hologram next page only works for 1 time, if there's multiple nextpages in a hologram, it wouldn't work, it only turn to page 2.

I am now stuck on CMI 8.5.6.0, because that is the version where it still works.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Hologram.yml config for the going to next page
```
rules_next:
  Loc: spawn;548.73;5.22;-376.64
  Interval: -1.0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - '&fNext Page'
  DownOrner: true
  Interactable: true
  Commands:
  - cmi hologrampages rules [playerName] next
```

Hologram.yml config for the page with multiple page
```
rules:
  Loc: spawn;548.64;7.53;-378.88
  Interval: -1.0
  Range: 8
  RangeExtra: 16
  Spacing: 0.22
  SpacingIcon: 0.5
  Lines:
  - '&61. No Griefing'
  - '!nextpage!'
  - '&62. No Trespassing'
  - '!nextpage!'
  - '&63. No Stealing / Scamming'
  - '!nextpage!'
  - '&64. No Cheats, Hack Clients, Bug or Glitches'
  - '!nextpage!'
  - '&65. Chat Behavior'
  - '!nextpage!'
  - '&66. No Advertising'
  DownOrner: true
  Interactable: false
```

---

**Cmi Version (using`/cmi version`):** 8.6.2.0

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot build 626

**Server Version (using `/ver`):** 1.13.2

**Relevant plugins (Delete if this isn't needed):** Protocollib 4.4.0 (idk if this is relevant)
