### ISSUE TITLE
[Bug] - Random Teleport

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1777]
**Description of issue or feature request:**
Random Teleport often teleports player to the same spot over and over again. Players on my server has come to the conclution that they can setup traps on those spots to kill them :)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
RandomTeleportation:
  Worlds:
    world:
      Enabled: true
      MaxRange: 9500
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 8.6.2.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-626 (MC: 1.13.2)
