### ISSUE TITLE
CMI Custom Alias [randomPlayer] doens't seem to parse?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1799]
Spigot 1.14.1 (today's build)
Latest CMI (8.6.3.1)
```
CustomAlias:
  test:
    Cmds:
    - cooldown:5?#! hasmoney:1000?#! msg! [playerName] &e debug cooldown/hasmoney
      msg $1
    - ifoffline:$1?! msg! [playerName] &e debug ifoffline msg $1 [randomPlayer]
    - ifonline:$1?! msg! [playerName] &e debug ifonline msg $1
    - fromConsole! cmi sound item_trident_return -p:0.8 -v:1.0 [playerName]
```
https://i.imgur.com/QwAm2Mb.png

It shows as plaintext `[randomPlayer]`
