### ISSUE TITLE
[Bug] Random teleport disabled/enabled worlds

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1808]
**Description of issue or feature request:**

---
Random teleport function ignores enabled/disabled worlds.

Example 1:
Player is in world "plot" (where RandomTeleportation is disabled)
Player tries to execute /rt
CMI returns message: `Possible worlds: world_the_end`

Example 2:
Player is in world "plot" (where RandomTeleportation is enabled)
Player tries to execute /rt
CMI returns message: `Possible worlds: world_the_end`
Random teleporting is not executed

Example 3:
Player is in world "world_the_end" (where RandomTeleportation is disabled)
Player tries to execute /rt
CMI returns message: `Possible worlds: world_the_end`

Workaround:
All enabled worlds must be stated first, after that all disabled worlds can be stated.
That doesn't solved the bug that a player in a disabled world receives the message: `Possible worlds: {returns the first world that is disabled!}`

BTW:
There is no real difference between `IgnoreLava: true` or `IgnoreLava: false`.
Player is teleported to lava anyways.

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  Worlds:
    world:
      Enabled: true
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_the_end:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_nether:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    plot:
      Enabled: true
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 60
      maxY: 70
```

---

**Cmi Version (using`/cmi version`):** 
8.6.3.0

**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 1.13.2 build 624
