### ISSUE TITLE
ClickHoverMessages & DiscordSRV no longer working together

### ISSUE THREAD

**Issue by ConfuseN** [Zrips/CMI#1817]
**Description of issue or feature request:**

---
Whenever ClickHoverMessages are enabled, discord SRV stops detecting player posted messages. However commands from discord end (such as: !c) works.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
  # Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true
  # Enables support for DynMap web chat
  DynMapChat: true
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
```

---

**Cmi Version (using`/cmi version`):** 
8.6.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-03bd4b0-c45c0a9 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):** 
DiscordSRV
