### ISSUE TITLE
Seat feature no longer working for stairs, slabs or carpets

### ISSUE THREAD

**Issue by JGuerndt** [Zrips/CMI#1840]
CMIs seat feature for stairs, slabs and carpets do not work.
In some recent update, I am no longer to use stairs, star or carpets as seats. Using /cmi sit still works though.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
For CMI version 8.6.4.0, i was unable to get any errors, it seems there is just no check for anything. I downgraded to an older version 8.6.1.3 and was able to get some errors (that version previously worked to my knowledge)

https://pastebin.com/VPFn1atV

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Animations:
  # Enable siting on stair block by clicking on them with empty hand or by looking and using command
  # Requires cmi.command.sit.stairs
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: true
  RemoveFromChairOnDamage: true
  # Player will sit on chair only after rapid double click
  DoubleClick: false
  # Delay in milliseconds between clicks to sit on chair when double click is enabled
  DoubleClickDelay: 200
  # Range in blocks from player to look up for valid chair block
  ChairRange: 4
```

---

**Cmi Version (using`/cmi version`):** 8.6.1.3 & 8.6.4.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1613

(also tested on spigot_79a30d7-acbc348_1.12.2)

I ran a server with limited plugins to rule out other things, but get same result. the errors above come from the server with the following installed. (sitting on the items works previously with same plugins installed.
**Relevant plugins (Delete if this isn't needed):** CMI, IPWhitelist, ServerSelectorX, SSX-Connector
