### ISSUE TITLE
/RT Values Not Taken Into Account

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#1848]
**Description of issue or feature request:**
When setting the /rt (random teleport) configuration, the min and max values are not taken into consideration. I used /rt twice and was still put nowhere near the values I set for the center.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Under the RandomTeleport section:
```
    kmc:
      Enabled: true
      MaxRange: 20000
      MinRange: 500
      CenterX: -9999525
      CenterZ: -9999648
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      minY: 20
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.14.2 (paper-53)
**Server Version (using `/ver`):** 
paper-53
