### ISSUE TITLE
Fly Other Permission Issue when CustomAlias Defined

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#1857]
Players could issue /fly username (themselves) and obtain fly on the server when /cmi checkperm cmi.command.fly & cmi.command.fly.other was set to false.

The only way around it I found was to remove a CustomAlias I had setup for the /fly command which provided some helpful output and information. I also removed the Alias /fly as well, but not sure that it was needed. 

This resolved to correct permissions, but doesn't help me with the CustomAlias to educate players about chargefly which is enabled.

---

---

[07:57:20 INFO]: --------------------------------------------------
[07:57:20 INFO]: CMI plugin version: 8.6.4.0
[07:57:20 INFO]: Server version: Paper(55) 1.14.2-R0.1-SNAPSHOT
[07:57:20 INFO]: Vault version: 1.6.10(+)
[07:57:20 INFO]: --------------------------------------------------

**Comment by Zrips** [comment]
I will need example of that customAlias which caused this issue

**Comment by digitalcrowd** [comment]
```
  fly:
  - msg! [playerName] ---------------------------------------------
  - msg! [playerName] &6&lSo You Want to Fly huh?
  - msg! [playerName] &cIn survival, it costs to fly using Coins or Exp
  - msg! [playerName] &cPlus, you need &2Settler Rank &cor Higher &b/ranks
  - msg! [playerName] &b/flightcharge expcharge [100-2000]
  - msg! [playerName] &b/flightcharge moneycharge [100-2000]
  - msg! [playerName] &b/chargefly &ctoggles flightcharge use on/off
  - msg! [playername] &f-OR-
  - msg! [playername] &cIf in Creative world/mode use &b/creativefly
  - msg! [playerName] ---------------------------------------------
  chargefly:
  - cmi flyc
  creativefly:
  - cmi fly
```

Creative fly is for people in the creative world. There was an issue in the past where if you had charge fly and you went to creative world, it would still use chargefly. So changing using creativefly worked fine. Since permissions where not set in other worlds for fly command, all was well.

**LuckPerms**
```
cmi.command.fly | true | never | global | plotworld3 | none | deletecontent_copy
cmi.command.flyspeed | true | never | global | plotworld3 | none | deletecontent_copy
cmi.command.flyspeed.3 | true | never | global | plotworld3 | none | deletecontent_copy

* Plotworld3 = Creative World

```
