### ISSUE TITLE
Auto AFK and Kick not working

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#1876]
Players are not being put into AFK status when idle and subsequently not being kicked automatically.

---

```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 5
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while chekcing players playtime
  StopPlayTime: false
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  AutoAfkIn: 600
  # Defines commands to be performed when player enters afk mode
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eis no longer AFK
  # Defines how long to wait after player stops moving to kick player
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  AutoKickIn: 1200
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &eYou have been kicked for idling more than [time]
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Disables afk on inventory click
  DisableOnInventoryClick: false
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables item pickup while afk
  DisableItemPickup: false

```

```
[05:37:24 INFO]: --------------------------------------------------
[05:37:24 INFO]: CMI plugin version: 8.6.4.1
[05:37:24 INFO]: Server version: Paper(65) 1.14.2-R0.1-SNAPSHOT
[05:37:24 INFO]: Vault version: 1.6.10(+)
[05:37:24 INFO]: --------------------------------------------------
```
