### ISSUE TITLE
CMI join/leave messages don't work with VentureChat

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#1881]
**Description of issue:**
Join/Leave message don't seem to be working. I am using venturechat, so that might be cause. It is enabled in the config, also I am switching from essentials and that worked fine.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: false
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: false
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: false
  DeathMessage:
    # Defines number of players from which to automatically start hiding death messages
    # Set to -1 to disable this
    AutoHideFrom: -1
```

---

**Cmi Version (using`/cmi version`):** 
[Mon, 3. Jun 2019 18:38:56 UTC INFO] --------------------------------------------------
[Mon, 3. Jun 2019 18:38:56 UTC INFO] CMI plugin version: 8.6.4.2
[Mon, 3. Jun 2019 18:38:56 UTC INFO] Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[Mon, 3. Jun 2019 18:38:56 UTC INFO] Vault version: 1.6.11(+)
[Mon, 3. Jun 2019 18:38:56 UTC INFO] --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
[Mon, 3. Jun 2019 18:42:07 UTC INFO] This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[Mon, 3. Jun 2019 18:42:07 UTC INFO] This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
**Relevant plugins (Delete if this isn't needed):**
CMI, Vault, LuckPerms, VentureChat, PlaceholderAPI
