### ISSUE TITLE
Towny incompatible with CMI economy

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#1883]
**Description of issue:**
All economy commands are broken in towny. See screenshot https://gyazo.com/b4e6b7d34ac40d019d6c60c0513a140f
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 1.0E8
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
  Global:
    # Starting amount of money players will have
    StartingAmount: 2500.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E8
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: $
    # Format used for displaying money
    MoneyFormat: '###,###.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumners: false
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: false
    # Placing of currency symbol
    Placing: '[symbol][money]'
```

---

**Cmi Version (using`/cmi version`):** 
[Mon, 3. Jun 2019 18:38:56 UTC INFO] --------------------------------------------------
[Mon, 3. Jun 2019 18:38:56 UTC INFO] CMI plugin version: 8.6.4.2
[Mon, 3. Jun 2019 18:38:56 UTC INFO] Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[Mon, 3. Jun 2019 18:38:56 UTC INFO] Vault version: 1.6.11(+)
[Mon, 3. Jun 2019 18:38:56 UTC INFO] --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
[Mon, 3. Jun 2019 18:42:07 UTC INFO] This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[Mon, 3. Jun 2019 18:42:07 UTC INFO] This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
**Relevant plugins (Delete if this isn't needed):**
CMI, Vault (CMI Compiled, also tried injector), Towny
