### ISSUE TITLE
Player cannot change skin

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#2010]
**Description of issue:**
Player cannot change skin it is stuck on an old version of his skin.
The issue was fixed by disabling CMI's skin management, but now I can't use /skin.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
```

---

**Cmi Version (using`/cmi version`):** Paper(124) 1.14.3-R0.1-SNAPSHOT

**Server Type (Spigot/Paperspigot/etc):** paperspigot

**Server Version (using `/ver`):** Paper version git-Paper-124 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
