### ISSUE TITLE
Incorrect gamemode in eventcommands

### ISSUE THREAD

**Issue by HeartlessAUS** [Zrips/CMI#2020]
**Description of issue:**
Gamemode change displays wrong gamemode.
Delay doesn't seem to help either
---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
playerGameModeChange:
  Enabled: true
  Commands:
  - broadcast! &8&l[&eBaconBot&8&l] &6[playerDisplayName]&6's gamemode was changed
    to [gameMode]
```

---

**Cmi Version (using`/cmi version`):** 
8.6.6.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
paper-114 (1.14.3)
**Relevant plugins (Delete if this isn't needed):**
CMI...?
