### ISSUE TITLE
Database corrupted, players are duplicated

### ISSUE THREAD

**Issue by Olexorus** [Zrips/CMI#2030]
Some of my users have multiple entries in the CMI database. It seems like CMI sometimes doesn't find a user for some reason and then creates a new entry. This leads to a loss of their previous stats, and for example the /votetop command shows those users multiple times. Some users have 5 different entries. It's a really big problem for me, because even if I manually adjust the stats, there are still the old "ghost" values which I have no access to, except when I edit the database directly.

I already tried `/cmi removeuser duplicates`, it says `0/0 duplicates removed`

Config (I've only included the part about the database):
```
storage:
  # storage method, can be MySQL or sqlite
  method: sqlite
mysql:
  # Requires Mysql.
  username: root
  password: ''
  hostname: localhost:3306
  database: minecraft
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false
```

---

**Cmi Version (using`/cmi version`):** 8.6.6.1 (latest version atm)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper-127 (latest build atm); 1.14.3

**Relevant plugins (Delete if this isn't needed):** CMI, LuckPerms, PandamiumPlugin (custom), PlaceholderAPI*, Votifier

It might be related to my own plugin (PandamiumPlugin, the name of my server is "Pandamium"), because it used to be a Snapshot server where votes were stored in the scoreboard objective "votes". To transfer it from there to the CMI system, I'm using this code:

```
@EventHandler
fun onPlayerJoin(event: PlayerJoinEvent) {
    transferStats(event.player)
}

private fun transferStats(player: Player) {
    val scoreboardVotes = Bukkit.getScoreboardManager()!!.mainScoreboard.getObjective("votes")!!.getScore(player.name)
    if (scoreboardVotes.score > 0) {
        Bukkit.getServer().dispatchCommand(Bukkit.getServer().consoleSender, "cmi voteedit ${player.name} set ${scoreboardVotes.score}")
        scoreboardVotes.score = 0
    }
}
```
