### ISSUE TITLE
Sleeping Speedup is not working for my player but working on op

### ISSUE THREAD

**Issue by alan67160** [Zrips/CMI#2035]
**Description of issue or feature request:**
Sleeping Speedup is not working for my player but working on op
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: bossbar
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 30%
```
---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.6.6.1 BungeeCord -> 8.6.7.0
Server version: Paper(124) 1.14.3-R0.1-SNAPSHOT
Vault version: 1.6.11(+)

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-124 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-123 (MC: 1.14.3)
You are 3 version(s) behind
