### ISSUE TITLE
ranks.yml formatting wrong no matter what I do

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#2041]
**Description of issue:**
I just added a new rank to "ranks.yml" and for some reason it keeps saying it isn't the right format but I literally copied the format from the rank above.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
11.07 19:33:17 [Server] INFO [CMI] 46 Enabled and 1 Disabled modules
11.07 19:33:17 [Server] INFO [CMI] LuckPerms plugin will be used
11.07 19:33:17 [Server] INFO [CMI] Loaded (46) regular alias into memory. Took 18ms
11.07 19:33:17 [Server] INFO [CMI] Loaded (4) custom text's into memory. Took 11ms
11.07 19:33:18 [Server] INFO [CMI] 5.5.5-10.1.38-MariaDB data base type detected
11.07 19:33:36 [Server] INFO [CMI] Started (MySQL) data base. Took 18897ms
11.07 19:33:36 [Server] INFO [CMI] Vault was found - Enabling capabilities. Economy: CMIEconomy
11.07 19:33:36 [Server] INFO [CMI] Can't determine sound name for tag. Trying to defaulting to BLOCK_NOTE_HARP
11.07 19:33:36 [Server] INFO [CMI] Loaded (5) warning categories into memory. Took 0ms
11.07 19:33:36 [Server] INFO [CMI] Loaded (3) warning commands into memory. Took 1ms
11.07 19:33:37 [Server] INFO [CMI] Loaded (121) custom mob heads
11.07 19:33:37 [Server] INFO [CMI] Loaded (7) cooldowns into memory. Took 44ms
11.07 19:33:37 [Server] INFO [CMI] Loaded (10) warmups into memory. Took 1ms
11.07 19:33:37 [Server] INFO [CMI] Loaded (1) jails into memory. Took 26ms
11.07 19:33:37 [Server] INFO [CMI] Can't find world with (Creative) name
11.07 19:33:37 [Server] INFO [CMI] Can't find world with (KMC2) name
11.07 19:33:37 [Server] INFO [CMI] Loaded (2) kits into memory. Took 9ms
11.07 19:33:37 [Server] ERROR Cannot load plugins/CMI/ranks.yml
11.07 19:33:37 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
11.07 19:33:37 [Server] INFO in 'string', line 104, column 17:
11.07 19:33:37 [Server] INFO DisplayName: "&eVeteran"
11.07 19:33:37 [Server] INFO ^
11.07 19:33:37 [Server] INFO expected alphabetic or numeric character, but found "(34)
11.07 19:33:37 [Server] INFO in 'string', line 104, column 26:
11.07 19:33:37 [Server] INFO DisplayName: "&eVeteran"
11.07 19:33:37 [Server] INFO ^
11.07 19:33:37 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:945) ~[?:?]
11.07 19:33:37 [Server] INFO at com.Zrips.CMI.CMI.onEnable(CMI.java:1385) ~[?:?]
11.07 19:33:37 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
11.07 19:33:37 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning an anchor
11.07 19:33:37 [Server] INFO in 'string', line 104, column 17:
11.07 19:33:37 [Server] INFO DisplayName: "&eVeteran"
11.07 19:33:37 [Server] INFO ^
11.07 19:33:37 [Server] INFO expected alphabetic or numeric character, but found "(34)
11.07 19:33:37 [Server] INFO in 'string', line 104, column 26:
11.07 19:33:37 [Server] INFO DisplayName: "&eVeteran"
11.07 19:33:37 [Server] INFO ^
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1452) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:937) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:368) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:530) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.14.3.jar:git-Paper-127]
11.07 19:33:37 [Server] INFO ... 14 more
11.07 19:33:37 [Server] INFO [CMI] Loaded (2) playtime rewards into memory. Took 2ms
11.07 19:33:37 [Server] INFO [CMI] Loaded (36) Player data into memory. Took 451ms
11.07 19:33:38 [Server] INFO [CMI] Loaded (421) playtime records into memory. Took 196ms
11.07 19:33:38 [Server] INFO [CMI] Loaded (15) playtime reward records into memory. Took 82ms
11.07 19:33:38 [Server] INFO [CMI] Loaded (26) custom alias into memory. Took 6ms
11.07 19:33:38 [Server] INFO [CMI] Loaded (2) interactive commands into memory. Took 2ms
11.07 19:33:38 [Server] INFO [CMI] Registered events. Took 339ms
11.07 19:33:38 [Server] INFO [CMI] Loaded (0) event action commands into memory. Took 3ms
11.07 19:33:39 [Server] INFO [CMI] Updated (EN) language file. Took 258ms
11.07 19:33:39 [Server] INFO [CMI] Loaded (245) worth values into memory. Took 13ms
11.07 19:33:39 [Server] INFO [CMI] Loaded (7) warps into memory. Took 6ms
11.07 19:33:39 [Server] INFO [CMI] Vault permissions was found - Enabling capabilities.
11.07 19:33:39 [Server] INFO [CMI] PlaceholderAPI hooked.
11.07 19:33:39 [Server] INFO [CMI] PlaceholderAPI was found - Enabling capabilities.
11.07 19:33:39 [Server] INFO [CMI] LWC was found - Enabling capabilities.
11.07 19:33:39 [Server] INFO [CMI] McMMO was found - Enabling capabilities.
11.07 19:33:39 [Server] INFO [CMI] Starting world timer.
11.07 19:33:39 [Server] INFO [CMI] Initializing world manager.
11.07 19:33:39 [Server] INFO [CMI] Loaded (5) schedules into memory. Took 5ms
11.07 19:33:39 [Server] INFO [CMI] Loaded (0) skin cache entries into memory. Took 0ms
11.07 19:33:39 [Server] INFO [CMI] Found DiscordSRV
11.07 19:33:39 [Server] INFO [DiscordSRV] API listener com.Zrips.CMI.Modules.DiscordSRV.DiscordSRVListener subscribed (4 methods)
11.07 19:33:39 [Server] INFO [CMI] Version 8.6.7.1 has been enabled
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Main server folder spigot.yml and check that stats saving prevention its set to false stats->disable-saving: false
# Player will get default rank group depending on set permission node cmi.rank.[groupName] 
# Not enabled ranks will be ignored
# DisplayName section is optional and it will be used to represent rank ingame. This is NOT defining required permission node and you still need to use node name to rankup to this rank
# DefaultRank section defines if player can be assigned to this rank if he dont have any. There can be more than one default rank, and depending on permision node, first rank will be assigned to that player when needed
# PermissionRequirement section defines list of permissions player should have to rankup to that rank. Optional - For each permission node you can add its name which will be shown in /cmi rankinfo with : In example cmi.command.fly:Fly
# McMMORequirement section defines list of McMMO skills and levels player should have to rankup to that rank.
# JobsRequirement section defines list of Jobs and levels player should have to rankup to that rank.
# ItemRequirement section defines list of items player should have to rankup to that rank. Items will be taken after succesfull rankup from players inventory.
# AutoRankup section defines if player will be auto ranked to this rank if posible. Keep in mind that if there is more than one legit rankup, player will have to confirm to which rank he wants to rankup
# RankupConfirmation section defines if you want to add aditional confirmation for this rankup. Usefull to avoid unintentional rankups. Keep in mind that autorankup will request confirmation for rankup to this rank even if there is only one legit rankup option
# NextRanks is list of posible next ranks from this rank. Can be one or can be dozens. Keep in mind that each rank requirements will be shown in chat and it can clutter quite allot if there is bunch of them at once
# MoneyCost defines how much player will have to pay to rankup to this rank
# ExpCost defines how much player will have to pay in exp to rankup to this rank
# Votes defines how much player will need to have votes to rankup to this rank
# Commands is list which will be performed on rankup. Can be aditional actions, like message broadcast or anything alse
# Main section is StatsRequirements and it can have allot of different values in it:
#   In general format goes like this [mainStat](:optionalSubStat):amount
#   In example MonsterKills:100 will require from player to have 100 monster kills while MonsterKills:Zombie:100 will require to have 100 zombie kills. Both of them can be used if needed.
#     List of posible requirement and basic explanations:
#       Distance in blocks:
#         Travel - travel in total
#         Walk - has to walk
#         Sneak - has to sneak
#         Sprint - has to sprint
#         Swim - has to swim
#         Fall - has to fall
#         Climb - has to climb
#         Fly - has to fly
#         Dive - has to walk under water
#         MinecartTravel - has to travel with minecart
#         BoatTravel - has to travel with boat
#         PigTravel - has to ride pig
#         HorseTravel - has to ride horse
#         ElytraTravel - has to fly with elytra
#       Time in sec:
#         PlayTime - total play time
#         FromLastDeath - from last death
#         SneakTime - sneak time
#       Amounts:
#         GameQuit - how many times player left game
#         Jump - jump count
#         DamageDealt - total damage made
#         DamageTaken - total damage taken
#         Deaths - count of deaths
#         MobKills - total amount of mobs killed by player
#         PlayerKills - total amount of players killed. Indirect kills dont count
#         ItemEnchanted - amount of enchanted items
#         AnimalsBred - animals bred
#         FishCaught - fish caught
#         TalkedToVillager - times talked to villager
#         TradedWithWillager - traded with willager
#         CakeSlicesEaten - cake slices eaten
#         CauldronFilled - cauldron filled
#         CouldronUsed - couldron used
#         ArmorCleaned - times armor cleaned (leather armor)
#         BannerCleaned - times banner cleaned
#         BrewingstandInteractions - brewingstand interactions
#         BeaconInteractions - beacon interactions
#         CraftingTableInteractions - crafting table interactions
#         FurnaceInteractions - furnace interactions
#         DispenserInspected - dispenser inspected
#         DropperInspected - dropper inspected
#         HopperInspected - hopper inspected
#         ChestOpen - chest open
#         TrappedChestTriggered - trapped chest triggered
#         EnderchestOpened - enderchest opened
#         NoteblockPlayed - noteblock played
#         NoteblockTuned - noteblock tuned
#         FlowerPotted - flower potted
#         RecordPlayed - record played
#         SleeptInBed - sleept in bed
#         ShulkerBoxOpened - shulker box opened
#         ItemDropped - defines amount of dropped items. If specific item is not defined, then total amount is used
#         ItemPickups - defines amount of picked up items. If specific item is not defined, then total amount is used
#         BlocksMined - defines amount of blocks mined. If specific block is not defined, then total amount is used
#         ItemBreaks - defines amount of broken items. If specific item is not defined, then total amount is used
#         ItemCrafts - defines amount of crafted items. If specific item is not defined, then total amount is used
#         ItemsUsed - defines amount of item usage. like mining with pickaxe. If specific item is not defined, then total amount is used
#         MonsterKills - defines amount of monster kills. If specific monster is not defined, then total amount is used
#         KilledBy - defines amount of deaths by monster. If specific monster is not defined, then total amount is used

 
Newbie:
  Enabled: true
  DisplayName: "&7Newbie"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Member
Member:
  Enabled: true
  DisplayName: "&2Member"
  AutoRankup: true
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame a Member!"
  - "asConsole! lp user [playerName] parent add member"
  StatsRequirements:
  - "PlayTime:14400
  NextRanks:
  - Veteran
Veteran:
  Enabled: true
  DisplayName: "&eVeteran"
  AutoRankup: true
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame a Veteran!
  - "asConsole! lp user [playerName] parant add veteran"
  StatsRequirements:
  - "PlayTime:172800"
Premium:
  Enabled: true
  DisplayName: "&6Premium"
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame a Premium member!"
  - "asConsole! lp user [playerName] parent add premium"
Builder:
  Enabled: true
  DisplayName: "&3Builder"
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame a Builder!"
  - "asConsole! lp user [playerName] parent add builder"
Moderator:
  Enabled: true
  DisplayName: "&5Moderator"
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame a Moderator!"
  - "asConsole! lp user [playerName] parent add moderator"
Admin:
  Enabled: true
  DisplayName: "&4Admin"
  Commands:
  - "broadcast! &6[playerDisplayName] &bbecame an Admin!"
  - "asConsole! lp user [playerName] parent add admin"
Branch1Rank1:
  Enabled: false
  DisplayName: "&2Branch1Rank1"
  DefaultRank: false
  AutoRankup: true
  RankupConfirmation: false
  PermissionRequirement:
  - "cmi.command.heal:Heal"
  NextRanks:
  - Last
  MoneyCost: 300
  ExpCost: 350
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch1Rank1 rank!"
  StatsRequirements:
  - "travel:10000"
  - "blocksmined:3000"
  - "blocksmined:diamond_ore:30"
  - "MonsterKills:1000"
  - "AccountAge:1209600"
  McMMORequirement:
  - "taming:10"
  - "unarmed:30"
Branch2:
  Enabled: false
  DisplayName: "&2Branch2"
  AutoRankup: true
  RankupConfirmation: true
  MoneyCost: 150
  NextRanks:
  - Branch2Rank1
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch2 rank!"
  PermissionRequirement:
  - "cmi.command.tp:Teleport"
  StatsRequirements:
  - "PlayTime:3600"
  - "travel:2000"
  - "MonsterKills:zombie:15"
  - "MonsterKills:slime:10"
Branch2Rank1:
  Enabled: false
  DisplayName: "&2Branch2Rank1"
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 100
  ExpCost: 150
  NextRanks:
  - Branch2Rank2
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch1Rank1 rank!"
  StatsRequirements:
  - "PlayTime:4600"
  - "Swim:1000"
  - "SneakTime:180"
  - "MonsterKills:100"
Branch2Rank2:
  Enabled: false
  DisplayName: "&2Branch2Rank2"
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 100
  ExpCost: 150
  NextRanks:
  - Last
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch2Rank2 rank!"
  StatsRequirements:
  - "walk:15000"
  - "HorseTravel:1000"
  - "ItemsUsed:10000"
  - "PlayerKills:10"
Last:
  Enabled: false
  DisplayName: "&2Last"
  AutoRankup: true
  StatsRequirements:
  - "PlayTime:21600"
  - "walk:30000"
  - "MonsterKills:1000"
  - "blocksmined:30000"
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Last rank!"
  - "cmi heal [playerName]"
  - "money give [playerName] 100"
```

---

**Cmi Version (using`/cmi version`):** 
8.6.7.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.14.3 #127
