### ISSUE TITLE
Kit on spawn

### ISSUE THREAD

**Issue by Saelman** [Zrips/CMI#2053]
**Question:**
Hey, so im trying to give players the kit Spawn when they first join the server, but it doesn't seem to be working, below is the relevant part of config that i think does this. any advice?
into server
```
  SpawnOnJoin: false
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as posible respawn point for player after death
  Main:
    World: Theia
    X: -1306.836024430177
    Y: 77.0
    Z: -692.5003481315823
    Pitch: -4.8099575
    Yaw: -89.920135
    RespawnLocation: false
    Rng: 0
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    World: Theia
    X: -1306.836024430177
    Y: 77.0
    Z: -692.5003481315823
    Pitch: -4.8099575
    Yaw: -89.920135
Newbie:
  # Kit name to give for new players joining server
  Kit: Spawn
Kits:
  # When set to true, kit list will be shown in GUI instead of chat list
  GUI: true
  # When set to true, kit selection gui empty fields will get filled with definet item
  FillEmptyFields: true
  Buttons:
    Cooldown: Watch
    Usages: STONE_PLATE
    Money: GOLD_INGOT
    Exp: EXP_BOTTLE
    Desc: WOOL:13
    Back: Fence
Warps:
  # When set to true, warps list will be shown in GUI instead of chat list
  GUI: true
  # Automatically opens GUI when created new warp point
  GUIOnCreation: true
  # Minimal lenght of warp name
  MinLenght: 4
  # Maximal lenght of warp name
  MaxLenght: 16
  # How many warps to show in each page
  perPage: 50
  # Do you want to show creator in warp list
  showCreator: false
  # When set to true, new warps by default will require permission node to use them
  requirePerm: false
```
