### ISSUE TITLE
Sleeping not working.

### ISSUE THREAD

**Issue by K4raM4rx** [Zrips/CMI#2080]
**Description of issue:**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: bossbar, title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 75
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 33%
```

---

**Cmi Version (using`/cmi version`):** cmi 8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** paper-136

**Server Version (using `/ver`):** 1.14.4
