### ISSUE TITLE
[Feature] Essential Feature For Factions Servers.

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2096]
**Description of feature/improvement request:**

A feature that comes out straight from `EssentialsProtect.jar`.
This will have effect over few things like world weather mechanics and mob spawning mechanics and behavior.
I will only include the ones that are imperative as far as it goes to new Factions (cannonig and such) oriented servers.

**Entity Damage**
```
  prevent:
    fire-spread: true
    lava-fire-spread: true
    lightning-fire-spread: true
    tnt-explosion: true
    tnt-minecart-explosion: true
    witherskull-explosion: true
    wither-spawnexplosion: true
    wither-blockreplace: true
    creeper-explosion: true
    creeper-playerdamage: true
    creeper-blockdamage: true
```

**Mob Spawning** - _world spawning events plus monster eggs_
```
    spawn:
      creeper: true
      wither: true
```

**Weather Options**
```
    weather:
      storm: true
      thunder: true
      lightning: false
```

### Detailed explanation of what it should do, when and in what situation: ###
If it is possible to have these on a simple command that can be toggled on/off/pause, with a countdown timer and a message/broadcast when activated and when the countdown is over, which will of course automatically set the pointed above on default "false". That does not include the weather options. The weather (rain, storm etc.) are just not used on this type of servers.
And lastly a simple command for the player so that he can see the time left on the "grace period" and what is being disabled during that.

If that is too much, and there is a option to consider any of these to be added, just a simple addition to the config.yml with "true/false" and /cmi reload will also just do fine.

### Basic explanation as to why this feature is needed and/or useful to have: ###
As i said these are features that are somewhat a part of the core gameplay of most Factions servers. Every competitive pvp oriented Factions uses these. It will be in a huge help for them, and imo the plugin will be able to target even bigger audience.
