### ISSUE TITLE
Warmups with spaces broken

### ISSUE THREAD

**Issue by xSkate** [Zrips/CMI#2102]
**Description of issue:**
With the latest update, warmups in config for things like warps and homes no longer work without making the base command have a warmup.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi tp :5:false
  - cmi back:3:false
  - cmi warp :5:false
  - cmi home :5:false
  - cmi spawn:5:false
  - f home:5:false
```

---

**Cmi Version (using`/cmi version`):** 
8.6.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper build 146
**Server Version (using `/ver`):** 
1.14.4
