### ISSUE TITLE
[Feature] Warmup Cancellation for Player Teleport Event (warp/spawn)

### ISSUE THREAD

**Issue by xxJinxedxx** [Zrips/CMI#2109]
**Description of feature/improvement request:**
_I'm not really sure if this feature is already within the plugin, like the (tpa) warmup cancellation and it's not working. To be honest I was really surprised that there was no warmup cancellation._

Just a warmup cancellation falling under the same mechanics as tpa basically. It will cancel the warmup and the command execution if:
 - player movement _(without yawn, pitch, jump, sneak)_
 - damage/ed

```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  CancelOnMove: true/fase
  CancelOnDamage: true/false
  List:
  - cmi spawn :3:true
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:true:
```
---
### Basic explanation as to why this feature is needed and/or useful to have: ###
I think that it is pretty clear on why this is useful. PvP, main reason.
