### ISSUE TITLE
RTP Module

### ISSUE THREAD

**Issue by silvasky54** [Zrips/CMI#2148]
**Description of feature/improvement request:**
Could you please add a module to enable or disable RTP?
---
### Detailed explanation of what it should do, when and in what situation: ###
If enabled, it reads settings from relevant configs. If disable, plugin does not look for RTP locations during server startup.

### Basic explanation as to why this feature is needed and/or useful to have: ###
RTP is not something most servers would use. It's mostly relevant to survival or faction servers. Being able to disable it as a module will also clear up the console on startup.

**Comment by mercurialmusic** [comment]
Do you mean random teleport? This is already a thing... /cmi rt

**Comment by silvasky54** [comment]
I'm aware of that command. It simply teleports you to a random location. I'm asking for a module in the module.yml file to disable the plugin using rtp entirely.

**Comment by mercurialmusic** [comment]
```
RandomTeleportation:
  Worlds:
    # World name to use this feature. Add another one with appropriate name to enable random teleportation
    [worldname]:
      Enabled: false
```
This is not difficult.
