### ISSUE TITLE
Question about Respawn location

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#2157]
**Question: **
I tried to set so that players will respawn on their home named Home when they die or else the plugin will find any home on the first list for the player. I can't seem to make it work. Player spawned in the server's spawn instead. This is my config

```
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 5
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: spawn, bedLocation, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - HomeLocation
    - BedLocation
    - Spawn
```
