### ISSUE TITLE
kit editor not opening

### ISSUE THREAD

**Issue by pixelsquared** [Zrips/CMI#2184]
**Description of issue or feature request:**
`/cmi kiteditor` does nothing there is no error in the server log and no output from the command

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
kits.yml:
```
# Player should have appropriate permission node to use particular kit: cmi.kit.[kitName]
# cmi.kit.newbie will allow to use newbie kit
# Possible custom variables: {USERNAME} {DISPLAYNAME} {WORLDNAME} {KITNAME} {RANDOMPLAYER}
# Edit kits ingame with /cmi kiteditor to avoid formating issues
Newbie:
  CommandName: Newbie
  Enabled: true
  DropOnGround: true
  ShowDespiteWeight: false
  Delay: 36000
  MaxUsages: -1
  Icon:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: GRASS_BLOCK
  IconOff:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: GRASS_BLOCK
  Group: groupName
  Items:
    '1':
      v: 1976
      type: OAK_PLANKS
      amount: 30
```

---

**Cmi Version (using`/cmi version`):** 
8.6.9.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-166 (MC: 1.14.4)
