### ISSUE TITLE
Scavenge command is broken

### ISSUE THREAD

**Issue by Spoonerj1** [Zrips/CMI#2197]
I have disabled the economy functions on my server, set the econ to false in CMI and set the cost for /scavenge to 0.0 for all items because I am using it as a donor perk, but somehow it still says players don't have enough money to use it. Why is this happening?

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Cost:
    # Defined base cost of extraction. Set to 0 if you want to make it free
    Base: 0.0
    # Extra cost which depends on enchantment worth which can be defined with /cmi setenchantworth 
    # This value is in percentage from worth value of that each enchantment and item
    # So if you have base cost of 100, extra cost of 5% and you are trying to extract sharpness 5 which worth is 1000 and item sell hand worth is 100, then you will have to pay 155 for extraction process
    Extra: 0.0
```

---

**Cmi Version (using`/cmi version`):** CMI plugin version: 8.6.8.4-> 8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-ea7e48b-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** Vault, CMI (no economy is being used for any functions)
