### ISSUE TITLE
cmi.autorespawn always granted via operator rights

### ISSUE THREAD

**Issue by BehrRiley** [Zrips/CMI#2200]
Operator always provides authorization for auto-respawn. Setting this permission to negative in any way does not change this

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 5
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: false
```
can't disable auto-respawn currently. I've attempted cleaning out my entire server for a fresh version of cmi , paper 163 | 1.14.4making the perm cmi.autorespawn negative doesn't do anything, and using UPerms i can see that it's being authorized by operator rights
---

**Cmi Version (using`/cmi version`):** 
cmi 8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper(163) 1.14.4 -R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):**
UPerms only, fresh test server to verify
