### ISSUE TITLE
Player First Join Inventory

### ISSUE THREAD

**Issue by konsyr11** [Zrips/CMI#2205]
## Weird Items in inventory
When players join for the first time, they have a couple of wood and two stacks of enchanted stone!! I have not changed anything in the config regarding this.
Thanks in advance for your help.

**Comment by mercurialmusic** [comment]
Check the /cmi kit newbie -- if those items are in that kit then change to your liking. If not, it's not CMI.

**Comment by JasperLorelai** [comment]
The items described do fit the default configuration for the newbie kit in `kits.yml` - for CMI.

**Comment by LogGits** [comment]
in config.yml look for:
```yaml
Newbie:
  # Kit name to give for new players joining server
  Kit: Newbie #probably called something else
```
If you change the name of the kit to a kit that doesnt exist it will disable this.
