### ISSUE TITLE
NameTagEdit and CMI

### ISSUE THREAD

**Issue by kforbro** [Zrips/CMI#2207]
I have NameTagEdit and CMI. When a player enters the server, his nickname is white in the tab. Without CMI, nick looks good. If you enter /nte reload, the nickname is displayed correctly
![javaw_T1nTgA4Tr6](https://user-images.githubusercontent.com/39985355/63155698-c4ce1180-c01b-11e9-9ec0-cec7e56db359.png)
![javaw_DA1Z110YhK](https://user-images.githubusercontent.com/39985355/63155703-c7c90200-c01b-11e9-85e7-d4b578a23138.png)

**Comment by mercurialmusic** [comment]
A workaround, or at least this is what works for me using CMI and NTE. You might need to fiddle with it a bit still, since your chat plugin can also interfere (if you use something other than CMI), but it is possible.

Set your CMI config to:
```
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{prefix}{nickName}'
```
and your tablist placeholder to:
```
  GeneralFormat:
    PlayerName: '%cmi_user_display_name%'
```
This should do it, but sometimes also giving the players a "nick" of their own username can help:
/cmi nick kforbro kforbro

Hopefully someday the current nameplate feature will be able to be set automatically based on group/permission and we can get rid of NTE.
