### ISSUE TITLE
/nick placeholders does update not or really late.

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2233]
**Description of issue:**
So when i do /nick it does not update in the chat nor tablist, it only updates on rejoin. Or when i stay afk randomly it changes on tablist & chat after a few minutes, i don't know why.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
I do not have errors.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################|
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 10
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '%luckperms_prefix%[playerDisplayName]'
    Header:
      '1': []
    Footer:
      '1': []
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  # If player has more than one permission node, then biggest one will be used
  GroupFormat:
    '1':
      PlayerName: '%luckperms_prefix%[playerDisplayName]'
      Header:
        '1': []
      Footer:
        '1': []
```

---

**Cmi Version (using`/cmi version`):** 8.6.9.8 BungeeCord, but i am using bukkit???

**Server Type (Spigot/Paperspigot/etc):** 
```
[22:30:56 INFO]: This server is running Paper version git-Paper-174 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
>.... [22:30:56 INFO]: Checking version, please wait...
>.... [22:30:57 INFO]: Previous version: git-Paper-172 (MC: 1.14.4)
>.... [22:30:57 INFO]: You are running the latest version```

**Server Version (using `/ver`):**  Paper version git-Paper-174 (MC: 1.14.4)
