### ISSUE TITLE
/itemname blacklisted items does not do anything.

### ISSUE THREAD

**Issue by JoelDeadMach** [Zrips/CMI#2301]
**Description of issue:**
Hi, so the issue we have now, we have blacklisted items in /itemname like chest. anvil, spawner, etc.
But players are just available to rename it without any message that the item is blacklisted.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items
  # Option to define specific name by using regex format
  Prevent: true
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
  - experience_bottle:([A-z]+ (?i)\w*xp)
  - anvil:([A-z])
  - chest:([A-z])
```

---

**Cmi Version (using`/cmi version`):** 
8.6.12.0

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.14.4
