### ISSUE TITLE
Player skins are not loaded correctly when logging in

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2326]
With the Skin module activated there are synchronization problems, these can lead to various issues:

1) The skin is simply not changed at joining, often new skins are only displayed after a server restart.

2) The skin is set to an old skin used weeks ago.

3) The /skin update command does not work reliably and often does not take effect until 30-60 minutes after the skin change.

These issues do not occur when the skin module is deactivated. New skins are displayed immediately then.
 
CMI 8.6.12.1
Paper 1.13.2 - 645

config:
```
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
```
modules:
```
# Handles player skins
# Applies for servers from 1.7.x and up
skin: true
```
