### ISSUE TITLE
Schedule Timing Question

### ISSUE THREAD

**Issue by DJKenzoDE** [Zrips/CMI#235]
It is possible du make schedules timing on a event? e.q: OnDeath (with specific player, this is possible with papi to set the nick from dead player or?)

It is not possible it is possible to make it with the feature?

**Comment by LogGits** [comment]
You can utilise `eventCommands.yml` file to achieve this:
```
playerDeath:
  Use: true
  List: 
    - cmi nick [playerName] Yikes
```
