### ISSUE TITLE
cmi home issue with warmups 

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#2374]
**Description of issue:**

I had noticed that if player types /HOME (name) he can bypass the warmups time, I do have config file setup correctly for sure so I don't understand why it don't work for capital letters :(
Video:
https://streamable.com/h7ilc

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - rt:3:false
  - res rt:3:false
  - cmi spawn:3:false
  - cmi spawn :3:false
  - cmi home:3:false
  - cmi home :3:false
  - cmi warp :3:false
  - cmi back:3:false
  - cmi dback:3:false
  - res tp :3:false


I also try to add this to fix it but did not worked:
  - cmi HOME :3:false
  - CMI HOME :3:false
  - HOME :3:false
  - HOME:3:false
```

---

**Cmi Version (using`/cmi version`):** 
8.6.13.2
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.14.4
