### ISSUE TITLE
/schedule doesn't detect schedule names from config.

### ISSUE THREAD

**Issue by Speyrow** [Zrips/CMI#2391]
When typing '/schedule [scheduleName]' it just returns with the message 'Schedule by this name is not found'

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Groundclean:
  Enabled: true
  MinPlayers: 0
  Delay: 600
  Repeat: true
  Commands:
  - cmi groundclean


```

---

**8.6.13.2** 

**Paper(175) 1.14.4-R0.1-SNAPSHOT** 

**MC 1.14.4**
