### ISSUE TITLE
Jumping between world with different worldborders

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#243]
Description of issue or feature request:
Jumping between world with different borders

When jumping betweens worlds with warps/portals it happen often at the Shown and teleported Cords become wrong

To Reproduce:
- Create a world - worldborder maybe 40000 Blocks
- search for a Location over 8000 Blocks away from your spawn
---- ->exa,mple: your Center is at X0,Z0 then go to X10000,Z10000
- creat a warp - "test"
- go to nether and set the worldborder for nether to 8000 Blocks
- now use the warp "test"
...-> effect: you will be teleported in overworld to near X8000,Z8000
when u look at your warp now the Cords are shown wrong and if u click it get teleported to the wrong Cords
- only reloading CMI helps here...

![image](https://user-images.githubusercontent.com/12080017/38546182-40d07772-3cac-11e8-88b3-32a61b1d18d4.png)

```
Roberts_Home:
  Location: Demantra;11112.46;137.0;13067.74;-1.48;18.3
  ReqPerm: true
  Creator: Cloude_Lecaw
```
