### ISSUE TITLE
TPA timer

### ISSUE THREAD

**Issue by Aeyori** [Zrips/CMI#2438]
**Description of issue:**

When I do /tpa it starts the timer even though the tpa hasn't been accepted. It starts the timer when i just run the command, it should only run the timer when the tpa has been accepted.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi tp :3:false:GlyphHead
  - cmi back:3:false:GlyphHead
  - cmi warp :3:false:GlyphHead
  - cmi home :3:false:GlyphHead
  - cmi tpa :3:false:GlyphHead
```

---

**Cmi Version (using`/cmi version`):** 
8.6.15
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 209 - 1.14.4
