### ISSUE TITLE
timer for kits may be bugged?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#244]
Description of issue or feature request:

Here u see my two kits: One should be for cookies all 5 Hours and one for free boats all two secounds

```
Notration:
  Description:
  - '&eDiesen Essen dient als Essen für den Anfang.'
  - '&eEs kann alle 5 Stunden genutzt werden.'
  CommandName: Notration
  Enabled: true
  Delay: 18000
  Commands:
  - msg &eDu hast das Kit &6{KITNAME} &eeingelöst.
  Conditions:
  - cmi.kit.get
  - cmi.kit.notration
  Group: Spieler
  Items:
    '1':
      type: COOKIE
      amount: 16
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Krümel´s Survival Cookies
        lore:
        - Besitzer:§3 {DISPLAYNAME}
        - §7§O
        - §7§ODiese Cookies haben einst
        - §7§Oeinem bekannten blauen Monster
        - §7§Oder Sesamstrasse gehört...
        - §7§OPasst auf wo ihr sie esst!
        - §7§O
Rettungsboot:
  Description:
  - '&eEin Boot das dir hilft den Spawn zu verlassen.'
  - '&eEs kann alle 2 Sekunden genutzt werden.'
  CommandName: Rettungsboot
  Enabled: true
  Delay: 2
  Commands:
  - msg &eDu hast das Kit &6{KITNAME} &eeingelöst.
  Conditions:
  - cmi.kit.get
  - cmi.kit.rettungsboot
  Group: Spieler
  Items:
    '1':
      type: BOAT
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Rettungsboot
        lore:
        - §7§O
        - §7§ODieses Boot bietet Platz für
        - §7§Obis zu zwei Spieler.
        - §7§OIn der Regel wird dieses Boot nur
        - §7§Ogenutzt um über die giftigen
        - §7§OGewässer zu kommen.
        - §7§O

```

The kit wor so long, but the timers seems to be currupted?
Example:
- you get  some cookies (kit Notration) - the 5 Hour countstart now starts...
- 10 minutes later you decide to get a boat (kit Rettungsboot)
- now you wanne check your remaining time with trying to get the cookiekit aggain (kit Notration)
 Rersult:  you will see that the boat kit resetet also the cookietimer to 5 hours
  you can now see that each time you get a boat from the boatkit ...the cookiekit timer also resets..

i have no clue why and think this may is a bug that still remains in current version... so i report it as issues here now :3

Cmi Version (7.6.5.2`): 
Server Type (Spigot): 
Server Version (1.12.2 - 3 days old):
