### ISSUE TITLE
Why do players appear on the spawn, and not by the bed?

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#2485]
My players after death appear on spawn. What should I change for players to appear in their beds?

**Comment by arturek1666** [comment]
Hi, please find this code:
```
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 0
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: spawn, bedLocation, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
  # Defines respawn order for defines worlds
  # Remove world if you want to leave respawn handling for server or 3rd party plugin
```

and change the priority order from:
```
    PriorityOrder:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
```
To something like this:
```
    PriorityOrder:
    - bedLocation
    - spawn
    - homeLocation
    - worldSpawn
```
