### ISSUE TITLE
Check for name change shows hidden/vanished players

### ISSUE THREAD

**Issue by ChitterChatter** [Zrips/CMI#2514]
Description of issue:

Hi there, not sure if this would be a bug report or a request? My admin logged into the world, he was vanished but his hidden presence was notified when other staff saw the name change announcement. 

CONFIG SECTION:

#######################################
```
# Checks and shows on players login if he have been changed hes name over Mojang
# Looks to be working only with online servers, duhhhh
CheckForNameChange:
  OnLogin: true
  AmountToShow: 3
  OnInfoShow: true
  # Do you want to perform commands
  PerformCommandsOnNewName: true
  # Command list to be performed in case player logs in with new name
  NameChangeCommands:
  - 'asConsole! cmi broadcast !&2[oldname] logged in with new name: [newname]'
```
#######################################

Is there a way certain people or certain ranks can be excluded from having this show?

Cmi Version (using`/cmi version`): latest version

Server Type (Spigot/Paperspigot/etc):  Paper

Server Version (using `/ver`):  1.14.4
