### ISSUE TITLE
Skin updates are not visible to the target player

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2519]
The _/cmi skin_ command updates the skin only on the main world correctly. On all other worlds the command will be executed but the skin won't update, _/cmi skin update_ won't help either. The skin updates itself only after a world change or after a relog.

Reproduction steps:
Server with two worlds:
1) Go to the !main_world and type _/cmi skin Santa_ -> The command is executed but there is no skin update visible
2) Change to the main world or relog to see the new skin.

It's a weird behavior, but I'm sure there is a technical reason. I tried to rule out everything else.

config:
```
Skins:
  Enabled: true
  AutoApply: true
  SteveOnOff: false
  RequireSpecificPerm: false
  SkinUpdateTimer: 60
  SkinRequestFrequency: 10
```
CMI 8.6.15.8
Paper 1.13.2 - 652
