### ISSUE TITLE
/cmi rankinfo BlocksMined increments by 3x for breaking 1x piece of dirt (Hand or tool)

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#2521]
Im creating my first autoranking with CMI to try and replace Autorank/Stats3.
On initial testing Block Breaking "BlocksMined" is increment 3 breaks at a time when you mine dirt?
No matter if you use an item or your hand.

---

```
2019-11-18 21:36:59 CMI: 8.6.15.8 BungeeCord                                                                                                                                                                           
2019-11-18 21:36:59  Server version: Paper(1617) 1.12.2-R0.1-SNAPSHOT                                                                                                                                                   
2019-11-18 21:36:59 Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER} 
```

**Comment by Zrips** [comment]
Statistics are been read from Minecraft collected data, CMI doesnt collect things like broken block count. If reported count is inaccurate then minecraft recorded it incorrectly or you have statistic set to count not only those blocks. Some extra information would be nice to have, like exact rankup requirements for broken blocks

**Comment by FrozenBeard** [comment]
Hello Zrips, what is being recorded live with CMI is +3 for each dirt for the "overall" mined.
This is my initial ranks.yml, At present this is entirely in testing stages as I got stuck at this bug.

```
default:
  Enabled: true
  DisplayName: "&9Deckhand"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - cadet
  StatsRequirements:
  - "PlayTime:18000"
  - "BlocksMined:5000"
  - "BoatTravel:5000"
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Cadet rank! To Celebrate everone gets 1.5x XP Boost for 5 mins!"
  - "lp user [playerName] parent settrack ranks cadet"
  - "lp user [playerName] permission set essentials.kits.cadet_rankup"
  - 'title [playerName] title {"text":"[playerName] you made Cadet!","color":"green"}'
  - 'title [playerName] subtitle {"text":"Congratulations!"}]}'
  - "xpb give all 1.5 300"
  - "execute @a[name=[playerName]] ~ ~ ~ /particle dragonbreath ~ ~2.0 ~ 0.35 1.75 0.25 0.03 300"
  - "execute @a[name=[playerName]] ~ ~ ~ /playsound entity.player.levelup ambient [playerName]"
  - "cmi msg [playerName] &dCongratulations [playerName], you are now Cadet Rank. Don`t forget to claim your /kit cadet_rankup! See https://piratemc.com/guides/ranks/"
```
