### ISSUE TITLE
Use of TimeSpeed in config.yml conflicts with "normal game" 1-player sleeping

### ISSUE THREAD

**Issue by Romaq** [Zrips/CMI#2529]
**Description of issue:**
Multiplayer sleeping works as expected, but "one player sleeping" fails.
---

**ERROR:**
When using "TimeSpeed" in config.yml, this sets "/gamerule doDaylightCycle false", which is appropriate for allowing the plugin to modify day ticks appropriate to the setting. Unfortunately, this conflicts with https://minecraft.gamepedia.com/Bed Quote: "Sleeping in a bed with the /gamerule doDaylightCycle set to false results in the player being kicked out of the bed after the 101 ticks, but does not change time of the world to day."

Expected behavior: One player sleeping in a bed should change it to day **IF** this is the normal behavior for multiple players sleeping within the same world/ dimension.

**CONFIG SECTION:**
```
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 1800
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 270
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 1260
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 270
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
```

---

**Cmi Version (using`/cmi version`):** 
22.11 14:04:59 [Server] Server thread/INFO CMI: 8.6.15.8-> 8.6.16.0
22.11 14:04:59 [Server] Server thread/INFO Server version: Spigot 1.14.4-R0.1-SNAPSHOT

Note: The next upgrade does not report fixing this problem, but I will update this plugin and the server tomorrow morning.

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
22.11 14:04:59 [Server] Server thread/INFO CMI: 8.6.15.8-> 8.6.16.0
22.11 14:04:59 [Server] Server thread/INFO Server version: Spigot 1.14.4-R0.1-SNAPSHOT
22.11 14:04:59 [Server] Server thread/INFO --------------------------------------------------
22.11 14:06:13 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-56f8471-56118c6 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
22.11 14:06:13 [Server] Server thread/INFO You are 1 version(s) behind

Again, will be updating in the morning.

**Relevant plugins:**
In testing (and per my understanding of the nature of this bug) no other plugins are used or required to replicate this bug.

If the plugin knows it has control over the scale of time, thus does a "/gamerule doDaylightCycle false" I would expect it to recognize its state and carry "multiplayer sleeping" behavior into the state of a single player sleeping on that world. If "TimeSpeed" is NOT configured **AND** Multi-player sleeping would not have an effect on advancing the clock, the behavior should duplicate Vanilla default behavior. Or... something like that. :)

I will keep an eye on this if you've further questions or insight into this report. --Romaq
