### ISSUE TITLE
perm:[permission] in eventcommands not working anymore

### ISSUE THREAD

**Issue by KyroOW** [Zrips/CMI#2532]
**Description of issue:**
perm:[permission] is not working in eventcommands.yml anymore, the command gets executed even if the player doesn't have the permission

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  - perm:cmi.tagpvp! lp user [playerName] permission unset animatednames.group.defaultpvp
playerKillPlayer:
  # [sourceName] to insert source player name
  # [sourceDisplayName] to insert player display name
  # [sourceLvl] to insert player level
  # [sourceExp] to insert player total exp
  # [sourceHp] to insert player health
  # [sourceMaxHp] to insert player max health
  # [sourceHunger] to insert player hunger level
  # [sourceGameMode] to insert player gamemode
  Enabled: true
  Commands:
  - perm:cmi.arenepomme! cmi give [sourceName] 322 1 -s
  - perm:cmi.arenepomme! cmi actionbarmsg [sourceName] &6&l+1 Pomme d'Or !
```

---

**Cmi Version (using`/cmi version`):** 

8.6.16.0

**Server Type (Spigot/Paperspigot/etc):** 

paper 1.12.2
