### ISSUE TITLE
Tablist doesn't sort playernames.

### ISSUE THREAD

**Issue by gaRt3n** [Zrips/CMI#2540]
**Description of issue:**
No sorting on the Tablist
http://prntscr.com/q30rwm
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: false
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 1
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  # When set to false we will not add header text to tablist
  addTabListHeader: true
  # When set to false we will not add footer text to tablist
  addTabListFooter: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '%vault_rankprefix%&r [playerDisplayName]'
    Header:
      '1':
      - '&aWillkommen &2[playerDisplayName] &aauf &2CraftTopia.de'
      - '&bSpieler auf dem Netzwerk Online: &f&l%bungee_total%'
    Footer:
      '1':
      - '&aAlle Informationen findest du unter &2CraftTopia.de'
      - ''
      - '&bDu befindest dich gerade hier: &3%player_world%'
      - '&bDein Kontostand beträgt &3%craftconomy_Topitaler% &bTopitaler'
      - '&7Uhrzeit: &f%server_time_HH:mm:ss%'
  useGeneralName: true
  # When this set to true, in case you dint defined PlayerName, Header or Footer in GroupFormat, then default one from GeneralFormat will be used
  useGeneralHeader: true
  useGeneralFooter: true
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  GroupFormat:
    '1':
      PlayerName: '%vault_rankprefix%&r [playerDisplayName]'
      Header:
        '1':
        - '&aWillkommen &2[playerDisplayName] &aauf &2CraftTopia.de'
        - '&bSpieler auf dem Netzwerk Online: &f&l%bungee_total%'
    Footer:
      '1':
      - '&aAlle Informationen findest du unter &2CraftTopia.de'
      - ''
      - '&bDu befindest dich gerade hier: &3%player_world%'
      - '&bDein Kontostand beträgt &3%craftconomy_Topitaler% &bTopitaler'
      - '&7Uhrzeit: &f%server_time_HH:mm:ss%'
    '2':
      PlayerName: '%vault_rankprefix%&r [playerDisplayName]'
      Header:
        '2':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '2':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'

```

---

**Cmi Version (using`/cmi version`):** 
8.6.16.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4 git-Paper-210
