### ISSUE TITLE
Shedule commands (eventcommands) issues

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#261]
Description of issue or feature request:
Since last Update to 7.6.6.1 it allways tells me on my eventcommands "That Player cant be found"

```
quitServer:
  Use: true
  List:
  - cmi fly [playerDisplayName] false -s
```

ERROR:
![image](https://user-images.githubusercontent.com/12080017/38730431-ccc219cc-3f16-11e8-94e8-602c20824cf6.png)
"it tells" the Player cant be found.
```

Cmi Version (7.6.6.1): 
Server Type (Spigot): 
Server Version (1.12.2 6 days old):
