### ISSUE TITLE
schedules error

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2735]
**Description of issue:**
If you put a decimal in the delay line in the schedules.yml it throws an error on the plugin reload and that schedule doesn't work.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/G956WY6b
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RefreshFabaledSkyblockHolograms:
  Enabled: true
  Delay: 1.5
  Repeat: true
  Commands:
  - island admin refreshholograms
```

---

**Cmi Version (using`/cmi version`):** 
8.6.18.7
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper(86) 1.15.2-R0.1-SNAPSHOT
