### ISSUE TITLE
IC without giving Players command Permission

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#279]
Description of issue or feature request:

#### Maybe a Feature Request Not Really Sure Some IC Commands Work others Don't ####

ERROR:
```
####################
##  Quoting you....
Added option to change IC into public one which can be utilized by making sign with 
top line as [ic:[nameOfIC]] in example [ic:spawnTeleport] you will need to have 
cmi.interactivesign permission node to create signs like this.

I have tried this everyway I can think of. I want to add a simple PvP counter in 
my arena. I would Prefer to use a Torch as the block but no matter what I do it tells me 
that the Player does not have the Perm for cmi.command.counter. 

The only way I can get the command to run at all is to use sudo [playerName] counter 
start t:5 msg:Pvp_Start! with the permission to always use counter.

Without Sudo it throws a usage error as follows....
Usage: /counter [join/leave/start] (t:time) (r:[range/-1]) (msg:custom_message) (-f)

I have made the block public added [ic:counter start t:5 msg:Pvp_Start!] on 1st line 
tried [ic:pvp] which is the name of the IC. I'm at a lost. 

Does only certain commands work? 

I have tppos set up and it works just fine with no perms to use that command. ##
####################
```

Cmi Version (using`/cmi version`): 7.6.10.0-> null
Server Type (Spigot/Paperspigot/etc): Paper
Server Version (using `/ver`): git-Paper-1392 (MC: 1.12.2)

**Comment by mercurialmusic** [comment]
I'm not quite sure what you're looking for, so this is a shot in the dark rather than an attempt to insult your intelligence, but do the command prefixes (specialized commands) asPlayer! or fromConsole! not work? I've used those as workarounds on a few things depending what I was after. Sudo will literally run the command as the player, requiring them to have the permission node, while I've noticed asPlayer! doesn't quite have as many requirements and fromConsole! will let me bypass perms entirely.

**Comment by MCTyler** [comment]
Ok, Where in the Hell did you fine reference to those prefixes? Lol I'm pretty sure I read the Wiki.

**Comment by mercurialmusic** [comment]
Yup. [Specialized Commands](https://www.spigotmc.org/wiki/cmi-specialized-commands/). =p I did quote it wrong, though, asConsole! instead of fromConsole! -- super useful. And Zrips should never stop lol. Anyone can update those wiki's ;)

**Comment by MCTyler** [comment]
Ahh Man thought you had something here.... :(
[18:14:02 INFO]: Captain_Jean_Luc doesn't have permission for: cmi.command.counter

**Comment by mercurialmusic** [comment]
Was that asPlayer! or asConsole! ? How did you do the command?

**Comment by mercurialmusic** [comment]
Ah yeah. I haven't actually played with that one. Since there are a couple location-based commands in CMI maybe you could request a new Specialized Command that uses targetCoord:[xyz]! or similar.

**Comment by MCTyler** [comment]
its really no big deal but I don't understand his Permission reference in SC...perm:[permissionNode]!, Doen't matter if you have this or not it's checking the Permission of the Player.

**Comment by mercurialmusic** [comment]
That makes it possible to do conditional perms, like checking if a player has permission A then it will run command B which might not have anything to do with permission A.

**Comment by MCTyler** [comment]
We Really all need to take Our favorite Parts and Rewrite the Wiki. Sounds like IC, SC and CP are your strong Point!

**Comment by CloudeLecaw** [comment]
i also saw this whole stuff in the patchlogs but never worked with it, may im a too old man to understand all this new commandstuff things
i also didnt understood what is IC SC and CP? what is that all?

**Comment by CloudeLecaw** [comment]
may this help :) its a Custom Alias i have created
```
  lll:
  - perm:cmi.command.customalias.lll! fromConsole! cmi effect $1 night_vision 1800
  - perm:cmi.command.customalias.lll! fromConsole! delay! 1
  - perm:cmi.command.customalias.lll! fromConsole! cmi effect $1 water_breathing 1800
    5
  - perm:cmi.command.customalias.lll! fromConsole! tell $1 Du hast eine Unglaublichen
    Effekt bekommen^^
  - perm:cmi.command.customalias.NoPermlll! fromConsole! tell $1 Du kannst keine Extrawurst
    bekommen..sorry!!!
```

the groups that do not have the permission to Execute the wanted command get the permission to execute the  not wanted command.  and if someone had none of this permission then no comamnds will be executed...

may this also words with what u wanted to do?

**Comment by CloudeLecaw** [comment]
how About creating a shedule that gives the Player a fake counter? and this command u let the button execute?
```
LeaverCounter:
  Enabled: true
  PerformOn:
    1:
      MinPlayers: 1
  Commands:
  - fromConsole! cmi titlemsg [playerName] Countdown  %subtitle% 40
  - delay! 10
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 30
  - delay! 10
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 20
  - delay! 10
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 10
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 9
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 8
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 7
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 6
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 5
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 4
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 3
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 2
  - delay! 1
  - fromConsole! cmi titlemsg [playerName] Countdown %subtitle% 1
  - delay! 1
  - fromConsole! titlemsg [playerName] Flymode is %subtitle% active now!
  - fromConsole! cmi fly [playerName] true
```
now you place a button and sudo the execution of this command to a black/item/button what ever..
