### ISSUE TITLE
[Feature Request] Anti Purge Option

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#281]
**Description of issue or feature request:**
a whitelist for listet UUIDs that can go over the purgelimit and will not go deleted

**how this could look in the config:**
```
purge:
  # Cleans files on server startup
  CleanOnStart: true
  # How long player should be offline for his data to be moved
  OfflineDays: 90
  # Whitelistet Players dont get deleted
  whitelistPlayers: true
    whitelist:
    - a0d1fc8a-3541-4a33-bef8-bb1c66cf2b9e
```

**Why this can be usefull?:**
- Some Plugins work with "dummfiles" of a Player and Need an existing uuid for this
- some staff members may not be online for some longer time and u dont want that their data got deleted if they expire the purgetime
