### ISSUE TITLE
The problem with Russian localization

### ISSUE THREAD

**Issue by lluffy-1PK** [Zrips/CMI#2828]
The problem with Russian localization, does not show the description of the commands
![CMI](https://user-images.githubusercontent.com/56547251/75191001-3240c480-575a-11ea-96fd-17e2fbd0cf61.png)

CMI: 8.6.19.5
Server version: Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by DarkFort** [comment]
Hey. I translated this plugin and shared it. You can download it here - http://rubukkit.org/threads/cmi-270-kommand-essentials-economy-mysql-sqlite.163791/
If the author of the plugin wants to add this translation, then no problem.

**Comment by Zrips** [comment]
@lluffy-1PK 
Someone mistranslated some variables, check your locale file and update appropriate lines with this ones
```
command:
  help:
    output:
      usage: '&eИспользуй: &6%usage%'
      cmdInfoFormat: '[command] &f- &e[description]'
      cmdFormat: '&6/[command]&f[arguments]'
      helpPageDescription: '&e* [description]'
      explanation: '&e * [explanation]'
```
Those variables will be transalted to russian, no idea why some one did this, but that prevents from it being replaced with appropriate vaalues
