### ISSUE TITLE
Players encounter the warm up for warping when simply changing pages in the warp gui.   Also, the pages in the GUI are numbered erratically.

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2838]
**Description of issue:**
When a player does /warp to see the warp GUI, and then tries to change pages, they get a warmup on the command as though they were actually warping before the page changes and they can see the next page. This part of the issue is clearly from my having a warmup on /cmi warp , but it seems page changes should be treated differently from actual warps.  Is there a way to do this?  I see a feature request for this here: https://github.com/Zrips/CMI/issues/2778

Also, the pages are numbered somewhat erratically:   
When on the first page of warps on my server, it shows it as page 1/2 both in the center and in the page changing icon on the bottom right. After changing to the second page, both show as page 2/4.  If I then change to the 3rd page (with a countdown for the warmup every page change), it shows as page 3/3!

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi tp :2:true
  - cmi tpa :2:true
  - cmi tpaccept:2:true
  - cmi there :2:true
  - cmi back:2:true
  - cmi warp :2:true
  - cmi home :2:true
  - cmi spawn:2:true
```

---

**Cmi Version (using`/cmi version`):** 
[13:56:26 INFO]: --------------------------------------------------
[13:56:26 INFO]: CMI plugin version: 8.6.19.6
[13:56:26 INFO]: Server version: Paper(105) 1.15.2-R0.1-SNAPSHOT
[13:56:26 INFO]: Vault version: 1.7.2-b107
[13:56:26 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[13:57:09 INFO]: This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[13:57:09 INFO]: Checking version, please wait...
[13:57:09 INFO]: Previous version: git-Paper-60 (MC: 1.15.1)
[13:57:09 INFO]: You are 15 version(s) behind
