### ISSUE TITLE
ranks  commands  delay!  not work

### ISSUE THREAD

**Issue by betwowt** [Zrips/CMI#2858]
**Description of issue:**

my ranks config

```
Rank1:
  Enabled: true
  DisplayName: "&2萌新小白"
  DefaultRank: true
  AutoRankup: true
  NextRanks: 
  - Rank2
Rank2:
  Enabled: true
  DisplayName: "&2初来乍到"
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 0
  ExpCost: 0
  NextRanks:
  - Rank3
  Commands:
  - asFakeOp! lp user [playerName] parent set rank2
  - delay! 2
  - asPlayer! cmi kit new1
  - broadcast! &6[playerDisplayName] &e进入到[初来乍到]阶段
  - asFakeOp! cmi titlemsg [playerName] 资源世界已解锁
  StatsRequirements:
  - "PlayTime:300"
```

up to Rank2    delay! 2  is Ineffective

and console print  Unknown command. Type "/help" for help.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):8.6.19.6 BungeeCord

**Server Type (Spigot/Paperspigot/etc):Spigot 1.15.2-R0.1-SNAPSHOT 

**Server Version (using `/ver`):This server is running CraftBukkit version git-Spigot-c574e08-918061b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
