### ISSUE TITLE
Player-specific PlaceholderAPI variables in PlayerName config key (tabList)

### ISSUE THREAD

**Issue by kadenscott** [Zrips/CMI#2866]
**Description of issue:**
The PlayerName config value doesn't parse player-specific PlaceholderAPI placeholders in the tablist config.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
_From tabList.yml_
```
  GeneralFormat:
    PlayerName: '%deluxetags_tag% [playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
```

---

**Cmi Version (using`/cmi version`):** 
8.6.19.8
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.15.2 build 121
**Server Version (using `/ver`):** 
Paper 1.15.2 build 121
