### ISSUE TITLE
Silktouch Spawners Exp Glitch

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#288]
```
####################
## There is no error but one of my Players discovered they could endlessly get Exp by 
"farming" Spawners over and over again with a silk touch PickAxe. Any way to disable 
this? I would really like to turn off Exp completely from breaking Spawners.##
####################
```
[16:28:28 INFO]: CMI plugin version: 7.6.10.0-> null
[16:28:28 INFO]: Server version: Paper 1.12.2-R0.1-SNAPSHOT
[16:28:28 INFO]: Vault version: 1.6.10(+)

**Comment by CloudeLecaw** [comment]
> Probably not needed but here is Video of glitch....
https://youtu.be/1RF3iwDrH4k

Who is this funny man that wanted into the Video? :D

**Comment by MCTyler** [comment]
Sentinel

**Comment by LogGits** [comment]
Could not reproduce this. Can you provide the necessary config section that relates to silktouch spawners. This can help us find the issue.

**Comment by CloudeLecaw** [comment]
sure we all can do this 🥉 
```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 2
```

when he now give the Rights to do this with silktouch 1... then the spawner gets silktouched with as normal silktouch .. on my Server i use the Solktouch 2 ench so not all Players can get this, but i opend ways for them to craft it.
