### ISSUE TITLE
Allow players to type "m" or "k" after amount for /pay <amount> command

### ISSUE THREAD

**Issue by PotatoIQ** [Zrips/CMI#2895]
**Description of issue or feature request:feature request**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Many people in our server have requested to be able to type "k" or "K" and "m" or "M" after an amount for the /pay command, instead of having to type all 0s, as it can be tricky sometimes to count all the 0s during payment or sometimes players add extra/less 0 when paying.
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):Spigot** 

**Server Version (using `/ver`):1.15.2**

**Comment by Zrips** [comment]
Config file
```
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: true
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
```
