### ISSUE TITLE
Playerheads in hologram not working in 8.6.20.3+

### ISSUE THREAD

**Issue by codingvincee** [Zrips/CMI#2961]
**Description of issue:**
When using playerheads as icon in a hologram, a steve head shows in version 8.6.20.3 and above. The feature works perfectly fine in 8.6.20.2

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Welcome:
  Loc: spawn;190.49;77.0;-332.79
  Interval: -1.0
  Range: 8
  RangeExtra: 64
  Spacing: 0.32
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&c&lWelcome to &b&lMINECLAPS &c&l%cmi_user_name%!'
  - '&7Use &f/help &7to see the available commands.'
  - ICON:head:%cmi_user_name%
```

---

**Cmi Version (using`/cmi version`): 8.6.20.3-5** 

**Server Type (Spigot/Paperspigot/etc):Paperspigot** 

**Server Version (using `/ver`):git-Paper-9. (MC: 1.15.2)**
