### ISSUE TITLE
Bossbar Persistent Bug

### ISSUE THREAD

**Issue by BiGUNMAN** [Zrips/CMI#2975]
**Description of issue:**
The new update that attempts to create persistent bossbars does **not** work as intended (from my understanding).
The following image displays what a user sees for approximately the first 10 seconds after joining the server (if they rejoin the server, they see this as well). As can be seen in the config, most of these bossbars have expired up to 240 seconds ago (at minimum).
 https://media.discordapp.net/attachments/650964421044338688/691172835460251658/unknown.png

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
announce-bossbar-trigger:
  Enabled: true
  MinPlayers: 1
  Delay: 250
  Repeat: true
  Randomize: true
  Commands:
  - cmi schedule announce-bossbar-1
  - cmi schedule announce-bossbar-2
  - cmi schedule announce-bossbar-3
announce-bossbar-1:
  Enabled: false
  MinPlayers: 1
  Delay: 1
  Repeat: false
  Randomize: false
  Commands:
  - cmi bossbarmsg all &fAccess the shop by typing &2/shop -s:1 -c:green -t:10
  - cmi sound ENTITY_SHEEP_AMBIENT -all -v:0.3
  - cmi sound ui_toast_in -v:3 -all
announce-bossbar-2:
  Enabled: false
  MinPlayers: 1
  Delay: 1
  Repeat: false
  Randomize: false
  Commands:
  - cmi bossbarmsg all &dBuy a &nrank!&d Support the server! &e/buy -s:10 -c:red -t:10
  - cmi sound ENTITY_SHEEP_AMBIENT -all -v:0.3
  - cmi sound ui_toast_in -v:3 -all
announce-bossbar-3:
  Enabled: false
  MinPlayers: 1
  Delay: 1
  Repeat: false
  Randomize: false
  Commands:
  - cmi bossbarmsg all &cLevel up! Unlock new features, use &3/levelup -s:10 -c:yellow
    -t:10
  - cmi sound ENTITY_SHEEP_AMBIENT -all -v:0.3
  - cmi sound ui_toast_in -v:3 -all
```

---

**Cmi Version (using`/cmi version`):** 8.6.20.6

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.15.2
