### ISSUE TITLE
Request for a limit on mobspawner placement in a area

### ISSUE THREAD

**Issue by rybuilder23** [Zrips/CMI#2978]
**Description of feature/improvement request:**
---
with cmi you can mine en place mob spawners if you allow it. 
My idea is to limit spawners in a area.

### Detailed explanation of what it should do, when and in what situation: ###
It should limit the mob spawner placement. for example you can only place 5 spawners in a radius of 15 blocks.

### Basic explanation as to why this feature is needed and/or useful to have: ###
why? because players can mine now 30 spawners en placed them in one area en thats not realy good voor 1.15 minecraft.

i hoop that this is a good idea.

**Comment by Zrips** [comment]
Config file Spwners category
```
  Proximity:
    # Allws to limit how tight spawners can be placed from each other
    Use: false
    # Radius in blocks from blaced block. Max range is 16
    # Can bypass with cmi.spawners.proximity.bypass
    Range: 3
```
