### ISSUE TITLE
White or Gray cannot be used as custom headdrop criteria for trading llamas

### ISSUE THREAD

**Issue by PsychoLynx** [Zrips/CMI#2990]
**Description of issue:**
I am trying to make trader llamas drop their heads based on their color.
I am able to make Brown and Creamy Trader Llamas drop their heads, but not White or Gray llamas (summoned using /summon trader_llama ~ ~ ~ {Variant:0-3} command)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  trader_llama:
    DropChance: 100
    LowerWithEachDrop: 0.0
    Heads:
    - 100:c-brown:ODQyNDc4MGIzYzVjNTM1MWNmNDlmYjViZjQxZmNiMjg5NDkxZGY2YzQzMDY4M2M4NGQ3ODQ2MTg4ZGI0Zjg0ZCJ9fX0=
    - 100:c-creamy:YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0=
    - 100:c-white:YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0=
    - 100:c-gray:YmU0ZDhhMGJjMTVmMjM5OTIxZWZkOGJlMzQ4MGJhNzdhOThlZTdkOWNlMDA3MjhjMGQ3MzNmMGEyZDYxNGQxNiJ9fX0=
```

---

**Cmi Version (using`/cmi version`):** 
8.6.20.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-136 MC: 1.15.2
