### ISSUE TITLE
CMI Kit Placeholders

### ISSUE THREAD

**Issue by Steev93** [Zrips/CMI#2993]
Placeholders in the kit.yml file provided do not work, from {displayname} to {kitname}.

This also returns back an error when using {displayname} for a cmd to run on there name

As seen here; http://prntscr.com/rnglzu

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Player should have appropriate permission node to use particular kit: cmi.kit.[kitName]
# cmi.kit.newbie will allow to use newbie kit
# Possible custom variables: {USERNAME} {DISPLAYNAME} {WORLDNAME} {KITNAME} {RANDOMPLAYER}
# Edit kits ingame with /cmi kiteditor to avoid formating issues
Newbie:
  Description:
  - '&eWill give you some stuff for money and exp'
  - '&eCan be used every X minutes'
  CommandName: Newbie
  Enabled: true
  DropOnGround: true
  ShowDespiteWeight: false
  Delay: 36000
  MaxUsages: -1
  MoneyCost: 100.0
  ExpCost: 30
  Commands:
  - msg &eYou just got &6{KITNAME} &ekit!
  Conditions:
  - cmi.kit.get
  - cmi.command.fly
  Group: groupName
  Items:
    '1':
      v: 2230
      type: STONE
      amount: 70
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §3Stone
        lore:
        - §2Name §3{USERNAME}
        - §3Display name §2{DISPLAYNAME}
        - §2Kit §3{KITNAME}
        - §3World name §2{WORLDNAME}
        enchants:
          ARROW_DAMAGE: 3
          THORNS: 5
    '3':
      v: 2230
      type: OAK_PLANKS
      amount: 30
```

---

**Cmi Version (using`/cmi version`):** 
8.6.20.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-paper-137 MC 1.15.2
