### ISSUE TITLE
FlightCharge issue

### ISSUE THREAD

**Issue by BBSnowIce** [Zrips/CMI#3005]
**Description of issue or feature request:**
I'm trying to make FlightCharge Deduct Only For Time but when player get 3600 seconds, after a little time, his time decrease without doing  anything, no commands at all.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yml
FlightCharge:
  EnabledByDefault: false
  AutoSwitch: false
  ExpRechargeCost: 0.0
  MoneyRechargeCost: 0.0
  MaxChargeLevel: 8640000
  DeductOnIdling: 1.0
  DeductOnlyForTime: 1.0
  DeductOnFallMulti: 0
  DamageOnFall: false
  DamageOnToggle: false
  KillOnFall: false
```

---

**Cmi Version (using`/cmi version`):** 
8.6.20.9
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
