### ISSUE TITLE
Spawners (Still) Giving out Exp When Harvested Creating Unlimited Exp Loop

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#301]
Config Action added does not Disable Getting Exp from Mining Spawners With SilkTouch Pick. @Zrips Mentioned that it might be another Plugin interacting But I have no other Plugins that effect Spawners. 
I will list below.

I fully Disabled this in the Config as as expected SilkTouch didn't work, but I still got Exp from 
Spawners. This is Hard Coded in Vanilla Minecraft I'm pretty sure, so I can't immediately blame MobHunting. I will try disabling MobHunting and report back any changes that are relevant.

I have Doubled Checked MobHunting and Jobs, those are the Only Plugins that Give Rewards at all. Recipe Manager Plugin is Strictly Crafting Recipes. Please Help if you see something I missed. Does McMMO Give Exp for Spawners?

MobHunting is Disabled: This may Indeed be Broke so I made a Issue there as well.

```
  Let the players get the naturally dropped XP from mobs spawned from mobspawners, 
  eggs and from eggs from Dispensers ?
  disable_naturally_dropped_xp_from_mobspawners_and_eggs: true

```
     Plugins (49): AnimationLib, AutomaticInventory, AutoPickup, BlowableObsidians, 
     ChestShop, Citizens, CMI, CombatLogX, CompatNoCheatPlus, 
     ConditionalCommands, ConsoleSpamFix, CrateReloaded, CS-CoreLib,
     EpicRename, ExoticGarden, Factions, FactionScoreboard, GriefPrevention, 
     InstaWall, Jobs, LibsDisguises, LuckPerms, LWC, MassiveCore, mcMMO, 
     MessageFilter, MobHunting, NoCheatPlus, NoFlyZone, OldCombatMechanics, 
     PlaceholderAPI, Prison, ProtocolLib, ProtocolSupport, ProtocolSupportLegacySupport, 
     ProtocolSupportStuff, RecipeManager, Sentinel, Slimefun, StackMob, TradeMe, 
     TransportPipes, Vault, VaultChatFormatter, Votifier, VotingPlugin, WorldBorder, 
     WorldEdit, WorldGuard, 

CONFIG SECTION:
Config File Pardon Misspellings, I copied it Verbatim.
DropExp: True or False in Config Yield the exact same results of EXP being Dropped.
```
#####################################
##  wSpawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any 
spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner 
charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have 
cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required 
to use silk touch pickaxe to get droped spawner
    Enabled: true
    # When set tp fa;se, exp will not be dropped from broken spawner independent 
if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1 ##
#####################################
```

[16:05:34 INFO]: CMI plugin version: 7.6.12.0
[16:05:34 INFO]: Server version: Paper 1.12.2-R0.1-SNAPSHOT
[16:05:34 INFO]: Vault version: 1.6.10(+)

BTW: How did I end up with a ArmorStand Spawner as I tested this Stuff? I have never 
Spawned or Created one of those...Yikes!

https://github.com/Rocologo/MobHunting/issues/398
