### ISSUE TITLE
RandomTeleport ignores most config options and safeteleport

### ISSUE THREAD

**Issue by spathizilla** [Zrips/CMI#3043]
**Description of issue:**
RandomTeleport ignores Y settings and also will drop into lava regardless of settings or the safeteleport permission

RT resulted in me landing at:
* 1331, 11, 519 -- WRONG
* 403, 29, 2352 -- WRONG
* 575, 63, -575 -- Correct
* 2973, 61, -2183 -- WRONG and teleported inside a block!!!
* 1292, 75, -1061 -- Teleported inside a block

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    world:
      Enabled: true
      MaxRange: 3000
      MinRange: 0
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 63
      maxY: 80
```
cmi.safeteleport is set but /cmi checkperm safeteleport shows it as orange. I most definitely have the permission (op alone should grant it but specifically set it on myself with luckperms)

---

[16:05:07 INFO]: CMI: 8.6.21.2 BungeeCord
[16:05:07 INFO]: Server version: Paper(161) 1.15.2-R0.1-SNAPSHOT
