### ISSUE TITLE
Create Countdown (w/ placeholders)

### ISSUE THREAD

**Issue by TimHarrio** [Zrips/CMI#3055]
**Description of feature/improvement request:**
Being able to also create cooldowns in CMI and execute commands at the end of this would be handy. It would also require Placeholders with the remaining time (ex: "3h 2m 1s").
I often use cooldowns and I have to do it with Javascript but it is not practical and in addition I cannot execute commands at the end of these.

---
### Detailed explanation of what it should do, when and in what situation: ###
When we vote execute a cooldown which after 24 hours will remind us to vote.
If with CMI we can create cooldowns we can easily use placeholders with it in Deluxemenu (Kits, Upgrades, etc ...)

**Comment by Baktus79** [comment]
There are cooldowns in CMI already

```yaml
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.cooldownbypass.[commandname] permission node
  # Always use full command name and not its alias
  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"
  Enabled: false
  List:
  - cmi heal:180
  - cmi feed:120
```

```yaml
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
