### ISSUE TITLE
Skin module loads old skins

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3066]
When a player joins, skins that are three to six months old are sometimes loaded. The correct skin is visible shortly before it is overwritten. The problem was first observed in version 8.6.21.5, before that the feature worked. Disabling the skin function (Enabled: false) solves the problem.

Another bug of the skin module can be found in #2519.

```
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 60
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with posible requests
  SkinRequestFrequency: 10
```
Paper 1.13.2 - 653
CMI 8.6.21.5
