### ISSUE TITLE
/msg Messages are not sent

### ISSUE THREAD

**Issue by Juiceqad** [Zrips/CMI#3076]
When sending a message / msg, he writes that "You can not find a player with the same name" while the nickname is entered correctly. Also does not see the nickname between the servers.

**Comment by Zrips** [comment]
are we talking about bungee private messages here entirely or do you have issue with local private messages?

**Comment by Steev93** [comment]
Local private messages, having the same issue.

**Comment by mrfloris** [comment]
- Download and Install CMI-Bungeecord (<http://www.zrips.net/wp-content/uploads/2020/02/CMIB1.0.0.4.jar>)

- Update CMI's `config.yml` (see below)
```yaml
# Enable CMI Bungee Support 
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true

# CMI config.yml, enable CMI Chat and CMI Bungee Chat
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true

# Also:

  # Do you want to enable private messaging over bungeecord
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: true
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: true
```
Then walk through all the other options related to chat. 

(Next, /stop the servers, and start it up again)

Just posting this here to give you some stuff to double check.
