### ISSUE TITLE
Chest trashcan

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3085]
Minecraft is a game in which players spend many hours. Item and chest management is inevitably an issue that keeps many players busy. Sometimes you can just throw things away. A much requested feature is a trashcan GUI for an open chest. Such a GUI would save the hassle of having to fill all items into the inventory to use the trashcan GUI.
So it would be fantastic if a shift + right click on a chest would open the chest with a trashcan GUI for direct movement of the corresponding items. Of course it should work for normal chests and double chests and be scaled accordingly. You could also think about including barrels in this system.

**Comment by mrfloris** [comment]
At the moment, I haven't tested this with blocks and chests and barrels, what I've done on my server is add /trash with /cmi dispose and [trash] with /cmi ic. 

```
  trash:
    Cmds:
    - cmi dispose
```
`customAlias.yml`

Give them the permission. 

and for /cmi ic, i've added `interactiveCommands.yml` section
```
trash:
  Locations:
  - general;12752.0;32.0;12008.0
  Commands:
  - click:rightclick! asConsole! cmi dispose [playerName]
  SignLines:
  - '&0&l TRASH BIN'
  - '&7~~~~~~~~~~~~'
  - '&9&lTry with /sell'
  - ' '
  Public: true
```

note please that the lines on the sign and the location are just for my server
I recommend adding the ic through the game. 

Then each time a player makes a sign with [trash], they can right click it and it will open.
