### ISSUE TITLE
bungeeChat

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3099]
**Description of issue:**

Normal chat is not sent across server whereas "/msg" "/w" and "/staffmsg" do transmit across.
Below is the config enabled, i have the cmi bungee plugin installed on my proxy, and CMI 8.6.22.1 on all of my servers.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: true
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: true
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.22.1 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper(162) 1.15.2-R0.1-SNAPSHOT
