### ISSUE TITLE
Playtime reset to 0 hours after reaching 100 days

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#3102]
**Description of issue:**
If player reached 100 days on their playtime, the playtime is set automatically back to 0, causing /prewards to not display the time needed correctly

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
PlayTimeRewards.yml https://paste.md-5.net/ibidavomax.bash
config.yml https://paste.md-5.net/yecegideba.coffeescript
```

---

**Cmi Version (using`/cmi version`):** 8.6.22.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot build 167

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Interesting, as this could be issue with minecraft itself as it stores player playtime in Integer type value, which can only be no higher than 2 147 483 647. This looks big, but playtime is saved in ticks and you have 20 of those in a second, so 100 days adds up. Will recheck code to make sure that everything is working as it should from y end with such huge playtimes

**Comment by Zrips** [comment]
What do you have set for PlayTimeFromStats in your config file?

**Comment by Sikatsu** [comment]
I noticed the same actually.   

PlayTimeFromStats: false

**Comment by blek-id** [comment]
It's on false

**Comment by blek-id** [comment]
Some playtime related config

```
  # When set to true, player play time will be grabbed from user stats file instead of from CMI user data file
  # This can help to get more accurate play time if you have older server and using players stats feature
  PlayTimeFromStats: false
  # When set to true, playtimetop list will be loaded on server startup
  PreloadTopPlaytime: false
  # Do you want to use CMI playtime tracking
  # While this is enabled, player play time will be record for each hour he playied in server
  # This doesnt have effect on rankup or /playtime commands, it will only show more specific playtime by hours when using /cplaytime command
  CMIPlayTimeTracking: true
  # Player names to be excluded from playtimetop list
  PlaytimeTopExclude:
  - Some
  - Names
  - Here
```
