### ISSUE TITLE
You can change your nicknames to someone else by using formats

### ISSUE THREAD

**Issue by variananora** [Zrips/CMI#3116]
**Description of issue:**
You can change your nicknames to someone else by using formats

You can't do this:
![image](https://user-images.githubusercontent.com/34732414/79456952-945ecd00-8019-11ea-90b4-bbb39881ff3b.png)
but you can do this:
![image](https://user-images.githubusercontent.com/34732414/79457025-b0fb0500-8019-11ea-98da-6872b36a2270.png)

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
NickName:
  BlackList:
  - admin
  - administrator
  - server
  - staff
  - staf
  - variananora
  MinLength: 3
  MaxLength: 16
  Prefix: '~'
  PrefixWhenDifferent: false
  IncludeInTabComplete: true
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.22.1 BungeeCord
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Server version: Paper(184) 1.15.2-R0.1-SNAPSHOT
