### ISSUE TITLE
CMI: Failed to apply skin when using /skin

### ISSUE THREAD

**Issue by SGlance** [Zrips/CMI#3157]
/cmi skin <player name> give out "Failed to apply skin" message.

No error for /skin command but sometimes we do got this upon player joining:
```
[Wed, 22. Apr 2020 01:48:55 SGT WARN] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at com.Zrips.CMI.Modules.Skin.SkinManager.setSkin(SkinManager.java:157)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:119)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:100)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at com.Zrips.CMI.Modules.Skin.SkinListener$2$1.run(SkinListener.java:52)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Wed, 22. Apr 2020 01:48:55 SGT WARN] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

config for this issue:
```
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 60
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with posible requests
  SkinRequestFrequency: 10
```

---

**Cmi Version:**
[Wed, 22. Apr 2020 03:10:40 SGT INFO] --------------------------------------------------
[Wed, 22. Apr 2020 03:10:40 SGT INFO] CMI: 8.6.23.0
[Wed, 22. Apr 2020 03:10:40 SGT INFO] Server version: Paper("49fdb18") 1.15.2-R0.1-SNAPSHOT
[Wed, 22. Apr 2020 03:10:40 SGT INFO] Vault version: 1.7.2-b107(CMIEInjector)
[Wed, 22. Apr 2020 03:10:40 SGT INFO] --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[Wed, 22. Apr 2020 03:10:42 SGT INFO] This server is running Paper version git-Paper-"49fdb18" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
CMI
