### ISSUE TITLE
Placeholder with featherboard.

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#320]
How can I use CMI's rank placeholders on my featherboard? I cannot seem to get them to work.
#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## PASTE ERROR HERE ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
  nextrank: # Server status (ram and tps)
      text:
      - '&7Next: &a{cmi_user_canrankup}'
      interval: 30
      random: false
```

Cmi Version (using`/cmi version`):  7.1.1
Server Type (Spigot/Paperspigot/etc): spigot
Server Version (using `/ver`): 1.12.2
