### ISSUE TITLE
CustomAliasPermissons

### ISSUE THREAD

**Issue by JaCyGa** [Zrips/CMI#3206]
I tried to use LuckPerms via permisson to disable CustomAlias from the yml, unfortunately the permissons in the alias editor are always reset to true no matter how often I change them

```
CustomAlias:
  spawn:
    Cmds:
    - asConsole! mvtp [playerName] city
  skyspawn:
    Cmds:
    - asConsole! mvtp [playerName] skyplots
  lobby:
    Cmds:
    - spawn
  survival:
    Cmds:
    - asConsole! mvtp [playerName] survival
  insel:
    Cmds:
    - asConsole! mvtp [playerName] insel
  partikel:
    Cmds:
    - pp gui
  reiten:
    Cmds:
    - ride
  spielzeit:
    Cmds:
    - playtime
  wetter:
    Cmds:
    - pweather
  zeit:
    Cmds:
    - ptime
  zuhause:
    Cmds:
    - p list mine
  spielregeln:
    Cmds:
    - cmi ctext Spielregeln
  teamregeln:
    Cmds:
    - cmi ctext Teamregeln
  vote:
    Cmds:
    - cmi ctext Vote
  discord:
    Cmds:
    - cmi ctext Discord
  hilfe:
    Cmds:
    - cmi ctext hilfe
  müll:
    Cmds:
    - cmi dispose
  berufe:
    Cmds:
    - jobs browse
  kündigen:
    Cmds:
    - jobs leaveall
  abfüllen:
    Cmds:
    - bottle get max
  geschenke:
    Cmds:
    - prewards
```

---

**Cmi Version (CMI8.6.23.5):** 

**Server Type (Spigot/Paperspigot):** 

**Server Version (1.15.2):**

**Comment by LogGits** [comment]
You could try:
```yaml
  testcommand:
    Cmds:
    - msg! [playerName] hi
    Perm: true
```
The `Perm: true` attribute make it so using the permission node `cmi.customalias.[alias]` or in this case `cmi.customalias.testcommand` will give them permission to access.
