### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by tribrix** [Zrips/CMI#3220]
**Question: **
How do you add a cool down to teleports like /spawn, homes and portals?

**Comment by CloudeLecaw** [comment]
```
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.cooldownbypass.[commandname] permission node
  # Always use full command name and not its alias
  # ----------
  # Alternatively you can use cmi.cooldown.[some_command].[timer] permission node. For example: cmi.cooldown.cmi_heal.30 which will set 30 second cooldown on /cmi heal command
  # If you want to apply cooldown on command when variable is provided, add extra _ at end. For example cmi.cooldown.cmi_heal_.30 which will only use this cooldown when healing some one else
  # KEEP IN MIND that for permission to work you need to set base command cooldown in this list, otherwise permission node will have no effect
  # -----
  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"
  Enabled: false
  List:
  - cmi heal:180
  - cmi feed:120
```
