### ISSUE TITLE
[Bug] Sleeping in bed doesn't move the stars or display title time anymore

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3222]
**Description of issue:**

Updated to latest cmi and noticed when I sleep on the server it's just delay, then it's morning. The stars don't move and the timer speeding up no longer displays.
---

see video:
https://youtu.be/mTiVUGXP8wQ

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: false
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 50
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 1
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

---
```
>cmi version
[19:05:48] [Server thread/INFO]: --------------------------------------------------
[19:05:48] [Server thread/INFO]: CMI plugin version: 8.6.23.6
[19:05:48] [Server thread/INFO]: Server version: Spigot 1.15.2-R0.1-SNAPSHOT
[19:05:48] [Server thread/INFO]: Vault version: 1.7.3-b
[19:05:48] [Server thread/INFO]: --------------------------------------------------
>
```
