### ISSUE TITLE
Players go AFK while fishing

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#3259]
**Description of issue:**
Players who are fishing without moving get flagged as afk, resulting in a possible kick or paused playtime and rewards. I would think that fishing would fall under the DisableOnInteract flag however it could potentially fall into a separate category.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables item pickup while afk
  DisableItemPickup: false
  
  # Mob Spawn settings
  
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false
```

---

**Cmi Version (using`/cmi version`):** 8.6.24.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.15.2, paper-213

**Comment by CloudeLecaw** [comment]
i also wished tere would be a dection that can see if players do fishing. we have the same problem in our server. Currently there is no detection for this. It would beed something like a "left and rightclick detection" for this. Also if the player islooking arround the afk state does not chance. Maybe there is a chance to also add this?

**Comment by Zrips** [comment]
Could you provide exact fishing setup players used to bypass current protection? Picture would be fine, video would be better but not necessary.

**Comment by CloudeLecaw** [comment]
I aggree withe101stella  we also have this on our server

This is our afk setup form CMI

```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  AutoAfkIn: 600
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eist jetzt AFK
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eist jetzt AFK
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eist nicht mehr AFK
  # Defines how long to wait after player stops moving to kick player
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &eDu wurdest wegen langen AFK gekickt [time]
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables item pickup while afk
  DisableItemPickup: false
  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: false
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: true
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false
```

The Players now start fishing, just fishing without any other interactions.
When the AFK time has passted they will went AFK. this is shown in chat. before
they do not chat or move or do anything nothing happens.
So if they fish about an hour maybe then they would count and shown as afk for over 50 minutes.
