### ISSUE TITLE
mutechat reason

### ISSUE THREAD

**Issue by charvyCZ** [Zrips/CMI#3266]
**If I want to mute chat, I would like to enter a reason** 

**Basic explanation as to why this feature is needed and/or useful to have:** 
You can add a reason to mutechat (for example: spam) so players know, why was the chat muted.

**Comment by CloudeLecaw** [comment]
a nice idea, For a first solution you could creat a custom alias that first Mutes the chat for your desired amount of time (command1) and then broadecasts the reason in chat (command2)
The customalias could look like this:
```
  mutec:
    Cmds:
    - fromConsole! cmi mutetechat $1 -s
    - fromConsole! cmi broadcast !The chat has been muted in all Worlds for $1 . Reason:&7 $2-
    Perm: true
```

Result:  
you type /mutec 10min Spamming
The chat will be munted for 10 minutes in all worlds and the broadcast starts for all
"The chat has beed muted in all world for 10 minutes . Reason: Spamming
