### ISSUE TITLE
Repeating commands with sheduler - extansion - Weekly Mo - So

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3283]
Some Commands like on our Server we want to execute each Saturday on 20:00 o'clock

Currently we found no working solution over the time with the CMI sheduler
I know we can set 7 days for the timer - the problem is this timer when "away from time after a while" So better once are weekday, time, and date oriented timers
what works fine so lone is if you setup a direct date also it works fine if you setup a direct time.
What is missing a bit is an option to setup a repeating weekly time.
This would wen dated like_ Each Sunday at 12:00  or  eadh Wendday at 14:00

So would it be possible to add a PefromOn Extantion like the weeksday?

Mo,Tue,Wed,Thu,Fr,Sa,So

```
WeeklyDiomond:
  Enabled: true
  MinPlayers: 3
  MaxPlayers: 10
  FeedBack: false
  Repeat: true
  PerformOn:
    '1':
      WeekDay: Sa
      Hour: 20
  Commands:
  - cmi give [randomPlayer] diamond %rand/1-5%
```

Why not simply start the countdown once at 20 at set it for repeating 7 days?
This is not oriantaed on with the real time its like a timer and the timer is moveing awaay from the time each time a sever restarts or do other things.

So pls it would be nice to add
