### ISSUE TITLE
Skin do not change correctly - MySQL Problem?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3293]
We tested this issues in two cases:

**Server:** Paperspigot (Latest build)
**CMI:** 8.6.24.3
**Database**: MYSQL (for test two we changed to SQLite, but thats not our usual used database)
....---...**Info:** The MYSQL-Database is on the same server as the gameserver.
**Erros in console that have to do with this issue:** None
**Other SkinPlugins**: None

**Test One**: Server with CMI that is using MySQL database.
**Test Two**: Server with CMI that is using SQLite - Database (db file)

--------------------------------------------------------------------------------------------------------
In **Test One** we noticed that changing of the Skin seems not to be accepted by the Server.
If we try to change the skin after the server is up Then you see the changed Skin for about a secound then CMI forces the old skin. We think it takes this Skin from the skincache.yml.

what is helping once here is using the /CMI skin update (playerName) command.
But if the player now chances his skin aggain, the changed skin cant be seen aggain.
Instead of this you see his changed skin for a secound then CMI forces his old skin (we think from the skincache.yml) In this case also a /cmi skin update (playerName) does not help. It just reloads the old skin.
We where looking at the MySQL table and saw that there is an entry  filetable for the skin.
But this just has the entry NULL
So it looks like the skin is just taken from the skincache file and not saved in the MYSQL database.
Is that right?

We also tried reducing SkinUpdateTimer and SkinRequestFrequency to 1 and AutoApply with true and false, but there where no improvment of this issue.

--------------------------------------------------------------------------------------------------------

In **Test Two** we noticed that all is working "correct" it does not mater here how often
the player changes his skin. With the SQLite as database everything work normal
and the skin is updated correctly each time. We dont know if it takes the skin from mohjangs stie
or also from the skincache. But it works correct.

--------------------------------------------------------------------------------------------------------

So the issues only seems to be existis when using a MYSQL - Database even we see no reason why if there is no skinTable in it (or should there be one?)

Our Players began to bleat us because there new skins are not shown on the Server.
For a quickfix we setted up the update skin command as joinevent for the players.
But this only helps once after each restart of the server.
We dont wanne change to the SQLite Database, there need to be a solution :3

So it would be nice to find a fast fix for this issues or maybe some information. May there is a solution that we can fix this by ourself?

--------------------------------------------------------------------------------------------------------

Here are our current settings:
```
Skins:
  # Enable or disable skin management
  Enabled: true
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 1
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with posible requests
  SkinRequestFrequency: 1
```

Picture of MySQL Filetable Skin:
![image](https://user-images.githubusercontent.com/12080017/81574162-bf80d600-93a5-11ea-9675-ffaf95dd0816.png)
