### ISSUE TITLE
glow command does not work?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3295]
Server: Paperspigot (Latest build)
CMI: 8.6.24.3
Database: MYSQL

When you type: /cmi glow Cloude_Lecaw blue true   or any other color then nothing happens
i renember the player had a shining frame around. In Chat you get an info that your glow "color" is set to true. but nothing happens 🥉 

maybe the glow command is broken in one of the last versions?

Looking into the MYSQL-Filetable shows just the value NULL in the register. So is the value not saved correctly?

Finaly we tested it also on our Testserver with a SQLite Database for CMI - but there the Glow command issues seem to be the same.
So it looks like this is not just a database problem, or is it?

**Comment by Zrips** [comment]
if you have DisableTeamManagement set to true in config file, it will not work

**Comment by CloudeLecaw** [comment]
```
Optimizations:
  # Time in seconds we want to give for playes who joins server a immortality state
  # Set this to 0 to disable
  ImmortalityOnJoin: 3
  # Enables or disables maintenance mode
  Maintenance: false
  # Automatically kicks everyone from server when enabling maintenance mode who doesnt have cmi.command.maintenance.bypass permission node
  MaintenanceAutoKick: true
  # When enabled will show bossbar message informing about current maintenance mode being enabled
  MaintenanceBossBar: true
  # When this is set to true features like glow color, player collision, name plates will stop working and CMI will avoid doing anything related to player teams
  # Enable this if you are experiencing issue with other plugins which utilizes players teams for certain features
  DisableTeamManagement: false
  ArmorStands:
    # When set to true, plugin will check if player can manipulate armor stand by sending fake block place event and checking if any plugin would want to prevent this action
    # This can help out to minimize posibility for players to manipulate armor stands when they dont have build permission in area where armorstand is standing
    CheckBlockPlace: false
  AutoDownload:
    # In case you dont have GeoIP.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoIp: true
    # In case you dont have GeoLiteCity.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
```
looks like its on true :3
