### ISSUE TITLE
Dynamic sign colors not working

### ISSUE THREAD

**Issue by sibraxlis** [Zrips/CMI#3298]
My colors are coming out as grey/white.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
'1':
  Loc: world;300.0;39.0;420.0
  Interval: 30
  Range: 12
  Personal: true
  Lines:
  - '&6Player Ranks:'
  - '&6Current &e%cmi_user_rank%'
  - '&6Next: &e%cmi_user_nextranks%'
  - '&6Percent: &e%cmi_user_nextrankpercent%'
'2':
  Loc: world;300.0;40.0;420.0
  Interval: 30
  Range: 12
  Personal: true
  Lines:
  - '&e%cmi_user_name%''s &6Stats:'
  - '&6Played for:'
  - '&e%cmi_user_playtime_dayst%&6D &e%cmi_user_playtime_hours%&6H &e%cmi_user_playtime_minutes%&6M'
  - '&6Walked for: &e%statz_distance_traveled% &6Blocks'
'3':
  Loc: world;300.0;39.0;421.0
  Interval: 30
  Range: 12
  Personal: true
  Lines:
  - '&6RPG Stats:'
  - '&6Class: &e%mmocore_class%'
  - '&6Level: &e%mmocore_level%'
  - '&6Quests Points: &e%quests_player_quest_points%'
```

---

**Cmi Version (using`/cmi version`):** 
8.6.24.2
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
273
