### ISSUE TITLE
MobFarmManager - error with GroupChunks

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3317]
Hello Zrips,

Im writing directly on the CMI-Github bebause i could not find a github for MobFarmManager
I have a big problem with the premium Plugin MobFarmnanager in its latest version 1.5.5.1
On our Server we are using the PaperSpigot Server (#283)

the following error accours.

The Option GroupChunks reacts like it would be set to true even it is on false.

I have set the limit for sheeps for example to 20
I placed 20sheeps in a chuck (messed with F3+G) and in the chunk next to it i tried to place 20 sheeps
Effect: the sheeps get removed even in the chunk next to it....
I placed some sheeps two Chunk away from the first one. and the sheeps stay aggain.
This would mean like the settings explains:
GroupChunks: true
GroupChunksRadius: 1

I pasted you the related part of our config so you can see what we have as current setting. 
If you need other parts or the whole config then pls tell me :)

```
EntitySpawn:
  #
  # Checks Chunk when entity spawns
  Check: true
  # When set to true players without permissions: mfm.build.wither mfm.build.irongolem mfm.build.snowman will be prevented from building appropriate monsters
  PreventMobBuild: false
  # If this set to true, chunks will be grouped up and counted as one. In example with range 2 all 10 chunks will be counted as one and limits will be used as for one chunk
  # This will give wider range of mob cleaning
  GroupChunks: false
  GroupChunksRadius: 1
#
# When set to true entities which are above allowed limit will get removed
# Disabling this will prevent entities from disappearing in front of your eyes, but this can allow player from stacking dozens or even hundreds of mobs in one chunk throw multiple methods
# Disable at your own risk
RemoveExisting: true
```
**Plugins:**
- MobFarmManager: 1.5.5.1
- CMI: 6.24.4 (dont know if that is reladed)
- PEX: 1.23.4
- Vault: 1.7.2
- CMIinjector: 1.0.2

Edit: the Testing showed me that the mob got removed from the 2 "neightbour chunks"...
I also tested it without MFM. There all 80 Sheeps (20 in each chunk stay)
So i can called this problem is related to MFM.

![image](https://user-images.githubusercontent.com/12080017/82046862-075b7200-96b2-11ea-9db0-12b57188fcec.png)
The sheeps in the secound neightbourhood Chunk where deleted about 20 secounds later... after the 20 in the direct neightbourchunk.

For Testting that it is MFM that is doing this:
i unloaded it and palced the 20 sheeps aggain in each chunk.
![image](https://user-images.githubusercontent.com/12080017/82049130-20feb880-96b6-11ea-945b-0379073b01d0.png)

**Comment by Blueeyestar** [comment]
i have the problem on my server too. The users complain to me about mobs / animals that disappear. Please fix. As long as I have deactivated the plugin.

**Comment by Blueeyestar** [comment]
I have the feeling that the topic is not being taken seriously. It is a real problem on my server. So big that I am thinking of removing the plugin as unusable. Because every day I get messages from users that your animals are disappearing. I ask for feedback whether this problem can be fixed or I can classify the plugin as defective to look for a replacement.

**Comment by LogGits** [comment]
@Blueeyestar do you want it to not remove mobs?

**Comment by CloudeLecaw** [comment]
LogGifts? The Problem is a bit bigger
Please look in the pictures in my first thread!
The Problem is that MFM removes mobes even if they have NOT reached the chunk limit (goupchunks: false) just because the mobs 2 chunks next to it get counted too!

**Comment by Zrips** [comment]
@CloudeLecaw 
Could you give me your config file? As it seams to be related to something more specific in your setup then i currently have.

**Comment by Blueeyestar** [comment]
we also have the problem. That's why I'm sending you my config

https://pastebin.com/np4TNn5a

**Comment by Zrips** [comment]
@Blueeyestar 
Which server version are you running? Spigot or paperspigot?

**Comment by Blueeyestar** [comment]
Paper version git-Paper-311 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
@ ZrIps the new Version 1.5.5.2 fixed the issues :)

![Snag_2571173](https://user-images.githubusercontent.com/12080017/82761308-02a56500-9dfa-11ea-9660-7a506d36d656.png)

**Comment by CloudeLecaw** [comment]
Well after testing a bit:

When The Option: is
GroupChunks: true
and
ChunkRadius: 1
then is does not effect the neigbourchunk. like when GroupChunks would be set to false
but If i set the ChunkRadius to 2 then it works fine. and the GroupRadius works.

So still a little Error remaining but the current will work for most i thinkppl i think :)

**Comment by CloudeLecaw** [comment]
```
EntitySpawn:
  #  
  # Checks Chunk when entity spawns
  Check: true
  # When set to true players without permissions: mfm.build.wither mfm.build.irongolem mfm.build.snowman will be prevented from building appropriate monsters
  PreventMobBuild: false
  # If this set to true, chunks will be grouped up and counted as one. In example with range 2 all 10 chunks will be counted as one and limits will be used as for one chunk
  # This will give wider range of mob cleaning
  GroupChunks: true
  GroupChunksRadius: 1
#  
# When set to true entities which are above allowed limit will get removed
# Disabling this will prevent entities from disappearing in front of your eyes, but this can allow player from stacking dozens or even hundreds of mobs in one chunk throw multiple methods
# Disable at your own risk
RemoveExisting: true
AutoClean:
  #  
  # Checks chunks around players for over populated farms
  Use: true
  #  
  # Informs users with mfm.cleaninform permission node how many entities we cleaned up and which ones in particular
  Inform: false
  # How often to check chunks in seconds. Minimal value: 30
  Interval: 15
  # Defines max amount of entities which we will remove from a chunk or chunk group when checking it
  # Set to 0 if you want to disable limit
  MaxRemoved: 0
  # When set to true and value for ChunkRadius is provided, we will group more then one chunk into check
  GroupChunks: true
  # Range around player in chunks to check. 2 means that 9 chunks will be checked, 3 - 25 chunks and so on
  # Max value is 5 to avoid unnecessary load on server
  ChunkRadius: 2
  # Defines range from 1 to 5 in chunks we will check around player when performing autoclean
  # This only applies when you dont have GroupChunks enabled
  ExpandRange: 3
```
