### ISSUE TITLE
CMI Money reseting when paying

### ISSUE THREAD

**Issue by bonjourkemal** [Zrips/CMI#3324]
![s](https://user-images.githubusercontent.com/35656797/82155320-bc418a80-987c-11ea-8dc1-aa4f37793ff6.PNG)

When money is sent to a player, the money of the player receiving the money is reset.
But "cmi money give %player% <int>" this command works, that is, it gives money.

NOTE: First I accidentally installed CMIEnjector with Vault 1.7.3. Then I removed CMIEnjector. How can I fix this bug?

**I have a problem with another issue:**
Do you have a library for information about CMI Vote, which functions the same as SuperbVote plugin? I have researched so far, I have not seen yet.

**Comment by CloudeLecaw** [comment]
You arejustung the CMIInjector 1.02  or the modifed CMIVault Version?

**Comment by bonjourkemal** [comment]
I did exactly what you said. You can see the results below.
```
[03:45:12 INFO]: testerbnjrKemal issued server command: /money
> cmi money give testerbnjrKemal 1000
[03:45:24 INFO]: [MVIP+] »  testerbnjrKemal yeni para miktarı: 0.0
[03:45:29 INFO]: testerbnjrKemal issued server command: /money
```
config
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 0
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: true
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - K-1000
    - M-1000000
    - B-1000000000
    - T-1000000000000
    - Q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: true
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
  Global:
    # Starting amount of money players will have
    StartingAmount: 0.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 0
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 0.01
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: ₴
    # Format used for displaying money
    MoneyFormat: '#####0.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: true
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - K
    - M
    - B
    - T
    - Q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: true
    # Placing of currency symbol
    Placing: '[money][symbol]'
```
