### ISSUE TITLE
Sheduler executing on wrong time

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3332]
We created a sheudler for a lotto drawing

```
WeeklyLottery:
  Enabled: true
  FeedBack: false
  Repeat: true
  PerformOn:
    '1':
      Day: Saturday
      Hour: 20
  Commands:
  - Lottery draw
```

This normaly should draw the lottery on each Saturday at 20:00
Problem: Its also drawing the lottery on Sunday at 20:00

Is there a problem with the Day: ?  Saturday - Sunday .... i know they sound simliar..but they are not...
