### ISSUE TITLE
[Bug] Cannot call a hologram "Info"

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3379]
**Description of issue:**

Was helping a customer debug why they couldn't interact with their "open gui" part of their hologram. I took the file and fresh install and everything worked, except when I used the same name. Making me believe the name 'info' is causing things to fail.

Restarted the server with their holograms.yml file and can reproduce the issue. 

```
Info:
  Loc: world;-22.43;69.62;-1.58
  Interval: -1.0
  LOSInterval: 0.0
  Range: 8
  RangeExtra: 12
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&lThis hologram will tell our &a&lFeatures&f&l!'
```

<img width="374" alt="Screenshot 2020-05-24 at 17 49 59" src="https://user-images.githubusercontent.com/28841349/82758469-fe238100-9de6-11ea-8a22-20296002b29b.png">

clicking the white open gui, results in the below msg:

<img width="251" alt="Screenshot 2020-05-24 at 17 49 44" src="https://user-images.githubusercontent.com/28841349/82758463-f532af80-9de6-11ea-8cba-351acf211b2b.png">

Note that the /holograms still shows them all and you can still click on it to see the lines, but the rest doesn't work well. 

The above fails.
renamed it to information as below
```
Informationtest:
  Loc: world;-22.43;69.62;-1.58
  Interval: -1.0
  LOSInterval: 0.0
  Range: 8
  RangeExtra: 12
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&lThis hologram will tell our &a&lFeatures&f&l!'
```
and this worked. 

```
>cmi version
[17:49:09] [Server thread/INFO]: --------------------------------------------------
[17:49:09] [Server thread/INFO]: CMI plugin version: 8.6.26.3 SqLite
[17:49:09] [Server thread/INFO]: Server: Spigot 1.15.2-R0.1-SNAPSHOT
[17:49:09] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[17:49:09] [Server thread/INFO]: Modules -> 50 enabled 0 disabled:
[17:49:09] [Server thread/INFO]: --------------------------------------------------
>
```
