### ISSUE TITLE
Sleep speedup stops before it turns day

### ISSUE THREAD

**Issue by MADS0LADEN** [Zrips/CMI#3384]
**Description of issue:**
Sleep speedup stops before it turns day
Watch this 22 seconds video:
[https://youtu.be/RZ3NZMOzjfU](https://youtu.be/RZ3NZMOzjfU)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 500
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 50
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 50%
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

---

**Cmi Version (using`/cmi version`):** 
8.6.26.2 but it still does not work with the latest.
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity (Paper)
**Server Version (using `/ver`):** 
Tuinity version git-Tuinity-"121cca1" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
