### ISSUE TITLE
custom recipes - modified materials turn back to vanilla default items

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3395]
i also posted this Problem once in the spigot discussion but may noone was interested in it^^

i saw that for current custom recipes ist not possible to use items that have names or Lores or other enchatments or NTB datas as recipes materials.

normaly i wanted a shape of Emeraldnblocks + a Silktouch 1 pickaxe  to craft the pickaxe with silktouch 2. The result ist that they can craft the the silktouch 2 picaxe with the Emeradblocks and a normal pickaxe.… when Looking aggain at the recipe i saw that the pickaxe with enchant in it got replaced with the Default versions of the item. I also tried it with renamed items and lore items as materials.
So the Problem more seems to be the way how the materials are saved 🥉 

**Error with a shaped recipe**
before (when creating it)
![image](https://user-images.githubusercontent.com/12080017/39251862-96217bd2-48a4-11e8-9135-28158b8bc887.png)

after saving (open it aggain)
![image](https://user-images.githubusercontent.com/12080017/39251885-a4028ef8-48a4-11e8-9129-275bf8832d96.png)
+
+
+

**Here also with a furnace recipe:**
![Snag_8a01d29](https://user-images.githubusercontent.com/12080017/82955866-ea774680-9faf-11ea-9663-869e12f316d6.png)

![Snag_8a03b5f](https://user-images.githubusercontent.com/12080017/82955878-eea36400-9faf-11ea-8b0f-533f06681229.png)
The Testitem in furnace should become a earthblock called Endprodukt

Now close the GUI and open the recipeeditor and the recipe of the Endprodukt
![Snag_8a0f8d3](https://user-images.githubusercontent.com/12080017/82955927-0bd83280-9fb0-11ea-8e6d-ffdec30a7090.png)
+
+
**Result**... the Testitem turned into the original Vanilla Version of it (all infos of it got lost)
![Snag_8a0e328](https://user-images.githubusercontent.com/12080017/82955922-0844ab80-9fb0-11ea-85d9-ae917bb202f0.png)
+
+

**This happens to all kind of custom recipes**
+
+
```
  '11':
    Type: Furnace
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: DIRT
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §rEndprodukt
    Recipe:
      1:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: BLACK_DYE
    Cook: 60
    Exp: 0.0
```
looks like ItemMetas of the materials that a needed are not saved in the recipefile.
+
**_CMI-Version: CMI_8.6.26.5
PaperSpigot - 1.25.2 Build 318_**
