### ISSUE TITLE
Swearing

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#3397]
The anti Swearing feature is pretty terrible, i made a list of about 30 words to block and replace with **** when writing out a sentence with 10 of the words in it, it missed all but 2 of them... so a 20% blocking rate, and sending the same message a second time has the same effect only blocks 2 of the words in the message.

I can provide this portion of the Config file per-request as it contains explicit language.

**Cmi Version (using`/cmi version`):** 
8.6.26.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
313

**Comment by CloudeLecaw** [comment]
maybe you used wrong regex? maybe no good setup?
you should post your config beofre :§

**Comment by ablac** [comment]
@CloudeLecaw https://pastebin.com/pc8LkUYN

**Comment by CloudeLecaw** [comment]
You made it a little bit wrong this is to much for 1 filter make one for each and other string just for variants

```
      swearing1:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bass\b|\basshole
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing2:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bshit
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing3:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bbitch
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing4:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bdamn
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing5:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bcunt
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing6:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bchoad
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing7:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bwanker
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing8:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \btwat
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing9:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bfuck
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
      swearing10:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \bcrap
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
```
![image](https://user-images.githubusercontent.com/12080017/82996384-2b4d7a80-a005-11ea-92ff-b2e29440fa72.png)
100% replaced

**Comment by ablac** [comment]
How would i make it prevent all possible wordings of it cause for example itll stop crap but not Crap or CrAp

**Comment by CloudeLecaw** [comment]
You need an other RegEx for this :)

**Comment by ablac** [comment]
so theres no way to do something like s?([a-zA-Z]{2,4})\b

**Comment by CloudeLecaw** [comment]
[a-zA-Z] for each letter

**Comment by ablac** [comment]
:) thank you :D

**Comment by CloudeLecaw** [comment]
![image](https://user-images.githubusercontent.com/12080017/82998681-4ff72180-a008-11ea-8a2f-6d3f5b744a57.png)

```
      swearing10:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b[cC]+[rR]+[aA]+[pP]
        ReplaceWith: '****'
        BlockType: other
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eTest Swear
```
