### ISSUE TITLE
More Permissions for Chat Command

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3406]
This request is made as a result of a question of a player for creating private Chatrooms

#3400 

The result was that there are some permissions missing for the Chat command
without these player may feel annoied if everyone joins their channels or invites other players
Also we see no reason why everyplayer should see the whole channellist.
So a few permissions may be needed:

**_cmi.command.chat_** - main command
**_cmi.command.chat.create_** - allow creating channel
**_cmi.command.chat.list_** - allows list command
**_cmi.command.chat.invite.own_** - allows inviting other players to own created chatroom
**_cmi.command.chat.invite.other_** - allows inviting other players to chatroom they have not created

**Comment by CloudeLecaw** [comment]
what the...
have you looked what your trying to do?
```
`5mWarning:
  Enabled: true
  PerformOn:
    '1':
      Hour: 23
      Minute: 55
  Commands:
  - title! &6Server Restart in 5 Minutes!
1mWarning:
  Enabled: true
  PerformOn:
    '1':
      Hour: 23
      Minute: 59
  Commands:
  - title! &6Server Restart in 60 sec!
30sWarningKick:
  Enabled: true
  PerformOn:
    '1':
      Hour: 23
      Minute: 59
      Second: 30
  Commands:
  - actionbar! &eServer will stop in &630 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &625 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &620 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &615 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &610 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &65 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &64 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &63 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &62 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &61 &esec!
  - delay! 1
  - kickall! &eServer will be back online soon!
  - delay! 1
  - asconsole! restart
ForceServerRestart:
  Enabled: false
  PerformOn:
    '1':
      Hour: 23
      Minute: 59
      Second: 30
  Commands:
  - actionbar! &eServer will stop in &65 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &64 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &63 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &62 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &61 &esec!
  - delay! 1
  - asconsole! send all hub
  - delay! 1
  - asconsole! restart`
```

if this all is just for one restart then why you preform so much action in one time with the same result that the console will restart?
