### ISSUE TITLE
CMI Scheduler Day Preform wrong on Weekends

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3407]
```
PayOff:
  Enabled: true
  Repeat: true
  PerformOn:
    1:
      Day: Saturday
      Hour: 20    
  Commands:
  - cmi money pay [randomPlayer] %rand/100-500%
```

We noticed:
The command is executed **each saturday** and **each sunday** at 20:00
But look in the code. it should be just preformd on Saturday at 20:00 so just  once a week.

we see no reason for this..May be a wrong entry for Sunday (like aggain Saturday?)
