### ISSUE TITLE
cmi saveditems - do notremove items from SavedItems.yml

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#3422]
CMI8.6.26.6.jar

After removing item from GUI (middle mouse key) or from command "/cmi saveditems remove <name>" the item is removed, but it is not removed from SavedItems.yml.
After server restarts the item is again in "saveditems" list gui.

It will be removed from file only after saving another item

**Comment by CloudeLecaw** [comment]
hoding a head:
..../cmi saveditems save Test
......content of saveditems.yml
```
Test:
  Item:
    v: 2230
    type: PLAYER_HEAD
    amount: 63
    meta:
      ==: ItemMeta
      meta-type: SKULL
      display-name: §r§6Benzin
      lore:
      - §7§oWird beim verbrennen
      - §7§ovon Rohöl gewonnen.
      internal: H4sIAAAAAAAAAFWSyY6jWBBFqVK3lJWqz+idlTKTwSxqgcFgMIONGd+mBRjM9Jjnr6kP6I9sKlWL7tWT4t64cSL03hHkHfn+yIeiuLVVnBbRG/KH5sMI+c4V1fCM/lai0J/ekfdNrqO2T6PuG/LWR3M/tFH3jiDIlzfk2yN9lf6vytd/hL4lxtsuYi/56uW1LdYkZR5Qqq/l8dyY8oO0dI3IfdcgBcKTT1CQhmmnt0LCkDlvy8ZcF2Pn4kQ4Z6g2GIbaAC0+lxfGWNw1VBpnQSuqKCMtO+PB8eDkXHeoZ1Zfx4V1rPLEQCGp9BkV51u+04opY5KD0nNlVXkwvTLdsmuSMqaVF7TMJG2JKMpVlH0U7Q3jlLJ5QpEVWIIcmqqmNGLAHJ7BSyobVJO4BYPTudWCX/XwOGETLbAX05j3NKu4O5RvnaubS1mkY2v9Av7i7AJKL3MqqW7TYzewqrWo1X6E48xt4Potv9ahLsQ0T1Yr3tV9fb6r8tJdzzhpW1ch3pGJN5yr1164UwUvLJao+T1MpxeldJqr2jtaeqzTwJj7xTeCMJWDO7QjRdCvEyynpAnus9Fn0YJrz2KdxvKcnSWvkXYYrjMFpax0sxd6Oq/vZEnF7p0hjfTMHNusIV1HPdZCKbpF6hpiIS10pS+tblDTuASqZJ+43CbZ090y5svhAhO8tY54OuXH6axwd48O1J4/orVgKXSfjsdpGB/KYZfChqRDFs9K+S6NvRJXRc4VY9b1wFqaxCMrYMpweN2sZD5TzCqlN8WOsFttCuaF5k5LoJ/zmI40inJyfd8BIIyORJA+OMkRfOBPPW9PSpdeKbLtrqfeApA/EKPNmncxW46cOT5XVgIQPPzUSurpxxvyp+0XQ/TlZzRVL4mTUd/BipAwksBlU4mvXqppHVReXVTeWrYPN2mP6SpxbBpe5BHAogNWkUspS229UM2MHGT55i8yDUooyNRFN1XSM41MN4VEzUCurgLUOKnjUvYlldtGOKgD0da9be7vHD4QGQyIdmyKdua5Yaqwn2yr7zwHzzWwENoP4AqY78oF4KSXnp7QsLSL3z4UuAn63LRw+dToz1kbs4X2spn+r/bLv+VNn7tKcOu7sJSyMP/JOPS+cyg8Qk5AeR8CaKMKYRTR5ReHNaoZS6jQIzU+SXTeW3THOgAe5NrqEZooQ8C/MJDZiSreUQ96qMqHs+dsN+ANqJvhrPLPFDgg9cztZnxSaKYBvVS6frJd0O09MVyJ/kCQN+Sr9ET+inHyGTMM+sGEVPBBxgT+wRBH/4MMGczHqSeBxSSC/AuTirIB1wQAAA==
      skull-owner: Cloude_Lecaw

```

/cmi saveditems remove Test
....item got removed from inventory


Issues: Error
..... remove Items removes items from inventory instead of database.
