### ISSUE TITLE
Error with tab players

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3426]
**Description of issue:**
I have a problem with the tab, players name have error sometimes (duplicate name of other player)
https://i.ibb.co/L6F0cMs/tab-bug.png
In the balance line "Votre argent" I get sometimes the money of the other connected player

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 1
    OnJoin: false
    OnLeave: false
    afkStateChange: false
    OnWorldChange: false
    OnDeath: false
    OnTeleport: false
    OnNickChange: false
  # When set to false we will not add header text to tablist
  addTabListHeader: true
  # When set to false we will not add footer text to tablist
  addTabListFooter: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: ' %javascript_complete_name%'
    Header:
      '1':
      - '&f&m*---------------*&r %javascript_server_name% &f&m*---------------*'
      - '&aFreebuild &7- &cCombat &7- &eEvent &7- &9Quêtes'
      - '&bJoueurs connectés: &e%premiumvanish_playercount%/%server_max_players%'
      - '&f&m*------------------------------------*'
    Footer:
      '1':
      - '&f&m*------------------------------------*'
      - '&bDate et heure: &e%server_time_dd/MM/yyyy HH:mm:ss%'
      - '&bVotre argent: %javascript_balance%'
      - '&f&m*---------------*&r %javascript_server_name% &f&m*---------------*'
  useGeneralName: false
  # When this set to true, in case you dint defined PlayerName, Header or Footer in GroupFormat, then default one from GeneralFormat will be used
  useGeneralHeader: false
  useGeneralFooter: false
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  GroupFormat:
    '1':
      PlayerName: '&2{&r[playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'

```
---

**Cmi Version (using`/cmi version`):** 
8.6.26.7

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.15.2
