### ISSUE TITLE
CMI not save data to database MySQL

### ISSUE THREAD

**Issue by Galajus** [Zrips/CMI#3470]
**Description of issue:**
CMI after migration from SQLite to MySQL not save data before restart server and we have a lost everything from todays players data.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Database coonfig:
```

storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: MyUsernameDatabase
  password: MyPasswordDataBase
  hostname: MyIPHostDataBase:MyPortDataBase
  database: minecraft <- is special create database
  tablePrefix: CMI_ <- succesfull create 4 table with prefix
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false #localhost without SSL
  verifyServerCertificate: false #localhost without SSL
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: true #test after error... - before value is false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: true #test after error... - before value is false

```

**Cmi Version (using`/cmi version`):** 
8.6.26.9
**Server Type (Spigot/Paperspigot/etc):** 
git-Paper-332 
**Server Version (using `/ver`):** 
(MC: 1.15.2)
