### ISSUE TITLE
Add a trash can GUI

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3472]
**Description of feature/improvement request:**
Hi!

Is it possible to add a trashcan gui?

---
### Detailed explanation of what it should do, when and in what situation: ###
I just need a command like /trash to open an empty gui and each items I put on this GUI will be erased (or just close the GUI and after redo /trash there is no items because it will be a new instance of the inventory)
The title of this GUI can be edited in the config and the command will have a permission to use the trash.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Player don't need to drop items on ground and this is faster.

**Comment by mrfloris** [comment]
I got you fam.

<img width="426" alt="Screenshot 2020-06-07 at 18 34 05" src="https://user-images.githubusercontent.com/28841349/83974435-96445e80-a8ed-11ea-8fbf-7114fcb1773a.png">
<img width="1392" alt="Screenshot 2020-06-07 at 18 34 31" src="https://user-images.githubusercontent.com/28841349/83974437-97758b80-a8ed-11ea-8831-e9136a1e146a.png">
<img width="1392" alt="Screenshot 2020-06-07 at 18 34 25" src="https://user-images.githubusercontent.com/28841349/83974441-99d7e580-a8ed-11ea-8094-3349f34425d5.png">
<img width="534" alt="Screenshot 2020-06-07 at 18 34 10" src="https://user-images.githubusercontent.com/28841349/83974442-9a707c00-a8ed-11ea-8333-9ecadb073f94.png">

Already possible with CMI :)

```
/cmi dispose
```
This will open the GUI.

You can use `/cmi aliaseditor` to create a new alias-command called `trash`, and then add a command to this like: `cmi dispose`

To make a sign like `[trash]` that will make it open the GUI interface on right click, use interactive commands feature.

first in `config.yml` from cmi, set it like this:
```
InteractiveCommands:
  # Regex used in recognizing public interactive commands used in signs
  # Default format is [ic:[icName]] in example [ic:trash]
  # If you want clean format use regex like: (\[([a-zA-Z0-9]+)\])
  SignRegex: (\[([a-zA-Z0-9]+)\])
```

And then in-game use /cmi ic, to create a new `[trash]` sign, that's public, using these commands (this is how it ends up in the YAML file `interactiveocmmands.yml`
```
trash:
  Locations:
  - world;12752.0;32.0;12008.0
  - general;10275.0;13.0;-751.0
  - wild;12192.0;70.0;11800.0
  Commands:
  - click:rightclick! asConsole! cmi dispose [playerName]
  SignLines:
  - '&0&l TRASH BIN'
  - '&7~~~~~~~~~~~~'
  - '&9&lTry with /sell'
  - ' '
  Public: true
```

Note that you can have your own lines of text, and the world locations are of course different for your world as you place a sign.

Now when someone places a sign with [trash] on it, it will become an interactive sign, running the dispose command, and they can also type: /trash, to open it.
