### ISSUE TITLE
Wither Skeletons are not dropping Default Minecraft Heads

### ISSUE THREAD

**Issue by VimaMT** [Zrips/CMI#3473]
**Description of issue or feature request: Unable to get default Minecraft heads as drops from Wither Skeletons**

Regardless of what I try, I keep getting the default Player Head which looks like Steve.

I have focused upon the customHeads.yml file in trying to make this work.  I have:

  1) Tried removing the entry, altogether, for wither_skeleton. The plugin restored it.
  2) Tried setting DropChance to 0.0 and individual head chances to 0. I still get Steve's head.
  3) Tried deleting all but one head line, then set the head name to garbage. I still get Steve.
  4) Tried setting criteria for getting the head to "c -powered" ... there's no way a wither skeleton can be powered.  I still get Steve.

**LATEST CONFIG SECTION:**
```
  wither_skeleton:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:c -powered:Nzk1M2I2YzY4NDQ4ZTdlNmI2YmY4ZmIyNzNkNzIwM2FjZDhlMWJlMTllODE0ODFlYWQ1MWY0NWRlNTlhOCJ9fX0=
```

---

**Cmi Version (using`/cmi version`): 8.6.26.9 SqLite** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): Paper(334) 1.15.2-R0.1-SNAPSHOT**

**Comment by CloudeLecaw** [comment]
there is just an error why your not getting the right right maybe currpt meta data? this would result in a steave head

**Comment by CloudeLecaw** [comment]
- 100:c -powered:    this is a not allowed thing c -powered there is no option like that

here u have the default aggain

```
  wither_skeleton:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:Default:Nzk1M2I2YzY4NDQ4ZTdlNmI2YmY4ZmIyNzNkNzIwM2FjZDhlMWJlMTllODE0ODFlYWQ1MWY0NWRlNTlhOCJ9fX0=
    - 100:Default:ZjVlYzk2NDY0NWE4ZWZhYzc2YmUyZjE2MGQ3Yzk5NTYzNjJmMzJiNjUxNzM5MGM1OWMzMDg1MDM0ZjA1MGNmZiJ9fX0=
    - 100:Default:NDk2YmM4ZWJkNGUxM2Y0OTZkOGQ3NGM1NjVkZDU2ZTk5YTRhZjJlMmVhN2EyN2E5NmMxYWJkMjg0MTg0YiJ9fX0=
```
