### ISSUE TITLE
Schedule give diamonds on delay

### ISSUE THREAD

**Issue by daoshii** [Zrips/CMI#3483]
Spams console infinitely every 2 seconds if there is not enough players

[10:45:56 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:45:58 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:00 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:02 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:04 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:06 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:08 INFO]: Skipping schedule GiveDiamonds due to player amount
[10:46:10 INFO]: Skipping schedule GiveDiamonds due to player amount

```
GiveDiamonds:
  Enabled: true
  MinPlayers: 2
  FeedBack: true
  Repeat: true
  Delay: 3600
  Commands:
  - cmi give [randomPlayer] diamond %rand/1-5%
  - msg! [randomPlayer] &eYou were randomly selected to receive diamonds!
```

CMI: 8.6.26.10 SqLite
Server: Paper(334) 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b CMI Chat: True
Modules -> 51 enabled 0 disabled:
