### ISSUE TITLE
Double cooldown messages

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3486]
**Description of issue:**
Hi, when I use for ex. /spawn, where I set cooldown to 10 seconds, there are two messages. https://imgur.com/a/hghRHvL

---
---

**Cmi Version (using`/cmi version`):**  CMI: 8.6.26.11 BungeeCord MySQL-> 8.6.26.9

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  This server is running Paper version git-Paper-342 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Cant reproduce. I need your cooldown section from config file.

**Comment by Volgeop** [comment]
WTF Custom aliases are also executed twice... https://imgur.com/a/SUz1wjT
```
  priroda:
    Cmds:
    - rt [playerName] world
    - asConsole! msg [playerName] Byl jsi teleportován do přírody :) Začni zde svou cestu!
  novacek:
    Cmds:
    - asConsole! featherboard show [playerName] novacek -s
    - asConsole! msg [playerName] Byla ti zobrazena nápověda pro nováčka :) Až ji
      nebudeš chtít, použij /novacekoff či se znovu připoj.
  novacekoff:
    Cmds:
    - asConsole! featherboard show [playerName] default -s
    - asConsole! msg [playerName] Byla ti skryta nápověda pro nováčka :) Kdybys ji
      chtěl znovu, použij /novacek.
  tabulka:
    Cmds:
    - asConsole! featherboard toggle [playerName] -s
    - asConsole! msg [playerName] Byla ti přepnuta tabulka. Pro opětovné přepnutí
      použij opět &c/tabulka&f.

```

All of them... why please? I tried default configuration... remove everything except these aliases, so wtf.

**Comment by Volgeop** [comment]
For ex. players can't toggle scoreboard because commands are executed twice.... https://imgur.com/a/XHZp1rv

**Comment by mrfloris** [comment]
Did you /reload the server, or use /plugman to load in or reload commands?
This still happens after /stop and then starting up the server?

The latest version of CMI is currently `8.6.27.3`, can you upgrade and let us know if the problem went away or still exists in that version? And just in case there's an issue with your build of paper, might be nice to update to 354 or newer https://papermc.io/downloads

**Comment by Volgeop** [comment]
I made so many servers /restart between it and it's still broken. No, I don't use reload and plugman plugin, just restart or /cmi reload.

No I made it in files directly.

And yeah, I updated to 8.6.27.3 and the newest paper and issue still exists.

**Comment by mrfloris** [comment]
Thank you for the additional information and testing if the upgrade would fix it. Good to hear. This helps (well, me at least).

**Comment by Volgeop** [comment]
I discovered the problem! But it needs solution by Zrips or dropping this plugin probably :/

https://www.spigotmc.org/resources/hideplugins-project-1-13-1-15-x-fully-configurable.25317/

This plugin causes issue... when the option
```
# Do you want to protect your commands?
lockedCommands: true
```
is enabled and there's command /tabulka or /priroda added in enabled one.... it makes them doubled. But wtf, why only in CMI? Shouldn't you @Zrips change a little bit behavior of custom aliases and cooldowns to don't broke this? Other commands from other plugins work great with this plugin and other commands from CMI too.

Btw I could solve it maybe by don't adding /tabulka etc. to the enabled command list, but it's still broken for people who are bypassing hideplugins locked commands.... So I could solve it for players, but for my team neither.

Maybe if you could try improve somehow behavior of custom aliases and cooldowns to support this plugin? I didn't find any good alternative to it.... Almost all of them are abandoded, this one is probably too now.... but he's still the best one which I can choose from.

**Comment by Volgeop** [comment]
And as I discovered... it only "multiply" commands which are executed by console, but why?
```
  priroda:
    Cmds:
    - rt [playerName] world
    - asConsole! msg [playerName] Byl jsi teleportován do přírody :) Začni zde svou
      cestu!
  novacek:
    Cmds:
    - asConsole! featherboard show [playerName] novacek -s
    - asConsole! msg [playerName] Byla ti zobrazena nápověda pro nováčka :) Až ji
      nebudeš chtít, použij /novacekoff či se znovu připoj.
  novacekoff:
    Cmds:
    - asConsole! featherboard show [playerName] default -s
    - asConsole! msg [playerName] Byla ti skryta nápověda pro nováčka :) Kdybys ji
      chtěl znovu, použij /novacek.
  tabulka:
    Cmds:
    - asConsole! featherboard toggle [playerName] -s
    - asConsole! msg [playerName] Byla ti přepnuta tabulka. Pro opětovné přepnutí
      použij opět &c/tabulka&f.
```

These are executed twice when they're added to enabled commands list....

But these are executed still once:
 ```
 creative:
    Cmds:
    - gamemode creative
  spectator:
    Cmds:
    - gamemode spectator
  pravidla:
    Cmds:
    - cmi ctext rules
  tresty:
    Cmds:
    - cmi ctext tresty
```
