### ISSUE TITLE
/cmi kitusagereset <kitname> <playername> not working

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3489]
**Description of issue:**
Hello, I've been trying to reset my usage for a certain kit using cmi kitusagereset, but it doesn't show up. It doesn't show any feedback message, and the usage is not even reset. 
Steps to reproduce:
1. Create a kit
2. Set a max usage
3. Check kit preview as a reference for usages
4. Get a few kit.
5. Execute cmi kitusagereset. It doesn't show any feedback on success, but it shows if you write the command wrongly. No, there are no errors on console.
6. Recheck kit preview, and it doesn't reset nor change anything.

A workaround would be deleting the kit and making it again, but it would be nice if this gets fixed.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RTPStick:
  CommandName: RTPStick
  Enabled: true
  DropOnGround: true
  ShowDespiteWeight: false
  Delay: -1
  MaxUsages: 200
  Items:
    '1':
      v: 2230
      type: STICK
      amount: 2
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/32483348/84420330-14816780-ac44-11ea-9fb3-49577389c396.png)
