### ISSUE TITLE
Command cooldown bug

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#35]
It appears that /time and /weather cooldowns don't work for me:
```yaml
Cooldowns:
  # You can enable any command cooldown to prevent intence usage of it
  # Heal:180 means that player can use /heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.command.[comandName].cooldownbypass permission node
  Enabled: true
  List:
  - Heal: 1800
  - Feed: 1800
  - Time: 1800
  - Weather: 1800
```

**Comment by LogGits** [comment]
This is resolved. For anyone who is having the same issue make sure you are using cmi at the beginning of the command for a cmi command as it doesn't work with aliases:
```yaml
Cooldowns:
  # You can enable any command cooldown to prevent intence usage of it
  # Heal:180 means that player can use /heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.command.[comandName].cooldownbypass permission node
  Enabled: true
  List:
  - cmi heal: 1800
  - cmi feed: 1800
  - cmi time: 1800
  - cmi weather: 1800
```
This is the working version ^
