### ISSUE TITLE
Problem with commandwarmup when command is performed by another plugin

### ISSUE THREAD

**Issue by destro174** [Zrips/CMI#3519]
**Description of issue:**
Command warmup doesn't active when commands are issued by plugins using
```
player.performCommand(Texts.getRaw("spawn-command"));
```
Texts.getRaw("spawn-command") returns cmi spawn.

When players do /cmi spawn this warmup does get actived.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi back:3:false
  - cmi home :3:false
  - cmi spawn:3:false
  - cmi dback:3:false
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.6.26.9 BungeeCord  MySQL-> 8.6.27.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-334 (MC: 1.15.2)
