### ISSUE TITLE
ipBlock / regex problem

### ISSUE THREAD

**Issue by THGamer2002** [Zrips/CMI#3537]
######################
######################
When someone writes for example: hello , i m andreas and i m from romania...it is put as if it is an advertisement. The problem comes frome the comma.
Note: i don t want to remove the "," from regex bcs after that it will be possible to advertise.

[CMI] Player (_THGamer2OO2_) triggered (ipBlock) chat filter with: 1,1,1,1,1
[♂] [lvl: 47] [✰] _THGamer2OO2_ » 1,1,1,1,1
[CMI] Player (_THGamer2OO2_) triggered (ipBlock) chat filter with: hello, i m andreas from romania.
[♂] [lvl: 47] [✰] _THGamer2OO2_ » hello, i m andreas from romania.

######################
######################
```
  ChatFilter:
    Enabled: true
    Deny:
      ipBlock:
        # If not set to true, this filter will not be used
        Enabled: true
        # Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
        Group: Reclama
        # When set to true, each time player triggers filter, console will receive information about who triggered it, which filter and with what message
        InformConsole: true
        # Regex expresion to filter by. How to use regex https://regexone.com/
        **Regex:
        - '[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|;|:|,|_|\/)\s?([a-zA-Z]{2}|biz|cat|com|gov|info|ro|net|org|)\b'
        - \b[0-9]{1,3}(\.|dot|\(dot\)|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}**(\.|dot|\(dot\)|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
        # With what we need to replace word, if not defined found expresion will not be changed
        ReplaceWith: ''
        # possible: none, others, all
        # Where 'none' means everyone will receive this message
        # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
        # 'all' means that no one will receive sent message
        BlockType: none
        # Players with cmi.chatfilter.inform permisison will receive defined message when rule is broken
        msgToStaff: ''
        # List of commands to perform when rule is broken. Use [senderName] to include message sender name. Supports global variales same as locale file
        Commands: []

```
######################
######################

Cmi Version: 8.6.27.3

Server Type: TacoSpigot

Server Version: 1.8.8-R0.2-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Belive me regex sind sometimes is a bitch ;) often its just using the "wrong" way for regey. I had also a lot of problems here at frist with this. Pls mark your configpart as Code. Else it become a bit "unreadable". If you want i can poste you the regex that solved this problem for us this later afternoon. If you want you can try it out and tell if this is good for you or not. But to be honey the problem itself is not the regex. This works. The problem is more the right setup of this. Regex looks like a whole own programming language, and i was happy too that the stuff here helped me with setting up it correct.

**Comment by THGamer2002** [comment]
I would really appreciate it if you could give me the correct configuration for this problem :D or if you have an even better one it is welcome.

**Comment by THGamer2002** [comment]
an answer here please ^-^ @CloudeLecaw

**Comment by CloudeLecaw** [comment]
sorry for letting u wait
```
  ChatFilter:
    Enabled: true
    Deny:
      ipBlock:
        # If not set to true, this filter will not be used
        Enabled: true
        # Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
        Group: Advertising
        # When set to true, each time player triggers filter, console will receive information about who triggered it, which filter and with what message
        InformConsole: false
        # Regex expresion to filter by. How to use regex https://regexone.com/
        Regex:
        - \b(?i)(\d+)(.|,)(\d+)(.|,)(\d+)(.|,)(\d+):(\d+)
        - \b(?i)(\d+)(.|,)(\d+)(.|,)(\d+)(.|,)(\d+)
        - \b(?i)(\D+)(.|,)(\D+)(.|,)(\D+):(\d+)
        - \b(?i)(\D+)(.|,)(\D+)(.|,)(\D+)
        # With what we need to replace word, if not defined found expresion will not be changed
        ReplaceWith: Test
        # possible: none, others, all
        # Where 'none' means everyone will receive this message
        # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
        # 'all' means that no one will receive sent message
        BlockType: none
        # Players with cmi.chatfilter.inform permisison will receive defined message when rule is broken
        msgToStaff: '&4!&6[playerName] &4advertising with: &r[message]'
        # List of commands to perform when rule is broken. Use [senderName] to include message sender name. Supports global variales same as locale file
        Commands: []
```

Waht this IP blocker is Blocking
Nummerc Ips: 543.34.346.345  (also with comma)
NumbericIps with ports: 543.34.346.345:25565  (also with comma)
Servernameips like  mc.stolenserver.net
ServernameIps with port: mc.stolenserver.net:24543

Note this is not a filter Redex for Homepages and Linsk with htttps etc.. there u can use other regex

**Comment by THGamer2002** [comment]
ty for your help but we have a problem :) players can add with comma on domains 
example: play,commnunity,ro

**Comment by THGamer2002** [comment]
UPDATE:
**For those who want to block most ads use:**
```
ChatFilter:
    Enabled: true
    Deny:
      ipBlock:
        # If not set to true, this filter will not be used
        Enabled: true
        # Defines filter group and defines required permission node to bypass this filter: cmi.chatfilter.bypass.[groupName]
        Group: Reclama
        # When set to true, each time player triggers filter, console will receive information about who triggered it, which filter and with what message
        InformConsole: true
        # Regex expresion to filter by. How to use regex https://regexone.com/
        Regex:
        - \b(?i)(\d+)(.|,)(\d+)(.|,)(\d+)(.|,)(\d+):(\d+)
        - \b(?i)(\d+)(.|,)(\d+)(.|,)(\d+)(.|,)(\d+)
        - \b(.)(?=\1\1+)
        - \b(..)(?=\1\1+)
        - \b(...)(?=\1\1+)
        - \b((http)*(\w|\W|\d|_)*(https)*(\w|\W|\d|_)*(www)*(\w|\W|\d|_)*[a-zA-Z0-9\.\-\*_\^\+\~\`\=\,\&*]{3,}(\W|\d|_|dot|\(dot\))+(com\b|org\b|net\b|ro\b|pro\b|ca\b|biz\b|mobi\b|xxx\b|tv\b|tk\b))
        # With what we need to replace word, if not defined found expresion will not be changed
        ReplaceWith: ''
        # possible: none, others, all
        # Where 'none' means everyone will receive this message
        # 'others' means that sender will get message but not other players, this is usefull to prevent advertising and silently block it
        # 'all' means that no one will receive sent message
        BlockType: all
        # Players with cmi.chatfilter.inform permisison will receive defined message when rule is broken
        msgToStaff: '&4&l[!] &c[playerName] &fa incercat sa faca reclama.'
        # List of commands to perform when rule is broken. Use [senderName] to include message sender name. Supports global variales same as locale file
        Commands: []
```


**If you want to block the name of a community or some swearing use:**
```
      Blaze1:
        Enabled: true
        Group: Reclama
        InformConsole: true
        Regex:
        - \b(?i)(m+(\W|_?)+u+(\W|_?)+l+(\W|_?)+t+(\W|_?)+y+(\W|_?)+p+(\W|_?)+l+(\W|_?)+a+(\W|_?)+y+(\W|_?))
        ReplaceWith: '**********'
        BlockType: all
        msgToStaff: '&4&l[!] &c[playerName] &fa incercat sa faca reclama.'
        Commands: []
```
