### ISSUE TITLE
MySQL critical error 

### ISSUE THREAD

**Issue by TopCZE** [Zrips/CMI#356]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## [CMI] Enabling CMI v7.7.4.0
[CMI] PEX permission plugin will be used
[CMI] Loaded (37) regular alias into memory. Took 11ms
[CMI] Loaded (1) custom text's into memory. Took 2ms
[CMI] Unable to connect to the database: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
Error occurred while enabling CMI v7.7.4.0 (Is it up to date?)
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.DataBase.DBMySQL.isTable(DBMySQL.java:145) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Modules.DataBase.DBDAO.createDefaultTable(DBDAO.java:1384) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Modules.DataBase.DBDAO.setUp(DBDAO.java:467) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Modules.DataBase.DBMySQL.initialize(DBMySQL.java:25) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:125) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Modules.DataBase.DBManager.start(DBManager.java:74) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Config.load(Config.java:561) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.Config.load(Config.java:543) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1282) ~[CMI7.7.4.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [minecraft_server.jar:git-Spigot-2086bb0-d0a3620]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112] ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
#####################################
## # Language file you want to use
Language: CZ
storage:
  method: MySQL
mysql:
  username: 260759_mysql_db
  password: 
  hostname: casa17.fakaheda.eu:3306
  database: 260759_mysql_db
  tablePrefix: CMI_
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
AutoSaveInterval: 15
Economy:
  Enabled: true
  Confirmation: false
  MaxChequeValue: 1.0E8
  BalTop:
    Exclude:
    - Notch
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
  Global:
    StartingAmount: 100.0
    MinimalAmount: 0.0
    MaximumAmount: 1.0E8
    CurrencySymbol: €
FileSave:
  Async: false
Optimizations:
  Maintenance: false
  AutoDownload:
    GeoIp: true
    GeoLiteCity: true
  ElevatorIndicator: '[CMIElevator]'
  MoneyFormat: '###,###.###'
  SellLog: true
  PreventDifferentCapitalizationNames: false
  PartialPlayerName: false
  DiscordSRVSupport: true
  CommandSorting: true
  RemoveLabel: false
  PermisionOnError: true
  PermisionInConsole: true
  Teleport:
    SafeLocationDownThenUp: false
    VehicleWorkArround: false
    SwitchPlaces: true
    CurrentLoc: true
    JumpDefault: 50
    TpaTime: 60
    TpaWarmup: 3
    TpaMove: false
    TpaBlock: 120
    TpBypass: 15
    BlackListedItems:
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    BackMinDistance: 5
  IP:
    delay: 30
  MaxHp: 200
  PlayTimeFromStats: false
  CMIPlayTimeTracking: true
  OnDurabilityLoss:
    Use: true
    Percentage: 10
  OnLimitedItemUse:
    Inform: true
  DisableWorldChunkCheckInfo: false
  PreventEntityBoatEnter:
    Monsters: false
    Animals: false
  PreventBedExplosion:
    Nether: false
    TheEnd: false
  PreventPlayersOnNetherRoof: false
  PreventIronGolem:
    Roses: false
  PreventHook: false
  Multicraft:
    DisableList: false
PlaytimeRewards:
  Enabled: true
  RewardInform: 15
  OneTimeAmount: 2
ExploitPatcher:
  PreventItemPickup: true
  PreventExpPortals: true
Vault:
  Money: true
  Group: true
Worth:
  BadLore:
  - Creative item by Gasha
BossBar:
  HpBarEnabled: true
Ban:
  OverrideLoginMessage: false
Homes:
  Groups:
    Newbie: 2
    Advanced: 3
    Vip: 5
  BedInteraction: true
ReSpawn:
  Global:
    PriorityOrder:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
  Specific:
    world:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    world_nether:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    world_the_end:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    MiniHry:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    Sq0ler:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    tezba:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
    event_world:
    - spawn
    - bedLocation
    - homeLocation
    - worldSpawn
Afk:
  Enabled: false
  PreventJumping: true
  PreventDamage: true
  CheckInterval: 10
  AutoAfkIn: 300
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eis no longer AFK
  AutoKickIn: -1
  RepeatingAutoKickInterval: 300
  RepeatKickCommand: false
  AutoKickCmds:
  - cmi kick [playerName] &eYou have been kicked for idling more than [time]
  DisableOnInteract: true
  SmartInteractCheck: true
  AntiAfkMachines: true
  DisableOnInventoryClick: true
  DisableOnCommand: true
  DisableOnPublicChat: true
  DisableOnPrivateChat: true
  DisableOnMove: true
  DisableItemPickup: false
Votifier:
  CountVotes: true
  PerformCommands: true
  CommandsOnVote:
  - cmi broadcast !&6[playerDisplayName] &evoted!
  - cmi give [playerName] diamond
  ExcludeList:
  - None
Ranks:
  AutoRankUp:
    Delay: 60
    PlayerDelay: 120
Signs:
  CheckInterval: 5000
  TranslateColors:
  - '&6-&8'
  - '&e-&f'
  - '&7-&8'
TabList:
  Enabled: true
  Async: true
  UpdateTabListNames: true
  GroupedEnabled: true
  Updates:
    AutoInterval: 60
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  GeneralFormat:
    PlayerName: '[playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
  GroupFormat:
    '1':
      PlayerName: '&2{&r[playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
Skins:
  Enabled: true
  SteveOnOff: false
  RequireSpecificPerm: false
Notes:
  ShowOnAlertEvent: true
GroundClean:
  WhiteList:
  - itemType
Chat:
  ModifyChatFormat: false
  ClickHoverMessages: false
  DiscordSRVPublicChat: true
  DynMapChat: true
  ReplyToLastMessenger: false
  LinkRegex2: (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  BungeeMessages: true
  BungeePublicMessages: true
  GeneralFormat: '{prefix}&f{displayName}&7: &r{message}'
  GeneralRange: -1
  ShoutRange: 200
  ShoutCost: 0
  GroupFormat:
    '1': '{prefix}&f{displayName}&f: &r{message}'
    '2': '{prefix}&f{displayName}&7: &r{message}'
    '3': '{prefix}&f{displayName}&8: &r{message}'
  Colors:
    PublicMessage: false
    PrivateMessage: true
    me: true
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      WhiteList:
      - '&c❤&7'
    NickName: true
  ChatFilter:
    Enabled: false
    Deny:
      ipBlock:
        Enabled: true
        Group: Advertising
        Regex:
        - '[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,|_|\/)\s?([a-zA-Z]{2}|aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel)\b'
        ReplaceWith: ''
        BlockType: others
        msgToStaff: '&4!&6[playerName] &4advertising with: &r[message]'
        Commands: []
      swearing1:
        Enabled: true
        Group: Swearing
        Regex:
        - \bass\b|\basshole
        ReplaceWith: dude
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
      swearing2:
        Enabled: true
        Group: Swearing
        Regex:
        - \bfu+ck
        ReplaceWith: not good
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
    WhiteList:
    - \bgoogle.\s?([a-zA-Z]{2,4})\b
    - \bspigotmc.\s?([a-zA-Z]{2,4})\b
    DuplicatedMessagePrevention:
      Use: false
      Percentage: 80
      Interval: 5
      MinAmount: 2
  IgnorePublicMessage: false
  Tag:
    Enabled: true
    HardCoreMode: false
    Color: '&c'
    Sound:
      Name: BLOCK_NOTE_HARP
      Volume: 1
      Pitch: 3
    RemoveEta: false
Command:
  CommandFilter:
    Duplicate:
      Use: false
      Percentage: 80
      Interval: 5
      MinAmount: 2
      WhiteList:
      - msg
      - tell
      - login
      - register
  Spy:
    DelayForTrigger: 60
    BlackListed:
    - register
    - login
    - l
    CommandList:
    - cmi spawn
    - cmi tp
    - cmi tpa
    - cmi heal
    - cmi feed
    - cmi fly
PlayerNotes:
  ExpiresIn: 30
PlayerMail:
  ExpiresIn: 30
  mailAllDays: 7
DisplayName:
  Format: '{nickName}'
NickName:
  BlackList:
  - admin
  - administrator
  - server
  - staff
  - staf
  MaxLength: 16
  Prefix: '~'
  PrefixWhenDifferent: false
ShowNewVersion: true
Spawners:
  FullDisable: false
  Break:
    Enabled: false
    DropExp: false
    SilkTouchLevel: 1
  Place:
    Enabled: true
    RequiresPermission: false
    RequiresExactPermission: false
  Interact:
    EggRequiresPermission: false
  TnTExplosionDrop:
    use: false
    Chance: 30
  CreeperExplosionDrop:
    use: false
    Chance: 30
  Charges:
    Use: false
    BreakWithoutCharge: false
    List:
      Noob:
        Use: false
        StartingCharge: 2
        MaxCharge: 5
        Cooldown: 3600
        Bonus: 10
      Advanced:
        Use: false
        StartingCharge: 3
        MaxCharge: 6
        Cooldown: 3000
        Bonus: 10
  Proximity:
    Use: false
    Range: 3
ItemRenaming:
  Prevent: false
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
SpawnMob:
  MaxQuantity: 10
  MaxPassengers: 10
Counter:
  Range: 10
Mirror:
  MaxRange: 50
NetherPortal:
  PreventCreation: false
  MaxHeight: 23
  MaxWidth: 23
Portals:
  CheckInterval: 300
  CheckParticleInterval: 500
  PerformCommands: true
  Commands:
  - cmi effect [playerName] blindness 2 1 -s
Animations:
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  DoubleClick: false
  DoubleClickDelay: 200
DamageControl:
- nowalldamage:fly_into_wall:0
- lowermagmacubedamage:hot_floor:0.5
Totem:
  RemoveFromInventory: false
  Cooldown:
    Use: false
    Time: 600
  Warmup:
    Use: false
    Time: 10
Elytra:
  Boost:
    SpeedLimit: 200
    SpeedLimitStop: false
    SpeedDecimals: true
    GeneralMultyplier: 0.1
    SuperMultyplier: 0.3
    UseItems: false
    Item: '288'
    RequiresItem: true
    Amount: 1
    SuperAmount: 5
    ShowParticles: true
  Launch:
    Time: 2
FlightCharge:
  Enabled: false
  EnabledByDefault: true
  AutoSwitch: false
  ExpRechargeRate: 1
  MoneyRechargeRate: 1
  MaxChargeLevel: 1000
  DeductOnIdling: 1
  DeductOnFallMulti: 2
  DamageOnFall: true
  DamageOnToggle: false
  KillOnFall: false
Point:
  DefaultParticle: COLOURED_DUST
Messages:
  Login:
    Disabled: false
    AutoHideFrom: -1
    Custom:
      Use: false
  Logout:
    Disabled: false
    AutoHideFrom: -1
    Custom:
      Use: false
  FirstJoinMessage:
    Use: false
  DeathMessage:
    AutoHideFrom: -1
Books:
  DefaultAuthor: Server
Motd: welcomeMessage
Spawn:
  Main:
    World: None
    X: 0.0
    Y: 0.0
    Z: 0.0
    Pitch: 0.0
    Yaw: 0.0
    RespawnLocation: false
    Rng: 0
  FirstSpawn:
    Use: true
    World: None
    X: 0.0
    Y: 0.0
    Z: 0.0
    Pitch: 0.0
    Yaw: 0.0
Newbie:
  Kit: Newbie
Kits:
  GUI: true
  FillEmptyFields: true
Warps:
  GUI: true
  perPage: 50
  saveCreator: false
  showCreator: false
GlobalGui:
  EmptyField: STAINED_GLASS_PANE:15
DynamicViewRange:
  Enabled: false
WorldLimits:
  Enabled: false
  Gamemode:
  - world:Survival
  Fly:
  - world:False
  GodMode:
  - world:False
  SpawnReasons:
    world:
    - None
    world_nether:
    - None
    world_the_end:
    - None
    MiniHry:
    - None
    Sq0ler:
    - None
    tezba:
    - None
    event_world:
    - None
CheckForNameChange:
  OnLogin: true
  AmountToShow: 3
  OnInfoShow: true
inv:
  SaveOnDeath: false
  IgnoreEmpty: false
  RequiresPermission: false
  SavedInventories: 5
hunger:
  overide: false
heal:
  RemoveNegative:
    use: false
    List:
    - blindness
    - confusion
    - harm
    - hunger
    - poison
    - slow
    - slow_digging
    - weakness
    - wither
Cuff:
  Mute: true
  AllowedCommands:
  - msg
  - r
  - tell
Dispose:
  UILines: 4
ItemRepair:
  RepairShare:
    ProtectNormalRepair: false
    ProtectCommandRepair: false
    Durability: 1
    BypassWithRepairPermission: true
    AddLore: true
    CancelEvent: true
    InformWithMessage: true
Cooldowns:
  Enabled: false
  List:
  - cmi heal:180
  - cmi feed:120
WarmUps:
  Enabled: false
  InformOnNoMove: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
Jail:
  CheckInterval: 500
  DefaultTime: 300
  ChatRange: 20
  WhiteListedCmds:
  - cmi msg
  - cmi reply
scan:
  SoftCap: 19.0
  DefaultSpeed: 15
  GlobalRangeByDefault: false
  DefaultRange: 2
  EnablePurge: false
search:
  EnablePurge: false
lfix:
  FixOnChunkGeneration: false
  WorldsToFix:
  - world
  - world_nether
  - world_the_end
  - MiniHry
  - Sq0ler
  - tezba
  - event_world
  SoftCap: 19.0
  DefaultSpeed: 15
purge:
  CleanOnStart: false
  OfflineDays: 90
  PlayerData:
    Enabled: true
    SourceFolder: world/playerdata
    DeleteFiles: false
    DestinationFolder: world/playerdata_backup
  PlayerStats:
    Enabled: true
    SourceFolder: world/stats
    DeleteFiles: false
    DestinationFolder: world/stats_backup
  PlayerAdvancements:
    Enabled: true
    SourceFolder: world/Advancements
    DeleteFiles: false
    DestinationFolder: world/Advancements_backup
  Essentials:
    Enabled: false
    SourceFolder: plugins/Essentials/userdata
    DeleteFiles: false
    DestinationFolder: plugins/Essentials/userdata_backup
  LWC:
    Enabled: false
Selection:
  Tool: wood_hoe
Time:
  Day: '12:00'
  Night: '24:00'
  Morning: 06:00
  Dusk: '18:00'
  AutoTime:
    Interval: 60
    Worlds:
    - ''
Enchanting:
  enchantLimits:
    Enabled: true
    MaxLevel:
      protection_environmental: 4
      protection_fire: 4
      protection_fall: 4
      protection_explosions: 4
      protection_projectile: 4
      oxygen: 3
      water_worker: 1
      mending: 1
      thorns: 3
      vanishing_curse: 1
      depth_strider: 3
      frost_walker: 2
      binding_curse: 1
      damage_all: 5
      damage_undead: 5
      damage_arthropods: 5
      knockback: 2
      fire_aspect: 2
      loot_bonus_mobs: 3
      sweeping_edge: 3
      dig_speed: 5
      silk_touch: 1
      durability: 3
      loot_bonus_blocks: 3
      arrow_damage: 5
      arrow_knockback: 2
      arrow_fire: 1
      arrow_infinite: 1
      luck: 3
      lure: 3
 ##
#####################################
```

Cmi Version (using`/cmi version`): 7.4.3.0
Server Type (Spigot/Paperspigot/etc): Spigot 
Server Version (using `/ver`): This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
