### ISSUE TITLE
Char formatting is messup with rank i have adventurer II,but in chat section show adventurer I

### ISSUE THREAD

**Issue by FelixsLeong** [Zrips/CMI#3563]
**Description of issue or feature request:**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## GeneralFormat: '{prefix} &f{displayName}&7: &r{message}'
  # Defines range of regular messages to travel
  # Set to -1 to disable range restriction
  GeneralRange: -1
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.chat.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
  # Prefix used to idicate that message should be sent to public chat instead of current players chat room
  # Set it to empty field if you want this feature to be disabled
  ChatRoomShout: '!'
  # Time in seconds you want to keep chat rooms alive before removing them
  # This only applies to empty rooms after last user leaves it
  ChatRoomLife: 3600
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  # Permission example: cmi.chatgroup.2
  GroupFormat:
    '1': '{prefix}&f{displayName}&f: &r{message}'
    '2': '{prefix}&f{displayName}&7: &r{message}'
    '3': '{prefix}&f{displayName}&8: &r{message}'##
#####################################
```

---

**Cmi Version (using`/cmi version`):* v8.6.27.3* 

**Server Type (Spigot/Paperspigot/etc):*PAPER* 

**Server Version (using `/ver`):*1.15.2* 

**Relevant plugins (Delete if this isn't needed):*luckperm*
