### ISSUE TITLE
Respawn Anchor Doesn't Work

### ISSUE THREAD

**Issue by MrAmos123** [Zrips/CMI#3566]
**Description of issue:**

Respawn Anchor's don't work, I assume because of "ReSpawn", though I tried with it on and off, both attempts respawn in overworld.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 5
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: spawn, bedLocation, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - spawn
    - worldSpawn
    - homeLocation
    - bedLocation
  # Defines respawn order for defines worlds
  # Remove world if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    world:
    - spawn
    - worldSpawn
    - homeLocation
    - bedLocation
    world_nether:
    - spawn
    - worldSpawn
    - homeLocation
    - bedLocation
    world_the_end:
    - spawn
    - worldSpawn
    - homeLocation
    - bedLocation
```

---

**Cmi Version (using`/cmi version`):** 8.7.0.1

**Server Type (Spigot/Paperspigot/etc):** Spigot 

**Server Version (using `/ver`):** 1.16.1 - 16d7899-4ff609e
