### ISSUE TITLE
Random Teleport Cooldown not working

### ISSUE THREAD

**Issue by crunchward** [Zrips/CMI#3587]
**Description of issue:**

/cmi rt
The cooldown appears to be ineffective.
It was set to 60 and tested after removing all perms except cmi.command.rt from the tester and they were able to run the command repeatedly and instantly. This was observed after a server restart for good measure.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will not longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: true
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 1000
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_nether:
      Enabled: true
      MaxRange: 5000
      MinRange: 1000
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: false
      minY: 0
      maxY: 256
    world_the_end:
      Enabled: true
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    Resource:
      Enabled: true
      MaxRange: 4800
      MinRange: 100
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: false
      IgnoreLava: false
      minY: 0
      maxY: 256
    Towny:
      Enabled: true
      MaxRange: 4900
      MinRange: 100
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
  # How long force player to wait before using command again.
  Cooldown: 60
  # How many times to try find correct location for teleportation.
  # Keep it at low number, as player always can try again after delay
  MaxTries: 20
  # List of biomes to exclude from random teleportation
  ExcludedBiomes:
  - Ocean
  - Deep ocean
```

---

**Cmi Version (using`/cmi version`):** 
8.6.27.0

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper 304
