### ISSUE TITLE
/tpa acting as /tpahere

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#3595]
**Description of issue or feature request:**
/tpa acting as /tpahere

For instance, if I ask Player1 with /tpa to TP to ME, when accepted they TP to me. So it just works like /tpahere

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):*
```
 Teleport:
    # When true then while checking for safe location, we will try to determin it going down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: false
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    Invulnerability: 5
    # When this set to true each time player teleports to any destination he will be teleported to spawn point
    # This is to prevent from people knowing to which direction you have teleported too
    # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
    ToSpawnBefore: false
    # Set to true if you want to use tp commands as /cmi tp [WhoYouWantToTeleport] [WhereToTeleport] when its false, its /cmi tp [whereToTeleport] [WhoYouWantToTeleport]
    SwitchPlaces: true
    # Applies for tpa, tpahere and tpaall only
    # If set to true then player will be teleported to current player position after accepting teleport request
    # If set to false then player will be teleported to player at which teleport request was issued
    CurrentLoc: true
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 50
    # Defines time in seconds for accepting tpa or tpahere requests
    TpaTime: 60
    # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
    TpaWarmup: 3
    # Defines if player can move when tpa or tpahere is being accepted
    TpaMove: false
    # Defines time in seconds for blocking player teleport offers after denying their request
    TpaBlock: 120
    # Defines time in seconds for bypassing prevented teleportation to unsafe location
    TpBypass: 15
    # When set to true adds accept and deny buttons when sending tpa or tpahere requests
    DenyConfirm: true
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in his inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    # Back location will not be triggered if player teleports closer than defined amount of blocks
    BackMinDistance: 5
    # When set to false we will not include teleport location when teleporting around with worldedit compass
    # When set to true we will include each teleport action, even if you simply jumped around with compass
    BackWithWE: true
    # List of worlds to whichones player can't go back with /back command
    BackBlackList:
    - TeztWorldz
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.2
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.16.1-R0.1-SNAPSHOT
