### ISSUE TITLE
Public messages going through the bungeecord are not ignored if the player is writing from the other server.

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#360]
Public messages going through the bungeecord are not ignored if the player is writing from the other server.

 ```
 # If set to true, players public message who is in your ignore list will not be shown
  IgnorePublicMessage: true
```

```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have aditional information when hovering over it (PlaceHOlderAPI supported) and can be clicked for quick reply option
  ClickHoverMessages: true
  # Enables support for DiscordSRV plugin
  DiscordSRVPublicChat: true
  # Enables support for DynMap web chat
  DynMapChat: true
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: true
  # Defines regex when replacing url in chat with short word
  LinkRegex2: (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # Do you want to enable private messaging over bungeecord
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  BungeePublicMessages: true

```
