### ISSUE TITLE
command spy problem

### ISSUE THREAD

**Issue by KingsRequin** [Zrips/CMI#3600]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
hello, I see the / login commands while being OP while they are in the blacklist
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
Spy:
    # Delay in seconds for commands spy to turn on after relog
    # This will prevent some one from loging in with admin account and seeing commands before loging in
    # Keep it at same or higher than your login plugin delay for entering password
    # This includes social spy too
    DelayForTrigger: 60
    # Commands in this list will not be shown when command spy is enabled for player for security/privacy reasons
    BlackListed:
    - register
    - login
    - l
#######################################
```

---

**Cmi Version (using`/cmi version`): 8.7.0.2** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): Paper-321** 

**Relevant plugins (Delete if this isn't needed): AutheMe5.6.0 and AuthMeBungee2.2.0-beta1 (in bungeecord) **
