### ISSUE TITLE
Custom permission in portals

### ISSUE THREAD

**Issue by Arkobat** [Zrips/CMI#3636]
## Custom permission in portals  
Currently, we have a `true/false` option to use permission in portals.
What I suggest, is access to have custom permissions, instead of `cmi.command.portal.<portalName>`
The way I suggest this implementation, is similar to the way it works now, but instead of a `true/false` option, it should be a String.
The config would then look like something like, where we have 3 portals with same permission node:
```yaml
  EndPortal1:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
  EndPortal2:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
  EndPortal3:
    Loc: <loc>
    Tp: <destination>
    requiresPerm: portal.end
    informOnMissingPerm: false
```

**Breaking current portals?**  
I'm aware that this will break existing portals. I therefore suggest that all new portals would be created with the default permission node, instead of true/false. (`requiresPerm: cmi.command.portal.<portalName>`)  
All old portals could either be renamed at first startup or have `true` fallback to de default permission node.

---  
### Properly unnecercery stuff  
As this is a suggestion, this is properly unnecessary, but I've supplied it regardless.
**Cmi Version (using`/cmi version`):** 8.6.20.6  
**Server Type (Spigot/Paperspigot/etc):** Paperspigot  
**Server Version (using `/ver`):** 1.13.2 (git-Paper-653)
