### ISSUE TITLE
Placeholders not working in schedules.

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#3655]
**Description of issue or feature request:**
I've tested PlaceholderAPI placeholders in multiple areas of CMI in testing for this, I use placeholders in tablist.yml and other files and I tried to use them today in schedules but no placeholder seem to work at all, even CMI ones.

This is one placeholderAPI placeholder that works in other menus and other plugins, but not schedules
<img width="486" alt="Screen Shot 2020-07-05 at 10 03 06 PM" src="https://user-images.githubusercontent.com/11791722/86530255-503de300-bf0b-11ea-8d87-072934872abb.png">

`
  - broadcast! &6Tip &e» &fOnly &e&n%voteparty_votes_required_party%&f more votes
    and everyone will recieve &e3x Risen Keys, 5x DP Keys and 2m gems&f. /vote!`

This is how it's setup in the schedules. It should work perfectly.

I even tried other CMI placeholders, setup like this in the schedules.yml:
<img width="803" alt="Screen Shot 2020-07-05 at 10 05 21 PM" src="https://user-images.githubusercontent.com/11791722/86530286-a0b54080-bf0b-11ea-9e98-b2346246fffa.png">

Yet, instead of the placeholders working it just turns into nothing as shown in the below screenshot:
<img width="433" alt="Screen Shot 2020-07-05 at 10 04 47 PM" src="https://user-images.githubusercontent.com/11791722/86530280-8ed39d80-bf0b-11ea-87d4-a1671ea97dad.png">

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Test:
  Enabled: true
  MinPlayers: 1
  FeedBack: false
  Delay: 2
  Repeat: true
  Randomize: true
  Commands:
  - broadcast! &6Tip &e» &fOnly %voteparty_votes_required_party%&f more votes
    and everyone will recieve &e3x Risen Keys, 5x DP Keys and 2m gems&f. /vote!
  - broadcast! &6Tip &e» &fYour total playtime is &e%cmi_user_playtime_days%d, %cmi_user_playtime_hours%h
    %cmi_user_playtime_minutes%m&f. &fSpend more time on JuiceBox to increase this!
```

---

**Cmi Version (using`/cmi version`):** 
Latest

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.2
