### ISSUE TITLE
CMI-setspawn after restart server the /spawn is gone

### ISSUE THREAD

**Issue by Ronron1026** [Zrips/CMI#3665]
**Description of issue:**

Here is my problem, everytime i setspawn use /cmi setspawn after i restart my server then i try to type /spawn the system tell me i don`t have set a spawn yet ..pls help me fix this problem thanks you
---

```

---

**Cmi Version :8.7.0.9* 

**Server type : Paper:** 

**Server Version: 1.16.1**

**Comment by Zrips** [comment]
Check your config.yml file to make sure that location is saved properly and make sure you dont have any startup errors which could reset config file

**Comment by Zrips** [comment]
And do you have spawn point set on normal world or created by some multiverse plugin?

**Comment by Ronron1026** [comment]
ya i use multiverse-core plugin to create a new world . but i did not set anything , just using /cmi setspawn

**Comment by Ronron1026** [comment]
i have check my config already but i did not saw anything about setspawn locations @@

**Comment by Zrips** [comment]
Check latest version of CMI and check config file, you are looking for something like
```
Spawn:
  # Forces players to login in defined spawn point when logging into server
  SpawnOnJoin: false
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  Main:
    World: LT_Craft
    X: 192.43680284487473
    Y: 67.0
    Z: -61.397220648273425
    Pitch: 13.9500065
    Yaw: -72.270454
    RespawnLocation: false
    Rng: 0
```
