### ISSUE TITLE
CMI Event Command Missfires.

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#3687]
In my EventCommands.yml i have this:

```
firstJoinServer:
  Enabled: true
  Commands:
  - cmi msg [playerName] Welcome to Angel-Gaming please type /register to get build
    rights!
  - cmi msg [playerName] Already registerd on Angel-Gaming.com type /link!
  - toast [playerName] -t:challenge -icon:diamond &4Thank you for &2Joining please /register!
```

When ever I join the server that event triggers and i get the Toast, and the MSG's sent to me.

No errors in console, just seems to be miss triggering.

Here is a list of my current plugins:

`
AutoPlugPlugin, BungeeTabListPlus, CMI, CMIPaperLib, CraftingStore, GrantX, LuckPerms, MineSync*, MysqlPlayerDataBridge, NoPluginsCommand*, PacketListenerApi*, PlaceholderAPI, ProtocolLib, ServerInfo, Spartan, TigerReports*, UltraCustomizer, UltraCustomizerPlus, Universes, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard
`
