### ISSUE TITLE
%cmi_schedule_nextin_[schedName]% doesn't work

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3688]
**Description of issue:**
---

Hi, this placeholder doesn't work. https://imgur.com/a/BKSBakF

```
xpboost:
  Enabled: true
  MinPlayers: 1
  FeedBack: true
  Repeat: true
  PerformOn:
    '1':
      Day: Monday
      Hour: 15
      Minute: 30
    '2':
      Day: Tuesday
      Hour: 16
    '3':
      Day: Wednesday
      Hour: 18
      Minute: 30
    '4':
      Day: Thursday
      Hour: 17
    '5':
      Day: Friday
      Hour: 17
      Minute: 45
    '6':
      Day: Saturday
      Hour: 1
    '7':
      Day: Saturday
      Hour: 9
      Minute: 30
    '8':
      Day: Saturday
      Hour: 15
    '9':
      Day: Sunday
      Hour: 2
    '10':
      Day: Sunday
      Hour: 8
      Minute: 30
    '11':
      Day: Sunday
      Hour: 16
      Minute: 30
  Commands:
  - xpb global 2.0 900
  - xpb on
  - broadcast! &e*********************************************** \n&7XPBoost s &edvojnásobným
    &7XP začal! \nVyužij &e15 min &7této výjimečné chvíle! \n&e***********************************************
  - delay! 450
  - broadcast! &e*********************************************** \n&7XPBoost s &edvojnásobným
    &7XP \npokračuje ještě &e7,5 min! \n&7Využij této výjimečné chvíle! \n&e***********************************************
  - delay! 450
  - broadcast! &e*********************************************** \n&7XPBoost s &edvojnásobným
    &7XP skončil! \nDalší za &e%cmi_schedule_nextin_xpboost%&7! \n&e***********************************************
  - xpb off
```

---

**Cmi Version (using`/cmi version`):**  8.7.0.11

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  82, 1.16.1
