### ISSUE TITLE
Command bypasses aren't working

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#3693]
From the config file

```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: true
  showBossBarInfo: true
  List:
  - cmi vanish:3:false
  - cmi back:3:true
  - cmi warp:3:false
```

I've given the permissions (and other permissions) to see if this could work and it's not working

cmi.command.vanish.warmupbypass 
cmi.command.back.warmupbypass 
cmi.command.warp.warmupbypass 

cmi.command.vanish.cooldownbypass 
cmi.command.back.cooldownbypass 
cmi.command.warp.cooldownbypass 

cmi.command.vanish.movebypass
cmi.command.back.movebypass
cmi.command.warp.movebypass
