### ISSUE TITLE
Various /cmi bossbarmsg issues?

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3695]
**Description of issue:**

1. When using `/cmi bossbarmsg all &6Server restart in &e[autoTimeLeft]! -cmd:"stop" -sec:-120 -c:red -n:restart`, even when cancelled with `/cmi bossbarmsg -cancel:restart`, it will still run the command? Not sure if this is intended behavior.
2. When using the `/cmi bossbarmsg` command inside of a customAlias (see my example below) mixed with the `delay!` parameter, the command that is used inside of the bossbarmsg is ran multiple times, however it's a random amount of times. Also not sure if this is intended behavior.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  restartcd:
    Cmds:
    - broadcast! &6Restarting in &e2&6 mins!
    - cmi bossbarmsg all &6Server restart in &e[autoTimeLeft]! -cmd:"stop" -sec:-120 -c:red -n:restart
    - delay! 60
    - broadcast! &6Restarting in &e1&6 min!
    - delay! 30
    - broadcast! &6Restarting in &e30&6 sec!
    - delay! 20
    - broadcast! &6Restarting in &e10&6 sec!
    - delay! 5
    - broadcast! &6Restarting in &e5&6 sec!
    - delay! 1
    - broadcast! &6Restarting in &e4&6 sec!
    - delay! 1
    - broadcast! &6Restarting in &e3&6 sec!
    - delay! 1
    - broadcast! &6Restarting in &e2&6 sec!
    - delay! 1
    - broadcast! &6Restarting in &e1&6 sec!
    Perm: true
```

---

**Cmi Version (using`/cmi version`):** 8.7.0.11

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 86 1.16.1
