### ISSUE TITLE
Nether Portals cannot be 23x23

### ISSUE THREAD

**Issue by Hexical1** [Zrips/CMI#3712]
**Description of issue:**
Players cannot create a nether portal that is 23x23, despite the config saying it is allowed. 

I had a player create a portal that was 23x23 with the frame (21x21 portal), and CMI gave the message that it was too large. I then decided to just try and up the number by 2 to see if that fixed it, but the same message popped up saying it is too wide, this time claiming 25 blocks is the max width. It appears CMI is reading the config correctly to a degree, but it is still blocking players from making portals. 

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
NetherPortal:
  # Can prevent nether portal creation entirely. Option to bypass with cmi.netherportalbypass
  PreventCreation: false
  # Maximum height nether portal can be created. Vanilla size is 23
  MaxHeight: 25
  # Maximum width nether portal can be created. Vanilla size is 23
  MaxWidth: 25
```

---

**Cmi Version (using`/cmi version`): 8.7.1.1** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): 1.16.1 (Paper 89)**
