### ISSUE TITLE
Maximum usage for /cmi rt

### ISSUE THREAD

**Issue by Harveyplays02** [Zrips/CMI#3715]
**Description of feature/improvement request:**

This feature would allow users to set a maximum uses number for randomly teleporting.

---
### Detailed explanation of what it should do, when and in what situation: ###
The settings for this new feature would be configurable per-world, via the config (or permission, config probably better?). This would put a fixed limit onto users to stop them from randomly teleporting after a set amount of uses. Example config below:
```
RandomTeleportation:
  AutoGenerateWorlds: true
  Worlds:
    world:
      Enabled: true
      MaxRange: 15000
      MinRange: 400
      MaxUses: 5 # This would be the fixed amount of uses for "world". Maybe a bypass for it with a permission (cmi.command.rt.bypassmaxuses)
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 128
```

### Basic explanation as to why this feature is needed and/or useful to have: ###
Thsi feature would be useful to have to block users that randomly teleport a lot to try and loot structures / chests / find other peoples' bases, or stop spam usage of machines with Slimefun, such as the ore chunks items.
