### ISSUE TITLE
[Request] Particle effect on /heal

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#373]
Configurable particle effect on /heal. Can be useful to notify surrounding players that the person has healed themselves.
For reference:
https://www.spigotmc.org/resources/particleheal.41105/

**Comment by MCTyler** [comment]
Have you looked into Event Settings?

**Comment by TheWranger** [comment]
No, I must've completely missed that. What config file is that in?

**Comment by MCTyler** [comment]
We will need to edit the Wiki to include this information if this is the case so others won't need to have this issue. I'll do it later.

**Comment by TheWranger** [comment]
Another thing is that Minecraft's particle command cannot be used to spawn particles at a certain players position.

**Comment by LogGits** [comment]
Forgot to close this but it can now be done using config section:
```yaml
Particles:
  Enabled: true
  Healing: circle;effect:heart;dur:0.1;part:1;offset:0,1.7,0;radius:0.3
```
