### ISSUE TITLE
CMI Rankup PlaceHolders Not Working

### ISSUE THREAD

**Issue by TheWookofWallST** [Zrips/CMI#3747]
**Description of issue:**
None of the rank related PlaceHolders for CMI will work with my scoreboard or the cmi tablist. I have my rankup config attatched, I was told by someone in discord that making sure spaces and lower cases and that all stat requirements should be " " wrapped. He said if that didn't work to make a GitHub big report.
Would also like to add that other CMI placeholders are working it is just the rank related ones. Specifically I am trying to use the % until rankup and next rank ones.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

# Main server folder spigot.yml and check that stats saving prevention its set to false stats->disable-saving: false
# Player will get default rank group depending on set permission node cmi.rank.[groupName]
# Not enabled ranks will be ignored
# DisplayName section is optional and it will be used to represent rank ingame. This is NOT defining required permission node and you still need to use node name to rankup to this rank
# DefaultRank section defines if player can be assigned to this rank if he dont have any. There can be more than one default rank, and depending on permision node, first rank will be assigned to that player when needed
# PermissionRequirement section defines list of permissions player should have to rankup to that rank. Optional - For each permission node you can add its name which will be shown in /cmi rankinfo with : In example cmi.command.fly:Fly
# McMMORequirement section defines list of McMMO skills and levels player should have to rankup to that rank.
# JobsRequirement section defines list of Jobs and levels player should have to rankup to that rank.
# ItemRequirement section defines list of items player should have to rankup to that rank. Items will be taken after succesfull rankup from players inventory.
# AutoRankup section defines if player will be auto ranked to this rank if possible. Keep in mind that if there is more than one legit rankup, player will have to confirm to which rank he wants to rankup
# RankupConfirmation section defines if you want to add additional confirmation for this rankup. Usefull to avoid unintentional rankups. Keep in mind that autorankup will request confirmation for rankup to this rank even if there is only one legit rankup option
# NextRanks is list of possible next ranks from this rank. Can be one or can be dozens. Keep in mind that each rank requirements will be shown in chat and it can clutter quite allot if there is bunch of them at once
# MoneyCost defines how much player will have to pay to rankup to this rank
# ExpCost defines how much player will have to pay in exp to rankup to this rank
# Votes defines how much player will need to have votes to rankup to this rank
# Commands is list which will be performed on rankup. Can be additional actions, like message broadcast or anything alse
# Main section is StatsRequirements and it can have allot of different values in it:
#   In general format goes like this [mainStat](:optionalSubStat):amount
#   In example MonsterKills:100 will require from player to have 100 monster kills while MonsterKills:Zombie:100 will require to have 100 zombie kills. Both of them can be used if needed.
#     List of possible requirement and basic explanations:
#       Distance in blocks:
#         Travel - travel in total
#         Walk - has to walk
#         Sneak - has to sneak
#         Sprint - has to sprint
#         Swim - has to swim
#         Fall - has to fall
#         Climb - has to climb
#         Fly - has to fly
#         Dive - has to walk under water
#         MinecartTravel - has to travel with minecart
#         BoatTravel - has to travel with boat
#         PigTravel - has to ride pig
#         HorseTravel - has to ride horse
#         ElytraTravel - has to fly with elytra
#       Time in sec:
#         PlayTime - total play time
#         FromLastDeath - from last death
#         SneakTime - sneak time
#       Amounts:
#         GameQuit - how many times player left game
#         Jump - jump count
#         DamageDealt - total damage made
#         DamageTaken - total damage taken
#         Deaths - count of deaths
#         MobKills - total amount of mobs killed by player
#         PlayerKills - total amount of players killed. Indirect kills dont count
#         ItemEnchanted - amount of enchanted items
#         AnimalsBred - animals bred
#         FishCaught - fish caught
#         TalkedToVillager - times talked to villager
#         TradedWithVillager - traded with willager
#         CakeSlicesEaten - cake slices eaten
#         CauldronFilled - cauldron filled
#         CouldronUsed - couldron used
#         ArmorCleaned - times armor cleaned (leather armor)
#         BannerCleaned - times banner cleaned
#         BrewingstandInteractions - brewingstand interactions
#         BeaconInteractions - beacon interactions
#         CraftingTableInteractions - crafting table interactions
#         FurnaceInteractions - furnace interactions
#         DispenserInspected - dispenser inspected
#         DropperInspected - dropper inspected
#         HopperInspected - hopper inspected
#         ChestOpen - chest open
#         TrappedChestTriggered - trapped chest triggered
#         EnderchestOpened - enderchest opened
#         NoteblockPlayed - noteblock played
#         NoteblockTuned - noteblock tuned
#         FlowerPotted - flower potted
#         RecordPlayed - record played
#         SleeptInBed - sleept in bed
#         ShulkerBoxOpened - shulker box opened
#         ItemDropped - defines amount of dropped items. If specific item is not defined, then total amount is used
#         ItemPickups - defines amount of picked up items. If specific item is not defined, then total amount is used
#         BlocksMined - defines amount of blocks mined. If specific block is not defined, then total amount is used
#         BlocksPlaced - defines amount of blocks placed. If specific block is not defined, then total amount is used
#         ItemBreaks - defines amount of broken items. If specific item is not defined, then total amount is used
#         ItemCrafts - defines amount of crafted items. If specific item is not defined, then total amount is used
#         ItemsUsed - defines amount of item usage. like mining with pickaxe. If specific item is not defined, then total amount is used
#         MonsterKills - defines amount of monster kills. If specific monster is not defined, then total amount is used
#         KilledBy - defines amount of deaths by monster. If specific monster is not defined, then total amount is used

peasant:
  Enabled: true
  DisplayName: '&7[&fPeasant&7]'
  DefaultRank: true
  AutoRankup: false
  NextRanks:
  - Merchant
merchant:
  Enabled: true
  DisplayName: '&7[&6Merchant&7]'
  AutoRankup: false
  RankupConfirmation: true
  Votes: 5
  McMMORequirement:
  - woodcutting:10
  - mining:20
  JobsRequirement:
  - totallevel:15
  NextRanks:
  - Craftsman
  MoneyCost: 25000
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &6Merchant &erank!
  StatsRequirements:
  - "PlayTime:1440"
  - "travel:1000"
  - "MonsterKills:100"
  - "PlayerKills:5"
craftsman:
  Enabled: true
  DisplayName: '&7[&2Craftsman&7]'
  DefaultRank: false
  AutoRankup: false
  RankupConfirmation: true
  Votes: 15
  NextRanks:
  - Artisan
  MoneyCost: 50000
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &2Craftsman &erank!
  StatsRequirements:
  - "travel:5000"
  - "blocksmined:3000"
  - "PlayerKills:25"
  - "MonsterKills:500"
  - "PlayTime:2880"
  McMMORequirement:
  - taming:5
  - unarmed:25
  JobsRequirement:
  - totallevel:20
artisan:
  Enabled: true
  DisplayName: '&7[&aArtisan&7]'
  AutoRankup: false
  RankupConfirmation: true
  Votes: 25
  MoneyCost: 100000
  NextRanks:
  - Aristocrat
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &aArtisan &erank!
  StatsRequirements:
  - "PlayTime:4320"
  - 'travel:10000"
  - "blocksmined:5000"
  - "MonsterKills:250"
  - "PlayerKills:10"
  McMMORequirement:
  - acrobatics:30
  - archery:35
  JobsRequirement:
  - totallevel:35
aristocrat:
  Enabled: true
  DisplayName: '&7[&bAristocrat&7]'
  AutoRankup: false
  RankupConfirmation: true
  Votes: 50
  MoneyCost: 250000
  NextRanks:
  - Nobleman
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &bAristocrat &erank!
  StatsRequirements:
  - "PlayTime:5760"
  - "Swim:1000"
  - "blocksmined:10000"
  - "MonsterKills:750"
  - "PlayerKills:50"
  McMMORequirement:
  - herbalism:50
  - fishing:45
  JobsRequirement:
  - totallevel:50
nobleman:
  Enabled: true
  DisplayName: '&7[&cNoble&9man&7]'
  AutoRankup: false
  RankupConfirmation: true
  Votes: 75
  MoneyCost: 500000
  NextRanks:
  - Spartan
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &cNoble&9man &erank!
  StatsRequirements:
  - "PlayTime:7200"
  - "walk:15000"
  - "HorseTravel:5000"
  - "itemsused:10000"
  - "PlayerKills:100"
  - "MonsterKills:1000"
  McMMORequirement:
  - acrobatics:50
  - mining:60
  JobsRequirement:
  - totallevel:75
spartan:
  Enabled: true
  DisplayName: '&6&l[&4&lSpartan&6&l]'
  AutoRankup: false
  RankupConfirmation: true
  Votes: 100
  StatsRequirements:
  - "PlayTime:10080"
  - "walk:30000"
  - "DamageDealt:50000"
  - "MonsterKills:2000"
  - "PlayerKills:150"
  - "blocksmined:30000"
  McMMORequirement:
  - swords:70
  - throwing:55
  JobsRequirement:
  - totallevel:100
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to &6&l[&4&lSpartan&6&l] &erank!
  - cmi heal [playerName]
  - money give [playerName] 10000
  - msg [player] &6Congratz &2Spartan&6!

```

---

**Cmi Version (using`/cmi version`):** 8.7.2.4

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot

**Server Version (using `/ver`): 1.16.1

**Relevant plugins: CMI
