### ISSUE TITLE
customAlias problem

### ISSUE THREAD

**Issue by dangerORclose** [Zrips/CMI#378]
Description of issue or feature request:
/help
/rules
Both commands are not doing anything, not showing a console error neither.
#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
####################
## PASTE ERROR HERE ##
####################
```

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
#####################################
## # 
# Edit custom variables in game if posible
# Some extra variables can be used, like [playerName] will insert senders name automaticaly
# All global variables should work, you can find full list in locale file
# You can add delay between commands by inserting line like
# delay! 5
# This will delay next commands by defines time in seconds
# If command is shortened and you need to provide some changing variables like target player name you need to define what and where it should be placed
# Example: /cmi heal Zrips 
# Can be shortened with custom alias to something like /h zrips by using alias command like
# cmi heal $1
# If you need to add more than one variable, use $1- format. Number represents variable place when used in alias command
# Example: cmi tppos $1-

CustomAlias:
  help:
  - ctext help $1-
  rules:
  - ctext rules $1-
 ##
#####################################
```

Cmi Version (using`/cmi version`): 7.7.6.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2-R0.1-SNAPSHOT
