### ISSUE TITLE
Cooldowns and Join/leave messages

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3794]
**Description of issue:**
_How can I set custom join-leave-first join messages? I have this config but they still aren't shown:_ **SOLVED**

![imagen](https://user-images.githubusercontent.com/29895095/88151484-0d665580-cc03-11ea-9973-a4de3abe3c0c.png)

And another question: Is it possible to cooldown the teleports only for some ranks? For example:

- Member has 5 seconds between /spawn and teleport, /tpaccept and teleport...
- VIP has 2 seconds
- Mod has 0 seconds

**Cmi Version (using`/cmi version`):** 8.7.3.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(379) 1.15.2-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
They are in the languagefile

**Comment by CloudeLecaw** [comment]
About the warmups in config you can define commandwarmups. The groups have to follow warmups and cooldowns until you give them the bypass permissions

cmi.command.tpa.warmupbypass – Allows to bypass tpa command warmup
cmi.command.tpahere.warmupbypass – Allows to bypass tpahere command warmup
Cooldown bypassedbare descripted in the config :)

**Comment by Srborjaa** [comment]
Thanks for your help. But I still have two questions:

- Is there a per-group teleport warp-up?
- Could I apply this warm-up to the /spawn and /warp commands?

Thanks for your help!

**Comment by CloudeLecaw** [comment]
not per group jet you just can define one for one command and give bypass permissions 
to selcet groups
```
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: false
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
you just need to add cmi spawn :5:false
bapasses would be

>  cmi.command.spawn.warmupbypass 
>  cmi.command.warp.warmupbypass

**Comment by CloudeLecaw** [comment]
for TPA and Tp modify you also have a nice section in the config
may you wanne take a look :)
```
  Teleport:
    # When true then while checking for safe location, we will try to determin it going down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: false
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    Invulnerability: 5
    # When this set to true each time player teleports to any destination he will be teleported to spawn point
    # This is to prevent from people knowing to which direction you have teleported too
    # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
    ToSpawnBefore: false
    # Set to true if you want to use tp commands as /cmi tp [WhoYouWantToTeleport] [WhereToTeleport] when its false, its /cmi tp [whereToTeleport] [WhoYouWantToTeleport]
    SwitchPlaces: true
    # Applies for tpa, tpahere and tpaall only
    # If set to true then player will be teleported to current player position after accepting teleport request
    # If set to false then player will be teleported to player at which teleport request was issued
    CurrentLoc: true
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 50
    # Defines time in seconds for accepting tpa or tpahere requests
    TpaTime: 60
    # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
    TpaWarmup: 3
    # Defines if player can move when tpa or tpahere is being accepted
    TpaMove: false
    # Defines time in seconds for blocking player teleport offers after denying their request
    TpaBlock: 120
    # Defines time in seconds for bypassing prevented teleportation to unsafe location
    TpBypass: 15
    # When set to true adds accept and deny buttons when sending tpa or tpahere requests
    DenyConfirm: true
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in his inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    # Back location will not be triggered if player teleports closer than defined amount of blocks
    BackMinDistance: 5
    # When set to false we will not include teleport location when teleporting around with worldedit compass
    # When set to true we will include each teleport action, even if you simply jumped around with compass
    BackWithWE: true
    # List of worlds to whichones player can't go back with /back command
    BackBlackList:
    - TeztWorldz
```
