### ISSUE TITLE
enchant help

### ISSUE THREAD

**Issue by alex339122** [Zrips/CMI#3833]
when I write - cmi give player stick e knockback:5, the player gets just a stick, without enchantment, how to solve this problem?

4 hours I searched for a problem when I deleted the ProtocolLib plugin, everything worked correctly, but this plugin can't be replaced with another one .. Maybe I'm doing something wrong, waiting for help!  (google translate)

**Comment by variananora** [comment]
What is your server are you using, what version and CMI version?
Try to update your ProtocolLib to the dev build, see if it helps.

**Comment by CloudeLecaw** [comment]
your using the command wrong
this is how to use it
```
cmi give [playerName] stick 1 {StoredEnchantments:[{id:knochback,lvl:5}]}
```

**Comment by alex339122** [comment]
CMI8.6.26.2
ProtocolLib 4.5.1
Paperspigot 1.12.2

I recorded a video - https://www.youtube.com/watch?v=iwIR1GDLhPU&feature=youtu.be 

If I give myself an op, the enchants works, but I need to have regular players work the enchantments
(google translate)

maybe I need permission to access the enchants?

**Comment by CloudeLecaw** [comment]
why usning the old CMI8.6.26.2? pls try with latest 8.7.4.0 mayb its fixed since along time

**Comment by alex339122** [comment]
the problem is solved! I have an itemfixer plugin, I had to give itemfixer permission.bypass.enchant enchant for players.

**Comment by CloudeLecaw** [comment]
your video is showing me your disabling enchants just by the way dont block them

**Comment by CloudeLecaw** [comment]
you have two possible ways.
- first the enchant is disabled - then you need to look into disabledEnchants.yml
- secound possibillity - the enchant is limited - then you need to look in the config here:
```
Enchanting:
  enchantLimits:
    # By disabling this, no limitation to enchanting will be applied
    # This only applies for enchant command not for natural enchanting
    Enabled: true
    MaxLevel:
      protection_fire: 4
      damage_all: 5
      arrow_fire: 1
      soul_speed: 3
      water_worker: 1
      arrow_knockback: 2
      loyalty: 3
      depth_strider: 3
      glow: 10
      vanishing_curse: 1
      durability: 3
      knockback: 2
      luck: 3
      binding_curse: 1
      loot_bonus_blocks: 3
      protection_environmental: 4
      dig_speed: 5
      mending: 1
      frost_walker: 2
      lure: 3
      loot_bonus_mobs: 3
      piercing: 4
      protection_explosions: 4
      damage_undead: 5
      multishot: 1
      fire_aspect: 2
      channeling: 1
      sweeping_edge: 3
      thorns: 3
      damage_arthropods: 5
      oxygen: 3
      riptide: 3
      silk_touch: 1
      quick_charge: 3
      protection_projectile: 4
      impaling: 5
      protection_fall: 4
      arrow_damage: 5
      arrow_infinite: 1
  # When set to true, players will be required to have cmi.enchantments.[enchantname] permission node
  RequireSpecificPermission: false
  # When set to true, players will be required to have cmi.enchantments.[enchantname].[maxlevel] permission node to be abble to enchant item to defined max level
  # Higest permission will be taken if player has more then one
  # Keep in mind that this will not prevent player from enchanting item to lower levels then permission was set too
  # And keep in mind that players without defined permission node will have access to level 1 enchants by default
  PermissionLevelLimit: false
```
