### ISSUE TITLE
cmi setspawn -w:worldname issue

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/CMI#3842]
**Description of issue:**
With multiple worlds (Multiverse):
`/cmi setspawn -w:worldname` 
does not add an entry for the world in the config.yml.
Based on the description of the command, players should be able to respawn in the world they die in if the setspawn defines the spawn location. I have done setspawn for 4 different worlds. Hub (Main spawn point if none other are found), then one for each overworld. 

Below config section is what was created, at no time did I do /setspawn with -g:groupname
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Spawn:
  # Forces players to login in defined spawn point when logging into server
  SpawnOnJoin: false
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  Main:
    World: None
    X: 0.0
    Y: 0.0
    Z: 0.0
    Pitch: 0.0
    Yaw: 0.0
    RespawnLocation: false
    Rng: 0
  Groups:
    CMISWG56281:
      World: Cyber_District1
      X: 211.49788026307445
      Y: 154.0
      Z: -190.51052691612486
      Pitch: 1.4999876
      Yaw: 90.43001
      RespawnLocation: false
      TeleportFrom:
      - Cyber_District
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    World: Hub
    X: 547.5625594480335
    Y: 63.0
    Z: 559.5043593886886
    Pitch: -1.0909148
    Yaw: -89.986084
```

---

**Cmi Version (using`/cmi version`):** 
8.7.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-spigot=9639cf7-7c03d25 (MC: 1.16.1)
**Relevant plugins (Delete if this isn't needed):**
CMI, Multiverse
