### ISSUE TITLE
CMI search not displaying pages beyond 1

### ISSUE THREAD

**Issue by Nelythia** [Zrips/CMI#388]
Description of issue or feature request:

The /cmi search command provides a list of players holding the item you searched for, however does not display any page beyond 1.
I can click on "Next page" but nothing happens, while the console still says " Naulii issued server command: /cmi search list 2 ".

There are 4 pages of players having the queried item, in this case beacons.
Command issued to query was " /cmi search id 138 "

CONFIG SECTION
```
scan:
  # Tps cap from which to start adjusting scan speed
  SoftCap: 14.0
  # Staring speed when scanning. Range from 1 to 30
  DefaultSpeed: 15
  # When this set to true, when using scan feature and not providing range, whole map will be scanned
  GlobalRangeByDefault: false
  # Range in chunks. 2 is 25 chunks, 1 is 9 and 0 is only chunk you are standing in
  DefaultRange: 2
  # When this set to true, all found items in containers will be removed automaticaly durring scan. Ex: /scan id 7 purge
  EnablePurge: false
search:
  # When this set to true, all found items in inventories will be deleted durring search. Ex: /cmi search id 7 purge
  EnablePurge: false
```

Cmi Version (using`/cmi version`): 7.7.1.2
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2-R0.1
