### ISSUE TITLE
Ranks module lagging

### ISSUE THREAD

**Issue by ipozow** [Zrips/CMI#3880]
**Description of issue:**
The ranks module is lagging, I think that the lag was introduced near CMI 8.7. CMI 8.6.20.8 was working fine without lag. 
CMI::Task: com.Zrips.CMI.Modules.Ranks.RankManager$2 (interval:1200) count(8)  total(1.10% 10.552s, 2.61% of tick)avg(1,319.03ms per - 1.31ms/0.00 per tick [here are the timings](https://timings.aikar.co/?id=73a72a8d176d410a897aae99d7c125e8)

---

**Cmi Version (using`/cmi version`):** 
<img width="588" alt="Captura de Pantalla 2020-08-03 a la(s) 15 50 24" src="https://user-images.githubusercontent.com/10505413/89221300-0e06d080-d5a1-11ea-9d12-db098afd27fb.png">
8.7.5.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
paper 1.13.2 build 655

**Comment by Zrips** [comment]
It depends what you have set as requirements. Some checks could introduce some extra load, so we need to determine which action in particular effects this. Could you give some examples of your ranks?

**Comment by ipozow** [comment]
```
Jugador:
  Enabled: true
  DisplayName: '&7Jugador'
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Miembro
Miembro:
  Enabled: true
  DisplayName: '&3Miembro'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - broadcast! &6[playerDisplayName] &eahora es Miembro
  - permissionsex:pex promote [playerName]
  StatsRequirements:
  - PlayTime:86400
  - travel:10000
  Votes: 6
  NextRanks:
  - Heroe
Heroe:
  Enabled: true
  DisplayName: '&9Héroe'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - broadcast! &6¡[playerDisplayName] &e ahora es héroe!
  - permissionsex:pex promote [playerName]
  StatsRequirements:
  - PlayTime:432000
  Votes: 48
  NextRanks:
  - Curtido
Curtido:
  Enabled: true
  DisplayName: '&5Curtido'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - broadcast! &6¡[playerDisplayName] &eahora es curtido!
  - permissionsex:pex promote [playerName]
  StatsRequirements:
  - PlayTime:1080000
  Votes: 148
  NextRanks:
  - Decano
Decano:
  Enabled: true
  DisplayName: '&6Decano'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - broadcast! &6¡[playerDisplayName] &eahora es decano!
  - permissionsex:pex promote [playerName]
  StatsRequirements:
  - PlayTime:1944000
  Votes: 248
Premium:
  Enabled: true
  DisplayName: '&bPremium'
```

**Comment by Zrips** [comment]
Found a place which could have been causing this performance loss, will update code and you can test out new version which will be released today, if issue persists, let me know.

**Comment by ipozow** [comment]
issue persists

**Comment by Zrips** [comment]
Show me new timings

**Comment by ipozow** [comment]
https://timings.aikar.co/?id=5a3f226760a44cc5aa979b9c908f041c
<img width="1413" alt="Captura de Pantalla 2020-08-04 a la(s) 14 09 05" src="https://user-images.githubusercontent.com/10505413/89328910-12dc8a80-d65c-11ea-899a-2625895bdb80.png">
but I have to say that with the fixed version (8.7.5.3) the CPU usage got back to normal

**Comment by Zrips** [comment]
How many players you had online?

**Comment by ipozow** [comment]
since the timings started like 40 and like 70 at the end

**Comment by Zrips** [comment]
Doing some testing. In general you could try switching into async rankup check method if that will not cause any issues then it will resolve extra load you are getting. But will do some testing, maybe we can optimize something extra on it

**Comment by Zrips** [comment]
Ok, did some extra optimization, wait for new version and test it out.

**Comment by ipozow** [comment]
well, it's still lagging, this was the in the version released the day this ticket was closed: https://timings.aikar.co/?id=8cb73fc9697a4b73aeddd19c28415697
and this is with latest (8.7.5.8) https://timings.aikar.co/?id=8d8f2e213a944df48701af9ee24c8aea
<img width="1373" alt="Captura de Pantalla 2020-08-10 a la(s) 20 50 06" src="https://user-images.githubusercontent.com/10505413/89844924-15068380-db4b-11ea-9d09-6b752a39e294.png">

**Comment by Zrips** [comment]
I will need entire config section from config.yml file related to ranks

**Comment by ipozow** [comment]
```
Ranks:
  AutoRankUp:
    # Defines how often in seconds plugin will check for possible player rankups
    # Set it to 0 or less to disable auto rankup checks
    Delay: 60
    # EXPERIMENTAL. When set to true, player rankup checks will be done in async mode
    # In case of errors related to this feature being turned on, turn it off and report issue with error log to github
    Async: false
    # Defines how often in seconds each separate player will be checked for rankup
    # This is different than general check just to avoid couple players ranking up at same time
    # This also defines how often player will be notified about possible rankup and it will proportionaly increase with each time player get notification to avoid annoying spam in chat
    # Keep it longer or same as general delay time
    PlayerDelay: 120
    # Enable or disable progression bar in rank info window
    progressBar: false
  # When set to true, command /cmi ranklist will output ranks from your rankup path which will exclude any rank from different paths or different rankup trees all together
  # When set to false, all set ranks will be shown in the list
  ListSamePathOnly: false
  EffectUp: GColumn
  # When set to true requirements which involve time will be shown in short format like '50 hours' instead of '2 days 2 hours'
  OnlyHours: false
  # When OnlyHours set to true you can add minutes to the output message instead of showing fractions. So you can have '5 hours 30 minutes' instead of 5.5hours'
  includeMinutes: true
```
Now I will be trying Async true
