### ISSUE TITLE
Bug kit ?

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3899]
Hello, several months ago, I created kits with CMI but I had a problem. When one player took a kit, another player received the kit items unlimited, it crashed the server.

Today, I wanted to try again but in the console, it puts the same message when I got the bug : https://ibb.co/XkmJC7M
(Image translation: Unable to find a player with this nickname) 

Here is my setup of a single kit :

```
Aventurier:
  CommandName: Aventurier
  Enabled: true
  DropOnGround: false
  ShowDespiteWeight: false
  Delay: 86400
  MaxUsages: -1
  Icon:
    ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: CHAINMAIL_CHESTPLATE
  IconOff:
    ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: CHAINMAIL_CHESTPLATE
  Slot: 22
  Commands:
  - cmi kit Aventurier {USERNAME} 1
  Group: Aventurier
  Items:
    '4':
      v: 2567
      type: LEATHER_CHESTPLATE
    '5':
      v: 2567
      type: IRON_LEGGINGS
    '6':
      v: 2567
      type: IRON_BOOTS
    '7':
      v: 2567
      type: COOKED_BEEF
      amount: 12
    '13':
      v: 2567
      type: IRON_SWORD
    '14':
      v: 2567
      type: IRON_AXE
    '15':
      v: 2567
      type: IRON_PICKAXE
    '23':
      v: 2567
      type: BREAD
      amount: 10
```

Did I set it up wrong or is it a bug in the plugin ?
