### ISSUE TITLE
finished one

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3910]
```
Sell64:
  Locations:
  - world;400.0;77.0;518.0
  - world;-34.0;65.0;325.0
  Commands:
  - hasitem:emerald-64! msg! [playerName] &fDu hast &a&l64 Smaragde&7 für &e&l64 Taler&f
    verkauft.
  - item:emerald-64#! cmi money give [playerName] 64 -s
  - msg! [playerName] &fDein neuer Kontostand ist &e&l%cmi_user_balance_formatted%&f.
  SignLines:
  - '&lVerkaufen:'
  - '&a&lSmaragde 64'
  - '&lErhalte:'
  - '&6&l64 Taler'
  Public: true
  ReqPerm: false

```
![image](https://user-images.githubusercontent.com/12080017/89719470-f2e4f800-d9c8-11ea-9208-317552d24e26.png)

since last version of CMI if you klick the sign where it is attached to "pay" X item to executea command just ONE of the materials is taken even if you have the right amount.
This was working beofre fine!
So in this case you normaly need 64 emeralds to execute the command that is on the sign.
It checks correct if you have 64 emeralds and stops if you dont have 64 anymore
but if you have the 64 then it just takes one.  So when you have lets say 163 emeralds
you can exevute the command 100 times )instead of just 2 times)
and you become 6400$ instead of 128$ this way... 
and if you have signs where u can buy 64 emeralds for 64$
and then run to the "bugged" sellsign...i aspect you become cheatet millionaere withing a few minutes

i just hope this can be fixed soon

![image](https://user-images.githubusercontent.com/12080017/89719458-c4ffb380-d9c8-11ea-9c92-ba751acbd326.png)

Edit: No changes with 8.7.5.8 - issues still exists
