### ISSUE TITLE
DiscordSRV Chat Hook pulls from all chats listed in the DiscordSRV config

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#3922]
**Description of issue:**
When you have multiple channels setup in the DiscordSRV config, CMI will pull all messages sent to any Discord Channel listed in the config. This poses problems when using other DiscordSRV channel hooks, such as a Staff Chat that links in-game to discord and vice versa. 

---
**CONFIG SECTION:**
_CMI Config Section_
```
DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'
    UnlinkedLabel: '&4[&cD&4]'
```
_DiscordSRV Config Section_
```
Channels: {"global": "xxxxxxxxxxxxxxxxxx", "staff-chat": "xxxxxxxxxxxxxxxxxx"}
```

---

**Cmi Version (using`/cmi version`):** 
8.7.5.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.16.1 Paper-133

**Relevant plugins (Delete if this isn't needed):**
DiscordSRV
DiscordSRV Staff Chat
