### ISSUE TITLE
bug with cmi money give

### ISSUE THREAD

**Issue by SlothSetups** [Zrips/CMI#3931]
**Description of issue:**

doing this with mythicmobs, worked perfectly fine on 8.7.5.5 then on all versions after that it just shows the default thing when u type /money give

  #- command{c="ifonline <trigger.name> money give <trigger.name> %rand/100-1000%"} ~onDeath

**Cmi Version (using`/cmi version`):**   BROKEN ON 8.7.5.6 / 8.7.5.7 / 8.7.5.8

**Server Type (Spigot/Paperspigot/etc):**  tuinity 1.16.1

**Server Version (using `/ver`):**   tuinity 1.16.1

**Comment by Zrips** [comment]
For future reference, i'm not familiar with every single plugin out there. Some extra information how and where this should be used could be provided to avoid time waste in trying to figure out how particular plugin works and spend an hour looking around it where i should use this specific setup and where to test it.

**Comment by Zrips** [comment]
If we are talking about setup like
```
SkeletalMinion:
  Type: SKELETON
  Display: '&2Skeletal Minion'
  Health: 10
  Damage: 2
  Skills:
  - command{c="ifonline <trigger.name> money give <trigger.name> %rand/100-1000%"} ~onDeath
  Options:
    MovementSpeed: 0.1
```
which works perfectly fine with latest CMI builds and i can get money without any issues after killing mob with a defined random amount. What did i missed here? 
And just wondering here, did you commented out command line because it dint worked or you accidentally commented it out and this was the cause of your issue? As i can see # in your provided example.
