### ISSUE TITLE
If TimeSpeed activated world not frozen

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#3959]
**Description of issue:**

If the 'TimeSpeed' of a world is activated, when the 'cmi time freeze' command is used the time is not frozen.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
##   # Allows you to change vanilla time speed to your own liking and needs
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 1200
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 180
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 180
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time  ##
#######################################
```

-----------------------
**CMI Version: 8.7.6.0**
**Server Type: PaperMC**
**Server Version: 1.16.1 #134**
**Vault Version: 1.7.3**
