### ISSUE TITLE
DiscordSRV hook appears to function differently now

### ISSUE THREAD

**Issue by e101stella** [Zrips/CMI#3972]
**Description of issue:**
Since updating to CMI 8.7.6.0 the DiscordSRV hook no longer appears to work in the same manner. Previously it would modify chat to look like CMI chat formatting, now it just reverts back to our default DiscordSRV formatting. From what I can see in the DiscordSRV debug info (included below), CMI doesn't seem to be cancelling the DiscordGuildMessagePreProcessEvent in 8.7.6.0 possibly linked to the change in how the global channel is newly defined. It's also interesting to note that DiscordSRV doesn't recognise CMI as a Chat Hook

---
**DiscordSRV Debug Info**:
CMI 8.7.5.8: https://bin.scarsz.me/da003a3d-8143-4a35-9419-7b5bb61820a2#87RuEEmae10QShOGkQtwf0oA2GZ4TPWW
CMI 8.7.6.0: https://bin.scarsz.me/cd328b95-b8f5-4332-9bea-01a00817491b#TKCW8aSPw32ioBJwFoERYpOKlujvXSJH

**Chat Difference**:
CMI 8.7.5.8:
![Screenshot_1](https://user-images.githubusercontent.com/37426292/90307051-65e4f600-df16-11ea-8901-dd7a8e95bc5f.png)
CMI 8.7.6.0: 
![image](https://user-images.githubusercontent.com/37426292/90307043-59f93400-df16-11ea-91f9-ffde586f3994.png)

**CONFIG SECTION:**
CMI Config
```
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Defines name of global chat channel in discordsrv
    GlobalChannel: global
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'
    UnlinkedLabel: '&4[&cD&4]'
```
DiscordSRV Config
```
# Channel links from game to Discord
# syntax is Channels: {"in-game channel name": "numerical channel ID from Discord", "another in-game channel name": "another numerical channel ID from Discord"}
# The first channel pair specified in this config option will be the "main" channel, used for sending player joins/quits/deaths/achievements/etc
#
Channels: {"global": "693951688234762241", "staff-chat": "671486668473106453"}

# Console channel numerical ID (NOT NAME), leave blank to disable the console channel all together
DiscordConsoleChannelId: "671481756578349115"
```
---

**Cmi Version (using`/cmi version`):** 8.7.6.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.16.1 Paper-135

**Relevant plugins (Delete if this isn't needed):** DiscordSRV
