### ISSUE TITLE
Prefix placeholder not accurate

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#3991]
**Description of issue:**
Prefix for luckperms group isn't accurate in the latest CMI build.
This happens if there's 2 group, and I use the stacking option for prefix in CMI
![image](https://user-images.githubusercontent.com/26654664/90340033-6ddc8d00-e01f-11ea-9d3b-25bdfa09ec8f.png)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Luckperms Config: https://paste.md-5.net/nakunozuve.shell
CMI Config: https://paste.md-5.net/godavojuwa.coffeescript

---

**Cmi Version (using`/cmi version`):** 8.7.6.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot #354

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):** LuckPerms-Bukkit-5.1.93

**Comment by CloudeLecaw** [comment]
```
  # Used for simple chat messages. Optional variables: {displayName} {world} {prefix} {suffix} {group} {shout} {message}. Supporting PlaceHolderAPI variables like %player_server%
  GeneralFormat: '{prefix} {displayName}&f: &r{message}'
  # Will define message format itself, this allows to have gradients in messages
  # It NEEDS to contain {message} otherwise we will ignore this setup
  # For 1.16+ servers you can use color gradients like '{#b3a28f>}{message}{#d7b8e6<}'
  # You can have more than 2 colors in gradient. To define it repeat {message} variable. For example '{#b3a28f>}{message}{#5c6999<>}{message}{#d7b8e6<}'
  GeneralMessageFormat: '{message}'
  # Defines range of regular messages to travel
  # Set to -1 to disable range restriction
  GeneralRange: -1
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.chat.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
  # Prefix used to idicate that message should be sent to public chat instead of current players chat room
  # Set it to empty field if you want this feature to be disabled
  ChatRoomShout: '!'
  # Time in seconds you want to keep chat rooms alive before removing them
  # This only applies to empty rooms after last user leaves it
  ChatRoomLife: 3600
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  # Permission example: cmi.chatgroup.2
  GroupFormat:
    '1': '{prefix} {displayName}&f: &r{message}'
    '2': '{prefix} {displayName}&7: &r{message}'
    '3': '{prefix} {displayName}&8: &r{message}'
```
maybe its luckperms?
mybe its CMI?
you have said prefix maybe CMI has a problem here?
look at your chat format...
You are not using CMI-Chat
look in the config u posted..
Look on your Screenshot and your config
`'{prefix} {displayName}&f: &r{message}'`
`֍] - Blegdigits: Hello`
**This is not what we see in your screenshot**
![](https://user-images.githubusercontent.com/26654664/90340033-6ddc8d00-e01f-11ea-9d3b-25bdfa09ec8f.png)

So i say this is not CMI related
