### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#3995]
Ok, im pretty sure that im just messing this up, but for the life of me i cannot seem to get the bit that is supposed to replace words in someones message to different words.

I tried to copy the already done filters, and make a `swearing3`.

Im trying to get it to change `:)` to `☺`
Once i get this down, and under stand how it works, i also wanna change `<3` to `&c♥&r`, and `=D` to `☻`

Im 99.999% sure the regex bit is where im messing it up, because i replaced the f-word filter to say `☺` and it works just fine.
Can anyone help me out?

Here is the attempt at regex i did:
```
      swearing3:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - /:[\)]/igm
        ReplaceWith: SomeTextPlzWork
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
```

Here is the full config for the relevant section (around line 760 in my config):

```
        msgToStaff: '&4!&6[playerName] &4advertising with: &r[message]'
        # List of commands to perform when rule is broken. Use [senderName] to include message sender name. Supports global variales same as locale file
        Commands: []
      swearing1:
        Enabled: false
        Group: Swearing
        InformConsole: true
        Regex:
        - \bass\b|\basshole
        ReplaceWith: dude
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
      swearing2:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_)*(u?)+(\W|_)*(c?)+(\W|_)*k+)
        ReplaceWith: ☺
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
      swearing3:
        Enabled: true
        Group: Swearing
        InformConsole: true
        Regex:
        - /:[\)]/igm
        ReplaceWith: SomeTextPlzWork
        BlockType: none
        msgToStaff: '&4!&6[playerName] &4swearing'
        Commands:
        - msg [senderName] &eDon't swear!
    # List of regex filter to exlude from block list. Usefull if you want to block all ip/host address but want to allow usage of your own server.
    WhiteList:
    - \bgoogle.\s?([a-zA-Z]{2,4})\b
    - \bspigotmc.\s?([a-zA-Z]{2,4})\b
    DuplicatedMessagePrevention:
      # When set to true, plugin will prevent spaming of same or similar messages in short time range. Can be bypased with cmi.chatfilter.spambypass permission
      Use: false
      # How much in percentage message is counted as same
      Percentage: 80
      # Defines how often in seconds you can send same/similar message
      Interval: 5
      # How many commands you can repeat before stopped for cooldown
      MinAmount: 2
  # If set to true, players public message who is in your ignore list will not be shown
```

I used https://www.regextester.com/ to try and 'build' the regex, and on the website it seems to look like itll work (see the pic attached), but dosent seem to work ingame.
<img width="806" alt="asdfasdfasdf" src="https://user-images.githubusercontent.com/68966344/90367518-8dc77d00-e02e-11ea-9340-bbc3cf19d4d9.PNG">

**Comment by CloudeLecaw** [comment]
easy one^^

**Comment by MrMcyeet** [comment]
Absolute legend my man!
Tysm!


I went and drew up a bunch of em, feel free to yoink them if ya wanna

```
      smile1:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \:\)
        ReplaceWith: ☺
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile2:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \<3
        ReplaceWith: '&c❤&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile3:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \-\>
        ReplaceWith: '→'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile4:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \<\-
        ReplaceWith: '←'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile5:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - 3\/4
        ReplaceWith: '¾'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile6:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(r\)
        ReplaceWith: '®'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile7:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(tm\)
        ReplaceWith: '™'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile8:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \=D
        ReplaceWith: '☻'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile9:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(sm\)
        ReplaceWith: '☃'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile10:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - x\.x
        ReplaceWith: '☠'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile11:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(\*\)
        ReplaceWith: '&e✪&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile12:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \=\)
        ReplaceWith: 'ツ'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile13:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - 1\/2
        ReplaceWith: '½'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile14:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - 1\/4
        ReplaceWith: '¼'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile15:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \:\(
        ReplaceWith: '☹'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile16:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(v\)
        ReplaceWith: '&a✔&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
      smile17:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \(x\)
        ReplaceWith: '&c✕&r'
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
```

Here is a picture of a few i made, the only one that isnt in the pic is `:) to ☺`
![InkedInked2020-08-17_04 21 24_LI](https://user-images.githubusercontent.com/68966344/90382337-3df3b080-e044-11ea-8e3c-c0f2b12b2644.jpg)
