### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3996]
Hello, is it possible to put an option to keep the fly activated even when a player logs out and reconnects to the server?

**Comment by CloudeLecaw** [comment]
Check the worldlimits

```
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: false
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - world:Survival
  - Creativ:Creative
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world: true
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoof: false
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoofLimitations:
  - world-256
  - world_nether-128
  - world_the_end-256
  # If player will have cmi.worldlimit.god.bypass permission node, fly mode wont be changed
  GodMode:
  - world:False
  # Prevents particular entity spawn reasons in defined worlds. All possible reasons: NATURAL, JOCKEY, CHUNK_GEN, SPAWNER, EGG, SPAWNER_EGG, LIGHTNING, BUILD_SNOWMAN, BUILD_IRONGOLEM, BUILD_WITHER, VILLAGE_DEFENSE, VILLAGE_INVASION, BREEDING, SLIME_SPLIT, REINFORCEMENTS, NETHER_PORTAL, DISPENSE_EGG, INFECTION, CURED, OCELOT_BABY, SILVERFISH_BLOCK, MOUNT, TRAP, ENDER_PEARL, SHOULDER_ENTITY, DROWNED, SHEARED, EXPLOSION, RAID, PATROL, BEEHIVE, CUSTOM, DEFAULT
  SpawnReasons:
    world:
    - BUILD_WITHER
    world_nether:
    - BUILD_WITHER
    world_the_end:
    - BUILD_WITHER
# Checks and shows on players login if he have been changed hes name over Mojang
# Looks to be working only with online servers, duhhhh
```

if all is right there in the flly sections then its not CMI

Cmi doies not disbale fly on logout if you have not setted it up for world limits
this can be 3rd plugin like Playerinventories or Multiworld , or other..
check this without any othersplugins installed you would see it will not disable
