### ISSUE TITLE
Schedule using days broken

### ISSUE THREAD

**Issue by HeartlessAUS** [Zrips/CMI#4005]
**Description of issue:**
```
Scheduler days are broken, it ignores the day and rather shoots them all at the time set

[Tue, 18. Aug 2020 00:20:00 UTC INFO] [LP] Set mcmmo.perks.xp.double.all to true for default (bacon) for a duration of 1 day in context global.
[Tue, 18. Aug 2020 00:20:00 UTC INFO] [LP] Set mcmmo.perks.xp.triple.all to true for default (bacon) for a duration of 2 days in context global.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
HumpDayXpRate:
  Enabled: true
  FeedBack: true
  Repeat: true
  PerformOn:
    '1':
      day: Wednesday
      Hour: 0
      Minute: 20
      Second: 0
  Commands:
  - lp group default permission settemp mcmmo.perks.xp.double.all true 1d
  - titlemsg all &8&l[&6MCMM0&8&l] &rIt's Hump day! \n &ax2 &6MCMMO XP -in:20 -out:20
    -keep:80
WeekendXpRate:
  Enabled: true
  FeedBack: true
  Repeat: true
  PerformOn:
    '1':
      Day: Saturday
      Hour: 0
      Minute: 20
      Second: 0
  Commands:
  - lp group default permission settemp mcmmo.perks.xp.triple.all true 2d
  - titlemsg all &8&l[&6MCMM0&8&l] &rIt's the weekend! \n &ax3 &6MCMMO XP -in:20 -out:20
    -keep:80
```

---

**Cmi Version (using`/cmi version`):** 8.7.5.8

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot

**Server Version (using `/ver`):** git-Paper-133 (MC: 1.16.1)
