### ISSUE TITLE
Afk [reason] needed to work in commands

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/CMI#4008]
**Description of feature/improvement request:**
Example use in config.yml in the AFK section:
```
  ManualAfkCmds:
  - eafk [playerName] [reason]
```
As certain things depend upon letting essentials know of the user's AFK status, I can't disable their system.  As CMI's player rewards and other things are supposed to act differently when a player is in afk and cmi doesn't acknowledge essential's afk status, I have to keep both enabled and have one talk to the other.  The downside of this appears to only be with the AFK reason, when it is provided.  While essentials has two different AFK messages... one with a reason and one without... CMI only includes one, and the only demonstration of the use of "[reason]" in the language file... of course doesn't work in the config file so if I use it there it simple gives "[reason]" as the reason instead of the text entered ("$1-" in the alias or "{1}" in essentials).

This is the only hitch I have using this seamlessly with other plugins, please address asap.

**Comment by CloudeLecaw** [comment]
HANDS UP FOR AFK REASONS! I also wanne se them in the /afk command
we also should be able to define a default reason if no reason is seted (can be left blank if none wanted ("")

So pls add this for the /afk responce meassge <3

**Comment by mrcoffee1026** [comment]
I did happen to manage a workaround  by doubling up the commands in the alias editor and doing:

```
  afk:
    Cmds:
    - cmi afk $1-
    - eafk $1-
```
Which will continue to operate as expected even if this feature is eventually added later.  Note that: currently CMI does support the reason argument within the afk command, it's just only displaying it in one fairly difficult to get to location.

**Comment by mrfloris** [comment]
```yaml
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&6 * &l[playerDisplayName]&r &ehas gone AFK &7(Automatically)
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi broadcast !&6 * &l[playerDisplayName]&r &ehas gone AFK &7(%cmi_user_afk_msg%)
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - 'cmi ctellraw all <T>&6 * &l[playerDisplayName] &ehas returned from AFK &7(%cmi_user_afk_msg%)</T><H>&7Has
    been away for: %cmi_user_afk_for%</H>'
```
```
%cmi_user_afk_msg%
%cmi_user_afk_for%
```
