### ISSUE TITLE
My player lost elytra due to message repair cantUse

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4013]
**Description of issue:**

---
Hi, one of my player told me that she bought elytra from one player. It was 2 weeks ago and today she put this elytra into chest, she didn't do it before. When she tried to pick it back, then cantUse message from repair(share prob.) appeared. But I don't know, when I have it disabled, and why elytra disappeared from her inventory (after picking from chest again), when it wasn't damaged (she told me that it was like new? With enchants mending and unbreaking 3)? Could you try check code if something like this can happen?

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ItemRepair:
  RepairShare:
    # When neabling you will need to perform full server restart for it to take effect
    # When enabled will prevent players repairing items for others in anvil regular way. They still can use items and repairs normaly for them selfs
    # Can be bypassed with cmi.command.repair.repairshare.bypass
    ProtectNormalRepair: false
    # When enabled will prevent players repairing items for others with CMI command. They still can use items and repairs normaly for them selfs
    ProtectCommandRepair: true
    # Sets durability on item when another picks it up or selects in inventory. Set to 0 or less if you don't want to change durability
    Durability: 0
    # When set to true, player who have cmi.command.repair permission will bypass this protection and can use other user repaired items without any additional actions
    BypassWithRepairPermission: false
    # When enabled additional lore line will be added when player can't use that item. This will not be shown for owner of item
    AddLore: true
    # When set to true, interact event will be canceled to prevent item usage
    CancelEvent: true
    # When set to true, player will get message informing about item usage he dint repaired him self
    InformWithMessage: true
```

---

**Cmi Version (using`/cmi version`):** 8.7.6.3

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 136
