### ISSUE TITLE
Socialspy/commandspy weirdness

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4047]
Ok, so its been going on for a decent minute, and i thought i was gonna take a little bit of time to try and fix it, but i CANNOT for the life of me find the source of this double message weirdness.

![Inked2020-08-22_16 16 32_LI](https://user-images.githubusercontent.com/68966344/90966044-a94de000-e493-11ea-96eb-1a7f1951fb1d.jpg)

What you see right there is player jao_ozaki doing `/r I feel that`(1) then user RcieOktgieke doing `/msg jao keep it real bro`(2)

And the weird part is where i have the pink `1` and `2` drawn. Even with (cmi)Commandspy off AND (cmi)Socialspy off the `[[playername]]` messages still show up, and i have tried EVERYTHING i can think of to try and fix it.

Anyone know why they pop up, and how to make it stop?

EDIT: i saw here (https://github.com/Zrips/CMI/issues/81) that zrips said that what the [[Playername]] weirdness is `your locale settup for command spy format`. But im like 99% sure this isnt the case for me, as i previously had used a different plugin for commandspy, and had set the `translations > Locale_EN > Commandspy > Info > Command` to just `command: ''`
Since then ive started using cmi's commandspy/socialspy though.

Not sure if itll help, but here is the commandspy part of my config

```
Command:
  CommandFilter:
    Duplicate:
      # When set to true, plugin will prevent spaming of same or similar command in short time range. Can be bypased with cmi.commandfilter.bypass permission
      Use: false
      # How much in percentage command is counted as same
      Percentage: 80
      # Defines how often in seconds you can send same/similar commands
      Interval: 5
      # How many commands you can repeat before stopped for cooldown
      MinAmount: 2
      # Whitelisted commands to ignore
      WhiteList:
      - msg
      - tell
      - login
      - register
  Spy:
    # Commands in this list will not be shown when command spy is enabled for player for security/privacy reasons
    # This can be bypassed with cmi.command.commandspy.bypass permission node
    BlackListed:
    - register
    - login
    - l
    - r
    - msg
    - reply
    - cmi msg
    - cmi reply
    # Players without cmi.security.admin will only see commands from this list with command spy feature
    CommandList:
    - cmi spawn
    - cmi tp
    - cmi tpa
    - cmi heal
    - cmi feed
    - cmi fly
```

And here is the commandspy part of my `Locale_EN`

```
commandspy:
    help:
      info: '&eToggle command spy'
      args: (playerName) (-s)
      explanation:
      - cmi.command.commandspy.hide - Hides performed commands from commandspy
    info:
      command: '&e>> &7[senderName]&e:&7 [command]'
      toggled: '&eCommand spy toggled to &6[state] &estate'
```

And here is the commandspy part of my `Locale_EN`

```
  socialspy:
    help:
      info: '&eToggle social spy'
      args: (playerName)
    info:
      msg: '&9>>&7[senderName] &9→ &7[playerName]&9&l:&r &7[message]'
      custom: socialspy > info > custom text here
      toggled: '&eSocial spy toggled to &6[state] &estate'
```
