### ISSUE TITLE
/sit allows emergency teleport

### ISSUE THREAD

**Issue by mindw0rm** [Zrips/CMI#4087]
Sitting allows the player to enter a state where sneaking will teleport him back to the sit location.

To reproduce:
* sneak  (hold the sneak key pressed)
* sit down somewhere -> you immediately stand up again, with the corresponding message
* sit down again -> you immediately stand up again, but there is only the mesage that you sat down and need to sneak to stand up
* release the sneak key
* walk somewhere else
* press sneak again -> you get teleported to the location where you sat down, showing the message that you are no longer sitting

The bug won't work after teleporting in any way.

---

**CONFIG SECTION:** (don't know if relevant, doesn't seem so)
```
Animations:
  # Enable siting on stair block by clicking on them with empty hand or by looking and using command
  # Requires cmi.command.sit.stairs
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: false
  RemoveFromChairOnDamage: true
  # Player will sit on chair only after rapid double click
  DoubleClick: false
  # Delay in milliseconds between clicks to sit on chair when double click is enabled
  DoubleClickDelay: 200
  # Range in blocks from player to look up for valid chair block
  ChairRange: 2
```

---

**Cmi Version (using`/cmi version`) 8.7.6.7:** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**
