### ISSUE TITLE
NetherPortal disable does not work

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#4091]
CMI:  8.7.6.7
Paper: Paper version git-Paper-148 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

Users can create Nether portals even though it is deactivated in the config

```
NetherPortal:
   #Can prevent nether portal creation entirely. Option to bypass with cmi.netherportalbypass
  PreventCreation: true
   #Maximum height nether portal can be created. Vanilla size is 23
  MaxHeight: 23
   #Maximum width nether portal can be created. Vanilla size is 23
  MaxWidth: 23
```
