### ISSUE TITLE
How do I reset CMI data

### ISSUE THREAD

**Issue by YTMrSnipa** [Zrips/CMI#4092]
How do I reset the CMI Data? I tried deleting folder, everything else, but It just won't reset. I want to reset all the stats of the player like playtime etc.

**Comment by CloudeLecaw** [comment]
some stats are saved in the playerfile in worldfolder.
for a full reset tell your players to save their inventory + Enderchest

Then Delet the CMI Database, in your Mainfolderfolder the subfolders stats, advancements,playerdata

if you want to do this for singleplayers
it recommand to use the remove userfeature r the purge feature
configure ot here before
config.yml
```
purge:
  # Cleans files on server startup
  CleanOnStart: false
  # How long player should be offline for his data to be moved
  OfflineDays: 90
  PlayerData:
    # Do you want to enable player data file cleaning
    Enabled: false
    # Source folder to take files from
    SourceFolder: world/playerdata
    # When this is false, data files will be moved to backup folder. When its true files will be deleted
    DeleteFiles: false
    # Target folder to put files into if DeleteFiles set to false
    DestinationFolder: world/playerdata_backup
  PlayerStats:
    # Do you want to enable player stats file cleaning
    Enabled: false
    # Source folder to take files from
    SourceFolder: world/stats
    # When this is false, data files will be moved to backup folder. When its true files will be deleted
    DeleteFiles: false
    # Target folder to put files into if DeleteFiles set to false
    DestinationFolder: world/stats_backup
  PlayerAdvancements:
    # Do you want to enable player Advancements file cleaning
    Enabled: false
    # Source folder to take files from
    SourceFolder: world/advancements
    # When this is false, data files will be moved to backup folder. When its true files will be deleted
    DeleteFiles: false
    # Target folder to put files into if DeleteFiles set to false
    DestinationFolder: world/advancements_backup
  Essentials:
    # Do you want to enable essentials playerdata file cleaning
    Enabled: false
    # Source folder to take files from
    SourceFolder: plugins\Essentials\userdata
    # When this is false, data files will be moved to backup folder. When its true files will be deleted
    DeleteFiles: false
    # Target folder to put files into if DeleteFiles set to false
    DestinationFolder: plugins\Essentials\userdata_backup
  LWC:
    # Do you want to enable lwc protection cleaning
    Enabled: false
```
this will remove, cmi data, stats, playerfile and archivments from a player
