### ISSUE TITLE
Repeated message on console

### ISSUE THREAD

**Issue by Hazugg** [Zrips/CMI#4107]
The messages are repeated in the console, I have already tried and it is a new configuration of the cmi, could you inform me if it is an error or I have to disable something in the configuration?
![image](https://user-images.githubusercontent.com/31551514/91627955-05779f00-e981-11ea-9955-ae30b2132d07.png)

**Comment by CloudeLecaw** [comment]
Are you using cmi's chat Management?

**Comment by Hazugg** [comment]
Yes, they currently use the cmi chat management, it is my only plugin for the chat, I tried disabling the plugin to see if it was the one that caused the error and so it was, when deactivating it the error does not occur, I re-enable it and it goes back to The same thing happens, only on my servers with this chat plugin it is failing so the console repeats the message and as I had reported that it causes a delay, I don't know if it is an option that I have to deactivate or an error

**Comment by CloudeLecaw** [comment]
could you give us soome more detailed information about server, cmi version and permission plugin your using?
might u want to char your configpart of the chat of your cmi config too? maybe its just a little missconfiguration

**Comment by Hazugg** [comment]
My permission plugin is luckperms, cmi version is current CMI8.7.6.9.
The part that is in red are new configuration added, I do not know if it is due to that, or if there are some more options, since I just noticed that those are new, and my permission node for vips users is only the part blue

![image](https://user-images.githubusercontent.com/31551514/91646395-45d42d00-ea14-11ea-992e-d221ea441dd9.png)

**Comment by CloudeLecaw** [comment]
```
  GeneralFormat: '{prefix}{displayName}&f: &r{message}'
  # Will define message format itself, this allows to have gradients in messages
  # It NEEDS to contain {message} otherwise we will ignore this setup
  # For 1.16+ servers you can use color gradients like '{#b3a28f>}{message}{#d7b8e6<}'
  # You can have more than 2 colors in gradient. To define it repeat {message} variable. For example '{#b3a28f>}{message}{#5c6999<>}{message}{#d7b8e6<}'
  GeneralMessageFormat: '{message}'
  # Defines range of regular messages to travel
  # Set to -1 to disable range restriction
  GeneralRange: -1
  # Defines range of shout messages to travel
  # Shout messages should start with ! and player should have cmi.chat.shout permission
  # GeneralRange should be enabled
  # set to 0 to shout across all worlds, -1 to disable
  ShoutRange: 200
  # Defines cost for each shout message
  ShoutCost: 0
  # Prefix used to idicate that message should be sent to public chat instead of current players chat room
  # Set it to empty field if you want this feature to be disabled
  ChatRoomShout: '!'
  # Time in seconds you want to keep chat rooms alive before removing them
  # This only applies to empty rooms after last user leaves it
  ChatRoomLife: 3600
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  # Permission example: cmi.chatgroup.2
  GroupFormat:
    '1': '{prefix}&f{displayName}&f: &r{message}'
    '2': '{prefix}&f{displayName}&7: &r{message}'
    '3': '{prefix}&f{displayName}&8: &r{message}'
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatmessagegroup.[id] permnission node to use
  # Permission example: cmi.chatmessagegroup.2
  GroupMessageFormat:
    '1': '{message}'
    '2': '{message}'
    '3': '{message}'
```
