### ISSUE TITLE
SelectionVisualizer - Worldborder effect can't be changed

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4116]
It is not possible to change the particle type in the config. No matter what you enter, the default purple particle remain. A Server restart doesn't help.
```

  WorldBorder:
    Area:
      Effect1:
        Effect: flame
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;255;255
        Cap: 200
      Effect2:
        Effect: flame
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;255;255
        Cap: 200
      Effect3:
        Effect: flame
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;255;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 50
      ShowFor: 120000
      ByDefaultIsEnabled: true
```
Paper 1.16.2 - 135
SelectionVisualizer 3.0.2.3
FAWE - 1.16 - 327 (https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
WorldBorder version 1.16 (https://www.spigotmc.org/resources/worldborder-pures-fork.81706/)
