### ISSUE TITLE
Rankup when two branches issue

### ISSUE THREAD

**Issue by DawidSsS** [Zrips/CMI#4118]
After update, CMI (sorry but I don't know exactly from which version of CMI) choose between two branches stopped working.

Before update player had to choose which branch he wants to go.
Now CMI automatically gives him first brunch and second immediately after it. 

Here's my config

```yml
newbie:
  Enabled: true
  DisplayName: '&aKadet'
  DefaultRank: true
  AutoRankup: false
  NextRanks:
  - male
  - female
male:
  Enabled: true
  DisplayName: '&aMale'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Mranga2
  Commands:
  - broadcast! &6[playerDisplayName] &ezostaje chłopem!
female:
  Enabled: true
  DisplayName: '&aFemale'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Kranga2
  Commands:
  - broadcast! &6[playerDisplayName] &ezostaje chłopką!

...
```
