### ISSUE TITLE
Setup question (maybe feature?)

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#412]
Not sure if I'm just dumb or blind but is there a way to set a message on new player join? (Like the essentials "Welcome name to the server!")

**Comment by MCTyler** [comment]
FirstJoin broadcast command?...It's in a file called eventCommands.yml
```
firstJoinServer:
  Use: true
  List:
  - sudo [playerName] /cmi getbook recipes
  - sudo [playerName] /cmi getbook colors
  - sudo [playerName] /cmi getbook rules
joinServer:
  Use: true
  List:
  - sudo [playerName] /cmi rankinfo
```

**Comment by Kbryst** [comment]
Thanks! Totally just derping today

**Comment by CloudeLecaw** [comment]
dont forgete to turn These to true in the cofnig 🗡  if u  just want a measssge.

```
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: false
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: false
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: false
```
This will replace join,quit and firstjoin measge with the once u settet up in the langfile :)
