### ISSUE TITLE
The newest ver error

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4155]
**Description of issue:**

---
Error here.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/zgDw3qEf

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Command section can utilize same custom variables as scheduler. Check schedules.yml file for all possible variables.

SurvivalSpawn:
  End_Portal:
    Loc: 264.0:42.0:19.0:266.0:42.0:21.0
    enabled: true
    effect: largesmoke
    showParticles: true
    safeLoc: world_the_end;128.5;53.0;-0.41;-4.79;76.79
    Tp: world_the_end;128.56;53.1;-0.33;2.25;67.19
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 3
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - asConsole! randomtpadmin [playerName] world_the_end
    - delay! 5
    - ifinworld:world_the_end! asConsole! cmi ctellraw [playerName] <T>&7Byl jsi přemístěn
      do endu! Pro tipy &enajeď &7myší.</T><H>&7Zde můžeš těžit suroviny. \n&7Nedoporučujeme
      ti zde stavět, \n&7jelikož se svět pravidelně restartuje. \n&7Dům si můžeš postavit
      na &e/priroda&7.\n\n &3Klikni pro teleport do přírody.</H><SC>/priroda</SC>
  Nether:
    Loc: 35.0:39.0:7.0:25.0:28.0:7.0
    enabled: true
    effect: lava
    showParticles: true
    Tp: world_nether;28.0;42.3;20.61;-0.07;0.74
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 3
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - asConsole! randomtpadmin [playerName] world_nether
    - delay! 5
    - ifinworld:world_nether! asConsole! cmi ctellraw [playerName] <T>&7Byl jsi přemístěn
      do netheru! Pro tipy &enajeď &7myší.</T><H>&7Zde můžeš těžit suroviny. \n&7Nedoporučujeme
      ti zde stavět, \n&7jelikož se svět pravidelně restartuje. \n&7Dům si můžeš postavit
      na &e/priroda&7.\n\n &3Klikni pro teleport do přírody.</H><SC>/priroda</SC>

```

---

**Cmi Version (using`/cmi version`):** 8.7.6.13

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  git-Paper-179 (MC: 1.16.2)
