### ISSUE TITLE
/colors broken

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4172]
The `/colors` command dosen't format the colors, it just pasts whats in the locale file into chat (see the attached picture) 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
config
```
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      books: true
      # List of strings to ignore when checking chat for color codes player cant use.
      # This will bypass players colorcode restrictions and will allow usage of particular chat formats
      # Applies only for public and private messages
      WhiteList:
      - '&c❤&7'
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true
```

Locale
```
  colors:
    help:
      info: '&eShows all possible colors'
      args: (playerName)
    info:
      List:
      - '&e***************************************'
      - '     &0&%0  &1&%1  &2&%2  &3&%3  &4&%4  &5&%5  &6&%6  &7&%7'
      - '     &8&%8  &9&%9  &a&%a  &b&%b  &c&%c  &d&%d  &e&%e  &f&%f'
      - '       &%k - &kMagic&r      &%l - &lBold'
      - '       &%m - &mStrike&r     &%n - &nUline'
      - '       &%o - &oItalic&r      &%r - &rReset'
      - '&e***************************************'
```

---

**Cmi Version (using`/cmi version`):** 
8.7.6.14

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper version git-Paper-158 (MC:1.16.2) (implementing API version version 1.16.2-R0.1-SNAPSHOT)
![2020-09-06_15 30 08](https://user-images.githubusercontent.com/68966344/92334815-f5358300-f056-11ea-96ba-8c967c32a7b2.png)
