### ISSUE TITLE
What does MYSQL do with the CMI skins?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4210]
Skins just gets updated once each serverstart + The Admins need to use the skinupdate command.
After one change they get not updated anymore.

On Login you see their current skin for may a half Secound then you see it gets changed to the "somewhere saved" one.

player often change their skins.
The issue only appears when MYSQL, is used as CMI database. When using SQLITE for CMI database all works normal and players see their current skins with each login no matter how often they change them.
We also tried disabling the the skin modul of CMI and using an other SkinManagmentPlugin.
Same result - Skin change is only seeable once a restart + forced by command as long CMI is set to use MYSQL for database. 

Server: Paper 1.16.3 Build 195
CMI 8.7.7.1

To Test:
Start Fresh CMI
Update your skin a few times (relog each time) and see if it changes - result you will see your changed skin
now setup datebasetype to MYSQL and restart the server.
Update your skin a few times (relog each time) and see if it changes - result you will see the change once then you see the changed skin for a half secound and it get overwritten with the old skin...

database.yml
```
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: XXXXXXXXX
  password: XXXXXXXXX
  hostname: XXXXXXXXX
  database: minecraft
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: true
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: true
```

config.yml parts:
```
  # When this is set to true features like glow color, player collision, name plates will stop working and CMI will avoid doing anything related to player teams
  # Enable this if you are experiencing issue with other plugins which utilizes players teams for certain features
  DisableTeamManagement: false
..
..
..
Skins:
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 30
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with posible requests
  SkinRequestFrequency: 5
```
