### ISSUE TITLE
Can't add allowed commands to /cuff

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#4212]
I'm trying to add the ability for players to use /help and /rules while cuffed but no commands will work other than the default set commands. /msg, /tell etc.

I tried using ```/ctext rules``` and every other alias for the commands but nothing seems to work.
Tested it on a server with nothing but CMI and still can't add any commands.

```
Cuff:
  # When set to false will allow players to talk who is cuffed
  Mute: true
  AllowedCommands:
  - msg
  - r
  - tell
  - spawn
  - help 
```

---

**Cmi Version:** 8.7.7.1

**Server Type :** Paper(196)

**Server Version:** 1.16.3
