### ISSUE TITLE
Per rank progress value not working

### ISSUE THREAD

**Issue by TABmk** [Zrips/CMI#4215]
**Description of issue:**

![](https://cdn.discordapp.com/attachments/744698034100895868/755549160064680006/unknown.png)

Placeholders are wrong too.

Even if i set rank or add only one dafault and 2 extra, or update second it still show same % for all ranks. 

---

**CONFIG SECTION:**
#### ranks.yml
```
1:
  Enabled: true
  DisplayName: '1'
  DefaultRank: true
  StatsRequirements:
  - "ChestOpen:20"
  Commands:
  - "cmi give [playerName] stone"
2:
  Enabled: true
  DisplayName: '2'
  DefaultRank: true
  StatsRequirements:
  - "MonsterKills:slime:5"
  Commands:
  - "cmi give [playerName] stone"
```

---

**Cmi Version (using`/cmi version`):** 8.7.7.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper build 196
