### ISSUE TITLE
No color in /me

### ISSUE THREAD

**Issue by Zykana** [Zrips/CMI#4219]
**Description of issue:**
Colors are not working in /me messages.

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    PublicMessage: false
    PrivateMessage: false
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: false
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: false
      privatemessage: false
      me: false
      signs: false
      books: false
```

---

**Cmi Version (using`/cmi version`):** 8.7.7.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 196

**Comment by CloudeLecaw** [comment]
You need to set it to true
```
   Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    PublicMessage: false
    PrivateMessage: false
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
```
Same for public and Private if you wanne use colors there
