### ISSUE TITLE
Pushing other players in AFK status put them out of the status

### ISSUE THREAD

**Issue by NeuTraLZero** [Zrips/CMI#4221]
**Description of issue:**
Pushing other players in AFK status even the slightest bit put them out of the status, even if PreventPushing is set to true
This can probably be solved by disabling the afk player's collision completely to prevent them from leaving the status
---

**Cmi Version (using`/cmi version`):** 
8.7.7.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3 paper-197

**Comment by CloudeLecaw** [comment]
normal - pushing is movement
if you dont want this then you need to disable it
in the config afk section you find
```
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: false
```

**Comment by NeuTraLZero** [comment]
> normal - pushing is movement
> if you dont want this then you need to disable it
> in the config afk section you find
> 
> ```
>   # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
>   # Keep in mind that player can still be moved around the same block he is in
>   PreventPushing: false
> ```

PreventPushing is already set to true and it still counts as movement

**Comment by CloudeLecaw** [comment]
push players should not be able to push the player - only admins

**Comment by CloudeLecaw** [comment]
Here an example how to disable pushment on afk

```
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  - cmi playercollision [playerName] true -s
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eis now AFK
  - cmi playercollision [playerName] true -s
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eis no longer AFK 
 - cmi playercollision [playerName] false -s
```
