### ISSUE TITLE
Schedulder day defined

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#4222]
**Description of issue:**
I created a schedule which should activate only Sunday at 20h. It activate everyday.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
votetop:
  Enabled: true
  PerformOn:
    '1':
      Day: Sunday
      Hour: 20
  Commands:
  - some cmi commands
```

---

**Cmi Version (using`/cmi version`):** 
8.7.7.0 (I know not latest.)
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.2

**Comment by Zrips** [comment]
Retested, everything seams to be working correctly, this only triggers on defined day. 
How often do you restart server?

**Comment by thomaboehi** [comment]
The server is restarded every morning at 5 oclock

**Comment by Zrips** [comment]
Do you have any other schedulers than this one? I need a way to make it bug out for me so i could fix it, if its a bug, as currently it seams to be working correctly and doesn't trigger if it should not.

**Comment by thomaboehi** [comment]
```
Lot:
  Enabled: true
  MinPlayers: 4
  FeedBack: true
  Repeat: true
  PerformOn:
    '1':
      Hour: 8
      Minute: 0
    '2':
      Hour: 12
      Minute: 0
    '3':
      Hour: 16
      Minutes: 0
    '4':
      Hour: 20
      Minutes: 0
  Commands:
  - cmi give [randomPlayer] gold_ingot %rand/5-20%
  - cmi give [randomPlayer] diamond %rand/5-10%
  - broadcast &6[randomPlayer] &ea été tiré au sort et a gagné un lot!
Announcer:
  Enabled: true
  MinPlayers: 1
  FeedBack: true
  Delay: 600
  Repeat: true
  Commands:
  - cmi ctext annonce%cmi_random_1_3% all
  - cmi sound entity_player_levelup -all
ClearLag:
  Enabled: true
  MinPlayers: 1
  Delay: 2400
  Repeat: true
  Commands:
  - broadcast Nettoyage des items au sol dans 1 minute.
  - delay! 30
  - cmi bossbarmsg all Nettoyage des items au sol dans [autoTimeLeft]! -cmd:"cmi groundclean"
    -sec:-30 -c:red
```
I've these
