### ISSUE TITLE
/afk -s

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4240]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, I suggest make -s way for /afk command, because I want to use afk as protection after loggining. When there's downloading resource pack for players, they told me that sometimes happen that they are killed by monsters. I don't wanna give them god, because it loads for every player individually, so I want to give them afk (protection before monsters until they move). But I don't wanna spam chat with it, after every player joins... that's why -s would be nice here.

**Comment by CloudeLecaw** [comment]
Afk does not prevent your players from mobs spawning so this addnwould be not usefull for you. It just prevents spawners spawning.

**Comment by Volgeop** [comment]
It prevents mob attack when I set it in config, and this is enough

**Comment by CloudeLecaw** [comment]
Dont u think your players will gona cheat with this? "oh a mob... /afk... Ok mob is gone i can move aggain".. This is what many ppl would do then ^. ^

**Comment by Volgeop** [comment]
I set there cooldown before to 5 minutes

**Comment by Zrips** [comment]
next update

**Comment by CloudeLecaw** [comment]
> I set there cooldown before to 5 minutes. And I expect they don't know it.

They will,like allways when we give players some advantages

**Comment by bobhenl** [comment]
Now I needed this feature for another usage. Players aren't kicked from server, just teleported on spawn, but then it cancels their afk, so I'll set them afk with -s to don't spam chat again.

**Comment by CloudeLecaw** [comment]
I see your server uses thw /Spawn and /back feature f or the chickennrunners ;)

I recomment to use multiple commands here may innform of a custom alias...(not afk..may something like /aafk):)

1.) Normal afk
2.) Spawn
3.) Delay of 1,2 secounds
4.) The silence afk


Why? Else it could happen that their afk state gets removed because of afk command was faster then the teleportation..

**Comment by bobhenl** [comment]
```
  AutoKickIn: 600
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - ifinworld:world@#! asConsole! cmi spawn [playerName]
  - delay! 3
  - asFakeOP! cmi afk -p:[playerName] -s
  - asConsole! cmi ctellraw [playerName] <T>&c&lAFK &f» &fZa AFK jsi byl přemístěn
    na &c/spawn&f. Pokud nechceš být přemisťován na spawn, zakup si alespoň rank &b&lVIP&f
    ze &c/store&f.</T><H>&cKlikni pro vykonání příkazu &e/store&c.</H><SC>/store</SC>
```

Can I somehow move them on spawn without canceling afk (at least without message that he isn't already afk)? And I have to set there ifinworld, cause then it's executed again and still again and again.... And what about if it's world, same world as normal one?
