### ISSUE TITLE
Accepting command fee is counting to cooldown

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4243]
**Description of issue:**

---
Hi, the problem is, when you use cooldown for specific command and also command cost on this command. Then, when you accept command, you'll pay money, but the command isn't executed, because you already "used it", so there's message that this command can't be executed for next .... (cooldown). And maybe in commands like /tfly, when player doesn't specify time, then cooldown and command cost doesn't have to be executed, because it only show player help for command tfly.

In config
```
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.cooldownbypass.[commandname] permission node
  # Always use full command name and not its alias
  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"
  Enabled: true
  List:
  - cmi top:3600
  - cmi tfly:3600
```
In command costs:
```
Enabled: true
# Example: - 'cmi heal:100.5:true'
# While defining command avoid using alias and use full command name
# Cost can be any positive number
# After cost you can use true/false to define if you want to inform player when money is charged after using command or not
# Second true/false will define if we confirmation from players by typing command again or clicking on a message in chat before performing it and charging for it. This will include information about command cost. By default players will be asked for confirmation
# Attention! Don't use alias command name, use full base command, for example /heal is not valid, use /cmi heal otherwise you will be risking in allowing players to perform base command without a charge
# On another hand you can use custom alias commands in here

# Keep in mind: base CMI commands will double check if command was successfully performed before charging money, while custom alias will charge money despite commands success
# So in example of /cmi warp player will not be charged if he enters incorrect warp name, while having custom alias will charge money even if command fails to be performed
Commands:
- cmi top:200:true
- cmi tfly:1000:true

```

---

**Cmi Version (using`/cmi version`):** 8.7.7.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 202, 1.16.3

**Comment by CloudeLecaw** [comment]
Where have you defined command cost?
Inna ic or custom alais? Then you need to define an extra cooldown requirements

**Comment by Volgeop** [comment]
Yeah, checking will be nice, because then I should probably disable alias for normal tfly and as you mentioned I have to create custom one now to let it work properly. But would be better, if cooldowns will be checked

**Comment by Volgeop** [comment]
@Zrips  DO you think that you can add checking system mentioned here soon or should I disable all commands from cooldowns with command cost and switch them to custom aliases? Cause now players can't use these commands and they're complaining about it, so if I should switch to custom alias system... but don't wanna switch there if you could change it soon.

**Comment by CloudeLecaw** [comment]
sometime specialy feature request seems to get forgotten. i really dont know sometimes if Zrips really read them all...maybe not.. i just think about my own feature requests (these are not less^^) It also made me searching often on loking for ways arrounds, sometimes with the needed help of extra plugins. For some of my request im waiting since 2016... without any responce from Zrips.  May he dont has the time to answer us all. (look on amount of opened ticketes alone....933... aspect that Zrips does this CMI project in his freetime and its not his real job...so this would be a hardcore work that stealls all freetime he ever will have to answer just all in github...short...its not possible for him..)

So currently i suggest you should disable them all at the moment ti solve your issue. you can reenable them if Zrips may add this one time, but dont aspect this done too soon.. :(

**Comment by Volgeop** [comment]
Wait, I tried it make via custom aliases and it isn't possible....

I tried these combinations:
1. Cooldown in config & command cost in command cost.yml -> command wasn't executed even if players money was charged + cooldown was activated -> so the worst solution
2. Cooldown in custom alias like 
```
  cletani:
    Cmds:
    - cooldown:3600?! asConsole! cmi tfly [playerName] 15m -s
    - cooldown:3600?! asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fBylo
      ti aktivováno &elétání &fpo dobu &e15 min&f. Aktivuj opětovným použitím.</T>
```
and `- cletani:1000:true` in command costs.yml

Here the command worked, but player's money was charged even when cooldown wasn't loaded, so when there is 1 hour before using the command again... and player used it earlier, he paid 1000$, but it only told him that he need to wait... for ex. 30 minutes. So he paid just to know how long he has to wait.

3. Using Cooldown & `moneycost:1000#!`, both in custom alias:
Here was the problem, that player executed /cletani and it instantly charged him money without accepting fee.... So he didn't know that it costs 1000$, there isn't any pop up, if he really wanna pay for it, like it is in commandcost.yml. In commandcost.yml player has to first confirm if he really wanna pay 1000$, but here it was instantly executed without letting player know and without his agreement. But it wasn't charging when command cooldown wasn't gone.

So.... any solution probably can't solve this, only when Zrips add some extra check that will check cooldown in cooldowns: in config.yml OR cooldown:X! in custom aliases, both need to be added, or if he add way to accept command fee in custom aliases when "moneycost:X!" is used.

So @Zrips , we probably need your solution from this side.

**Comment by CloudeLecaw** [comment]
About point 3. You never said that plaer need s to be informed or get asked

this is something this can not be done by this
moneycost:1000#! just ask you if you have the mone and cancel all commands  after if you dont have the money
So all was working fine here. If you wished what u done want you could create a seocund custom alias where it asked if this command really want to be executed or not using Hover and ctext format. Then when you click on YES other customalias get executed if no then 3rd custom alaias that tells it was cancelt or still nothing ;)

But if think you prefer the way with the command costs. So lets see if Zrips can do sothing there :)

**Comment by Volgeop** [comment]
@Zrips by the latest update you almost fixed it. Now it respects Cooldowns: section in config, that's great, but because we can't add custom aliases to cooldowns:  config... it doesn't work there, I had to add cooldown to custom aliases command to it's own, so I have:
```
  cletani:
    Cmds:
    - cooldown:3600?! asConsole! cmi tfly [playerName] 15m -s
    - cooldown:3600?! asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fBylo
      ti aktivováno &elétání &fpo dobu &e15 min&f. Aktivuj opětovným použitím.</T>
```
Cause when I had "cletani:3600" in Cooldowns in config... it didn't work. So  I did it this way. BUT NOW, you fixed that commands under COoldowns: now show cooldown without taking fees (command costs), so it's great. BUT cooldown from custom alias is still broken and you have to pay just to see your cooldown there. Do you think that you can:
1. Try respect cooldown from custom alias before command costs too?
OR
2. Add support for custom aliases in Cooldowns: section?

**Comment by CloudeLecaw** [comment]
why this command in custom alias has no money cost?
cooldown:3600#! moneycost:432#!   these should break up command if its still in cooldown or player does not have money
its enough to have this in the first like because its cancels all commands after

**Comment by Volgeop** [comment]
Cause as I mentioned, there isn't confirmation for it... I wanna that players have to confirm it, because then they're complaining about it that they didn't know it cost so much money... Maybe will be good if asking for confirmation about money is added to hasmoney! too. That's why I used cletani in commandcosts.yml file instead of doing it via hasmoney!

**Comment by CloudeLecaw** [comment]
confimation? well you should inform your players about costs somewhere . maybe on the homepage of your server in an extra section. or somewhere where all costs are listed. This would prevent from complain. just executing a command is not god

Idea: Let tem Execute a custom alaias that informs them in chat by msg and lears to a secounds custom alias that they can click from the meassage and that is direct like /ibuyitemfor250dollar that execute the cooldown command
so they cant complaint anymore telling they didint know. for a nice design of that you could use the cctest format that is also used from cellraw

**Comment by Volgeop** [comment]
Yes, this is also good method, but I think Zrips also can try to respect these cooldowns when using command costs section, like he did in the latest update with cooldowns: section in config. Thanks for idea, will try it.

**Comment by Volgeop** [comment]
I combined it a little bit more.
```
  cletani:
    Cmds:
    - asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fMáš zájem o &edočasné létání &fna &e15 minut &fza &e1000€&f? Klikni pro zaplacení a aktivaci.</T><H>&ePřipomínáme, že tento příkaz ti strhne &f1000€&e.</H><CC>cletaniyes [playerName]</CC>
  cletaniyes:
    Cmds:
    - ptarget:$1! cooldown:3600?#! moneycost:1000?#! cmi tfly $1 15m -s
    - ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo
      ti aktivováno &elétání &fpo dobu &e15 min&f. Aktivuj opětovným použitím.</T>
```
