### ISSUE TITLE
/sell command to OPEN menu instead of selling item in hand

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4271]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, could you please add option or add is as default to open menu (gui - sell gui) via /sell command?

### Basic explanation as to why this feature is needed and/or useful to have: ###
The problem is that my player wanted to try it, executed /sell and it sold him Netheritte pickaxe with silk touch.... He though that it will opens menu. I think that this will be better solution than instantly selling item, atleast config option for it.

**Comment by CloudeLecaw** [comment]
could you simply create a custom alias?;)

**Comment by Volgeop** [comment]
I can't, because then /sell hand, /sell blocks etc. stop work.

**Comment by CloudeLecaw** [comment]
U havent thought full about it
Just create a secound custom alais called /sell hand  and a thrid /sell blocks  that executes the commands for /cmi sell blocks and /cmi sell hand its just Importent that these come before the /sell custom alias

**Comment by CloudeLecaw** [comment]
So here is is, add to custom alais:

add to CustomAlias.yml
```
  sell all:
    Cmds:
    - cmi sell all
  sell block:
    Cmds:
    - cmi sell blocks
  sell hand:
    Cmds:
    - cmi sell hand
  sell same:
    Cmds:
    - cmi sell same
  sell:
    Cmds:
    - cmi sell gui
```

**Comment by Volgeop** [comment]
Hey it almost work, except it's not tab completed 😅

**Comment by CloudeLecaw** [comment]
Maybe because i forget the : at /sell normal.?
Usually it should i will build this one in an hour when i am at home and check where is the problem, because it should work that way.

**Comment by Volgeop** [comment]
I noticed you forget it but I added it there before and it still didn't work.

**Comment by CloudeLecaw** [comment]
Dont worry i will check. Maybe its just because of the disabling in alias.yml i will check what wents wrong here 🙃

**Comment by CloudeLecaw** [comment]
ok i solved the problem *lol* u wont belive it what it was^^ well i will post you the result

**Comment by CloudeLecaw** [comment]
Oh one last thing may its usefull may not
If u add this alias as last of the sell custom alias then when a player write /sell SOMETHING
then this commands gets executeded i used this for help to so when a player writed /help SOMEWORD then the mainhelppage opens (note: the little bad site of this is - you have the "?" in the chooseable arugment in tabcomplet then...but may that does not matter... so add this too if you want that gui allways opens if its something else then in the other customaliases above.
  sell ?:
    Cmds:
    - asPlayer! cmi sell gui

**Comment by Volgeop** [comment]
Yeah, thank you very much.

But it's a bit weird when you use for ex.   /sell MyDreamBlocks  then it doesn't open GUI normally, but use normal /sell. Why, when there's set:
```
  sell:
    Cmds:
    - asPlayer! cmi sell gui
```
It's a little bit weird, but ok, I added there ?

**Comment by CloudeLecaw** [comment]
if your using "/sell ?": you dont need the extra alias "/sell"

**Comment by Volgeop** [comment]
Yeah I know, but I meant when if I don't use sell ?, then it's weird it doesn't open menu when you write there something.

**Comment by CloudeLecaw** [comment]
when you have /sell ?  and you u writee /mydreamblock then gui should open because the ? stand for "everthing" this is why its important that this is the last /sell customalais because it checks the once above first if you use for example /sell normal

**Comment by Volgeop** [comment]
And now still question... Do you think there could be added option to disable selling items with enchantments and special tags like name and lores.... or should I remove for now way to sell tools, weapons and armors? If still players use /sell all, it's for VIP and they use it sometimes, but I don't know, what's better, if the better will be when I remove these items from worth.list, or if I replace sell all with sell blocks like you mentioned.

**Comment by CloudeLecaw** [comment]
someone asked this questen before.  in a anther thread, at the moment the normal sell command cant do that because it used just vanilla names :\

**Comment by Volgeop** [comment]
Or maybe confirmation when when using /sell all as warning

**Comment by CloudeLecaw** [comment]
this also would be a nice idea if this could be added

**Comment by CloudeLecaw** [comment]
If you dont use it at the moment what about blocking selling of gear and give them

access to /cmi scavange
there they can enter their items in a gui and get back some materials if they want.
also you can deinfe the price and chances for it in the config

```
Scavenge:
  ItemBreak:
    # Defined percentage for item to break when salvaging it
    # Value can be from 0 to 100, where 100 means that each time player extract enchant, item breaks
    # This can allow player to extract enchantments without breaking item itself
    # Set it to 100 if you want to always break item
    # Keep in mind that broken item will go throw ingredient return process
    # Attention! Items without enchants will have 100% break chance
    Base: 8.0
    # Adds extra chance to break item depending on how many enchants item has
    # In example having base chance of 8% and having this set to 2 while having item with 3 enchants will result into 8+(2*3)=14% chance to break item
    ForEachEnchant: 2.0
    # Adds extra chance to break item depending on enchant level
    # This will take into consideration enchantment max and current levels
    # Having this set to 7.5 means, that enchantment at max level will have 7.5% extra chance to to break item
    # But if you have sharpness 2 which has max level of 5, then only 3% fail chance will be added
    ForEachEnchantLevel: 2.0
    # Defines in percentage a max chance to break item when extracting enchants
    # This can limit chance to particular one in case it gets to 100% and it would always break
    MaxBreakChance: 100.0
    # Value between 0 and 100 which defines extra fail chance when items doesnt have max durability
    # Having this set to 50 will mean that item at 1 left durability will have fail chance increase by 50%
    # Items which are not damaged will not experience any fail chance increase
    BreakDurabilityCheck: 50.0
    # When set to true, items durability will be taken into consideration when extracting ingredients
    # In example if item has 100 max durability and current is at 50, then only half of ingredients will be considered for extraction
    # This doesnt mean that player gets 50% of them, it only means that half of posible ingredients will go throw IngredientReturn process
    DurabilityCheck: true
    IngredientReturn:
      # Defines in percentage a max chance to return ingredients of item if it fails extraction process
      # This will apply for each ingredient that item has
      # Recipe to make that item should exist in database, or it will not return any ingredients
      Base: 25.0
```
