### ISSUE TITLE
Commands listed in the config section under "WarmUps:" will not show in Commandspy.

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#428]
Any command listed in the config section under "WarmUps:" will not show in Commandspy.

**CONFIG SECTION:**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  List:
  - cmi back:3:false
  - rtp:3:false
  - warp :3:false
  - cmi home :3:false
  - cmi spawn:3:false
```

**Cmi Version (using`/cmi version`):** 7790
**Server Type (Spigot/Paperspigot/etc):** Spigot
**Server Version (using `/ver`):** 1.12.2
