### ISSUE TITLE
Naming players default bed "Home Bed" breaks commands.

### ISSUE THREAD

**Issue by incredimike** [Zrips/CMI#4280]
I named the default bed name to "Home Bed" in the config. I've since reverted it, but a few players created new homes while I had the bad value and they have a home named "Home Bed" which they cannot warp to or delete. They get "permission denied" error.

As op, I try to delete the home with `/removehome Home Bed PlayerName` and it doesn't work either. Seems pretty obvious now that I shouldn't have used a space in the name. 🔢 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Homes:
  # Name for default home location. By default its "Home"
  DefaultName: Home
  # Name for bed location. By default its "Home"
  # Different name can be used to identify home location set by interacting with a bed from home location created with command
  DefaultBedName: Home Bed
  # Defines what characters you can use in your home names
  ValidNameRegex: '[^a-zA-Z0-9\-\_]'
```

---

**Cmi Version (using`/cmi version`):** 8.7.7.4

**Server Type (Spigot/Paperspigot/etc):** Paper 204

**Server Version (using `/ver`):** 1.16.3
