### ISSUE TITLE
Allow Tabformats for Groups

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4285]
We want our Admins to see all players in Tab with format of GoupTab2.
The Players should only see all players with the format of GroupTab1

Now we gave players   cmi.tablist.1   and admins  cmi.tablist.2

Result.. everyone sees admins in GroupTab2 format and all players in GroupTab1 format
everyone.... Thats not what we need. We want differnt Tab designs for differnt groups

```
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 60
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  # When set to false we will not add header text to tablist
  addTabListHeader: true
  # When set to false we will not add footer text to tablist
  addTabListFooter: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '  [prefix][playerDisplayName] %cmi_user_afk_symbol%'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Willkommen auf Lululand'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome% '
      - '&7Konto:&6%cmi_user_balance_formatted% '
      - '&7Uhrzeit: &6%server_time_HH:mm% &7Ping:&6%player_ping% '
      - '&7Lululandzeit: &6%player_world_time_24%'
      - '&f------------------------------------'
  useGeneralName: false
  # When this set to true, in case you dint defined PlayerName, Header or Footer in GroupFormat, then default one from GeneralFormat will be used
  useGeneralHeader: false
  useGeneralFooter: false
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  GroupFormat:
    '1':
      PlayerName: '  [prefix][playerDisplayName] %cmi_user_afk_symbol%'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Willkommen auf Lululand'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome% '
        - '&7Konto:&6%cmi_user_balance_formatted% '
        - '&7Uhrzeit: &6%server_time_HH:mm% &7Ping:&6%player_ping% '
        - '&7Lululandzeit: &6%player_world_time_24%'
        - '&f------------------------------------'
    '2':
      PlayerName: '  [prefix][playerDisplayName] %cmi_user_vanished_symbol% %cmi_user_afk_symbol% &0(&b%cmi_user_gamemode%&0)'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Willkommen auf Lululand'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome% '
        - '&7Konto:&6%cmi_user_balance_formatted% '
        - '&7Uhrzeit: &6%server_time_HH:mm% &7Ping:&6%player_ping% '
        - '&7Lululandzeit: &6%player_world_time_24%'
        - '&f------------------------------------'
    '3':
      PlayerName: '  [prefix][playerDisplayName] %cmi_user_vanished_symbol% &3testet etwas'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Willkommen auf Lululand'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome% '
        - '&7Konto:&6%cmi_user_balance_formatted% '
        - '&7Uhrzeit: &6%server_time_HH:mm% &7Ping:&6%player_ping% '
        - '&7Lululandzeit: &6%player_world_time_24%'
        - '&f------------------------------------'
```
One the picture you can see i seted myself the TabGroup3
everyone see it
![Snag_935865](https://user-images.githubusercontent.com/12080017/94484230-6098ed80-01dc-11eb-8329-2491d2faa1ec.png)
What i thought an wanted is that only me sees this format and i could see this format for all that is listet on my name
but currently its listet for me in TAB and everyone ingame sees it.. this cant be right.
