### ISSUE TITLE
Bypass cooldown:XXX?! in specialized commands

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4307]
**Question: **
Hi, how can I please bypass this cooldown via permission in specialized commands?
So if I have:
```
  cletani:
    Cmds:
    - cooldown:3600?! asConsole! cmi tfly [playerName] 15m -s
    - cooldown:3600?! asConsole! cmi ctellraw [playerName] <T>&eBylo ti aktivováno létání po dobu
      15 min. Aktivuj opětovným použitím.</T>
```

How can I add special permission that could bypass cooldown?

May if there's something like cooldown:3600?! **OR** haspermission:.... ?

**Comment by TheExceed** [comment]
`perm:[value][@][?][#]!` @Volgeop

**Comment by Volgeop** [comment]
But wait, will it work for players without permission but with cooldown then? And with players with permission without cooldown?

**Comment by TheExceed** [comment]
> But wait, will it work for players without permission but with cooldown then? And with players with permission without cooldown?

So AFAIK, you would have two commands exact same commands. Cmi.commandname.nocd and cmi.commandname.withcd and one has the cd and one doesn't. Afaik

**Comment by Volgeop** [comment]
What's wrong with it please?
```
  cletani:
    Cmds:
    - perm:cmi.cletani.withoutcd#! cooldown:600?#! cmi tfly [playerName] 5m -s
    - cmi ctellraw [playerName] <T>&c&lRádce &f» &fBylo
      ti aktivováno &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
  cletani:
    Cmds:
    - perm:cmi.cletani.withcd#! asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fMáš zájem o &edočasné létání &fna &e15 minut &fza &e1000€&f? Klikni pro zaplacení a aktivaci.</T><H>&ePřipomínáme, že tento příkaz ti strhne &f1000€&e.</H><CC>cletaniyes [playerName]</CC>
  cletaniyes:
    Cmds:
    - ptarget:$1! cooldown:3600?#! moneycost:1000?#! cmi tfly $1 15m -s
    - ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo
      ti aktivováno &elétání &fpo dobu &e15 min&f. Aktivuj opětovným použitím.</T>
```
The command doesn't exist when I have it like this

**Comment by Volgeop** [comment]
From some reason it didn't work.
```
  cletani:
    Cmds:
    - cooldown:600?#! asConsole! cmi tfly [playerName] 5m -s
    - asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fBylo
      ti aktivováno &emoderátorské létání &fpo dobu &e5 min&f. Aktivuj opětovným použitím.</T>
  cletani:
    Cmds:
    - asConsole! cmi ctellraw [playerName] <T>&c&lRádce &f» &fMáš zájem o &edočasné létání &fna &e15 minut &fza &e1000€&f? Klikni pro zaplacení a aktivaci.</T><H>&ePřipomínáme, že tento příkaz ti strhne &f1000€&e.</H><CC>cletaniyes [playerName]</CC>
  cletaniyes:
    Cmds:
    - ptarget:$1! cooldown:3600?#! moneycost:1000?#! cmi tfly $1 15m -s
    - ptarget:$1! cmi ctellraw $1 <T>&c&lRádce &f» &fBylo
      ti aktivováno &elétání &fpo dobu &e15 min&f. Aktivuj opětovným použitím.</T>
```
