### ISSUE TITLE
Enable player head drop; Disable Custom mob head drop

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/CMI#4312]
**Description of issue:**
This is not following the settings as they are available.  I Would like to enable player head drops, but disable custom head drops from mobs.  This cannot be done at this time as evidenced by these settings:
```
  Heads:
    Player:
      Drop: true
      # Percentage from 0 to 100 for head to be dropped. Decimals are acceptable, like 0.2
      # 100 will mean that head will be dropped every time player kills another player
      # 1 will mean that there is 1% that player will drop head if he is killed by another player
      Percentage: 1.0
      # Percentage from 0 to 100 for lowering chance in getting second head of same player
      # This will reset on each server restart
      LowerChanceOfterDrop: 50.0
      # When enabled player heads will have bigger chance to drop when using tools with looting enchantment
      # Value is in % and it will add appropriate percentage to current drop chance by using drop chance itself
      # For example player who has head drop change of 1% with looting 3 which has 30% bonus will have 1.3% as end value (default values)
      # This only applies for player heads
      # You can add as many levels as you want, simply duplicate line and set new number, in example
      # Lvl33: 35.5
      LootBonus:
        Enabled: true
        Lvl1: 5.0
        Lvl2: 15.0
        Lvl3: 30.0
        Lvl10: 99.5
    Mob:
      # Enables custom mob heads dropping from mobs with particular chance
      # Check customHeads.yml for customization by entityType
      Drop: false
```
This should be enough in and of itself, but since these setting are very obviously being ignored since all mobs are still dropping custom skulls as defined in customHeads.yml, I went ahead and also modified each entry in that file setting the DropChance to 0.0 and... since that didn't work either later set the chance per each individual skull to 0.  None of these settings had any effect and all mobs are still dropping custom skulls.  

Here's an excerpt from the modified customHeads.yml, each mob/skull combination is set up exactly this way, and each mob is still dropping the skulls that are defined in this file:
```
  wither_skeleton:
    DropChance: 0.0
    LowerWithEachDrop: 50.0
    Heads:
    - 0:Default:Nzk1M2I2YzY4NDQ4ZTdlNmI2YmY4ZmIyNzNkNzIwM2FjZDhlMWJlMTllODE0ODFlYWQ1MWY0NWRlNTlhOCJ9fX0=
    - 0:Default:ZjVlYzk2NDY0NWE4ZWZhYzc2YmUyZjE2MGQ3Yzk5NTYzNjJmMzJiNjUxNzM5MGM1OWMzMDg1MDM0ZjA1MGNmZiJ9fX0=
    - 0:Default:NDk2YmM4ZWJkNGUxM2Y0OTZkOGQ3NGM1NjVkZDU2ZTk5YTRhZjJlMmVhN2EyN2E5NmMxYWJkMjg0MTg0YiJ9fX0=
```

---

**Cmi Version (using`/cmi version`):** 
[22:04:02 INFO]: --------------------------------------------------
[22:04:02 INFO]: CMI: 8.7.8.0 SqLite
[22:04:02 INFO]: Server: Paper(212) 1.16.3-R0.1-SNAPSHOT
[22:04:02 INFO]: CMI economy: False Vault: 1.7.3-b131 CMI Chat: False
[22:04:02 INFO]: Modules -> 17 enabled 34 disabled: spawnerProximity, cuffed, customMessages, mirror, versionCheck, moneyCheque, skin, noTarget, bossBarCompass, coloredArmor, cooldown, spawnerCharge, vanish, namePlates, anvilUnlimitedRepair, timedCommands, homeInteractions, hpBossBar, armorstand, portals, anvilRenameColor, jail, spawners, playerChatTag, kits, flightCharge, schedule, disabledEnchants, worldLimits, ranks, firstJoinMessages, selection, silentChest, warmup
[22:04:02 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-212 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
