### ISSUE TITLE
Geo IP broken

### ISSUE THREAD

**Issue by Jhezreel708** [Zrips/CMI#4331]
**Description of issue:**

Geo IP seems to be broken.. I downloaded the plugin for the first time.. enabled the download GEOIP and CITY too...
I have transferred from EssentialsX to CMI and my IP is still the same.. it used to be accurate on EsX but on CMI it's stuck to United States.. I live in asia sadly... 
my lobby is on EsX still but it shows the right country..

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  AutoDownload:
    # In case you dont have GeoIP.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoIp: true
    # In case you dont have GeoLiteCity.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoLiteCity: true
```

---

**Cmi Version (using`/cmi version`):** 
8.7.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3
**Relevant plugins (Delete if this isn't needed):**
