### ISSUE TITLE
/cmi tp end similar /cmi commands without aliases & cooldowns:

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4334]
**Description of issue:**

---

Hi, I have issue with /cmi <command> not aliases commands ant it's cooldowns. Cause when player doesn't have permission to use command, for ex. regular player doesn't have access to /tp command, but he can do /cmi tp and it shows him that he has to wait next 3 seconds... instead of showing that he doesn't have permission. So please make check for permission before checking for cooldown from cooldowns: section.
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.cooldownbypass.[commandname] permission node
  # Always use full command name and not its alias
  # ----------
  # Alternatively you can use cmi.cooldown.[some_command].[timer] permission node. For example: cmi.cooldown.cmi_heal.30 which will set 30 second cooldown on /cmi heal command
  # If you want to apply cooldown on command when variable is provided, add extra _ at end. For example cmi.cooldown.cmi_heal_.30 which will only use this cooldown when healing some one else
  # KEEP IN MIND that for permission to work you need to set base command cooldown in this list, otherwise permission node will have no effect
  # -----
  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"
  Enabled: true
  List:
  - cmi heal:300
  - cmi feed:120
  - cmi tp:3
```

---

**Cmi Version (using`/cmi version`):** 8.7.8.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):**  1.16.3, 214
