### ISSUE TITLE
I want to ask for a (head texture) website

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#4339]
**Question: **
  skeleton_horse:
    DropChance: 0.01
    LowerWithEachDrop: 0
    Heads:
    - 100:&b骷髅马头:NDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ==

**Comment by CloudeLecaw** [comment]
what is this and why you dont use it allready for oyur own custom heads?

**Comment by CloudeLecaw** [comment]
```
  skeleton_horse:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ==
```

simply add yours of this text you have theire is a vailded format (i dont think so because of the japanise letters in the coder
