### ISSUE TITLE
touch! for Specialized Commands

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4341]
if an IC is attached to a block or entiies the variable touch! should be abbleto  set before the command

if the player touched now the entity or block that is attached to the ic then the command get executed.

so command would look like 

Example - IC Test is connected to ab NPC Citicents:
```
Test:
  ID:
  - 206
  Commands:
  - touch! msg! [playerName] &bYou touched me
```

Now when Player touches Citizen 206 the command will be executed.
It also could be blocks or other entities.
