### ISSUE TITLE
These custom aliases don't work

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4348]
**Question: **
Hi, don't you please someone know why these custom aliases don't work?
```
  warp priroda:
    Cmds:
    - asPlayer! priroda
  warp tezba:
    Cmds:
    - asPlayer! tezba
  warp spawn:
    Cmds:
    - asPlayer! spawn
```
When player executes /warp XP for exp, then command /priroda is executed... why? I wanna it execute just when he type warp priroda....

**Comment by CloudeLecaw** [comment]
What do your custom alias? Are these the real commands? Example: Dont use alias like spawn instead of cmibspawn

**Comment by Volgeop** [comment]
It executes the RTP command. I use for warp another plugin on one of my two servers (need to make this alias also for server with CMI to handle warps), on the mentioned I use HyperDrive. 

And I just wanted to make "warp wild" that will do random teleport to the wild, because players are often mad about it instead of using /wild. So I wanted to transfer random teleport to /wap wild too. Method you told me with "warp ?" didn't work neither :/ Then it broken tab completion of warps etc.

**Comment by Zrips** [comment]
You kind of have them backwards. Instead of defining alias as **priroda** you defined it as warp priroda. So to fix that
```
  priroda:
    Cmds:
    - asPlayer! warp priroda
  tezba:
    Cmds:
    - asPlayer! warp tezba
  spawn:
    Cmds:
    - asPlayer! warp spawn
```
