### ISSUE TITLE
Custom aliases problem with command fees - important abusing bug

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4379]
**Description of issue:**

---
Hi, I probably found issue with custom aliases and cmi. Will give you example. The problem is, when player uses /loterie 1500 or something after /loterie, it doesn't cost anything....

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Custom aliases file:
```
  loterie:
    Cmds:
    - asConsole! scrates givekey BohatsiNezKral [playerName] 1
  loterie5:
    Cmds:
    - asConsole! scrates givekey BohatsiNezKral [playerName] 5
  loterie10:
    Cmds:
    - asConsole! scrates givekey BohatsiNezKral [playerName] 10
  loterie20:
    Cmds:
    - asConsole! scrates givekey BohatsiNezKral [playerName] 20
```
Command cost file:
```
- loterie:1500:true:true
- loterie5:7500:true:true
- loterie10:15000:true:true
- loterie20:30000:true:true
```

My players used it to get keys to lotery crate for free and then they got about 100K+ money...

---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 228
