### ISSUE TITLE
Player Balance Limit and /pay Issue

### ISSUE THREAD

**Issue by BetaBurnt** [Zrips/CMI#4384]
**Description of issue:**
Sending money to another player with /pay when their balance is at the cap set in the config.yml voids that money (the player sending it loses it, the player it was sent to can't have it so it just vanishes) rather than cancel/deny the payment.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: true
  # Set to true if you want to log money transfers between players
  LogEnabled: true
  log:
    Unknown: true
    Transfer: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 1.0E8
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: false
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: false
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
  Global:
    # Starting amount of money players will have
    StartingAmount: 1000.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 25000000
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 0.5
    # Defines if you want to allow payments with fractions
    # if this is disabled then payments will be limited to whole numbers and in case player provides number with fraction we will round number down
    Fractions: true
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: $
    # Format used for displaying money
    MoneyFormat: '###,###.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: false
    # Placing of currency symbol
    Placing: '[symbol][money]'
```

---

**Cmi Version (using`/cmi version`):**  CMI: 8.7.8.2 SqLite-> 8.7.8.4 (little out of date but nothing in the changelogs for the newer builds that suggest this would be fixed in them either - update pending for active server)

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** This server is running Paper version git-Paper-231 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** Using Vault 1.7.3 and CMIInjector 1.0.2.3
