### ISSUE TITLE
MobFarmManager Armor stands not culled

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4398]
**Description of issue:**
When placing armor stands, mfm blocks the placement of new empty armor stand. That works well.
When a piston pushes a new empty armor stand into the crowded chunk, the armor stands are not culled.
So you still can overload chunks with armor stands.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
no error
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# When this set to true, armor stands with items on it will be ignored on chunk cleanup
# Recomended to keep it at true to avoid player item deletion
IgnoreFullArmorStands: true
EntityTypes:
  ARMOR_STAND:
    Use: true
    Limit: 8
```

---

**MFM Version (using`/cmi version`):** 
MFM 1.5.8.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.3
