### ISSUE TITLE
Cannot set a warmup on a custom alias

### ISSUE THREAD

**Issue by hamcoremusic** [Zrips/CMI#4420]
**Description of issue:**
Cannot set command warm up on a custom alias

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
config.yml
```
  - survival:3:false:tpaWarmup
  - creative:3:false:tpaWarmup
```
CustomAlias.yml
```
  creative:
    Cmds:
    - asConsole! mv tp [playerName] Creative
    Perm: true
  survival:
    Cmds:
    - asConsole! mv tp [playerName] world
    Perm: true
```
---

**Cmi Version (using`/cmi version`):** 
8.7.9.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
(238) 1.16.3-R0.1-SNAPSHOT
