### ISSUE TITLE
Warmups still don't work in 8.7.9.1

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4462]
**Description of issue:**

The warmups still don't work after the update.

---

**Cmi Version (using`/cmi version`):**  CMI8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by Sancaros** [comment]
me too 
Cmi Version (using/cmi version): CMI8.7.9.1

Server Type (Spigot/Paperspigot/etc): Paper fork

Server Version (using /ver): 1.16.3

**Comment by SmallSansSerif** [comment]
Same. Help please

**Comment by TomLewis** [comment]
@Zrips 
Even in  8.7.9.2 warmups are broken still.
You can use `/warp` and then click on a warp and it gives you a cooldown, but if you use `/warp name` it does not work, which is how most players will use the warps.

```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi warp :5:false:GlyphHead
  - cmi spawn:5:false:GlyphHead
  - cmi home :5:false:GlyphHead
```
