### ISSUE TITLE
PICKAXE_OF_CONTAINMENT from Slimefun & charges from CMI incompatibillity - duplication

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4474]
**Description of issue:**

---

Hi, when you have enabled Charges from CMI and they're on 0 and players try mine spawners with PICKAXE_OF_CONTAINMENT from Slimefun, then there's bug that they can duplicate spawners (broken spawners) with it. I also mentioned it on Slimefun github https://github.com/Slimefun/Slimefun4/issues/2507 (read this too please)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Charges:
    # When enabled players will be assigned to particular spawner charges group who have cmi.spawners.charge.[groupName] permission node
    # Players will be limited to how many spawners they can mine
    # StartingCharge will determine how many charges they will have on first time joining group
    # MaxCharge will limit to how many charges you can have at one time
    # Cooldown determines how often new charge will be given
    # Bonus is optional and it will determine by how many seconds to lower cooldown for next charge when placing spawner
    # Option to bypass limitations with cmi.spawners.charge.bypass
    Use: true
    # If set to true when player runs out of spawner charges spawner will be destroyed without droping it
    BreakWithoutCharge: false
    List:
      Default:
        Use: true
        StartingCharge: 2
        MaxCharge: 2
        Cooldown: 43200
        Bonus: 3600
```
Important video https://streamable.com/809hy3

---

**Cmi Version (using`/cmi version`):**  8.7.9.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 240

**Relevant plugins (Delete if this isn't needed):** Slimefun
