### ISSUE TITLE
[Feature Request] A command to toggle the silent join/quit messages when you can the silent join/quit perms

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4487]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
This would be a new command added just to be able to toggle if your join is silent or not when you have the permissions, cmi.messages.disablelogin, cmi.messages.disablequit. This could have a new permission of it's own dedicated to toggling your join. These don't necessarily have to be connected though. This is just to toggle it, as currently I have to negate the perm for players with the "*" perm or op as their join is automatically silenced.
### Basic explanation as to why this feature is needed and/or useful to have: ###
Just to quickly sumarize what I just said, I think there should be a command to toggle your join/leave message manually ingame rather than having to negate the previously mentioned permissions for your join message to show if you have all permissions.

Now, this may already exist and I just couldn't find it. Let me know if I missed it, thanks :)

**Comment by CloudeLecaw** [comment]
You can create a custom alias that gives and negate the the permission asConsole! for you. Dont forget to add a needed permission to execute this command.

**Comment by AZFire1** [comment]
I use LuckPerms. I tried this, and I also tried it with $1 replacing the $2 but it doesn't seem to be doing anything when I check ingame and console for if it effected anything. This is actually the first time I've seen  that CMI can do that much. I actually didn't know it could do this, that's awesome.

Due to the fact that you can do so much with custom aliases, I was wondering if there's a possible way I could do the same or similar things in the eventCommands for the death event. By this I mean, would there be a way I could make a death message that is not just one base death message but one that I could add my own custom reasons per death cause? I was just curious if that can be done.

**Comment by CloudeLecaw** [comment]
yes you can

**Comment by AZFire1** [comment]
Awesome. Would you possibly be able to provide an example of one custom death reason so I could see how to do it?

Also, could you please send me some documentation on how this works, so I could figure out how to fix the "joinleave [on/off]" command as, as I previously said I couldn't get it to work.

**Comment by CloudeLecaw** [comment]
Well if you want can post you our little eventcommamd.yml we use just the join anf first join events but may it help you to see what is possible :)
```

firstJoinServer:
  Enabled: true
  Commands:
  - atr reset [playerName]
joinServer:
  Enabled: true
  Commands:
  - msg! [playerName]         Willkommen auf dem Server [playerName]
  - msg! [playerName] &6&l   **********************************************
  - msg! [playerName] &4                  &8۩&8۩&8۩&4Halloween-Event-2020&8۩&8۩&8۩
  - msg! [playerName] &7              Vom 30.10-01.11.2020 feiern wir auf
  - msg! [playerName] &7                        Lululand Halloween
  - msg! [playerName] &4      &8۩&8۩&8۩&fNähere Infos in den Lulu-Wiki News&8۩&8۩&8۩
  - msg! [playerName] &6&l   **********************************************
  - cmi ctext news [playerName]
  - check:%cmi_user_dailyvotecount%==0! msg! [playerName] Du hast in den letzten 24
    Stunden noch nicht einmal für Lululand gevotet. &e☹
  - check:%cmi_user_dailyvotecount%==0! msg! [playerName] &c❤&4♥&fBitte vote für den
    Server&c❤&4♥
  - check:%cmi_user_dailyvotecount%!=0! msg! [playerName] &c❤&4♥&f Du hast in den
    letzten 24 Stunden %cmi_user_dailyvotecount% mal für Lululand gevotet.&c❤&4♥
  - check:%cmi_user_dailyvotecount%==0! cmi ctext voteslogin [playerName]
  - check:%cmi_user_dailyvotecount%!=0! cmi ctext voteslogin2 [playerName]
  - msg! [playerName]
  - check:%cmi_user_name%==Blueeyestar! cmi flyspeed Blueeyestar 5 -s
  - check:%cmi_user_name%!=Blueeyestar! cmi flyspeed [playerName] 1 -s
  - check:%cmi_user_name%==Cloude_Lecaw! cmi broadcast !&6&l⚡ &e&l⚡ &6&l⚡ &e&l⚡ &b&lCloude_Lecaw
    &e&list wieder da! &6&l⚡ &e&l⚡ &6&l⚡ &e&l⚡
  - check:%cmi_user_name%==Opa_Gerd! cmi broadcast !&4&l❤&c&l♥ &4&l❤&c&l♥ &4&l❤&c&l♥
    &e&lHier ist euer Lieblings-&4&lOpa&e&l! &4&l❤&c&l♥ &4&l❤&c&l♥ &4&l❤&c&l♥
  - check:%cmi_user_name%==Trevodor! cmi broadcast !&d&l♫ &6&4♫ &6&l♫ &e&l♫ &e&lTri,
    Tra, Trullala,... Der &9&lTrevodor &e&list wieder da. &a&l♫ &b&l♫ &1&l♫ &5&l♫
  - check:%cmi_user_name%==Heldo44! cmi broadcast !&e&lIst es ein Düsenjäger?✈,,,
    Ist es ein Blitz?⚡....NEIN es ist &d&lHeldo44&e&l!ツ
  - msg! [playerName]
quitServer:
  Enabled: true
  Commands:
  - cmi skin off [playerName] -s
  - cmi nick off [playerName] -s
```
