### ISSUE TITLE
Small tweak to the /rt command. 

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#4490]
**Description of feature/improvement request:**
More placeholders.

---
### Detailed explanation of what it should do, when and in what situation: ###
Add support for `[x] [z] [y]` to be used in the `teleported:` line. 

### Basic explanation as to why this feature is needed and/or useful to have: ###
Because it logical to have it there... It currently returns just those text. 

Quick thing: Please take a look at https://github.com/Zrips/CMI/issues/4470 it isnt fixed. Its still showing parts of the function.

**Comment by mrfloris** [comment]
Can you use placeholders?
```
playerTeleport:
  Enabled: true
  Commands:
  - cmi invsave [playerName]
  - 'msg! [playerName] &7Teleported: %player_world% @ %player_x% %player_y% %player_z%'
```
