### ISSUE TITLE
Jail bossbar for one secound when leavingnafk - reason: config - jail - noAfk true

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4492]
Since last cmi Update 8.7.9.3 we get a meassage in bossbar that tells us we were jailed for a secound when we leave afk
![unknown](https://user-images.githubusercontent.com/12080017/97473855-bf709480-194b-11eb-8d84-c49d4a452d6e.png)

Edit: the bossbar appears for may 1/2 secounds, was hard to Screenshot it becauae it disappers so fast 

CMI 8.7.9.3
Paper 1.16.3 Build 250

**Comment by Zrips** [comment]
What commands you have set for afk leave action in config file?

**Comment by CloudeLecaw** [comment]
`AfkLeaveCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist nicht mehr AFK.</T><H>[playerDisplayName]
    war AFK wegen %cmi_user_afk_msg% für %cmi_user_afk_for%.</H>`

**Comment by CloudeLecaw** [comment]
i found the issue in the config

```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: -1
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true
  # Do you want to prevent players damage while he is in jail
  PreventDamage: true
  WhiteListedCmds: []
```

when i set
  NoAfk: true  this happens
when i set
  NoAfk: false the issue is gone
