### ISSUE TITLE
/list Customization

### ISSUE THREAD

**Issue by DJKenzoDE** [Zrips/CMI#45]
Is it possible, if so then where?

To set true or false to  have in the /list list all Users or Users in they Groups? Or to edit they names fromn they catogories: e.q.: admin=boss etc.

Nice Greetz from Germany to you. ^^

**Comment by LogGits** [comment]
Its located in the locale_en.yml file:
```yaml
list:
    help:
      info: '&eShows online player list'
      args: ''
      explanation:
      - 'Perm: '
      - cmi.command.list.admin
      - cmi.command.list.staff
      - cmi.command.list.hidden
      - cmi.command.list.group[number]
    info:
      ListFormat:
      - '&e========================'
      - '&ePlayers online &6[amount]&e/&6[maxamount]'
      - '[adminLine]'
      - '[staffLine]'
      - '[hiddenLine]'
      - '[groupLine]'
      - '&e========================'
      staffLine: '&eStaff online: &f[list]'
      adminLine: '&eAdmin online: &f[list]'
      hiddenLine: '&eHidden: &f[list]'
      groupLine: '&e[groupName]: &f[list]'
      playerFormat: '&e[playerDisplayName]'
      # Add as many groups as you wish, by default there is only 10, to create new one, just copy paste one line and add increment into lines name, like group11 or group12 and so on.
      # Player have to have appropriate permission node to be plaecd in group cmi.command.list.group.[groupnumber], bigger number have priority
      groups:
        group1: '&eGroup1: &f[list]'
        group2: '&eGroup2: &f[list]'
        group3: '&eGroup3: &f[list]'
        group4: '&eGroup4: &f[list]'
        group5: '&eGroup5: &f[list]'
        group6: '&eGroup6: &f[list]'
        group7: '&eGroup7: &f[list]'
        group8: '&eGroup8: &f[list]'
        group9: '&eGroup9: &f[list]'
        group10: '&eGroup10: &f[list]'
      noGroupLine: '&eList'
```
