### ISSUE TITLE
Different chat hover/click actions for staff

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4507]
**Description of feature/improvement request:**
It would be cool to be able to have different click and hover actions for staff.

For instance, we could add this to the Locale_EN.yml
```yml
  altPublicHover: '[senderDisplayName] aka [senderName]\n&eSent time: &6%server_time_hh:mm:ss%\nPlayed since %parseother_[senderName]_player_first_join_date%'
  altPrivateHover: '[senderDisplayName] aka [senderName]\n&eSent time: &6%server_time_hh:mm:ss%\nPlayed since %parseother_[senderName]_player_first_join_date%'
```
and if the player has, for instance, the `cmi.chathovergroup.alt` it would show them these hover messages instead of the normal ones.

In addition to this, we could also change the config.yml to have this
```yml
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true

  AltClickAction: '/tp [senderName]'  #<<<-------------This is the new line
```
and players with the `cmi.chathovergroup.alt` would have this action run when they click on a players name in chat.

---
### Detailed explanation of what it should do, when and in what situation: ###
This would show staff members, or anyone with the `cmi.chathovergroup.alt` permission additional/different information about the player that send the chat message.
In addition to this, the chat AltClickAction would make it a bit easier for staff to tp to players. For instance if a player says "Help, jimmy is killing my horses" a staff member could just click on the chat message and it would tp them to the players position

### Basic explanation as to why this feature is needed and/or useful to have: ###
Explained above. but its also nice to have the customization.
