### ISSUE TITLE
Player's drop head when using a totem of undying

### ISSUE THREAD

**Issue by 27chandler** [Zrips/CMI#4509]
**Description of issue:**
When a player is attacked until they use a totem of undying to prevent death, CMI counts it as a death and drops the player's head.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Heads:
    Player:
      Drop: true
      Percentage: 33
      LowerChanceOfterDrop: 50.0
      LootBonus:
        Enabled: false
        Lvl1: 5.0
        Lvl2: 15.0
        Lvl3: 30.0
    Mob:
      Drop: true
```

---

CMI: 8.7.9.3

PaperSpigot

Paper Build 246
