### ISSUE TITLE
[Bug/feature request] Disable riptide when a user has /pweather rain

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4543]
**Description of feature/improvement request:**
Pretty simple. Basically in its current state, when a user has `/pweather rain` on, they can throw their trident. 
Which is a little bit of a problem cause it causes anti-cheats to go crazy.

Simple solution, you just have a config option somewhere that is either true or false. 
It would be called `AllowRiptideInPweather:` and if set to true, when a player goes to throw a riptide trident, it would check the servers weather for the world that they are in, and if its sunny(or just not rainy), and if they are not standing in water, it would cancel the trident throw event.

Alternately, you could also add a permission thats like `cmi.command.pweather.riptide` which would either allow/disallow throwing a trident while its ONLY rainy on the players pweather. 

Edit: If you use `/pweather rain` and use a riptide trident and chain them together to fly, the player gets kicked for 'Flying is not enabled on this server' which is the default (spigot i think?) no flying kick, which makes this feel alot more like a bug that needs fixed rather than a feature request.

---
### Detailed explanation of what it should do, when and in what situation: ###
See above

### Basic explanation as to why this feature is needed and/or useful to have: ###
Its a needed feature as when players throw a trident in (server side)sunny weather but rainy pweather, anti-cheats assume they are speed/fly hacking. This is an issue imho.

**Comment by MrMcyeet** [comment]
also, while im here, im gonna put this here instead of in a new post, but with cmi's chat filter, I cant seem to get the regex to do what I want it to do.

I want `:)` to get changed to `☺` which ive already done just fine with this in my config
```
      smile1:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - \:\)
        ReplaceWith: ☺
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
```
But now I want to change it to  NOT change `>:)` to `>☺` cause thats kind of annoying. 
but with this in my config it says check my spelling on `/cmi reload`
```
      smile1:
        Enabled: true
        Group: Emote
        InformConsole: false
        Regex:
        - [^>]\:\)
        ReplaceWith: ☺
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
        Commands: []
```
and in my text editor, it highlights the ` [ ] ` (see pic), normally anything in these fields are just yellow. any way around this?
Ive already tried wrapping the line like this `        - '[^>]\:\)'` and `        - "[^>]\:\)"` but with no luck.
