### ISSUE TITLE
Repost: perm:[permission] in eventcommands not working anymore

### ISSUE THREAD

**Issue by KyroOW** [Zrips/CMI#4549]
**Description of issue:**
perm:[permission] is not working in eventcommands.yml anymore, the command gets executed even if the player doesn't have the permission

I'm reposting this, AGAIN, as it was closed without even obtaining an answer, this is broken since more than a YEAR.

EDIT: Tried with latest of the latest version, still happening....

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  - perm:cmi.tagpvp! lp user [playerName] permission unset animatednames.group.defaultpvp
playerKillPlayer:
  # [sourceName] to insert source player name
  # [sourceDisplayName] to insert player display name
  # [sourceLvl] to insert player level
  # [sourceExp] to insert player total exp
  # [sourceHp] to insert player health
  # [sourceMaxHp] to insert player max health
  # [sourceHunger] to insert player hunger level
  # [sourceGameMode] to insert player gamemode
  Enabled: true
  Commands:
  - perm:cmi.arenepomme! cmi give [sourceName] 322 1 -s
  - perm:cmi.arenepomme! cmi actionbarmsg [sourceName] &6&l+1 Pomme d'Or !
```

---

**Cmi Version (using`/cmi version`):** 

8.7.10.3

**Server Type (Spigot/Paperspigot/etc):** 

paper 1.12.2

**Comment by CloudeLecaw** [comment]
be sure this was working before? Itshould not
why?
see here
```
playerGameModeChange:
  Enabled: true
  Commands:
  - say hi
```
![Snag_628e1b3](https://user-images.githubusercontent.com/12080017/98449368-46372580-2133-11eb-8ac1-c5eeb3b47c96.png)

So what does this mean?
It means if you ask for permisssion it will ask the console if the console has the permission
and so this condution is true and the command you get up is executed
asking for permissions is nothing for evencommands and also not for parts like the scheduler
