### ISSUE TITLE
Rank item not being register

### ISSUE THREAD

**Issue by Dutasmilas** [Zrips/CMI#4550]
**Description of issue:**

Some rank item and requirement is not being register
one item i found not working is redstone dust
requirement such as dive is also not working.I tried walking in water,swimming in water,it wont register progress.
![bug](https://user-images.githubusercontent.com/67474322/98447743-2b2fda00-2162-11eb-9c6c-6e8d2cc14011.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
MightyAdventurerII:
  Enabled: true
  DisplayName: '&2Mighty Adventurer II'
  AutoRankup: false
  MoneyCost: 45000
  Votes: 42
  NextRanks:
  - MightyAdventurerIII
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Mighty Adventurer II rank!
  - broadcast! &6[playerDisplayName] &eRecieve &5000,300&c&lexp,&95 diamond &efor
    ranking up!
  - experience add [PlayerName] 300
  - cmi cheque [playerName] 5000
  - give [PlayerName] diamond 5
  - lp user [playerName] parent add mightyadventurerii
  - lp user [playerName] parent remove mightyadventureri
  StatsRequirements:
  - PlayTime:61200
  - walk:2500
  - MonsterKills:200
  - BlocksMined:500
  - AnimalsBred:20
  ItemRequirement:
  - cobweb:64
  - apple:20
  - redstone dust:64
  - diamond:64
  - iron ingot:64
  McMMORequirement:
  - Archery:30
  - Swords:30
  - Taming:15
#######################################
```

---

**Cmi Version (using`/cmi version`):*8.7.9.3*

**Server Type (Spigot/Paperspigot/etc):*paper* 

**Server Version (using `/ver`):*1.16.3* 

**Relevant plugins (Delete if this isn't needed):**
