### ISSUE TITLE
Combat Timer Bossbar

### ISSUE THREAD

**Issue by naikyys** [Zrips/CMI#4557]
**Description of issue:** Hello, im trying to disable that Combat bossbar timer and nothing works. I tried already these things:

Timer: -1
Timer: 0

and nothing works, so this sounds like issue. I would be so grateful for fixxing this problem because it is so annoying to kill monsters and mobs with some bossbar at the top.

**CONFIG SECTION:**
```
Combat:
  # Defines combat timer to be used in particular features
  Timer: 0
  # Prevents damage from players with god mode enabled
  # Can be bypassed with cmi.pvp.godBypass permission node
  noGodDamage: true
  # informs player that he cant damage players while in god mode
  noGodDamageInform: true
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: true
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: false
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: false
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: false
    AllowedCommands:
    - msg
    - r
    - tell
```
---

**Cmi Version (using`/cmi version`):** CMI: 8.7.10.3

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** The newest build of Tuinity

**Comment by EkonC** [comment]
Try setting
`ShowBossBar: false`
under the Mob section which you didn't show us

My config (which works):
```
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: false
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: false
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: false
    AllowedCommands:
    - msg
    - r
    - tell

```
