### ISSUE TITLE
/repair all - broken

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4564]
**Description of issue:**

---
Hi, since the update from Oct 24 when you included:

> Some improvements relating to cooldown recognition when it comes to commands with same core prefix, like /fix and /fix all and /fix hand now all can have their own cooldowns

It almost fixed the issue https://github.com/Zrips/CMI/issues/3998, but the problem appeared.... Now it doesn't work anyway.

I use /repair all, and then cooldown for normal repair is activated from some reason.
![image](https://user-images.githubusercontent.com/18662086/98558868-3d1a9580-22a6-11eb-8fb8-c67adbd032fb.png)
Strings:   repairConfirm and then Cooldowns
Previously before this update repair: cooldown didn't count to repair all: cooldown.

I think that when player use /repair all, and then click on it to accept it, it should normally be executed without triggering cooldown for normal repair.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Repair:
    # When item costs money, player will be required to confirm repair action by clicking message in chat
    Confirmation: true
    # When set to true, item repair with /cmi repair will cost money depending on setup
    # Player who performs command will pay repair cost
    # If command gets performed from console, then player whose items are repaired will be paying
    CostsMoney: true
    # Base price to repair item
    # If you have enabled durability check, then this value will wary depending on items condition
    BasePrice: 1000.0
    # Item repair cost will depend on how baddly item is damaged
    CheckDurability: true
    # Adds extra cost to repair depending on items cost set in /cmi setworth
    # Value should be set from 0 to 100 range
    WorthPercentage: 20.0
    # Adds extra cost to repair depending on items enchantment cost set in /cmi setenchantworth
    # Value should be set from 0 to 100 range
    # If item has more then one enchantment, then prices will be added up
    enchantWorthPercentage: 35.0
```

---

**Cmi Version (using`/cmi version`):**  8.7.10.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 261
