### ISSUE TITLE
Drop Spawner

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#4586]
**Description of issue:**
Hello,

With permission to retrieve cave spider spawners, players equipped with a silk touch see the message "Failed to mine spawner. 0% drop chance" and don't get the spawner.  

They have the permissions:  
- cmi.dropspawner
- cmi.drospawner.cavespider (or cave_spider)

**CONFIG SECTION :**
```
Spawners:
  FullDisable: false
  Break:
    Enabled: true
    RequiresExactPermission: true
    DropExp: false
    SilkTouchLevel: 1
    BaseDropChance: 100
```

---

**Cmi Version :** 
8.7.10.4

**Server Type:** 
Purpur (paper)

**Server Version:** 
purpurclip-821 (1.16.4)
