### ISSUE TITLE
[Feature Request] Vanish (fake) join/leave vanish change message sent to DiscordSRV channel?

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#4600]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
It should send a fake (DiscordSRV) join/leave message if you have the support for DiscordSRV enabled and if you have the fake join/leave message enabled in your vanish edit GUI. 
### Basic explanation as to why this feature is needed and/or useful to have: ###
If you have the fake join/leave message enabled, you may vanish and it'll send a message ingame while nothing will be sent in DiscordSRV chat channel. This would be nice to possibly add at somepoint.

**Comment by mrfloris** [comment]
To be honest, and not to take away from your request, what I have done is make a command like /hide, and /unhide, that where i use certain params to optionally announce leaves/joins. And am using the discord announcement feature to fake an event to discord channels when i also want to show as leaving or joining in-game. 

`asConsole! discordsrv broadcast :emojiyouwant: **[Prefix] The player [playerName] lef the server`
obviously adjust to your server.

And /unhide for example could look like this
```
  unhide:
    Cmds:
    - asConsole! cmi vanish [playerName] off
    - asConsole! cmi gm [playerName] creative -s
    - asConsole! cmi god [playerName] true -s
    - asConsole! cmi heal [playerName] 100% -s
    - asConsole! cmi effect [playerName] clear -s
    - asConsole! cmi fly [playerName] true -s
    Perm: true
```

i've extended it with `check:$1==msg! ..etc` to then spit out the fake join msg to discord and in-game.
