### ISSUE TITLE
Tag RepairCost

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4603]
**Description of issue:**

---

Hi, I don't know from what reason, but my players told me that they found elytra multiple times in end city, then they didn't use it, didn't repair it and wanted use it for crafting, but they can't use it for crating due to special tag RepairCost: 7 that's used there from some reason. Could this be fixed please? And the most weird is that I have disabled RepairShare.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ItemRepair:
  RepairShare:
    # When neabling you will need to perform full server restart for it to take effect
    # When enabled will prevent players repairing items for others in anvil regular way. They still can use items and repairs normaly for them selfs
    # Can be bypassed with cmi.command.repair.repairshare.bypass
    ProtectNormalRepair: false
    # When enabled will prevent players repairing items for others with CMI command. They still can use items and repairs normaly for them selfs
    ProtectCommandRepair: false
    # Sets durability on item when another picks it up or selects in inventory. Set to 0 or less if you don't want to change durability
    # Attention! Keep this number above 0, otherwise item will get removed without option for the player to repair it throw some means, unless this is what you actually want
    Durability: 100
    # When set to true, player who have cmi.command.repair permission will bypass this protection and can use other user repaired items without any additional actions
    BypassWithRepairPermission: false
    # When enabled additional lore line will be added when player can't use that item. This will not be shown for owner of item
    AddLore: true
    # When set to true, interact event will be canceled to prevent item usage
    CancelEvent: true
    # When set to true, player will get message informing about item usage he dint repaired him self
    InformWithMessage: true
  Repair:
    # When item costs money, player will be required to confirm repair action by clicking message in chat
    Confirmation: true
    # When set to true, item repair with /cmi repair will cost money depending on setup
    # Player who performs command will pay repair cost
    # If command gets performed from console, then player whose items are repaired will be paying
    CostsMoney: true
    # Base price to repair item
    # If you have enabled durability check, then this value will wary depending on items condition
    BasePrice: 1000.0
    # Item repair cost will depend on how baddly item is damaged
    CheckDurability: true
    # Adds extra cost to repair depending on items cost set in /cmi setworth
    # Value should be set from 0 to 100 range
    WorthPercentage: 20.0
    # Adds extra cost to repair depending on items enchantment cost set in /cmi setenchantworth
    # Value should be set from 0 to 100 range
    # If item has more then one enchantment, then prices will be added up
    enchantWorthPercentage: 35.0
```

---

**Cmi Version (using`/cmi version`):** 8.7.10.5

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 265
