### ISSUE TITLE
Slimefun reinforced spawners by it's type aren't respected

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4605]
**Description of issue:**

---

Hi, when you have enabled that CMI controls place, then when you place reinforced spawner, with type creeper for ex., then there's placed pig spawner.
Crafting:
![image](https://user-images.githubusercontent.com/18662086/99160032-15cb2a80-26e3-11eb-83ff-e4e2e02712fb.png)
Use /sf searchto discover recipe, then /sf give <name_of_item>, broken spawner you can earn by pickaxe of contaiment, when you mine specific type of spawner and this one you can repair in ancient altar to reinforced spawner with specific type.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: true
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player wil
```
When place enabled is true, then it doesn't work. I know that I can set it false, BUT then permissions that i'm using too won't work... And I wanted to use permissions for it, but this way it probably won't work. So, couldn't you try fix this specific problem with Slimefun?

---

Cmi Version (using/cmi version): 8.7.10.5

Server Type (Spigot/Paperspigot/etc): Paper

Server Version (using /ver): 265
