### ISSUE TITLE
Bug DropSpawner

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#4610]
**Description of issue:**
Hello,

With permission to retrieve cave spider spawners, players equipped with a silk touch see the message "Failed to mine spawner. 0% drop chance" and don't get the spawner.

They have the permissions:

cmi.dropspawner
cmi.drospawner.cave_spider

it does the same with all dropspawner permissions, and the problem remains even if CMI is the only plugin on the server.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Spawners:
  FullDisable: false
  Break:
    Enabled: true
    RequiresExactPermission: true
    DropExp: false
    SilkTouchLevel: 1
    BaseDropChance: 100
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.4

**Server Type (Spigot/Paperspigot/etc):** 
Purpur (paper)

**Server Version (using `/ver`):** 
purpurclip-821 (1.16.4)
