### ISSUE TITLE
Ability to disable arg suggestions for custom aliases

### ISSUE THREAD

**Issue by nemmynaomi** [Zrips/CMI#4634]
**Occasionally, custom commands will incorrectly suggest stuff, this is expected.**
---
**However**, this may cause confusion for inexperienced users, and annoyance for those who are experienced.

![A screenshot of the alias for reference. (lp user $1 parent add $2)](https://user-images.githubusercontent.com/72463576/99713320-22001080-2a72-11eb-9b7d-282c7129dffc.png)
![A gif screenshot of the suggestions received.](https://user-images.githubusercontent.com/72463576/99712599-49a2a900-2a71-11eb-89ea-b3731ee7146d.gif)

My suggestion, allow to completely disable them, such as the following;
```yml
  addrank:
    Cmds:
    - lp user $1 parent add $2
    Suggestions: false
```
