### ISSUE TITLE
Sethome for other players doesn't work properly

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#4647]
When you create a home for another player (`/sethome Test Fangorn`) a success message will appear in the chat. The Home will not be set to the current position, but to the current position of the back-point. In addition, the display in the Home GUI is then no longer correct. The number of available homes is set to one and does not correspond to the permission and therefore not to the actual number of available homes. 
![Home-Bug](https://user-images.githubusercontent.com/24480321/99905562-d481de80-2cd1-11eb-8c5b-71700677757d.PNG)
There are no erros in the log.

CMI 8.7.10.8
Paper 1.16.3 - build 246
```
Homes:
  # Open gui when using /cmi home command if you have more then one home in your saved list
  Gui: true
  # Homes groups to define max amount homes player can have. Permission: cmi.command.sethome.[groupname]
  # If players home group if not find then amount will be set to 1
  # To have unlimited homes use cmi.command.sethome.unlimited permission
  # In addition to this you can use simple numeric permission node cmi.command.sethome.[number] which will define max number of homes player can have
  Groups:
    default: 2
    ProMember: 3
    EhrenMember: 5
    SuperMember: 7
    Elite: 9
    Legende: 11
    staff: 20
  # Requires cmi.bedhome permission node
  # When set to true by interacting with bed, regular home location will be created
  # When set to false vanilla bed home location will be set
  BedInteraction: false
  # When set to true, you can only set home location when you shift click a bed
  onlyShiftBed: false
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: true
  # When enabled, plugin will check if player can break block in that area before creating new home location
  # This allows to prevent setting homes in protected areas
  # Can be bypassed with cmi.command.sethome.bypass
  CheckBlockBreak: false
  # Name for default home location. By default its "Home"
  DefaultName: Home
  # Name for bed location. By default its "Home"
  # Different name can be used to identify home location set by interacting with a bed from home location created with command
  DefaultBedName: Home
  # Defines what characters you can use in your home names
  ValidNameRegex: '[^a-zA-Z0-9\-\_]'
```
Permissions:
![Permissions](https://user-images.githubusercontent.com/24480321/99905699-c54f6080-2cd2-11eb-9021-ec006ab6d085.PNG)
