### ISSUE TITLE
(feature) Friendlier chat filter

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#4648]
Hey zrips,

Under `chatfilter:` it would be nice if there's a more friendly find/replace for chat that has nothing to do with filters, and doesn't risk the player getting warning points or staff msgs or sanctions of sorts. And keep swearing to swearing. Would this be possible? The request has come up a few times, i thought it was time to post a request for it.

Basically what the user types:
` Yo mah bois, luv ya <3`

What CMI does:
```
friendlyFilter:
      heart:
        Enabled: true
        Group: emoji
        Regex:
        - '<3'
        ReplaceWith: `{#Feijoa}❤{#Cerulean}`
        includePrivateMessages: true
      smiley:
        Enabled: true
        Group: emoji
        Regex:
        - ':)'
        ReplaceWith: `{#Feijoa}☆{#Cerulean}`
        includePrivateMessages: true
```

Certain swearing features like commands and staffmsg etc aren't needed. Nor complex regex maybe?

<img width="287" alt="Screenshot 2020-11-22 at 18 15 44" src="https://user-images.githubusercontent.com/28841349/99910516-bf677880-2cee-11eb-98cf-02825ee0943c.png">

<img width="476" alt="Screenshot 2020-11-22 at 18 09 25" src="https://user-images.githubusercontent.com/28841349/99910386-f1c4a600-2ced-11eb-8397-beb73558b7c9.png">
<img width="320" alt="Screenshot 2020-11-22 at 18 09 36" src="https://user-images.githubusercontent.com/28841349/99910387-f2f5d300-2ced-11eb-993b-a9d012ba57f0.png">

Thank you for considering. 

(and no, this isn't full unicode emoji support, i understand that is `:hello:` replacement with resource packs.
