### ISSUE TITLE
Disable Combat Module

### ISSUE THREAD

**Issue by EnderGamingFilms** [Zrips/CMI#4654]
Can you please add a way to disable the combat module for CMI. I have searched through the config and there does not appear to be any section to just disable it altogether. I use a custom combat management plugin and I don't want to stop using CMI because of this. I see you can disable other modules and I don't see why you shouldn't be able to disable the Combat handling.

**Comment by EkonC** [comment]
Just set everything to false in Players: and Mobs: under the Combat section in config.Ulm

**Comment by EnderGamingFilms** [comment]
Why isn't there a tagging section. Because there are some decent features in combat. but the tagging system is not needed because it can't do anything other than block commands. (my system runs commands when a player enters combat) There should just be a true false for those features.

**Comment by EkonC** [comment]
Your config.yml will have to look something like this to have Combat mode disabled.
```
Combat:

...

  Player:
    DisableFlight: false
    DisableFallDamage: false
    ShowBossBar: false
    BlockCommands: false
    AllowedCommands:
    - msg
  Mob:
    DisableFlight: false
    DisableFallDamage: true
    ShowBossBar: false
    BlockCommands: false
    AllowedCommands:
    - msg
```
I'm not sure if there is a module in modules.yml which this Combat section belongs to and would be able to disable it entirely but try playing with those options and maybe one of them will work for that.

Running commands on entering combat mode would be a great feature though.
