### ISSUE TITLE
WarmUps doesn't work with CustomAlias commands

### ISSUE THREAD

**Issue by thboehi** [Zrips/CMI#4656]
**Description of issue:**
https://github.com/Zrips/CMI/issues/4420

Warmups doesn't work on CustomAlias commands.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :3:false:GlyphHead
  - cmi back:3:false:GlyphHead
  - cmi warp :3:false:GlyphHead
  - cmi home :3:false:GlyphHead
  - cmi spawn:3:false:GlyphHead
  - kraken:3:false:GlyphHead
  - royaume:3:false:GlyphHead
  - bicrew:3:false:GlyphHead
  - aodla:3:false:GlyphHead
  - skyshop:3:false:GlyphHead
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.8
**Server Type (Spigot/Paperspigot/etc):** 
PaperMC
**Server Version (using `/ver`):** 
1.16.4
