### ISSUE TITLE
Spawners couldn't be placed by it's type (even when place is false and players have perm)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4672]
**Description of issue:**

---

Hi, from some reason players can't place spawner by it's type. I as admin with * can normally place it and it changes from pig to for ex. spider, but for players spawners don't change. I earned spawner by placing spawner from /give spawner on the ground (the pig one), then I changed type with spawner egg, then I mine it and it dropped and then I gave it to players and after they place it it's pig spawner instead of specific type spawner. Players also have placespawner permission, placespawner.* etc.... but anything doesn't work.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: true
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 4
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: false
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: false
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: false
  Interact:
    # When set to true, players trying to change spawner with monster egg will require appropriate permission node
    # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
    EggRequiresPermission: true
  # If set to true, spawners will have chance to be dropped when destroying with tnt
  TnTExplosionDrop:
    use: false
    # Chance in percentage for spawner to drop
    Chance: 30
  # If set to true, spawners will have chance to be dropped when destroyed by creeper
  CreeperExplosionDrop:
    use: false
    Chance: 30
  Charges:
    # When enabled players will be assigned to particular spawner charges group who have cmi.spawners.charge.[groupName] permission node
    # Players will be limited to how many spawners they can mine
    # StartingCharge will determine how many charges they will have on first time joining group
    # MaxCharge will limit to how many charges you can have at one time
    # Cooldown determines how often new charge will be given
    # Bonus is optional and it will determine by how many seconds to lower cooldown for next charge when placing spawner
    # Option to bypass limitations with cmi.spawners.charge.bypass
    Use: true
    # If set to true when player runs out of spawner charges spawner will be destroyed without droping it
    BreakWithoutCharge: false
    List:
      Default:
        Use: true
        StartingCharge: 2
        MaxCharge: 2
        Cooldown: 43200
        Bonus: 3600
      upgrade1:
        Use: true
        StartingCharge: 2
        MaxCharge: 3
        Cooldown: 43200
        Bonus: 3600
      upgrade2:
        Use: true
        StartingCharge: 2
        MaxCharge: 4
        Cooldown: 21600
        Bonus: 3600
      upgrade3:
        Use: true
        StartingCharge: 4
        MaxCharge: 5
        Cooldown: 21600
        Bonus: 3600
      upgrade4:
        Use: true
        StartingCharge: 4
        MaxCharge: 6
        Cooldown: 21600
        Bonus: 3600
      upgrade5:
        Use: true
        StartingCharge: 4
        MaxCharge: 7
        Cooldown: 21600
        Bonus: 3600
      upgrade6:
        Use: true
        StartingCharge: 6
        MaxCharge: 8
        Cooldown: 21600
        Bonus: 3600
      upgrade7:
        Use: true
        StartingCharge: 6
        MaxCharge: 9
        Cooldown: 21600
        Bonus: 3600
      upgrade8:
        Use: true
        StartingCharge: 6
        MaxCharge: 10
        Cooldown: 21600
        Bonus: 3600
      vip+:
        Use: true
        StartingCharge: 10
        MaxCharge: 15
        Cooldown: 21600
        Bonus: 3600
      mvip:
        Use: true
        StartingCharge: 10
        MaxCharge: 20
        Cooldown: 21600
        Bonus: 3600
      mvip+:
        Use: true
        StartingCharge: 10
        MaxCharge: 25
        Cooldown: 21600
        Bonus: 3600
      evip:
        Use: true
        StartingCharge: 15
        MaxCharge: 30
        Cooldown: 21600
        Bonus: 3600
      neovip:
        Use: true
        StartingCharge: 15
        MaxCharge: 35
        Cooldown: 21600
        Bonus: 3600
  Proximity:
    # Allws to limit how tight spawners can be placed from each other
    Use: true
    # Radius in blocks from blaced block. Max range is 16
    # Can bypass with cmi.spawners.proximity.bypass
    Range: 3
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items
  # Option to define specific name by using regex format
  Prevent: false
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/100650430-3383cb00-3344-11eb-9a09-66cf85c09bfe.png)

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/100650419-2ebf1700-3344-11eb-8c3b-1bfc4e4131f4.png)

**Relevant plugins (Delete if this isn't needed):**
