### ISSUE TITLE
moneycost broke in some ICs in some cases only.. example - when combined with asPlayer!

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4673]
when moneycost is used in an ic the command seems to be executed without taking the money..

```
SignierSchmied:
  Locations:
  - world;-80.0;64.0;270.0
  Commands:
  - click:left#! cooldown:2?#! hasmoney:5@! msg! [playerName] &fDu brauchst mindestens &e&l5 Taler &fum deinen Gegenstand signieren zu lassen&f. Du besitzt aktuell nur &e&l%cmi_user_balance_formatted% Taler&f.
  - pex user [playerName] timed add RHSignItem.use 1 world
  - delay! 0.1
  - moneycost:5! asPlayer! rhsignitem:sign &7
  - delay! 0.1
  - msg! [playerName] &fDein neuer Kontostand ist &e&l&l%cmi_user_balance_formatted%&f.
  ReqPerm: false
```
**Edit: On other ICs it works fine, so it seem like the issues seems just to effect this special case...**

![Snag_33691e1](https://user-images.githubusercontent.com/12080017/100809038-930dd380-3435-11eb-81a3-feabc8b89633.png)

![Snag_337bff1](https://user-images.githubusercontent.com/12080017/100809124-bfc1eb00-3435-11eb-895b-539c583b9c97.png)

The item, the IC is attached with is an anvil.

This IC was working fine before...

**Edit: On other ICs it works fine, so it seem like the issues seems just to effect this special case...**
