### ISSUE TITLE
IncludeInTabComplete doesn't work?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4704]
**Description of issue:**

---
Hi, I have problem that includeintabcomplete option doesn't work for me from some reason.  For ex I, Renzotom, changed nickname to "doesntwork" and it's not listed there. Could you please check if it's really working? And give me an idea, what could be wrong there?
![image](https://user-images.githubusercontent.com/18662086/101296730-5b33d100-3825-11eb-870e-85cf553b920d.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
NickName:
  # Prevents players to change their nick name to one of defined without permission
  # Use lower case
  # cmi.command.nick.bypassblacklist
  # to bypass protection against already in use name/nickname use cmi.command.nick.bypassinuse
  BlackList:
  - admin
  - administrator
  - server
  - staff
  - staf
  - helper
  - pomocník
  - pomocnik
  - stavitel
  - builder
  - architekt
  - spravce
  - správce
  - technik
  - engineer
  - dev
  - manager
  - manažer
  - vip
  - op
  - debil
  - blbec
  - idiot
  - dement
  - kund
  - štětk
  - děvk
  - stetk
  - devk
  - pizda
  - pussy
  - fuck
  - kurv
  - kurev
  - horny
  - nadržen
  - aroused
  - hentai
  - porn
  - slut
  - slag
  - boob
  - vagin
  - penis
  - péro
  - pero
  - pele
  - dick
  - cock
  - bugger
  - bastard
  - cunt
  - nigga
  - nigger
  - jerk
  - vyhoni
  - anal
  - anál
  - wanker
  - tosser
  - shit
  - hovn
  - srá
  - sra
  - rape
  - rapist
  - whore
  - bitch
  - asshole
  - twat
  - titt
  - piss
  - sex
  - gay
  - lesb
  - homo
  - teplouš
  - intercourse
  - cum
  - sperm
  - spunk
  - testicle
  - milf
  - retard
  - anus
  - dafuq
  - prick
  - wtf
  - douche
  - prostitut
  - ffs
  - pedo
  - deb
  - blb
  - kkt
  - zmrd
  - svině
  - dement
  - imbecil
  - chcát
  - chcal
  - chčít
  - kokot
  - kretén
  - pič
  - jeb
  - mrd
  - buz
  - čurák
  - čurak
  - kripl
  - krypl
  - prdel
  - čubk
  - idiot
  - posrán
  - cigán
  - cikán
  - cigoš
  - cikoš
  # Min length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MinLength: 4
  # Max length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MaxLength: 16
  # Adds prefix for players nickname to indicate that its not real name. This can be added to display name with {nicknameprefix}
  Prefix: '~'
  # When true, will only add nickname prefix when its not same as original name. This can allow colorization or capitalization change without addign prefix
  PrefixWhenDifferent: true
  # When true, online players nick name will be included into tabcomplete
  IncludeInTabComplete: true
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 312

**Relevant plugins (Delete if this isn't needed):** ChatControl, maybe?
