### ISSUE TITLE
CMI Chat Filter Is Case Sensitive (Which Isn't Ideal)

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Zrips/CMI#4707]
**Description of issue:**
The Regex chat filter is case-sensitive which is not desirable in this situation.
I.e. Say I want to block "bitch" and variations of it:
`\b(b+(\W|\d|_)*(i|1|\!|\-|\_|\*)+(\W|\d|\!|\-|\_|\*)*(t|n)+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*)`
At least with ChatControlPro (which also uses regex) the line above would block 'bitch' & variations (i.e. 'b1tch' & 'BItch'). But with CMI it only blocks lowercase ones like 'bitch'. And does **not** block Bitch, BITCH, BITch, etc (anything with an uppercase letter).

If this is intended, I recommend changing it or adding a configurable option for it. Because while I'm sure there is a way around this for server owners to configure, it adds unnecessary extra steps.

Image: (Shows in Minecraft chat sending 'bitch' vs 'BITCH' using the "others" blockType. Right screen sent the msgs.)
https://gyazo.com/c502ebd2e6ea46322f495a1b9b983c52

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
      swearing1:
        Enabled: true
        Group: Swearing
        InformConsole: false
        Regex:
        - \b((a|\@)+(\W|\d|_|\@)*(s|5|$)+(\W|\d|_)*(s|5|$)+(\W|\d|_)*h+(\W|\d|_)*(o|0)+(\W|\d|_)*(l|1)+(\W|\d|_)*(e|3)+(\W|\d|_)*)
        - \b(n+(\W|\d|_)*(i|1|\*|\!|\-|\_)+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*(e|3|0|o)+(\W|\d|_)*r+(\W|\d|_)*)
        - \b(n+(\W|\d|_)*(i|1|\*)+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*(a|\@)+(\W|\d|_)*)
        - \b(n+(\W|\d|_)*(i|1|\*|\!|\-|\_)+(\W|\d|_)*g+(\W|\d|_)*g+(\W|\d|_)*(e|3|0|o)+(\W|\d|_)*r+(\W|\d|_)*)
        - \b(f+(\W|\d|_)*(a|\*|\_|\-|\@)+(\W|\d|_)*(g|6)+(\W|\d|_)*)\b
        - \b((f)+(\W|\d|_)*(a|\@|\*|\-|\_)+(\W|\d|_)*(g|6)+(\W|\d|_)*(g|6)+(\W|\d|_)*(o|0|\*|\_|\-)+(\W|\d|_)*(t|\*)+(\W|\d|_)*)
        - \b(b+(\W|\d|_)*(a|\@)+(\W|\d|_)*(s|5)+(\W|\d|_)*t+(\W|\d|_)*(a|\@)+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
        - \b(c+(\W|\d|_)*u+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*)
        - \b(p+(\W|\d|_)*u+(\W|\d|_)*(s|5)+(\W|\d|_)*(s|5)+(\W|\d|_)*y+(\W|\d|_)*)
        - \b(r+(\W|\d|_)*(a|\@)+(\W|\d|_)*p+(\W|\d|_)*(i|1|\!)+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*)
        - \b(w+(\W|\d|_)*h+(\W|\d|_)*(o|0)+(\W|\d|_)*r+(\W|\d|_)*(e|3)+(\W|\d|_)*)
        - \b(b+(\W|\d|_)*(i|1|\!|\-|\_|\*)+(\W|\d|\!|\-|\_|\*)*(t|n)+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*)
        - \b(m+(\W|\d|_)*(i|1|\-|\_|\*)+(\W|\d|\-|\_|\*)*(l|1)+(\W|\d|_)*f+(\W|\d|_)*)
        - \b(r+(\W|\d|_)*(e|3)+(\W|\d|_)*t+(\W|\d|_)*(a|\@)+(\W|\d|_)*r+(\W|\d|_)*d+(\W|\d|_)*)
        - \b((a|\@)+(\W|\d|_)*n+(\W|\d|_)*u+(\W|\d|_)*(s|5)+(\W|\d|_)*)
        - \b(p+(\W|\d|_)*r+(\W|\d|_)*(i|1|\*|\!)+(\W|\d|\_|\*|\!)*c+(\W|\d|_)*k+(\W|\d|_)*)
        - \b(d+(\W|\d|_)*(o|0)+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*h+(\W|\d|_)*(e|3)+(\W|\d|_)*)
        - \b(p+(\W|\d|_)*r+(\W|\d|_)*(o|0)+(\W|\d|_)*(s|5)+(\W|\d|_)*t+(\W|\d|_)*(i|1|\*|\_)+(\W|\d|_)*t+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*(e|3)+(\W|\d|_)*)
        - \b(p+(\W|\d|_)*(e|3)+(\W|\d|_)*d+(\W|\d|_)*(o|0)+(\W|\d|_)*)
        - \b(m+(\W|\d|_)*(o|0)+(\W|\d|_)*f+(\W|\d|_)*(o|0)+(\W|\d|_)*)\b
        ReplaceWith: ''
        BlockType: others
        includePrivateMessages: true
        msgToStaff: ''
        Commands:
        - msg [senderName] &cChat Warning - Don't swear!
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.10.8 SqLite-> 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper(200) 1.16.3-R0.1-SNAPSHOT

**Server Version (using `/ver`):** Paper version git-Paper-200 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

Please fix if it hasn't been in later versions. Thanks!

**Comment by PiggiesGoSqueal** [comment]
Please Note: I will not check this again probably. I think I'll just use ChatControlPro to save time but other people may run into this issue as well hence why I reported it.

**Comment by w41k3r26** [comment]
I was able to replicate the bug. Facing the same issue.

**Comment by CloudeLecaw** [comment]
this just shows us there are many versions how we can use that
try this one if you want:) this one is sees bitttchh BITITTCCH or BITCCssschh
and others. may it does not see b!tch so add one wuth the ! :)

```
      swearing26:
        Enabled: true
        Group: swearing
        InformConsole: true
        Regex:
        - \b(?i)(b+(\W|_?)+i+(\W|_?)+t+(\W|_?)+c+(\W|_?)+h+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - cmi msg [senderName] &eFluchen ist hier nicht er
```
