### ISSUE TITLE
Slimefun pickaxe of containment + break chance + no silk  -> duplicating spawners

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4775]
**Description of issue:**

---

Hi, spawners could be duplicated using Pickaxe of containment from Slimefun (/sf give <player> pickaxe_of_containment) and mining spawners with some chance for dropping on them + with permission to drop them without silk. Then you can duplicate them and mine 2 as 1.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: true
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 4
```
But I've set: **cmi.dropspawner.nosilk** & cmi.dropspawner.basedropchance.90 (for ex., btw you should also edit your Wiki page, this permission node & many other are missing there)

And then this could happen:
https://streamable.com/3ezmlu

---

**Cmi Version (using`/cmi version`):** 8.7.12.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 335

**Relevant plugins (Delete if this isn't needed):** Slimefun
