### ISSUE TITLE
Combat Timer doesn't disable after death

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Zrips/CMI#4779]
**Description of issue:**
The combat timer won't disable after the player dies and there is no config option to do this either. Currently, say a player dies from a mob and the combat timer lasts 12 seconds. Then the player still has an active combat timer even after death until those seconds are over.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Combat:
  # Defines combat timer to be used in particular features
  Timer: 12
  # Prevents damage from players with god mode enabled
  # Can be bypassed with cmi.pvp.godBypass permission node
  noGodDamage: true
  # informs player that he cant damage players while in god mode
  noGodDamageInform: true
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: true
```

---

**Cmi Version (using`/cmi version`):** 
[11:10:32 INFO]: CMI: 8.7.12.1 MySQL-> 8.7.12.2
[11:10:32 INFO]: Server: Paper(332) 1.16.4-R0.1-SNAPSHOT
[11:10:32 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True 
[11:10:32 INFO]: Modules -> 48 enabled 6 disabled: spawnerProximity, cuffed, worldLimitsElytra, skin, warmup, vanish

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper version git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
