### ISSUE TITLE
1.16.4 schedules.yml for StopServer not work

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#4824]
It not stop the server, when set in schedules.yml

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
<details>

```
StopServer:
  Enabled: true
  PerformOn:
    '1':
      Hour: 13
      Minute: 55
  Commands:
  - title @a times 60 200 60
  - title @a title ["",{"text":"\u269c","color":"dark_purple"},{"text":" Omstart om
    5 min ","bold":true,"color":"dark_red"},{"text":"\u269c","color":"dark_purple"}]
  - cmi bossbarmsg drakanoiderna -a:1 Startar om servern om 5min [autoTimeLeft]! -t:320
    -p:0.015 -s:5 -n:serverrestart -c:red
  - actionbar! &45 &emin! Till server omstart!
  - delay! 240
  - h save
  - save-all
  - title @a title ["",{"text":"\u269c","color":"dark_purple"},{"text":" Omstart om
    1 min ","bold":true,"color":"dark_red"},{"text":"\u269c","color":"dark_purple"}]
  - actionbar! &41 min! Till server omstart!
  - delay! 30
  - cmi saveall online
  - actionbar! &130 sec! Till server omstart!
  - delay! 5
  - actionbar! &225 sec! Till server omstart!
  - delay! 5
  - actionbar! &420 sec! Till server omstart!
  - delay! 5
  - title @a title ["",{"text":"\u269c","color":"dark_purple"},{"text":" Omstart om
    15 sec ","bold":true,"color":"dark_red"},{"text":"\u269c","color":"dark_purple"}]
  - actionbar! &115 sec! Till server omstart!
  - delay! 5
  - actionbar! &210 sec! Till server omstart!
  - delay! 5
  - actionbar! &45 sec! Till server omstart!
  - delay! 1
  - actionbar! &14 sec! Till server omstart!
  - delay! 1
  - actionbar! &23 sec! Till server omstart!
  - delay! 1
  - title @a title ["",{"text":"\u269c","color":"dark_purple"},{"text":" Omstart om
    2 sec ","bold":true,"color":"dark_red"},{"text":"\u269c","color":"dark_purple"}]
  - actionbar! &c2 sec! Till server omstart!
  - delay! 1
  - actionbar! &c1 sec! Till server omstart!!
  - delay! 1
  - kickall! &5⌛&2 Servern är strax uppe igen. Passa på och ta lite dricka &5⌛!
  - delay! 1
  - stop
```
</details>
---

**Cmi Version (using`/cmi version`):** 
8.7.12.4
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.16.4 348
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
have you tested this with simple 
```
StopServer:
  Enabled: true
  PerformOn:
    '1':
      Hour: 13
      Minute: 55
  Commands:
  - stop
```
setup to make sure that its performing it? Or atleast provide some extra information about this issue. Does any other command got performed? Have you tested this with more simplistic setup?
