### ISSUE TITLE
Inclusion on certain days in the schedule

### ISSUE THREAD

**Issue by 1thenikita** [Zrips/CMI#4843]
Add to the schedule the ability to include on certain days (New Year, April 1st, Halloween, etc.)

**Comment by Zrips** [comment]
```
aprilsFools:
  Enabled: true
  PerformOn:
    '1':
      Month: 4
      Day: 1
```
You can already define specific days of the month and month itself.
