### ISSUE TITLE
Bug with the player tag system

### ISSUE THREAD

**Issue by Romain-NT** [Zrips/CMI#4873]
### When we want to tag a player in games, have made "@Player" the sound does not occur, I have activated it in "Modules.yml" and "Config.yml" and activated the deletion of the @ when have measured, but it remains, which proves that it bug :(
---
CONFIG SECTION:

```
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&c'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound BLOCK_NOTE_BLOCK_HARP:3:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: true
```
---
Cmi Version: 8.7.12.7

Server Type: PaperMC

Server Version: 1.16.4
