### ISSUE TITLE
Improper alias and tab completion handling

### ISSUE THREAD

**Issue by YouHaveTrouble** [Zrips/CMI#4878]
**Description of issue:**

I've noticed that CMI does really weird things with aliases and tab completions. When setting an alias plugin just makes command sender execute actual command instead of registering as an alias. 

This behavior causes issues for plugins handling command management.

It wouldn't be as bad if setting a command alias in bukkit's commands.yml didn't entirely break tab completions.

Please redo the alias system so it properly registers command aliases.

**Comment by Zrips** [comment]
In general command is being registered, atleast attempt to do so is being done. There could be issues if another plugin already took that command. If you have better knowledge about command handling in situation like this which could resolve issues you are having i'm all here. Ot atleast give some examples what happened with what command and what result should have been.

**Comment by YouHaveTrouble** [comment]
Commands are being registered, true. I'm talking about aliases and command completions here. 

Commands can have aliases registered, and all CMI aliases do is executing command with another command.
Example: 
When activating /balance in CMI's Alias.yml when player executes /balance they actually execute 2 commands:
`/balance` and `/cmi balance` which can be seen if you listen to PlayerCommandPreprocessEvent and print commands executed.

Aliases registered with bukkit will just execute the logic of the actual command and will properly tab complete when completions are registered to the command itself. You can test it out yourself by instead of adding alias via CMI you add an alias to a cmi command via bukkit's commands.yml.

The issue with this plugins cancelling the PlayerCommandPreprocessEvent will encounter unexpected behavior. I've experienced some strange things myself, such as separate plugin acted as the command was cancelled when baltop needed to be recalculated resulting in showing the command cancelled message from the plugin aswell as the info from cmi that baltop has to be recalculated.

Second part of this is tab completions. When cmi commands aliases are registered through bukkit commands.yml (to avoid plain errors with command event cancels) they appear to lose all tab completions as the completions were set in tabCompleteEvent instead of registering them to a command with getCommand("command").setTabCompleter(new commandCompleter).

There is also a smaller, but annoying issue where sometimes /cmi [something] completions are displayed in further arguments than the first one. For example you're trying to complete /cmi something [and you still get list of commands here]

I may have missed some things, feel free to ask if something is unclear

**Comment by YouHaveTrouble** [comment]
The only workaround I found to properly cancel the cmi aliases was to listen to protocollib command packet and cancelling that before it got to the server. This _should not_ be the case basically ever.

**Comment by YouHaveTrouble** [comment]
Still relevant

**Comment by notpivan** [comment]
This is probably the thing causing issues with my Pl-Hide-Pro plugin.
Years ago I had a configuration like this:

```YAML
groups:
  default:
    commands:
      - afk
      - sit
      - spawn
      - tpa
      - tpahere
      - tpaccept
      - tpdeny
      - home
      - homes
      - sethome
      - delhome
      - removehome
      - back
      - warp
      - warps
      - msg
      - tell
      - reply
      - r
      - discord
      - ds
      - regole
      - rules
      - ping
      - cmi       #NO TAB-COMPLETE
      - cmil      #NO TAB-COMPLETE
      - ctext     #NO TAB-COMPLETE

    tabcomplete:
      - afk
      - spawn
      - tpa
      - tpahere
      - tpaccept
      - tpdeny
      - home
      - homes
      - sethome
      - delhome
      - removehome
      - back
      - warp
      - warps
      - msg
      - tell
      - reply
      - r
      - discord
      - ds
      - regole
      - rules
      - ping
    priority: 0
    blocked-command-message: "&8&l(&c&l!&8&l) &7Comando sconosciuto."
    inherited-groups: []
```

and everything was working fine.

Now, I have to add `- cmi <command>` and UNSET `- cmi` to make the plugin "kinda" work.
And I say "kinda" because there is an alias in particular that just skips everything: /lag.

When any player on my server, even if I set `- "!lag"` and `- "!cmi lag"` to blacklist that command, performs /lag, the check of Pl-Hide-Pro gets entirely skipped.
I can confirm this since it shows the default CMI's "No permission" text, instead of the Pl-Hide-Pro's `blocked-command-message`.
And /lag is and alias of /status. But /status gets blocked correctly. /lag doesn't.

My current config is:

```YAML
groups:
    commands:
      - afk
      - cmi afk
      - sit
      - cmi sit
      - spawn
      - cmi spawn
      - tpa
      - cmi tpa
      - tpahere
      - cmi tpahere
      - tpaccept
      - cmi tpaccept
      - tpdeny
      - cmi tpdeny
      - home
      - cmi home
      - homes
      - cmi homes
      - sethome
      - cmi sethome
      - delhome
      - cmi delhome
      - removehome
      - cmi removehome
      - back
      - cmi back
      - warp
      - cmi warp
      - warps
      - cmi warps
      - msg
      - cmi msg
      - tell
      - cmi tell
      - reply
      - cmi reply
      - r
      - cmi r
      - discord
      - ds
      - regole
      - rules
      - ping
      - cmi ping
      #- cmi       #NO TAB-COMPLETE
      - cmil      #NO TAB-COMPLETE
      - ctext     #NO TAB-COMPLETE
      - "!lag"
      - "!cmi lag"
    tabcomplete:
      - afk
      - spawn
      - tpa
      - tpahere
      - tpaccept
      - tpdeny
      - home
      - homes
      - sethome
      - delhome
      - removehome
      - back
      - warp
      - warps
      - msg
      - tell
      - reply
      - r
      - discord
      - ds
      - regole
      - rules
      - ping
    priority: 0
    blocked-command-message: "&8&l(&c&l!&8&l) &7Comando sconosciuto."
    inherited-groups: []
```

As you can see, from the config and what I stated, something is not working as it shoulds.
Pl-Hide-Pro dev says he handles the Command event correctly, and blames CMI.
Here we are.
