### ISSUE TITLE
/sethome IconPicker Lag

### ISSUE THREAD

**Issue by Lewui** [Zrips/CMI#4882]
**Description of issue:**

When players using sethome command, server not responding.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
![изображение](https://user-images.githubusercontent.com/49539029/104049777-93e51280-51f6-11eb-81e4-6950a612c063.png)

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Homes:
  # Open gui when using /cmi home command if you have more then one home in your saved list
  Gui: true
  # Homes groups to define max amount homes player can have. Permission: cmi.command.sethome.[groupname]
  # If players home group if not find then amount will be set to 1
  # To have unlimited homes use cmi.command.sethome.unlimited permission
  # In addition to this you can use simple numeric permission node cmi.command.sethome.[number] which will define max number of homes player can have
  Groups:
    Ultra: 70
    Sponsor: 60
    Prime: 50
    Platinum: 30
    Premium: 10
    Vip: 5
  # Requires cmi.bedhome permission node
  # When set to true by interacting with bed, regular home location will be created
  # When set to false vanilla bed home location will be set
  BedInteraction: false
  # When set to true, you can only set home location when you shift click a bed
  onlyShiftBed: false
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: false
  # When enabled, plugin will check if player can break block in that area before creating new home location
  # This allows to prevent setting homes in protected areas
  # Can be bypassed with cmi.command.sethome.bypass
  CheckBlockBreak: false
  # Name for default home location. By default its "Home"
  DefaultName: home
  # Name for bed location. By default its "Home"
  # Different name can be used to identify home location set by interacting with a bed from home location created with command
  DefaultBedName: Home
  # Defines what characters you can use in your home names
  ValidNameRegex: '[^a-zA-Z0-9\-\_]'
  # When set to true home icons in GUI will try to pick real blocks from that location for easy way to see which is which
  # When set to false, then random wool block will be used
  PickRealBlock: false
```

---

**Cmi Version (using`/cmi version`):** 
8.8.0.0

**Server Type (Spigot/Paperspigot/etc):** 
CarServer

**Server Version (using `/ver`):** 
This server is running CatServer version git-CatServer-1.12.2-d35de0b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)
