### ISSUE TITLE
Player can run CMI commands in jail

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#4896]
**Description of issue:**
Player can run all cmi based commands when being jailed. They tried other plugin (/res tp), but that one is blocked just fine.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 0
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true
  # Do you want to prevent players damage while he is in jail
  PreventDamage: true
  WhiteListedCmds:
  - login
  - l
```

---

**Cmi Version (using`/cmi version`):** CMI 8.8.0.1

**Server Type (Spigot/Paperspigot/etc):** Paper 394

**Server Version (using `/ver`):** 1.16.4
