### ISSUE TITLE
Playtime still being counted while in vanish

### ISSUE THREAD

**Issue by xReplicate** [Zrips/CMI#4913]
Time spent in vanish is still being counted towards playtime even with stopPlaytime:true
![image](https://user-images.githubusercontent.com/73534050/104845862-eb127380-58d7-11eb-9202-917a5a9f9d8c.png)

**CONFIG SECTION:**
```
Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: false
    PrivateMessages: false
    relogDisable: false
    noMessages: false
    fakeJoinLeave: false
    mobSpawning: false
    stopPlaytime: true
```

---

**Cmi Version:** 8.8.0.3

**Server Type:** Tuinity

**Server Version:** 1.16.4

**Relevant plugins:** PremiumVanish
