### ISSUE TITLE
Displaying items with Apostrophe's in chat causes an error and the item does not display.

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#4921]
**Description of issue:**
Greetings, I seem to be having an issue where if any of my players have item names or lore with an ' (apostrophe), the item fails to display in chat when using [item] and an error is printed in console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[04:58:15 INFO]: DragonEye issued server command: /msg DragonAgent [item]
[04:58:15 WARN]: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '}' at position 521: ...":"Dragon'<--[HERE]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  ModifyChatFormat: true
  ClickHoverMessages: true

  HoverItems: true
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
  BungeeMessages: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.0.3
**Server Type (Spigot/Paperspigot/etc):** Paper
**Server Version (using `/ver`):** Paper-406 (1.16.4)

**Comment by Zrips** [comment]
Could you provide actual item data? Basically saving it with **/cmi saveditems save dragon** aand then from saveditems file copy paste entire item section. As everything seam to work properly with ' in item name or lore. So something else is going on here

**Comment by NightFuryStrike** [comment]
Apologies for the delay, here is the item. (I just renamed a sword with /cmi itemname)

```
Dragon:
  Item:
    v: 2584
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Dragon''s
        Test"}],"text":""}'
```

I will do some more testing later and see if there is another plugin causing a conflict.
