### ISSUE TITLE
asFakeOp! in alias removes letters of triggered command

### ISSUE THREAD

**Issue by imparium-de** [Zrips/CMI#4929]
**Description of issue:**
When using a command like `/c show` as an alias for something like `lp user [playerName] permission set show.coordinates true`, CMI removes the `lp` part so `/user [playerName] permission set show.coordinates` true gets triggered. 

Screenshot: 
![image](https://user-images.githubusercontent.com/63745647/105121083-c2ef6400-5ad3-11eb-95ad-45cd04bed422.png)

---

**Cmi Version (using`/cmi version`):** 
CMI Plugin Version: 8.8.0.3 BungeeCord CMIB  MySQL-> 8.8.0.4
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-393 (MC: 1.16.4)

**Comment by CloudeLecaw** [comment]
Have you checked whats written in customalias.yml?
Does fakeOp work with that plugin? I recommend to use asConsole! here and define a permission for that command, so not every user can use the command.

**Comment by derMiepz** [comment]
asConsole! is working now, I just missed the space... Thanks for pointing that out! 
And for the permission, I actually want all users to be able to use it. On our farming server, it shows your current coords in the tab list. For streamers it can be annoying because of other players stream sniping them. Because of that, I added a condition to either show or hide the coords, depending on you (the player) having the permission or not :D

**Comment by CloudeLecaw** [comment]
you know that u can design your tab for that allready? :)
a simple short alias for /cmi tablistupdate would be enough then.

here is a little view into our tablist.yml
may you can collect 1-2 ideas for your players too :-)

```
  GroupFormat:
    '1':
      PlayerName: '  [prefix][playerDisplayName] %cmi_user_afk_symbol%'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Willkommen auf Lululand'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &a%player_x%:&a%player_y%:&a%player_z% &7Biom: &a%player_biome% '
        - '&7Konto:&6%cmi_user_balance_formatted% '
        - '&7Uhrzeit: &6%server_time_HH:mm% &7Ping:&6%player_ping% '
        - '&7Lululandzeit: &6%player_world_time_24%'
        - '&f------------------------------------'
```
