### ISSUE TITLE
CustomAlias aren't reloaded

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4941]
**Description of issue:**

Hi, when you use /cmi reload, then customalias aren't reloaded...
```
  btruhlahlasovacitruhla:
    Cmds:
    - asConsole! actionbarmsg $1 -s:1 GG %cmi_random_1_100%
    - check:%cmi_lastrandom_$1%<=90! ptarget:$1! asConsole! cmi ctellraw
      all <T>&c&lTruhly &f» &eHráč &f$1 &ezískal z &9&lHlasovací truhla &f$2-&e. Klíč
      z &c/vote&e.</T><H>&cKlikni pro teleport hlasování.</H><SC>/vote</SC>
    Perm: true
```
All time I change something here, command, or I add ptarget etc. before first argument, then I had to restart server to apply changes...

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  btruhlahlasovacitruhla:
    Cmds:
    - asConsole! actionbarmsg $1 -s:1 GG %cmi_random_1_100%
    - check:%cmi_lastrandom_$1%<=90! ptarget:$1! asConsole! cmi ctellraw
      all <T>&c&lTruhly &f» &eHráč &f$1 &ezískal z &9&lHlasovací truhla &f$2-&e. Klíč
      z &c/vote&e.</T><H>&cKlikni pro teleport hlasování.</H><SC>/vote</SC>
    Perm: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.0.4

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):** SpecializedCrates, but it¨s only used to execute btruhlahlasovacitruhla command with player name ($1) and rewards ($2-).
