### ISSUE TITLE
Warmup - No move not working, players can move and command is not cancelled

### ISSUE THREAD

**Issue by Baterka** [Zrips/CMI#4958]
**Description of issue:**

I have those warmups configured:
```yml
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back :3:false
  - cmi warp :3:false
  - cmi home :3:false
  - cmi spawn :3:false
```

When user do /home and warmup starts he moves and he is still teleported. Warmup is never cancelled.

---

**Cmi Version (using`/cmi version`): 8.8.0.5** 

**Server Type (Spigot/Paperspigot/etc): Yatopia** 

**Server Version (using `/ver`): Yatopia 1.16.4 3770a43**
