### ISSUE TITLE
PortalCommands not executed when entering in a minecart

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4971]
```
  ANI-geisterbahn1:
    Loc: -330.0:21.0:236.0:-293.0:27.0:246.0
    enabled: true
    effect: soul
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 4
    particleHide: 0
    activationRange: 24
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 8 1 -s
```

Well i hope this sais all.. when you enter a portal while drive in rails in a minecart the command will not be executed :(

![Snag_2fbe5dc](https://user-images.githubusercontent.com/12080017/105615590-24644b00-5dd2-11eb-9fd2-0c2fef8c4e5a.png)

![Snag_2fdaee4](https://user-images.githubusercontent.com/12080017/105615616-69887d00-5dd2-11eb-8dae-bf601fb0b205.png)

Edit: we noticed the same when other plugins try to execute a cmi command when sitting in a minecart.
The only possible way at the moment is useing a commandblock then it seems to work fine.
