### ISSUE TITLE
DiscordSRV Alerts with CMI commands don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4978]
**Description of issue:**
Hi, I wanna report that DiscordSRV alerts.yml section don't work with CMI commands. when I use trigger: /unknownworld adsa, then it is shown on Discord 
![image](https://user-images.githubusercontent.com/18662086/105647274-b89ee280-5ea4-11eb-9c09-a91d8a88c880.png)
But when I use /cmi broadcast / /broadcast, /helpop, /gamemode.... anything doesn't work. Even when I enabled integration with DIscordSRV in CMI config, but I don't use CMI to format chat, I'm using chatcontrol, but this shouldn't be issue probably... Other commands from other plugins normally work.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
- Trigger: /broadcast
  Channel: standard
  Embed:
    Color: "#FFFF00"
    Author:
      ImageUrl: "{embedavatarurl}"
      Name: "Dotaz"
    Description: "${#allArgs}"

- Trigger: /cmi broadcast
  Channel: standard
  Embed:
    Color: "#FFFF00"
    Author:
      ImageUrl: "{embedavatarurl}"
      Name: "Dotaz"
    Description: "${#allArgs}"
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/105647287-dbc99200-5ea4-11eb-8e30-17c5f8d95f25.png)

**Server Type (Spigot/Paperspigot/etc):** Yutopia

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/105647297-e7b55400-5ea4-11eb-8037-09ca8a1889b3.png)

**Relevant plugins (Delete if this isn't needed):** DiscordSRV, ChatControl Red (but this isn't case probably, cause it's command work)

**Comment by mrfloris** [comment]
Yeah, I was also fighting with /msg, /r, etc. I can't get custom alias commands to trigger either. Nor the default base commands. With or without the config.yml of cmi set to true for using discordsrv. 

I guess the next step is to check the cmi api to see what events are being called by cmi for these things and maybe hook into that instead.

**Comment by mrfloris** [comment]
!!
Progress..

```yaml
  - Trigger: PlayerCommandPreprocessEvent 
    Channel: team
    Conditions:
      - "(#command.split(\"\\s+|$\")[0].equals(\"cmi\"))"
      - "(#command.split(\"\\s+|$\")[1].equals(\"msg\"))"
    Embed:
      Color: "#000001"
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: '**MSG SPY**'
      Description: "Message by `{username}` : ```\n/${#command}```"
```

First argument "cmi", and 2nd argument "msg" and it should work. 
This might need tweaking to be more 'accurate' and failproof, but this part worked at least for /msg and /r
<img width="528" alt="Screenshot 2021-02-05 at 11 44 09" src="https://user-images.githubusercontent.com/28841349/107023835-78463b00-67a7-11eb-8860-d7e3e288f254.png">
