### ISSUE TITLE
PlaytimeRewards timing not correct

### ISSUE THREAD

**Issue by alan67160** [Zrips/CMI#4995]
**Description of issue:**
PlaytimeRewards countdown is not working
when that timer reaches the time it will add reset and add more time
![image](https://user-images.githubusercontent.com/20385640/106141240-c9a06a00-61aa-11eb-9a94-5228b18508fd.png)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
hourly1:
  DisplayName: "&f薪水"
  AutoClaim: true
  Description:
  - "&8---------------------"
  - "&e領地格子: &a+250格"
  - "&8---------------------"
  PayEvery: 1800
  Commands:
  - asConsole! cmi actionbarmsg [playerName] &6&l玩半個小時的250格已入帳>w<!
  - asConsole! cmi money give [playerName] 250 -s
```
```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: false
PlaytimeRewards:
  # Enable or disable playtime rewards.
  # This is required if you want to have auto rewards
  Enabled: true
  # When enabled, while player is in afk mode, repeatable playtime rewards will not increase in playtime
  # ATENTION! this setting will not have any effect if you have Afk.StopPlayTime set to true
  # When StopPlayTime set to true, afk will be expluded automatically
  ExcludeAfk: false
  # Defines time in minutes to inform player about pending reward which needs to be claimed
  RewardInform: 15
  # Defines how many one time rewards you want to show in list
  # This will show next X amount rewards from your current playtime
  # No point in listing all rewards if player is still far away
  OneTimeAmount: 1
  # When set to true player will be required to have cmi.prewards.[name] permission node to get particular playtime reward
  RequiresPermission: true
```

---

**Cmi Version (using`/cmi version`):** 
---------------------------------------------------
CMI Version: 8.8.0.7 BungeeCord  MySQL
CMILib: 1.0.0.2 
Server: 1.16.5 1.16.5-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 50 enabled 4 disabled: armorstand, ranks, votifier, holograms
---------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot fork

**Server Version (using `/ver`):** 
This server is running SSSpigot version SSSpigot-1.16.5-20210124-41e4383 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
