### ISSUE TITLE
Portal access permission

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#500]
It is possible to add the possibility of using the portal for a group of players with the desired permissions?

**Comment by CloudeLecaw** [comment]
lucky man. the answer is yes :D

**Comment by GrimPod** [comment]
Portals dont need a location to teleport to, they can be used to just run a command
So you could just make the portal run the warp command, the warps have permission per warp
Another way would also be make the portal run a customalias that does a number of things,

**Comment by CloudeLecaw** [comment]
"Portals dont need a location to teleport to"..but they can. When looking into the portals, we see that commands are a part of it but are more to execute an optional command(s) the main Thing of a Portal is still to teleport. ist not really the sense to use a "teleporter" to open an other teleportingmethode by command (warp). 

```
  NSHSpawn:
    Loc: 35.0:73.0:5.0:35.0:80.0:5.0
    enabled: true
    effect: reddust
    showParticles: true
    Tp:
      ==: org.bukkit.Location
      world: NSH
      x: -168.1224851346153
      y: 104.0
      z: -968.7867147708934
      pitch: -4.649986
      yaw: 180.90007
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands:
    - cmi effect [playerName] blindness 2 1 -s
```

Why permission?
+ enough place for needPerm
+ perm can block the useage of the Portal itself and not of optional function
+ (Maybe not noticed but u see that commands get executed as console with all permisison?)
…..would not be nice if a Player would have accesto cmi effect.. ;) - so also the customalais Needs a "asplayer"...hmmm the console executes asplayer...does not Sound like a reasonable solution…
….so + aggain for usingage of Portal not of the command
