### ISSUE TITLE
Server crash - unloaded world

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5017]
**Description of issue:**

---

Hi, server crashed due to unloaded world. See here https://pastebin.com/EGg8upZM. There's mentioned CMI module there, so it's probably something wrong in CMI too.

---

**Cmi Version (using`/cmi version`):** 8.8.1.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 1.16.5,17

**Relevant plugins (Delete if this isn't needed):** PlayerWorlsPro with 
```

    # Player world will be unloaded if there is no player in it.
    Unload-Empty-Worlds:
      Enabled: true
      # Time in seconds after which the empty world will be unloaded.
      Delay: 10
```
