### ISSUE TITLE
Were do I find warm ups in the config?

### ISSUE THREAD

**Issue by redalpha123123** [Zrips/CMI#5025]
Visit https://github.com/Zrips/CMI/discussions/new to post question
Posting questions in ticket section could result in their removal.

I am trying to find warm up in the configs but I can not seem to find it in the confg.

**Comment by CloudeLecaw** [comment]
u should open config and search for it ;)
i recommend not to use windows Editor.  you should use a better editor like notepad++

```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: false
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:false
  - cmi home :3:false
```
