### ISSUE TITLE
ranks.yml rank displaynames don't accept vanilla color codes as well as hex

### ISSUE THREAD

**Issue by AZFire1** [Zrips/CMI#5034]
**Description of issue:**
The displaynames of all of my ranks do not accept hex. Here is a demo of one of my ranks. If you are curious as to why I have it set to single quotes, CMI automatically changes all the quotes for me by itself. It doesn't register hex in a format of {#000000} as well as &x&0&0&0&0&0&0 and just has it set as white as if no changes happened. It doesn't remove these codes though, so it's strange.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
CMI doesn't throw any errors.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Here's one of my ranks as an example:
Lvl0:
  Enabled: true
  Displayname: '&x&e&6&7&c&0&0Lvl0'
  DefaultRank: true
  NextRanks:
  - Lvl1
```

---

**Cmi Version (using`/cmi version`):** https://pastebin.com/tdXvckcv

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** https://pastebin.com/DsJCNVhL
