### ISSUE TITLE
Can't restrict /nickname to alphanumeric while supporting hexcode

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#5057]
**Description of issue:**
Hi, players now can add weird symbols on their name with /nickname, this happens because of the new regex `[^\p{L}0-9\-\_]` that is implemented on nickname regex. Is there a way to prevent them using unique characters and at the same time support hexcode nickname colors?

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{nickName}'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  ValidNicknameRegex: '[^\p{L}0-9\-\_]'
```

---

**Cmi Version (using`/cmi version`):** 8.8.1.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot build 466

**Server Version (using `/ver`):** 1.16.5
