### ISSUE TITLE
Bypassing warmup delays using /cmi:

### ISSUE THREAD

**Issue by 27chandler** [Zrips/CMI#5074]
**Description of issue:**

Players are able to bypass warmups by prefixing a command with /cmi:

For example:
If theres a 5 second warmup delay on /spawn, a player can use /cmi:spawn to bypass the delay, and adding /cmi:spawn to the warmup delay list is impossible due to the formatting of the config
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi warp :5:false:tpaWarmup
  - cmi home :5:false:tpaWarmup
  - cmi rt:5:false:tpaWarmup
  - cmi spawn:5:false:tpaWarmup
```

---

**Cmi Version (using`/cmi version`):** 
8.8.1.1

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-449 (MC: 1.16.5)
