### ISSUE TITLE
Schelduer format is wrong now? what happend? - Wrong Order in how commands are executed

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5094]
This is the code of the scheduler

```
BroadcastVoteReminder:
  Enabled: true
  MinPlayers: 1
  Delay: 3600
  Repeat: true
  Commands:
  - cmi ctellraw all <T>&b&l████████████████████████</T><H>Hier Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
  - cmi ctellraw all <T>&b&l█                                           █</T><H>Hier Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
  - cmi ctellraw all <T>&b&l█ &e&lHabt ihr heute schon gevotet? &3/vote &b&l█</T><H>Hier Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
  - cmi ctellraw all <T>&b&l█                                           █</T><H>Hier Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
  - cmi ctellraw all <T>&b&l████████████████████████</T><H>Hier Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
```

Well the output is wrong - the 1st and 5h line come first, then the 2dn and 4rd and at least the 3rd line.
so there seems to be an isssue with the order how commands are executed
![Snag_28f8c40](https://user-images.githubusercontent.com/12080017/107996256-440d1e80-6fe0-11eb-8b99-d5cba0c5a392.png)

So what went wrong here?

![Snag_2900b92](https://user-images.githubusercontent.com/12080017/107996280-51c2a400-6fe0-11eb-99e6-ef54ded3c8ac.png)

**Comment by CloudeLecaw** [comment]
i hope this issue can be fixed soon :-)

**Comment by cxmputer** [comment]
Have the same issue. Sometimes it's in the right order, but most of the time it isn't.

**Comment by cxmputer** [comment]
Seems to be an issue with /aliaseditor too. Have a few commands that are run in the wrong order also.

**Comment by mrfloris** [comment]
computer, please provide an output of /cmi version as well, and share the customalias.yml part for the commands you have an issue with - this can help with trying to reproduce this.

**Comment by cxmputer** [comment]
![2021-02-20_08 10 07](https://user-images.githubusercontent.com/26337884/108561890-1531d800-7353-11eb-9dc7-733fdf943b4f.png)

`CustomAlias:
  automsg:
    Cmds:
    - asConsole! cmi broadcast !&r &r
    - asConsole! cmi broadcast !&2&l- &a&l⋆ - ⋆ - &b&l⋆ - ⋆ - &3&l⋆ - ⋆ - &1&l⋆ -
      &3&l⋆ - ⋆ - &b&l⋆ - ⋆ - &a&l⋆ - ⋆ -&2&l -
    - asConsole! cmi broadcast !&f&l$1-
    - asConsole! cmi broadcast !&2&l- &a&l⋆ - ⋆ - &b&l⋆ - ⋆ - &3&l⋆ - ⋆ - &1&l⋆ -
      &3&l⋆ - ⋆ - &b&l⋆ - ⋆ - &a&l⋆ - ⋆ -&2&l -
    - asConsole! cmi broadcast !&r &r
    Perm: true
  donatormsg:
    Cmds:
    - asConsole! cmi broadcast !&r &r
    - asConsole! cmi broadcast !&2&l- &a&l⋆ - ⋆ - &b&l⋆ - ⋆ - &3&l⋆ - ⋆ - &1&l⋆ -
      &3&l⋆ - ⋆ - &b&l⋆ - ⋆ - &a&l⋆ - ⋆ -&2&l -
    - asConsole! cmi broadcast !&a&l$1&r&f donated and purchased &a&l$2&r&f!
    - asConsole! cmi broadcast !Thank you for the support &c<3
    - asConsole! cmi broadcast !&2&l- &a&l⋆ - ⋆ - &b&l⋆ - ⋆ - &3&l⋆ - ⋆ - &1&l⋆ -
      &3&l⋆ - ⋆ - &b&l⋆ - ⋆ - &a&l⋆ - ⋆ -&2&l -
    - asConsole! cmi broadcast !&r &r
    Perm: true`

**Comment by Zrips** [comment]
Both broadcast and ctellraw being processed in async which means that it can get out of order in case one line gets processed faster then another one. Solution for now would be to stack those lines into one by separating each line with \n which is even recommended to avoid triggering same command multiple times instead of single one. Will try to make some work around at my end.
```
BroadcastVoteReminder:
  Enabled: true
  MinPlayers: 1
  Delay: 3600
  Repeat: true
  Commands:
  - cmi ctellraw all <T>&b&l████████████████████████\n&b&l█                                           █\n&b&l█
    &e&lHabt ihr heute schon gevotet? &3/vote &b&l█\n&b&l█                                           █\n&b&l████████████████████████</T><H>Hier
    Klicken um die Votelinks angezeigt zu bekommen.</H><C>/vote</C>
```
