### ISSUE TITLE
PlayTime rewards Timings?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5117]
![image](https://user-images.githubusercontent.com/18662086/108582107-616c2080-7331-11eb-9eeb-817b27b34eb0.png)

Hi, is this value in timings OK? https://timings.aikar.co/?id=c6eb3f43b95a466e96f4fc0c4737e37c#plugins 

And other CMI values? Couldn't be anything improved here?

**Comment by Zrips** [comment]
This seam to point towards performed commands method. Most of the code is performed in async while commands should be in sync which is seen in your timings. You might check those and try optimize them in particular.

**Comment by bobhenl** [comment]
```
hourly1:
  DisplayName: "&7Přestávka na svačinku"
  AutoClaim: true
  Description:
  - "&eZa &fkaždou &eodehranou &fhodinu &edostaneš"
  - "&f5 jablek, zdarma uzdravení, 150 ⛃"
  - "&fa klíč ke truhle &e&lTo to letí&e."
  PayEvery: 3600
  Commands:
  - asConsole! cmi heal [playerName] -s
  - asConsole! cmi give [playerName] apple 5
  - asConsole! cmi money give [playerName] 150 -s
  - asConsole! scrates givekey ToToLeti [playerName]
  - 'cmi ctellraw [playerName] <T>&c&lServer &f» &eDostal jsi &f5 jablek, zdarma uzdravení \n&fa 150 ⛃&e. Toto dostaneš &fkaždou &eodehranou &fh&e.</T>'
```

Example how do commands look
