### ISSUE TITLE
PlayTime (One-Time) Rewards are given multiple times...

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/CMI#5135]
**Description of issue:**
PlayTimeRewards, that are supposed to be given only once, are given multiple times after every `/cmi reload` command.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
[config.yml]
PlaytimeRewards:
  Enabled: true
  ExcludeAfk: true
  RewardInform: 15
  OneTimeAmount: 2
  RequiresPermission: false

[PlayTimeRewards.yml]
OneDay:
  DisplayName: "&6Hopper"
  AutoClaim: true
  Description:
  - "&ePrize for playing for one day &8(&686400 seconds&8)&e."
  PayFor: 86400
  Commands:
  - asConsole! give [playerName] hopper 1
```
**!!! In example:**
```
• After player reaches 1 day, he gets the reward;
• I change something in config, so I do /cmi reload;
• Player gets the reward once again (if he's online, if he's not - nothing happens), doesn't matter if it's one-time.
```
---

**Cmi Version (using`/cmi version`):** 8.8.1.3

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** Yatopia 1.16.5-R0.1-SNAPSHOT (latest stable build)

Edit: I have fixed this by enabling required-permission: true // and then by giving everyone permissions to get every reward // and then by disabling permission after reward is given, so that they're not able to "use it" again... This is the only "fix" that I could have thought of, but still, would be nice if it was somehow fixed by not going into such actions. 😌
