### ISSUE TITLE
Scheduler and Permissions/checks does not work as shown in wiki

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5137]
> If command starts with perm:[permissionNode]! then command will get performed if player has permission node. This will not work when we don’t know who the target player is. Example: perm:cmi.announce.vip! broadcast! Hello vip guys

Thtas what the Wiki is saying.
i tried to create a shedulder that only one group can see

```
TestFromCloudeLecaw:
  Enabled: true
  MinPlayers: 1
  Delay: 10
  Repeat: true
  Randomize: false
  Commands:
  - perm:cmi.announce.notvoted! broadcast! Dies ist ein Test.
```

Result - all see the broadcast no matter if they have the permission or not.
may the shown concept does not work for schedules
So i aspect this is a bug?

If not is there a solution to this situalion? "create a scheduler that is only (readable)if player has permission"
