### ISSUE TITLE
PlayTime Rewards Spam

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5140]
**DESCRIPTION OF ISSUE:**

Players are noticed about remaining reward multiple times. This happens randomly and not for every reward, usually it's only the one called "every_4hours" (config section). Looks like "PayEvery" tag is ignored, maybe something wrong in for cycle, I really don't know.

---

**ERROR SCREENSHOTS FROM SOME PLAYERS:**

![2021-02-21_21 55 48](https://user-images.githubusercontent.com/16023709/108662292-500c4b00-74ce-11eb-9f01-ddd803457ab2.png)
![unknown](https://user-images.githubusercontent.com/16023709/108662298-526ea500-74ce-11eb-8f68-53e15fcd3493.png)
![2021-02-19_23 03 09](https://user-images.githubusercontent.com/16023709/108662342-6914fc00-74ce-11eb-8ee5-a80b3861948c.png)

---

**CONFIGS SECTIONS:**
```
[config.yml]
PlaytimeRewards:
  Enabled: true
  ExcludeAfk: true
  RewardInform: 10
  OneTimeAmount: 1
  RequiresPermission: false

[PlayTimeRewards.yml]
first_hour:
  DisplayName: "První seznámení"
  AutoClaim: false
  Description:
  - "&2Tvoje &aprvní &2odehraná hodina na serveru."
  - "Na kontě ti přistane &a1 000€ &2do začátku."
  PayFor: 3600
  Commands:
  - asConsole! cmi money give [playerName] 1000
every_hour:
  DisplayName: "Hodinová prémie"
  AutoClaim: true
  Description:
  - "&2Každá odehraná &ahodina &2se počítá."
  - "Automaticky se ti co hodinu přičte &a110€&2."
  PayEvery: 3600
  Commands:
  - asConsole! cmi money give [playerName] 110 -s
every_4hours:
  DisplayName: "Zkrácený úvazek"
  AutoClaim: false
  Description:
  - "&2Získej odměnu za každé &a4h &2online."
  - "Do kapsy ti brigádně skočí &a400€&2."
  PayEvery: 14400
  Commands:
  - asConsole! cmi money give [playerName] 400
every_24hours:
  DisplayName: "Další přežitý den"
  AutoClaim: false
  Description:
  - "&2Získej odměnu za každých &a24h &2online."
  - "Do kapsy ti přistane až &a2 000€&2."
  PayEvery: 86400
  Commands:
  - asConsole! cmi money give [playerName] 2000
first_week:
  DisplayName: "Náročný týden"
  AutoClaim: false
  Description:
  - "&2Odehrál jsi první týden na serveru."
  - "Za svou vytrvalost získáš &a10 000€&2."
  PayFor: 604800
  Commands:
  - asConsole! cmi money give [playerName] 10000
```

---

**CMI Version:** 8.8.1.3

**Server type:** Paper

**Server version:** 1.16.5-b470
