### ISSUE TITLE
moneycost does not work in some cases

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5146]
In some cases the moneycost does not work... this is broken since a few versions in this situation and was working fine before

```
worldSignierSchmied:
  Locations:
  - world;-133.0;64.0;287.0
  Commands:
  - click:left#! hasmoney:5@! msg! [playerName] &fDu brauchst mindestens &e&l5 Taler &fum deinen Gegenstand signieren zu lassen&f. Du besitzt aktuell nur &e&l%cmi_user_balance_formatted% Taler&f.
  - cooldown:5?#! ptimer give [playerName] WeltAktion RHSignItem.use 2
  - delay! 0.5
  - moneycost:5! asPlayer! rhsignitem:sign &7
  - delay! 0.1
  - msg! [playerName] &fDein neuer Kontostand ist &e&l&l%cmi_user_balance_formatted%&f.
  SignLines:
  - '&lSignierschmied'
  - '&7Siegniert Items'
  - '&7per Linksklick'
  - '&lPreis:&6&l 5 Taler'
```

EDIT: with the example like you see it here above the money is not taken from the player but the command after is executed

![Snag_80274de](https://user-images.githubusercontent.com/12080017/108775068-e0936b80-7560-11eb-96c3-0c4ec8c1d0e8.png)

![Snag_802b0fd](https://user-images.githubusercontent.com/12080017/108775095-e8531000-7560-11eb-91f1-0f7b5083f317.png)
