### ISSUE TITLE
Placeholders output the players nickname

### ISSUE THREAD

**Issue by Piki-dev** [Zrips/CMI#5153]
I want to be able to use placeholders to reward certain players or display them in a leaderboard, however the output for example %cmi_votetop_1% displays the nicked name. Would it be possible to have a option to have it put out the players real name?

---

**Cmi Version: CMI: 8.8.1.4:** 

**Server Type: Purpur** 

**Server Version: 1.16.5**

**Comment by Zrips** [comment]
It shows players display name which can be a nickname or real name depending how you use it which can be defined in config.yml file

**Comment by Piki-dev** [comment]
Could you tell me where i could find this in the config?

**Comment by Zrips** [comment]
```
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{nickName}'
```
By default its using nickname, so you might want to change that
