### ISSUE TITLE
Selection Visualizer: Can't set FLAME particle as a worldborder effect

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#5188]
**Description of issue:**
The flame particle cannot be set as a world border effect. 
`WorldBorder: true`
[...]
```
  WorldBorder:
    Area:
      Effect1:
        Effect: FLAME
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: FLAME
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: FLAME
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 50
      ShowFor: 120000
      ByDefaultIsEnabled: true
```
If I now delete the player files, reload the config or restart the server, the wrong particle type is written to the player file:
    WorldBorder:
      Area:
        Range: 32
        ShowFor: 30000
        Effect1:
          Effect: COLOURED_DUST
        Effect2:
          Effect: COLOURED_DUST
        Effect3:
          Effect: COLOURED_DUST
Replacing COLORED_DUST with FLAME in the player file has no effect after a svis reload or server restart. COLORED_DUST is still displayed as a particle in the game.

**Versions**
Paper-468 (1.16.5)
SelectionVisualizer version 3.0.3.4
WorldBorder version 1.16.4 ([https://www.spigotmc.org/resources/worldborder-pures-fork.81706/](https://www.spigotmc.org/resources/worldborder-pures-fork.81706/))
