### ISSUE TITLE
Whitelist for words in chatfilters

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5197]
The Chatfilter is a nice thing but often its a bit to agressive.

Example: 
We want to block a word "fresse"
This should be blocked in all variants like
fresse, FRESSE, F R E s s E or F.r.e.s.s.sssssse

the following regex does manage this:
```
      swearing07:
        Enabled: true
        Group: swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - cmi msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde
          darüber informiert!
```
problem: some word are wanted to be shown like "fressen"
this word would need something like a whitelisted word for this filter
_This is how it could look: the following would allow the words "fressen" and "kopfresse"._
```
      swearing07:
        Enabled: true
        Group: swearing
        InformConsole: true
        Regex:
        - \b(?i)(f+(\W|_?)+r+(\W|_?)+e+(\W|_?)+s+(\W|_?)+s+(\W|_?)+e+)
        ReplaceWith: ✪✪✪✪✪
        BlockType: none
        includePrivateMessages: true
        whitelist:
        - fressen
        - kopfresse
        msgToStaff: '&4!&6[playerName] &4hat geflucht.'
        Commands:
        - cmi msg [senderName] &eFluchen ist hier nicht erlaubt! Ein Teamler wurde
          darüber informiert
```

with this whitlist we could avoid many unwanted filterings. that happen because they match the chatfilter to much.
This would help to create a more friendly not so often censored chat in many cases :-)
