### ISSUE TITLE
Chatfilter bypass Permission does not work.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5210]
The thread said it:
just an example:

cmi.chatfilter.bypass.[groupName]   would be the bypass permission

The bypass permission do not be able to use this would be
cmi.chatfilter.bypass.testword
give someone this permission and you will see he still cant write Testword without its replacement..
This can be done with all chatfilters from CMI. So this means the bypass permission seems not to work..

```
  ChatFilter:
    Enabled: true
    Deny:
      herzen:
        Enabled: true
        Group: testword
        InformConsole: false
        Regex:
        - Testword
        ReplaceWith: *Test*
        BlockType: none
        includePrivateMessages: true
        msgToStaff: ''
```

![image](https://user-images.githubusercontent.com/12080017/109780973-ca904580-7c07-11eb-892f-743d4e16ba24.png)
