### ISSUE TITLE
Nested placeholders still don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5227]
**Description of issue:**

---

Hi, I wanna again reopen https://github.com/Zrips/CMI/issues/5047, but please try my example and see if it will work for you.

**Custom alias file*
```
  welcomerandom:
    Cmds:
    - delay! 4
    - asConsole! cmi ctellraw $1 <T>&c&lSprávce &fRenzotom &8» &fVítej &e$1&f! Ať
      se Ti zde líbí!</T>
    - delay! 2
    - check:%cmi_lastrandom_player_name%!=%Renzotom%! check:%cmi_lastrandom_player_name%!=$1! asConsole! cmi ctellraw $1 <T>%parseother_{cmi_random_player_name}_{vault_prefix}% {cmi_random_player_name} &8» &7Vítej $1 :)</T>
    - delay! 3
    - check:%cmi_lastrandom_player_name%!=%Renzotom%! check:%cmi_lastrandom_player_name%!=$1! check:%cmi_lastrandom_player_name%!=%cmi_random_player_name%! cmi ctellraw $1 <T>%parseother_{%cmi_random_player_name%}_{vault_prefix}% {cmi_random_player_name} &8» &7Čus $1!</T>
    - check:%cmi_server_online%>10#!
    - check:%cmi_lastrandom_player_name%!=%Renzotom%! check:%cmi_lastrandom_player_name%!=$1! check:%cmi_lastrandom_player_name%!=%cmi_random_player_name%! cmi ctellraw $1 <T>%parseother_{cmi_random_player_name}_{vault_prefix}% {cmi_random_player_name} &8» &7Ahoj $1!</T>
    Perm: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.1.7

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Relevant plugins (Delete if this isn't needed):** PlaceholderApi
