### ISSUE TITLE
MakeBlackList in combat isn't working

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5229]
**Description of issue:**

HI, this option still works as whitelist.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - flyc
    - fly
    - cletani
    - cletanimod
    - cletaniyes
    - heal
    - feed
    - cmi
    - parkour
    - gamemode
    - gm
    - creative
    - survival
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
```

and players can't use /spawn, /money...

---

**Cmi Version (using`/cmi version`):** 8.8.1.7

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25
