### ISSUE TITLE
MakeBlackList in combat isn't working

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5241]
**Description of issue:**

---

Hi, I just wanna reopen this https://github.com/Zrips/CMI/issues/5237, still doesn't work, in both of commands (MOB AND PLAYER TOO).

I can't even use commands like /auction, /shop and bunch of other commands from other plugins

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - flyc
    - fly
    - cletani
    - cletanimod
    - cletaniyes
    - heal
    - feed
    - cmi
    - parkour
    - gamemode
    - gm
    - creative
    - survival
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
```

Just note: I can't use any commands in combat, not even listed one and not even commands which aren't on the list.

Even on version 8.8.2.0 with:
Fix for combat mode against monsters not getting detected and appropriate checks are not performed

It still seems not working.

---

**Cmi Version (using`/cmi version`):** 8.8.2.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Relevant plugins (Delete if this isn't needed):**
