### ISSUE TITLE
cmi ctext CTEXT_NAME all <page>

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5244]
**Description of issue:**

---

Hi, I just wanna report that I'm trying to show ctext to all players, but I wanna show page 5 for ex. and I can't... without "all" and with specified player it works, but this way it isn't. COuld it be fixed please?
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

**Comment by CloudeLecaw** [comment]
can you reproduce this issue with Spigot 1.16.5 or Paper 1.16.5? And with CMI 

command is
cmi ctext [cText] all
page is just an option for the single player
u want to execute it for all?
then try
allPlayers! cmi ctext [ctext] [page] [allPlayers]

**Comment by bobhenl** [comment]
I've tried, but then this problem happens. https://github.com/Zrips/CMI/issues/5246

**Comment by bobhenl** [comment]
And btw when I use all players... then cooldown for ptarget doesn't work :/
```
ptarget:$1! cooldown:86400?#! asConsole! allPlayers! cmi ctext prikazy [allPlayers]
      49
```

Code isn't stopped even when there's #...

**Comment by CloudeLecaw** [comment]
Why u need ptarget:$1 for this?...

**Comment by bobhenl** [comment]
Due to cool down on player name? Cause it's not working without ptarget probably. And also due to I wanna replace arguments, but this don't work neither

**Comment by Zrips** [comment]
More correct usage would be
`gcooldown:86400?#! asConsole! cmi ctext prikazy all 49`
we have new gcooldown variable which applies globally to all players. Then we have special variable for ctext command to show ctext for all online players, so you can use that.

**Comment by bobhenl** [comment]
Yeah, but cmictext prikazy all <page> doesn't work.

Page variable doesn't work here.

And about gcooldown... It's command to give player daily reward and it starts here, but I can move cooldown to command below probably. Here's the whole cmd:
```
  denniodmenareward:
    Cmds:
    - ptarget:$1! cooldown:86400?#! asConsole! ctellraw all <T>&c&lDenní odměny &f»
      &eHráč &f$1 &esi vyzvedl &c/denniodmena&e.</T><H>&eOdměna:\n&e- &71 smaragd\n&e-
      &716 uhlí\n&e- &716 XP lahví\n&e- &72 zlatá jablka\n&e- &750 peněz na vlastní
      světy\n&e- &71 hlasovací bod\n\n&7Doporučujeme také &e/vote&7.\n\n&cKlikni pro
      zobrazení hlasovacích stránek.</H><SC>/vote</SC>
    - ptarget:$1! asConsole! cmi ctext prikazy $1 50
    - ptarget:$1! asConsole! give $1 emerald 1
    - ptarget:$1! asConsole! give $1 coal 16
    - ptarget:$1! asConsole! give $1 experience_bottle 16
    - ptarget:$1! asConsole! give $1 goldenapple 2
    - ptarget:$1! asConsole! money give $1 50
    - ptarget:$1! asConsole! av User $1 AddPoints 1
    Perm: true
```

And the first ctellraw I replaced with the mentioned ctext.
