### ISSUE TITLE
Hide FirstJoin Meassage - happens with cmi.messages.disablelogin?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5248]
We want to hide the join meassagefor first joiner

What we tried at the moment:

```
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: true
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: true
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: true
```

and we gave their NewbieGroup the permission.
    - cmi.messages.disablelogin
    - cmi.messages.disablequit

Does the hide permission include the first joiner?
