### ISSUE TITLE
Perform commands on /RankSet

### ISSUE THREAD

**Issue by kemmeo** [Zrips/CMI#525]
### Commands not running on /Rankset ###

Normally, when players /Rankup, configurable commands are executed.
Right now it doesn't seem like commands are being executed when /Rankset is being run,
Eventhough I would like them to.

_example of ranks.yml with commands to be executed on Rankup._
```
Gold:
  Enabled: true
  DisplayName: "&6Gold"
  AutoRankup: true
  Commands:
  - "broadcast! &8[&a⬆&8] &r[playerDisplayName] &ereached &6Gold &eRank!"
  - "pex user [playerName] group set Gold *"
```

CMI Version: 7.8.4.0

Server Type: Paper 

Paper Version: 1463, 1.12.2-R0.1-SNAPSHOT

**Comment by kemmeo** [comment]
@MCTyler Why the thumb? am I missing something?

**Comment by kemmeo** [comment]
/RankUp can only be run by players themselves.

**Comment by MCTyler** [comment]
/sudo {playername} rankup ? Suggestion...Just trying to help.

**Comment by kemmeo** [comment]
I don't want players upping their rank manually or for a console command to do it through them.
The reason I want commands to run when /RankSet is used, is because I have a custom plugin dictating when players should rank up.

/RankSet is useless if it doesn't run commands the specified commands anyway.
I get that you're trying to help, and I appreciate it.

**Comment by MCTyler** [comment]
NP, I guess I don't understand the need to use any other Rank Plugin with CMI's rank system but that seems to be people's case in a lot of features. Players do not need /rankup in order for auto rankup to work. So Basically you need support for another plugin that does your ranking up. Why Bother using CMI's rank features at all? You can disable it.

**Comment by kemmeo** [comment]
My point is. I expect configured commands to run when /RankSet is executed, the same way they would be with /RankUp. Only seems logical, right?

The whole idea of letting players decide when to rank up doesn't suit my needs at all, and I'd rather it be an automatic process once certain criteria is met. Hence /RankUp is inadequate for me.

**Comment by MCTyler** [comment]
But...Players don't _have to_ decide. There are tons of configurable circumstances that should suit your needs and just have ranks that are automatic without any commands at all. What am I missing?

**Comment by MCTyler** [comment]
Here's my Prison Coal Rank for reference....
```
Coal:
  Enabled: true
  DisplayName: "&0Coal"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Iron
  MoneyCost: 25
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Prison Coal Rank!"
  - "broadcast! &6[playerDisplayName] &eUse &a/rankup &eto Check your Stats."
  - "execute [playerName] ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
  - "execute [playerName] ~ ~ ~ /playsound entity.player.levelup player [playerName]"
  - "lp user [playerName] group add coal"
  StatsRequirements:
  - "PlayTime:180"
  - "travel:1000"
  - "MonsterKills:zombie:3"
  - "MonsterKills:skeleton:1"
  - "MonsterKills:spider:1"
```
