### ISSUE TITLE
Custom-Alias: Dynamic tab complete variables not working

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5250]
**Description of issue:**
Since 8.8.2.0 the customalias refuses to accept variables like `[playername]` and won't tab-complete the base command anymore.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Two examples:
```
CustomAlias:
  whois [playername]:
    Cmds:
    - cmi info $1-
  skull:
    Cmds:
    - cmi head $1-
```
`/Skull` works. `/Whois` won't work.
CMI 8.8.1.7:
![CMI-customalias8817](https://user-images.githubusercontent.com/28690790/110374800-6af3c900-8051-11eb-873e-c91402364152.png)
CMI 8.8.2.0:
![CMI-customalias8820](https://user-images.githubusercontent.com/28690790/110374804-6cbd8c80-8051-11eb-9cc7-9d5be79605fa.png)
When the command is still executed, it returns as "unknown command".

---

**Cmi Version (using`/cmi version`):** 
CMI v 8.8.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5
