### ISSUE TITLE
Custom Heads dropped by mobs are duplicated when using ExtraHeads addon from Slimefun

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5259]
**Description of issue:**

---

Hi, when you have enabled custom head drop in CMI and also extraheads from Slimefun on server... and you destroy the Slimefun head from addon extraheads, then it gets duplicated by CMI one too.
**Cmi Version (using`/cmi version`):** 8.8.2.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 33

**Relevant plugins (Delete if this isn't needed):** Slimefun - ExtraHeads addon

**Comment by Zrips** [comment]
Can you elaborate more on this one. Which exactly head are you breaking? How exactly i could get it with slimefun command? are you using latest official build or dev builds of slimefun and extraheads?
Did basic test and everything seam to work properly at this moment. Head is broken and only one is given back.

**Comment by bobhenl** [comment]
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExtraHeads/master/

This one, try to set bigger chance in config and kill mob.

I had enabled both - extraheads and also CMI, here's my section in CMI:
```
  Heads:
    Player:
      Drop: true
      # Percentage from 0 to 100 for head to be dropped. Decimals are acceptable, like 0.2
      # 100 will mean that head will be dropped every time player kills another player
      # 1 will mean that there is 1% that player will drop head if he is killed by another player
      Percentage: 1.0
      # Percentage from 0 to 100 for lowering chance in getting second head of same player
      # This will reset on each server restart
      LowerChanceOfterDrop: 50.0
      # When enabled player heads will have bigger chance to drop when using tools with looting enchantment
      # Value is in % and it will add appropriate percentage to current drop chance by using drop chance itself
      # For example player who has head drop change of 1% with looting 3 which has 30% bonus will have 1.3% as end value (default values)
      # This only applies for player heads
      # You can add as many levels as you want, simply duplicate line and set new number, in example
      # Lvl33: 35.5
      LootBonus:
        Enabled: true
        Lvl1: 5.0
        Lvl2: 15.0
        Lvl3: 30.0
    Mob:
      # Enables custom mob heads dropping from mobs with particular chance
      # Check customHeads.yml for customization by entityType
      Drop: true
```

Custom heads: https://pastebin.com/dh5tPJ6Y

This is extraheads config, but try with bigger chance to get one head.
```
options:
  auto-update: true
  sword-of-beheading-multiplier: 1.5
chances:
  BAT: 0.1
  BLAZE: 0.1
  CAVE_SPIDER: 0.1
  CHICKEN: 0.1
  COW: 0.1
  DOLPHIN: 0.1
  DROWNED: 0.1
  ELDER_GUARDIAN: 0.1
  ENDERMAN: 0.1
  EVOKER: 0.1
  GHAST: 0.1
  GUARDIAN: 0.1
  HORSE: 0.1
  HUSK: 0.1
  ILLUSIONER: 0.1
  IRON_GOLEM: 0.1
  LLAMA: 0.1
  MAGMA_CUBE: 0.1
  MUSHROOM_COW: 0.1
  OCELOT: 0.1
  PARROT: 0.1
  PIG: 0.1
  POLAR_BEAR: 0.1
  RABBIT: 0.1
  SHEEP: 0.1
  SHULKER: 0.1
  SLIME: 0.1
  SPIDER: 0.1
  SQUID: 0.1
  STRAY: 0.1
  TURTLE: 0.1
  VEX: 0.1
  VILLAGER: 0.1
  VINDICATOR: 0.1
  WITCH: 0.1
  WITHER: 0.1
  ZOMBIE_VILLAGER: 0.1
  RAVAGER: 0.1
  PILLAGER: 0.1
  FOX: 0.1
  PANDA: 0.1
  WANDERING_TRADER: 0.1
  PIGLIN: 0.1
  ZOMBIFIED_PIGLIN: 0.1
  STRIDER: 0.1
```
