### ISSUE TITLE
Combat command blacklist -> custom aliases can't be blacklisted?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5272]
**Description of issue:**

---
Hi, I have problem that players can use custom alias (like /cletani that gives them fly AND btw, the fly wasn't disabled for them when they were in combat... is it due to they get this fly from console? It was disabled just after second mob attacked and player landed on the ground, but when he was in the air it wasn't).

So, I have custom alias /cletani that gives player tfly and I wanna disable this alias in combat. But it doesn't work... i've tried /cmi cletani too but it doesn't work. What about to make something like /cmi alias <command> for easier disabling? Cause with alias were problems in other sections in config (cooldowns & warmups), command cost.yml too.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  cletani:
    Cmds:
    - asConsole! cmi ctext prikazy [playerName] 54
    Perm: true
  cletaniyes:
    Cmds:
    - ptarget:$1! cooldown:3600?#! moneycost:1000?#! asConsole! cmi tfly $1 15m -s
    - ptarget:$1! asConsole! cmi msg $1 !&c&lRádce &f» &fBylo ti aktivováno &elétání
      &fpo dobu &e15 min&f. Kliknutím aktivuješ po vypršení.
    Perm: true
```
Config:
```
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - cmi flyc
    - cmi fly
    - cletani
    - cletanimod
    - cletaniyes
    - cmi heal
    - cmi feed
    - parkour
    - cmi gamemode
    - cmi gm
    - cmi creative
    - cmi survival
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 33
