### ISSUE TITLE
Way to delete money & sell logs after specific period?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5289]
Hi, I wanna suggest new option to delete money & sell logs after configured period. Would be useful to clear logs, exactly in money one.

**Comment by CloudeLecaw** [comment]
something like

```
  LogEnabled: true
  log:
    Unknown: true
    Transfer: true
    #Remove Moneylog After X Amount of Days. Set to 0 to disable Removing of Moneylog
    removeLogAfter: 7
```
