### ISSUE TITLE
Sleep fastforward bug

### ISSUE THREAD

**Issue by JediM4ster** [Zrips/CMI#5305]
**Description of issue or feature request:**
I seem to have an issue where a player will go to sleep at night and then the next day is in constant speed up as well as the next night. I'm not sure how to explain int very well. I have a video of it as an example. I'm using the default config for the time setting and there seemed to be no console errors

https://user-images.githubusercontent.com/72643339/111734251-fbdb5900-8836-11eb-8837-cb2650bca836.mp4

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: []
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 50%
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

---

**Cmi Version (using`/cmi version`): 8.8.2.3** 

**Server Type: Paper Spigot** 

**Server Version (using `/ver`): 1.16.5 **
