### ISSUE TITLE
Totems Bug

### ISSUE THREAD

**Issue by fabmm** [Zrips/CMI#5352]
**Description of issue:**
Totems consume from inventory even if the player is still in cooldown
They're supposed to just die with the totem sitll in their inventory if they died while the cooldown is active

---
```
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: true
    Time: 30
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: true
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.8.2.6 SqLite
CMILib: 1.0.0.2 
Server: Paper(570) 1.16.5-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b
