### ISSUE TITLE
ReSpawn anchor does not respawn back at anchor but skips it in priority list

### ISSUE THREAD

**Issue by gooderzz** [Zrips/CMI#5381]
**Description of issue:**
When using the respawn order within config.yml the anchor is skipped and the player respawns in a lower priority space. Below is my config. When a player dies in the nether they are respawning back at spawn, not the anchor.

---

**CONFIG SECTION:**
```
 Specific:
    world:
    - bedLocation
    - spawn
    - anchor
    - worldSpawn
    - homeLocation
    world_nether:
    - anchor
    - bedLocation
    - spawn
    - worldSpawn
    - homeLocation
    world_the_end:
    - anchor
    - spawn
    - worldSpawn
    - homeLocation
```

---

**Cmi Version (using`/cmi version`):** 
8.8.2.7

**Server Type (Spigot/Paperspigot/etc):** 
Paper 

**Server Version (using `/ver`):** 
Paper version git-Paper-567 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
