### ISSUE TITLE
IC - Skipping of Commands

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5386]
I have some issues with Interactive Commands. I have defined some IC's for some different blocks but while interaction with players are some of these commands just skipped skipped. It is not happening with every IC, it's random bug and it happens aspecially in associacion with "tellraw" and "modreq" commands.

---

**CONFIG SECTION:**

**interactiveCommands.yml**

```
easter1:
  Locations:
  - tok;285.0;99.0;349.0
  Commands:
  - cooldown:2592000! asConsole! cmi give [playerName] enchanted_golden_apple 1 -s
  - cooldown:2592000! asConsole! cmi money give [playerName] 199 -s
  - cooldown:2592000! asConsole! cmi sound entity_player_levelup [playerName]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Našel jsi velikonoční vajíčko!","color":"light_purple"}]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Získáváš 199€ a očarované zlaté jablko.","color":"gray"}]
  - delay! 1
  - cooldown:2592000! asConsole! modreq create [playerName]#EasterEvent2021Find#1
easter2:
  Locations:
  - world;67.0;84.0;-1745.0
  Commands:
  - cooldown:2592000! asConsole! cmi give [playerName] sponge 24 -s
  - cooldown:2592000! asConsole! cmi money give [playerName] 140 -s
  - cooldown:2592000! asConsole! cmi sound entity_player_levelup [playerName]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Našel jsi velikonoční vajíčko!","color":"yellow"}]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Získáváš 140€ a 24 kousků mycí houby.","color":"gray"}]
  - delay! 1
  - cooldown:2592000! asConsole! modreq create [playerName]#EasterEvent2021Find#2
easter3:
  Locations:
  - world;146.0;71.0;-86.0
  Commands:
  - cooldown:2592000! asConsole! cmi give [playerName] cake 10 -s
  - cooldown:2592000! asConsole! cmi money give [playerName] 215 -s
  - cooldown:2592000! asConsole! cmi sound entity_player_levelup [playerName]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Našel jsi velikonoční vajíčko!","color":"aqua"}]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Získáváš 215€ a 10 dortíků.","color":"gray"}]
  - delay! 1
  - cooldown:2592000! asConsole! modreq create [playerName]#EasterEvent2021Find#3
easter4:
  Locations:
  - world;51.0;44.0;-142.0
  Commands:
  - cooldown:2592000! asConsole! cmi give [playerName] charcoal 43 -s
  - cooldown:2592000! asConsole! cmi money give [playerName] 119 -s
  - cooldown:2592000! asConsole! cmi sound entity_player_levelup [playerName]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Našel jsi velikonoční vajíčko!","color":"white"}]
  - cooldown:2592000! asConsole! tellraw [playerName] [{"text":"[","color":"yellow"},{"text":"MystiQ","color":"gold"},{"text":"]","color":"yellow"},{"text":" » ","color":"yellow","bold":true},{"text":"Získáváš 119€ a 43 kousků uhlí.","color":"gray"}]
  - delay! 1
  - cooldown:2592000! asConsole! modreq create [playerName]#EasterEvent2021Find#4
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.8

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5-b571
