### ISSUE TITLE
Teleport on lava, first spawn, baltop

### ISSUE THREAD

**Issue by borjxrroyo** [Zrips/CMI#5396]
**Description of issue:**
Hi there, when users do /cmi rt they may teleport into lava and die, I tried the safeteleport permission but doesn't work. Any idea?

And also, how can I set the newbies spawn for my server? I used /setspawn and I've set that world in multiverse but doesn't seem to work, they appear at the world "world"

Finally, I would like to see the balance's top, but I constantly see the message "Wait and try again" https://gyazo.com/cb4312eb285f63faed4c410346ed06b8

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
IgnoreWater and IgnoreLava are set to true in the correct worlds.
The /setspawn is set on the world I need.

```

---

**Cmi Version (using`/cmi version`):**  8.8.2.6

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):**  1.16.5

PD: Please take a look at my suggestion about filters: https://github.com/Zrips/CMI/issues/4429

PD: Players with cmi.commandspy permission cannot spy commands, only being OP.

https://i.gyazo.com/9259f7fc53537df5811eab95b367747b.png

**Comment by borjxrroyo** [comment]
PD: I've also like to put a cooldown into custom commands, so if I have /warp townhall and /townhall as an alias, the second one will also have a cooldown.

**Comment by CloudeLecaw** [comment]
a newbies spawn is set by group :)

here an example where the Newbiegroup called Gast allways spawns at an other place until they reach the group Spieler.
groupmanagement is the part of your Permissionplugin.

```
Spawn:
  # Forces players to login in defined spawn point when logging into server
  SpawnOnJoin: false
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  Main:
    World: world
    X: 33.16315150155524
    Y: 64.0
    Z: 337.765194947924
    Pitch: -20.10004
    Yaw: 0.20717628
    RespawnLocation: false
    Rng: 0
  Groups:
    Gast:
      World: tutorial
      X: -109.08893875494117
      Y: 64.0
      Z: 113.19814302915441
      Pitch: 21.299973
      Yaw: -182.99005
      RespawnLocation: true
      Rng: 0
    Spieler:
      World: world
      X: 33.16315150155524
      Y: 64.0
      Z: 337.765194947924
      Pitch: -20.10004
      Yaw: 0.20717628
      RespawnLocation: true
      Rng: 0
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    World: tutorial
    X: -104.5
    Y: 49.0
    Z: 208.5
    Pitch: 0.0
    Yaw: 0.0
```

You also can define a first spawn for all (even if they are in the Newbie group on first spawn
