### ISSUE TITLE
Working with GeoCity

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5415]
when someone loogs in i just see the country name and the Country code..
CMI has the option to download the GeoCity but i cant get it. How to get this?

if checked the lang file. the langfile just said:

```
      - '[ip][country]'
      newNameHoverCountry: ' &7[country] &f(&2[countryCode]&f)'
```

Result_
![image](https://user-images.githubusercontent.com/12080017/113868937-7bae7080-97b0-11eb-80a5-9f741558fa5b.png)

In config i habe enabled both options...
```
  AutoDownload:
    # In case you dont have GeoIP.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoIp: true
    # In case you dont have GeoLiteCity.dat it will be downloaded automatically on server start. Restart can be needed for it to take effect
    GeoLiteCity: true
  # When enabled you will see skull owner name in action bar when right clicking it
```

The files are in the CMi folder...

So what placeholder does i need to get the GeoCity? 

```
[geocity]?
[city]?
[cityname]?
```
