### ISSUE TITLE
Player info saving during mysql connection problems

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5469]
**Description of issue:**
In case a mysql connection to an external database fails, all sorts of issues occur.
- homes can be wiped
- homes can be coppied from another player
- balance can be wiped

Background: the database is on another machine. Connection issues may occur sometimes. Incidents happen. Rarely, the database connection is unstable for more than a couple of minutes. When players join anyway, the outcome is uncertain. This happened to me 2 times now and I want to prevent this.

I would welcome a more fail safe way to deal with this.
Warn the player that his profile could not be loaded and keep trying.
If the player data cannot be loaded, don't save empty data over it.

Maybe I should consider save to locally stored files. Unfortunately it isn't searchable like a database.
It can't solve questions like:
- What players have a nickname?
- What players are still in prison?

So I therefor would prefer to continue to use mysql databases.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/raw/cdwc2QcD

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
storage:
  method: MySQL
mysql:
  username: censored
  password: censored
  hostname: censored
  database: censored
  tablePrefix: CMI_
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
AutoSaveInterval: 15
ForceSaveOnLogOut: false
ForceLoadOnLogIn: false
```

---

**Cmi Version (using`/cmi version`):** 
8.8.3.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5
**Relevant plugins (Delete if this isn't needed):**
