### ISSUE TITLE
Not Work with UltraPermissions

### ISSUE THREAD

**Issue by Ventuj** [Zrips/CMI#547]
Plugin not work with UltraPermissions.
the plugin does not see the permissions, it reads only * as permission, if I use luckperms my server prison does not recognize the rank the only one able to see them is UltraPermissions.

CMI Version: 7.8.6.2
Server Version: Spigot 1.8.8

**Comment by MCTyler** [comment]
You made Ranks with CMI Ranks and they are not recognized? Here is my example with LP, Works Perfectly!
```
Coal:
  Enabled: true
  DisplayName: "&0Coal"
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Iron
  MoneyCost: 25
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Prison Coal Rank!"
  - "broadcast! &6[playerDisplayName] &eUse &a/rankup &eto Check your Stats."
  - "execute [playerName] ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
  - "execute [playerName] ~ ~ ~ /playsound entity.player.levelup player [playerName]"
  - "lp user [playerName] group add coal"
  StatsRequirements:
  - "PlayTime:180"
  - "travel:1000"
  - "MonsterKills:zombie:3"
  - "MonsterKills:skeleton:1"
  - "MonsterKills:spider:1"
Iron:
  Enabled: true
  DisplayName: "&7Iron"
  AutoRankup: false
  RankupConfirmation: true
  NextRanks:
  - Gold
  MoneyCost: 500
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Prison Iron Rank!"
  - "broadcast! &6[playerDisplayName] &eYou can now Warp to Iron Mine!"
  - "execute [playerName] ~ ~ ~ /summon fireworks_rocket ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[I;11743532],FadeColors:[I;14602026]}]}}}}"
  - "execute [playerName] ~ ~ ~ /playsound entity.player.levelup player [playerName]"
  - "lp user [playerName] group add iron"
  StatsRequirements:
  - "PlayTime:3600"
  - "travel:5000"
  - "blocksmined:coal_ore:1000"
  - "MonsterKills:zombie:10"
  - "MonsterKills:skeleton:10"
  - "MonsterKills:spider:10"
```
