### ISSUE TITLE
The sleeping speedup feature prevents the dropping of cat gifts

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#5480]
**Description of issue:**
The sleeping speedup feature prevents cats from dropping gifts on a regular basis. If the night runs normally, cats drop a gift with a 70% chance. If you place enough cats next to your bed, it is guaranteed that a gift will always be dropped. If you go through the night without a speedup, the cats will drop their gifts normally. If the night is skipped completely, the cats also drop their gifts. If the night is speeded up, the gift process of the cats is usually interrupted and no gifts are dropped. 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds:
    - weltn
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 20
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 1
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

---

**Cmi Version (using`/cmi version`):** 8.8.3.5

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper-586
