### ISSUE TITLE
Playtime rewards are not working as they should

### ISSUE THREAD

**Issue by Teleriann** [Zrips/CMI#5586]
**Description of issue:**
We recently implemented prewards system to our server, reward is set to every 10 hours of playtime. But there is one problem, We have regular server restarts with backups every night, so every night, when for example player plays for 9 hours during the day, then after server restart players has 10 hours cooldown again. 
 
 I found out that there is some problem with database, we have cmi connected to mysql. There is table CMI_users which writes down data fine, all of our players are there, but when i check table called CMI_playtimereward then there is just me and few random players. I tried to create line in this table manually and it works properly.
 
 So root of the problem should be somewhere there.
 
**CONFIG SECTION - PlayTimeRewards:**
```
onlinetime:
  DisplayName: "&7Onlinetime key"
  AutoClaim: false
  Description:
  - "&2Reward for every 10hours online"
  PayEvery: 36000
  Commands:
  - asConsole! crate give p onlinetime 1 [playerName]
```
**CONFIG SECTION - config:**
```
PlaytimeRewards:
  Enabled: true
  ExcludeAfk: true
  RewardInform: 30
  OneTimeAmount: 2
  RequiresPermission: false
```
---
 
**Cmi Version (using`/cmi version`):** 
CMI: 8.8.4.2
**Server Type (Spigot/Paperspigot/etc):** 
Yatopia
**Server Version (using `/ver`):** 
1.16.5

Thanks and sorry for my bad english.
