### ISSUE TITLE
CMI prewards

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#5594]
**Description of issue:**
So playtime rewards randomly stops and goes from start, for example i have rewardd for 10 hours and when you type /cmi prewards it starts from that moment, but again, it randomly stops so you have to type it agait to start it. I posted it once but it still doesnt work even if i updated the CMI to newest version

**CONFIG SECTION:**

```
10hour:
  DisplayName: "&310 hodinová odměna"
  AutoClaim: true
  Description:
  - "        &9&l&nZískáš&r"
  - "&7&l⇨ &31x &e&l&nVote&r &e&l&nTruhla&r"
  - "&7&l⇨ &35000 Kč&r"
  PayEvery: 36000
  Commands:
  - asConsole! crazycrates add V Vote 1 [playerName]
  - asConsole! money give [playerName] 5000
50hour:
  DisplayName: "&350 hodinová odměna"
  AutoClaim: true
  Description:
  - "             &9&l&nZískáš&r"
  - "&d&l&kk &5&l&nMega&r &5&l&nbalíček&r &5&l&nna&r &5&l&n7&r &5&l&ndní&r &d&l&kk&r"
  PayEvery: 180000
  Commands:
  - asConsole! cti MegaBalicek7d [playerName]
```

**Cmi Version (using`/cmi version`):** 8.8.4.4

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-686 (MC: 1.16.5)
