### ISSUE TITLE
Random region being generated *FROM* the world player use /cmi rt (AutoGenerateWorlds: false not working.)

### ISSUE THREAD

**Issue by josephcy95** [Zrips/CMI#5596]
**Description of issue:**
Let's say there's 2 world, a spawn world where there is wolrd border set at 500x500 block radius, then there is a main survival world where world border radius set at 10000x10000, the issue I've noticed is when a player use "/cmi rt world" when he is in the spawn world, a few random region .mca file will be generated in spawn world region folder, instead of just world folder.

A small spawn region that only takes 20MB has grown into 5GB in a month because my players use /cmi rt when they first spawn in spawn world.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  AutoGenerateWorlds: false
  Worlds:
    spawn:
      Enabled: false
      MaxRange: 2
      MinRange: 1
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world:
      Enabled: true
      MaxRange: 10000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`): 8.8.4.4** 

**Server Type (Spigot/Paperspigot/etc): Tested on both Paper and Purpur** 

**Server Version (using `/ver`): Paper Build 712 and Purpur build 1126** 

**Relevant plugins (Delete if this isn't needed): Multiverse-Core**
