### ISSUE TITLE
ctellraw not working with schedule.yml

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5610]
Ive been trying to make random timers for my servers chat, and when putting in a schedule config for them, and reload cmi it doesnt work. Either the schedule doesnt show up, or schedule doesnt autofill at all.

This is the config ive tried to make: https://pastebin.pl/view/9bb809b9

**Comment by CloudeLecaw** [comment]
We also use ctellraw with schedulers they work fine

**Comment by Zrips** [comment]
@ItLucifer-MRPG 
Your file is miss formatted, correct one should look like
```
ChatTimer:
  Enabled: true
  MinPlayers: 1
  MaxPlayers: 10000
  Delay: 6
  Repeat: true
  Randomize: true
  Commands:
  - asConsole!cmi ctellraw all <T>{#B2FDFF>}&lJoin our Discord now! {#D5B0EE<}Discord.gg/mgtNACMpTJ</T><URL>https://discord.gg/mgtNACMpTJ</URL>
  - 'asConsole!cmi ctellraw all <T>{#B2FDFF>}&lCheck out our website webshop: {#F0BDEB<}https://CrystalCraft.me</T><URL>https://CrystalCraft.me</URL>'
  - asConsole!cmi ctellraw all <T>{#B2FDFF>}&lReminder to vote for free rewards!{#ECB5EE<}</T><C>vote</C>
```
Which not only fixes issues but simplifies things by using gradients instead of trying to get correct color for each word
