### ISSUE TITLE
/CMI RT still generate region files in source world instead of target world

### ISSUE THREAD

**Issue by josephcy95** [Zrips/CMI#5619]
**Description of issue:**
This is a continue for this issue https://github.com/Zrips/CMI/issues/5596
The update 8.8.4.5 stated it fixed the issues, but after trying out both 8.8.4.6 and 8.8.4.5 the issue still here, doesn't happen when using other random teleport plugin but only CMI RT

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will not longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: false
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world_the_end:
      Enabled: false
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 1000
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    spawn:
      Enabled: false
      MaxRange: 100
      MinRange: 5
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world:
      Enabled: true
      MaxRange: 9000
      MinRange: 100
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_nether:
      Enabled: false
      MaxRange: 1000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 
8.8.4.6 and 8.8.4.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper (Purpur)
**Server Version (using `/ver`):** 
Latest Purpur build 1132
