### ISSUE TITLE
[Request] Kit editor feature 

### ISSUE THREAD

**Issue by WalkingPixel1** [Zrips/CMI#564]
Feature Request: 

My idea was maybe you could add a faster way to put more time on the cool down as I know you can do shift click but be time I get to day 30 my fingers are dead. So I was wondering if there could be a new feature on there where you can possibly add a time yourself by making it so you type the day in chat or more click options for adding days. 

So .. maybe adding a feature where you can type in chat on how many days you wish to make the not cool down. 

Hope this makes sense lol

**Comment by MCTyler** [comment]
Like just editing the Config file with NotePad++?
```
PvP:
  CommandName: PvP
  Weight: 1
  Enabled: true
  Delay: 86400
  MoneyCost: 1000.0
  Group: PvP
```
