### ISSUE TITLE
[Request] serverStop event

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#569]
serverStop event for `eventCommands.yml`, would be useful for kicking everybody on server stop.
Thanks.

**Comment by CloudeLecaw** [comment]
Hey what About this in shedule.yml?
```
StopServer:
  Enabled: false
  PerformOn:
    1:
      Hour: 0
      Minute: 0
      Second: 2
  Commands:
  - actionbar! &eServer will stop in &630 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &625 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &620 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &615 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &610 &esec!
  - delay! 5
  - actionbar! &eServer will stop in &65 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &64 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &63 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &62 &esec!
  - delay! 1
  - actionbar! &eServer will stop in &61 &esec!
  - delay! 1
  - kickall! &eServer will be back online soon!
  - delay! 1
  - stop
```
