### ISSUE TITLE
Deny private message in vanish bypass

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5772]
**Description of issue:**
A player can message a staff member if he has been unvanished for a moment.

To reproduce:
Staff member has private messages set to false via vanishedit gui
- Joins server in vanish
- Appears
- Disappears (V)
- Player can message staff member.

This can only be avoided by rejoin/switch server.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    PrivateMessages: false
```

---

**Cmi Version (using`/cmi version`):** 
8.8.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5
