### ISSUE TITLE
CMI Portals Not Working Consistently

### ISSUE THREAD

**Issue by winndeer** [Zrips/CMI#5774]
**Description of issue:**

CMI Portals aren't working consistently, they'll sometimes work after editing the portal/right after creating it, but afterwards, (normally or if you teleport or rejoin the server) they'll stop working.

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

# Command section can utilize same custom variables as scheduler. Check schedules.yml file for all possible variables.

Lobby:
  East:
    Loc: 24.0:62.0:-3.0:24.0:72.0:3.0
    enabled: true
    effect: Reddust
    showParticles: true
    Tp: Lobby;0.5;65.0;0.5;0.0;0.02
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: true
    particleAmount: 25
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - Commands-1
  North:
    Loc: -3.0:62.0:-24.0:3.0:72.0:-24.0
    enabled: true
    effect: Reddust
    showParticles: true
    Tp: Lobby;0.5;65.0;0.5;0.0;0.02
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: true
    particleAmount: 25
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - Commands-1
  South:
    Loc: -3.0:62.0:24.0:3.0:72.0:24.0
    enabled: true
    effect: Reddust
    showParticles: true
    Tp: Lobby;0.5;65.0;0.5;0.0;0.02
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: true
    particleAmount: 25
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - Commands-1
  West:
    Loc: -24.0:62.0:-3.0:-24.0:72.0:2.0
    enabled: true
    effect: Reddust
    showParticles: true
    Tp: Lobby;0.5;65.0;0.5;0.0;0.02
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: true
    particleAmount: 22
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - Commands-1

```

**Cmi Version (using`/cmi version`):** 

CMI: 9.0.0.3 SqLite
CMILib: 1.0.2.4
Server: Spigot 1.17-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled
Modules -> 55 enabled 1 disabled: votifier

**Server Type (Spigot/Paperspigot/etc):** 

Spigot 1.17

**Server Version (using `/ver`):** 

Checking version, please wait...
You are 1 version(s) behind

**Comment by Zrips** [comment]
Is this server of yours special in some way? What i mean is that its named as Lobby which indicates to be part of multiverse type server, so does it get unloaded or similar while no one is there? Does this issue happen on other servers?

**Comment by winndeer** [comment]
I just use Multiverse worlds so basically i have Lobby world as the Lobby, then the portals are supposed to teleport you to the actual survival world. However it portals dont teleport even when its to a position in the same world (they work once, then just dont work) They're really inconsistent. I think someone was able to reproduce the problem in their server.

**Comment by winndeer** [comment]
It's one server, i dont use bungee or anything

**Comment by Zrips** [comment]
Could you provide exact version of multiverse plugin and maybe lobby world config file?

**Comment by winndeer** [comment]
Sure, Multiverse version is Multiverse-Core-4.3.0.jar, and lobby world config (in mutliverse) is 

```
  Lobby:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 64.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '6385123784858757453'
    generator: VoidGenerator:<biome>
    playerLimit: '-1'
    allowFlight: 'true'
    ```
    
    however i dont believe its due to multiverse as even when the portal location is to just another place in the same world it wont work. but then again it might be
