### ISSUE TITLE
Unable to define text of ClickHoverMessages

### ISSUE THREAD

**Issue by lejoueur50** [Zrips/CMI#5790]
**Description of issue:**

I'm unable to find where to define the text of ClickHoverMessages when looking to the chat section of the locale file

---

**CONFIG SECTION:**
config.yml
```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
```
Locale file :
```
chat:
    help:
      info: '&eCreate and join chat rooms'
      args: '[create/join/leave/list/invite/kick/listrooms] (chatName/playerName)
        (-private) (-locked) (-persistent)'
    info:
      joined: '&eJoined chat room: &7[chatRoomName]'
      joinedInfo: '&e[playerDisplayName] &7joined chat room'
      alreadyIn: '&eYou are already in &7[chatRoomName] chat room'
      left: '&eLeft &7[chatRoomName] &echat room'
      leftInfo: '&e[playerDisplayName] &7left chat room'
      invite: '&6[playerDisplayName] &einvites you to join chat room: &7[chatRoomName]'
      sentInvite: '&eInvited &6[playerDisplayName] &eto join chat room: &7[chatRoomName]'
      format: '&3|&7[chatRoomName]&3| &6[playerDisplayName]: &r[message]'
      nobody: '&4Nobody is in chat room'
      notOwner: '&4Only chat owner can do this'
      wrongName: '&4Wrong chat room name'
      takenName: '&4Chat room name is taken, use different one'
      notIn: '&4User is not in chat room'
      cantJoin: '&4Chat room is private and you don''t have invitation'
      kicked: '&6[playerDisplayName] &ekicked from chat room'
      cantleave: '&6Can''t leave locked room'
      gotKicked: '&4You got kicked from &7[chatRoomName] &4chat room'
      list: '&e[chatRoomName]&e: &7[list]'
      globalList: '&7[number]. [joined]&e[chatRoomName][private]&e: &7[count][expires]'
      globalListPrivate: '&2(P)'
      globalListJoined: '&2+'
      globalListHover:
        Owner: '&7Owner: [playerDisplayName]'
        Ends: ' &7Expires in: [time]'
        Names: '&7[playerDisplayName]'
```
---

**Cmi Version (using`/cmi version`):** 9.0.0.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper version git-Paper-68 (MC: 1.17)
