### ISSUE TITLE
Schedule I made not working

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#5791]
So I made a chat schedule, which looking at it. it should work fine, but it causes this issue, and doesnt load the schedule file and shows this upon loading up: https://pastebin.com/BZUb6ivn 
Idk if its an issue with the config I made for it, or something just isnt supported that I tried to use, like hex codes or something

This is the config for the schedule:
[WHY.txt](https://github.com/Zrips/CMI/files/6751292/WHY.txt)

**Comment by CloudeLecaw** [comment]
Didnu created two times the same scheduke?

**Comment by CloudeLecaw** [comment]
u make an issue
asConsole!cmi ctellraw
it must be asConsole! cmi ctellraw

**Comment by Zrips** [comment]
@ItLucifer-MRPG 
Miss format.
```
ChatTimer:
  Enabled: true
  MinPlayers: 1
  MaxPlayers: 10000
  Delay: 600
  Repeat: true
  Randomize: true
  Commands:
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lJoin {#B7E8FB}&lour {#BDC8F5}&lDiscord {#C3AAEF}&lnow!{#D5B0EE}&lDiscord.gg/mgtNACMpTJ</T><URL>https://discord.gg/mgtNACMpTJ</URL>'
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lCheck {#B7E8FB}&lout {#BDC8F5}&lour {#C3AAEF}&lwebsite{#D5B0EE}&l& {#ECB5EE}&lwebshop: {#F0BDEB}&lhttps://CrystalCraft.me</T><URL>https://CrystalCraft.me</URL>'
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lReminder {#B7E8FB}&lto {#BDC8F5}&lvote {#C3AAEF}&lfor{#D5B0EE}&lfree {#ECB5EE}&lrewards!</T><C>vote</C>'
  
ChatTimer:
  Enabled: true
  MinPlayers: 1
  MaxPlayers: 10000
  Delay: 600
  Repeat: true
  Randomize: true
  Commands:
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lJoin {#B7E8FB}&lour {#BDC8F5}&lDiscord {#C3AAEF}&lnow!{#D5B0EE}&lDiscord.gg/mgtNACMpTJ</T><URL>https://discord.gg/mgtNACMpTJ</URL>'
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lCheck {#B7E8FB}&lout {#BDC8F5}&lour {#C3AAEF}&lwebsite{#D5B0EE}&l& {#ECB5EE}&lwebshop: {#F0BDEB}&lhttps://CrystalCraft.me</T><URL>https://CrystalCraft.me</URL>'
  - 'asConsole! cmi ctellraw all <T>{#B2FDFF}&lReminder {#B7E8FB}&lto {#BDC8F5}&lvote {#C3AAEF}&lfor {#D5B0EE}&lfree {#ECB5EE}&lrewards!</T><C>vote</C>'
```
You need to add ' at start and end or " in case you are using ' inside the text itself. Other than this you can always parse your yaml file over here https://yaml-online-parser.appspot.com/ which will indicate issue if there is any and might give you better idea what's going on and what needs to be fixed.
