### ISSUE TITLE
Worldlimit fly issue

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#5808]
**Description of issue:**
It worked for a long time but in a recent update it must've changed.

Using this config below, when a player was flying in the overworld and would teleport to any of the above worlds, fly would disable. When they would go back to the overworld, fly would still be enabled without having to use commands. However, now the player has to do twice /fly in order to be able to fly again in the overworld when coming from one of these 3 worlds.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WorldLimits:
  Enabled: true
  Gamemode:
  - world2:Survival
  Fly:
  - world_nether:False
  - world_the_end:False
  - nogard:False
```

---

**Cmi Version (using`/cmi version`):** CMI: 9.0.0.5

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** Tuinity version git-Tuinity-7 (MC: 1.17)
