### ISSUE TITLE
error with the rankup system

### ISSUE THREAD

**Issue by istarengwa** [Zrips/CMI#5838]
**Description of issue:**
Hello, I have a very big problem on my server, I just upgraded it to 1.17, and therefore upgraded CMI to version 9.0.0.9, I use all cmi modules, and the one I use the most is the rankup system.

When changing version, all players lost their rank. And impossible to give them back, when I rank a player, it goes back to the first rank.

When a player does / rankup, it tells him that he has gone up in rank but still leaves him at the first rank and he can therefore go up indefinitely. while always staying at the same rank but by increasing ranks indefinitely thanks to what the rankup gives. "/lp user pseudo promote"

the ranks are more than 50% of my server, if that could be fixed it would help me enormously, for me, and for my players

**CONFIG SECTION (DELETE IF NOT RELEVANT):** a small part of my configuration
```
Vagabond:
  Enabled: true
  DisplayName: '&7Vagabond'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - Manant
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Vagabond&e !
  - cmi heal [playerName]
Vagabondiel:
  Enabled: true
  DisplayName: '&7Vagabondiel'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - Manantiel
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Vagabondiel&e
    !
  - cmi heal [playerName]
Vagabonde:
  Enabled: true
  DisplayName: '&7Vagabonde'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - Manante
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Vagabond&e !
  - cmi heal [playerName]
Manant:
  Enabled: true
  DisplayName: '&2Manant'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - ManantP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &8Manant&e !
  - cmi heal [playerName]
  - lp user [playerName] promote homme
Manantiel:
  Enabled: true
  DisplayName: '&2Manantiel'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - ManantielP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &8Manantiel&e !
  - cmi heal [playerName]
  - lp user [playerName] promote nonbinaire
Manante:
  Enabled: true
  DisplayName: '&2Manante'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - MananteP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &8Manante&e !
  - cmi heal [playerName]
  - lp user [playerName] promote femme
ManantP1:
  Enabled: true
  DisplayName: '&2Manant Palier 1'
  AutoRankup: false
  RankupConfirmation: false
  McMMORequirement:
  - woodcutting:5
  - mining:5
  JobsRequirement:
  - totallevel:2
  ItemRequirement:
  - stone:10
  NextRanks:
  - ManantP2
  MoneyCost: 10
  StatsRequirements:
  - PlayTime:300
  - travel:1000
  - MonsterKills:5
ManantielP1:
  Enabled: true
  DisplayName: '&2Manantiel Palier 1'
  AutoRankup: false
  RankupConfirmation: false
  McMMORequirement:
  - woodcutting:5
  - mining:5
  JobsRequirement:
  - totallevel:2
  ItemRequirement:
  - stone:10
  NextRanks:
  - ManantielP2
  MoneyCost: 10
  StatsRequirements:
  - PlayTime:300
  - travel:1000
  - MonsterKills:5
MananteP1:
  Enabled: true
  DisplayName: '&2Manante Palier 1'
  AutoRankup: false
  RankupConfirmation: false
  McMMORequirement:
  - woodcutting:5
  - mining:5
  JobsRequirement:
  - totallevel:2
  ItemRequirement:
  - stone:10
  NextRanks:
  - MananteP2
  MoneyCost: 10
  StatsRequirements:
  - PlayTime:300
  - travel:1000
  - MonsterKills:5
ManantP2:
  Enabled: true
  DisplayName: '&2Manant Palier 2'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - ManantP3
  MoneyCost: 25
  ExpCost: 350
  StatsRequirements:
  - travel:5000
  - blocksmined:300
  - blocksmined:diamond_ore:3
  - MonsterKills:10
  McMMORequirement:
  - herbalism:10
  - swords:10
ManantielP2:
  Enabled: true
  DisplayName: '&2Manantiel Palier 2'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - ManantielP3
  MoneyCost: 25
  ExpCost: 350
  StatsRequirements:
  - travel:5000
  - blocksmined:300
  - blocksmined:diamond_ore:3
  - MonsterKills:10
  McMMORequirement:
  - herbalism:10
  - swords:10
MananteP2:
  Enabled: true
  DisplayName: '&2Manante Palier 2'
  AutoRankup: false
  RankupConfirmation: false
  NextRanks:
  - MananteP3
  MoneyCost: 25
  ExpCost: 350
  StatsRequirements:
  - travel:5000
  - blocksmined:300
  - blocksmined:diamond_ore:3
  - MonsterKills:10
  McMMORequirement:
  - herbalism:10
  - swords:10
ManantP3:
  Enabled: true
  DisplayName: '&2Manant Palier 3'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  NextRanks:
  - ManantP4
  StatsRequirements:
  - PlayTime:3600
  - MonsterKills:zombie:15
  - MonsterKills:spider:10
ManantielP3:
  Enabled: true
  DisplayName: '&2Manantiel Palier 3'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  NextRanks:
  - ManantielP4
  StatsRequirements:
  - PlayTime:3600
  - MonsterKills:zombie:15
  - MonsterKills:spider:10
MananteP3:
  Enabled: true
  DisplayName: '&2Manante Palier 3'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  NextRanks:
  - MananteP4
  StatsRequirements:
  - PlayTime:3600
  - MonsterKills:zombie:15
  - MonsterKills:spider:10
ManantP4:
  Enabled: true
  DisplayName: '&2Manant Palier 4'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  ExpCost: 150
  NextRanks:
  - ManantP5
  StatsRequirements:
  - PlayTime:7200
  - Swim:1000
  - MonsterKills:50
ManantielP4:
  Enabled: true
  DisplayName: '&2Manantiel Palier 4'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  ExpCost: 150
  NextRanks:
  - ManantielP5
  StatsRequirements:
  - PlayTime:7200
  - Swim:1000
  - MonsterKills:50
MananteP4:
  Enabled: true
  DisplayName: '&2Manante Palier 4'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 35
  ExpCost: 150
  NextRanks:
  - MananteP5
  StatsRequirements:
  - PlayTime:7200
  - Swim:1000
  - MonsterKills:50
ManantP5:
  Enabled: true
  DisplayName: '&2Manant Palier 5'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 50
  ExpCost: 150
  NextRanks:
  - Palefrenier
  Votes: 1
  StatsRequirements:
  - walk:15000
  - HorseTravel:1000
  - ItemsUsed:100
  - PlayerKills:1
ManantielP5:
  Enabled: true
  DisplayName: '&2Manantiel Palier 5'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 50
  ExpCost: 150
  NextRanks:
  - Palefriel
  Votes: 1
  StatsRequirements:
  - walk:15000
  - HorseTravel:1000
  - ItemsUsed:100
  - PlayerKills:1
MananteP5:
  Enabled: true
  DisplayName: '&2Manante Palier 5'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 50
  ExpCost: 150
  NextRanks:
  - Palefrenière
  Votes: 1
  StatsRequirements:
  - walk:15000
  - HorseTravel:1000
  - ItemsUsed:100
  - PlayerKills:1
Palefrenier:
  Enabled: true
  DisplayName: '&2Palefrenier'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 250
  ExpCost: 2500
  NextRanks:
  - PalefrenierP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Palefrenier&e
    !
  - cmi heal [playerName]
  - cmi money give [playerName] 380
  - msg [playerName] L'argent que tu as utilisé pour monter tes premiers rangs t'a
    été rendu
  - lp user [playerName] promote homme
Palefriel:
  Enabled: true
  DisplayName: '&2Palefriel'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 250
  ExpCost: 2500
  NextRanks:
  - PalefrielP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Palefriel&e !
  - cmi heal [playerName]
  - cmi money give [playerName] 380
  - msg [playerName] L'argent que tu as utilisé pour monter tes premiers rangs t'a
    été rendu
  - lp user [playerName] promote nonbinaire
Palefrenière:
  Enabled: true
  DisplayName: '&2Palefrenière'
  AutoRankup: false
  RankupConfirmation: false
  MoneyCost: 250
  ExpCost: 2500
  NextRanks:
  - PalefrenièreP1
  Commands:
  - broadcast &6[playerDisplayName] &eviens de passer au grade de &7Palefrenière&e
    !
  - cmi heal [playerName]
  - cmi money give [playerName] 380
  - msg [playerName] L'argent que tu as utilisé pour monter tes premiers rangs t'a
    été rendu
  - lp user [playerName] promote femme
```

A screenshoot : https://zupimages.net/up/21/27/udxf.png

---

**Cmi Version (using`/cmi version`):** 
9.0.0.9

**Server Type (Spigot/Paperspigot/etc):** 
Purpur 1.17.1

**Server Version (using `/ver`):** 
purpurclip-1261.jar
