### ISSUE TITLE
"schedule_endat" placeholder

### ISSUE THREAD

**Issue by LvXP0** [Zrips/CMI#5864]
If schedule have delay trigger, endat placeholder doesnt work well. Can you fix it?

(Endat placeholder's time is pre-end when delay trigger in schedule)

**Comment by Zrips** [comment]
schedule_endat should show when scheduler ends which is calculated by scheduler start time + all delays it have. Is it showing incorrect time for you?

**Comment by LvXP0** [comment]
Let's assume I use the following schedule below.

```
Test:
  Enabled: true
  Delay: 30
  Repeat: true
  Commands:
  - delay! 10
  - broadcast! 10 seconds
  - delay! 10
  - broadcast! 20 seconds
```
In %cmi_schedule_endat_Test%, it's result start at 50 seconds.
but reset at 20 seconds(not 0)

I mean, I hope %cmi_schedule_endat_[ScheduleName]% is reset at 0 when delay trigger in schedule.
