### ISSUE TITLE
Dying cost money or eco

### ISSUE THREAD

**Issue by NightLife-SG** [Zrips/CMI#5886]
I would like this feature requested as this will add option for server that has keepinventory on to punish people if they die

**Comment by mercurialmusic** [comment]
You can already do this in the eventCommands.yml. See the section:

```
playerDeath:
  Enabled: true
  Commands:
  - cmi money take [playerName] [amount]
```
