### ISSUE TITLE
Trouble with CMI RT in Nether

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#5903]
**Description of issue:**
Not sure if this is a question or a bug. I know you've been working on this mechanic for a bit, but we've still been having difficulty getting random teleportation to work in the nether. It's been a thing for a while that hasn't been a priority for me but players keep complaining about it. I'm sorry I haven't tracked it more closely to tell when it started. But any time someone uses /cmi rt in a nether world they get put in the command cooldown and the command is never successful. No problems in the overworld environments.

I've tried variations on all the settings with no luck, including increasing the number of checks, removing the cooldown, and varying the ignore settings. The only way I was able to get it to work was to set the Y value above the nether roof, but then that's the only safe spot it finds and they always end up on top. No errors in console. Any input would be appreciated!

---

**CONFIG SECTION:**
```
RandomTeleportation:
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will not longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: true
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    resource_nether:
      Enabled: true
      MaxRange: 5500
      MinRange: 100
      CenterX: 0
      CenterZ: 0
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 127
    resource:
      Enabled: true
      MaxRange: 5000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    resource_end:
      Enabled: true
      MaxRange: 4000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    gallifrey:
      Enabled: true
      MaxRange: 9000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    gallifrey_nether:
      Enabled: true
      MaxRange: 4000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 127
  # How long force player to wait before using command again.
  Cooldown: 60
  # How many times to try find correct location for teleportation.
  # Keep it at low number, as player always can try again after delay
  MaxTries: 60
  # List of biomes to exclude from random teleportation
  ExcludedBiomes:
  - OCEAN
  - COLD_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_OCEAN
  - DEEP_WARM_OCEAN
  - FROZEN_OCEAN
  - FROZEN_RIVER
  - RIVER
  - WARM_OCEAN
  - LUKEWARM_OCEAN
```

---

**Cmi Version (using`/cmi version`):** 9.0.1.2; CMILib 1.0.2.13

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-780 (MC: 1.16.5)
