### ISSUE TITLE
Death penalty 

### ISSUE THREAD

**Issue by Dutasmilas** [Zrips/CMI#5905]
I would like this feature to be implemented for CMI

Player dying will lose certain percentage or certain amount of money they had.

so server with keep inventory on will have more balancing economy.

**Comment by CloudeLecaw** [comment]
You can do this allready by simply using ancommand in EventCommands when they die

**Comment by Dutasmilas** [comment]
But I would like a feature that take certain percentage amount that they had,they aren’t any of this option.

for example if they had 1mil,10% would be 1000000 of that.So it not a fix amount when player die.

**Comment by CloudeLecaw** [comment]
playerDeath:
  Enabled: true
  Commands:
  - cmi money take [playerName] 10% -s

**Comment by CloudeLecaw** [comment]
You can also add a meassge to the player..but may the format is confusing
(PlaceholderAPI and Extransion parseothers required)

```
playerDeath:
  Enabled: true
  Commands:
  - cmi money take [playerName] 10% -s
  - msg! [playnerName] You died and lost %cmi_equation_%parseother_{Cloude_Lecaw}_{cmi_user_balance_formatted}%*0.1% Money.
```
