### ISSUE TITLE
Improved formatting

### ISSUE THREAD

**Issue by RAPHAEL599** [Zrips/CMI#5921]
Add new formatting in the economy my such as: QQ, S, SS, OC
![eco](https://user-images.githubusercontent.com/73084300/126589688-570b1c80-bf9d-468b-a401-ec4aafbbb373.png)

**Comment by CloudeLecaw** [comment]
You will also need them here if added

```
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: false
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - mil-1000
    - M-1000000
    - B-1000000000
    - T-1000000000000
    - Q-1000000000000000
    - QQ-1000000000000000000
    - S-1000000000000000000000
    - SS-1000000000000000000000000
```
