### ISSUE TITLE
Teleportation upon completion of flight charges is not safe

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#5930]
**Description of issue:**

When a player runs out of flight ability charges, automatic teleportation is not safe. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
FlightCharge:
  ShowBossBar: true
  EnabledByDefault: false
  AutoSwitch: true
  ExpRechargeCost: 0.0
  MoneyRechargeCost: 0.0
  MaxChargeLevel: 1000
  DeductOnIdling: 0.7
  DeductOnlyForTime: 0.0
  AutoRecharge:
    From: 10.0
    Amount: 25.0
  DeductOnFallMulti: 2
  DamageOnFall: false
  DamageOnToggle: false
  KillOnFall: false
```

---

**Cmi Version (using`/cmi version`):** 9.0.1.3

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** git-Tuinity-23 (MC: 1.17.1)

https://user-images.githubusercontent.com/3759745/126832805-143ed858-1115-43ec-a7f1-d7d143fa3335.mp4
