### ISSUE TITLE
Silent Option of gm command doesnt work correcly

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5963]
We are using the cmi gm command to change players gamemode on worldchange.
We noticed that even if -s is used the result its printed out to console.

Part of EventCommands.yml
```
playerWorldChange:
  Enabled: true
  Commands:
  - ifinworld:plotworld! cmi gm [playerName] 1 -s
```

![127170908-73b2c5b8-1054-4e12-a55f-7984eb6fb20f](https://user-images.githubusercontent.com/12080017/127277680-54970c93-5705-473b-819c-422b8fc244a7.jpg)

![Screenshot_20210727-161839](https://user-images.githubusercontent.com/12080017/127170934-e89184ec-acf9-49b9-83c8-cb1f118a626e.png)

![image](https://user-images.githubusercontent.com/12080017/127278190-aaf90f29-abf5-49fa-878e-2b943c9b41f5.png)
