### ISSUE TITLE
Percentage in sleeping speedup not working

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#5964]
**Description of issue:**
Plugin not responding to "MinBeforeSpeeding: 25%" when using **percentage**, it requires all the players to sleep. It used to work but now it stopped. The config works well when used with whole numbers (like 1, 2, ....)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: world
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: false
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 25%
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

---

**Cmi Version (using`/cmi version`):** 

--------------------------------------------------
CMI: 9.0.2.1 BungeeCord CMIB  SqLite
CMILib: 1.0.3.1 
Server: Purpur 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
Modules -> 53 enabled 3 disabled: tablist, votifier, skin
--------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Purpur

**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1297 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b2056c2 on ver/1.17.1)
