### ISSUE TITLE
Silent Option of nick command doesnt work correcly

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5965]
When using -s in skin command as argument to be silent the feedback is still geting in console 

```
joinServer:
  Enabled: true
  Commands:
  - cmi skin off [playerName] -s
  - cmi nick off [playerName] -s
```

![image](https://user-images.githubusercontent.com/12080017/127283529-bbc746db-c46b-4743-a13d-4e33089ee886.png)

![image](https://user-images.githubusercontent.com/12080017/127283652-a24920e8-106d-4276-b4dd-fdcba66373da.png)
