### ISSUE TITLE
Chat Filter Message Canceling & Console Informing

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#5972]
**Description of issue:**
When using the chat filter feature, some settings cause unexpected outcomes. I am using TownyChat for the that formatting and integration with DiscordSRV. Have tried enabling DiscordSRV support in the CMI config and also disabling ClickHoverMessages as some other tickets suggested to no avail. 

I really like the innovative idea of having the bad actors not know their f bombs and n words are only being shown to them via the 'others' block type. Also really love how the chat filter feature is setup such that someone saying the n word can have different commands run on them than someone who says the a word for instance. So I'm hoping maybe the issues I've come across are easy to fix because I would really like to use the chat filtering within CMI and not have to find a new plugin for just chat filtering. :)

---

Situation # 1 - InformConsole = true and BlockType = all
```yaml
    unicodeBlock:
      Enabled: true
      Group: Unicode
      InformConsole: true
      Regex:
      - '[^\u0000-\u007F]+'
      ReplaceWith: ''
      BlockType: all
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4unicode with: &r[message]'
      Commands: []
```
Result: Triggering this filter does not inform console

Situation # 2 - BlockType = others
```yaml
    unicodeBlock:
      Enabled: true
      Group: Unicode
      InformConsole: true
      Regex:
      - '[^\u0000-\u007F]+'
      ReplaceWith: ''
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4unicode with: &r[message]'
      Commands: []
```
Results: Triggering this filter does not cancel the chat event so DiscordSRV sends the message to the discord chat.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
ChatFilter:
  Enabled: true
  Deny:
    unicodeBlock:
      Enabled: true
      Group: Unicode
      InformConsole: true
      Regex:
      - '[^\u0000-\u007F]+'
      ReplaceWith: ''
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4unicode with: &r[message]'
      Commands: []
```

---

**Cmi Version (using`/cmi version`):** 
9.0.2.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5 Build # 777
**Relevant plugins (Delete if this isn't needed):**
DiscordSRV 1.23.0
TownyChat 0.88
