### ISSUE TITLE
Playtime Reward Autoclaim Not Working

### ISSUE THREAD

**Issue by TheNylox** [Zrips/CMI#5998]
Hello, i got a problem with CMI playtime rewards. Actually the AutoClaim option its not working. Player still have to do /prewards and claim it manually

This is my pRewards config:
https://pastebin.com/EJpt9N4C

**Cmi Version (using`/cmi version`): 9.0.2.0** 

**Server Type (Spigot/Paperspigot/etc):Tuinity 1.16.5** 

**Server Version (using `/ver`):Tuinity git-Tuinity-"901ac35£ (MC 1.16.5)**

**Comment by CloudeLecaw** [comment]
What your config sais?

```
PlaytimeRewards:
  # Enable or disable playtime rewards.
  # This is required if you want to have auto rewards
  Enabled: true
  # When enabled, while player is in afk mode, repeatable playtime rewards will not increase in playtime
  # ATENTION! this setting will not have any effect if you have Afk.StopPlayTime set to true
  # When StopPlayTime set to true, afk will be expluded automatically
  ExcludeAfk: true
  # Defines time in minutes to inform player about pending reward which needs to be claimed
  RewardInform: 15
  # Defines how many one time rewards you want to show in list
  # This will show next X amount rewards from your current playtime
  # No point in listing all rewards if player is still far away
  OneTimeAmount: 2
  # When set to true player will be required to have cmi.prewards.[name] permission node to get particular playtime reward
  RequiresPermission: false
```
