### ISSUE TITLE
Can't change the login message.

### ISSUE THREAD

**Issue by justreathy** [Zrips/CMI#6032]
**Description of issue or feature request:**

I can't change the login message. It's always on: [+] PlayerName

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
`Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: true
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: true
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: false
  DeathMessage:
    # Defines number of players from which to automatically start hiding death messages
    # Set to -1 to disable this
    AutoHideFrom: -1
`
```

---

**Cmi Version (using`/cmi version`):*9.0.2.5* 

**Server Type (Spigot/Paperspigot/etc):*Paper* 

**Server Version (using `/ver`):*1.17,1* 

**Relevant plugins (Delete if this isn't needed):*Chat Manager*
