### ISSUE TITLE
Going Afk creates Hologram at location which does not vanish

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#6054]
**Description of issue:**
When I run /AFK a hologram is created at that location. This hologram updates each time I run the /AFK command. hologram does not appear in the hologram config

The hologram is labeled test according to the cmi hologram tab completion.

Running cmi hologram deleteline test 1 removes hologram however this is an issue as I can not be expected to fix this for all players etc.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Actual Holograms YML -Note it is NOT showing created hologram 

bank:
  Loc: PlayerShops;5.36;66.25;-0.08
  Range: 8
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '&b&lFWS Bank'
  - '&b&lThis Way'
RedDistrict:
  Loc: PlayerShops;1.1;66.37;4.76
  Range: 8
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '&b&lRed District'
  - '&b&lPlayer Shops'
  - '&b&lThis way'
BlueDistrict:
  Loc: PlayerShops;1.12;66.37;-4.67
  Range: 8
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '&b&lBlue District'
  - '&b&lPlayer Shops'
  - '&b&lThis way'
AdminShop:
  Loc: PlayerShops;-3.6;66.25;0.01
  Range: 8
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '&b&lAdmin Shop'
  - '&b&lThis Way'

```

cmi version
[19:34:32 INFO]: --------------------------------------------------
[19:34:32 INFO]: CMI: 9.0.2.6 SqLite-> 9.0.2.7
[19:34:32 INFO]: CMILib: 1.0.3.5
[19:34:32 INFO]: Server: Purpur 1.17.1-R0.1-SNAPSHOT
[19:34:32 INFO]: CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled
[19:34:32 INFO]: Modules -> 55 enabled 1 disabled: votifier
<img width="181" alt="cmi holo 1" src="https://user-images.githubusercontent.com/47970978/130340053-69410ffd-61ab-4419-becc-874b3e48e4ae.PNG">
<img width="254" alt="cmi holo 2" src="https://user-images.githubusercontent.com/47970978/130340054-67198677-d53a-4b8d-a20b-5de593d2ec3b.PNG">

Any additional info I can provide please let me know. Including if needed direct access to the server for testing.
