### ISSUE TITLE
Holograms are updated for one player only

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#6060]
**Description of issue:**

Hello.

Holograms are updated for only one player at a time. If there is more than one player in the hologram update zone, then the hologram update stops for all players except one.
In the video, for comparison, I added the same placeholders to the scoreboard as in the hologram:
[VIDEO](https://youtu.be/XraVlgng8o0)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

holograms.yml:
```yaml
outposttest:
  Loc: w;-256.51;66.62;142.5
  Interval: 0.1
  LOSInterval: 0.1
  Range: 24
  RangeExtra: 24
  Spacing: 0.25
  SpacingIcon: 0.5
  Lines:
  - '%outpost_status%'
  - '%outpost_capping_percent%'
  - '%outpost_capping_player%'
  - '%outpost_capping_team%'
  - '%outpost_capped_player%'
  - '%outpost_capped_team%'
  - '%outpost_controlled_time%'
  - '%outpost_percent_symbol%'
```

Best regards.
---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.2.8 SqLite
CMILib: 1.0.3.6

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-157 (MC: 1.17.1)

**Relevant plugins (Delete if this isn't needed):**
PlaceholderAPI
