### ISSUE TITLE
Timeformat is staffmsg is broken when sendet from server

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6073]
Timeformat in the hover of staffmsg is broken 

We are using staffmsg as joinEvent for some groups so we get noticed when they join

The format when hovering over the stafffmsg of the kind the time playerholder is broken.
For a normal staffmsg from a player is works fine.

```
joinServer:
  Enabled: true
  Commands:
  - check:%cmi_user_group%==Gast! cmi staffmsg [playerName] ist wieder da, hat das Tutorial aber noch nicht beendet.
```
![Snag_15be1329](https://user-images.githubusercontent.com/12080017/130683838-f7d16cbc-1fc8-4f91-9a73-0e5e0b71ec5c.png)
sender from joinEvent

![Snag_15beea30](https://user-images.githubusercontent.com/12080017/130683950-e528ec19-728f-431b-bb45-48042a127eb9.png)
sender staffmsg from me
.
.
.

i checked CMIlibs translation folder. looks fine..
```
  publicHover: '&6gesendete Zeit: &e%server_time_hh:mm:ss%'
  privateHover: '&6gesendete Zeit: &e%server_time_hh:mm:ss%'
  staffHover: '&egesendete Zeit: &6%server_time_hh:mm:ss%'
  helpopHover: '&egesendete Zeit: &6%server_time_hh:mm:ss%'
```

![Snag_15bfe3f1](https://user-images.githubusercontent.com/12080017/130684045-b26c04f3-1571-45a2-a5c9-e41d2dda8c73.png)
