### ISSUE TITLE
flightchage cant work after death or rejoin

### ISSUE THREAD

**Issue by patatoplugin** [Zrips/CMI#6086]
**Description of issue:**
Player cant fly after they die,even if they still have enough flightcharge
Player cant fly after they leave server and rejoin

I dont change the config and it work well.But after an update of CMI,the problem come
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
`FlightCharge:
  ShowBossBar: true
  EnabledByDefault: true
  AutoSwitch: true
  ExpRechargeCost: 1.0
  MoneyRechargeCost: 1.0
  MaxChargeLevel: 9999
  DeductOnIdling: 1.0
  DeductOnlyForTime: 0.0
  AutoRecharge:
    From: 10.0
    Amount: 25.0
  DeductOnFallMulti: 2
  DamageOnFall: true
  DamageOnToggle: false
  KillOnFall: false
  GlowColor: none`
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
9.0.2.9
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.17.1
**Relevant plugins (Delete if this isn't needed):**
