### ISSUE TITLE
Custom Tab Completes does not work for existing commands.

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#6087]
**Description of issue:**
Hello.

Custom Tab Completes feature does not disable or override tab completes for existing commands and aliases.
On my server I have `/l` command, which is a built-in and non-disabable alias for `/lands` command (Lands plugin). I want to reassign the action of the `/l` command and add custom tab completes using the corresponding functionality of the CMI plugin: `CustomAlias.yml`. I managed to reassign the action to the `/ct` command, but the custom tab completes does not work and I am still prompted for the commands for the original `/l` command. I have tested many other commands from other plugins. The result is the same. Based on the results of my tests, I concluded that Custom Tab Completes only works for previously non-existent aliases.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
CustomAlias.yml:

Fully working config version (works and `Cmds:` and `CustomTabs:`) because `/somecommand` alias did not exist until it was added in the `CustomAlias.yml`:
```yaml
CustomAlias:
  somecommand:
    Cmds:
    - ct $1-
    CustomTabs:
    - give kinetic,laser,mortar [playername]
    - giveammo kinetic,laser,mortar [playername] 64
    - reload
```

Not working config version (works `Cmds:` section only) because `/l` alias already registered at server:
```yaml
CustomAlias:
  l:
    Cmds:
    - ct $1-
    CustomTabs:
    - give kinetic,laser,mortar [playername]
    - giveammo kinetic,laser,mortar [playername] 64
    - reload
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.2.9 SqLite
CMILib: 1.0.3.6

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
git-Paper-157 (MC: 1.17.1)

Best regards.
