### ISSUE TITLE
vanish AFK bug

### ISSUE THREAD

**Issue by ItLucifer-MRPG** [Zrips/CMI#6126]
While im in vanish, for a while now I've noticed that if I tab out for a while, I will still get the title and subtitle message even when "Trigger AFK when vanished" is set to false. Ive tested this a few times, to get the same issue each time.

**Comment by CloudeLecaw** [comment]
Where you setted this?

You just have a permission that doesnt set ubautoafk, to manually afk when vanished or to not Show commands

A no autoafk while vanished Option does notnexist.
So this is no issue its a feature request.

For now you can create an alias for vanish
That replaces /vanish
With the following steps:
- set/unset you to vanish
- give u bypass autoafk bypass permission if vanishsybol matches
- remove autoafk bypass permission if vanishsymbol is not matched

So you have 1 command and 2 Specialized commands that get executed / checked each time your using /vanish.

So you see its anneasy to manage thing.

But anoption for 'no afk when vanished' does not exist.

**Comment by ItLucifer-MRPG** [comment]
Its not a feature, there is a setting in vanishedit called "Trigger AFK when vanished" and when you turn it to false,  and sit in vanish for the amount of time you've set auto afk to, it still puts you in AFK, gives you the titlemsg, and the placeholder symbol, if it wasnt made for auto afk, it would be a pointless feature, because the only other way of going afk is /cmi afk, which would make the option redundant

**Comment by CloudeLecaw** [comment]
Did i missed this setting...

```
Vanish:
  # Defines default states of vanish edit options for players
  # This will not have any effect if player already edited his vanish mode with vanishedit command
  Defaults:
    damageToEntity: false
    playerDamage: false
    itemPickup: false
    mobAggro: false
    interaction: false
    noisyChest: false
    informOnLeave: false
    informOnJoin: false
    nightVision: true
    bossbar: true
    afkcommands: false
    PrivateMessages: false
    relogDisable: false
    noMessages: false
    fakeJoinLeave: false
    mobSpawning: false
    stopPlaytime: false
```
I see no noafk when vanished
