### ISSUE TITLE
issues from console with custom aliases...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6151]
i used a custom alias from consone.. may there was a big issues.. i just dont know what went wrong and why..

```
  pongg:
    Cmds:
    - perm:cmi.command.customalias.ping@! msg! [playerName] &cDu kannst diesen Befehl nicht benutzen.
    - perm:cmi.command.customalias.ping#! check:$1==null! msg! [playerName] &cDu musst einen Spielernamen als Ziel hinzufügen.
    - check:$1==0! asConsole! cmi broadcast !&2 Leider hat kein Spieler innerhalb der Zeit mit einem &4&lPONG&2 geantwortet. Daher verfällt der Preis dieses Mal. Vielleicht seid Ihr das nächste Mal ja schneller. =)
    - check:$1!=null! asConsole! cmi usermeta $1 add PingPongGewinn %cmi_random_1_99% -s
    - check:$1!=null! check:%cmi_lastrandom_$1%>=1! check:%cmi_lastrandom_$1%<=33! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt zwei &5&lMystery Boxen&5&l✩✩✩&2. &eHerzlichen Glückwunsch!
    - check:$1!=null! check:%cmi_lastrandom_$1%>=34! check:%cmi_lastrandom_$1%<=66! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt 20 &5&lLulumanten&2. &eHerzlichen Glückwunsch!
    - check:$1!=null! check:%cmi_lastrandom_$1%>=67! check:%cmi_lastrandom_$1%<=99! asConsole! cmi broadcast !&4&l $1&2 hat als erstes mit einem &4&lPONG&2 geantwortet und erhällt 30 &6&lTaler&2. &eHerzlichen Glückwunsch!
    - check:$1!=null! check:%cmi_lastrandom_$1%>=1! check:%cmi_lastrandom_$1%<=33! asConsole! gmysteryboxes give $1 2 3 msg=false
    - check:$1!=null! check:%cmi_lastrandom_$1%>=34! check:%cmi_lastrandom_$1%<=66! asConsole! mysterydust add $1 20 msg=false
    - check:$1!=null! check:%cmi_lastrandom_$1%>=67! check:%cmi_lastrandom_$1%<=99! asConsole! cmi money give $1 30 -s
    - check:$1!=null! asConsole! cmi usermeta $1 remove PingPongGewinn -s
    Tab: true
    CustomTabs:
    - '[playername], 0'
```
i used it from console

How i used the comand:
from console: **pongg Cloude_Lecaw**
so $1 should be Cloude_Lecaw

![image](https://user-images.githubusercontent.com/12080017/132840576-f2c8b20f-5858-4f46-92d7-535d062aea62.png)

Error:
![image](https://user-images.githubusercontent.com/12080017/132851191-4f30c487-2d2d-4cee-94a2-3d953c99ba48.png)

it might be possible this is not useable from console? :3
