### ISSUE TITLE
Tag doesnt support HEX color when putting the chat back to normal color

### ISSUE THREAD

**Issue by Nesseley** [Zrips/CMI#6154]
**Description of issue:**
Set my tag to &e, when players ping me it says
"Nesseley{#DDDDDD} text here" in all yellow

What it should do: only Nesseley should be in yellow.

---
**Cmi Version (using`/cmi version`):** 0.0.3.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-paper-257 1.17.1

**Comment by Nesseley** [comment]
For information: 

Giving the player `cmi.colors.publicmessage.*` fixes the issue, but then again lets them use colors in chat at their own will :)

**Comment by CloudeLecaw** [comment]
Dont forget to Format your chat before the meassage starts ;)

**Comment by Nesseley** [comment]
> Dont forget to Format your chat before the meassage starts ;)

This is not my doing. I cannot change this as it is hardcoded after the tag. No matter what I format in my chat, I can not fix this

**Comment by mrfloris** [comment]
`GroupFormat:` is to customize the cmi chat that happens "before" the `{message}`
`GroupMessageFormat:` is to customize the cmi chat `{message}`after the groupformat.

In groupformat don't customize the {message} part, and visa versa.

**Comment by Nesseley** [comment]
I am using Generalformat

GeneralFormat: ' &8%server_time_HH:mm_GMT+2% [{prefix}&8] {suffix}{displayName} &8» {#DDDDDD}{message}'
Which becomes: https://gyazo.com/a13989234b6b2671f7155a0f7844682c

**Comment by Zrips** [comment]
@Nesseley 
I need clarification what you mean by "Set my tag" and I need Colors section from config file

**Comment by Nesseley** [comment]
Hello! I am talking about this part of the config.yml

```
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: true
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&e'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound entity_chicken_egg:3:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```
    
    
And here is the color section:
```
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      books: true
      # List of strings to ignore when checking chat for color codes player cant use.
      # This will bypass players colorcode restrictions and will allow usage of particular chat formats
      # Applies only for public and private messages
      WhiteList:
      - '&c❤&7'
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true
  # If set to true, players public message who is in your ignore list will not be shown
  IgnorePublicMessage: true
  ```
