### ISSUE TITLE
Votifier Module disabled no matter what

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#6168]
**Description of issue:**
The votifier module is always disabled, regardless of what is in `Modules.yml`

---
```
# Handles votifier system
# Applies for servers from 1.7.x and up
votifier: true
```
---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/60494179/133914590-c558b003-f629-4fe0-8b48-e846bbf5bf42.png)

**Comment by mrfloris** [comment]
The build I use for NuVotifier (dont' use Votifier..)
<https://ci.velocitypowered.com/job/NuVotifier/>
You can also get it here: <https://github.com/NuVotifier/NuVotifier/releases>

Can you confirm which version you're running? Type the following in console please:
```
ver
ver Votifier
```
Is your votifier configured and confirmed to be working? For a single server... not set up for bungee i hope, and test votes and real votes both show up properly in the console?

I see your paper is some github number, mine shows with a build number, maybe try an official jar?
<https://papermc.io/downloads>
Latest build currently is 266

During startup, latest.log, check the cmi loading and NuVotifier loading stuff, can you share that info here as well so we can confirm they work together okay?

It will look like this:
```
[INFO]: [Votifier] Enabling Votifier v2.7.3
[INFO]: [Votifier] Loaded token for website: default
[INFO]: [Votifier] Using NIO transport to accept votes.
[INFO]: [Votifier] Method none selected for vote forwarding: Votes will not be received from a forwarder.
```

```
[INFO]: [CMI] Enabling CMI v9.0.4.1
[INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[INFO]: _______________________________________________________
[INFO]:   Integrating PaperSpigot async methods
[INFO]:   Citizens found.
[INFO]:   55 Enabled and 1 Disabled modules
[INFO]:   Votifier found. Enabling vote listeners
[INFO]:   Loaded (29) portals into memory. Took 15ms
```
(but .. your logs, not mine..)

And from config.yml can you please post the configuration for votifier integration?
```yaml
Votifier:
  # When set to true votifier votes will be counted for player
  CountVotes: true
  # Number of votes one IP can make in last 24 hours
  # Set it to 0 to have unlimited amount
  MaxVotesInADay: 0
  # Cooldown between votes from same service
  # In most cases voting service will have its own cooldown setup
  # But if you need extra one to prevent rapid voting you can define time in seconds over here
  GeneralCooldown: 0
  # When set to false, commands on sucessfull vote will not be performed
  PerformCommands: false
  # Defines commands to be performed when player votes
  # Supports specialized commands and placeholders
  # [serviceName] variable can be used to insert address
  CommandsOnVote:
  - cmi msg [playerName] You're pretty awesome for voting
  # Keep it at false if you dont want to give out extra rewards
  ExtraRewardsEnabled: true
  # Commands will be performed when player collect determined amount of votes
  ExtraRewards:
    '10':
    - cmi heal [playerName]
    - cmi money give [playerName] 1000
    - 'cmi msg [playerName] &6 From the server owner: Thank you for voting!'
    '100':
    - cmi heal [playerName]
    - cmi money give [playerName] 10000
    - cmi give [playerName] diamond 32
    - 'cmi msg [playerName] &6 From the server owner: Woah, 100 votes? Niiice!'
    '1000':
    - cmi heal [playerName]
    - cmi money give [playerName] 100000
    - cmi give [playerName] diamond_ore 64
    - 'cmi msg [playerName] &6 From the server owner: 1k votes, niiiiceeeee !!!!'
  # List of players to be excluded from top voter list
  ExcludeList:
  - 1MBNetwork
  - mrfloris
```
Here's how mine looks like

And from modules.yml, please show your configuration related to votifier as well, here's mine again:
```yaml
# Handles votifier system
# Applies for servers from 1.7.x and up
votifier: true
```

Again, we want YOUR information, im just posting mine to help you make it easier to post yours. im not looking for an answer like "yeah, did that, same" .. i want to see the data.
