### ISSUE TITLE
Riptide bug

### ISSUE THREAD

**Issue by SoniXlash** [Zrips/CMI#6176]
Elytras and riptide works together, even if you set DisableRiptide: true in the config. The only difference is: when DisableRiptide: true, the animation is not shown, but the speed increases as usual.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Launch:
    Time: 2
  # 1.13+ servers. Do you want to disable riptide enchant usage while flying with elytra and trident which has riptide enchant
  # This combination is dangerous as player can reach extreme speed's if allowed to use it
  DisableRiptide: true
  Fix:
    # Disables option to damage yourself while flying with arrows to boost up
    PreventSelfDamage: false
    # Disables option to use rockets to boost yourself while flying with elytra
    PreventRocketUsage: false

```
#######################################
#######################################
```
elytraExploit: true - in modules.cfg
---

**Cmi Version (using`/cmi version`):** 
[22:28:55 INFO]: --------------------------------------------------
[22:28:55 INFO]: CMI: 9.0.4.1 MySQL
[22:28:55 INFO]: CMILib: 1.0.3.9
[22:28:55 INFO]: Server: Paper(259) 1.17.1-R0.1-SNAPSHOT
[22:28:55 INFO]: CMI Economy: Enabled Vault: 1.7.3-bCMI Chat: Enabled
[22:28:55 INFO]: Modules: 45enabled, 11 disabled: coloredArmor, cuffed, disabledEnchants, mirror, playerCombat, votifier, portals, spawnerCharge, warmup, dynamicSigns, totemBehavior
[22:28:55 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
[22:36:41 INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)
