### ISSUE TITLE
wong meaning for Explaintext for rtps config?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6177]
The Config of RPT sais 
` # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates`

`# If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates`

people think that setting the max range now let their people teleport between X-1000 and x1000 in all cases.
But this is just the case if The Center is set to 0.0
If you even Move the center to lets say 3000,3000 Then you never could get it to x-1000

So the explainnote might be changed a litte to something like:
`# Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 blocks between defined center location`

Here a little Example aggain try to get to X-1000+ or Z2000 ;)

```
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world_the_end:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 1000
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 500
      CenterX: -3000
      CenterZ: 4000
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```
