### ISSUE TITLE
Placeholders to calulate with balance and exp

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6181]
i want to create an abuse for dieing.
So i want to create placeholders that calculate a value and round it to a full number for xp and money.
these value i store in metas so i can work with them after in the money take and exp take commands and a msg to the player
after that i remove the metas.

```
playerDeath:
  Enabled: true
  Commands:
  - cmi usermeta [playerName] add moneydeath %cmi_equationint_{cmi_user_balance_formated}/10% -s
  - cmi usermeta [playerName] add expdeath %cmi_equationint_{cmi_user_totalexp}/10% -s
  - cmi money take [playerName] %cmi_user_meta_moneydeath% -s
  - cmi exp take [playerName] %cmi_user_meta_expdeath% -s
  - msg! [playerName] Your Death took its Price. You lost %cmi_user_meta_moneydeath% Dollar and %cmi_user_meta_expdeath% XP.
  - cmi usermeta [playerName] remove moneydeath -s
  - cmi usermeta [playerName] remove expdeath -s
  SourceCommands: []
```

im not sure if this placeholders will do it.
So im asking before. Are these placeholders that i wanne use the correct once?
`%cmi_equationint_{cmi_user_balance_formated}` and `%cmi_equationint_{cmi_user_totalexp}/10%`
or do i have to change them edit them?
