### ISSUE TITLE
[Request] Please add delay commands.

### ISSUE THREAD

**Issue by DutchUser** [Zrips/CMI#619]
Hello.

Could you please add an delay timer for commands that have been set in the config. And that when an player have moved it will be canceld. (the teleport)

ps: Not sure if it can allready, so far i did not found anything about it...

**Comment by DutchUser** [comment]
nvm, found it after i used "warmup" instead "delay" Thx :D

**Comment by MCTyler** [comment]
Use Notepad ++ Find feature...Saves a lot of headaches! ;)

**Comment by DutchUser** [comment]
Uhm, what i'm doing here wrong?

```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.command.[comandName].warmupbypass permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  Enabled: true
  InformOnNoMove: true
  List:
  - spawn:5:false
```

It just insta tp me to spawn whitout timer, ps: Yes it was not opped or had not an opped rank.
