### ISSUE TITLE
Issue with the AFK subtitle

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#6241]
**Description of issue:**

If you get afk-kicked and you rejoin, then teleport to a location it will show the AFK subtitle under the ''Don't move!'' title. This only occurs for the first teleport and doesn't repeat itself then.

---

![image](https://user-images.githubusercontent.com/5664135/136653475-d98604a2-c31c-4486-b3cf-0ebece74627b.png)

**Comment by Sikatsu** [comment]
```
  WarmUp:
    canceled: '&7Teleportatie is geannuleerd omdat je bewoog.'
    counter: '!actionbar!{#FDEA83}--> &7[time] {#FDEA83}<--'
    DontMove: '!title!!subtitle!{#FDEA83}Niet bewegen!'
```
