### ISSUE TITLE
Event Commands playerDeath running on totem

### ISSUE THREAD

**Issue by razorrider7** [Zrips/CMI#6246]
**Description of issue:**
When using CMI's "Event Commands" feature, and adding commands to `playerDeath` in eventCommands.yml, the commands are run even if the player is saved by a totem. Perhaps add a config entry for if the player dies, but has a totem?

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
playerDeath:
  Enabled: true
  Commands:
  - tempban [playerName] 1d dying
  SourceCommands: []
```

---

**Cmi Version (using`/cmi version`):** 9.0.4.3

**Server Type (Spigot/Paperspigot/etc):** Airplane

**Server Version (using `/ver`):** git-Airplane-77 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 01dd14c on HEAD)
