### ISSUE TITLE
rankup miss? do not know why

### ISSUE THREAD

**Issue by lanessNet** [Zrips/CMI#625]
**Description of issue or feature request:**
I want to know why the rankup feature does not work. I attached my configuration file. What's the problem?

**rank.config**
```
user:
  Enabled: true
  DisplayName: "&6[기본]"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - test
  StatsRequirements:
  - "Travel:100"
  Commands:
  - "broadcast! &6[기본] 등급으로 지정"
  - "lp user [playerName] parent add 테스트"
test:
  Enabled: true
  DisplayName: "&6[테스트]"
  AutoRankup: true
  RankupConfirmation: true
  ItemRequirement:
  - "Dirt:10"
  StatsRequirements:
  - "Travel:100"
  - "Walk:100"
  - "Sneak:100"
  - "Sprint:100"
  - "Swim:100"
  - "MobKills:100"
  - "MonsterKills:zombie:100"
  - "PlayerKills:100"
  - "BlocksMined:100"
  JobsRequirement:
  - "totallevel:20"
  NextRanks:
  - testup
  MoneyCost: 100
  Commands:
  - "broadcast! &6[테스트] 등급으로 지정"
  - "lp user [playerName] parent add 테스트업"
testup:
  Enabled: true
  DisplayName: "&6[테스트업]"
  AutoRankup: true
  RankupConfirmation: true
  ItemRequirement:
  - "Dirt:30"
  StatsRequirements:
  - "Travel:100"
  MoneyCost: 1000
  Commands:
  - "broadcast! &6[테스트업] 등급으로 지정 마지막 승급입니다!"
```

**Cmi Version (using`/cmi version`):** 
7.9.0.0

**Server Type (Spigot/Paperspigot/etc):** 
spigot

**Server Version (using `/ver`):** 
1.12.2
