### ISSUE TITLE
End crystal and Respawn anchors in god and vanish

### ISSUE THREAD

**Issue by rmalca** [Zrips/CMI#6277]
**Description of issue:**

Hello, I think this must be a bug. Players with vanish or god can still interact with the end crystal and respawn anchor and can generate explosions and kill other players. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Combat:
  IncludeVictim: true
  Player:
    noGodDamage: true
[...]
Vanish:
  Defaults:
    interaction: false
```

---

**Cmi Version (using`/cmi version`):** 9.0.6.0

**Server Type (Spigot/Paperspigot/etc):** Purpur (PaperSpigot fork)

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1415 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2df73e0 on ver/1.17.1)
