### ISSUE TITLE
hasitem check broken in ics in some cases?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6280]
This is the IC i tried to create....

```
EventweltBackToSpawn:
  Locations:
  - HalloweenWorld;-496.0;83.0;-1431.0
  Commands:
```yml
  Commands:
  - hasitem:carved_pumpkin-1! hasitem:jack_o_lantern-1! cmi sound block_note_block_pling [playerName] -s
  - hasitem:carved_pumpkin-1@! hasitem:jack_o_lantern-1! cmi sound block_note_block_pling [playerName] -s
  - hasitem:carved_pumpkin-1! hasitem:jack_o_lantern-1@! cmi sound block_note_block_pling [playerName] -s
  - hasitem:carved_pumpkin-1! hasitem:jack_o_lantern-1! cmi titlemsg [playerName] &cNo Exis\n&eDont wear pumpkins or lanterns with you! -in:20 -out:20 -keep:30
  - hasitem:carved_pumpkin-1@! hasitem:jack_o_lantern-1! cmi titlemsg [playerName] &cNo Exis\n&eDont wear pumpkins or lanterns with you! -in:20 -out:20 -keep:30
  - hasitem:carved_pumpkin-1! hasitem:jack_o_lantern-1@! cmi titlemsg [playerName] &cNo Exis\n&eDont wear pumpkins or lanterns with you! -in:20 -out:20 -keep:30
  - hasitem:carved_pumpkin-1@! hasitem:jack_o_lantern-1@! cmi spawn [playerName] -s
```

ppl should not be able to spawn back with these two item
current these has command checks get ignoresd.

![image](https://user-images.githubusercontent.com/12080017/138176764-b7431ab3-1156-4b40-9c28-5471cdff2476.png)

Edit: i tried it with a more simple item like glass - same result
