### ISSUE TITLE
First buysign IC got not working without delay anymore

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6281]
I crrated a buysign to buy emerlads but the first BUY shows a wongblance in chat (the money is taken a bit latter...)
then the chat result.  seems to show the wrong value.. looking in the following codes shows u the item and money is taken but the chat result (the last command of the IC seems not so see it.

```
verkaufenSchild16:
  Locations:
  - world;-38.0;65.0;325.0
  Commands:
  - cooldown:1#! hasitem:emerald-16@! msg! [playerName] &fDu brauchst mindestens &2&l16 Smaragde&f, um diese für &e&l16 Taler &fzu verkaufen.
  - hasitem:emerald-16! msg! [playerName] &fDu hast &a&l16 Smaragde&f für &e&l16 Taler&f verkauft.
  - item:emerald-16#! cmi money give [playerName] 16 -s
  - msg! [playerName] &fDein neuer Kontostand ist &e&l%cmi_user_balance_formatted%&f.
```
![Snag_31bbb85](https://user-images.githubusercontent.com/12080017/138179470-d12bd66e-c649-4296-9419-b6db341b05fb.png)

here u see i bought it two times the money is allways the amount before the buy...
this was working fine before in older cmi versions.

![Snag_3180785](https://user-images.githubusercontent.com/12080017/138179085-bb955db4-aece-4459-9ddc-9dfc0102929e.png)

Edit: Addming a delay! of 0.2 fore the mgs! seems to solve the issue now but there is still the question why this is happening now
was not happening before :3
