### ISSUE TITLE
Help with PlayerName Placeholders

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#629]
**Description of issue or feature request:**
there's no list for placeholders specific to the PlayerName option in the tablist config. 

in the headers and footers i can see normal placeholders like "%server_online%" and such... but under playername i see "playerDisplayName" which isn't on the list of placeholders nor is it mentioned in the tablist wiki.. however the picture shows [prefix]Name[Suffix] so obviously its configurable.. but theres not a variable mentioned for prefix and suffix... i would like the name to include the server the player is in on bungeecord. how do i do that? what other placeholders for PlayerName option are there?

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  GeneralFormat:
    PlayerName: '[playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Current &fMoth&2Craft&7 realm: &f%cmi_user_bungeeserver%'
      - '&7Online players: &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%cmi_user_bungeeserver% %player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
```

**Cmi Version (using`/cmi version`):** 
7.9.1.0

**Server Type (Spigot/Paperspigot/etc):** 
spigot

**Server Version (using `/ver`):** 
git-Spigot-642f6d2-6103339 (MC: 1.12.2)
