### ISSUE TITLE
Nameplate command will break "asConsole!" (Revised)

### ISSUE THREAD

**Issue by Raesak** [Zrips/CMI#6304]
Minecraft: 1.17.1
Paper: 353
CMI: 9.0.6.1
CMILib: Latest

This was reported before but the report was a bit messy, the commands were wrong, and it seemed generally confusing.
I found the problem.

When running the nameplate command in a custom alias "asConsole!", "asPlayer!", ETC, it will break if 4-5 hex codes are used.

For example, the command below seems to break after the fourth or fifth color code (also breaks using gradient format), only printing "TEST". It will also break on `-suf:`
If the `asConsole!` is removed, it will print the whole thing "TEST!!".
```
CustomAlias:
  test:
    Cmds:
    - asConsole! cmi nameplate [playerName] -pref:{#B093D3}T{#BE5339}E{#DFB033}S{#33DFA6}T{#338CDF}!{#4833DF}!
```

This bug does not seem to occur when Minecraft color formats are used instead (&b, &c, &e, ETC).

This is a crushing issue when setting up premade nameplates as it makes it impossible to do so. Please fix it so that the full commands will run.
