### ISSUE TITLE
Elimination of certain names on the anvil

### ISSUE THREAD

**Issue by ArrozElManko** [Zrips/CMI#6307]
Hi, I've been using the "CMI" Plugin for a while now and I want to give a suggestion that I would like to see.

My suggestion is to put like a blacklist on the anvils that I mean, a player can put "nig ** - Pu *** ... etc" on the anvils, and it would be nice if there is an obcion to ban those names on the anvils

**Comment by ArrozElManko** [comment]
A blacklist for the anvils

**Comment by Zrips** [comment]
```
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: false
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - mobspawner:([A-z]+ (?i)\w*spawner)
```
Located in general config file. This by default prevents renaming items with something like "Pig Spawner" but you can always add your own regex to include something else if you want.
