### ISSUE TITLE
[Bug] Holding right click whilst gliding with an elytra with a trident with riptide on it in an area that does not have rain allows extreme accelleration

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#6311]
**Description of issue:**
This could be just me misunderstanding a section of the configuration, but this feels like a *very* abusable bug.

The config section in question is this
```yml
Elytra:
  # 1.13+ servers. Do you want to disable riptide enchant usage while flying with elytra and trident which has riptide enchant
  # This combination is dangerous as player can reach extreme speed's if allowed to use it
  DisableRiptide: true
```
When in an area that does not have rain *`(Such as the end)`*, while holding right click with a trident with riptide on it in your hand, you are able to gain insane amounts of speed *`(up to 480 KM/h according to the CMI elytra speedometer)`*

I made a video clip of it
[![as you can see here](https://img.youtube.com/vi/X1tmihHqk1Y/0.jpg)](https://www.youtube.com/watch?v=X1tmihHqk1Y)

and here is a section from my modules.yml file
```yml
#  
# Elytra boost
# Applies for servers from 1.9.x and up
elytraBoost: false
#  
# Elytra launch
# Applies for servers from 1.9.x and up
elytraLaunch: false
#  
# Exploit prevention, like using trident for infinite flight or self damage with arrow
# Applies for servers from 1.9.x and up
elytraExploit: true
```

Additionally, another bug I found whilst debugging this issue, when ElytraBoost is disabled via the modules.yml file, the elytra speedometer stops appearing, even for players with the cmi.elytra.speedometer permission.

---

**Cmi Version (using`/cmi version`):** 
```verilog
--------------------------------------------------
CMI: 9.0.6.0 SqLite-> 9.0.6.1
CMILib: 1.0.4.2
Server: Paper(326) 1.17.1-R0.1-SNAPSHOT
CMI economy: Disabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 46 enabled 10 disabled: deathMessages, mirror, tablist, votifier, moneyCheque, spawnerCharge, vanish, namePlates, elytraLaunch, kits
--------------------------------------------------
```

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 
```verilog
Paper version git-Paper-326 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 56e65fd)
```
