### ISSUE TITLE
Slip option for tpa/tpahere ''CurrentLoc''

### ISSUE THREAD

**Issue by kedavlar** [Zrips/CMI#6338]
Hi, would it be possible in the future to divide the teleport option: '' CurrentLoc '' between tpa and tpahere? an example .. Having the tpa in CurrentLoc: true and the tpahere CurrentLoc: false for example, so as to have the most customizable option for each type of server. Thanks in advance

**Comment by Zrips** [comment]
Will do

**Comment by kedavlar** [comment]
i update to the last version with this feature added but it dosent work.. if i set true or false it dosent change and in the config i only see the option for /tpahere

**Comment by mercurialmusic** [comment]
> 
> 
> i update to the last version with this feature added but it dosent work.. if i set true or false it dosent change and in the config i only see the option for /tpahere

Came here looking for this as well since I had the same with my config, but I added the "tpa:" line manually, backed up my config, held my breath, reloaded CMI, and came back to the full options available. All good now:
```
    CurrentLoc:
      # Applies for tpa, tpahere and tpaall only
      # If set to true then player will be teleported to current player position after accepting teleport request
      # If set to false then player will be teleported to player at which teleport request was issued
      tpa: false
      # Applies for tpahere only
      tpahere: true
```
