### ISSUE TITLE
[BUG] Not respawning at spawn

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#635]
**Description of issue or feature request:**
Players aren't being teleported across worlds to the spawn when they die.
CMI spawn is at `0,0`, people are being teleported to 0,0 when they die but are not teleported across to the spawn world.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ReSpawn:
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Posible respawn locations: spawn, bedLocation, homeLocation, worldSpawn, warp![warpName]
    # Where warp![warName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - spawn
  # Defines respawn order for defines worlds
  # Remove world if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    spawn:
    - spawn
    islands_nether:
    - spawn
    islands:
    - spawn
    mobarena:
    - spawn
```

**Cmi Version (using`/cmi version`):** 
8.0.0.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
MC 1.12.2 (1506)
