### ISSUE TITLE
Incompatible with Leveledmobs plugin

### ISSUE THREAD

**Issue by SvenLameir** [Zrips/CMI#6361]
The spawner handling module can not be active if using the LevelledMobs plugin
https://www.spigotmc.org/resources/levelledmobs-for-1-16-x-1-17-x.74304/

For the other plugin to work spawner handling needs to be disabled.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Spawner handling, like drop, place, egg interactions
# Applies for servers from 1.7.x and up
spawners: false
```

---

**Cmi Version**  9.0.6.2

**Server Type**  paper

**Server Version This server is running Paper version git-Paper-373 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5af80b0)

**Relevant plugins**  LevelledMobs

**Comment by Zrips** [comment]
You will need to be more specific what doesn't work with this plugin

**Comment by ArtamaMeyer** [comment]
> 
> 
> You will need to be more specific what doesn't work with this plugin

When placing spawners created by the plugin Leveledmobs, CMI overwrites the mob and a pig spawner is placed.
When disabling spawner handling in CMI it works correctly but this disables some CMI features using spawner handling.

**Comment by Zrips** [comment]
You can simply try disabling spawner place handling in config.yml file which should no longer change placed spawner type based on spawner type you are actually placing without disabling other functionality.

**Comment by UltimaOath** [comment]
Hello! I am one of the contributors to LevelledMobs and I just wanted to do a check-in on the particular issue. I see that you say there is a specific setting regarding the placement of spawners versus all the feature related to CMI/Spawners.   
Could you share the snippet of config where this resides, so in the future we can tell users of CMI how to resolve the issue?  
Much appreciated!

**Comment by Zrips** [comment]
@UltimaOath 
```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: false
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: false
```
Its located in config.yml, for time being, might be moved to its own file in the future updates, but there is simple way to manage specific actions CMI should handle when it comes to spawner placement of braking them
