### ISSUE TITLE
connected Citicents get lost in interactiveCommands.yml

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6368]
We designed a lot of ICs that we attached to Citicienz plced over the world.

After 1-2 Wekks it ofen hapens that some (sometimes all) connections get los in the interactiveCommands.yml
What a luck we have backups - it would be an horror to reconnect all NPC all time.

So the issue still is, there must be a reason why they get lost sometimes from the file.

Example:
before:
```
npcFischshop:
  ID:
  - 277
  Commands:
  - cooldown:5?#! ptimer give [playerName] WeltAktion emf.shop 2
  - delay! 0.2
  - asPlayer! emf shop
  ReqPerm: false
```
After:
```
npcFischshop:
  Commands:
  - cooldown:5?#! ptimer give [playerName] WeltAktion emf.shop 2
  - delay! 0.2
  - asPlayer! emf shop
  ReqPerm: false
```

looks like there is a chance, that some "inteligent" scan can remove the ID entrie for some unknown reasons...

![image](https://user-images.githubusercontent.com/12080017/141980808-5e934f21-e6ea-4ce3-912e-82b734163f5d.png)

Related other plugins:
Citizens_2.0.28-Build2395.jar

So could u "add" or create a fix that the Citicenze IDs not get lost from interactiveCommands?

Note: it happens near all 1-2 Weeks on the Server one time.
"May a unwanted not delet function if CMI was loaded faster then Citicenzens funtion?"

So please fix it :3 - its annoying to backup the interactiveCommands.yml each week.
