### ISSUE TITLE
Option to Design the Pingbar in Tablist

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6371]
by Default we have the Option to design the Playerbar
Here the default value is name.

Behind the Playername there is allways his PINGBAR...
![image](https://user-images.githubusercontent.com/12080017/142159292-f91917d1-cbaa-451f-a3cc-1a2ec095a7af.png)

It would be nice to be able to design this part of the Tablist too
by assding a setting like: Pingbar... by default it would look like this

```
    PlayerName: '[playerDisplayName]'
    PingBar: '%cmi_player_pingsymbol%'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
```

This would allow us to modfy the look of this like adding a own PINGvalue before like
    PingBar: ``&6%player_ping% %cmi_player_pingsymbol%``
what would result in something like this in the tablist.
![unknown](https://user-images.githubusercontent.com/12080017/142159724-47a33119-88e4-458c-867f-6a7d499309a8.png)

**Why you cant simply use:** ``PlayerName: '  [playerDisplayName]&e      &6%player_ping%'``**?**

Names have different lenght what would make it look ugly in the tablist like you can see here:
You see it does not look very clean....
![unknown](https://user-images.githubusercontent.com/12080017/142160097-8b7c2c7c-2336-4666-b73b-bffd3e3d5d88.png)
e
