### ISSUE TITLE
Global Chat (Bungeecord) not working AT ALL

### ISSUE THREAD

**Issue by mfnalex** [Zrips/CMI#6419]
**Description of issue:**
Global chat via Bungeecord is not working at all. Players can always only see chat messages from their own server, not from others.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
The following config.yml runs on ALL servers
```yml
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Defines name of global chat channel in discordsrv
    GlobalChannel: global


BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true


  # Attention! This will require you to have CMI Bungee plugin which can be found at zrips.net
  # Or direct download https://www.zrips.net/cmi/
  # Do you want to enable private messaging over bungeecord
  BungeeMessages: true
  # Do you want to enable public messaging over bungeecord
  # Player needs to have cmi.bungee.publicmessages.[servername] permission node to be able to send messages to target server
  BungeePublicMessages: true
  # Do you want to enable staff messaging over bungeecord
  BungeeStaffMessages: true
```

---

**Cmi Version (using`/cmi version`):** 9.1.0.0 BungeeCord CMIB SqLite

**Server Type (Spigot/Paperspigot/etc):** Spigot & Paper & Waterfall

**Server Version (using `/ver`):** 3344-Spigot-3c40a6c-4b5f988 and git-Paper-25 (both 1.18) connected through git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462

---

The only output CMI does at all on the proxy is the following:

```
[08:39:29 INFO]: Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[08:39:29 INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[08:39:29 INFO] [CMIB]: Registered channel!
[08:39:29 INFO] [CMIB]: Registered listeners!
[08:39:29 INFO]: Enabled plugin CMIB version 1.0.1.0 by Zrips
[08:39:29 INFO]: Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
[08:39:29 INFO]: Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ab927be:462 by WaterfallMC
```

Players do have the cmi.bungee.publicmessages.[servername] permission. I also checked through LuckPerms (running on the proxy) whether CMI actually checks for that permission at all, but it doesn't: https://luckperms.net/verbose/RiKCHmt9vY
