### ISSUE TITLE
Portals Self Erasing From Config Upon Reload OR Restart

### ISSUE THREAD

**Issue by fauxpinpricks** [Zrips/CMI#6454]
**Description of issue:**
running a server in a multiverse world. in one of the worlds named spgt-1.17.1
portals will not remain in place once the server restart OR when the cmi configuration is reloaded.
i put the error below but in short: it splits up the location world of the portal in to 3 separate lines thus
invalidating the portal configuration and it gets automatically deleted from the config upon reload.

if the server is not restarted the portal functions perfectly, same goes for cmi config reload (portals.yml to be specific)

manually correcting the portal config to have the world name "spgt-1.17.1:" on a single line does not work either.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
This is how the cmi generated in the portals.yml (obtained while the server was still running)
spgt-1:
  '17':
    '1':
      xpfarmexit:
        Loc: -100.0:-36.0:-2572.0:-100.0:-32.0:-2568.0
        enabled: true
        effect: WitchMagic
        showParticles: true
        Tp: spawn;-83.33;60.0;-933.52;-88.48;-3.59
        kickBack: true
        particlesByPermission: false
        requiresPerm: false
        informOnMissingPerm: false
        particleAmount: 40
        particleHide: 0
        activationRange: 80
        commandsWithoutTp: true
        commands: []
######################
```

---

**Cmi Version 9.1.0.1** 

**Server Type (git-Paper-36 (mc 1.18) api version 1.18-R0.1-Snapshot (Git: 76ee105):** 

**multiverse core:**
