### ISSUE TITLE
Nether Portal Creation Prevention not working

### ISSUE THREAD

**Issue by felix920506** [Zrips/CMI#6491]
**Description of issue:**
Setting "PreventCreation" under NetherPortal does nothing

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
NetherPortal:
  # Can prevent nether portal creation entirely. Option to bypass with cmi.netherportalbypass
  PreventCreation: true
  # Maximum height nether portal can be created. Vanilla size is 23
  MaxHeight: 23
  # Maximum width nether portal can be created. Vanilla size is 23
  MaxWidth: 23
```

---

**Cmi Version (using`/cmi version`):** 
9.0.4.5
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-293 (MC: 1.17.1)
