### ISSUE TITLE
Lava death message not working

### ISSUE THREAD

**Issue by EkonC** [Zrips/CMI#6500]
**Description of issue:**

Lava death message is not showing when player dies in lava, default configuration
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Custom:
  Lava:
    General:
    - '&2[playerDisplayName] &7tried to swim in lava'
```

---

**Cmi Version (using`/cmi version`):** 
9.1.0.4

**Server Type (Spigot/Paperspigot/etc):** 
Purpur

**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1452 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0623652 on HEAD)
