### ISSUE TITLE
Sit facing north

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6506]
**Description of issue:**

When sitting on a stairs, the legs of the player refuse to point to north.
All other directions work fine.
When turning around, the legs flip instantly from west to east skipping north

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
Animations:
  # Enable siting on stair block by clicking on them with empty hand or by looking and using command
  # Requires cmi.command.sit.stairs
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: false
  CarpetsAsChairs: false
  RemoveFromChairOnDamage: true
  # Player will sit on chair only after rapid double click
  DoubleClick: false
  # Delay in milliseconds between clicks to sit on chair when double click is enabled
  DoubleClickDelay: 200
  # Range in blocks from player to look up for valid chair block
  ChairRange: 4
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.1.0.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18.1
