### ISSUE TITLE
Mob heads drop chance.

### ISSUE THREAD

**Issue by En0tS** [Zrips/CMI#6539]
**Description of issue:**

Hello. I have enabled custom heads, all drop chance set to 1.0, but players can receive head after fifth mob even without loot bonus enchantment. This chance doesn't matches formula described in config. 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
LootMobBonus:
  Enabled: true
  Lvl1: 100.0
  Lvl2: 200.0
  Lvl3: 300.0

EntityHeads:
  elder_guardian:
    DropChance: 1.0
    LowerWithEachDrop: 50.0
    Heads:
    - 100:Default:MWM3OTc0ODJhMTRiZmNiODc3MjU3Y2IyY2ZmMWI2ZTZhOGI4NDEzMzM2ZmZiNGMyOWE2MTM5Mjc4YjQzNmIifX19
```

---

cmi 9.10.4 on paper-1620 (mc 1.12.2)
