### ISSUE TITLE
/rankup - it only shows the 2nd to the last rank

### ISSUE THREAD

**Issue by MarkE-Official** [Zrips/CMI#6542]
Help it keeps showing the 2nd last rankup on my ranks.yml everytime i /rankup although when i do /ranklist it's organized and set properly.
![unknown (2)](https://user-images.githubusercontent.com/93688829/148381933-74453c83-208a-4d07-be06-f59b6ca2b29a.png)
![unknown (3)](https://user-images.githubusercontent.com/93688829/148381962-c60eb85c-f165-4beb-ace8-52e8ca1aaedb.png)
![unknown (4)](https://user-images.githubusercontent.com/93688829/148381974-628292a2-6287-45e7-bed2-f5aa14c40a4d.png)
![unknown (5)](https://user-images.githubusercontent.com/93688829/148381982-975e8bab-3022-42c2-ac14-0939d08d86b3.png)

My Ranks.yml - https://pastebin.com/KBhvRkqQ
My Luckperms - https://luckperms.net/editor/chFgrnfqug

CMI Version -
![cmiver](https://user-images.githubusercontent.com/93688829/148382802-277bfb21-3097-4958-824b-0fab9544b07b.PNG)

**Comment by Zrips** [comment]
you have issue with your ranks file
```
kalaon:
  Enabled: true
  DisplayName: '&eK&6alaon'
  PermissionRequirement:
  - cmi.rank.kalaon
  AutoRankup: false
  RankupConfirmation: true
  NextRanks:
  - Kalaon
```
You have set that kalaon rank next rank will be that same kalaon rank, which creates all this issue.
