### ISSUE TITLE
Kicked whilst connecting to lobby: Server is in maintenace mode. Come back later

### ISSUE THREAD

**Issue by service2client** [Zrips/CMI#6573]
**Description of issue:**

CMILib file when deleted fixes this issue. Bungeecord hub server being forced into Maintenance Mode by CMIlib file.

I have Mysql installed on server and for the hub the cmi databaseinfo.yml is set to sqlite since mysqlplayerdatabridge is syncing the db from the main survival server where cmi dbinfo is connected to MySQL.

After removing the cmilib file I can login to the server with no errors but at the top of the mc client screen it says "Maintenance Mode"

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## client: message Kicked whilst connecting to lobby: Server is in maintenace mode. Come back later
console message:
[12:39:18 INFO]: UUID of player xxxxxxx is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[12:39:18 INFO]: Disconnecting com.mojang.authlib.GameProfile@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,name=xxxxxxx,properties={textures=[com.mojang.authlib.properties.Property@xxxxxx]},legacy=false] (/xx.17.81.xx:51743): Server is in maintenance mode. Come back later.
[12:39:18 INFO]: com.mojang.authlib.GameProfile@xxxxxxxxx[id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,name=xxxxxxxx,properties={textures=[com.mojang.authlib.properties.Property@xxxxxxx]},legacy=false] (/xx.17.81.xx:51743) lost connection: Server is in maintenance mode. Come back later. ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## # Language file you want to use
Language: EN
# When enabled plugin will try to keep CMILib up to date automatically
# When enabled plugin will try to keep CMILib up to date automatically
AutoUpdate: true
# When enabled plugin will try to clean up outdated CMILib files. This only works when autoUpdate is enabled
# When enabled plugin will try to clean up outdated CMILib files. This only works when autoUpdate is enabled
AutoFileRemoval: true
GlobalGui:
  # Defines item type in empty fields in GUI when its needed to be filled up
  # Defines item type in empty fields in GUI when its needed to be filled up
  EmptyField: BLACK_STAINED_GLASS_PANE
  Pages:
    # Icon for UI previous page button
    # Icon for UI previous page button
    Previous: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0=
    # Icon for UI next page button
    # Icon for UI next page button
    Next: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgyYWQxYjljYjRkZDIxMjU5YzBkNzVhYTMxNWZmMzg5YzNjZWY3NTJiZTM5NDkzMzgxNjRiYWM4NGE5NmUifX19
    # Icon for UI information button
    # Icon for UI information button
    Middle: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmEyYWZhN2JiMDYzYWMxZmYzYmJlMDhkMmM1NThhN2RmMmUyYmFjZGYxNWRhYzJhNjQ2NjJkYzQwZjhmZGJhZCJ9fX0=
Spawners:
  # List of spawners to pick from while using spawner:random variable
  # List of spawners to pick from while using spawner:random variable
  mysterySpawners:
  - skeleton
  - zombie
  - silverfish
  - panda
  - fox  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

I tried a few CMILib versions and the same with all of them 1.1.0.8  1.1.0.7   1.1.0.1  1.0.4.3

**Server Type (Spigot/Paperspigot/etc):** spigot paper .152

**Server Version (using `/ver`):** ubuntu 20

**Relevant plugins (Delete if this isn't needed):**
Plugins (20): BungeeTabListPlus, CMI, CMIEInjector*, CMILib, DiscordSRV, EditSign, GriefPrevention, Maintenance, Multiverse-Core, Multiverse-Portals, MysqlPlayerDataBridge, PlaceholderAPI, ProtocolLib, PyroLib, Roulette, SuperbVote, Vault, ViaVersion, Votifier, WorldEdit
