### ISSUE TITLE
Final rank in ranks.yml not being recognised

### ISSUE THREAD

**Issue by gooderzz** [Zrips/CMI#6582]
**Description of issue:**
10th and final rank within ranks.yml config file is not recognised when running /ranklist. Any commands that are meant to be performed are also not ran as a result of this.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
OneStar:
  Enabled: true
  DisplayName: '{#008000}[1★]&r'
  AutoRankup: true
  DefaultRank: true
  RankupConfirmation: false
  Commands:
  - asConsole! lp user [playerName] permission set group.verified
  - asConsole! lp user [playerName] promote players
  - asConsole! chestcommands open district [playerName]
  NextRanks:
  - TwoStar
TwoStar:
  Enabled: true
  DisplayName: '{#4cfc00}[2★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to two star rank for 6 hours playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to two star rank for 6 hours playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - ThreeStar
  StatsRequirements:
  - PlayTime:21600
ThreeStar:
  Enabled: true
  DisplayName: '{#ffe602}[3★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to three star rank for 12 hours playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to three star rank for 12 hours playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - FourStar
  StatsRequirements:
  - PlayTime:43200
FourStar:
  Enabled: true
  DisplayName: '{#e69204}[4★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to four star rank for 1 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to four star rank for 1 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - FiveStar
  StatsRequirements:
  - PlayTime:86400
FiveStar:
  Enabled: true
  DisplayName: '{#e65a44}[5★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to five star rank for 2 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to five star rank for 2 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - SixStar
  StatsRequirements:
  - PlayTime:172800
SixStar:
  Enabled: true
  DisplayName: '{#d41300}[6★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to six star rank for 7 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to six star rank for 7 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - SevenStar
  StatsRequirements:
  - PlayTime:604800
SevenStar:
  Enabled: true
  DisplayName: '{#be107a}[7★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to seven star rank for 15 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to seven star rank for 15 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - EightStar
  StatsRequirements:
  - PlayTime:1296000
EightStar:
  Enabled: true
  DisplayName: '{#7f03bd}[8★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to eight star rank for 30 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to eight star rank for 30 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  NextRanks:
  - NineStar
  StatsRequirements:
  - PlayTime:2592000
NineStar:
  Enabled: true
  DisplayName: '{#34007c}[9★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to nine star rank for 50 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to nine star rank for 50 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  StatsRequirements:
  - PlayTime:4320000
TenStar:
  Enabled: true
  DisplayName: '{#F0CB05}[10★]&r'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &emoved up to ten star rank for 100 days playtime!
    Give &6[playerDisplayName] &ea GG!
  - asConsole! lp user [playerName] promote players
  - 'asConsole! discord broadcast :cactus: :cactus: **[playerDisplayName] moved up
    to ten star rank for 100 days playtime! Give [playerDisplayName] a GG! **:cactus:
    :cactus: '
  StatsRequirements:
  - PlayTime:8640000
```

**RANKLIST OUTPUT WORKING IN CONSOLE**
```
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 1. [1★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 2. [2★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 3. [3★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 4. [4★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 5. [5★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 6. [6★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 7. [7★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 8. [8★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 9. [9★]
[Sun, 16. Jan 2022 18:29:07 UTC INFO] 10. [10★]
```

**IN GAME NOT WORKING**
![image](https://user-images.githubusercontent.com/35272535/149673035-122570de-4e86-418c-b732-da10f0dfe50c.png)

**PLAYER OVER THE STATS REQUIREMENT AND CONFIRMATION OF LAST RANK**
![image](https://user-images.githubusercontent.com/35272535/149673072-19c6a110-237a-4ebf-b312-c294bf060747.png)

---

```
[Sun, 16. Jan 2022 18:26:27 UTC INFO] --------------------------------------------------
[Sun, 16. Jan 2022 18:26:27 UTC INFO] CMI: 9.1.0.6 SqLite
[Sun, 16. Jan 2022 18:26:27 UTC INFO] CMILib: 1.1.0.8
[Sun, 16. Jan 2022 18:26:27 UTC INFO] Server: Paper(152) 1.18.1-R0.1-SNAPSHOT
[Sun, 16. Jan 2022 18:26:27 UTC INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled
[Sun, 16. Jan 2022 18:26:27 UTC INFO] Modules -> 55 enabled 1 disabled: votifier
[Sun, 16. Jan 2022 18:26:27 UTC INFO] --------------------------------------------------
```
