### ISSUE TITLE
Wrong calculation for repair

### ISSUE THREAD

**Issue by Bibithom** [Zrips/CMI#6599]
**Description of issue:**
When using /cmi repair all, weared armor is counted twice in price.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ItemRepair:
  RepairShare:
    # When neabling you will need to perform full server restart for it to take effect
    # When enabled will prevent players repairing items for others in anvil regular way. They still can use items and repairs normaly for them selfs
    # Can be bypassed with cmi.command.repair.repairshare.bypass
    ProtectNormalRepair: false
    # When enabled will prevent players repairing items for others with CMI command. They still can use items and repairs normaly for them selfs
    ProtectCommandRepair: false
    # Sets durability on item when another picks it up or selects in inventory. Set to 0 or less if you don't want to change durability
    # Attention! Keep this number above 0, otherwise item will get removed without option for the player to repair it throw some means, unless this is what you actually want
    Durability: 1
    # When set to true, player who have cmi.command.repair permission will bypass this protection and can use other user repaired items without any additional actions
    BypassWithRepairPermission: true
    # When enabled additional lore line will be added when player can't use that item. This will not be shown for owner of item
    AddLore: false
    # When set to true, interact event will be canceled to prevent item usage
    CancelEvent: false
    # When set to true, player will get message informing about item usage he dint repaired him self
    InformWithMessage: true
  Repair:
    # List of custom model data id's we should not allow to be repaired with /repair command
    BlockedCustomDataID:
    - 298785423
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    # When item costs money, player will be required to confirm repair action by clicking message in chat
    Confirmation: true
    # When set to true, item repair with /cmi repair will cost money depending on setup
    # Player who performs command will pay repair cost
    # If command gets performed from console, then player whose items are repaired will be paying
    CostsMoney: true
    # Base price to repair item
    # If you have enabled durability check, then this value will wary depending on items condition
    BasePrice: 50.0
    # Item repair cost will depend on how baddly item is damaged
    CheckDurability: true
    # Adds extra cost to repair depending on items cost set in /cmi setworth
    # Value should be set from 0 to 100 range
    WorthPercentage: 0.0
    # Adds extra cost to repair depending on items enchantment cost set in /cmi setenchantworth
    # Value should be set from 0 to 100 range
    # If item has more then one enchantment, then prices will be added up
    enchantWorthPercentage: 0.0
```

---

**Cmi Version (using`/cmi version`):** 9.1.0.6 MySQL

**Server Type (Spigot/Paperspigot/etc) and version:** PAPER(170) 1.18.1-R0.1-SNAPSHOT

---

Some screenshots, 'cause it way more accurate :
![Screenshot_20220123_124904](https://user-images.githubusercontent.com/18242631/150676946-ca65cffa-53be-4761-8c1b-5e2f37771e3e.png)
![Screenshot_20220123_124950](https://user-images.githubusercontent.com/18242631/150676963-86ee3334-d337-4f8a-aa5d-bd1eb791242b.png)

Have tried and there's effectively big price calculated

Thank's for your work, have a nice day !
