### ISSUE TITLE
Regex Support for Nickname Blacklist

### ISSUE THREAD

**Issue by H4zlq** [Zrips/CMI#6610]
Hello, i think its better to add a regex support for nickname blacklist because some user can change the nick similiar to the user name like the image below 
![image](https://user-images.githubusercontent.com/76235095/151512649-582f4f89-5180-4560-99ce-778097da68af.png)

**Comment by CloudeLecaw** [comment]
definatly a needed add of the nick feature

**Comment by mrfloris** [comment]
```yaml
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{prefix}{nickName}&r'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  # If you want to allow any letter from any language use [^\p{L}0-9\-\_]
  ValidNicknameRegex: '[^\p{L}0-9\-\_]'
NickName:
  # Prevents players to change their nick name to one of defined without permission
  # Use lower case
  # cmi.command.nick.bypassblacklist
  # to bypass protection against already in use name/nickname use cmi.command.nick.bypassinuse
  BlackList:
  - admin
  - floris
  - administrator
  - mod
  - moderator
  - team
  - god
  - server
  - staff
  - staf
  # Min length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MinLength: 4
  # Max length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MaxLength: 16
  # Adds prefix for players nickname to indicate that its not real name. This can be added to display name with {nicknameprefix}
  Prefix: '~'
  # When true, will only add nickname prefix when its not same as original name. This can allow colorization or capitalization change without adding prefix
  PrefixWhenDifferent: false
  # When true, online players nick name will be included into tabcomplete
  IncludeInTabComplete: true
  ```
