### ISSUE TITLE
CMI Portal Chat Commands

### ISSUE THREAD

**Issue by Armagedon711** [Zrips/CMI#6624]
Add the ability to add portal commands through just chat instead of Gui or Config. This would allow servers to set up systems to automatically generate portals with pre-applied commands.

Example [/cmi portal <NAME> command <1> <COMMAND>]

Currently, a player must click edit portal commands through the GUI before being able to add commands which are limiting the plugins opportunities.

**Comment by CloudeLecaw** [comment]
u know that you can add predefined command in the config for new portals?

```
Portals:
  # Defines in milliseconds how often to check if player entered portal or not
  # Bigger numbers can help slightly lower server load but small portals, 1 block depth without back wall can be passed through without teleportations if player moves fast enought
  CheckInterval: 200
  # Defines in milliseconds how often to check if player entered portal range for particles to apear
  CheckParticleInterval: 500
  Defaults:
    # Should we perform commands without set destination location by default
    # This only effects newly created portal areas
    # When set to true at moment you create portal you can enter it and commands defined belove will be performed without teleporting you anywhere
    # This can be change for each portal independently with ingame portal editor
    PerformCommands: true
    # Commands to be performed on teleport event
    Commands:
    - cmi effect [playerName] blindness 2 1 -s
```
