### ISSUE TITLE
Cannot create mysql tables

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6640]
**Description of issue:**

New installation of CMI can't create new MySQL tables on startup. Credentials are right, because they work for the other plugin.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
08.02 15:45:02 [Server] WARN java.sql.SQLSyntaxErrorException: Table 'ktmc_test.CMI_users' doesn't exist
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1211)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
08.02 15:45:02 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
08.02 15:45:02 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
08.02 15:45:02 [Server] INFO Loaded (0) player data into memory. Took 7ms
08.02 15:45:02 [Server] WARN java.sql.SQLSyntaxErrorException: Table 'ktmc_test.CMI_playtime' doesn't exist
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayTimes(DBDAO.java:1235)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:610)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
08.02 15:45:02 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
08.02 15:45:02 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
08.02 15:45:02 [Server] WARN java.sql.SQLSyntaxErrorException: Table 'ktmc_test.CMI_playtimereward' doesn't exist
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
08.02 15:45:02 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayerPlayTimeRewards(DBDAO.java:1369)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:611)
08.02 15:45:02 [Server] WARN at CMI9.1.1.2.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
08.02 15:45:02 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
08.02 15:45:02 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
08.02 15:45:02 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
08.02 15:45:02 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
08.02 15:45:02 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: ***********
  password: ***********
  hostname: ***********
  database: ***********
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false

```

---

**Cmi Version (using`/cmi version`):** CMI: 9.1.1.2 MySQL

**Server Type (Spigot/Paperspigot/etc):** Paper(187) 1.18.1-R0.1-SNAPSHOT

**Server Version (using `/ver`):** git-Purpur-1477 (MC: 1.18.1)
