### ISSUE TITLE
 problema nel settaggio di Raccolta spawner problem in setting Spawner collection

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#6689]
**Spawner collection:**

I'm trying to make sure that the spawners can be taken with the silk touch pickaxe but I don't know what to do,
 in the moduleeyml I have set it like this:
 
 
 spawners: true
#  
# Checking spawner place proximity
# Applies for servers from 1.7.x and up
spawnerProximity: true
#  
# Checking spawner charges
# Applies for servers from 1.7.x and up
spawnerCharge: true
---

**Versione Cmi (utilizzando /cmi version 9.1.1.3):
versione paper 1.18.1
Tipo di server (/Paperspigot):**

**Comment by Zrips** [comment]
You need to enable spawner brake handling in main config file
```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # ATTENTION! cmi.dropspawner will be required to get spawner dropping for the player
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: false
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 100
```
