### ISSUE TITLE
Selection visualizer Bug

### ISSUE THREAD

**Issue by moderator10000078** [Zrips/CMI#6691]
**Description of issue:** I find a bug in plugin **SelectionVisualizer**

---

**ERROR**
```
This bug is related to the visualization of FAWE on 1.18.1, when i select territory with a wooden ax there is no visualization, if i use //pos1, //hpos1 or svis we then the visualization appears
link video with ERROR: https://youtu.be/gOz4v7CpIkw
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Language file you want to use
Language: EN
# Shows if there is an available new version on login with sv.versioncheck permission node
ShowNewVersion: true
# Enable or disable world border compatability. In case you dont want world border visualization, just set this to false and restart server
WorldBorder: true
PlotSquared:
  Enter:
    # Will show plot boundaries when entering player owned area
    # This doesnt require player to have /svis plot command permission to be able to see those particles
    Show: true
    # Time in milliseconds for a particle duration when entering plot
    Duration: 2000
# Posible particle effect names: 
Types:
  WE:
    Paste:
      Effect1:
        Effect: reddust
        # Minimum spacing in blocks between particle effects for rows
        # Minal value 0.1
        RowSpacing: 1.0
        # Minimum spacing in blocks between particle effects for collums
        # Minimal value 0.1
        CollumnSpacing: 1.0
        Color: 255;255;180
        # Max amount of particles allow to show for one player
        Cap: 200
      Effect2:
        Effect: reddust
        # Minimum spacing in blocks between particle effects for rows
        # Minal value 0.1
        RowSpacing: 1.0
        # Minimum spacing in blocks between particle effects for collums
        # Minimal value 0.1
        CollumnSpacing: 1.0
        Color: 255;1;255
        # Max amount of particles allow to show for one player
        Cap: 200
      Effect3:
        Effect: reddust
        # Minimum spacing in blocks between particle effects for rows
        # Minal value 0.1
        RowSpacing: 1.0
        # Minimum spacing in blocks between particle effects for collums
        # Minimal value 0.1
        CollumnSpacing: 1.0
        Color: 255;1;1
        # Max amount of particles allow to show for one player
        Cap: 200
      # How often update particles for player. 20 = 1sec
      Interval: 3
      # How many particles to skip. By increasing this will lower update interval but decrese particle count. Can create nice looking moving partile effects
      SkipBy: 10
      # Maximum range in blocks to draw particle effects for player
      # In general view range is unlimited, but keep it at 16-32 range for best experience and performance
      Range: 32
      # For how long in miliseconds (30000 = 30sec) to show particle effects
      # Defines maximum time length
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Cuboid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 168;19;84
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Sphere:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Cylinder:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 168;19;84
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Poly:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 168;19;84
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Convex:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 119;136;153
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 168;19;84
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  CommandBlock:
    Cuboid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  Custom:
    Point:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;182;193
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;250;205
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Chunk:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Grid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 244;164;96
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;218;185
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
      Climbing: false
    Biome:
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
      Climbing: false
  Spawner:
    Sphere:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  Beacon:
    Effect1:
      Effect: reddust
      RowSpacing: 1.0
      CollumnSpacing: 1.0
      Color: 1;255;1
      Cap: 200
    Effect2:
      Effect: reddust
      RowSpacing: 1.0
      CollumnSpacing: 1.0
      Color: 255;1;1
      Cap: 200
    Interval: 3
    SkipBy: 10
    Range: 32
    ShowFor: 30000
    ByDefaultIsEnabled: true
  Kingdoms:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 21;175;21
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;41;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;206;209
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
      Climbing: false
  Factions:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 21;175;21
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;41;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;206;209
        Cap: 200
      Effect4:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 245;222;179
        Cap: 200
      Effect5:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 152;251;152
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
      Climbing: false
  GriefPrevention:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  PlotSquared:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 253;245;230
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 123;104;238
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  WG:
    Cuboid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
    Poly:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  Res:
    Cuboid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 173;255;47
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;250;205
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  ResSub:
    Cuboid:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 233;150;122
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  Towny:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 170;255;170
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
      Climbing: false
  DiceFurniture:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  WorldBorder:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  ChunkyBorder:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  Jobs:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;255;1
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 255;1;1
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 190;1;255
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
  CMI:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 100;149;237
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 180;255;107
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true

```

---

**SelectionVisualizer version 3.1.0.0:** 

**Pufferfish** 

**git-Pufferfish-42(MC-1.18.1):** 

**Fast Async WorldEdit(FAWE):**
