### ISSUE TITLE
check with delay togeher doesnt work in EventCommands.yml

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6740]
i added a check with a delay for event commands join Server Event
the delay only should be when the check is true
here is the setting
```
joinServer:
  Enabled: true
  Commands:
  - check:%cmi_user_uuid%==f24df990-9c6b-4f32-938a-4c91a26d31f4! delay! 4
  - check:%cmi_user_uuid%==f24df990-9c6b-4f32-938a-4c91a26d31f4! cmi exp Cloude_Lecaw add 1 -s
```

This should check for my UUID and use dely 4 secounds if its true on login
combines with this check it does not work (the delay does not work)
it only works when i remove the check before the delay. But thats not what i want
i want the delay only happens when the UUID check is true...

i renember once there was a fix for delay combines with checks
but looks like it was not made for all areas like the EventCommands :3

![Snag_adafbe](https://user-images.githubusercontent.com/12080017/158805900-f0c3fb23-8eb6-4a6c-82ab-d94ccf309d64.png)
