### ISSUE TITLE
Play Time Rewards Bug Report

### ISSUE THREAD

**Issue by moderator10000078** [Zrips/CMI#6769]
**Description of issue:**

---

**ERROR:**
```
I have a Play time reward to issue money once at a certain time, if you set "AutoClaim: true", then the reward will not be issued, but with "AutoClaim: false" everything is issued, video with this bug: https://youtu.be/FtuwxNplwEQ
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
*in PlayTimeRewards:*

money:
  DisplayName: "&7money"
  AutoClaim: true
  StackRewards: false
  Description:
  - "&2money"
  PayEvery: 10
  Commands:
  - asConsole! cmi money give [playerName] 50
```

---

**Cmi Version - 9.1.3.2** 

**Server Type - Paperspigot** 

**Server Version - git-Pufferfish-42 (MC: 1.18.1)**
