### ISSUE TITLE
Eventcommands spectator mode

### ISSUE THREAD

**Issue by Impactic48** [Zrips/CMI#6798]
**Description of issue:**
If you put a player immediately into spectator mode with event commands, it won't allow them to fly underground.

But if you add "delay! 1" and then put them into spectator mode on respawn with event commands then it'll allow players to fly underground.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Doesn't allow players to fly underground:
```
playerRespawn:
  Enabled: true
  Commands:
  - cmi gm spectator [playerName]
```
Allows players to fly underground:
```
playerRespawn:
  Enabled: true
  Commands:
  - delay! 1
  - cmi gm spectator [playerName]
```

---

**Cmi Version (using`/cmi version`):** 9.1.3.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper (278) 1.18.2
