### ISSUE TITLE
Improvement of the /cmi options (new)

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6807]
Hi @Zrips and thanks for this awesome update!

For the /cmi options, I think it would be handy to add the "toggle" value, it would simplify the task a bit more for several things.
Example: `/cmi options cmdspy toggle`.

~ **Noltox** ~

**Comment by CloudeLecaw** [comment]
You can do enable and disable this by the options command.
Like `cmi Options Noltox cmdspy enabled/disabled` for other player
And `cmi options cmdspy enabled/disabled`  for youself
Well its not a toggle but its possible to enable / disable it by command.
Also you could add a meta check and preform the comand in an alais depending on its state

**Comment by NoltoxGit** [comment]
> You can do enable and disable this by the options command. Like `cmi Options Noltox cmdspy enabled/disabled` for other player And `cmi options cmdspy enabled/disabled` for youself Well its not a toggle but its possible to enable / disable it by command. Also you could add a meta check and preform the comand in an alais depending on its state

Hi,

Yes I understood how it works, but creates an alias, while before the maj we could switch the option with a simple command, it was rather simple x)

~ Noltox ~

**Comment by CloudeLecaw** [comment]
you can bring back these commands as an alias.

chatspy:
- Set Meta - State
- Check MetaSate Enabled - command 1 - turn it off
- Check MetaState Not Enabled - command 2 - turn if on
- remove Meta State

you see it could be done in 4 lines in the alias to have a switchable  chatspy command ;)

**Comment by CloudeLecaw** [comment]
here a little example how this could look as custom alias (PAPI and PAPI Expansion parseother needed, and it CANT be runed from console because parseing others dont work from console..)

```
  chatspy:
    Cmds:
    - check:$1!=%cmi_user_name%! asConsole! cmi usermeta [playerName] add chatspymeta %cmi_user_spy% -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==enable! cmi options [playerName] chatspy disable -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==enable! msg! [playerName] &cYour Chatspymode was disabled.
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==disable! check:$1!=null! cmi options [playerName] chatspy enable -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==disable! msg! [playerName] &2Your Chatspymode is enabled now.
    - check:$1!=%cmi_user_name%! asConsole! cmi usermeta [playerName] remove chatspymeta -s
    - check:$1==null! asConsole! cmi usermeta [playerName] add chatspymeta %cmi_user_spy% -s
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==enable! cmi options [playerName] chatspy disable -s
    - check:$1==null! check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==enable! msg! [playerName] &cYour Chatspymode was disabled.
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==disable! check:$1!=null! cmi options [playerName] chatspy enable -s
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==disable! msg! [playerName] &2Your Chatspymode is enabled now.
    - check:$1==null! asConsole! cmi usermeta [playerName] remove chatspymeta -s
    - check:$1!=%cmi_user_name%! cmi usermeta [playerName] add chatspymeta %cmi_user_spy% -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==enable! cmi options [$1] chatspy disable -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==enable! msg! [playerName] &2You disabled $1s Chatspymode.
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==disable! check:$1!=null! cmi options [$1] chatspy enable -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==disable!==disable! msg! [playerName] &2You enabled $1s Chatspymode.
    - check:$1!=%cmi_user_name%! asConsole! cmi usermeta $1 remove chatspymeta -s
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername]'
```

**Comment by mercurialmusic** [comment]
Thank you for that, truly. I think this does illustrate, though, how complicated this has suddenly become.

**Comment by CloudeLecaw** [comment]
well u may see i corrected my example from before ;) there was a little mess with the == and != XD

**Comment by NoltoxGit** [comment]
Hello @CloudeLecaw, I am replying a bit late,

I put this in my customalias.yml folder, and it doesn't work. When I execute the command, nothing happens (and there are 0 errors in the console)

**Comment by CloudeLecaw** [comment]
Well nothing happened why you enter /chatspy? Well i will check today. Give me some hours to get home first :3

**Comment by CloudeLecaw** [comment]
i tested this one out

```
  chatspy:
    Cmds:
    - check:$1==%cmi_user_name%! asConsole! cmi usermeta [playerName] add chatspymeta %cmi_user_spy% -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==true! asConsole! cmi options [playerName] chatspy disable -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==true! msg! [playerName] &cYour Chatspymode was disabled.
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==false! asConsole! cmi options [playerName] chatspy enable -s
    - check:$1==%cmi_user_name%! check:%cmi_user_meta_chatspymeta%==false! msg! [playerName] &2Your Chatspymode is enabled now.
    - check:$1==%cmi_user_name%! asConsole! cmi usermeta [playerName] remove chatspymeta -s
    - check:$1==null! asConsole! cmi usermeta [playerName] add chatspymeta %cmi_user_spy% -s
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==true! asConsole! cmi options [playerName] chatspy disable -s
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==true! msg! [playerName] &cYour Chatspymode was disabled.
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==false! asConsole! cmi options [playerName] chatspy enable -s
    - check:$1==null! check:%cmi_user_meta_chatspymeta%==false! msg! [playerName] &2Your Chatspymode is enabled now.
    - check:$1==null! asConsole! cmi usermeta [playerName] remove chatspymeta -s
    - check:$1!=%cmi_user_name%! asConsole! cmi usermeta $1 add chatspymeta %cmi_user_spy% -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==true! asConsole! cmi options [$1] chatspy disable -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==true! msg! [playerName] &2You disabled $1s Chatspymode.
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==false! asConsole! cmi options [$1] chatspy enable -s
    - check:$1!=%cmi_user_name%! check:%parseother_{$1}_{cmi_user_meta_chatspymeta}%==false! msg! [playerName] &2You enabled $1s Chatspymode.
    - check:$1!=%cmi_user_name%! asConsole! cmi usermeta $1 remove chatspymeta -s
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername]'
```

works fine

![Snag_ce237](https://user-images.githubusercontent.com/12080017/164771851-bed38974-4043-4f70-b284-805dab1fcf68.png)

may u missed something.. ok lets see

1. Install PlaceholderAPI  https://www.spigotmc.org/resources/placeholderapi.6245/
2. Install PlaceholderAPI Expansion PareOther https://api.extendedclip.com/expansions/parseother/
3. make sure the jar is located inside PlaceholderAPI/expansions folder
![Snag_f6354](https://user-images.githubusercontent.com/12080017/164772244-eff02df1-498d-43d1-9687-3d8b6b93b87a.png)
4. restart the server

The expansion is needed in case u use it on other players.
![Snag_1154b4](https://user-images.githubusercontent.com/12080017/164772531-30362bc4-d33b-467b-9ebe-c53b955ed97f.png)
