### ISSUE TITLE
config.yml/ Teleport.CurrentLoc dont work

### ISSUE THREAD

**Issue by jack444410** [Zrips/CMI#6831]
**Description of issue:**
when I edit tpahere to false in config, it does not work as what it should function.
According to the description, it should teleport the player to the location where the tpahere request was sent.
In contrast, it still directly teleports to the player who sent the tpahere request.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    CurrentLoc:
      # Applies for tpa, tpahere and tpaall only
      # If set to true then player will be teleported to current player position after accepting teleport request
      # If set to false then player will be teleported to player at which teleport request was issued
      tpa: false
      # Applies for tpahere only
      tpahere: false
```

---

**Cmi Version (using`/cmi version`): 9.1.3.3

**Server Type (Spigot/Paperspigot/etc): Paper

**Server Version (using `/ver`): 1.18.2

**Relevant plugins (Delete if this isn't needed):**
