### ISSUE TITLE
Hologram with multiple click actions issues

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6851]
i created a little hologramm
It should interact onf leftclick, rightclick, shiftrightclick and shiftleftclick
so see the Result i let the interaction print a little msg..
now the issue is when i use SHIFT+left or right click it executed all 4 commands instead of just one

```
TestHolo:
  Loc: world;1725.03;70.25;1633.24
  Interval: 0.5
  LOSInterval: 9.59
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - '!leftclick! item:stone-1?! msg! [playerName] LEFT'
  - '!rightclick! item:stone-2?! msg! [playerName] RIGHT'
  - '!shiftleftclick! item:stone-3?! msg! [playerName] SHIFT LEFT'
  - '!shiftrightclick! item:stone-4?! msg! [playerName] SHIFT RIGHT'
  Lines:
  - ICON:DIAMOND_ORE-64
```

![image](https://user-images.githubusercontent.com/12080017/165382126-01469157-5d72-4a00-b23c-a83f0437f61d.png)

Here a little video:
https://streamable.com/lfgrqy

![image](https://user-images.githubusercontent.com/12080017/165380208-f6c65258-1cc9-4418-ab6e-123f03837f2c.png)
