### ISSUE TITLE
Cmi warns command add perform command placeholders

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#6867]
is it possible to add placeholders to the warning command perform section like that:

```
Warnings:
  Default:
    LifeTime: 86400
    Points: 1
    DefaultReason: '&7Violated server rules'
  Categories:
    Swear:
      LifeTime: 86400
      Points: 3
      DefaultReason: '&7Swearing'
    Grief:
      LifeTime: 86400
      Points: 10
      DefaultReason: '&7Griefing'
    Bug:
      LifeTime: 86400
      Points: 30
      DefaultReason: '&7Using bugs'
    Cheat:
      LifeTime: 86400
      Points: 50
      DefaultReason: '&7Using cheats'
  Perform:
    '20':
    - cmi tempban [playerName] 5m &cTemporary banned for [reason]!
```

i want that cmi hands over the [reason] and maybe the [sender] to the Perform section.
It would be nice if the request can be addet to cmi thank you for your attention
