### ISSUE TITLE
Change world bug report

### ISSUE THREAD

**Issue by moderator10000078** [Zrips/CMI#6923]
### Description of Issue

immortality is disabled on the server when teleporting, but when changing the world it appears

### Version Information

```shell
CMI version - 9.4.1.7
```

### Errors

```shell
immortality is disabled on the server when teleporting, but when changing the world it appears
Report Video - https://youtu.be/Q1WENhopmd8
```

### Relevant Config Sections

```yaml
# Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 0

  # Time in seconds we want to give for playes who joins server a immortality state
  # Set this to 0 to disable
  # Max 60 seconds
  ImmortalityOnJoin: 0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
