### ISSUE TITLE
Warps only 20 out of 28.

### ISSUE THREAD

**Issue by MC-MrBirdy** [Zrips/CMI#6933]
### Description of Issue

Only 20 out of 28 warps are displayed per page when the config is set to 28.
Even having a higher number in the config doesn't seem to solve the issue.

Yet having 28 warps will display 20 on page 1 and the remaining 8 on page 2.
These 8 slots can be any slot, as long as a page has 8 empty slots.

Tested with just CMI and CMILib (with their default configs) to verify that no other plugins cause any issues.

How to reproduce:
- In the config.yml set perPage to 28 (or above)
- Create 28 warps
- Check page 1 and only 20 are displayed
- Check page 2 and the other 8 are displayed

### Version Information

```shell
CMI: 9.1.4.7 SqLite
CMILib: 1.1.2.5
Server: Paper(349) 1.18.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 55 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
Warps:
  # When set to true, warps list will be shown in GUI instead of chat list
  GUI: true
  # Automatically opens GUI when created new warp point
  GUIOnCreation: true
  # Minimal length of warp name
  MinLength: 4
  # Maximal length of warp name
  MaxLength: 16
  # How many warps to show in each page
  perPage: 28
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
