### ISSUE TITLE
Unexpected exception while parsing console command "migratedatabase"

### ISSUE THREAD

**Issue by rad1914** [Zrips/CMI#6938]
### Description of Issue

Hello, cmi throws an error every time I try to migrate my SQLite database to MySQL, having filled in all the information correctly, and having restarted the server when changing the configuration. (I'm using the latest compilation of Purpur 1.18.2) 

### Version Information

```shell
CMI: 9.1.4.7
```

### Errors

```shell
https://pastebin.com/fmtbwMs4
```

### Relevant Config Sections

```yaml
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: mysql
mysql:
  # Requires Mysql.
  username: ***
  password: ***
  hostname: ***:***
  database: ***
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: true
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 60
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false
```

### Relevant Plugins

Chunky, CMI, CMIEInjector*, CMILib, DiscordSRV, floodgate, Geyser-Spigot, LiteBans, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard. (All up to date) 

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
