### ISSUE TITLE
Death Messages

### ISSUE THREAD

**Issue by Person0z** [Zrips/CMI#6946]
### Description of Issue

So enabling custom death messages, the pre-put ones there don't work, place holders, for example: instead of it being "Person0z died from a zombie...)" It does "[playerDisplayName] died from a [mobName]"

### Version Information

```shell
--------------------------------------------------
CMI: 9.1.5.0 SqLite
CMILib: 1.1.2.6 
Server: Purpur 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled 
Modules -> 55 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
Wither_skeleton:
    General:
    - '&2[playerDisplayName] &7killed by &2[mobName]'
    Item:
    - '&2[playerDisplayName] &7killed by &2[mobName] &7with &2[item]'
```

### Relevant Plugins

Vault 1.7.3-b131

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
