### ISSUE TITLE
9.2.0.2: Time is "frozen"

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#6976]
### Description of Issue

The time freezes at 5:30 am. Actually it does not freeze but days pass super fast (each tick starts new day). After using command `/time 5:31` the time unlocks BUT goes like 3-5 times quicker.

The issue starts to appear as soon as players speed up time using beds. I think the time goes as fast as sleep speedup after command usage, so this sleep speedup might be an issue at this point.

I attach `Time` config section as requested though I did not touch it. I also include `Sleeping` section as it might be relevent to the problem.

Thanks ahead.

### Version Information

```shell
[15:35:46 INFO]: --------------------------------------------------
[15:35:46 INFO]: CMI: 9.2.0.2 BungeeCord CMIB  SqLite
[15:35:46 INFO]: CMILib: 1.2.0.2
[15:35:46 INFO]: Server: Purpur 1.18.2-R0.1-SNAPSHOT - build 1628
[15:35:46 INFO]: CMI Economy: Yes Vault: 1.7.3-b CMI Chat: Off
[15:35:46 INFO]: Modules -> 51 on 5 off: tablist, ranks, playerCombat, votifier, headDrop
[15:35:46 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Time:
  # Defines preset time
  Day: '12:00'
  Night: '24:00'
  Morning: 06:00
  Dusk: '18:00'
  AutoTime:
    # Time in seconds time in game will be adjusted to match real
    # Keep it at arround one minute
    Interval: 60
    # Enables by default smooth sun transition to new time
    # You can always override this setting with -smooth variable in time command
    Smooth: true
    # Speed of smooth transition
    # 100 will mean that sun moves 100 times faster than usual until it reaches target time
    SmoothSpeed: 100
    # Worlds effected by autotime adjustment
    Worlds:
    - ''
  # Allows you to change vanilla time speed to your own liking and needs
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: []
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: false
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 20
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 1.5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 15%
    # When set to true online players will be informed about missing sleeping people count
    Inform: false
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
