### ISSUE TITLE
Can't skip night

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6998]
### Description of Issue

When there is only 1 player online, the night won't be skipped.
When 2 players are online, the night goes quicker.

Used to work fine before version 9.2.0.3
I tried `MinBeforeSpeeding: 1` in absolute number and in percentages (1%).

I can't reproduce it on other servers. So I guess there must be something awkward on this particular server/in this version.
Server contains multiple worlds.

### Version Information

```shell
CMI: 9.2.0.3 MySQL
CMILib: 1.2.0.2
Server: Purpur 1.18.2-R0.1-SNAPSHOT
CMI economy: Ingeschakeld Vault: 1.7.3-b CMI Chat: Ingeschakeld
Modules -> 31 enabled 25 disabled: cuffed, mirror, tablist, versionCheck, moneyCheque, noTarget, elytraBoost, eventCommands, coloredArmor, playerCombat, votifier, attachedCommands, spawnerCharge, namePlates, launchPad, armorstand, portals, holograms, dynamicSigns, playerChatTag, flightCharge, disabledEnchants, worldLimitsElytra, ranks, selection
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: []
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: bossbar
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 1
    # When set to true online players will be informed about missing sleeping people count
    Inform: false
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mare-on** [comment]
Server version: Paper 1.19.1
CMI version: 9.2.3

Bug is stil in game, night can't be skipped.

**Comment by mare-on** [comment]
Sleeping is still broken... will be there any fix in near updates?

CMI verrsion 9.2.3.7
Server version: Paper 1.19.2-137

**Comment by mrfloris** [comment]
Hey there, sorry to hear this issue has persisted all the way to 1.19.2 and the latest cmi/cmilib combo, I wonder what your configuration options are, so perhaps share those, and perhaps a list of plugins/ or at least the ones that might handle core features of a server, deal with game rules, world management, etc. to see if there's any known conflicts potentially.

what values do you have for these settings below?

`modules.yml`
```yaml
# Handles home bed interactions and bed destroy events. Disabling this homes will still work
# Applies for servers from 1.7.x and up
homeInteractions: true
```

`config.yml`
```yaml
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: []
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 50
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 1
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

still in `config.yml` under vanish:
```yaml
sleepIgnore: true
```

And permission-wise, in case you `*` wildcard and run as `operator` on the server, can you please share the output of this for the player that has an issue with sleeping?

```
> cmi haspermission JaCkperByte cmi.sleepignore
[16:50:10 INFO]: --------------------------------------------------
[16:50:10 INFO]: JaCkperByte -> cmi.sleepignore
[16:50:10 INFO]: Permission is not set for player and he is not OP. Results to Disabled
>
```
Check the perms perhaps, make sure it's set correctly on the groups/players

Hopefully, some additional information will help @Zrips reproduce/debug this and perhaps find a workable solution.
