### ISSUE TITLE
Bug with "&" Symbol

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#7006]
### Description of Issue

I receive console errors with this configuration file. In my schedules.yml, I have configured an event that announces a message via bossbar message as such.

  --------------------------------------------------------------------------------------------------

Event1:
  Enabled: false
  PerformOn:
    '1':
      Hour: 21
      Minute: 15
  Commands:
  - asConsole! cmi bossbarmsg all &6&lEvent: &fReceive &a&lx1 Unique Slot Increaser (CE) &fevery hour!
      (CE)!
  - asConsole! lp group novice permission settemp cmi.prewards.event1 true 2h global
Event2:
  Enabled: false
  PerformOn:
    '1':
      Hour: 15
      Minute: 0
  Commands:
  - asConsole! cmi bossbarmsg all &6&lEvent: for 2 hours to receive &a&lx1 BlockTrak
      (CE)!
  - asConsole! lp group novice permission settemp cmi.prewards.event2 true 3h global
  
  --------------------------------------------------------------------------------------------------
  
  I've checked by pasting that command output 
 
  - asConsole! cmi bossbarmsg all &6&lEvent: &fReceive &a&lx1 Unique Slot Increaser (CE) &fevery hour!` in-game and it works fine. I've checked on yaml parser and it says this.
  
  `ERROR:

while scanning an anchor
  in "<unicode string>", line 47, column 56:
     ... barmsg all &6&lEvent: &fReceive &a&lx1 Unique Slot Increaser (CE ... 
                                         ^
expected alphabetic or numeric character, but found '&'
  in "<unicode string>", line 47, column 58:
     ... rmsg all &6&lEvent: &fReceive &a&lx1 Unique Slot Increaser (CE)  ... 
                                         ^`
  
  But when I checked console, it output this error. https://pastebin.com/ininpnZG
  
  Not sure what went wrong, though Schedule 2 (Event2) has no issues nor error although its similar in format. Could someone take a look?
  
  

### Version Information

```shell
CMI: 9.2.0.3 BungeeCord CMIB  SqLite-> 9.2.0.4
CMILib: 1.2.0.2 -> 1.2.0.3
Server: Paper(287) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
Modules -> 56 enabled 0 disabled:
```

### Errors

```shell
https://pastebin.com/ininpnZG
```

### Relevant Config Sections

```yaml
Event1:
  Enabled: false
  PerformOn:
    '1':
      Hour: 21
      Minute: 15
  Commands:
  - asConsole! cmi bossbarmsg all &6&lEvent: &fReceive &a&lx1 Unique Slot Increaser (CE) &fevery hour!
      (CE)!
  - asConsole! lp group novice permission settemp cmi.prewards.event1 true 2h global
Event2:
  Enabled: false
  PerformOn:
    '1':
      Hour: 15
      Minute: 0
  Commands:
  - asConsole! cmi bossbarmsg all &6&lEvent: for 2 hours to receive &a&lx1 BlockTrak
      (CE)!
  - asConsole! lp group novice permission settemp cmi.prewards.event2 true 3h global
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
