### ISSUE TITLE
After updating CMI /warp GUI is only displaying 1 item to players with cmi.command.warp.showlist

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#7035]
### Description of Issue

I updated CMI today, and my warps all exist still, but players with `cmi.command.warp.showlist` are only showed 1 warp GUI item.
I disabled the GUI in config and all the warps they have access too are listed in chat perfectly fine, this is related to adding custom borders around /warp GUI as I had warps that filled up the whole GUI before this border was added.

The update that caused it to break.
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=452808

Before the update this is how my /warp gui looked.

![2022-07-03_10 01 47](https://user-images.githubusercontent.com/144046/177052862-42863ff2-ed80-4efc-8bcc-0e2026a9092e.png)

After the update this is how the GUI looks as OP
![2022-07-03_18 09 45](https://user-images.githubusercontent.com/144046/177052867-f492cd52-2a60-4611-a04d-cbeeed464d75.png)

The issue is now that as a player with `cmi.command.warp.showlist` and the correct permissions to all these warps (they are all public in that screenshots) they only see this;

![2022-07-03_18 52 13](https://user-images.githubusercontent.com/144046/177052896-cc162e79-bf53-47e5-9d2b-e3eac47f34da.png)

But if I disable the GUI for displaying warps, you can see as a player the warps are being listed fine:
![2022-07-03_19 28 10](https://user-images.githubusercontent.com/144046/177052905-2979847e-1d64-4ff6-8b2d-0fdbca5ca525.png)

This only happened after the border was introduced to the warp gui.

They can still use the /warp <warpname> they just are not visually shown in the GUI.

its odd as all the warps are shown fine for OP.

I have sent you a copy of my warps.yml so you can test yourself.

**Other outstanding bugs I found with /warp while I was testing:**

1. You can not edit warps.yml and then do /cmi reload, all changes to warps are lost that were made in-game and no changes are pulled from the updated warps.yml.
2. /warp does not tab complete for normal players, but it does to OP, is this something to do with conflicting to essentials? my players do not have the essentials warp command, but OP does?
4. Even tho I have 89 warps, /warp is only displaying 3 pages for a total of 84 warps when im OP, a 4th page was not created, this could be because in my languages file:
```
      pageTitles:
      - '&9&lTravel PirateCraft'
      - '&9&lStaff Warps'
      - '&9&lSpecial PirateCraft'
```
I tried adding more pages and doing /cmi reload but no change.

### Version Information

```shell
[19:43:46] [Render thread/INFO]: [CHAT] --------------------------------------------------
[19:43:46] [Render thread/INFO]: [CHAT] CMI: 9.2.1.1 BungeeCord CMIB  MySQL
[19:43:46] [Render thread/INFO]: [CHAT] CMILib: 1.2.1.0 
[19:43:46] [Render thread/INFO]: [CHAT] Server: Purpur 1.18.2-R0.1-SNAPSHOT
[19:43:46] [Render thread/INFO]: [CHAT] CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[19:43:46] [Render thread/INFO]: [CHAT] Modules -> 31 enabled 25 disabled: spawnerProximity, customMessages, mirror, tablist, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, coloredArmor, votifier, shulkerBackpack, attachedCommands, spawnerCharge, namePlates, homeInteractions, hpBossBar, afk, anvilRenameColor, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, disabledEnchants, worldLimits
[19:43:46] [Render thread/INFO]: [CHAT] --------------------------------------------------
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Config.yml

Warps:
  # When set to true, warps list will be shown in GUI instead of chat list
  GUI: true
  # Automatically opens GUI when created new warp point
  GUIOnCreation: true
  # Minimal length of warp name
  MinLength: 4
  # Maximal length of warp name
  MaxLength: 16
  # How many warps to show in each page
  perPage: 50
  # Do you want to show creator in warp list
  showCreator: false
  # When set to true, new warps by default will require permission node to use them
  requirePerm: true
  Complex:
    CloseButton:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - closeinv!
    InfoButton:
      # Extra button to be used in case you want to provide any aditional information when clicking on it
      Use: false
      Slot: 1
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ==
      Commands:
      - closeinv!
```

Local_EN.yml
```
  warp:
    help:
      info: '&eTeleports to warp location'
      args: (warpName) (playerName) (-s) (-g:[groupName]) (-p:[pageNumber])
    info:
      list: '&eWarps: &6'
      click: '&eClick to teleport to &6[warp]'
      teleported: '&8[&6Warp&8] &eYou travelled to: &6[warp]&e, bon voyage.'
      noWarps: '&cThere is no saved warps'
      autoLoreName: '&7[warpName]'
      autoLoreFormat:
      - '&7[worldName]'
      - '&e[x]:[y]:[z]'
      - '[creator]'
      creator: '&eCreator: &6[creator]'
      noWarpByName: '&8[&6Warp&8] &cArr thar be no warp by this name! Check &9/warps'
      noAccess: '&cNo access to this warp'
      guiTitle: '&6Warps'
      pageTitles:
      - '&9&lTravel PirateCraft'
      - '&9&lStaff Warps'
      - '&9&lSpecial PirateCraft'
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
