### ISSUE TITLE
Kicked with null error after getting out of AFK mode

### ISSUE THREAD

**Issue by nhanledev** [Zrips/CMI#7050]
### Description of Issue

Leave AFK mode and the player is kicked with null exception. Only happens on Minecraft Client 1.19

![image](https://user-images.githubusercontent.com/28459250/178089343-168d3cdc-2c07-4499-99f7-ad94b8eddad6.png)

### Version Information

```shell
[10:08:27 INFO]: --------------------------------------------------
[10:08:27 INFO]: CMI: 9.2.1.1 BungeeCord CMIB  MySQL
[10:08:27 INFO]: CMILib: 1.2.1.0 -> 1.2.1.1
[10:08:27 INFO]: Server: Paper(387) 1.18.2-R0.1-SNAPSHOT
[10:08:27 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[10:08:27 INFO]: Modules -> 14 enabled 42 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, moneyCheque, skin, noTarget, elytraBoost, cmiPlaytime, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, votifier, shulkerBackpack, headDrop, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, armorstand, anvilRenameColor, jail, spawners, paintingEditor, dynamicSigns, durabilityLoss, kits, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks, firstJoinMessages, silentChest, warmup, totemBehavior
[10:08:27 INFO]: --------------------------------------------------

Waterfall #497
Paper 1.18.2 #387
Minecraft Client 1.19
```

### Relevant Config Sections

```yaml
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: false
  # When enabled shows random subtitle message
  SubTitleMessage: false
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: true
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 30
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: false
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 120
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - msg! [playerName] You are now afk
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - msg! [playerName] You are now afk
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - msg! [playerName] You are no longer afk
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 60
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] You are AFKing for too long -s
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - test_world
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: false
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on fishing
  DisableFishing: true
  # Disables item pickup while afk
  DisableItemPickup: true
  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: true
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: true
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: true
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
