### ISSUE TITLE
Jailed symbol

### ISSUE THREAD

**Issue by Deimosssss** [Zrips/CMI#7060]
My feature request is, if could be possible to add placeholder and lines for set text format to CMILib Translation file for Jailed and unJailed players as same as vanish feature has it (%cmi_user_vanished_symbol%). I would be very pleased! Thank you.

**Comment by CloudeLecaw** [comment]
well are you able to create own placeholders? Yes you can with cmi :-)
You need PlaceholderAPI and the extansion ParseOther
If so you can work with this
`%cmi_user_jailed% – True or false if player is jailed`
so create a own jail command (custom alias)
in it add a usermeta!
here is how to do it

Here an example:
```
  jail:
    Cmds:
    - asConsole! cmi jail $1~
    - delay 1
    - check:%parseother_{$1}_{cmi_user_jailed}%==true! asConsole cmi usermeta $1 add playerjailed JAILED -s
    - check:%parseother_{$1}_{cmi_user_jailed}%==false! asConsole cmi usermeta remove playerjailed -s
    Perm: true
```
permission is: cmi.customalias.jail

now you could use the /jail Player JAIL CELL REASON -s like before and a placeholder is created after
If its in Tablist then (playername line) you can work with `%cmi_user_meta_playerjailed%`
If you need the placeholder in other plugins or textes shown to others use `%parseother_{PLAYERNAME}_{cmi_user_meta_playerjailed}%`
