### ISSUE TITLE
Kits GUI only show two pages

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7064]
### Description of Issue

Well the GUI of kits only shows two pages if you have more kits

### Version Information

```shell
[00:59:56 INFO]: --------------------------------------------------
[00:59:56 INFO]: CMI Pluginversion: 9.2.1.4 MySQL
[00:59:56 INFO]: CMILib: 1.2.1.2
[00:59:56 INFO]: Server: Paper(61) 1.19-R0.1-SNAPSHOT
[00:59:56 INFO]: CMI Economy: Aktiviert Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Aktiviert
[00:59:56 INFO]: Module -> 55 aktiviert 1 deaktiviert: votifier
[00:59:56 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
here an example kitfile


VehicleDrill1:
  CommandName: VehicleDrill1
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill2:
  CommandName: VehicleDrill2
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill3:
  CommandName: VehicleDrill3
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill4:
  CommandName: VehicleDrill4
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill5:
  CommandName: VehicleDrill5
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill6:
  CommandName: VehicleDrill6
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill7:
  CommandName: VehicleDrill7
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill8:
  CommandName: VehicleDrill8
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill9:
  CommandName: VehicleDrill9
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill11:
  CommandName: VehicleDrill11
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill12:
  CommandName: VehicleDrill12
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill13:
  CommandName: VehicleDrill13
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDril14:
  CommandName: VehicleDrill14
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill15:
  CommandName: VehicleDrill15
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill16:
  CommandName: VehicleDrill16
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill17:
  CommandName: VehicleDrill17
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill18:
  CommandName: VehicleDrill18
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill19:
  CommandName: VehicleDrill19
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill21:
  CommandName: VehicleDrill21
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill22:
  CommandName: VehicleDrill22
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill23:
  CommandName: VehicleDrill23
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill24:
  CommandName: VehicleDrill24
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill25:
  CommandName: VehicleDrill25
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill26:
  CommandName: VehicleDrill26
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill27:
  CommandName: VehicleDrill27
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill28:
  CommandName: VehicleDrill28
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill29:
  CommandName: VehicleDrill29
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill31:
  CommandName: VehicleDrill31
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill32:
  CommandName: VehicleDrill32
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill33:
  CommandName: VehicleDrill33
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill34:
  CommandName: VehicleDrill34
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill35:
  CommandName: VehicleDrill35
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill36:
  CommandName: VehicleDrill36
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill37:
  CommandName: VehicleDrill37
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill38:
  CommandName: VehicleDrill38
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill39:
  CommandName: VehicleDrill39
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDril41:
  CommandName: VehicleDrill41
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill42:
  CommandName: VehicleDrill42
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill43:
  CommandName: VehicleDrill43
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill44:
  CommandName: VehicleDrill44
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill45:
  CommandName: VehicleDrill45
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill46:
  CommandName: VehicleDrill46
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill47:
  CommandName: VehicleDrill47
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill48:
  CommandName: VehicleDrill48
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill49:
  CommandName: VehicleDrill49
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill51:
  CommandName: VehicleDrill51
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill52:
  CommandName: VehicleDrill52
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill53:
  CommandName: VehicleDrill53
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill54:
  CommandName: VehicleDrill54
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill55:
  CommandName: VehicleDrill55
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill56:
  CommandName: VehicleDrill56
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill57:
  CommandName: VehicleDrill57
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill58:
  CommandName: VehicleDrill58
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill59:
  CommandName: VehicleDrill59
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill61:
  CommandName: VehicleDrill61
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill62:
  CommandName: VehicleDrill62
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill63:
  CommandName: VehicleDrill63
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill64:
  CommandName: VehicleDrill64
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill65:
  CommandName: VehicleDrill65
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill66:
  CommandName: VehicleDrill66
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill67:
  CommandName: VehicleDrill67
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill68:
  CommandName: VehicleDrill68
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
VehicleDrill69:
  CommandName: VehicleDrill69
  Delay: 10
  Items:
    '14':
      v: 2975
      type: STONE
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
