### ISSUE TITLE
CMI Vault and Towny Bank Balance

### ISSUE THREAD

**Issue by ItsRainingHP** [Zrips/CMI#7081]
### Description of Issue

Towny bank balances do not store in MySQL database. Major issue for many servers. Without this feature I will have to use something other than CMI and I wasted my money on it.

### Version Information

```shell
CMI 9.2.2.0
```

### Errors

```shell
No error logs
```

### Relevant Config Sections

```yaml
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: CMI
  password: pass
  hostname: IP:3306
  database: CMI
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: true
  verifyServerCertificate: false
```

### Relevant Plugins

CMI Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
