### ISSUE TITLE
the displayname config option doesn't change the displayname for cmi commands

### ISSUE THREAD

**Issue by Ceddix** [Zrips/CMI#7083]
### Description of Issue

In all my cmi messages it shows `Prefix  Name` _(double space)_
![image](https://user-images.githubusercontent.com/49922771/180603147-edcc9087-574f-4141-b204-c6c23b593fde.png)
and I found no way to change that, because somehow the `DisplayName` `config.yml` option only changes the displaynames for other plugins but not for cmi's own commands

### Version Information

```shell
CMI: `9.2.1.4`
CMILib: `1.2.1.0`
```

### Relevant Config Sections

```yaml
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{prefix}{nickName}{suffix}'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  # If you want to allow any letter from any language use [^\p{L}0-9\-\_]
  ValidNicknameRegex: '[^\p{L}0-9\-\_]'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
