### ISSUE TITLE
Sell all feature

### ISSUE THREAD

**Issue by Downsurge** [Zrips/CMI#7097]
Feature request
Please this is pretty important, can you prevent items with lores or customs names to be sold in /sell all? I keep having issues with players selling special items.

Either that or a way to give an item data. Like dirt_block:3 and only allow dirt_block to be sold

**Comment by CloudeLecaw** [comment]
have u tired these settings in config?
```

Worth:
  # Defines lore that will prevent an item from being sold using /cmi sell.
  # Color codes and capitalization are being ignored
  BadLore:
  - Event
  # If enabled any item with custom name will not be allowed to be sold with /cmi sell command
  CustomNameBlocking: true
  # If enabled any item with custom lore will not be allowed to be sold with /cmi sell command
  LoreBlocking: true
```
