### ISSUE TITLE
Kits recovery not working

### ISSUE THREAD

**Issue by Proemmis** [Zrips/CMI#7099]
### Description of Issue

Hello, I have a problem with the recovery of the kits that I did, I recover a kit, but it activates the cooldown on all my kits, while I have not even claimed it, which is problematic, because I have several kits available, but I can only claim one, because once claimed, the cooldown is also activated on all the other kits, while I did not claim it, I send you to a recording I made to better understand the problem :

https://drive.google.com/file/d/1L9BqAAsOrWs_hQqsVJO-YjyrPY_6R4jb/view?usp=sharing
https://drive.google.com/file/d/1eIE47i2M85U83e67DMeKPbyoBI_ZUSHx/view?usp=sharing

Thanks in advance

### Version Information

```shell
CMI - 9.2.3.0
CMILib - 1.2.3.1
```

### Relevant Config Sections

```yaml
# Player should have appropriate permission node to use particular kit: cmi.kit.[kitName]
# cmi.kit.newbie will allow to use newbie kit
# Possible custom variables: {USERNAME} {DISPLAYNAME} {WORLDNAME} {KITNAME} {RANDOMPLAYER}
# Edit kits ingame with /cmi kiteditor to avoid formating issues
# Commands support specialized command format
Newbie:
  CommandName: Newbie
  Delay: 36000
  Commands:
  - asConsole! msg! [playerName] &eTu viens de réclamer ton kit &6{KITNAME}!
  Group: groupName
  Items:
    '1':
      type: STONE
      amount: 64
Dresseur:
  CommandName: Dresseur
  Delay: 3600
  Commands:
  - asConsole! msg! [playerName] &eTu viens de réclamer ton kit &6{KITNAME}!
  Group: groupName
  Items:
    '1':
      type: PIXELMON_POKE_BALL
      amount: 12
    '2':
      type: PIXELMON_RARE_CANDY
      amount: 2
    '3':
      type: PIXELMON_HOURGLASS_GOLD
      amount: 2
    '4':
      type: PIXELMON_ALUMINIUM_PLATE
      amount: 8
Food:
  CommandName: Food
  Delay: 1800
  Commands:
  - asConsole! msg! [playerName] &eTu viens de réclamer ton kit &6{KITNAME}!
  Group: groupName
  Items:
    '1':
      type: COOKED_BEEF
      amount: 64
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
