### ISSUE TITLE
Some translation doesn't apply

### ISSUE THREAD

**Issue by RispyCZ** [Zrips/CMI#7107]
### Description of Issue

Hello,
I found out that two translations doesn't apply properly. One is from CMILib and it's a NoPermission and other one is [autoTimeLeft] which add world "sec" at the end.

### Version Information

```shell
CMI plugin version: 9.2.3.0 SqLite
CMILib: 1.2.3.1 
Server: Paper(81) 1.19-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 55 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
CMILib (Translation)
NoPermission: '&cNa toto nemáš práva'

CMI (Translation)
Boss:
   DontMove: '&cNehýbej se po dobu &e[autoTimeLeft] &cvteřin!'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
