### ISSUE TITLE
[item] working for latest version players, but broken in older version players.

### ISSUE THREAD

**Issue by ShockCharge** [Zrips/CMI#7109]
### Description of Issue

![image](https://user-images.githubusercontent.com/48907444/182044239-55014194-2a41-400b-989e-e817ade6dfd3.png)

My server is at 1.17.1, has full compatibility with 1.8.9 since all 1.9-1.19+ items, blocks, events, interaction, entities, and etc. are disabled. 

![image](https://user-images.githubusercontent.com/48907444/182044162-8dd7e5c7-5397-4c54-aaf4-e0bff70f9fc4.png)
![image](https://user-images.githubusercontent.com/48907444/182044225-d2d728ba-07d3-4607-82ac-1f1d769213eb.png)

### Version Information

```shell
CMI: 9.2.3.0 SqLite
CMILib: 1.2.3.1 
Server: Purpur 1.17.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
Modules -> 34 enabled 22 disabled: spawnerProximity, cuffed, hpBossBar, mirror, tablist, moneyCheque, skin, holograms, noTarget, jail, spawners, paintingEditor, bossBarCompass, flightCharge, ranks, playerCombat, votifier, shulkerBackpack, headDrop, spawnerCharge, vanish, homeInteractions
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Defines name of global chat channel in discordsrv
    GlobalChannel: global
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'
    UnlinkedLabel: '&4[&cD&4]'
  # Enables support for DynMap web chat
  DynMapChat: false
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: false
  # If ReplyToLastMessenger is set to false, then timeOut will be taken into consideration to who you should reply
  # If you had conversation in last 120 seconds (default) then even receiving message from 3rd person, you will still reply to original player
  # If you had conversation in longer then 120 seconds period, then you will reply to latest person who send you a message
  LastMessengerTimeOut: 120
  # When set to true players will need to have cmi.command.msg.[groupname].send where [groupName] is receivers main permission group
  PrivateMessagesGroups: false
  # When set to false, web pge links in a chat will not get shortened to default [LINK] format
  TranslateLink: true
  # Defines regex when replacing url in chat with short word
  # Examples:
  # (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  LinkRegex: ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s|^\)]+)
  # When set to true, particular variables in chat will be translated into items player are holding. List of variables belove
  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
  - (\[i\])
```

### Relevant Plugins

Vault 1.7.3-b131 , ProtocolLib 5.0.0-SNAPSHOT-b585

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
