### ISSUE TITLE
CommandsOnTag is executed multiple times on 1.19.2

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#7157]
### Description of Issue

Player A mentions player B, the command in CommandsOnTag will be executed multiple times, and it will take a few seconds to see player A send a message containing @.
![tag](https://user-images.githubusercontent.com/46647646/184532184-43653802-b12d-4027-8acb-b3f922b602a9.png)

### Version Information

```shell
[17:58:01 INFO]: --------------------------------------------------
[17:58:01 INFO]: CMI plugin version: 9.2.3.4 BungeeCord  SqLite
[17:58:01 INFO]: CMILib: 1.2.3.3
[17:58:01 INFO]: Server: Paper(125) 1.19.2-R0.1-SNAPSHOT
[17:58:01 INFO]: CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: enabled 
[17:58:01 INFO]: Modules -> 52 enabled 4 disabled: tablist, playerCombat, votifier, headDrop
[17:58:01 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&a'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound BLOCK_NOTE_BLOCK_HARP:10:1 [playerName] -s
    - asConsole! title [playerName] title ["",{"text":"嘿,","color":"gold"},{"text":"有人@你","color":"green"}]
    - asConsole! title [playerName] subtitle ["",{"text":"[senderName]","color":"gold"},{"text":"
      提到了你","color":"white"}]
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
