### ISSUE TITLE
Fly won't disabled in PVE if mob can't damage player

### ISSUE THREAD

**Issue by Igzak** [Zrips/CMI#7160]
### Description of Issue

Players fly above mobs and shoot them using a bow, so I have a suggestion:
 - option to disable fly if player damage mob
 - option to disable fly if mob damage player
 
It can look like `IncludeVictim: true` option but for PVE also

### Version Information

```shell
[13:47:08 INFO]: --------------------------------------------------
[13:47:08 INFO]: Версия плагина CMI: 9.2.3.4 BungeeCord CMIB  SqLite
[13:47:08 INFO]: CMILib: 1.2.3.3 
[13:47:08 INFO]: Версия сервера: Purpur 1.19.2-R0.1-SNAPSHOT
[13:47:08 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMICMI Чат: Включено 
[13:47:08 INFO]: Модули -> 56 включено 0 отключено: 
[13:47:08 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Combat:
  # Defines combat timer to be used in particular features
  Timer: 30
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: false
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: true
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: false
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: false
    AllowedCommands:
    - msg
    - r
    - tell
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: false
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pve.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage mobs while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: false
    AllowedCommands:
    - msg
    - r
    - tell
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
