### ISSUE TITLE
Tabcomplete in customalias doesn't work

### ISSUE THREAD

**Issue by Mappors** [Zrips/CMI#7173]
### Description of Issue

The TabComplete feature of customalias doesn't seem to work.

I've enabled it in the ingame aliaseditor. I've also tried adding CustomTabs. But it keeps having no tabcompletion.

### Version Information

```shell
--------------------------------------------------
CMI: 9.2.0.3 BungeeCord SqLite-> 9.2.3.5
CMILib: 1.2.2.0 -> 1.2.3.3
Server: Paper(379) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 46 enabled 10 disabled: deathMessages, customMessages, tablist, ranks, playerCombat, votifier, skin, spawners, silentChest, vanish
--------------------------------------------------
```
```


### Errors

```shell
None
```

### Relevant Config Sections

```yaml
tnt-run join:
    Cmds:
    - asConsole! trconsole join TNT-run [playerName]
    CustomTabs:
    - tnt-run join
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
