### ISSUE TITLE
The CMI GUI will move the cursor to the center of the window.

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#7175]
### Description of Issue

I integrated the CMI GUI into Deluxemenus, but the cursor moves to the center of the window after jumping to the CMI GUI.

This doesn't happen when I use Deluxemenus to jump to the GUI of other plugins, so I believe the CMI GUI can do better?

### Version Information

```shell
[16:39:26 INFO]: --------------------------------------------------
[16:39:26 INFO]: CMI plugin version: 9.2.3.5 BungeeCord  SqLite->
[16:39:26 INFO]: CMILib: 1.2.3.3
[16:39:26 INFO]: Server: Paper(132) 1.19.2-R0.1-SNAPSHOT
[16:39:26 INFO]: CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: enabled
[16:39:26 INFO]: Modules -> 52 enabled 4 disabled: tablist, playerCombat, votifier, headDrop
[16:39:26 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Deluxemenus:
  'kits':
    material: "CHEST_MINECArT"
    slot: 23
    display_name: "&aKits"
    left_click_commands:
      - "[player] cmi kit"

CMI:
Kits:
  # When set to true, kit list will be shown in GUI instead of chat list
  GUI: true
  # When set to true, kit selection gui empty fields will get filled with definet item
  FillEmptyFields: true
  Buttons:
    Cooldown: Watch
    Usages: STONE_PLATE
    Money: GOLD_INGOT
    Exp: EXP_BOTTLE
    Desc: WOOL:13
    Back: Fence
  Complex:
    CloseButton:
      Use: true
      Slot: 9
      Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
      Commands:
      - asConsole! dm open main [playername]
```

### Relevant Plugins

DeluxeMenus 1.13.6

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
