### ISSUE TITLE
MYSQL ERROR

### ISSUE THREAD

**Issue by uploadx10** [Zrips/CMI#7183]
### Description of Issue

When player Disconnect

### Version Information

```shell
cmi 9.2.3.6
cmilib 1.2.3.3
paper 1.18.1
```

### Errors

```shell
https://pastebin.com/zqAT29aJ
```

### Relevant Config Sections

```yaml
mysql enable
ForceSaveOnLogOut: true
ForceLoadOnLogIn: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
