### ISSUE TITLE
add RTP redirection

### ISSUE THREAD

**Issue by moderator10000078** [Zrips/CMI#7198]
I would like to see the configuration of RTP redirection, for example, so that if I used /rtp in the **spawn**. i teleport in **world**, I know what can be done with custom commands, but it will obviously be more convenient to configure it in the config

**Comment by Zrips** [comment]
You will need to be more specific here with what you actually want. What exactly is this redirection? When should it apply? What it should do differently?

**Comment by mrfloris** [comment]
> You will need to be more specific here with what you actually want. What exactly is this redirection? When should it apply? What it should do differently?

I think in for example betterRTP you can define what a world does. So if you type /rtp inside the a world that's set up as a redirect, it actually does /rtp for the other world it's set to.

betterRTP for example has this in the config.yml
```yaml
Overrides:
- spawn: wild
- lobby: minigameslobby
```

**Comment by CloudeLecaw** [comment]
this is what you can define in config.
```
RandomTeleportation:
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will not longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: true
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world_the_end:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 blocks between defined center location
      # For example having centerX at 2000 and centerZ at 3000 while MaxRange is set to 1500 we will teleport player between x:500;z:1500 and x:3500;z:4500 coordinates
      MaxRange: 4500
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 500
      CenterX: -147
      CenterZ: 32
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      ignorePowderSnow: false
      minY: 0
      maxY: 256
    world:
      Enabled: true
      MaxRange: 4500
      MinRange: 300
      CenterX: 33
      CenterZ: 337
      Circle: true
      IgnoreWater: true
      IgnoreLava: true
      ignorePowderSnow: false
      minY: -64
      maxY: 320
```
