### ISSUE TITLE
CommandPannel Integration 

### ISSUE THREAD

**Issue by Nokrato** [Zrips/CMI#7232]
### Description of Issue

warm-up will be skipped if the command is run from the plugin "command panel"
Command 
`- cmi warp MysteryVault`
warmup will take into consideration only if the command pannel runs the command with this string 
` - console= sudo %player_name% c:/cmi warp WarpName`

### Version Information

```shell
--------------------------------------------------
 CMI: 9.2.4.1 BungeeCord CMIB  SqLite
 CMILib: 1.2.3.6 
 Server: Paper(139) 1.19.2-R0.1-SNAPSHOT
 CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
 Modules -> 55 enabled 2 disabled: hpBossBar, votifier
--------------------------------------------------


Server Version
This server is running Paper version git-Paper-139 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 36a5f15)
You are 14 version(s) behind
```

### Relevant Plugins

Vault version 1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Warmup is only for players, if its being done from console then its bypassing this automatically. Its not a bug.

**Comment by Nokrato** [comment]
like a mention about by running the command 
`- cmi warp MysteryVault` CommandPannel will run the command player side, even tho will bypass warmup.
But by using a console and a use command the warmup will take into consideration 

this is a pice ofo the config WORKING 

```
      '20':
        material: potion
        stack: 1
        name: 'Test'
        commands:
        - console= sudo %player_name% c:/cmi warp Tavern
```

this on the other side is run by a player .... even tho, will not work properly 


```
      '20':
        material: potion
        stack: 1
        name: 'Test'
        commands:
        - cmi warp Tavern
```
