### ISSUE TITLE
homes being deleted when playtime reward is given

### ISSUE THREAD

**Issue by shovelbug** [Zrips/CMI#7235]
### Description of Issue

asConsole! lp user [playerName] parent set member
so once a player hits 12 hours of in game playtime they rank up from default to member with luck perm
but when they rank up it deletes their homes that are saved.....it only does this when they change usergroups....and only when it comes from the playtime rewards executing, if i just run /lp user [playerName] parent set member it promotes the user but the homes do not delete
i also notice that the promote sometimes happens a second time like it will have promoted (using example name emmbo2 at 12 hours gametime but then it will promote emmbo2 again at 3 days playtime

### Version Information

```shell
9.2.4.2
```

### Errors

```shell
no errors showing up in log
```

### Relevant Config Sections

```yaml
I setup playtime rewards as such
12hour:
DisplayName: "&f12 hour reward"
AutoClaim: true
Description:
PayFor: 43200
Commands:
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
