### ISSUE TITLE
Warm Up even for /Spawn [CommandPanel INTEGRATION]

### ISSUE THREAD

**Issue by Nokrato** [Zrips/CMI#7263]
Mention below command that we run in command panel ...via players

(Not Working .... is bypassing the warmup )
```
      '20':
        material: bed
        name: 'Test'
        commands:
        - cmi warp Tavern
```

this on the other side is run by a console .... and will work properly even with the worm up
```
      '20':
        material: bed
        name: 'Test'
        commands:
        - console= sudo %player_name% c:/cmi warp Tavern
```

now even dipper if I try to switch that with /spawn... in this case will not work periodically 

my request then is can you please add integration with this plugin, please will be much appreciated
(be able to run command via player in the menu and having the warmup, since gain at the moment the warmup is bypass by default not sure why)

Thanks in advance
