### ISSUE TITLE
Sleep speedup not work in 1.18.2 cmi 9.2.4.3

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#7266]
### Description of Issue

Sleep speedup not speed up time (only do the animation and kick player out of the bed) if it only 1 player on server (works if more an 1 player). Works in 9.2.3.8 I tested now (on 1.18.2 server), has not try newer version.

### Version Information

```shell
29.09 20:49:23 [Server] INFO CMI: 9.2.4.3 MySQL
29.09 20:49:23 [Server] INFO CMILib: 1.2.3.6 
29.09 20:49:23 [Server] INFO Server: Paper(388) 1.18.2-R0.1-SNAPSHOT
29.09 20:49:23 [Server] INFO CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
29.09 20:49:23 [Server] INFO Modules -> 52 enabled 5 disabled: customMessages, worldLimits, jail, dynamicSigns, kits
```

### Relevant Config Sections

```yaml
Sleeping:
  Speedup:
    # When set to true, players can speedup night by sleeping in bed
    # This will allow to speed up night in percentage depending how many players are sleeping in beds in that world
    Enabled: true
    # List of worlds where this should be applied.
    # Keep in mind that time speed up only works on a normal type world and by default you will have only one
    # Set this list to [] if you want to include all possible worlds
    Worlds: []
    # When this set to true time will be speed up only between 13000 and 24000 ticks of the day
    # When having this set to false players can speed up day durring storms or other events
    OnlyDurringNight: true
    # Type of speedup information, can be: none, title, bossbar
    InfoType: title
    # When set to true, players who are in afk mode will be excluded from speed calculations
    ExcludeAfk: true
    # Defines speed to go throw night, bigger numbers will make it go faster and less players you will need to go throw night
    # 100 will result in 100 times faster time
    BaseSpeed: 100
    # Defines minimal speed to go throw night, this is in case there are more players than base speed and calculation return default speed
    MinSpeed: 5
    # Minimal amount of players sleeping in beds before speeding it up
    # Can be defined in 2 formats. When using clean number like 3, then 3 players will have to be sleeping before speedup kicks in
    # If amount is defined with % like 50% then half of server population will have to be sleeping before speedup kicks in
    MinBeforeSpeeding: 0%
    # When set to true online players will be informed about missing sleeping people count
    Inform: true
    # Time in seconds between information messages can be shown when player starts or stops sleeping
    InformDelay: 30
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
