### ISSUE TITLE
CMI Bungee - Message for Server Switch not working

### ISSUE THREAD

**Issue by thboehi** [Zrips/CMI#7268]
### Description of Issue

When a player change server, for example switch from `survie `to `creatif`, it doesn't show the message (on both server)
```yaml
ServerSwitchOut: ' &6[playerDisplayName] &eswitched server to &6[serverName]'
ServerSwitchIn: ' &6[playerDisplayName] &ecame from &6[serverName] &eserver'
```

We're using Waterfall (bungeecord fork, made by PaperMC team)
https://papermc.io/downloads#Waterfall

### Version Information

```shell
survival server:
CMI: 9.2.4.3 BungeeCord CMIB  SqLite
CMILib: 1.2.3.6 
Server: Paper(188) 1.19.2-R0.1-SNAPSHOT

creative server:
CMI: 9.2.4.3 BungeeCord CMIB  SqLite
CMILib: 1.2.3.6 
Server: Paper(188) 1.19.2-R0.1-SNAPSHOT

Proxy (waterfall):
CMIB1.0.2.1.jar
```

### Errors

```shell
No error shown (console or chat)
```

### Relevant Config Sections

```yaml
Same on both servers:


Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: true
      # When enabled and you have bungeeserver with CMIB on it we will try to detect where player went and we will show switch server message instead of login if possible
      ServerSwitch: true
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: true
      # When enabled and you have bungeeserver with CMIB on it we will try to detect where player went and we will show switch server message instead of logout if possible
      ServerSwitch: true
  # Check locale file for translation and custom placeholders: [playername], [totalUsers], [onlinePlayers]
  FirstJoinMessage:
    Use: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
