### ISSUE TITLE
Shift+Rightclicking shulker boxes doesn't work from player inventory menu

### ISSUE THREAD

**Issue by GiraffeCubed** [Zrips/CMI#7279]
### Description of Issue

Shulker boxes should work as backpacks by holding them in your hand, OR hovering over them in your inventory and then pressing SHIFT + RIGHTCLICK. This functionality seems to have partially broken in the latest update however (9.2.4.1). Shulker boxes can still be opened in this way when holding them in your hand, but _not_ whilst hovering them in your inventory. In this case, the shulkers currently just move between your hotbar and inventory slots, whereas before they would open the shulker box contents.

### Version Information

https://i.imgur.com/HtAWCHI.png

### Errors

No errors.

### Relevant Config Sections

```yaml
config.yml:
  ShulkerBoxes:
    PreventInCombat: false

Modules.yml:
    shulkerBackpack: true

(Was going to link permissions, but this is a server-wide issue, even for OPs)
```

### Relevant Plugins

CMI 9,2,4,1 | CMILib 1.2.3.6 | Vault 1.7.3-CMI | WorldGuard 7.0.8 | (Full plugins: https://i.imgur.com/PMstn0K.png)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
