### ISSUE TITLE
The compass function is abnormal

### ISSUE THREAD

**Issue by CN-Dragon** [Zrips/CMI#7280]
### Description of Issue

I want to display CompassTarget, but I don't want to display Spawn. Therefore, when I set ShowSpawn to false and ShowCompassTarget to true, CompassTarget will not be displayed in Compass because it is affected by ShowSpawn.

### Version Information

```shell
[18:40:27] [Server thread/INFO]: --------------------------------------------------
[18:40:27] [Server thread/INFO]: CMI: 9.0.1.2 SqLite-> 
[18:40:27] [Server thread/INFO]: CMILib: 1.2.3.4 -> 1.2.3.6
[18:40:27] [Server thread/INFO]: Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT
[18:40:27] [Server thread/INFO]: CMI economy: Disabled CMI Chat: Disabled 
[18:40:27] [Server thread/INFO]: Modules -> 55 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
Compass:
  # Enable EXPERIMENTAL boss bar compass
  # Only for 1.9+ servers
  BossBar: true
  # When set to true then by default player will see bossbar compass, to hide it they will need to use /togglecompass
  # When set to false bossbar compass will not show up until player uses /togglecompass
  DefaultState: true
  # Requires to hold compass in had to see it
  RequireCompass: false
  # Compass update interval in milliseconds
  UpdateInterval: 200
  # Keep same spacing between each direction. Length can be any you want
  Shape: '------------SW-------------W-------------NW-------------N-------------NE-------------E-------------SE-------------S-'
  Color: '&7'
  ShowHome: true
  Home: ۩
  ShowSpawn: false
  Spawn: ⤋
  ShowDeath: true
  Death: ☠
  ShowCompassTarget: true
  CompassTarget: ꖴ

```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
