### ISSUE TITLE
CMI Severe Save Error + /cmi armorstand 

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#73]
Hey,

So I woke up this morning again to CMI spamming my console with "CMI SEVERE SAVE ERROR" - I am running CMI 7.3.17.0 on Spigot 1.8.8. The problem seemed to stop after doing /cmi reload in the console, but am not sure as I restarted the server.

/cmi armorstand was fixed, but now it is broken again where as if I type /cmi armorstand when looking at an armor stand it always says "Look at entity" - but at least shift + right clicking them still works :)

![cmierror](https://user-images.githubusercontent.com/34957646/36948007-04d5caf0-1fa2-11e8-8eae-e8c52dd05077.png)

**Comment by LogGits** [comment]
Heya if possible could you go into the log folder and provide us a log to see what the NullPointerException error is caused by?

**Comment by Ew9304** [comment]
I will wait for it to happen again, I must have deleted my logs -_-.. It might take a few days for it to happen again, if it ever does (random) .

**Comment by Zrips** [comment]
Test out with new update and provide full error log as it should now print out more information for simpler debugging

**Comment by stashenko** [comment]
I have the same problem. If specify a method: sqlite, everything works fine.
The MySQL database is on the same hosting as the server
Errors disappear after the plugin is rebooted, but before the next player enters.

Spigot-c3093ef-7e94e65 (MC: 1.12.2)
CMI v7.4.2.0
CMIEInjector v1.0.1.2
logs: https://drive.google.com/file/d/1giaPfgIxLaWatcsa5q0BTdHesCOahjKW/view?usp=sharing

**Comment by stashenko** [comment]
Thanks for the update 7.4.2.1. There are no errors. But now the players have two UUIDs
https://hastebin.com/uqimixiniy.vbs

**Comment by Zrips** [comment]
Double uuid issue could happen if you switched server from offline to online mode or vise versa

**Comment by stashenko** [comment]
Thank you

**Comment by stashenko** [comment]
Not immediately noticed the error. As soon as the players began to join, errors began.
https://hastebin.com/cowavuqujo.md

Spigot- 1.12.2
CMI v7.4.2.1
CMIEInjector v1.0.1.2
mysql  Ver 14.14 Distrib 5.6.35, for Linux (x86_64)

**Comment by MCTyler** [comment]
@Zrips Could this possibly be related to the Version of MySql? My Version is Server version: 5.7.21-0ubuntu0.16.04.1 (Ubuntu) and I do not receive this error. The Config file is as follows.
```
storage:
  # storage method, can be MySQL or sqlite
  method: MySQL
mysql:
  # Requires Mysql.
  username: root
  password: secret
  hostname: localhost:3306
  database: cmi
  tablePrefix: CMI_
  # If you have no clue what these values does, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds. As there can be to much data waiting to be saved into database if interval is too big and can cause some short freezes
AutoSaveInterval: 3
```
