### ISSUE TITLE
CMI doesn't block hex and gradient usage in public chat by default

### ISSUE THREAD

**Issue by t347549** [Zrips/CMI#7300]
### Description of Issue

CMI is not preventing players (non-op) with no permission from using hex codes and gradients, for example with {#FFFF00}. 

Steps I have taken:
1. CMI and CMILib version is up-to-date
2. CMIChat is on
3. Checked permissions for the player
4. /cmi colorlimits shows all show that the player has no permissions for any formatting whatsoever
5. LP Verbose show that the node "CMI.colors.publicmessage.(color code) is being checked; says its undefined, meaning it's not set for the player
6. I specifically denied the node CMI.colors.* for the player, which didn't solve the issue
7. I then denied all permissions for the player by denying *, and it still doesn't work, so it can't be another plugin affecting it

Is this somehow intended, or perhaps a bug? Maybe I'm missing something?

### Version Information

```shell
CMI: 9.2.4.5 SqLite
CMILib: 1.2.3.6
Server: Paper(175) 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 55 enabled 2 disabled: tablist, votifier
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      books: true
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
