### ISSUE TITLE
[ CMI ]  Problem with /skin command.

### ISSUE THREAD

**Issue by ghost** [Zrips/CMI#7301]
### Description of Issue

When a player playing from version 1.12.2 (on server version 1.19.2) changes the skin with the /skin command - it gets stuck in an empty chunk... ( https://imgur.com/a/kSuhGlp )

### Version Information

```shell
Output of /cmi version - https://imgur.com/a/kLUNySh

server version - Purpur 1.19.2-R0.1-SPANSHOT b1819
```

### Errors

```shell
This issue does not cause errors in the console.
```

### Relevant Config Sections

```yaml
Modules.yml
 skin: true

config.yml
 Skins:
  AutoApply: false
  SteveOnOff: true
  RequireSpecificPerm: false
  SkinUpdateTimer: 1320
  SkinRequestFrequency: 10
```

### Relevant Plugins

[ ProtocolLib  5.0.0-SNAPSHOT-b600 ], [ CMILib 1.2.3.6 ], [ Vault 1.7.3-CMI ]

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
