### ISSUE TITLE
%cmi_equation_{parseother_{$1}_{XXX}}*2%

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7305]
### Description of Issue

Hi, I'm trying to let this placeholder work, but it doesn't. I think it's probably due to the {} that appears there. Do you think you can try to fix it? I'm using especially this:
%cmi_equation_{parseother_{$1}_{lifesteal_hearts}}*2%

May it can be escapped or something? I'm trying to use it in the customalias, this is the cmd:
```
  heartsBack:
    Cmds:
    - msg YourName %cmi_equation_{parseother_{$1}_{lifesteal_hearts}}*2%
    - asConsole! cmi maxhp set $1 %math_{shortcut_hearts}*2%
```
I've tried it also using the Math placeholderapi, but it didn't work for the same reason

### Version Information

```shell
9.2.4.5
```

### Relevant Config Sections

```yaml
heartsBack:
    Cmds:
    - msg YourName %cmi_equation_{parseother_{$1}_{lifesteal_hearts}}*2%
    - asConsole! cmi maxhp set $1 %math_{shortcut_hearts}*2%
```

### Relevant Plugins

Vault 1.7.3, PlaceholderAPI, ParseOther

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
