### ISSUE TITLE
RepairCost Bypass Not Working

### ISSUE THREAD

**Issue by Classicalad** [Zrips/CMI#7312]
### Description of Issue

When `CostsMoney: true` is enabled in the config, and a base price and worth percentage are set, there seems to be no functional permission node to grant a player the ability to override this cost. I've tried ~30+ variants of `cmi.command.repair.bypass` - all not functional. Thanks!

### Version Information

```shell
[Tue 20:21:32 INFO ] --------------------------------------------------
  [Tue 20:21:32 INFO ] CMI: 9.2.4.6 SqLite
  [Tue 20:21:32 INFO ] CMILib: 1.2.3.6 
  [Tue 20:21:32 INFO ] Server: Paper(119) 1.19.2-R0.1-SNAPSHOT
  [Tue 20:21:32 INFO ] CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
  [Tue 20:21:32 INFO ] Modules -> 50 enabled 7 disabled: spawnerProximity, worldLimitsElytra, worldLimits, moneyCheque, portals, spawners, spawnerCharge
  [Tue 20:21:32 INFO ] --------------------------------------------------
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
Repair:
    # List of custom model data id's we should not allow to be repaired with /repair command
    BlockedCustomDataID:
    - 298785423
    # When item costs money, player will be required to confirm repair action by clicking message in chat
    Confirmation: true
    # When set to true, item repair with /cmi repair will cost money depending on setup
    # Player who performs command will pay repair cost
    # If command gets performed from console, then player whose items are repaired will be paying
    CostsMoney: false
    # Base price to repair item
    # If you have enabled durability check, then this value will wary depending on items condition
    BasePrice: 100.0
    # Item repair cost will depend on how baddly item is damaged
    CheckDurability: true
    # Adds extra cost to repair depending on items cost set in /cmi setworth
    # Value should be set from 0 to 100 range
    WorthPercentage: 10.0
    # Adds extra cost to repair depending on items enchantment cost set in /cmi setenchantworth
    # Value should be set from 0 to 100 range
    # If item has more then one enchantment, then prices will be added up
    enchantWorthPercentage: 10.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
