### ISSUE TITLE
Custom Alias, /help, Bedrock, /geyser

### ISSUE THREAD

**Issue by Tazler89** [Zrips/CMI#7316]
### Description of Issue

Maybe an issue maybe something that needs to be added worked around if even possible.

setting Custom Alias, to replace /help /? to open my own gui, works perfect on java, but bedrock users connecting via geyser still get normal /help info and not the gui java gets using the Custom Alias

Have used full command and gui opens as should alias is only place not working under all conditions.

### Version Information

```shell
all upto date
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
CustomAlias:
  help:
    Cmds:
    - asConsole! cp NoobGUI [playerName]
  '?':
    Cmds:
    - asConsole! cp NoobGUI [playerName]
```

### Relevant Plugins

CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
