### ISSUE TITLE
Customalias with multiple words will fire when single word is typed

### ISSUE THREAD

**Issue by Mappors** [Zrips/CMI#7328]
### Description of Issue

When I add customalias' with multiple words in the alias, the command will get fired when players only type the first word.

For example, with the configuration:
```
  tnt-run join:
    Cmds:
    - asConsole! trconsole join TNT-run [playerName]
    CustomTabs:
    - join
```

If the player only types `/tnt-run` the command will get fired. The keyword `join` is not mandetory.

### Version Information

```shell
--------------------------------------------------
CMI: 9.2.0.3 BungeeCord SqLite-> 9.2.4.8
CMILib: 1.2.3.6 -> 1.2.3.7
Server: Paper(388) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 46 enabled 10 disabled: deathMessages, customMessages, tablist, ranks, playerCombat, votifier, skin, spawners, silentChest, vanish
--------------------------------------------------
```
```


### Errors

_No response_

### Relevant Config Sections

```yaml
tnt-run join:
    Cmds:
    - asConsole! trconsole join TNT-run [playerName]
    CustomTabs:
    - join
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by T14D3** [comment]
I recommend you read the specialized commands wiki section again, it's doing exactly what you tell it to do, using custom tabs is not how you filter second arguments for specific commands
(Hint: check:$1==join!)

**Comment by Zrips** [comment]
@Mappors 
Solution is as @T14D3 mentioned, you can use specialized commands to check for first variable. Other than this, it works correctly on my test server. Most likely cause is another alias using base command which derps out everything else.
What works correctly and might help you is by having something like this
```
  tnt-run:
    Cmds:
    - check:$1==null! asConsole! cmi feed [playerName]
    - check:$1==join! asConsole! cmi heal [playerName]
    - check:$1!=join#! check:$1!=null#! asConsole! cmi msg [playerName] !&4Wrong command!
    CustomTabs:
    - join
```
in this case you will have command being performed when not entering any variables, which will feed player. Command which will be performed when player enter "join" as sub command and error message when sub command is incorrect.
