### ISSUE TITLE
Incorrect Lang Value used for Spliter among some commands

### ISSUE THREAD

**Issue by TheGamersBrew** [Zrips/CMI#7339]
### Description of Issue

The Spliter from the CMILib used for the non GUI WarpGroups should be using the SpliterValue but it is using the default Spliter. So when pulling up warpgroups by using either /warps or /warpgroup command it isn't showing Warps as a value. (The Value should be Warps) 

### Version Information

```shell
9.2.5.1 (lib 1.2.3.7)
```

### Relevant Config Sections

```yaml
PlayerSpliter: '&e----- &6[playerDisplayName] &e-----'
  Spliter: '&e--------------------------------------------------'
  SpliterValue: '&e------------------ &6[value] &e------------------'
  singleSpliter: '&e-'
  SpliterMiddle: ' &6[value] '
  ListSpliter: ', '
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
