### ISSUE TITLE
Sit facing north

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7354]
### Description of Issue

When sitting on a stairs, the legs of the player refuse to point to north.
All other directions work fine.
When turning around, the legs flip instantly from west to east skipping north

Same as #6506

### Version Information

```shell
CMI: 9.2.5.2 BungeeCord SqLite
CMILib: 1.2.3.7
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 1 disabled: votifier
```

### Relevant Config Sections

Test done on an empty server with fresh CMI with everyting default
```yaml
Animations:
  # Enable sitting on stair block by clicking on them with empty hand or by looking and using command
  # Requires cmi.command.sit.stairs
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  CarpetsAsChairs: false
  RemoveFromChairOnDamage: true
  # Player will sit on chair only after rapid double click
  DoubleClick: false
  # Delay in milliseconds between clicks to sit on chair when double click is enabled
  DoubleClickDelay: 200
  # Range in blocks from player to look up for valid chair block
  ChairRange: 4
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
