### ISSUE TITLE
check seems to have an issue with new | check when its !=

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7356]
### Description of Issue

The Check executes the equal of == when != is used
also when a != check is used nothing happens when the check normaly is `null` (in this case when no argument was used)

![image](https://user-images.githubusercontent.com/12080017/200085704-f9922272-5159-4f3f-82ac-99e08575c7b2.png)

```
  testdura:
    Cmds:
    - check:$1==1|2|3|4! msg! [playerName] Die haltbarkeit ist %cmi_iteminhand_durability%. %player_item_in_hand_durability%
    - check:$1!=1|2|3|4! msg! [playerName] an extra line
    - check:$1!=1! check:$1!=2! check:$1!=3! check:$1!=4! msg! [playerName] an other line
    Perm: true
    Tab: true
    CustomTabs:
    - '1,2,3,4,5,6,7,8,9'
```

### Aspected behave:
when testdura 1 is used only the first msg should be triggered
when testdura 5 is used the secound and thrid msg should be triggered.
Whenn just testdura is used the secound and third msg sould be trigger because $1 is `null`

### Version Information

![image](https://user-images.githubusercontent.com/12080017/200085798-833d6c3d-a4be-422c-97f1-9668b794ae04.png)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
