### ISSUE TITLE
PlayTime Rewards not auto claiming rewards.

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#7375]
### Description of Issue

I have a few playtime rewards set to autoclaim but it doesn't auto claim for the players.
Here is how my playtime rewards config looks like.

I have given the permission cmi.prewards.1hourclaimchunk cmi.prewards.2hourclaimchunk cmi.prewards.3hourclaimchunk cmi.prewards.4hourclaimchunk to the default rank.

### Version Information

```shell
CMI: 9.2.5.3 BungeeCord  SqLite
CMILib: 1.2.3.7 
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 53 enabled 4 disabled: customMessages, tablist, firstJoinMessages, moneyCheque
```

### Errors

```shell
No errors.
```

### Relevant Config Sections

```yaml
1hourclaimchunk:
  DisplayName: "&fOne hour reward."
  AutoClaim: true
  Description:
  - "&fGet a reward for 1st hour you have been online."
  - "&a+1 Claim Chunk"
  PayFor: 3600
  Commands:
  - asConsole! vouchers give [playerName] 1 claimchunk
  - msg! [playerName] &aYou recieved 1x Claim Chunk for your 1st hour playing on the server.
2hourclaimchunk:
  DisplayName: "&fTwo hour reward."
  AutoClaim: true
  Description:
  - "&fGet a reward for 2nd hour you have been online."
  - "&a+1 Claim Chunk"
  PayFor: 7200
  Commands:
  - asConsole! vouchers give [playerName] 1 claimchunk
  - msg! [playerName] &aYou recieved 1x Claim Chunk for your 2nd hour playing on the server.
3hourclaimchunk:
  DisplayName: "&fThree hour reward"
  AutoClaim: true
  Description:
  - "&fGet a reward for 3rd hour you have been online."
  - "&a+1 Claim Chunk"
  PayFor: 10800
  Commands:
  - asConsole! vouchers give [playerName] 1 claimchunk
  - msg! [playerName] &aYou recieved 1x Claim Chunk for your 3rd hour playing on the server.
4hourclaimchunk:
  DisplayName: "&fFour hour reward"
  AutoClaim: true
  Description:
  - "&fGet a reward for 4th hour you have been online."
  - "&a+1 Claim Chunk"
  PayFor: 14400
  Commands:
  - asConsole! vouchers give [playerName] 1 claimchunk
  - msg! [playerName] &aYou recieved 1x Claim Chunk for your 4th hour playing on the server.

  
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
