### ISSUE TITLE
latest Tablist empty line fix breaks reading first empty line of a section

### ISSUE THREAD

**Issue by xGinko** [Zrips/CMI#7392]
### Description of Issue

When a section gets read and contains empty lines as first entries, the empty lines will be skipped until there is a line that contains _something_

**Example:**

Lets say this is your config:
```
 GeneralFormat:
    # This will define how others see players name in tab list
    PlayerName: '[playerDisplayName]%example_playertag_placeholder%'
    Header:
      '1':
      - ' '
      - ' '
      - ' '
      - ' '
      - '&f&l&oExample Server'
      - ' '
    Footer:
      '1':
      - ' '
      - '&7Example Footer'
      - ' '
      - ' '
      - ' '
```

CMI as of version 9.2.5.4 will read it in as:
```
 GeneralFormat:
    # This will define how others see players name in tab list
    PlayerName: '[playerDisplayName]%example_playertag_placeholder%'
    Header:
      '1':
      - '&f&l&oExample Server'
      - ' '
    Footer:
      '1':
      - '&7Example Footer'
      - ' '
      - ' '
      - ' ' 
```

**The workaround for this currently is to use &r or any other formatting/color code in the empty lines.**

### Version Information

```shell
CMI Plugin Version: 9.2.5.4 SqLite
CMILib: 1.2.3.7 
Server: Purpur 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
its just a question how you define an empty line.. my suggestion is just dont make it empty.
we mostly use a colorcode followed by an empty space

```
 GeneralFormat:
    # This will define how others see players name in tab list
    PlayerName: '[playerDisplayName]%example_playertag_placeholder%'
    Header:
      '1':
      - '&7 '
      - '&7 '
      - '&7 '
      - '&7 '
      - '&f&l&oExample Server'
      - '&7 '
    Footer:
      '1':
      - '&7 '
      - '&7Example Footer'
      - '&7 '
      - '&7 '
      - '&7 '
```
