### ISSUE TITLE
After the teleport, /fly is deactivated

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7411]
### Description of Issue

See also #7401

In short:
Fly is turned off every time I teleport by means of a warp/home/tppos.

When WorldLimits is on, it doesn't matter what worlds are entered. Even when said worlds are set to `:true`
Permissions are not the culprit. I have the `cmi.worldlimit.fly.bypass` and even had made myself OP.

Even when WorldLimits is turned off, fly is turned off by teleporting to another world.
I doubled checked by testing on a test server with default CMI config.

### Version Information

```shell
--------------------------------------------------
CMI: 9.2.5.6 BungeeCord SqLite
CMILib: 1.2.3.7
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 1 disabled: votifier
--------------------------------------------------
```

### Relevant Config Sections

```yaml
WorldLimits:
  Enabled: false
  Fly:
  - testWorld:False

#tested also with
WorldLimits:
  Enabled: true
  Fly:
  - world:False
  - world_nether:False
  - world_the_end:False

#even with
WorldLimits:
  Enabled: true
  Fly:
  - world:true
  - world_nether:true
  - world_the_end:true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
