### ISSUE TITLE
Problem with AutoRanks system

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#7412]
### Description of Issue

I'm setting up the rankup system, following the Wiki as it should be, but when I set a playtime and a player reaches it, it doesn't move him to the next rank and I don't understand why :/

### Version Information

```shell
cmi version
[00:13:21 INFO]: CMI: 9.2.5.6 BungeeCord CMIB MySQL
[00:13:21 INFO]: CMILib: 1.2.3.7
[00:13:21 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[00:13:21 INFO]: CMI economy: Désactivée CMI Chat: Activée
[00:13:21 INFO]: Modules -> 20 enabled 37 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, bossBarCompass, playerCombat, votifier, shulkerBackpack, cooldown, headDrop, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, portals, spawners, dynamicSigns, durabilityLoss, kits, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, selection, sitAnimation, warmup, totemBehavior
```

### Relevant Config Sections

```yaml
Bricoleur:
  Enabled: true
  DisplayName: '{#FCD779}Bricoleur'
  AutoRankup: true
  NextRanks:
  - Artiste
  StatsRequirements:
  - PlayTime:43200
Artiste:
  Enabled: true
  DisplayName: '{#FC8D6A}Artiste'
  AutoRankup: false
  Commands:
  - cmi sound block_anvil_use -p:2 -all -s
  - cmi broadcast !{#7ddf52}☄ &lGrades &7» {#green}Bravo à {#e6d545}[playerDisplayName]
    {#green}qui devient {#FC8D6A}Artiste {#green}!
  NextRanks:
  - Peintre
  StatsRequirements:
  - PlayTime:43200
Peintre:
  Enabled: true
  DisplayName: '{#766DB5}Peintre'
  AutoRankup: true
  Commands:
  - cmi sound block_anvil_use -p:2 -all -s
  - cmi broadcast !{#7ddf52}☄ &lGrades &7» {#green}Bravo à {#e6d545}[playerDisplayName]
    {#green}qui devient {#766DB5}Peintre {#green}!
  StatsRequirements:
  - PlayTime:864000
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by NoltoxGit** [comment]
![image](https://user-images.githubusercontent.com/75265787/204669148-058dbb9a-728c-4bf8-8fb0-88dc94b4dd0f.png)

**Comment by CloudeLecaw** [comment]
why u have autorankup false for your Artiste?
What is your default rank? i currently see no default one...

**Comment by CloudeLecaw** [comment]
have you tried this one?

```
Bricoleur:
  Enabled: true
  DisplayName: '{#FCD779}Bricoleur'
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Artiste
Artiste:
  Enabled: true
  DisplayName: '{#FC8D6A}Artiste'
  AutoRankup: true
  Commands:
  - cmi sound block_anvil_use -p:2 -all -s
  - cmi broadcast !{#7ddf52}☄ &lGrades &7» {#green}Bravo à {#e6d545}[playerDisplayName]
    {#green}qui devient {#FC8D6A}Artiste {#green}!
  NextRanks:
  - Peintre
  StatsRequirements:
  - PlayTime:43200
Peintre:
  Enabled: true
  DisplayName: '{#766DB5}Peintre'
  AutoRankup: true
  Commands:
  - cmi sound block_anvil_use -p:2 -all -s
  - cmi broadcast !{#7ddf52}☄ &lGrades &7» {#green}Bravo à {#e6d545}[playerDisplayName]
    {#green}qui devient {#766DB5}Peintre {#green}!
  StatsRequirements:
  - PlayTime:864000
```
