### ISSUE TITLE
AntiAFK not kick player

### ISSUE THREAD

**Issue by eduardopilati** [Zrips/CMI#7413]
### Description of Issue

hello, i am having a problem with afk autokick

config.yml:

```
Afk:
  Enabled: true
  TitleMessage: true
  SubTitleMessage: true
  PreventJumping: true
  PreventDamage: false
  CheckInterval: 10
  StopPlayTime: true
  AutoAfkIn: 60
  AutoAfkCmds:
  - null
  ManualAfkCmds:
  - null
  AfkLeaveCmds:
  - null
  AutoKickIn: 60
  RepeatingAutoKickInterval: 60
  RepeatKickCommand: false
  AutoKickCmds:
  - cmi kick [playerName] &eVocê foi expulso por ficar AFK por mais de [time] segundos
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  DisableOnInteract: true
  SmartInteractCheck: true
  AntiAfkMachines: true
  PreventPushing: false
  DisableOnInventoryClick: true
  DisableOnitemDrop: true
  DisableOnCommand: true
  DisableOnPublicChat: true
  DisableOnPrivateChat: true
  DisableOnMove: true
  DisableFishing: false
  DisableItemPickup: true
  PreventMobSpawning:
    Enabled: false
    Natural: false
    Spawners: false
    VillageDefence: false
  DisableExpPickup: false
```

permission cmi.command.afk.auto

```
lp user pilati_ permission check cmi.command.afk.auto
[LP] Permission information for cmi.command.afk.auto:
[LP] - pilati_ does not have cmi.command.afk.auto set.
[LP] - pilati_ inherits cmi.command.afk.auto set to true from default in context global.
[LP] 
[LP] Permission check for cmi.command.afk.auto:
[LP]     Result: true
[LP]     Processor: common.DirectProcessor
[LP]     Cause: default has cmi.command.afk.auto set to true in context global
```

permission cmi.command.afk.kickbypass 

```
lp user pilati_ permission check cmi.command.afk.kickbypass 
[LP] Permission information for cmi.command.afk.kickbypass:
[LP] - pilati_ does not have cmi.command.afk.kickbypass set.
[LP] - pilati_ does not inherit cmi.command.afk.kickbypass.
[LP] 
[LP] Permission check for cmi.command.afk.kickbypass:
[LP]     Result: undefined
[LP]     Processor: None
    Cause: None
```

cmi afkcheck pilati_
Pilati_: Inactive for past 6 min 28 sec

### Version Information

```shell
CMI: 9.2.5.6 MySQL
CMILib: 1.2.3.7 
Paper(245) 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
Modules -> 25 enabled 32 disabled: spawnerProximity, moneyCheque, skin, elytraBoost, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, vanish, timedCommands, homeInteractions, launchPad, portals, anvilRenameColor, playerChatTag, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, firstJoinMessages, selection, sitAnimation, silentChest, warmup
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
