### ISSUE TITLE
cmi.chat.rangebypass not working on OP's; only OP's chat is being sent to DiscordSRV

### ISSUE THREAD

**Issue by PovilasLT** [Zrips/CMI#7423]
### Description of Issue

cmi.chat.rangebypass permission is not working on players, who have all permissions (OP's). Chat messages froms OP's is only visible inside chat range.
Another problem, chat messages are being sent to DiscordSRV ingame chat channel only from players, who have cmi.chat.rangebypass permission.

### Version Information

```shell
9.2.6.1
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
Chat:
  ModifyChatFormat: true
  ClickHoverMessages: true
  DiscordSRV:
    Enabled: true
    GlobalChannel: globas
    Label: '&8[&7Discord&8]&r '
    UnlinkedLabel: '&8[&7Discord&8]&r '
  GeneralFormat: '%luckperms_prefix%%luckperms_suffix%%deluxetags_tag%%funkcijos_stars%&r
    %cmi_user_meta_spalva%{displayName}&f: &f'
  GeneralMessageFormat: '{#bbbbbb}{message}'
  GeneralRange: 250
  ShoutRange: -1
  ShoutCost: 0
```

### Relevant Plugins

DiscordSRV 1.26.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
