### ISSUE TITLE
Commands inside rank not running 

### ISSUE THREAD

**Issue by UltiMultiGamer** [Zrips/CMI#7437]
### Description of Issue

When running commands such as /rankset or /rankup, CMI should also run the "commands" section, present within a defined rank (from my understanding). However, when i attempt to run /rankset, /rankinfo shows the correct rank, but the commands (such as broadcast or pay and any others) are ignored.

### Version Information

```shell
Версия плагина CMI: 9.2.6.1
SqLite-> 9.3.0.1
[21:18:46 INFO]: CMILib: 1.2.3.7 -> 1.2.4.1
[21:18:46 INF0]: Версия сервера: Paper(301)
1.19.2-RO.1-SNAPSHOT
[21:18:46 INFO]: CMI Экономика: Enabled Bec ия Vault: 1.7.3-CMICMI Чат: Enabled
[21:18:46 INFO]: Модули -> 56 включено 1 отк лючено: votifier
```

### Relevant Config Sections

```yaml
- DamageDealt:500000
  NextRanks:
  - Netherite+
Netherite+:
  Enabled: true
  DisplayName: '&2Незерит+'
  AutoRankup: true
  Commands:
  - 'pay [playerName] 4500000:'
  - lp user [playerName] parent set netherite+
  - broadcast! &6[playerDisplayName] &eДостиг ранг %luckperms_prefix%!
  - playsound entity.player.levelup player @p ~ ~ ~ 1000000 0
  - particle minecraft:flash
  StatsRequirements:
  - PlayerKills:50000
  - DamageDealt:1000000
  NextRanks:
  - Champion
Champion:
  Enabled: true
  DisplayName: '&2Чемпион'
  AutoRankup: true
  Commands:
  - lp user [playerName] parent set champion
  - broadcast! &6[playerDisplayName] &eДостиг ранг %luckperms_prefix%!
  - playsound entity.player.levelup player @p ~ ~ ~ 1000000 0
  - particle minecraft:flash
  - pay [playerName] 1000000000
  StatsRequirements:
  - PlayerKills:100000
  - DamageDealt:2000000
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
