### ISSUE TITLE
Some entity names just won't be translated, even if they could.

### ISSUE THREAD

**Issue by notpivan** [Zrips/CMI#7467]
### Description of Issue

There are some entity types, like on /stats under "Mobs killed", that even if they are correctly translated in the CMILib Translation file, they're still displayed with their legacy (english) names.
Editing the translation file works just fine for some entities, but not for all of them.
I leave you an image which shows what I'm talking about:

![non tradotti](https://user-images.githubusercontent.com/35925140/209572848-8975db16-f3c4-4d80-9507-1cdc1ef3dd75.png)

As you can see, entities like Skeleton (Scheletro), Sheep (Pecora) etc. are correctly translated and if I edit those they change accordingly. But not everyone, like the Trader Llama, Polar Bear, Mushroom Cow and so on (everyone you see it has it's name in english just won't get translated).

### Version Information

```shell
cmi version
[18:51:01 INFO]: --------------------------------------------------
[18:51:01 INFO]: Versione di CMI: 9.3.0.2 SqLite
[18:51:01 INFO]: CMILib: 1.2.4.1 
[18:51:01 INFO]: Server: Purpur 1.19.3-R0.1-SNAPSHOT
[18:51:01 INFO]: CMI Economy: Disabilitato CMI Chat: Abilitato 
[18:51:01 INFO]: Moduli -> 56 abilitati 1 disabilitati: votifier
[18:51:01 INFO]: --------------------------------------------------


paper version
[18:51:03 INFO]: Checking version, please wait...
[18:51:03 INFO]: Current: git-Purpur-1876 (MC: 1.19.3)*
Previous: git-Purpur-1875 (MC: 1.19.3)
* You are running the latest version
```

### Relevant Config Sections

```yaml
EntityType:
    allay: Allay
    area_effect_cloud: Nuovola d'Effetto ad Area
    armor_stand: Armor Stand
    arrow: Frecce
    axolotl: Axolotl
    bat: Pipistrello
    bee: Ape
    blaze: Blaze
    boat: Barca
    camel: Cammello
    cat: Gatto
    cave_spider: Ragno delle Caverne
    chest_boat: Barca con Cassa
    chicken: Pollo
    cod: Merluzzo
    cow: Mucca
    creeper: Creeper
    dolphin: Delfino
    donkey: Asino
    dragon_fireball: Palle di Drago
    dropped_item: Oggetto Gettato
    drowned: Affogato
    egg: Uovo
    elder_guardian: Guardiano
    enderman: Enderman
    endermite: Endermite
    ender_crystal: Cristallo dell'End
    ender_dragon: Drago dell'End
    ender_pearl: Perla di Ender
    ender_signal: Segnale di Ender
    evoker: Evocatore
    evoker_fangs: Zanne
    experience_orb: Orb di Esperienza
    falling_block: Blocco Cadente
    fireball: Palla di Fuoco
    firework: Fuochi d'Artificio
    fishing_hook: Amo
    fox: Volpe
    frog: Rana
    ghast: Ghast
    giant: Gigante
    glow_item_frame: Cornice Luminosa
    glow_squid: Calamaro Luminoso
    goat: Capra
    guardian: Guardiano
    hoglin: Hoglin
    horse: Cavallo
    husk: Husk
    illusioner: Illusionista
    iron_golem: Golem di Ferro
    item_frame: Cornice
    leash_hitch: Intoppo al Guinzaglio
    lightning: Fulmine
    llama: Lama
    llama_spit: Sputo di Lama
    magma_cube: Cubo di Magma
    marker: Marker
    minecart: Carrello
    minecart_chest: Carrello con Cassa
    minecart_command: Carrello con Blocco Comandi
    minecart_furnace: Carrello con Fornace
    minecart_hopper: Carrello con Tramoggia
    minecart_mob_spawner: Carrello Mob Spawner
    minecart_tnt: Carrello con TNT
    mule: Mulo
    mushroom_cow: Mucca Fungosa
    ocelot: Ocelot
    painting: Dipinto
    panda: Panda
    parrot: Pappagallo
    phantom: Phantom
    pig: Maiale
    piglin: Piglin
    piglin_brute: Piglin Bruto
    pillager: Predone
    player: Giocatore
    polar_bear: Orso Polare
    primed_tnt: TNT Accesa
    pufferfish: Pescepalla
    rabbit: Coniglio
    ravager: Ravager
    salmon: Salmone
    sheep: Pecora
    shulker: Shulker
    shulker_bullet: Proiettile di Shulker
    silverfish: Silverfish
    skeleton: Scheletro
    skeleton_horse: Cavallo Scheletro
    slime: Slime
    small_fireball: Piccola Palla di Fuoco
    snowball: Palla di Neve
    snowman: Pupazzo di Neve
    spectral_arrow: Freccia Sprettale
    spider: Ragno
    splash_potion: Pozione da Lancio
    squid: Calamaro
    stray: Stray
    strider: Strider
    tadpole: Girino
    thrown_exp_bottle: Bottiglia di Esperienza
    trader_llama: Lama del Mercante
    trident: Tridente
    tropical_fish: Pesce Tropicale
    turtle: Tartaruga
    unknown: Sconosciuto
    vex: Vex
    villager: Villico
    vindicator: Vendicatore
    wandering_trader: Mercante Vagabondo
    warden: Sorvegliante
    witch: Strega
    wither: Wither
    wither_skeleton: Scheletro Wither
    wither_skull: Testa di Wither
    wolf: Lupo
    zoglin: Zoglin
    zombie: Zombie
    zombie_horse: Cavallo Zombie
    zombie_villager: Villico Zombie
    zombified_piglin: Piglin Zombificato
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
