### ISSUE TITLE
EventCommand order

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#7494]
I have this set in the config to get around /fly being disabled on world change.
```
playerTeleport:
  Enabled: true
  Commands:
  - statement:check1! perm:cmi.command.fly!
  - if:check1! cmi fly [playerName] true
```
However, fly is set to true before the player switches worlds when using /home. So it sets their fly to true, then switches world after the event command has run, which disables their fly again.
My request would be to run event commands after the world switch or add a delay option within event commands to have more control over when the command is run on a player.
