### ISSUE TITLE
Disabling kit preview doesnt work

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7504]
### Description of Issue

Hi, first thanks for adding that option, but sadly it doesnt seem to work.

Tried it with completely fresh configs, only set GUI and KitPreview to false, then created a new kit and gave player permission to use it - "lp user nick permission set cmi.kit.test". When that player types "/kit" it will correctly show him that kit, yet theres also a preview option that still works (removing the "eye" from lang file also doesnt help).

### Version Information

```shell
13:35:56[INFO] CMI: 9.3.0.5 SqLite
13:35:56[INFO] CMILib: 1.2.4.1
13:35:56[INFO] Server: Paper(365) 1.19.3-R0.1-SNAPSHOT
13:35:56[INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled
13:35:56[INFO] Modules -> 56 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
Kits:
  # When set to true, kit list will be shown in GUI instead of chat list
  GUI: false
  # When set to true, kit selection gui empty fields will get filled with definet item
  FillEmptyFields: true
  # When enabled players can preview kits they have access to or have cmi.kit.[kitName].preview or cmi.kit.[kitName].* permission node
  KitPreview: false


test:
  CommandName: test
  Delay: 10
  Items:
    '28':
      v: 3218
      type: GRASS_BLOCK
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
