### ISSUE TITLE
Schedule - Always returns true, regardless of configuration. 

### ISSUE THREAD

**Issue by Ksewedo5** [Zrips/CMI#7516]
### Description of Issue

I can't tell if something is true or false. I've been trying different possibilities for 3 hours, I always have a problem that everything is returned as true.

Maybe I'm configuring something wrong.... but I don't understand what could be causing this

### Version Information

```shell
CMI 9.3.0.5
CMILib 1.2.4.1
Server Paper(348) 1.19.3-R0.1
```

### Relevant Config Sections

```yaml
XXX:
  Enabled: true
  Delay: 5
  repeat: true
  Commands:
  - statement:check1! %cmi_user_name%!=Zrips! #Zrips = True, Ksewedo5 = True
  - if:check1! broadcast PASS
  - if:check1@! broadcast FAIL
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
