### ISSUE TITLE
PlayTimeRewards - PayFor doesnt work

### ISSUE THREAD

**Issue by Skopii** [Zrips/CMI#7523]
### Description of Issue

As the title says function PayFor doesnt work properly and if I try to claim the reward it just shows the command that is used to open the playtime rewrads ( **/prewards (playername)** 
Here are screenshot of what is happening (As you can see I can claim some rewards)  [Screenshots](https://ctrlv.cz/6mUZ)

_Idk If the same problems happen if you use AutoClaim (I will test it out - but I think it will work just fine because I have one PayEvery with AutoClaim on and it works)_ - 

**EDIT**
I have tested AutoClaim on PayFor and it works. So its only bugged if you dont use AutoClaim

### Version Information

```shell
CMI plugin version: 9.3.0.5 SqLite
 CMILib: 1.2.4.1
 Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
 CMI economy: Zapnuto Vault: 1.7.3-CMI CMI Chat: Zapnuto
 Modules -> 31 enabled 26 disabled: spawnerProximity, cuffed, mirror, tablist, moneyCheque, elytraBoost, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, shulkerBackpack, vanish, homeInteractions, hpBossBar, launchPad, elytraExploit, anvilRenameColor, jail, paintingEditor, playerChatTag, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks
```

### Errors

```shell
No errors
```

### Relevant Config Sections

```yaml
3 dny:
  DisplayName: "&a&lOdměna za 3 dny"
  AutoClaim: false
  Description:
  - "&7Získáš odměnu za odehrání 3 dní"
  PayFor: 259200
  Commands:
  - asConsole! ctellraw [playerName] <T>Získal jsi odměnu</T>
  - asConsole! cmi money give [playerName] 5000
  - asConsole! cc give v Pro 1 [playerName]
  
4 dny:
  DisplayName: "&a&lOdměna za 4 dny"
  AutoClaim: false
  Description:
  - "&7Získáš odměnu za odehrání 4 dní"
  PayFor: 345600
  Commands:
  - asConsole! ctellraw [playerName] <T>Získal jsi odměnu</T>
  - asConsole! cmi money give [playerName] 5000
  - asConsole! cc give v Pro 1 [playerName]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
