### ISSUE TITLE
(AFK) Kick message

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#753]
What players are getting the afk kick message?
From the language file:
`
  kick:
    info:
      messageToAll: '&6[playerDisplayName] &egot kicked from server.
      kickReason: ' &eReason: &6[reason]''
`

Does CMI have its own permission for staff to receive this message? So players won't be spammed with this.

**Comment by CloudeLecaw** [comment]
ist in the config! afk, back, and afkkickmeasseg are a command ;)

```

Afk:
  # Enable or disable auto afk system entirely
  Enabled: false
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  AutoAfkIn: 900
  # Defines commands to be performed when player enters afk mode
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&6[playerDisplayName] &eist nun AFK.
  - cmi gm [playerName] adventure -s
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&6[playerDisplayName] &eist nicht länger AFK
  - cmi gm [playerName] survival -s
  # Defines how long to wait after player stops moving to kick player
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &eDu warst länger als [time] AFK.
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables item pickup while afk
  DisableItemPickup: true
```
