### ISSUE TITLE
Holograms - Inccorrect placeholder format

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7549]
### Description of Issue

Hello, today ive got weird error about playtime top placeholder. Didnt touch this hologram for about a month or smt and never had that issue. Mostl likely could be CMI version 9.3.1.0 as i updated to it yesterday. Tho both of the placeholders still work normally.

### Version Information

```shell
15:41:50[INFO] CMI plugin version: 9.3.1.0 SqLite
15:41:50[INFO] CMILib: 1.2.4.1 -> 1.2.4.3
15:41:50[INFO] Server: Pufferfish 1.19.3-R0.1-SNAPSHOT
15:41:50[INFO] CMI economy: enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: enabled
15:41:50[INFO] Modules -> 33 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ran
ks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Errors

```shell
https://pastebin.com/mdQ71Jh7
```

### Relevant Config Sections

```yaml
TopPlaytime:
  Loc: Spawn;18.5;112.0;-45.5
  PageInterval: 30.0    
  HoverParticles:
    Count: 1
  Range: 16
  RangeExtra: 16
  Lines:
  - ICON:clock
  - _
  - '&c▶ &7Top Playtime &c◀'
  - '&c&l1. &6»&c %cmi_playtimetop_name_1% &7| &c%cmi_playtimetop_time_1% '
  - '&c&l2. &6»&c %cmi_playtimetop_name_2% &7| &c%cmi_playtimetop_time_2% '
  - '&c&l3. &6»&c %cmi_playtimetop_name_3% &7| &c%cmi_playtimetop_time_3% '
  - '&c&l4. &6»&c %cmi_playtimetop_name_4% &7| &c%cmi_playtimetop_time_4% '
  - '&c&l5. &6»&c %cmi_playtimetop_name_5% &7| &c%cmi_playtimetop_time_5% '
  - '&c&l6. &6»&c %cmi_playtimetop_name_6% &7| &c%cmi_playtimetop_time_6% '
  - '&c&l7. &6»&c %cmi_playtimetop_name_7% &7| &c%cmi_playtimetop_time_7% '
  - '&c&l8. &6»&c %cmi_playtimetop_name_8% &7| &c%cmi_playtimetop_time_8% '
  - '&c&l9. &6»&c %cmi_playtimetop_name_9% &7| &c%cmi_playtimetop_time_9% '
  - _
  - '&7Your playtime: &c%cmi_user_playtime_days%d %cmi_user_playtime_hours%h %cmi_user_playtime_minutes%m'
  - '!nextpage!'
  - ICON:clock
  - _
  - '&c▶ &7Top Playtime &c◀'
  - '&c&l10. &6»&c %cmi_playtimetop_name_10% &7| &c%cmi_playtimetop_time_10% '
  - '&c&l11. &6»&c %cmi_playtimetop_name_11% &7| &c%cmi_playtimetop_time_11% '
  - '&c&l12. &6»&c %cmi_playtimetop_name_12% &7| &c%cmi_playtimetop_time_12% '
  - '&c&l13. &6»&c %cmi_playtimetop_name_13% &7| &c%cmi_playtimetop_time_13% '
  - '&c&l14. &6»&c %cmi_playtimetop_name_14% &7| &c%cmi_playtimetop_time_14% '
  - '&c&l15. &6»&c %cmi_playtimetop_name_15% &7| &c%cmi_playtimetop_time_15% '
  - '&c&l16. &6»&c %cmi_playtimetop_name_16% &7| &c%cmi_playtimetop_time_16% '
  - '&c&l17. &6»&c %cmi_playtimetop_name_17% &7| &c%cmi_playtimetop_time_17% '
  - '&c&l18. &6»&c %cmi_playtimetop_name_18% &7| &c%cmi_playtimetop_time_18% '
  - _
  - '&7Your playtime: &c%cmi_user_playtime_days%d %cmi_user_playtime_hours%h %cmi_user_playtime_minutes%m'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
