### ISSUE TITLE
WorldLimits Fly bypass permission ignored

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7565]
### Description of Issue

Fly is disabled for players despite having the bypass permission `cmi.worldlimit.fly.bypass`

When teleporting, player will be checked for the permission but this is ignored but Fly is turned off anyway.

### Version Information

```shell
CMI: 9.3.1.3 BungeeCord SqLite
CMILib: 1.2.4.4
Server: Purpur 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled
Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
No errors
LuckPerms verbose info to prove that the permission is checked correctly:

[Server thread/INFO]: TestPlayer123 issued server command: /tppos 10 30 10 world
[luckperms-worker-13/INFO]: [LP] VB > TestPlayer123 - cmi.command - true
[luckperms-worker-13/INFO]: [LP] VB > TestPlayer123 - cmi.command.* - undefined
[luckperms-worker-13/INFO]: [LP] VB > TestPlayer123 - cmi.command.tppos - true
[luckperms-worker-13/INFO]: [LP] VB > TestPlayer123 - cmi.worldlimit.fly.bypass - true
```

### Relevant Config Sections

```yaml
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: true
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - world:Survival
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:false
  - world_nether:false
  - etc_worlds:false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
