### ISSUE TITLE
activation of totem whenever landing with pet from high locations

### ISSUE THREAD

**Issue by benpryde** [Zrips/CMI#7586]
### Description of Issue

When i was flying with my pet, and land from a high locations, the totem activates and my health drop to 1 heart.

If I don't have totem in my inventory, nothing happens, I land with no damage and proceed with my day.

After numerous tests, i singled out CMI, and found out if i disable the totem option (activation of totem within inventory), then the problem is gone.

I love this feature, is there anyway to fix it?

### Version Information

```shell
[12:02:01 INFO]: CMI: 9.3.1.4 BungeeCord  SqLite-> 9.3.1.3
[12:02:01 INFO]: CMILib: 1.2.4.5 
[12:02:01 INFO]: Server: Purpur 1.19.3-R0.1-SNAPSHOT
[12:02:01 INFO]: CMI economy: Enabled CMI Chat: Enabled 
[12:02:01 INFO]: Modules -> 38 enabled 19 disabled: spawnerProximity, cuffed, mirror, launchPad, tablist, jail, elytraBoost, elytraLaunch, bossBarCompass, flightCharge, disabledEnchants, worldLimitsElytra, ranks, playerCombat, votifier, shulkerBackpack, spawnerCharge, warmup, homeInteractions
```

### Errors

```shell
no error in console
```

### Relevant Config Sections

```yaml
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: false
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: false
    Time: 600
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: true
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

### Relevant Plugins

MyPet 3.12-B1737

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
