### ISSUE TITLE
Playerdisplay Name in Chat don't work anymore

### ISSUE THREAD

**Issue by PanetiX** [Zrips/CMI#7587]
### Description of Issue

Since the last update from CMI 9.3.1.3 to 9.3.1.4 the playername color (prefix) in Chat don't work correctly.
we have permission "cmi.chatgroup.13"

and in config.yml:
    '13': '&7[&4AN&7] {#ff0000}{displayName}{#DADADA}: {message}'

The playername in Chat is displayed gray after the update. 
When i switch back to 9.3.1.3 it works again like it should!

### Version Information

```shell
CMI 9.3.1.4
```

### Errors

```shell
No error in Log
```

### Relevant Config Sections

    '13': '&7[&4AN&7] {#ff0000}{displayName}{#DADADA}: {message}'

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Can you check if this is still an issue in 9.5.0.6 or newer?

**Comment by ChanceSD** [comment]
Same thing or similar here, I have this in config.yml:
```
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{prefix}{nickName}'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  # If you want to allow any letter from any language use [^\p{L}0-9\-\_]
  ValidNicknameRegex: '[^a-zA-Z0-9\-\_]'
```
And this in chat.yml:
`GeneralFormat: '{displayName} &4&m> {#e6dbcf}{message}'`

And there's no prefix in the messages
