### ISSUE TITLE
Socialspy not working

### ISSUE THREAD

**Issue by Kawazski** [Zrips/CMI#7612]
### Description of Issue

When I enable social spy in config.yml file or /cmi options it doesnt work. When u execute /cmi socialspy it says "This command doesnt exist". Especially when I enable command spy, every player is able to see commands written by other players without permission.

### Version Information

```shell
CMI Version: 9.3.1.5
CMILib Version: 1.2.4.5
```

### Errors

```shell
In console no errors are popping up for this issue
```

### Relevant Config Sections

```yaml
Spy:
    # Delay in seconds for commands spy to turn on after relog
    # This will prevent some one from loging in with admin account and seeing commands before loging in
    # Keep it at same or higher than your login plugin delay for entering password
    # This includes social spy too
    DelayForTrigger: 60
    # Commands in this list will not be shown when command spy is enabled for player for security/privacy reasons
    # This can be bypassed with cmi.command.commandspy.bypass permission node
    BlackListed:
    - register
    - login
    - l
    # Players without cmi.security.admin will only see commands from this list with command spy feature
    CommandList:
    - cmi spawn
    - cmi tp
    - cmi tpa
    - cmi heal
    - cmi feed
    - cmi fly

      # !Strongly not recommended to be enabled!
      chatSpy: true
      # !Strongly not recommended to be enabled!
      cmdSpy: true
      # !Strongly not recommended to be enabled!
      signSpy: true
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
COmmand spy doesn not exiits. In cmi options you can define the default state of command spy for ALL
that never used /cmi options before. once an options was set the defaults dont count for them anymore.

i recomment setting this value NOT to true. elxe everyone can commandspy you.
If you want the old command spy back create a custom alias for it.

**Comment by Kawazski** [comment]
> COmmand spy doesn not exiits. In cmi options you can define the default state of command spy for ALL that never used /cmi options before. once an options was set the defaults dont count for them anymore.
> 
> i recomment setting this value NOT to true. elxe everyone can commandspy you. If you want the old command spy back create a custom alias for it.

I dont understand, how can i create custom alias for it when its set to false + actual /cmi commandspy doesnt work?

**Comment by CloudeLecaw** [comment]
cmi DONT HAS COMMANDSPY command its all in cmi options. Update the translator please :P

Here you have a custom alias. it adds a command called cmdspy.

```
CustomAlias:
  cmdspy:
	Cmds:
	- check:$1==enable|disable|toggle! check:$2==null! asConsole! cmi options [playerName] commandspy $1 -s
	- check:$1!=enable|disable|toggle! check:$2==null! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy enable&c|&cdisable&c|&ctoggle
	- check:$1!=enable|disable|toggle! check:$2!=null! perm:cmi.customalias.cmdspy.others@! msg! [playerName] &c Your dont have permision to change the cmdspy status of other players.
	- check:$1!=enable|disable|toggle! check:$2!=enable|disable|toggle! perm:cmi.customalias.cmdspy.others! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy &cPLAYERNAME enable&c|&cdisable&c|&ctoggle
	- check:$1!=enable|disable|toggle! check:$2==enable|disable|toggle! perm:cmi.customalias.cmdspy.others! asConsole! cmi options $1 commandspy $2 -s
	Perm: true
	Tab: true
	CustomTabs:
	- 'enable,disable,toggle,[playerName], enable,disable,toggle'
```

**Comment by Kawazski** [comment]
Oh, sorry :D I didnt know about the creating own commands in CMI, anyways for socialspy command its the same setting?

**Comment by Kawazski** [comment]
> cmi DONT HAS COMMANDSPY command its all in cmi options. Update the translator please :P
> 
> Here you have a custom alias. it adds a command called cmdspy. command usegae: `/cmdspy [enable|disable|toggle|[playername]] (enable|disable|toggle)` permission to use it. `cmi.customalias.cmdspy` and to change status of other `cmi.custom.alias.cmdspy.others`
> 
> ```
> CustomAlias:
>   cmdspy:
> 	Cmds:
> 	- check:$1==enable|disable|toggle! check:$2==null! asConsole! cmi options [playerName] cmdspy $1 -s
> 	- check:$1!=enable|disable|toggle! check:$2==null! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy enable&c|&cdisable&c|&ctoggle
> 	- check:$1!=enable|disable|toggle! check:$2!=null! perm:cmi.customalias.cmdspy.others@! msg! [playerName] &c Your dont have permision to change the cmdspy status of other players.
> 	- check:$1!=enable|disable|toggle! check:$2!=enable|disable|toggle! perm:cmi.customalias.cmdspy.others! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy &cPLAYERNAME enable&c|&cdisable&c|&ctoggle
> 	- check:$1!=enable|disable|toggle! check:$2==enable|disable|toggle! perm:cmi.customalias.cmdspy.others! asConsole! cmi options $1 cmdspy $2 -s
> 	Perm: true
> 	Tab: true
> 	CustomTabs:
> 	- 'enable,disable,toggle,[playerName], enable,disable,toggle'
> ```
> 
> for other options read the wikipart here
> 
> > cmi [options (playerName) (option) (enable/disable/toggle/status) (-s)](https://www.zrips.net/cmi/commands/)
> > Modify personal options
> > Commands work individually. Without parameters will open a GUI where players can toggle to enable/disable certain features.
> > As of CMI version 9.1.4.x these legacy commands have been moved into a newer more convinient single /options command: togglecompass, toggleshiftedit, toggletotem, tagtoggle, socialspy, commandspy, signspy, msgtoggle, tptoggle, paytoggle.
> > In the config.yml file you can further configure the /options’ GUI panel.
> > Permissions involved to allow modifying specific options: cmi.command.options.[visibleholograms/shiftsignedit/totembossbar/bassbarcompass/tagsound/chatspy/cmdspy/signspy/acceptingpm/acceptingtpa/acceptingmoney]. Players will also need the base command: cmi.command.options
> > Placeholders are grouped as well: %cmi_user_toggle_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]% %cmi_user_togglename_[msg|pay|tp|compass|sospy|sispy|cospy|schest|autoflightrecharge|totem|shiftedit]%

Yep, thanks for your help, Apreciate it!

**Comment by CloudeLecaw** [comment]
well i dont know if the reply has a copy paste error.. but here the Custom Alias aggain 🗡️ 

```
  cmdspy:
    Cmds:
    - check:$1==enable|disable|toggle! check:$2==null! asConsole! cmi options [playerName] commandspy $1 -s
    - check:$1!=enable|disable|toggle! check:$2==null! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy enable&c|&cdisable&c|&ctoggle
    - check:$1!=enable|disable|toggle! check:$2!=null! perm:cmi.customalias.cmdspy.others@! msg! [playerName] &c Your dont have permision to change the cmdspy status of other players.
    - check:$1!=enable|disable|toggle! check:$2!=enable|disable|toggle! perm:cmi.customalias.cmdspy.others! msg! [playerName] &c You used wrong command syntax. usage&c:&c/&ccmdspy &cPLAYERNAME enable&c|&cdisable&c|&ctoggle
    - check:$1!=enable|disable|toggle! check:$2==enable|disable|toggle! perm:cmi.customalias.cmdspy.others! asConsole! cmi options $1 commandspy $2 -s
    Perm: true
    Tab: true
    CustomTabs:
    - 'enable,disable,toggle,[playerName], enable,disable,toggle'
```
