### ISSUE TITLE
Links and commands in the hologram do not work

### ISSUE THREAD

**Issue by Ikdan08** [Zrips/CMI#7628]
### Description of Issue

Hello, I have a problem with the plugin. In the configuration, I even inserted an example from the wiki, but it still doesn't work.
![image](https://user-images.githubusercontent.com/65921752/220978107-0cd8eb8f-2dfd-4b87-9045-ec62009032c5.png)
![image](https://user-images.githubusercontent.com/65921752/220978142-606f80e7-3cde-4d32-bcec-6a2cffe36af1.png)
![image](https://user-images.githubusercontent.com/65921752/220978192-0e8d45f4-34df-419b-bbf0-1b554d44b8bc.png)
![image](https://user-images.githubusercontent.com/65921752/220978270-fa926670-1c21-4057-b1c0-5b24bc846036.png)
my plugins folder:
![image](https://user-images.githubusercontent.com/65921752/220978360-327cbce5-6074-4f81-9ada-e82cc95e088b.png)

### Version Information

```shell
Версия плагина CMI: 9.3.1.5 SqLite
CMILib: 1.2.4.5
```

### Errors

```shell
no errors
```

### Relevant Config Sections

```yaml
spawn_MOTD:
  Loc: spawn;-100.5;104.0;-17.5
  Interval: 0.1
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
    Stabilize: true
  Range: 6
  RangeExtra: 56
  DownOrner: false
  Interactable: true
  BigButton: false
  Lines:
  - '%javascript_servername%'
  - '&r'
  - Привет %player_name%, мы рады тебя видеть!
  - Приятной игры на сервере :)
  - '&r'
  - '<T>Сайт: %javascript_website%</T><C>onPlayer! site</C>'
  - <T>{#gray>}Free heal{#edward<}</T><H>{#edward>}&lFree heal{#gray<}</H><C>asConsole!
    gcooldown:3?! cmi heal [playerName]</C>
```

### Relevant Plugins

[Vault] Vault v1.7.3-CMI Information [Vault] Economy: CMIEconomy [CMIEconomy]

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
