### ISSUE TITLE
color code unusable on sign

### ISSUE THREAD

**Issue by JeremyDarbellay** [Zrips/CMI#7634]
### Description of Issue

When I enter : "&fHi" on a sign,
This sign translate this to "\<white\>Hi", instead of coloring it to white.
This feature comes from CMI, i've tried with and without oraxen, it happens only with oraxen.

I've reported this issue to oraxen, because i don't know which can fix this.

### Version Information

```shell
CMI: 9.3.1.5 sqlite
CMILIB: 1.2.4.5
SERVER: Paper(420) 1.19.3-R0.1-SNAPSHOT
economy disabled, cmi chat disabled
modules-> 56 enabled 1disabled (votifier)

(i'm using default configs from all plugins and default for paper, it's a fresh test server without any change)
```

### Errors

```shell
-- no error --
```

### Relevant Config Sections

```yaml
-- no relevant config section --
```

### Relevant Plugins

Oraxen 1.151.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Btoven** [comment]
In Oraxen settings.yml you can disable all formatting. Not sure what version this was added to the config but I had the same issue. Hope this helps!
  

```
  formatting:
    inventory_titles: true # Formats all inventory titles made by any plugin
    titles: false # Formats all titles made by any plugin
    subtitles: false # Formats all subtitles made by any plugin
    action_bar: false # Formats all action bars made by any plugin
    anvil: false # Formats the result item based on the Anvil Text made by any plugin
    signs: false
  keep_this_up_to_date: true
```
