### ISSUE TITLE
customrecipe

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/CMI#7657]
### Description of Issue

Hello, 
since the MC spawners changed after the new version 1.19.3, we can't customcraft with them. There was never a problem and everything worked fine. Now sometimes it happens that a recipe can be created, but sometimes unfortunately not. (screen)

### Version Information

```shell
[17:01:42 INFO]: CMI: 9.3.1.6 BungeeCord MySQL
[17:01:42 INFO]: CMILib: 1.2.4.5
[17:01:42 INFO]: Server: Purpur 1.19.3-R0.1-SNAPSHOT
[17:01:42 INFO]: CMI economy: POVOLENO Vault: 1.7.3-b131(CMIEInjector) CMI Chat: ZAKAZÁNO
[17:01:42 INFO]: Modules -> 46 enabled 11 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, tablist, skin, noTarget, elytraBoost, spawnerCharge, paintingEditor, playerChatTag
```

### Errors

```shell
[screen](https://imgur.com/a/KDZ2lrN)
```

### Relevant Config Sections

```yaml
bceb8019-51c8-3621-a109-16bff3dc4a3a:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: NETHERITE_AXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_blue","text":"DIY"},{"bold":true,"italic":false,"color":"dark_aqua","text":"
          Sekera"}],"text":""}'
        lore:
        - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Kolekce
          |"},{"bold":false,"italic":false,"color":"white","text":" "},{"bold":true,"italic":false,"color":"dark_blue","text":"DIY"}],"text":""}'
        enchants:
          DIG_SPEED: 6
          MENDING: 1
          SILK_TOUCH: 1
```

### Relevant Plugins

Vault 1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
