### ISSUE TITLE
Regex is both overly zealous and also not catching the appropriate things

### ISSUE THREAD

**Issue by Kraxous** [Zrips/CMI#7673]
### Description of Issue

After deploying and configuring the chat filters for CMI, I'm a little bit baffled as the regex values are very unpredictable.

My players have been helping me test it, and I've found that it blocks random sentences from players (In this instance Player2) but won't block swears with spaces between them from another (Player1).

I used the recommended website, [CMI ChatFilter](https://dkalaxdk.github.io/CMIRegexFilter/CMIRegex.html), and it looks fine in the config but doesn't work as I intended it to.

I believe I could be missing something, but figured I'd report it since this is blocking sentences but not swears.

I have also tried it with and without `\b` values with same results.

### Version Information

```shell
CMI: 9.3.2.0 MySQL
CMILib: 1.2.4.6
Server: Purpur 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 53 enabled 4 disabled: votifier, shulkerBackpack, moneyCheque, vanish
```

### Errors

```shell
[21:19:54 INFO]: (317) Member | Player1 ▷ t w a t
[21:20:10 INFO]: (317) Member | Player1 ▷ in your face d i c k h e a d
[21:20:16 INFO]: (317) Member | Player1 ▷ w a n k

[21:27:19 INFO]: [CMI] Player2 triggered (Swearing) chat filter with: because im at 2 stacks of coal and no skulls
[21:27:19 INFO]: Player2 got warned by Server for: Violated server rules
[21:27:19 INFO]: Added new note for player
[21:27:19 INFO]:  [X] 01. Caught swearing
```

### Relevant Config Sections

```yaml
Swearing:
      Enabled: true 
      Group: Swearing
      InformConsole: true
      Regex: 
        - [̀-ͯ᪰-᫿᷀-᷿⃐-⃿︠-︯] 
        - [^ -~] 
        - (?i)(a|4(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+
        - (?i)(a|4(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(w|//(\W|\d|_|)+)+(j(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(b|8(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(w|//(\W|\d|_|)+)+( (\W|\d|_|)+)+(j(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(b|8(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(b|8(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(p|\|2(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+
        - (?i)(c|\((\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(r(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+
        - (?i)(c|\((\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+
        - (?i)(c|\((\W|\d|_|)+)+(r(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(p|\|2(\W|\d|_|)+)+
        - (?i)(c|\((\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+
        - (?i)(d|<\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(d|<\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(d|<\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+
        - (?i)(d|<\|(\W|\d|_|)+)+(y|'/(\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(h|\|-\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(d|<\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(p|\|2(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(f|ph(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(d|<\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+( (\W|\d|_|)+)+(p|\|2(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(h|\|-\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(m|\|\/\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+
        - (?i)(j(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(j(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(z(\W|\d|_|)+)+(z(\W|\d|_|)+)+
        - (?i)(k|\|<(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(b|8(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(d|<\|(\W|\d|_|)+)+
        - (?i)(k|\|<(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(b|8(\W|\d|_|)+)+(h|\|-\|(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(d|<\|(\W|\d|_|)+)+
        - (?i)(m|\|\/\|(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(f|ph(\W|\d|_|)+)+(f|ph(\W|\d|_|)+)+
        - (?i)(n|\|\\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(n|\|\\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+
        - (?i)(p|\|2(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+
        - (?i)(p|\|2(\W|\d|_|)+)+(r(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(p|\|2(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+(y|'/(\W|\d|_|)+)+
        - (?i)(q(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(s|5(\W|\d|_|)+)+(c|\((\W|\d|_|)+)+(r(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(m|\|\/\|(\W|\d|_|)+)+
        - (?i)(s|5(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(x|><(\W|\d|_|)+)+
        - (?i)(s|5(\W|\d|_|)+)+(l|\|(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+
        - (?i)(s|5(\W|\d|_|)+)+(m|\|\/\|(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(g|6|9(\W|\d|_|)+)+(m|\|\/\|(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+
        - (?i)(s|5(\W|\d|_|)+)+(p|\|2(\W|\d|_|)+)+(u|\|_\|(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(t|7\|+(\W|\d|_|)+)+(i|1|!|\|(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+
        - (?i)(t|7\|+(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+(s|5(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+(r(\W|\d|_|)+)+
        - (?i)(t|7\|+(\W|\d|_|)+)+(w|//(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(t|7\|+(\W|\d|_|)+)+
        - (?i)(w|//(\W|\d|_|)+)+(a|4(\W|\d|_|)+)+(n|\|\\|(\W|\d|_|)+)+(k|\|<(\W|\d|_|)+)+
        - (?i)(w|//(\W|\d|_|)+)+(h|\|-\|(\W|\d|_|)+)+(o|0(\W|\d|_|)+)+(r(\W|\d|_|)+)+(e|3(\W|\d|_|)+)+
      Blocktype: all
      msgToStaff: '&7[&4&l!&r&7] &c[playerName] has just said &6"[message]" &cin global.'
      Commands: 
        - cmi warn [senderName]
        - cmi note [senderName] add Caught swearing
      includePrivateMessages: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
