### ISSUE TITLE
https://paste.gg/p/anonymous/a22c48abf075400eb9eb40b2b5228cb1

### ISSUE THREAD

**Issue by TWME-TW** [Zrips/CMI#7675]
### Description of Issue

Can't display particle 

### Version Information

```shell
SelectionVisualizer v3.2.1.0
```

### Errors

```shell
https://paste.gg/p/anonymous/a22c48abf075400eb9eb40b2b5228cb1
```

### Relevant Config Sections

```yaml
GriefDefender:
    Area:
      Effect1:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 144;238;144
        Cap: 200
      Effect2:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 50;50;20
        Cap: 200
      Effect3:
        Effect: reddust
        RowSpacing: 1.0
        CollumnSpacing: 1.0
        Color: 1;20;20
        Cap: 200
      Interval: 3
      SkipBy: 10
      Range: 32
      ShowFor: 30000
      ByDefaultIsEnabled: true
```

### Relevant Plugins

GriefDefender v2.3.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
