### ISSUE TITLE
setworth command

### ISSUE THREAD

**Issue by Oneida15** [Zrips/CMI#7693]
### Description of Issue

I think the purple text in the picture is wrong
it is  command.setworth.info.ingridient
i think it needs to be  command.setworth.info.ingredient
 

### Version Information

```shell
--------------------------------------------------
CMI: 9.4.0.2 SqLite
CMILib: 1.2.5.2 
Server: Paper(466) 1.19.4-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 56 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
https://cdn.discordapp.com/attachments/526402563847880725/1087566978144817152/2023-03-20_21.39.45.png
```

### Relevant Config Sections

```yaml
setworth:
    help:
      info: '&eChange item worth'
      args: (itemname) -s:(sellPrice)
    info:
      setSell: '&eSet item sell price &7[amount]'
      setBuy: '&eSet item buy price &7[amount]'
      notInUse: '&eMainly used for possible exploit detection'
      sellPrice: '&fSell price: &e[amount]'
      buyPrice: '&fBuy price: &2[amount]'
      exploit: '&4Possible EXPLOIT!'
      ingredient: '&2Ingredients'
      ingredients: '&7[ingredient]&f(&7[amount]&f) = &e[price]'
      notSet: '&eprice not set'
      notSetBuy: '&7Buy price not set'
      result: '&2Crafts into &7[result]&f(&7[amount]&f)'
      ingredientsPrice: '&cIngredient price: &7[price]'
      resultPrice: '&cCan be sold for: &7[price]'
      explanation: '&2Buy price is only used in detecting posible exploits'
  shadowmute:
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
