### ISSUE TITLE
Prevent Mob Spawn When AFK Not working

### ISSUE THREAD

**Issue by Michael-A-Sloan** [Zrips/CMI#7697]
### Description of Issue

Hello I have found that players that are afk at a farming machine on the nether roof are not having mobs stopped from spawning when they are afk.

### Version Information

```shell
CMI: 9.4.0.2 SqLite
CMILib: 1.2.5.2
Server: Paper(448) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 47 enabled 10 disabled: deathMessages, customMessages, firstJoinMessages, playerCombat, portals, headDrop, sitAnimation, namePlates, playerChatTag, timedCommands
```

### Errors

```shell
No errors found
```

### Relevant Config Sections

```yaml
PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: true
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: true
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: true
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
