### ISSUE TITLE
dynamic Signs failed to move to folder in 9.5.0.0 - Also Jails, Portals, Holograms and D-Enchants might need a tweek..

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7703]
### Description of Issue

- Dynamic Signs were not moved and need to be in main folderm else they do not load
- Jails are still in main Folder and are not loaded. Even if you manually move them to the save folder they got not loaded

- Holograms were not taken to the Save folder. A 0 file created. -  placing a Backup into the Saved Folder and rename them to Holograms.yml helped and they loaded after
- Portals were not taken to the Save folder. A 0 file created. -  placing a Backup into the Saved Folder and rename them to Portals.yml helped and they loaded after
- DisabledEnchants got moved to Saved folder but not deleted from mainfolder.

![Snag_208d242](https://user-images.githubusercontent.com/12080017/227659667-0bdeaca4-a5d6-4962-a902-852db31d8334.png)
No jails founds. i have no chance at the moment to load them. not placing them in saves or mainfolder nor the rename to Jails.yml

### Version Information
![Snag_206866e](https://user-images.githubusercontent.com/12080017/227659434-6a1664ba-597e-44b7-a28c-cba6efc01c63.png)

### Errors
```shell
None is console
```

### Relevant Config Sections
```yaml
portals.yml
dynamicSigns.yml
jails.yml
holograms.yml
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Edit: Afer the last Restart the jails.yml now also was moved to saved and got renamed to Jails.yml and the Jails are shows now aggain.

The dynamicSigns.yml is remaining...

**Comment by mrfloris** [comment]
I cannot reproduce the jails issue. Mine are loading, and show ingame.

**Comment by CloudeLecaw** [comment]
> I cannot reproduce the jails issue. Mine are loading, and show ingame.

well see my Editing they where loaded into the right folder after secound restart and shown correct too

**Comment by Zrips** [comment]
dynamicSigns file was oversight of mine as it only gets created if there are records which need to be saved. Will fix that. Rest of the issues are related to missing folder bug, will fix that too.

**Comment by CloudeLecaw** [comment]
> dynamicSigns file was oversight of mine as it only gets created if there are records which need to be saved. Will fix that. Rest of the issues are related to missing folder bug, will fix that too.

hm is there a difference if "recods neesd to be saved and file is not empty?
Here you see the 7 signs we got :3
```
'1':
  Loc: world;440.0;60.0;337.0
  Interval: 1.0
  Range: 7
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_6%'
  - '%cmi_jail_time_Verliess_6%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_6%'
'2':
  Loc: world;421.0;60.0;343.0
  Interval: 1.0
  Range: 7
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_3%'
  - '%cmi_jail_time_Verliess_3%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_3%'
'3':
  Loc: world;424.0;60.0;337.0
  Interval: 1.0
  Range: 7
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_4%'
  - '%cmi_jail_time_Verliess_4%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_4%'
'4':
  Loc: world;432.0;60.0;337.0
  Interval: 1.0
  Range: 7
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_5%'
  - '%cmi_jail_time_Verliess_5%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_5%'
'5':
  Loc: world;440.0;60.0;343.0
  Interval: 1.0
  Range: 7
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_1%'
  - '%cmi_jail_time_Verliess_1%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_1%'
'6':
  Loc: world;430.0;60.0;343.0
  Interval: 1.0
  Range: 10
  Personal: true
  Lines:
  - '%cmi_jail_username_Verliess_2%'
  - '%cmi_jail_time_Verliess_2%'
  - 'Grund:'
  - '%cmi_jail_reason_Verliess_2%'
'7':
  Loc: world;-179.0;71.0;222.0
  Interval: 2.0
  Range: 10
  Personal: false
  Lines:
  - '&0Rohes'
  - '&0Hammelfleisch'
  - '&cRoher'
  - '&cKabeljau'
  - '&0Rohes'
  - '&0Schweinefleisch'
  - '&cRohes'
  - '&cRindfleisch'
  - '&0Tonklumpen'
  - '&cStein'
  - '&0Bruchstein'
  - '&cRohes'
  - '&cHühnchen'
  - '&0Netherrack'
  - '&cSand'
  - '&0Eisenerz'
  - '&cGolderz'
```
