### ISSUE TITLE
Custom Recipes not working with Custom Items

### ISSUE THREAD

**Issue by Pjotr001** [Zrips/CMI#7713]
### Description of Issue

When I create a recipe using custom items that have been added through ItemsAdder, they refuse to show up after trying to craft the exact same recipe in a crafting table.

Server version: git-Paper-488

![image](https://user-images.githubusercontent.com/129227740/228370430-ae8de928-9234-4dfe-acdb-1046f88ce35a.png)
![image (1)](https://user-images.githubusercontent.com/129227740/228370465-45f1a1d5-afa6-4493-a5e1-b94030edb752.png)

### Version Information

```shell
[21:18:28 INFO]: --------------------------------------------------
[21:18:28 INFO]: CMI: 9.5.0.1 SqLite
[21:18:28 INFO]: CMILib: 1.2.5.2 
[21:18:28 INFO]: Server: Paper(448) 1.19.3-R0.1-SNAPSHOT
[21:18:28 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[21:18:28 INFO]: Modules -> 57 enabled 1 disabled: votifier
[21:18:28 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
CRecipes:
  9cb4ab75-2fad-3047-8f2c-c5394255aa42:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: LEATHER_LEGGINGS
      meta:
        ==: ItemMeta
        meta-type: LEATHER_ARMOR
        display-name: '{"italic":false,"color":"white","text":"Fur Leggings"}'
        lore:
        - '{"italic":false,"color":"gray","text":"Durability: 225 / 225"}'
        custom-model-data: 10008
        attribute-modifiers:
          GENERIC_ARMOR:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 2.5
            name: itemsadder
            slot: LEGS
            uuid: fe6a4c5b-bb89-3990-95a0-b60481c7dbc2
            operation: 0
          GENERIC_ARMOR_TOUGHNESS:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.0
            name: itemsadder
            slot: LEGS
            uuid: 29f0ccfc-37ea-3848-bd5d-f16672d5828a
            operation: 0
        ItemFlags:
        - HIDE_DYE
        internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS1iZhDNTayITy4tLsnPjU8pLUpMyszJLKlkYGB4yMHAmZeYm1pckJicysANUZJYlJtfxMHAlJnCwJNWWhSfk5qenpmXXszGwJ+WmJ2KZIJD0AEGEGBmEMRqOgMDAL5anrOMAAAA
        color:
          ==: Color
          RED: 214
          BLUE: 182
          GREEN: 66
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '1':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"italic":false,"color":"white","text":"Fur"}'
            lore:
            - '{"italic":false,"color":"blue","text":"Ingredients"}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
  7b13aa4b-f7d4-39f9-8cbc-5a20a0091642:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: LEATHER_HELMET
      meta:
        ==: ItemMeta
        meta-type: LEATHER_ARMOR
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur
          Hood"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Durability:
          165 / 165"}],"text":""}'
        custom-model-data: 10007
        attribute-modifiers:
          GENERIC_ARMOR:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 4.5
            name: itemsadder
            slot: HEAD
            uuid: ecfab2ba-5d04-371f-940b-6042757b5b7d
            operation: 0
          GENERIC_ARMOR_TOUGHNESS:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.0
            name: itemsadder
            slot: HEAD
            uuid: 40bc0c55-fad6-3bd4-970a-c755d15edb5c
            operation: 0
        ItemFlags:
        - HIDE_DYE
        internal: H4sIAAAAAAAA/22MQQ6CMBBFfyQxtS4IC+/jnkM0AzOERseaaZvIjst4T2PYsOCt33se8PCxiGZiFmtwU/qEseaSNHA1GuIzlgXA1+HyIpX8plFw3RQyTeZwigw3VQtzSnxGO9FDdvW9X/GnQXd4Bn6VKZ75iAAAAA==
        color:
          ==: Color
          RED: 214
          BLUE: 182
          GREEN: 66
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
        byItem: true
      '1':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
        byItem: true
  fc773653-96ee-32f3-a20f-03f6ecc2c8b1:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: LEATHER_BOOTS
      meta:
        ==: ItemMeta
        meta-type: LEATHER_ARMOR
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur
          Boots"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Durability:
          195 / 195"}],"text":""}'
        custom-model-data: 10008
        attribute-modifiers:
          GENERIC_ARMOR:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.5
            name: itemsadder
            slot: FEET
            uuid: 5fbe10fa-f282-3f34-b5d5-234880566b98
            operation: 0
          GENERIC_ARMOR_TOUGHNESS:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.0
            name: itemsadder
            slot: FEET
            uuid: aeee788e-035b-3e0a-ad34-0868bc51d844
            operation: 0
        ItemFlags:
        - HIDE_DYE
        internal: H4sIAAAAAAAA/22MQQqDMBBFPwoS40JceB+P0BuE0Uwg2GnKJAF7Pi9WipsufOv3ngUsbCwsmbxnbTELHW6ruSRxviqt8RnLB8Bp0L9IOL9pYwyXQipJDZro0Yeqbk2p5A5joJ3/8uWx4EeL6XYNfAG09oSiiQAAAA==
        color:
          ==: Color
          RED: 214
          BLUE: 182
          GREEN: 66
    Recipe:
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
  917aa24b-1b83-3664-a294-8d93cd5b96cc:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: LEATHER_CHESTPLATE
      meta:
        ==: ItemMeta
        meta-type: LEATHER_ARMOR
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur
          Coat"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Durability:
          240 / 240"}],"text":""}'
        custom-model-data: 10008
        attribute-modifiers:
          GENERIC_ARMOR:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 3.5
            name: itemsadder
            slot: CHEST
            uuid: 1e050829-4f8e-3b16-9f36-4e5b50a28031
            operation: 0
          GENERIC_ARMOR_TOUGHNESS:
          - ==: org.bukkit.attribute.AttributeModifier
            amount: 1.0
            name: itemsadder
            slot: CHEST
            uuid: f269729a-5199-3723-ab1f-8ba201e83007
            operation: 0
        ItemFlags:
        - HIDE_DYE
        internal: H4sIAAAAAAAA/22MwQqDMBAFHwoS40F66P/0I7yHNVkhtNvIJgH71/0EQS8enPPMWMDCxsKSKQTWFk+hzfmaSxIXqtIcP7H8APwN+i8J55U8YzgVUklq0MQAs1R1PlHpMC705kv9mnDQ4nF7BnbSwpKtiAAAAA==
        color:
          ==: Color
          RED: 214
          BLUE: 182
          GREEN: 66
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '4':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '7':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: PAPER
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Fur"}],"text":""}'
            lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Ingredients"}],"text":""}'
            custom-model-data: 10106
            internal: H4sIAAAAAAAA/+NiYOBi4MosSc0tTkxJSS3iYGDKTGFgTisFsjjzEnNTiwsSk1MZuJNLi0vyc8HqGBgAoQNINTUAAAA=
        byItem: true
  234547e4-7116-30fb-83f6-ecaebe5fb237:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: OAK_WOOD
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '1':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '4':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '7':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: OAK_PLANKS
        byItem: true
```

### Relevant Plugins

ItemsAdder 3.4.1-r3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
