### ISSUE TITLE
Geyser players not getting playtime rewards

### ISSUE THREAD

**Issue by DuneSciFye** [Zrips/CMI#7740]
### Description of Issue

Geyser players don't get playtime rewards, while Java players do. Both types of players have playtime increase though from the /cmi playtime command

### Version Information

```shell
--------------------------------------------------
CMI: 9.5.0.2 SqLite
CMILib: 1.2.5.2
Server: Paper(448) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled
Modules -> 55 enabled 3 disabled: cuffed, tablist, votifier
--------------------------------------------------
```

### Relevant Config Sections

```yaml
hourly1:
  DisplayName: "&fEvery 10 Minutes"
  AutoClaim: true
  Description:
  - "&7Get &f5&7-&f10 &bMobcoins"
  PayEvery: 500
  Commands:
  - asConsole! mobcoins give [playerName] %rng_5,10%
  - asConsole! cmi msg [playerName] !-&aYou recieved mobcoins for playing for &f10 &3Minutes&a!
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
