### ISSUE TITLE
SQL dont save players when server get restart

### ISSUE THREAD

**Issue by abenraged** [Zrips/CMI#7743]
### Description of Issue

title

### Version Information

```shell
CMI: 9.5.0.2 MySql
CMILib: 1.2.5.2
```

### Errors

```shell
0 errors just dont save info player when server get ctrl+c

but when player manualy left from server - sql save properly
```

### Relevant Config Sections

```yaml
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: xxx
  password: xxx
  hostname: xxx
  database: xxx
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 60
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: true
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
