### ISSUE TITLE
Permission "cmi.cooldown.__" isn't working anymore

### ISSUE THREAD

**Issue by Replaycchi** [Zrips/CMI#7775]
### Description of Issue

Hello,

I'm using permissions to reduce the cooldown of the /tpa command on my server (cmi.cooldown.cmi_tpa_.900)
since a long time but it seems to be broken for now, player still has the highest default cooldown for the command

### Version Information

```shell
[14:14:53 INFO]: CMI: 9.5.0.7 BungeeCord CMIB MySQL
[14:14:53 INFO]: CMILib: 1.2.5.3
[14:14:53 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[14:14:53 INFO]: CMI economy: Activé Vault: 1.7.3-b CMI Chat: Activé
[14:14:53 INFO]: Modules -> 49 enabled 9 disabled: spawnerProximity, deathMessages, tablist, ranks, votifier, headDrop, spawners, spawnerCharge, namePlates
```

### Relevant Config Sections

```yaml
Cooldowns:
  # You can enable any command cooldown to prevent instant usage of it
  # cmi heal:180 means that player can use /cmi heal command only once every 180 seconds
  # if cooldown set to -1 then this command can be performed only one time
  # Administration can bypass limitations with cmi.cooldownbypass.[commandname] permission node
  # Always use full command name and not its alias
  # ----------
  # Alternatively you can use cmi.cooldown.[some_command].[timer] permission node. For example: cmi.cooldown.cmi_heal.30 which will set 30 second cooldown on /cmi heal command
  # If you want to apply cooldown on command when variable is provided, add extra _ at end. For example cmi.cooldown.cmi_heal_.30 which will only use this cooldown when healing some one else
  # KEEP IN MIND that for permission to work you need to set base command cooldown in this list, otherwise permission node will have no effect
  # -----
  # ATTENTION! If you have command like "/cmi home" and you want to prevent teleportation to home but allow gui opening without restrictions, use space after command, in example "cmi home :10"
  Enabled: true
  List:
  - cmi tpa:1800
  - cmi tpahere:86400
  - cmi nick:86400
  - cmi nick off:0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
