### ISSUE TITLE
CMI Tpa Cooldown Problem

### ISSUE THREAD

**Issue by HandsomeshadowYT** [Zrips/CMI#7778]
### Description of Issue

So My issue is that When someone tpa to the other person it has a option that gives a warmup of X seconds as defined in the config.
Now the problem is if u set the warmup under the teleport column ops/admins cannot bypass it
So i had an idea of setting that warmup to 0 and add tpaccept to the "warmups" list
Now what problem that created is for example Player A runs /tpa B
So player B gets request and clicks the green button in chat which runs /tpaccept but player B gets cooldown instead of player A who should get it because he is teleporting

So what should i do to solve it.
Asked on discord smone told to make a issue here.

### Version Information

```shell
[08:40:29 INFO]: --------------------------------------------------
[08:40:29 INFO]: CMI: 9.5.0.1 BungeeCord  SqLite-> 9.5.0.7
[08:40:29 INFO]: CMILib: 1.2.5.3 
[08:40:29 INFO]: Server: Paper(111) 1.19.1-R0.1-SNAPSHOT
[08:40:29 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[08:40:29 INFO]: Modules -> 57 enabled 1 disabled: tablist
[08:40:29 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Teleport:
    # Players need to have cmi.safeteleport permision node to be placed in a safe location when teleporting to target location
    # When true then while checking for safe location, we will try to determin it going down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: false
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 5
    # When this set to true each time player teleports to any destination he will be teleported to spawn point
    # This is to prevent from people knowing to which direction you have teleported too
    # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
    ToSpawnBefore: false
    # Set to true if you want to use tp commands as /cmi tp [WhoYouWantToTeleport] [WhereToTeleport] when its false, its /cmi tp [whereToTeleport] [WhoYouWantToTeleport]
    SwitchPlaces: true
    CurrentLoc:
      # Applies for tpa, tpahere and tpaall only
      # If set to true then player will be teleported to current player position after accepting teleport request
      # If set to false then player will be teleported to player at which teleport request was issued
      tpa: true
      # Applies for tpahere only
      tpahere: true
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 50
    # Defines time in seconds for accepting tpa or tpahere requests
    TpaTime: 60
    # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
    TpaWarmup: 0
    # Defines if player can move when tpa or tpahere is being accepted
    TpaMove: false
    # Defines time in seconds for blocking player teleport offers after denying their request
    TpaBlock: 120
    # Defines time in seconds for bypassing prevented teleportation to unsafe location
    TpBypass: 15
    # When set to true adds accept and deny buttons when sending tpa or tpahere requests
    DenyConfirm: true
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in his inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5





WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: true
  showBossBarInfo: true
  List:
  - cmi tp :5:false
  - cmi back:3:true
  - cmi warp :3:true
  - cmi home :3:true
  - cmi tpaccept:3:false
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
