### ISSUE TITLE
Vanish got half disbled sometimes on relog

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7783]
### Description of Issue

When a vanished player relogs sometimes his vanished status got half disabled

He does not see in the bossbar anymore that he is vanished but still is shown in tablist as vanished if your using the vanish symbol placeholder there.

I checked twice that vanish should not get disabled on relog in the vanisheditor.

![Snag_10c4eb4](https://user-images.githubusercontent.com/12080017/232600079-45573056-5ebe-4ed1-a307-874a2906437b.png)  Here you see CMIs tablist still thinks im vanished because i logged off in vanish state

![Snag_10cff09](https://user-images.githubusercontent.com/12080017/232600233-a0fc73d1-c223-4851-a610-521e3d535b1f.png)
Here you see the bossbar that normaly should show "Your vanished" does not apear. Also i asked some players about if they can se me? They aggrees and where able to see me.

To fix the issues i need to disabled vanishmode and reenable it after.
![Snag_10e55a0](https://user-images.githubusercontent.com/12080017/232600548-28013daa-923e-4f95-8ce1-92609ddad523.png)
In this state they cant se me.

Sometimes when i relog the vanish state stay active but sometimes it got half disabled on relog.
Then CMI still thinks im vanished (Vanish AFK-Symbol Placeholder) but The bossbar is not there + the players can see me

### Version Information
![Snag_1100eba](https://user-images.githubusercontent.com/12080017/232600923-f56ffe2f-9c0f-41ba-9eaf-927b29ff6830.png)

### Errors

```shell
non in console - just the issue wrote in description
```

### Relevant Config Sections

```yaml
# This will not have any effect if player already edited his options with /cmi options command
    Defaults:
      visibleHolograms: true
      shiftSignEdit: false
      totemBossBar: true
      bassBarCompass: true
      tagSound: true
      # !Strongly not recommended to be enabled!
      chatSpy: false
      # !Strongly not recommended to be enabled!
      cmdSpy: false
      # !Strongly not recommended to be enabled!
      signSpy: false
      acceptingPM: true
      acceptingTPA: true
      acceptingMoney: true
      chatbubble: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
