### ISSUE TITLE
Reddust Particle Size Not Saving (Portals Module)

### ISSUE THREAD

**Issue by EnderGamingFilms** [Zrips/CMI#7791]
### Description of Issue

Portal particles of type `reddust` do not save particle size. All portals will keep color but will reset particle size to 1 on server reload/restart even if running `/cmi saveall`.

FYI: I have not tested this particle in any other portion of CMI (idk if you even could) I have just noticed this for all of my portals on all my servers using reddust as different sizes.

### Version Information

```shell
CMI: 9.5.0.7
CMILib: 1.2.4.1
Server: Paper-1.19.2-R0.1-SNAPSHOT
```

### Errors

```shell
There are no errors in console.
```

### Relevant Config Sections

```yaml
neportal:
    Loc: 28.0:64.0:-30.0:30.0:64.0:-28.0
    enabled: true
    effect: Reddust
    color: 16711680
    showParticles: true
    Tp: Resurgence;6411.49;101.0;-5360.49;179.78;3.14
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 64
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - cmi sound entity_ghast_shoot [playerName] -v:0.5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
