### ISSUE TITLE
own /help sometimes doesnt show correct tab - Restart fixes it until it happens aggain

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7793]
### Description of Issue

a own created /help sometimes or after some random time just shows /help ?
The only way i found to solve this issue was restarting the server each time it happens.

![Snag_174abcf](https://user-images.githubusercontent.com/12080017/233221823-43c40d20-2882-4dbb-bcb9-c9a5f3551583.png)

### Version Information
![Snag_17422d8](https://user-images.githubusercontent.com/12080017/233221758-b7a933ef-7d72-4254-97a8-f634eb452efa.png)

### Errors
```shell
read issue description
```

### Relevant Config Sections
CustomAlias File
```yaml


#
# Edit custom variables in game if possible
# Some extra variables can be used, like [playerName] will insert senders name automatically
# All global variables should work, you can find full list in locale file
# You can add delay between commands by inserting line like
# delay! 5
# This will delay next commands by defines time in seconds
# If command is shortened and you need to provide some changing variables like target player name you need to define what and where it should be placed
# Example: /cmi heal Zrips 
# Can be shortened with custom alias to something like /h zrips by using alias command like
# cmi heal $1
# If you need to add more than one variable, use $1- format. Number represents variable place when used in alias command
# Example: cmi tppos $1-
# In case you want to print out help page if player enters wrong subcommand, use ? in alias
# Example: ca ?
# In this case if player performs /ca wrongsub or /ca anotherwrong
# Commands under this alias will get executed. Exelent way to show help page and correct usage if needed

CustomAlias:
  help home:
    Cmds:
    - asConsole! cmi ctext home [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help menü:
    Cmds:
    - asConsole! cmi ctext menue [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help zonen:
    Cmds:
    - asConsole! cmi ctext zonen [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  zonen:
    Cmds:
    - asConsole! cmi ctext zonen [playerName]
    Tab: false
    CustomTabs:
    - ''
  help limits:
    Cmds:
    - asConsole! cmi ctext limits [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  limits:
    Cmds:
    - asConsole! cmi ctext limits [playerName]
    Tab: false
    CustomTabs:
    - ''
  help kompass:
    Cmds:
    - asConsole! cmi ctext kompass [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  kompass:
    Cmds:
    - asConsole! cmi ctext kompass [playerName]
    Tab: false
    CustomTabs:
    - ''
  help jobs:
    Cmds:
    - asConsole! cmi ctext jobs [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help geld:
    Cmds:
    - asConsole! cmi ctext geld [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help discord:
    Cmds:
    - asConsole! cmi ctext discord [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  discord:
    Cmds:
    - asConsole! cmi ctext discord [playerName]
    Tab: false
    CustomTabs:
    - ''
  help köpfe:
    Cmds:
    - asConsole! cmi ctext koepfe [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  köpfe:
    Cmds:
    - asConsole! cmi ctext koepfe [playerName]
    Tab: false
    CustomTabs:
    - ''
  help lululandaufgaben:
    Cmds:
    - asConsole! cmi ctext lululandaufgaben [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  lululandaufgaben:
    Cmds:
    - asConsole! cmi ctext lululandaufgaben [playerName]
    Tab: false
    CustomTabs:
    - ''
  help weltkarte:
    Cmds:
    - asConsole! cmi ctext weltkarte [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  weltkarte:
    Cmds:
    - asConsole! cmi ctext weltkarte [playerName]
    Tab: false
    CustomTabs:
    - ''
  help rezepte:
    Cmds:
    - asConsole! cmi ctext rezepte [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help regeln:
    Cmds:
    - asConsole! cmi ctext regeln [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help ticket:
    Cmds:
    - asConsole! cmi ctext ticket [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help smilie:
    Cmds:
    - asConsole! cmi ctext smilie [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  smilie:
    Cmds:
    - asConsole! cmi ctext smilie [playerName]
    Tab: false
    CustomTabs:
    - ''
  help spawnnavigator:
    Cmds:
    - asConsole! cmi ctext spawnnavigator [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  spawnnavigator:
    Cmds:
    - asConsole! cmi ctext spawnnavigator [playerName]
    Tab: false
    CustomTabs:
    - ''
  navi:
    Cmds:
    - asConsole! cmi ctext spawnnavigator [playerName]
    Tab: false
    CustomTabs:
    - ''
  help chat:
    Cmds:
    - asConsole! cmi ctext chat [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  help luluwiki:
    Cmds:
    - asConsole! cmi ctext luluwiki [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  luluwiki:
    Cmds:
    - asConsole! cmi ctext luluwiki [playerName]
    Tab: false
    CustomTabs:
    - ''
  help wiki:
    Cmds:
    - asConsole! cmi ctext luluwiki [playerName]
    Tab: false
    CustomTabs:
    - ''
  wiki:
    Cmds:
    - asConsole! cmi ctext luluwiki [playerName]
    Tab: false
    CustomTabs:
    - ''
  help vote:
    Cmds:
    - asConsole! cmi ctext vote [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  vote:
    Cmds:
    - asConsole! cmi ctext vote [playerName]
    Tab: false
    CustomTabs:
    - ''
  help news:
    Cmds:
    - asConsole! cmi ctext news [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
  news:
    Cmds:
    - asConsole! cmi ctext news [playerName]
    Tab: false
    CustomTabs:
    - ''
  help ?:
    Cmds:
    - asConsole! cmi ctext help [playerName]
    Tab: true
    CustomTabs:
    - chat,discord,geld,home,jobs,kompass,köpfe,limits,lululandaufgaben,luluwiki,menü,news,regeln,rezepte,smilie,spawnnavigator,ticket,vote,weltkarte,wiki,zonen
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
