### ISSUE TITLE
Custom Alias Check issue

### ISSUE THREAD

**Issue by DuneSciFye** [Zrips/CMI#7794]
### Description of Issue

When using a check: in custom alias, and you check for metaint to equal a number, it doesn't work some times.

### Version Information

```shell
[Thu 20:54:06 INFO ] --------------------------------------------------
  [Thu 20:54:06 INFO ] CMI: 9.5.0.8 SqLite
  [Thu 20:54:06 INFO ] CMILib: 1.2.5.3 
  [Thu 20:54:06 INFO ] Server: Purpur 1.19.3-R0.1-SNAPSHOT
  [Thu 20:54:06 INFO ] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
  [Thu 20:54:06 INFO ] Modules -> 55 enabled 3 disabled: cuffed, tablist, votifier
  [Thu 20:54:06 INFO ] --------------------------------------------------
```

### Relevant Config Sections

```yaml
'hat':
    Cmds:
    - check:%cmi_user_metaint_hat%==1~! bperm:cmi.command.hat! asplayer! cmi hat
    - asConsole! cmi msg [playerName] !&cYou needto have &6VIP+ &cor above to use &e/hat&c!
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
