### ISSUE TITLE
colored Colorchat broke in combine with Chatfilter..

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7798]
### Description of Issue

When an Chatfilter replacement is triggert this breaks gradient chat format

![Snag_15f1a91](https://user-images.githubusercontent.com/12080017/233812569-e8d1fa89-1444-455c-85f9-3fe552cca429.png)
First one is without Chatfilter last one with a smilie set by the chat filter.

### Version Information
![Snag_15f0dcf](https://user-images.githubusercontent.com/12080017/233812567-91562d8f-f3f5-4c1f-bc23-1c0bc472bf00.png)

### Relevant Config Sections

```yaml
###Chat.yml - player needs cmi.chatmessagegroup.1
  GroupMessageFormat:
    '1': '{#thunderbird>}{message}{#malachite<>}{message}{#persianblue<}'


###Chatfilter.yml
    smile1:
      Enabled: true
      Group: emote
      InformConsole: false
      Regex:
      - \;\-D
      - \;-\)
      - \;\-P
      - \;\D
      - \;\)
      - \;P
      ReplaceWith: '&e☺&f'
      BlockType: none
      includePrivateMessages: true
      msgToStaff: ''
      Commands: []
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
