### ISSUE TITLE
Request: /pay command

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#78]
There does not seem to be a /pay command, so how do players send money to and from each other?

**Comment by 0xC1A551C** [comment]
Also the ability to switch the $ sign from behind 1000$ to the front $1000

**Comment by LogGits** [comment]
> There does not seem to be a /pay command, so how do players send money to and from each other?

`/cmi money pay [playername] [amount]`

> Also the ability to switch the $ sign from behind 1000$ to the front $1000

in Locale_EN.yml change your "currencyPlacing" to this:
```yaml
econ:
  disabled: '&cCan''t use this command while economy support is disabled'
  currencyPlacing: '[symbol][money]' #### <- make your line like this
  noMoney: '&cNot enough money in balance'
```
