### ISSUE TITLE
&u in Hologramms doesnt work.. and § needs to be used instead of &,,,

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7805]
### Description of Issue

Here an example Hologram
when i try to use §u the color allways stays white. i cant use the & for colors in holograms because then i get a big error because i used &?
```
SpawnStatsHologrammNorth:
  Loc: world;-84.5;67.5;267.5
  Interval: 3.0
  LOSInterval: 3.0
  PageInterval: 0.0
  ShowParticles: true
  HoverParticles:
    ShowHover: true
    Count: 1
  Range: 4
  RangeExtra: 4
  Interactable: true
  NewMethod: false
  Commands:
  - '!leftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!rightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  - '!shiftleftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!shiftrightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  Lines:
  - §u§lDie besten Partygamer
  - §f1. §e%ajlb_lb_partygames_wins_1_alltime_name% §f(§e%ajlb_lb_partygames_wins_1_alltime_value% wins§f)
  - '!nextpage!'
  - §u§lDie besten Roulettespieler
  - §f1. §e%ajlb_lb_roulette_winnings_1_alltime_name% §f(§e%ajlb_lb_roulette_winnings_1_alltime_value%
  - '!nextpage!'
```

![Snag_79b77c](https://user-images.githubusercontent.com/12080017/234361813-cb41c3c0-8dfd-45ff-882d-5650145c9ab7.png)
![Snag_79ca19](https://user-images.githubusercontent.com/12080017/234361835-772d648c-01f1-44af-8196-aacf270d8a64.png)

### Version Information
![Snag_7c2530](https://user-images.githubusercontent.com/12080017/234362448-3e4d20fb-b339-4907-80ce-054e724b0e63.png)

### Errors

```shell
see description
Error is shown in console only come when &c is used instead of §c
```

### Relevant Config Sections

```yaml
###Holograms.yml

SpawnStatsHologrammNorth:
  Loc: world;-84.5;67.5;267.5
  Interval: 3.0
  LOSInterval: 3.0
  PageInterval: 0.0
  ShowParticles: true
  HoverParticles:
    ShowHover: true
    Count: 1
  Range: 4
  RangeExtra: 4
  Interactable: true
  NewMethod: false
  Commands:
  - '!leftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!rightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  - '!shiftleftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!shiftrightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  Lines:
  - §u§lDie besten Partygamer
  - §f1. §e%ajlb_lb_partygames_wins_1_alltime_name% §f(§e%ajlb_lb_partygames_wins_1_alltime_value% wins§f)
  - '!nextpage!'
  - §u§lDie besten Roulettespieler
  - §f1. §e%ajlb_lb_roulette_winnings_1_alltime_name% §f(§e%ajlb_lb_roulette_winnings_1_alltime_value%
  - '!nextpage!'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
