### ISSUE TITLE
-s is not working for head command when executed from console

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7827]
### Description of Issue

-s is not working for head command when executed from console or asConsole! in a custom alias.

![Snag_101b64d](https://user-images.githubusercontent.com/12080017/236707460-60a991d6-95bd-4e8a-bded-0bd8d2a286c1.png)
![Snag_102f20a](https://user-images.githubusercontent.com/12080017/236707499-bc0924a7-c4cb-4551-b1d4-7a0e5a247dc8.png)

### Version Information
![Snag_fff9c9](https://user-images.githubusercontent.com/12080017/236707417-95873554-784d-4aad-913e-87458a47d8e2.png)

### Errors
```shell
none
```

### Relevant Config Sections

```yaml
CustomAlias:
  head:
    Cmds:
    - cooldown:15?#! check:$2<=10! asConsole! cmi head $1 [playerName] $2 -s
    - check:$2>10! msg! [playerName] &c Sorry man but you cant have more then 10 at once
    Perm: true
    Tab: true
    CustomTabs:
    - '[playerName], 1,2,3,4,5,6,7,8,9,10'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
