### ISSUE TITLE
custom recipe issue

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#7836]
### Description of Issue

I have unlocked the custom recipe.
I try to use the recipe from the book, it only shows the materials that I need but do not allow me to craft.
(red background color)
However, I have enough materials in my inventory.
I need to put those materials into the crafting table by myself each time.

The first picture shows that I cannot use the recipe from the book when I have enough materials.
![image](https://github.com/Zrips/CMI/assets/83176041/14fe2a0a-6824-4ed9-ae15-eacb85ea6be9)

The second picture shows that I need to put those materials into the crafting table by myself without using the recipe from the book.
![image](https://github.com/Zrips/CMI/assets/83176041/168a66ab-5941-44f0-9683-256788829c1e)

### Version Information

```shell
CMI: 9.5.0.9 SqLite
CMILib: 1.2.5.3 
Server: Purpur 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled CMI Chat: Disabled 
Modules -> 57 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
Recipes.yml

CRecipes:
  10fd9908-31d1-3a08-b686-6b2e82957dd3:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: ITEM_FRAME
      amount: 8
      meta:
        ==: ItemMeta
        meta-type: ENTITY_TAG
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"隱形物品展示框"}],"text":""}'
        internal: H4sIAAAAAAAA/+NiYGBk4MzMK8sszkzKSWVkAACKqLFkEQAAAA==
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '1':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '4':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: SPLASH_POTION
          meta:
            ==: ItemMeta
            meta-type: POTION
            potion-type: minecraft:long_invisibility
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '7':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: ITEM_FRAME
        byItem: true
  e728a7fb-6a35-3a1e-9cf8-70a8cc8f6952:
    Type: Shaped
    Result:
      ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: GLOW_ITEM_FRAME
      amount: 8
      meta:
        ==: ItemMeta
        meta-type: ENTITY_TAG
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"螢光物品隱形展示框"}],"text":""}'
        internal: H4sIAAAAAAAA/+NiYGBk4MzMK8sszkzKSWVkAACKqLFkEQAAAA==
    Recipe:
      '0':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '1':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '2':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '3':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '4':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: SPLASH_POTION
          meta:
            ==: ItemMeta
            meta-type: POTION
            potion-type: minecraft:long_invisibility
        byItem: true
      '5':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '6':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '7':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
      '8':
        item:
          ==: org.bukkit.inventory.ItemStack
          v: 3218
          type: GLOW_ITEM_FRAME
        byItem: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
