### ISSUE TITLE
Alias Command + MoneyCost + Cooldown + Bug.

### ISSUE THREAD

**Issue by ItzASecret** [Zrips/CMI#7850]
### Description of Issue

Using a custom alias command that takes money, and putting the command in the alias on a cooldown causes the user to get the money taken from them even if the command was not activated due to the cooldown.

### Version Information

```shell
20.05 01:45:41 [Server] [INFO] --------------------------------------------------
20.05 01:45:41 [Server] [INFO] CMI: 9.5.1.0 SqLite-> 9.5.1.1
20.05 01:45:41 [Server] [INFO] CMILib: 1.2.5.3 -> 1.2.5.4
20.05 01:45:41 [Server] [INFO] Server: Paper("bcd8dc2") 1.19.4-R0.1-SNAPSHOT
20.05 01:45:41 [Server] [INFO] CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
20.05 01:45:41 [Server] [INFO] Modules -> 57 enabled 1 disabled: votifier
20.05 01:45:41 [Server] [INFO] --------------------------------------------------
```

### Relevant Config Sections

```yaml
In Alias command file.
  world:
    Tab: true
    Cmds:
    - bperm:cmi.command.rt! moneycost:100!  rt [playerName] world
    
    Cooldown list in config.yml
    
      List:
  - cmi home :10
  - cmi spawn:10
  - cmi rt:60
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
