### ISSUE TITLE
Warps with multiple locations as respawn point - Doesn't use locations

### ISSUE THREAD

**Issue by Mikebbe** [Zrips/CMI#7869]
### Description of Issue

Hey there!
I'm experiencing some unexpected behavior from the warps when using them as a respawn point.

I have a warp set with multiple locations, and when using /warp <name> i'll get teleported to one of these locations at random
However if i die, i'll always get teleported to the main location

Heres a few pictures as to how the warp is set up:
![image](https://github.com/Zrips/CMI/assets/55026250/3c143e9d-9326-4519-94ff-2a69b225eeef)
![image](https://github.com/Zrips/CMI/assets/55026250/dd9f34e8-6e7e-40a1-9bd6-c828a4acde08)
![image](https://github.com/Zrips/CMI/assets/55026250/e5d3a003-76ad-4b59-9919-33c7f9d7103f)

### Version Information

```shell
CMI: 9.5.1.3 BungeeCord CMIB  SqLite
CMILib: 1.2.5.5 
Server: Purpur 1.19.4-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 49 enabled 9 disabled: spawnerProximity, worldLimitsElytra, tablist, votifier, headDrop, noTarget, spawnerCharge, vanish, bossBarCompass
```

### Relevant Config Sections

```yaml
#####Config.yml#####
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  # Max 60 seconds
  Immortality: 3
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: anchor, bedLocation, spawn, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # anchor is location defined by interacting with respawn anchor. This in general will only apply when you die in nether world, otherwise bed location is used
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - anchor
    - bedLocation
    - warp!Hospital
    - spawn
    - worldSpawn
  # Defines respawn order for defines worlds
  # Set respawn priority to [] or to random respawn criteria if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    someWorld:
    - anchor
    - bedLocation
    - worldSpawn


##### Warps.yml #####
Hospital:
  Location: spawn;-48.5;103.0;-60.5;162.47;-1.65
  sLocs:
  - spawn;-47.5;103.0;-67.5;89.87;0.45
  - spawn;-52.5;103.0;-60.5;132.92;1.19
  - spawn;-59.5;103.0;-66.5;-122.52;-0.45
  - spawn;-55.5;103.0;-74.5;-32.22;-0.9
  Creator: 8ef68116-cace-4acf-b2e0-3cc9d53c7c70
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
