### ISSUE TITLE
Mirror Feature does not properly apply durability loss

### ISSUE THREAD

**Issue by Mareron** [Zrips/CMI#7870]
### Description of Issue

Breaking Blocks with mirror mode active breaks two blocks but only reduces durability by one.

There's also a bit of an issue with mirror mode being usable for what could be described as mining duplication, where instead of mirror building it's used for faster mining, could there maybe be a setting to disable mirror mode breaking?

### Version Information

```shell
CMI 9.5.1.3
CMILib: 1.2.5.5
Server: Arclight 1.16.5
```

### Errors

```shell
No errors in console
```

### Relevant Config Sections

```yaml
Mirror:
  # Defines how far in blocks from mirror center you can build
  # This is mainly to protect from forgeting to turn off mirror and starting to build on different side of map
  MaxRange: 50
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
