### ISSUE TITLE
Player FlightCharge can't over 1000

### ISSUE THREAD

**Issue by SeanWalk** [Zrips/CMI#790]
**Description of issue or feature request: Player FlightCharge can't over 1000**

player charge only can have 1000 block at all

the more charge money will be take but no over 1000 charge get

like this
[https://github.com/Zrips/CMI/issues/658](url)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
FlightCharge:
  # Do you want to enable flight charge feature
  Enabled: true
  # When set to true, each time player gets flight charge or relogs, his fly mode will be toggled on
  # If set to false, then players will have to manualy turn on flight with /cmi flyc
  EnabledByDefault: false
  # When set to true, in event of player changing his game mode from survival/adventure to creative/spectator his flight charge  mode will get disabled
  # Same applies when changind game mode from creative/spectator to survival/adventure
  AutoSwitch: false
  # How much it costs for one recharge point in exp points. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  ExpRechargeCost: 1.0
  # How much it costs for one recharge point. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  MoneyRechargeCost: 1.0
  # Defines maximum amount of charge player can have
  # One charge is one traveled block while flying
  # if player dosent move, then one charge for each second while hovering
  MaxChargeLevel: 10000
  # Defines multiplier when player doesnt move but is hovering. For each second player hovers.
  # Set to 0 to disable
  DeductOnIdling: 1
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penealty from jumping from clifs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 2
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: true
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false
#####################################
```

**Cmi Version (using`/cmi version`):** 8.0.7.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13
