### ISSUE TITLE
The total condition of the skill plug-in cannot be used!

### ISSUE THREAD

**Issue by wlm1455925277** [Zrips/CMI#7961]
### Description of Issue

The total condition of the skill plug-in cannot be used!

### Version Information

```shell
[02:53:28 INFO]: --------------------------------------------------
[02:53:28 INFO]: CMI 插件版本: 9.6.0.6 BungeeCord  SqLite-> 9.6.1.1
[02:53:28 INFO]: CMILib: 1.3.1.0 -> 1.4.0.1
[02:53:28 INFO]: Server: Purpur 1.20.1-R0.1-SNAPSHOT
[02:53:28 INFO]: CMI economy: 启用 Vault: 1.7.3-CMI CMI Chat: 启用
[02:53:28 INFO]: Modules -> 56 enabled 2 disabled: tablist, votifier
[02:53:28 INFO]: --------------------------------------------------
```

### Errors

```shell
新手1:
  Enabled: true
  DisplayName: '&e新手'
  McMMORequirement:
  - Power:999
  StatsRequirements:
  - MonsterKills:30
  - Travel:300
  - PlayTime:3600
  - FishCaught:20
  - BlocksMined:500
  - BlocksPlaced:250
  - ItemCrafts:30
  - ItemsUsed:1000
  - MoneyCost:2000
  - ExpCost:1000
  AutoRankup: false
  NextRanks:
  - 新手2
  Commands:
  - lp user [playerDisplayName] parent set xr1
```

### Relevant Config Sections

```yaml
新手1:
  Enabled: true
  DisplayName: '&e新手'
  McMMORequirement:
  - Power:999
  StatsRequirements:
  - MonsterKills:30
  - Travel:300
  - PlayTime:3600
  - FishCaught:20
  - BlocksMined:500
  - BlocksPlaced:250
  - ItemCrafts:30
  - ItemsUsed:1000
  - MoneyCost:2000
  - ExpCost:1000
  AutoRankup: false
  NextRanks:
  - 新手2
  Commands:
  - lp user [playerDisplayName] parent set xr1
```

### Relevant Plugins

[02:54:33 INFO]: [技能插件] 您正在使用 Aurelium Skills版本 Beta 1.3.21. 最新版本是 Beta 1.3.21

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
