### ISSUE TITLE
/helpop won't show the "offline" message if there are staff members in vanish.

### ISSUE THREAD

**Issue by PovilasLT** [Zrips/CMI#7970]
### Description of Issue

When there are no staff members online, /helpop sends a special message informing players about the absence of online staff. However, if there are any staff members who have vanished, this message isn't being sent, allowing players to detect staff that are currently vanished.

### Version Information

```shell
9.6.1.3
```

### Relevant Config Sections

```yaml
helpop:
    # When set to true player will not see his sent message to helpop, but rather predefined message informing that his question have been sent to online staff
    feedbackMessage: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
