### ISSUE TITLE
After teleport, players can still get hurt by falling down when setting Invulnerability: 5

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#8010]
### Description of Issue

Time in seconds player should be invulnerable after teleporting is set as 5.
However, player can still get hurt by falling down after teleporting in 5 seconds.
Other damage such as attcked by players/monster or void or lava is prevented in 5 seconds.

### Version Information

```shell
CMI 9.6.1.3
CMILib 1.4.0.1
```

### Relevant Config Sections

```yaml
Teleport:
    # Players need to have cmi.safeteleport permision node to be placed in a safe location when teleporting to target location
    # When true then while checking for safe location, we will try to determin it going down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: true
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
