### ISSUE TITLE
Hologram V3 scale-height

### ISSUE THREAD

**Issue by TheLittle0ne** [Zrips/CMI#8013]
### Description of Issue

Hey,
when I perform scaling in the Hologram GUI and restart the server, the "Scale-Height" in the GUI is reset to 1.0. However, "Scale-Width" is not reset.
Even when the server is shut down, and I perform scaling in the config, the hologram automatically sets in the GUI the Scale-Height to 1.0 after the restart. But the scaling I had made remains in the config.

### Version Information

```shell
--------------------------------------------------
CMI Plugin Version: 9.6.2.0 BungeeCord CMIB  MySQL
CMILib: 1.4.0.2 
Server: Paper(95) 1.20.1-R0.1-SNAPSHOT
CMI economy: Aktiviert Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Deaktiviert 
Modules -> 56 enabled 2 disabled: votifier, vanish
--------------------------------------------------
```

### Relevant Config Sections

```yaml
Minigamesspawn:
  Loc: world;-243.33;68.73;3.75
  HoverParticles:
    Count: 1
  Range: 8
  RangeExtra: 32
  Spacing: 0.24
  NewDisplay: true
  ND:
    Bill: FIXED
    Align: CENTER
    TAlpha: 230
    Shadow: false
    Yaw: 45
    Pitch: 0
    Double: true
    BColor: Black
    BAlpha: 125
    ScaleW: 11.09
    ScaleH: 11.09
  Lines:
  - §b§lMinigames
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
