### ISSUE TITLE
New hologram system bug/thing

### ISSUE THREAD

**Issue by Adreez** [Zrips/CMI#8035]
### Description of Issue

Hi 👋 I don't know if it is a bug or it is intended behavior.

So the best way I was able to duplicate the issue was:
1. Create a hologram with the new way. 
2. Set some text and set `Range:` to `1`
3. Do /cmi reload
4. If you are outside the area and you are trying to move the hologram trough menu nothing happens until you re-enter the area.

It is really weird thing that took me a while to realize what's wrong because it was working for a while fine, but then I was unable to move the hologram.

**Expected behavior:**
- To be able to change the hologram position even if I'm outside the range. 

(On a wish I can make a video with it 😅)

### Version Information

```shell
[11:11:45 INFO]: --------------------------------------------------
[11:11:45 INFO]: CMI plugin version: 9.6.2.1 BungeeCord CMIB  SqLite
[11:11:45 INFO]: CMILib: 1.4.0.3 
[11:11:45 INFO]: Server: Purpur 1.20.1-R0.1-SNAPSHOT
[11:11:45 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[11:11:45 INFO]: Modules -> 56 enabled 2 disabled: tablist, votifier
[11:11:45 INFO]: --------------------------------------------------
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
store:
  Loc: newlobby;28.9;85.7;-1112.5
  HoverParticles:
    Count: 1
  Range: 1
  RangeExtra: 64
  Spacing: 0.24
  NewDisplay: true
  ND:
    Bill: FIXED
    Align: CENTER
    TAlpha: 230
    Shadow: true
    Yaw: 90
    Pitch: 5
    Double: true
    BColor: '{#Black}'
    BAlpha: 0
    ScaleW: 1.9
    ScaleH: 1.9
    SL: 15
    BL: 15
  Lines:
  - '{#f2ff00>}&lsᴛᴏʀᴇ{#ebff7a<}'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
