### ISSUE TITLE
/attachcommand does not work

### ISSUE THREAD

**Issue by 1337kamillll** [Zrips/CMI#8037]
### Description of Issue

/attachcommand does not work properly with asFakeOp!
![image](https://github.com/Zrips/CMI/assets/141153755/87bbf561-985f-48c5-893f-17aff5ca9465)
![image](https://github.com/Zrips/CMI/assets/141153755/32aaa8e2-db9e-4f4f-a67c-c85867592b70)

### Version Information

```shell
CMI: 9.6.2.1 SqLite
CMILib: 1.4.0.3 
Serwer: Purpur 1.16.5-R0.1-SNAPSHOT
CMI ekonomia: Włączone CMI Chat: Włączone
```

### Errors

```shell
Tried to use asFakeOp! specialized command variable but event got canceled
```

### Relevant Config Sections

```yaml
Optimizations:
  # When disabled we wont try to deop fake operator on server starup or unload while at same time disabling asFakeOp! specialized command usage
  UseFakeOperator: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
