### ISSUE TITLE
Luckperms prefix rgb/gradient chat formatting

### ISSUE THREAD

**Issue by Faobi69** [Zrips/CMI#8039]
### Description of Issue

Hello, activating the chat formatting of CMI and also the supports for rgb colors in CMILib the prefix rgb (gradient) of luckperms is displayed in chat but not in console (in console I see COPPER in white without rgb colors)

my console is not monochrome and the option in config.yml MonochromeConsole: is on false

This is the prefix of Luckperms: &#e5846e&lC&#d77c67&lO&#c87460&lP&#ba6b59&lP&#ab6352&lE&#9d5b4b&lR

### Version Information

```shell
Versione di CMI: 9.6.2.3 BungeeCord  MySQL-> 9.6.2.1
CMILib: 1.4.0.3 
Server: Paper(100) 1.20.1-R0.1-SNAPSHOT
CMI economy: Disabilitato CMI Chat: Abilitato 
Modules -> 53 enabled 5 disabled: tablist, ranks, votifier, moneyCheque, headDrop
```

### Relevant Config Sections

```yaml
# ATTENTION! Dont use gradient colors for {message} variable, if you want to apply gradient for it, utilize GeneralMessageFormat section
  GeneralFormat: '%luckperms_prefix%%cmi_user_display_name% &8» %luckperms_suffix%{message}'
  # Will define message format itself, this allows to have gradients in messages
  # It NEEDS to contain {message} otherwise we will ignore this setup
  # For 1.16+ servers you can use color gradients like '{#b3a28f>}{message}{#d7b8e6<}'
  # You can have more than 2 colors in gradient. To define it repeat {message} variable. For example '{#b3a28f>}{message}{#5c6999<>}{message}{#d7b8e6<}'
  # Use %cmi_user_chatcolor% to add players choosen chat color
  GeneralMessageFormat: '{message}'
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
