### ISSUE TITLE
Add bossbar in joinServer event

### ISSUE THREAD

**Issue by Ligzsir** [Zrips/CMI#8070]
### Description of Issue

I added bossbarmsg in EventCommands and set refresh time. bossbarmsg in EventCommands doesn't refresh the placeholder automatically when I update it (placeholder is money)

### Version Information

```shell
[22:47:38 INFO]: CMI: 9.6.2.3 BungeeCord  SqLite
[22:47:38 INFO]: CMILib: 1.4.1.0 
[22:47:38 INFO]: Paper(108) 1.20.1-R0.1-SNAPSHOT
```

### Relevant Config Sections

```yaml
joinServer:
  Enabled: true
  Commands:
  - cmi bossbarmsg [playerName] %img_position%主城  %img_money%%vault_eco_balance_formatted%
    -t:-1 -s:1 -c:white -a:2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
