### ISSUE TITLE
Hologramms flickering throw glass

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8104]
### Description of Issue

Well if you have a hologramm behind a glaswall you see a big flicker

https://streamable.com/ictub3

### Version Information

![Snag_148b3e3](https://github.com/Zrips/CMI/assets/12080017/82dfb461-973e-4a86-a7b4-94beeeb3128f)

### Errors
```shell
visual error
```

### Relevant Config Sections

Not a config but hologram from Holograms.yml
```yaml
SpawnStatsHologrammWest2:
  Loc: world;31.0;68.0;298.95
  Interval: 1.0
  LOSInterval: 0.1
  ShowParticles: false
  PageInterval: 0.1
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 8
  RangeExtra: 8
  Spacing: 0.24
  NewMethod: false
  NewDisplay: true
  ND:
    Bill: FIXED
    Align: LEFT
    TAlpha: 230
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 255
    SL: -1
    BL: -1
  Lines:
  - '&c&l &c&l &c&l &u&lDie eifrigsten Jober'
  - '&f&l '
  - '&f&l1. &e%ajlb_lb_jobs_total_levels_1_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_1_alltime_value% lvl&f&l)'
  - '&f&l2. &6%ajlb_lb_jobs_total_levels_2_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_2_alltime_value% lvl&f&l)'
  - '&f&l3. &e%ajlb_lb_jobs_total_levels_3_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_3_alltime_value% lvl&f&l)'
  - '&f&l4. &6%ajlb_lb_jobs_total_levels_4_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_4_alltime_value% lvl&f&l)'
  - '&f&l5. &e%ajlb_lb_jobs_total_levels_5_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_5_alltime_value% lvl&f&l)'
  - '&f&l6. &6%ajlb_lb_jobs_total_levels_6_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_6_alltime_value% lvl&f&l)'
  - '&f&l7. &e%ajlb_lb_jobs_total_levels_7_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_7_alltime_value% lvl&f&l)'
  - '&f&l8. &6%ajlb_lb_jobs_total_levels_8_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_8_alltime_value% lvl&f&l)'
  - '&f&l9. &e%ajlb_lb_jobs_total_levels_9_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_9_alltime_value% lvl&f&l)'
  - '&f&l10. &6%ajlb_lb_jobs_total_levels_10_alltime_name% &f&l(&e%ajlb_lb_jobs_total_levels_10_alltime_value% lvl&f&l)'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
