### ISSUE TITLE
Question about CMI Ranks and LuckPerms

### ISSUE THREAD

**Issue by chedadmin** [Zrips/CMI#815]
I've set up my CMI ranks and LuckPerms groups so that they have the same names (default, apprentice, skilled, expert and master).  How do I make it so that when a player moves up a CMI rank, they also get added to the next LuckPerms groups and therefore get extra permissions?

**Comment by Fabrimat** [comment]
You could do something like this:
```
Rank2
  Enabled: true
  DisplayName: "&2Rank3"
  DefaultRank: false
  AutoRankup: true
  NextRanks:
  - rank2
  Commands:
  - "lp user [playerName] parent remove Rank1"
  - "lp user [playerName] parent add Rank2"
  StatsRequirements:
  - "BlocksMined:10000"
```
or you can work with Luckperm's track that is simpler.
