### ISSUE TITLE
Tablist

### ISSUE THREAD

**Issue by SonnenPingu** [Zrips/CMI#8158]
### Description of Issue

The table list is no longer displayed since the update to the latest server and CMI and CMILib.

### Version Information

```shell
[Thu 20:58:11 INFO ] --------------------------------------------------
  [Thu 20:58:11 INFO ] CMI Plugin Version: 9.6.5.1 SqLite
  [Thu 20:58:11 INFO ] CMILib: 1.4.2.0 
  [Thu 20:58:11 INFO ] Server: Paper(217) 1.20.2-R0.1-SNAPSHOT
  [Thu 20:58:11 INFO ] CMI economy: Aktiviert Vault: 1.7.3-CMI CMI Chat: Aktiviert 
  [Thu 20:58:11 INFO ] Modules -> 55 enabled 4 disabled: ranks, votifier, shulkerBackpack, jail
  [Thu 20:58:11 INFO ] --------------------------------------------------
```

### Relevant Config Sections

```yaml
The Tablist.yml..
 
# To disable tablist handling visit Modules.yml file
TabList:
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 60
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  # When set to false we will not add header text to tablist
  addTabListHeader: true
  # When set to false we will not add footer text to tablist
  addTabListFooter: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In addition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    # This will define how others see players name in tab list
    PlayerName: ' %luckperms_prefix%&4 [playerDisplayName]'
    Header:
      '1':
      - '&5------------------------------------'
      - '     &6Herzlich willkommen auf'
      - '      &6Mystic Celduin'
      - '&5------------------------------------'
      - ' §eOnline &f%server_online%&7'
      - ' Maximale Spieler &f%server_max_players%'
      - '&5------------------------------------'
    Footer:
      '1':
      - '&5------------------------------------&r'
      - '  &9%player_world%'
      - ' &f%player_x%:&7%player_y%:&f%player_z%'
      - '&5------------------------------------&r'
      - '&6 Geld: &f%vault_eco_balance_formatted%'
      - '&5------------------------------------'
  useGeneralName: false
  # When this set to true, in case you dint defined PlayerName, Header or Footer in GroupFormat, then default one from GeneralFormat will be used
  useGeneralHeader: false
  useGeneralFooter: false
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  GroupFormat:
    '1':
      PlayerName: '&2{%luckperms_prefix%&r [playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
```

### Relevant Plugins

 AcceptTheRules, AdvancedRegionMarket, AutomaticBroadcast, BlueBridgeCore, BlueBridgeWG, BlueMap, BlueMapCustomSkinProvider, BlueMapDeathMarkers, BlueMapFloodgate, BlueMapOfflinePlayerMarkers [21:05:19 INFO]: ChestShop, ChestShopNotifier, ChestShopTools, Chunky, CMI, CMILib, DeathChest, DiscordSRV, FastAsyncWorldEdit, FileGUI [21:05:19 INFO]: floodgate, Geyser-Spigot, Jobs, LuckPerms, MCGBluemapEssentialsPlus, Multiverse-Core, PlaceholderAPI, SmoothTimber, spark, Spartan [21:05:19 INFO]: UltimateStatistics, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEditSUI, WorldGuard, WorldGuard, WorldGuardExtraFlags 

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
