### ISSUE TITLE
Sit bug teleporting

### ISSUE THREAD

**Issue by thunderlight411** [Zrips/CMI#816]
When a player is in /SIT mode and they want to use /warp for example they are not moved the the warp of there choise. instead they are removed from the /sit mode.

And when a user is sitting on a area with air below them they get a "empty world" like its fully filled with barrier blocks.
When you teleport to a other location the world is loaded again and they can see everything again
Example : https://i.imgur.com/dTMxHZw.png

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Animations:
  SitOnStairs: true
  StairsAsChairs: true
  SlabsAsChairs: true
  DoubleClick: false
  DoubleClickDelay: 200
```

**Cmi Version (using`/cmi version`):** 
CMI version 8.0.8.1
CMIEInjector version 1.0.2.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
