### ISSUE TITLE
SavedItems doesnt save ntb correct...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8170]
### Description of Issue

On this site i created a head
https://www.gamergeeks.net/apps/minecraft/give-command-generator/player-heads

The site created this command for me:
```
/give @p player_head{SkullOwner:{Id:[I;-123912,47658,20349,-95316],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAwYzNhYWZmMzEzZDBjMzNlYzc4MDc5MjA4NzhmN2U0YTYzYjNlOTlkM2MwZTM0MTBlMWZlYzFmNjc4NGYzYyJ9fX0="}]}},display:{Name:'[{"text":"H","italic":false,"bold":true,"color":"gold"},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"k","color":"gray"},{"text":"ü"},{"text":"r","color":"gray"},{"text":"b"},{"text":"i","color":"gray"},{"text":"s"}]',Lore:['[{"text":"","italic":false}]','[{"text":"Handelsgegenstand:","italic":false,"color":"aqua","bold":true},{"text":"","italic":false,"color":"dark_purple","bold":false}]','[{"text":"H","italic":false,"color":"gold","bold":true},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"e","color":"gray"},{"text":"v"},{"text":"e","color":"gray"},{"text":"n"},{"text":"t","color":"gray"},{"text":"2"},{"text":"0","color":"gray"},{"text":"2"},{"text":"3","color":"gray"},{"text":"","color":"dark_purple","bold":false}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"Dieser Gegenstand kann","italic":true,"color":"gray"}]','[{"text":"gesammelt und im","italic":true,"color":"gray"}]','[{"text":"Halloweenshop gegen","italic":true,"color":"gray"}]','[{"text":"einzigartige Gegenstände","italic":true,"color":"gray"}]','[{"text":"getauscht werden.","italic":true,"color":"gray"}]']}} 1
```

i created a custom alias with cmi to:
```
minecraft:give [playerName] player_head{SkullOwner:{Id:[I;-123912,47658,20349,-95316],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAwYzNhYWZmMzEzZDBjMzNlYzc4MDc5MjA4NzhmN2U0YTYzYjNlOTlkM2MwZTM0MTBlMWZlYzFmNjc4NGYzYyJ9fX0="}]}},display:{Name:'[{"text":"H","italic":false,"bold":true,"color":"gold"},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"k","color":"gray"},{"text":"ü"},{"text":"r","color":"gray"},{"text":"b"},{"text":"i","color":"gray"},{"text":"s"}]',Lore:['[{"text":"","italic":false}]','[{"text":"Handelsgegenstand:","italic":false,"color":"aqua","bold":true},{"text":"","italic":false,"color":"dark_purple","bold":false}]','[{"text":"H","italic":false,"color":"gold","bold":true},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"e","color":"gray"},{"text":"v"},{"text":"e","color":"gray"},{"text":"n"},{"text":"t","color":"gray"},{"text":"2"},{"text":"0","color":"gray"},{"text":"2"},{"text":"3","color":"gray"},{"text":"","color":"dark_purple","bold":false}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"Dieser Gegenstand kann","italic":true,"color":"gray"}]','[{"text":"gesammelt und im","italic":true,"color":"gray"}]','[{"text":"Halloweenshop gegen","italic":true,"color":"gray"}]','[{"text":"einzigartige Gegenstände","italic":true,"color":"gray"}]','[{"text":"getauscht werden.","italic":true,"color":"gray"}]']}} 1
```

after executing the Custom Alias i got my head
![Snag_b8f156](https://github.com/Zrips/CMI/assets/12080017/cb3f8a27-b758-446a-ba48-7cbe84f05a42)

i tried to save it with cmis saveditems with using the command:
**_/cmi saveditems save Halloweenkuerbis2023_**

**_Result:_** The colors and formation got saved coruppted
now it looks in cmi saveditems menue like this:
![Snag_ba3d1f](https://github.com/Zrips/CMI/assets/12080017/5818d466-05e1-4ce0-80cb-fade4128497e)

### Version Information
![Snag_ba6383](https://github.com/Zrips/CMI/assets/12080017/9ec21f09-7b3e-4913-b7c7-b8aabfbb21ba)

### Relevant Sections
The customalias i made

```
  test_test:
    Cmds:
    - minecraft:give [playerName] player_head{SkullOwner:{Id:[I;-123912,47658,20349,-95316],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjAwYzNhYWZmMzEzZDBjMzNlYzc4MDc5MjA4NzhmN2U0YTYzYjNlOTlkM2MwZTM0MTBlMWZlYzFmNjc4NGYzYyJ9fX0="}]}},display:{Name:'[{"text":"H","italic":false,"bold":true,"color":"gold"},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"k","color":"gray"},{"text":"ü"},{"text":"r","color":"gray"},{"text":"b"},{"text":"i","color":"gray"},{"text":"s"}]',Lore:['[{"text":"","italic":false}]','[{"text":"Handelsgegenstand:","italic":false,"color":"aqua","bold":true},{"text":"","italic":false,"color":"dark_purple","bold":false}]','[{"text":"H","italic":false,"color":"gold","bold":true},{"text":"a","color":"gray"},{"text":"l"},{"text":"l","color":"gray"},{"text":"o"},{"text":"w","color":"gray"},{"text":"e"},{"text":"e","color":"gray"},{"text":"n"},{"text":"e","color":"gray"},{"text":"v"},{"text":"e","color":"gray"},{"text":"n"},{"text":"t","color":"gray"},{"text":"2"},{"text":"0","color":"gray"},{"text":"2"},{"text":"3","color":"gray"},{"text":"","color":"dark_purple","bold":false}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"Dieser Gegenstand kann","italic":true,"color":"gray"}]','[{"text":"gesammelt und im","italic":true,"color":"gray"}]','[{"text":"Halloweenshop gegen","italic":true,"color":"gray"}]','[{"text":"einzigartige Gegenstände","italic":true,"color":"gray"}]','[{"text":"getauscht werden.","italic":true,"color":"gray"}]']}} 1
    Perm: true
    Tab: false
    CustomTabs:
    - ''
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
