### ISSUE TITLE
The warns will not be applied to players

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#8213]
### Description of Issue

Then i warn an player via
`/cmi warn <player> (reason)`
And check the warns with
`/cmi warnings <player>`
There no warnings will be applied to the player and no command will be performet

### Version Information

```shell
CMI: 9.6.7.2
CMILib: 1.4.2.2
```

### Relevant Config Sections

```yaml
Warnings:
  Default:
    LifeTime: 86400
    Points: 1
    DefaultReason: Regelverstoß
  Categories:
    ChatSpam:
      LifeTime: 86400
      Points: 1
      DefaultReason: ChatSpam
    Provokation:
      LifeTime: 86400
      Points: 3
      DefaultReason: Provokation
    Fremdwerbung:
      LifeTime: 86400
      Points: 3
      DefaultReason: Fremdwerbung
    Beleidigung:
      LifeTime: 86400
      Points: 3
      DefaultReason: Beleidigung
    AFK-Umgehung:
      LifeTime: 86400
      Points: 1
      DefaultReason: AFK-Umgehung
    Betrug:
      LifeTime: 86400
      Points: 15
      DefaultReason: Betrug
    Multiaccount:
      LifeTime: 86400
      Points: 50
      DefaultReason: Multiaccount
    Griefing:
      LifeTime: 86400
      Points: 15
      DefaultReason: Griefing
    Bugusing:
      LifeTime: 86400
      Points: 30
      DefaultReason: Bugusing
    Cheaten:
      LifeTime: 86400
      Points: 50
      DefaultReason: Cheaten
    Regelverstoß:
      LifeTime: 86400
      Points: 100
      DefaultReason: Regelverstoß
  Perform:
    '3':
    - cmi mute [playerName] 10m
    - cmi msg [playerName] !&cDu bist temporär gemutet für 10 Minuten.
    '10':
    - cmi kick [playerName] &cDu wurdest durch einen Regelverstoß gekickt.
    '15':
    - cmi kick [playerName] &cDu wurdest durch einen Regelverstoß gekickt.
    '20':
    - cmi tempban [playerName] 10m &cRegelverstoß.
    '30':
    - cmi tempban [playerName] 6h &cRegelverstoß.
    '50':
    - cmi ban [playerName] &cRegelverstoß
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
