### ISSUE TITLE
-s of setmotd does not work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8222]
### Description of Issue

The -s of setmodt command does not work.
i was trying to create a scheduler that changes the motd all x secounds..
but its shown in console each time what i wanted to avoid with the -s option.
The wiki said its exsting...but ifit looks like it is broken..
i asume its broken because the -s is not shown in the setmotd as a text -> so the command itself saw -s was used at the end
what normaly should result in so feedback ingame and no feedback in console.

Command used:
`cmi setmotd &f ☁&2&l__&7۩۩&2&l__&bWillkommen&2&l__&bin&f☁&bLuluLand&2&l__&7۩&2&l__&7۩۩&f☁&2&l__&1&l____&2&l__&7۩\n&2&l__&7۩&2&l__&7۩&f☁&3Viel&2&l__&3Spass&2&l__&3beim&2&l__&3Spielen&2&l__&7۩۩&f☁&7۩&2&l__&7۩۩&2&l____&f☁ -s`

Console Shows:
![image](https://github.com/Zrips/CMI/assets/12080017/deea24f7-c5f4-4dbd-8b2a-2f89fba786da)

Wiki sais:
![image](https://github.com/Zrips/CMI/assets/12080017/53b5926f-a582-4224-93cd-a41081d8acde)

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/d3226590-b2b5-4446-9808-28ea3b4cbc0a)

### Relevant Part:
The schedule from Schedules.yml:
```
SetModt:
  Enabled: true
  FeedBack: false
  Delay: 60
  Repeat: true
  Randomize: true
  Commands:
  - check:%phc_Wartungsmodus%==false! cmi setmotd &f ☁&2&l__&7۩۩&2&l__&bWillkommen&2&l__&bin&f☁&bLuluLand&2&l__&7۩&2&l__&7۩۩&f☁&2&l__&1&l____&2&l__&7۩\n&2&l__&7۩&2&l__&7۩&f☁&3Viel&2&l__&3Spass&2&l__&3beim&2&l__&3Spielen&2&l__&7۩۩&f☁&7۩&2&l__&7۩۩&2&l____&f☁ -s
  - check:%phc_Wartungsmodus%==false! cmi setmotd &f ☁&2&l__&7۩۩&2&l__&bWillkommen&2&l__&bin&f☁&bLuluLand&2&l__&7۩&2&l__&7۩۩&f☁&2&l__&1&l____&2&l__&7۩\n&2&l__&7۩&2&l__&7۩&f☁&3Viel&2&l__&3Spass&2&l__&3beim&2&l__&3Spielen&2&l__&7۩۩&f☁&7۩&2&l__&7۩۩&2&l____&f☁ -s
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
