### ISSUE TITLE
Bug with an interactive (InteractiveCommands ) sign created for selling an item

### ISSUE THREAD

**Issue by danyadanya2005** [Zrips/CMI#8225]
### Description of Issue

The problem is this. If you sell an item renamed on an anvil in a store, the item does not disappear from the player’s inventory.
https://youtu.be/JnveV4HWqs8?si=_96gh9eqIPOwPEGt

was tested even on the latest build git-Paper-260 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1865625)

You can check it yourself, create an interactive sign with something for sale. rename this item and sell it.
I'm waiting for a fix

### Version Information

```shell
[23:54:35 INFO]: --------------------------------------------------
[23:54:35 INFO]: Версия плагина CMI: 9.6.7.4 SqLite
[23:54:35 INFO]: CMILib: 1.4.2.2
[23:54:35 INFO]: Server: Purpur(2062) 1.20.1-R0.1-SNAPSHOT
[23:54:35 INFO]: CMI economy: enabled Vault: 1.7.3-b CMI Chat: enabled
[23:54:35 INFO]: Modules -> 59 enabled 0 disabled:
[23:54:35 INFO]: --------------------------------------------------

This server is running Purpur version git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6fd5f6 on HEAD)
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
InteractiveCommands.yml
sellemerald:
  Locations:
  - world;394;57;391
  Commands:
  - click:right! cooldown:1#! hasmoney:4000@! msg! [playerName] &7У вас недостаточно
    денег, чтобы купить этот товар. Ваш счет &6%cmi_user_balance_formatted%.
  - click:left! cooldown:1#! hasitem:emerald-8@! msg! [playerName] &7У вас недостаточно
    товара, чтобы продать его.
  - moneycost:4000! fromConsole! click:right! cmi give [playerName] emerald 8
  - item:emerald-8#! click:left! cmi money give [playerName] 2000

```

### Relevant Plugins

Vault-1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by danyadanya2005** [comment]
https://youtu.be/JnveV4HWqs8?si=_96gh9eqIPOwPEGt

**Comment by CloudeLecaw** [comment]
here an example of a sellbuy sign we use on our server for emeralds

> leftclick - buys one emerald
> rightclick sells one emerald
> shift-leftclick buys a stack emeralds
> shift-rightclick sells a stack emeralds

```
buysellsign:
  Locations:
  - world;1730;70;1635
  Commands:
  - click:left! cooldown:1#! hasmoney:1@! msg! [playerName] &fYou need at least a balance of &e&l1&e⛁&e&l &fto buy &2&l1 emderald&f. Your current balance is &e&l%cmi_user_balance_formatted%&f.
  - click:right! cooldown:1#! hasitem:emerald-1@! msg! [playerName] &fYou need at least &2&l1 emderald&f, to sell it for &e&l1&e⛁&f.
  - click:leftshift! cooldown:1#! hasmoney:64@! msg! [playerName] &fYou need at least a balance of &e&l64&e⛁&e&l &fto buy &2&l64 emderalds&f. Your current balance is &e&l%cmi_user_balance_formatted%&f.
  - click:rightshift! cooldown:1#! hasitem:emerald-64@! msg! [playerName] &fYou need at least &2&l64 emeralds&f, to sell them for &e&l64&e⛁&f.
  - click:left! hasmoney:1! msg! [playerName] &fYou bought &a&l1 emerald&f for &e&l1&e⛁&f.
  - click:left! moneycost:1#! cmi give [playerName] emerald 1 -s
  - click:right! hasitem:emerald-1! msg! [playerName] &fYou sold &a&l1 emerald&f for &e&l1&e⛁&f.
  - click:right! item:emerald-1#! cmi money give [playerName] 1 -s
  - click:leftshift! hasmoney:64! msg! [playerName] &fYou bought &a&l64 emderalds&f for &e&l64&e⛁&f.
  - click:leftshift! moneycost:64#! cmi give [playerName] emerald 64 -s
  - click:rightshift! hasitem:emerald-64! msg! [playerName] &fYou sold &a&l64 emeralds&f for &e&l64&e⛁&f.
  - click:rightshift! item:emerald-64#! cmi money give [playerName] 64 -s
  - delay! 0.2
  - msg! [playerName] &fYour current balance is &e&l%cmi_user_balance_formatted%&f.
  SignLines:
  - ''
  - '&2&lEmerald'
  - '&6&lB:1 | S:1'
  - ' '
  ReqPerm: false
```
