### ISSUE TITLE
Only CMI Placeholders Work With Nameplate Feature

### ISSUE THREAD

**Issue by GangPop** [Zrips/CMI#8226]
### Description of Issue

This issue seems to be easily replicable. The screenshots provided below shows exactly what I am describing. Placeholders from PAPI extensions do not parse in the nameplate. However, CMI placeholders will.
It is also worth mentioning, '/cmi placeholders parse' command will parse PAPI placeholders as expected. These PAPI placeholders also work elsewhere such as chat and tablist -- just not nameplates.

![Screenshot_404](https://github.com/Zrips/CMI/assets/88950816/1f61abb7-0002-4333-a746-d60f7ca1d324)
![Screenshot_408](https://github.com/Zrips/CMI/assets/88950816/1a29c539-9e8f-4f5a-9d43-2157ced0a822)

If necessary, you can contact me on Discord. Username: 7gp

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.7.5 SqLite
CMILib: 1.4.2.2
Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 54 enabled 5 disabled: chatBubble, votifier, afk, elytraBoost, elytraLaunch
--------------------------------------------------
```

### Relevant Config Sections

```yaml
EventCommands.yml

joinServer:
  Enabled: true
  Commands:
  - cmi nameplate [playerName] reset
  - cmi nameplate [playerName] -pref:%luckperms__prefix__element__highest%
```

### Relevant Plugins

CMI 9.6.7.5, CMILib 1.4.2.2, Vault 1.7.3-CMI, PlaceholderAPI 2.11.5, LuckPerms v5.4.106

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
