### ISSUE TITLE
Chat bubble don't work

### ISSUE THREAD

**Issue by erickterri** [Zrips/CMI#8233]
### Description of Issue

I enabled the chat bubble, but the text does not appear above the player

I attach my configuration
[CMI.zip](https://github.com/Zrips/CMI/files/13234094/CMI.zip)

### Version Information

```shell
Versión de CMI: 9.6.7.5
Base de Datos: SqLite
Versión de CMILib: 1.4.2.2 
Versión del Servidor: Paper(241) 1.20.2-R0.1-SNAPSHOT
Economía de CMI: Enabled | Vault: 1.7.3-CMI | Chat de CMI: Disabled 
Módulos activados: 58 | Módulos desactivados: 1 (votifier).
¡Archivo de Idioma traducido por C4BR3R4.es ► Versión: 23.03.20!
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
your not using cmi chat that feature is for CMI Chat

```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: false
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
```
