### ISSUE TITLE
item specialized command doesn't work with items with custom data

### ISSUE THREAD

**Issue by VictorLorian** [Zrips/CMI#8241]
### Description of Issue

After updating CMI & CMILib to the latest versions, the item specialized command no longer reacts in any way to items with custom data (made with or without ItemsAdder), nothing happens at all. Also, due to items with a space in the name, an error is thrown.

### Version Information

```shell
CMI plugin version: 9.6.7.7 Velocity CMIB MySQL
CMILib: 1.4.2.4
Server version: Paper(279) 1.20.2-R0.1-SNAPSHOT-
CMI Economy: Enabled Vault Version: 1.7.3-CMI
CMI Chat: Enabled
Modules -> 58 enabled 1 disabled: votifier
```

### Errors

```shell
In the case of an item with a space in the name: Could not determine the requirement for a specialized item by value: paper{itemsadder:{id:"minecord_krona",namespace:"eco"},CustomModelData:10007,display:{Name:'{"italic":false,"color":" white","text":"Minecord

Nothing in other cases.
```

### Relevant Config Sections

```yaml
It worked on older versions with this configuration:

    Loc: -164.0:65.0:-494.0:-164.0:66.0:-494.0
    enabled: true
    effect: DripWater
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - item:paper{CustomModelData:10007}:1-5! msg [playerName] HHH

Tested non-working variations of the portal config on the latest version:

  hell:
    Loc: -398.0:78.0:-1278.0:-392.0:83.0:-1273.0
    enabled: true
    effect: Nautilus
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 144
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - item:paper{itemsadder:{id:"minecord_krona",namespace:"eco"},CustomModelData:10007,display:{Name:'{"italic":false,"color":"white","text":"Minecord Krona"}'}}:1-5! tppos [playerName] 0 100 0
    - cmi effect [playerName] darkness 10 1
    - sound ambient_crimson_forest_mood -v:5 [playerName]
    - ...

(Tried including without a space in the name of the item (nothing happens and no errors))
```

### Relevant Plugins

ItemsAdder_3.6.2-beta-r2, ViaVersion-4.8.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
