### ISSUE TITLE
Unwanted Fall Damage

### ISSUE THREAD

**Issue by EpicJosch** [Zrips/CMI#8244]
### Description of Issue

Hello. I do have a problem.. sometimes when a player jumps from a high place in a worldguard region where FallDamage is DISABLED the player gets falldamage from CMI around 2 seconds after he lands on the ground. How can i prevent CMI from doing ANYTHING with FallDamage on the Server?

### Version Information

```shell
[17:45:55 INFO]: --------------------------------------------------
[17:45:55 INFO]: CMI: 9.6.7.7 BungeeCord CMIB  MySQL
[17:45:55 INFO]: CMILib: 1.4.2.4 
[17:45:55 INFO]: Server: Paper(196) 1.20.1-R0.1-SNAPSHOT-
[17:45:55 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
[17:45:55 INFO]: Modules -> 35 enabled 24 disabled: spawnerProximity, signEdit, mirror, launchPad, elytraExploit, skin, elytraBoost, spawners, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, flightCharge, disabledEnchants, worldLimitsElytra, ranks, playerCombat, votifier, shulkerBackpack, headDrop, sitAnimation, spawnerCharge, namePlates, totemBehavior
[17:45:55 INFO]: --------------------------------------------------
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
DeductOnlyForTime: 0.0
  AutoRecharge:
    # Value in percentage when we should automatically recharge players flight charges if player enabled autorecharge with /autorecharge command
    From: 10.0
    # Value in percentage of charges we need to recharge
    # 25 will result into 25% of max allowed charges being recharged each time auto recharge is triggered
    Amount: 25.0
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penalty from jumping from cliffs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 0
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false
  # When color name is defined then at moment player starts flying with flight charges, he will start glowing
  # Set this to 'none' if you want to disable it
  GlowColor: none
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
