### ISSUE TITLE
Multiple Paths for Autorankup at once

### ISSUE THREAD

**Issue by okapischwerin** [Zrips/CMI#8268]
I currently have a minecraft Server running CMIs Autorankup Feature-
I have 5 start-ranks and then a few differente branches.
Each player should start, after the first 5 ranks, doing all the other paths at once.
But right now, each player is only doing one of the paths at once. File Attached:
What do i need to do, so that after rank5, the players work on each rank at the same time?

```
Start1:
  Enabled: true
  DisplayName: '&2Beginner I'
  AutoRankup: true
  DefaultRank: true
  RankupConfirmation: false
  NextRanks:
  - Start2
  Commands:
  - broadcast! &6[playerDisplayName] &eHat Level 1 erreicht!
  - lp user [playerName] promote level
  StatsRequirements:
  - BlocksMined:50
  - ItemCrafts:crafting_table:1
  - travel:100
  - MonsterKills:1
Start2:
  Enabled: true
  DisplayName: '&2Beginner II'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Start3
  Commands:
  - broadcast! &6[playerDisplayName] &eHat Level 2 erreicht!
  - lp user [playerName] promote level
  StatsRequirements:
  - BlocksMined:150
  - ItemCrafts:stone_pickaxe:1
  - ItemCrafts:stone_axe:1
  - ItemCrafts:stone_shovel:1
  - ItemCrafts:stone_sword:1
  - travel:250
  - MonsterKills:2
Start3:
  Enabled: true
  DisplayName: '&2Beginner III'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Start4
  Commands:
  - broadcast! &6[playerDisplayName] &eHat Level 3 erreicht!
  - lp user [playerName] promote level
  StatsRequirements:
  - BlocksMined:300
  - ItemCrafts:furnace:1
  - ItemCrafts:iron_pickaxe:1
  - ItemCrafts:iron_axe:1
  - ItemCrafts:iron_shovel:1
  - ItemCrafts:iron_sword:1
  - travel:500
  - MonsterKills:5
Start4:
  Enabled: true
  DisplayName: '&2Beginner IV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - Start5
  Commands:
  - broadcast! &6[playerDisplayName] &eHat Level 4 erreicht!
  - lp user [playerName] promote level
  StatsRequirements:
  - ItemCrafts:iron_helmet:1
  - ItemCrafts:iron_chestplate:1
  - ItemCrafts:iron_leggings:1
  - ItemCrafts:iron_boots:1
  - travel:1000
  - MonsterKills:10
Start5:
  Enabled: true
  DisplayName: '&2Beginner V'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime1
  - monsterkills1
  - traveler1
  - buy1
  Commands:
  - broadcast! &6[playerDisplayName] &eHat Level 5 erreicht!
  - lp user [playerName] promote level
  StatsRequirements:
  - ItemCrafts:diamond_helmet:1
  - ItemCrafts:diamond_chestplate:1
  - ItemCrafts:diamond_leggings:1
  - ItemCrafts:diamond_boots:1
  - ItemCrafts:diamond_sword:1
  - travel:2000
  - MonsterKills:15
playtime1:
  Enabled: true
  DisplayName: '&2Spielzeit I'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime2
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 1 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:3600
playtime2:
  Enabled: true
  DisplayName: '&2Spielzeit II'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime3
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 2 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:7200
playtime3:
  Enabled: true
  DisplayName: '&2Spielzeit III'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime4
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 3 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:10800
playtime4:
  Enabled: true
  DisplayName: '&2Spielzeit IV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime5
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 5 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:18000
playtime5:
  Enabled: true
  DisplayName: '&2Spielzeit V'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime6
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 10 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:3600
playtime6:
  Enabled: true
  DisplayName: '&2Spielzeit VI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime7
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 15 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:54000
playtime7:
  Enabled: true
  DisplayName: '&2Spielzeit VII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime8
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 20 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:72000
playtime8:
  Enabled: true
  DisplayName: '&2Spielzeit VIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime9
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 25 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:90000
playtime9:
  Enabled: true
  DisplayName: '&2Spielzeit IX'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime10
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 32 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:115200
playtime10:
  Enabled: true
  DisplayName: '&2Spielzeit X'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime11
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 40 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:144000
playtime11:
  Enabled: true
  DisplayName: '&2Spielzeit XI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime12
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 50 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:180000
playtime12:
  Enabled: true
  DisplayName: '&2Spielzeit XII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime13
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 60 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:216000
playtime13:
  Enabled: true
  DisplayName: '&2Spielzeit XIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime14
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 75 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:270000
playtime14:
  Enabled: true
  DisplayName: '&2Spielzeit XIV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - playtime15
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 85 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:306000
playtime15:
  Enabled: true
  DisplayName: '&2Spielzeit XV'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &eSpielt jetzt schon seit 100 Stunden!
  - lp user [playerName] promote level
  StatsRequirements:
  - PlayTime:360000
monsterkills1:
  Enabled: true
  DisplayName: '&2Killer I'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills2
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 50 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:50
monsterkills2:
  Enabled: true
  DisplayName: '&2Killer II'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills3
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 75 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:75
monsterkills3:
  Enabled: true
  DisplayName: '&2Killer III'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills4
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 100 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:100
monsterkills4:
  Enabled: true
  DisplayName: '&2Killer IV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills5
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 150 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:150
monsterkills5:
  Enabled: true
  DisplayName: '&2Killer V'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills6
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 250 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:250
monsterkills6:
  Enabled: true
  DisplayName: '&2Killer VI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills7
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 400 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:400
monsterkills7:
  Enabled: true
  DisplayName: '&2Killer VII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills8
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 750 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:750
monsterkills8:
  Enabled: true
  DisplayName: '&2Killer VIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills9
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 1.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:1000
monsterkills9:
  Enabled: true
  DisplayName: '&2Killer IX'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills10
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 1.500 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:1500
monsterkills10:
  Enabled: true
  DisplayName: '&2Killer X'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills11
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 2.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:2000
monsterkills11:
  Enabled: true
  DisplayName: '&2Killer XI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills12
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 3.500 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:3.500
monsterkills12:
  Enabled: true
  DisplayName: '&2Killer XII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills13
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 5.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:5000
monsterkills13:
  Enabled: true
  DisplayName: '&2Killer XIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills14
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 7.500 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:7500
monsterkills14:
  Enabled: true
  DisplayName: '&2Killer XIV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills15
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 10.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:10000
monsterkills15:
  Enabled: true
  DisplayName: '&2Killer XV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills16
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 15.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:15000
monsterkills16:
  Enabled: true
  DisplayName: '&2Killer XVI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills17
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 20.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:20000
monsterkills17:
  Enabled: true
  DisplayName: '&2Killer XVII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills18
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 25.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:25000
monsterkills18:
  Enabled: true
  DisplayName: '&2Killer XVIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills19
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 40.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:40000
monsterkills19:
  Enabled: true
  DisplayName: '&2Killer XIX'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills20
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 50.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:50000
monsterkills20:
  Enabled: true
  DisplayName: '&2Killer XX'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills21
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 60.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:60000
monsterkills21:
  Enabled: true
  DisplayName: '&2Killer XXI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills22
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 70.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:70000
monsterkills22:
  Enabled: true
  DisplayName: '&2Killer XXII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills23
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 80.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:80000
monsterkills23:
  Enabled: true
  DisplayName: '&2Killer XXIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - monsterkills24
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 90.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:90000
monsterkills24:
  Enabled: true
  DisplayName: '&2Killer XXIV'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &eHat insgesamt 100.000 Monster getötet!
  - lp user [playerName] promote level
  StatsRequirements:
  - MonsterKills:100000
traveler1:
  Enabled: true
  DisplayName: '&2Traveler I'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler2
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 3.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:3000
traveler2:
  Enabled: true
  DisplayName: '&2Traveler II'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler3
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 5.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:5000
traveler3:
  Enabled: true
  DisplayName: '&2Traveler III'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler4
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 7.500 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:7500
traveler4:
  Enabled: true
  DisplayName: '&2Traveler IV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler5
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 10.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:10000
traveler5:
  Enabled: true
  DisplayName: '&2Traveler V'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler6
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 15.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:15000
traveler6:
  Enabled: true
  DisplayName: '&2Traveler VI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler7
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 25.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:25000
traveler7:
  Enabled: true
  DisplayName: '&2Traveler VII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler8
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 35.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:35000
traveler8:
  Enabled: true
  DisplayName: '&2Traveler VIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler9
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 50.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:50000
traveler9:
  Enabled: true
  DisplayName: '&2Traveler IX'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler10
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 75.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:75000
traveler10:
  Enabled: true
  DisplayName: '&2Traveler X'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler11
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 100.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:100000
traveler11:
  Enabled: true
  DisplayName: '&2Traveler XI'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler12
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 125.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:125000
traveler12:
  Enabled: true
  DisplayName: '&2Traveler XII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler13
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 150.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:150000
traveler13:
  Enabled: true
  DisplayName: '&2Traveler XIII'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler14
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 175.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:175000
traveler14:
  Enabled: true
  DisplayName: '&2Traveler XIV'
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - traveler15
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 200.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:200000
traveler15:
  Enabled: true
  DisplayName: '&2Traveler XV'
  AutoRankup: true
  RankupConfirmation: false
  Commands:
  - broadcast! &6[playerDisplayName] &eIst ingesammt 250.000 Blöcke gereist!
  - lp user [playerName] promote level
  StatsRequirements:
  - travel:250000
buy1:
  Enabled: true
  DisplayName: '&2Aktionär I'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy2
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 10€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 10
buy2:
  Enabled: true
  DisplayName: '&2Aktionär II'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy3
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 25€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 25
buy3:
  Enabled: true
  DisplayName: '&2Aktionär III'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy4
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 50€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 50
buy4:
  Enabled: true
  DisplayName: '&2Aktionär IV'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy5
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 100€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 100
buy5:
  Enabled: true
  DisplayName: '&2Aktionär V'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy6
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 200€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 200
buy6:
  Enabled: true
  DisplayName: '&2Aktionär VI'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy7
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 350€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 350
buy7:
  Enabled: true
  DisplayName: '&2Aktionär VII'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy8
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 500€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 500
buy8:
  Enabled: true
  DisplayName: '&2Aktionär VIII'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy9
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 750€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 750
buy9:
  Enabled: true
  DisplayName: '&2Aktionär VIX'
  AutoRankup: true
  RankupConfirmation: true
  NextRanks:
  - buy10
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 1.000€ einen Rang gekauft... PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 1000
buy10:
  Enabled: true
  DisplayName: '&2Aktionär VIX'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - broadcast! &6[playerDisplayName] &eHat sich mit 10.000€ einen Rang gekauft...
    PAYTOWIN
  - lp user [playerName] promote level
  MoneyCost: 10000

```
