### ISSUE TITLE
CustomHeads.yml - problem with Player Heads

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8282]
### Description of Issue

How to change "Player's Head"?
In my language there is no 's

At now i have "Martynas's Head", how to change " 's Head"?

Can't find in translations file, can't find in CustomHeads.yml, **LORE only**.

### Version Information

```shell
9.6.8.4
```

### Errors

```shell
no errors
```

### Relevant Config Sections

```yaml
... ... ...
useDefaultHeadLore: true
# Default lore used when head doesnt have defined head lore set
defaultHeadLore:
- '&8monstro galva'
PlayerHead:
  # Defines if you want to use player head lore
  UseLore: true
  # Lore used for player head drops
  # Global variables can be used for simple identification who was killed and who killed player
  # Aditionally placeholders can be used too, but we will use victim as source for their translation if placeholder requires source player
  Lore:
  - '&8žaidėjo galva'
... ... ...
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
