### ISSUE TITLE
Players are teleported to world spawn on join instead of CMI Spawn

### ISSUE THREAD

**Issue by EpicJosch** [Zrips/CMI#8285]
### Description of Issue

When Players login to the Server, they get teleported to world spawn instead of being teleported to CMI Spawn. In config i activated "SpawnOnJoin" and set both the Spawn and the first spawn point aswell as the respawn point. Also i configured Multiverse Core to not interfere with Spawn.

### Version Information

```shell
[21:33:28 INFO]: --------------------------------------------------
[21:33:28 INFO]: CMI: 9.6.8.4 Unknown  MySQL
[21:33:28 INFO]: CMILib: 1.4.3.4 
[21:33:28 INFO]: Server: Paper(196) 1.20.1-R0.1-SNAPSHOT-
[21:33:28 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
[21:33:28 INFO]: Modules -> 35 enabled 24 disabled: spawnerProximity, signEdit, mirror, launchPad, elytraExploit, skin, elytraBoost, spawners, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, flightCharge, disabledEnchants, worldLimitsElytra, ranks, playerCombat, votifier, shulkerBackpack, headDrop, sitAnimation, spawnerCharge, namePlates, totemBehavior
[21:33:28 INFO]: --------------------------------------------------
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
Spawn:
  # Forces players to login in defined spawn point when logging into server
  # Can be bypasses with cmi.spawnonjoin.bypass permission node
  SpawnOnJoin: false
  # List of worlds which should be ignored and players joining in those servers will not be teleported to appropriate spawn point but will login at their log out location
  IgnoredWorlds: []
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  Main:
    World: freebuild
    X: 89.47218548824479
    Y: 75.0
    Z: 5880.511074166412
    Pitch: -0.9000134
    Yaw: 179.96057
    RespawnLocation: true
    Rng: 0
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    World: freebuild
    X: 89.47218548824479
    Y: 75.0
    Z: 5880.511074166412
    Pitch: -0.9000134
    Yaw: 179.96057
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  # Max 60 seconds
  Immortality: 3
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: anchor, bedLocation, spawn, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # anchor is location defined by interacting with respawn anchor. This in general will only apply when you die in nether world, otherwise bed location is used
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - spawn
    - bedLocation
    - anchor
    - worldSpawn
    - homeLocation
  # Defines respawn order for defines worlds
  # Set respawn priority to [] or to random respawn criteria if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    world:
    - spawn
    - bedLocation
    - anchor
    - worldSpawn
    - homeLocation
```

### Relevant Plugins

Vault: 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
