### ISSUE TITLE
Usermeta Values Being Wiped

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#8319]
### Description of Issue

I've had some issues with `/cmi usermeta` values being reset randomly. If I had to guess it's happening more frequently when CMI updates, but it's not happening for everyone all the time and not every update or every restart etc. I don't use the function super often so it's not like there are a ton of values in there - maybe one or two per player and only a small fraction of players. 

Any time I use the function at this point I use it with a kit that also prints the value to Discord so we can track it at least and recover anything that is wiped, but it is certainly frustrating.

The particular key I'm using in this case is called "TimeyWimey5" and values are only incremented and decremented one at a time and wouldn't be a lot at once. Using them normally within an online session seems to work without issue. The update guess is indeed purely a guess since it doesn't _seem_ to happen during normal restarts. I'm really not sure though - it's a tough one to pin down.

I'll include the commands (kits) we use below: 

```
vaultDepositTimeVortex:
  CommandName: vaultDepositTimeVortex
  Delay: 10
  Commands:
  - cmi usermeta [playerName] increment TimeyWimey5 1 -s
  - cmi msg [playerName] !-You have deposited your Time Vortex for future use!
  - 'discord broadcast #[redacted] %cmi_user_nickname% deposited a Time Vortex. Previous balance: %cmi_user_meta_TimeyWimey5%'
  Group: Vaults
vaultWithdrawTimeVortex:
  CommandName: vaultWithdrawTimeVortex
  Delay: 10
  Commands:
  - statement:tokencheck! check:%cmi_user_meta_TimeyWimey5%>=1!
  - if:tokencheck! cmi usermeta [playerName] increment TimeyWimey5 -1 -s
  - if:tokencheck! mgive [playerName] vaulttimevortex
  - if:tokencheck! msg! [playerName] You have withdrawn a Time Vortex!
  - 'if:tokencheck! discord broadcast #[redacted]  %cmi_user_nickname% withdrew a Time Vortex. Previous balance: %cmi_user_meta_TimeyWimey5%'
  - if:tokencheck@! msg! [playerName] You do not have any Time Vortices!
  Group: Vaults
vaultUseTimeVortex1:
  CommandName: vaultUseTimeVortex1
  Delay: 10
  Commands:
  - statement:tokencheck! check:%cmi_user_meta_TimeyWimey5%>=1!
  - if:tokencheck! cmi usermeta [playerName] increment TimeyWimey5 -1 -s
  - if:tokencheck! cmi bossbarmsg [playerName] {#17b4e6>}&lVault will self-destruct
    in{#5555FF<} [autoTimeLeft]{#5555FF}&l! -sec:-300 -s:1 -n:vaulttimer -cmd:"cmi
    kit vaultEnd [playerName]"
  - if:tokencheck! msg! [playerName] You have used a Time Vortex!
  - 'if:tokencheck! discord broadcast #[redacted]  %cmi_user_nickname% used a Time Vortex. Previous balance: %cmi_user_meta_TimeyWimey5%'
  - if:tokencheck@! msg! [playerName] You do not have any Time Vortices!
  Group: Vaults
vaultUseTimeVortex2:
  CommandName: vaultUseTimeVortex2
  Delay: 10
  Commands:
  - statement:tokencheck! check:%cmi_user_meta_TimeyWimey5%>=2!
  - if:tokencheck! cmi usermeta [playerName] increment TimeyWimey5 -2 -s
  - if:tokencheck! cmi bossbarmsg [playerName] {#17b4e6>}&lVault will self-destruct
    in{#5555FF<} [autoTimeLeft]{#5555FF}&l! -sec:-600 -s:1 -n:vaulttimer -cmd:"cmi
    kit vaultEnd [playerName]"
  - if:tokencheck! msg! [playerName] You have used 2 Time Vortices!
  - 'if:tokencheck! discord broadcast #[redacted] %cmi_user_nickname% used 2 Time Vortices. Previous balance: %cmi_user_meta_TimeyWimey5%'
  - if:tokencheck@! msg! [playerName] You do not have any Time Vortices!
  Group: Vaults
vaultUseTimeVortex3:
  CommandName: vaultUseTimeVortex3
  Delay: 10
  Commands:
  - statement:tokencheck! check:%cmi_user_meta_TimeyWimey5%>=3!
  - if:tokencheck! cmi usermeta [playerName] increment TimeyWimey5 -3 -s
  - if:tokencheck! cmi bossbarmsg [playerName] {#17b4e6>}&lVault will self-destruct
    in{#5555FF<} [autoTimeLeft]{#5555FF}&l! -sec:-900 -s:1 -n:vaulttimer -cmd:"cmi
    kit vaultEnd [playerName]"
  - if:tokencheck! msg! [playerName] You have used 3 Time Vortices!
  - 'if:tokencheck! discord broadcast #[redacted] %cmi_user_nickname% used 3 Time Vortices. Previous balance: %cmi_user_meta_TimeyWimey5%'
  - if:tokencheck@! msg! [playerName] You do not have any Time Vortices!
  Group: Vaults
```

Thanks for the assistance!

### Version Information

```shell
CMI plugin version: 9.6.9.2 BungeeCord CMIB  SqLite
CMILib: 1.4.4.1 
Server: Paper(318) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin
```

### Errors

```shell
None that we've seen.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
