### ISSUE TITLE
HoverItems: Items being displayed in chat don't use their custom display name

### ISSUE THREAD

**Issue by DaniDipp** [Zrips/CMI#8339]
### Description of Issue

When using the HoverItems feature to replace a chat variable with the item in my hand, the text in chat displays the item material, not the item's display name.
![2023-12-19T13-21-40](https://github.com/Zrips/CMI/assets/17002453/fba83a0b-b9f8-4b21-9acb-d9447009bc27)
![2023-12-19T13-22-59](https://github.com/Zrips/CMI/assets/17002453/7530c985-6267-497f-9677-5b8d7679e073)

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.9.3 Unknown  SqLite
CMILib: 1.4.4.2 
Server: Paper(318) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 18 enabled 41 disabled: spawnerProximity, cuffed, versionCheck, armorEffects, moneyCheque, skin, elytraBoost, eventCommands, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, votifier, shulkerBackpack, cooldown, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, signEdit, hpBossBar, launchPad, elytraExploit, afk, holograms, jail, spawners, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, schedule, disabledEnchants, worldLimitsElytra, worldLimits, ranks, firstJoinMessages, silentChest, warmup, totemBehavior
--------------------------------------------------
```

### Relevant Config Sections

```yaml
# When set to true, particular variables in chat will be translated into items player are holding. List of variables belove
  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
