### ISSUE TITLE
private message doesn't work in bungeecord when server is in different computer

### ISSUE THREAD

**Issue by aaa8881** [Zrips/CMI#8347]
### Description of Issue

server alpha is in computer A
server beta is in computer B
server gamma in computer A 

private messaging
player in alpha -> player in gamma ✅ works 
player in beta -> player in gamma ❌ does not work

latest CMI , CMILib, and CMIB set up correctly.
used to work, but suddenly stopped working recently, maybe within a week of this report.

### Version Information

```shell
CMI: 9.6.9.3 BungeeCord CMIB
CMILib: 1.4.4.2
Server: Paper(69) 1.20.1 
```
```


### Errors

```shell
can't find any exception relevant to this.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by aaa8881** [comment]
I've rollbacked server to CMI 9.6.7.7 which worked fine previously, and decided to update to latest 9.6.10.7 ( with correct CMILib and latest CMIB) , but issue still persists.

there are three computers A,B,C . Each computer contains multiple bukkit instances. 

A<->B works fine but
A<->C and 
B<->C does not work. 

config.yml
```yml
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true
  # When set to true player names from entire bungee network will be included into tab complete
  NamesInTabComplete: true

```

Chat.yml
```yml
  Bungee:
    # Attention! This will require you to have CMI Bungee plugin which can be found at zrips.net
    # Or direct download https://www.zrips.net/cmi/
    # Do you want to enable private messaging over bungeecord
    # Bungee cord support needs to be enabled for this to have any effect
    Messages: true
    # Do you want to enable public messaging over bungeecord
    # Player needs to have cmi.bungee.publicmessages.[servername] permission node to be able to send messages to target server
    PublicMessages: true
    # Do you want to enable staff messaging over bungeecord
    StaffMessages: true
```

are set up correctly as guided from https://www.zrips.net/cmi/bungeecord/

 ``/cmi serverlist`` correctly identifies server.
 player name tab complete works too.

simply private message is not conveyed from one bukkit instance from computer C to other bukkit instance in other computer.

message between bukkit instances in same computer works. 

sorry for ping @Zrips , but I think you missed it, and I really need support for this.
