### ISSUE TITLE
cmi.colors.publicmessages doesn't work in /cmi chatcolor and /nick

### ISSUE THREAD

**Issue by Everts0n** [Zrips/CMI#8350]
### Description of Issue

1. player that doesn't have cmi.colors.publicmessages.bold or if even its set to false can use bold formatting in /cmi chatcolor, same as all other formatting like italic and etc

2. same problem with cmi.colors.nickname. (all colors and formatting)
if even player has negative false perm for that he can use all colors and formatting in /nick

### Version Information

```shell
[00:45:34 INFO]: --------------------------------------------------
[00:45:34 INFO]: Версия плагина CMI: 9.6.9.3 MySQL
[00:45:34 INFO]: CMILib: 1.4.4.2 
[00:45:34 INFO]: Версия сервера: Paper(388) 1.18.2-R0.1-SNAPSHOT-
[00:45:34 INFO]: CMI Экономика: on Версия Vault: 1.7.3-CMICMI Чат: on 
[00:45:34 INFO]: Модули -> 40 on 19 off: signEdit, customMessages, tablist, armorstand, elytraExploit, portals, skin, holograms, dynamicSigns, deathMessages, disabledEnchants, chatBubble, ranks, firstJoinMessages, selection, votifier, sitAnimation, spawnerCharge, warmup
[00:45:34 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
what your chat.yml is defined?

**Comment by Zrips** [comment]
@Everts0n 
You will need to double check players access to colors, simplest way would be to just run `/cmi colorlimits [playerName]` and check how much that list is populated with color codes. Its quite likely that player simply inherits wildcard placeholder as cmi.colors.publicmessages.* which allows usage of all color codes.
Will make small change relating to this which could potentially solve your issue if it was caused by wild card. If issue persists with next update and player doesn't have access to those color codes then let me know. Closing this ticket for now.

**Comment by Everts0n** [comment]
> @Everts0n You will need to double check players access to colors, simplest way would be to just run `/cmi colorlimits [playerName]` and check how much that list is populated with color codes. Its quite likely that player simply inherits wildcard placeholder as cmi.colors.publicmessages.* which allows usage of all color codes. Will make small change relating to this which could potentially solve your issue if it was caused by wild card. If issue persists with next update and player doesn't have access to those color codes then let me know. Closing this ticket for now.

i checked it and i still can use colors if i dont have perms on it. But as I understand it, the problem is in formatting, because I have it added to /chatcolor too, and for some reason the perms with it work with a bug. (if it is in chatcolor and you do not have perms to it, then you still can use it, as well as colors)

**Comment by CloudeLecaw** [comment]
> > @Everts0n You will need to double check players access to colors, simplest way would be to just run `/cmi colorlimits [playerName]` and check how much that list is populated with color codes. Its quite likely that player simply inherits wildcard placeholder as cmi.colors.publicmessages.* which allows usage of all color codes. Will make small change relating to this which could potentially solve your issue if it was caused by wild card. If issue persists with next update and player doesn't have access to those color codes then let me know. Closing this ticket for now.
> 
> i checked it and i still can use colors if i dont have perms on it. But as I understand it, the problem is in formatting, because I have it added to /chatcolor too, and for some reason the perms with it work with a bug. (if it is in chatcolor and you do not have perms to it, then you still can use it, as well as colors with formatting, bold and etc)
> 
> sorry for the long answer

pls check your chat.yml may you allow color useage without perms?

**Comment by Everts0n** [comment]
> > > @Everts0n You will need to double check players access to colors, simplest way would be to just run `/cmi colorlimits [playerName]` and check how much that list is populated with color codes. Its quite likely that player simply inherits wildcard placeholder as cmi.colors.publicmessages.* which allows usage of all color codes. Will make small change relating to this which could potentially solve your issue if it was caused by wild card. If issue persists with next update and player doesn't have access to those color codes then let me know. Closing this ticket for now.
> > 
> > 
> > i checked it and i still can use colors if i dont have perms on it. But as I understand it, the problem is in formatting, because I have it added to /chatcolor too, and for some reason the perms with it work with a bug. (if it is in chatcolor and you do not have perms to it, then you still can use it, as well as colors with formatting, bold and etc)
> > sorry for the long answer
> 
> pls check and may sahre your chat.ym with us. May you allow color useage without perms?

```
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: true
      books: true
      itemname: true
      itemlore: true
      # List of strings to ignore when checking chat for color codes player cant use.
      # This will bypass players colorcode restrictions and will allow usage of particular chat formats
      # Applies only for public and private messages
      WhiteList:
      - '&c❤'
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true
    # Determines /cmi chatcolor command contents. What player can pick will be determined by cmi.colors.publicmessage.[colorCode] and will be used in %cmi_user_chatcolor% placeholder
    Picker:
    - '&0'
    - '&1'
    - '&9'
    - '&b'
    - '&3'
    - '&4'
    - '&c'
    - '&2'
    - '&a'
    - '&e'
    - '&6'
    - '&5'
    - '&d'
    - '&7'
    - '&8'
    - '{#00e625}'
    - '{#brown}'
    - '&0&l'
    - '&1&l'
    - '&9&l'
    - '&b&l'
    - '&3&l'
    - '&4&l'
    - '&c&l'
    - '&2&l'
    - '&a&l'
    - '&e&l'
    - '&6&l'
    - '&5&l'
    - '&d&l'
    - '&7&l'
    - '&8&l'
    - '&f&o&l'
    - '&b&o&l'
    - '&6&o&l'
    - '&4&o&l'
```
