### ISSUE TITLE
[sourceDisplayName] in custom death message dont work  when player is killed by mobs 

### ISSUE THREAD

**Issue by microvencn** [Zrips/CMI#8352]
### Description of Issue

[sourceDisplayName] in custom death message dont work  when player is killed by mobs .
It will directly display "some body is killled by [sourceDisplayName]", which leads to it cant display the display name of mobs created by Mytchimobs.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.9.3 SqLite
CMILib: 1.4.3.0 -> 1.4.4.2
Server: Paper(290) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Diabled
Modules -> 57 enabled 2 disabled: tablist, votifier
 --------------------------------------------------
```

### Relevant Config Sections

```yaml
Mob:
  Elder_guardian:
    General:
    - '&2[playerDisplayName] &7was killed by &2[sourceDisplayName]'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
