### ISSUE TITLE
Displayname issue

### ISSUE THREAD

**Issue by Gojan1** [Zrips/CMI#836]
**Description of issue or feature request:**
Hello, i have added a plugin named : Powertags to be able to give player prefixes/suffixes. but for some reason they don't appear on the displayname,
i even moved cmi and powertags to a seperated server to test it, and both times it failed.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Posible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{prefix} {nickName} testeste'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  ValidNicknameRegex: '[^\p{L}0-9\-\_]'
#####################################
```

**Cmi Version (using`/cmi version`):** 
cmi plugin version: 8.0.9.0
**Server Type (Spigot/Paperspigot/etc):** 
Server version: Spigot 1.8.8-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
