### ISSUE TITLE
Chat Format Placeholder Issues

### ISSUE THREAD

**Issue by 0bviouslee** [Zrips/CMI#8360]
### Description of Issue

I'm trying to use a LuckPerms placeholder in my chat format, though for some reason it doesn't parse. It parses with /papi parse, but not in the chat format or /cmi placeholders parse.

Chat Format where "%eternaltags_tag%" parses correctly though the LuckPerms placeholders do not:
![image](https://github.com/Zrips/CMI/assets/60064846/093f3f9c-c11f-4f64-a817-e78337c97ad1)

/papi parse for both placeholders:
![image](https://github.com/Zrips/CMI/assets/60064846/c2abdeb0-bfd9-4645-ace5-292c27d5bab4)

/cmi placeholders parse for both placeholders:
![image](https://github.com/Zrips/CMI/assets/60064846/265d415a-d92d-42e9-a661-0f1d26fd21c6)

### Version Information

```shell
CMI: 9.6.9.4
CMILib: 1.4.4.2
Server: Paper 1.20.4
```

### Relevant Config Sections

```yaml
GeneralFormat: '%eternaltags_tag%{prefix}{displayName} %luckperms_meta_prefix-color%:
    &r{message}'
  GeneralMessageFormat: '%luckperms_meta_chat-color% {message}'
```

### Relevant Plugins

LuckPerms 5.4.104

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
