### ISSUE TITLE
Go into combat mode because you took damage from a cactus?

### ISSUE THREAD

**Issue by LOURENT4462** [Zrips/CMI#8378]
### Description of Issue

when you are hit by a cactus, you will enter combat mode, it seems it is detected as mob damage, I think that is strange and annoying.

why can I conclude that it is considered mob damage by cmi? because when I deactivate combat mode on a mob, I don't enter combat mode again when I get damage from the cactus, so it can be concluded that cactus damage is considered mob damage

### Version Information

```shell
[19:21:21 INFO]: --------------------------------------------------
[19:21:21 INFO]: CMI: 9.6.8.5 BungeeCord CMIB  SqLite-> 9.6.9.6
[19:21:21 INFO]: CMILib: 1.4.3.4 -> 1.4.4.4
[19:21:21 INFO]: Server: Paper(245) 1.20.2-R0.1-SNAPSHOT-
[19:21:21 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[19:21:21 INFO]: Modules -> 49 enabled 10 disabled: spawnerProximity, flightCharge, tablist, shulkerBackpack, headDrop, sitAnimation, anvilRenameColor, spawners, spawnerCharge, bossBarCompass
[19:21:21 INFO]: --------------------------------------------------
```

### Errors

```shell
There is no error log in the console
```

### Relevant Config Sections

```yaml
Combat:
  # Defines combat timer to be used in particular features
  Timer: 15
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: false
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: false
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging players
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c⚔[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: true
    AllowedCommands:
    - msg
    - r
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging mobs
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c❤[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pve.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage mobs while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - msg
    - r
    - tell
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
```

### Agreements

- [X] My server is supported by CMI.
- [ ] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
