### ISSUE TITLE
new delay option to use %cmi_random_from_to% sometimes breaks up the ca/scheduler

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8381]
### Description of Issue

new delay option to use %cmi_random_from_to% sometimes breaks up the ca/scheduler

here a litte TestCustomAlias
```
  test_test:
    Cmds:
    - msg! [playerName] start 0
    - delay! %cmi_random_1_10%
    - msg! [playerName] end %cmi_lastrandom_[playerName]%
    Perm: true
    Tab: false
    CustomTabs:
    - ''
```
to retry this. use the command and wait for the feedback message (end x)
then repeat the command.
repeat this up to 10 times (try to not run it doubled)

You will see the CustomAlias sometimes breaks up. so looks liek this new random delay option is not stable yet..
here a little picture of the chat when i tried it.
![Snag_187230a](https://github.com/Zrips/CMI/assets/12080017/28b482e7-15a6-442c-80d2-0e7e876d75c0)

### Version Information
![Snag_1885ed6](https://github.com/Zrips/CMI/assets/12080017/b933f7a3-febe-42a4-900d-329a845a4fb5)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
