### ISSUE TITLE
Can't use %checkitem% placeholderapi

### ISSUE THREAD

**Issue by 1470429149** [Zrips/CMI#8404]
### Description of Issue

For CMI9.2.5.1, I can use %checkitem% normally

For CMI9.6.9.8：
When I try to use placeholderapi, I get an error：
[21:43:48 INFO]: Placeholder got blocked due to security concerns (%checkitem%)

### Version Information

```shell
[21:48:26 INFO]: --------------------------------------------------
[21:48:26 INFO]: CMI 插件版本: 9.6.9.8 SqLite
[21:48:26 INFO]: CMILib: 1.4.4.6 
[21:48:26 INFO]: 服务器版本: Paper(408) 1.17.1-R0.1-SNAPSHOT-
[21:48:26 INFO]: CMI 经济: 启用 经济: 1.7.3-CMI CMI 聊天: 禁用 
[21:48:26 INFO]: 模块 -> 58 已启用 1 已禁用: votifier
```

### Errors

```shell
[21:43:48 INFO]: Placeholder got blocked due to security concerns (%checkitem%)
```

### Relevant Config Sections

```yaml
ql01:
  Locations:
  - world;1030.0;7.0;1006.0
  Commands:
  - statement:check1! check:%checkitem_remove_custommodeldata:98999,amt:5%==yes!
  - if:check1@! tellraw [playerName] [{"text":"&c兑换失败!"}]
  - if:check1@! tellraw [playerName] [{"text":"&e兑换需要：&6神器碎片&7 * 5%checkitem_remove_custommodeldata:98999,amt:5%"}]
  - if:check1! tellraw [playerName] [{"text":"&a兑换成功!"}]
  - if:check1! mi give sword QL16 [playerName] 1 0 100 0 silent
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
