### ISSUE TITLE
Reply via clicking message in chat failing on newer CMI/CMILib

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#8405]
### Description of Issue

On our server, nicked players often have colored display names and have a unicode * before their names.  
On recent versions of CMI/CMILib, clicking the name of a nicked player in chat no longer works to send them a /msg.  It will prompt the message, but when entered, it tells the player "Can't find player with this name!"

<img width="267" alt="image" src="https://github.com/Zrips/CMI/assets/16856680/14c5730d-373d-438b-8989-2f57907b9c09">

### Version Information

```shell
[18:37:16 INFO]: --------------------------------------------------
[18:37:16 INFO]: CMI plugin version: 9.6.9.9 MySQL-> 9.6.9.8
[18:37:16 INFO]: CMILib: 1.4.4.7 
[18:37:16 INFO]: Server: Paper(389) 1.20.4-R0.1-SNAPSHOT+
[18:37:16 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[18:37:16 INFO]: Modules -> 51 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[18:37:16 INFO]: --------------------------------------------------
> ver cmi
[18:37:38 INFO]: CMI version 9.6.9.9
[18:37:38 INFO]: Powerful server management tool
[18:37:38 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[18:37:38 INFO]: Author: Zrips
```

### Errors

```shell
No console errors.  In chat we get:
"Can't find player with that name"
```

### Relevant Config Sections

```yaml
DisplayName:
  # If you have 3rd party plugin changing players display name, set this to false
  Change: true
  # Format of players display name. By default only nick name will be visible, if its set, if not, then players name
  # Possible custom varibales: {prefix} {suffix} {nicknameprefix}
  # Supports placeholders
  Format: '{nicknameprefix}{nickName}'
  # Defines regex for valid nick name
  # By default only letters and numbers are allowed
  # If you want to allow any letter from any language use [^\p{L}0-9\-\_]
  ValidNicknameRegex: '[^\p{L}0-9\-\_]'
NickName:
  # Prevents players to change their nick name to one of defined without permission
  # Use lower case
  # cmi.command.nick.bypassblacklist
  # to bypass protection against already in use name/nickname use cmi.command.nick.bypassinuse
  BlackList:
  - admin
  - administrator
  - server
  - staff
  - staf
  - owner
  - co-owner
  - mod
  - moderator
  - founder
  - sysadmin
  # Min length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MinLength: 2
  # Max length of nick name, can be bypassed with cmi.command.nick.bypass.length
  MaxLength: 16
  # Adds prefix for players nickname to indicate that its not real name. This can be added to display name with {nicknameprefix}
  Prefix: '&b✪'
  # When true, will only add nickname prefix when its not same as original name. This can allow colorization or capitalization change without adding prefix
  PrefixWhenDifferent: false
  TabComplete:
    # When true, online players nick name will be used instead of real name in tabcomplete
    ReplaceReal: true
    # When true, we will include real name on top of nickname. This only has effect when ReplaceName is enabled
    IncludeReal: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
I can reproduce this. 

i use `prefix.13.{#d34087}✪` for example, where i append the unicode character in the prefix for the player group.

Then when the player msg me and i reply, the prefix is in there, making the name invalid. 

Updating `Chat.yml` to use ` [playerNickName]` mitigates the issue.
```yaml
  ClickSuggestions:
    pubmsg: '/msg [playerNickName] '
    privmsg: '/msg [playerNickName] '
    staffmsg: '/staffmsg '
    helpop: '/msg [playerNickName] '
    chatroom: '/msg [playerNickName] '
    discord: '/msg [playerNickName] '
 ```
Tested with momshroom and on my live server, 
a- i can reproduce the issue
b- this fix makes clickable msgs work properly again

**Comment by Momshroom** [comment]
This was fixed by changing playerDIsplayName to playerNickName in the Chat.yml click suggestions:
```
  ClickSuggestions:
    pubmsg: '/msg [playerNickName] '
    privmsg: '/msg [playerNickName] '
    staffmsg: '/msg [playerNickName] '
    helpop: '/msg [playerNickName] '
    chatroom: '/msg [playerNickName] '
    discord: '/msg [playerNickName] '
```
Again, with thanks to Floris for the idea
