### ISSUE TITLE
About CMIs Schedules feature

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#841]
Well...

In CMIs schedule, Can not use "asPlayer!", "[playerName]", and "%cmi_user_name%"

I want to make peolpe execute commands who has permissions.

For example, perm:asdf.asdf! cmi spawn [playerName]

But, At present, I can't use this.

Can you add these features at Schedules?

**Cmi Version (using`/cmi version`):**  8.0.9.0

**Server Type (Spigot/Paperspigot/etc):**  spigot

**Server Version (using `/ver`):**  1.11

**Comment by CloudeLecaw** [comment]
Well could you more example what the sheduler should do?

normaly the seduler is to execute commands shedules on servertimings…

like: saving x Hours or anything else..
These commands are servercommands and no ingame executives..
you could force a randomplayer Players each Hours to do something… with it..why ever..
Example:
```
RandomForce:
  Enabled: true
  MinPlayers: 1
  Delay: 7200
  Repeat: true
  Commands:
  - cmi sudo [randomPlayer] /say Hello, i am Still Online
```
