### ISSUE TITLE
Bug in WarmUps

### ISSUE THREAD

**Issue by imtorich** [Zrips/CMI#8438]
### Description of Issue

This does not work on newer versions of CMI. Please fix it.

```
WarmUps:
  # You can enable any command warmup to prevent instant command usage
  # tp:5:false means that when player performs /tp command he will need to wait 5 sec
  # false variable is optional and when its set to false player cant move while warmup is counting
  # If you dont want to deny empty warp command but want to deny any extra variable after that, then just add space, in example 'warp :5:false'
  # When setting warmups for CMI commands, use full command name and not allias, in example 'cmi warp:5false'
  # Administration can bypass limitations with cmi.warmupbypass.[commandname] permission node
  # ATTENTION! cmi home command is being handled in special way and to prevent double warmup, add space, example: - cmi home :5:false
  # Experimental: add GlyphHead to the warmup to show particle effect while command is on warmup period. Like
  # - cmi warp :3:false:GlyphHead
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: false
  List:
  - cmi back:4:false
  - cmi warp :3:false
  - cmi dback:4:false
  - cmi home :4:false
  - cmi spawn:4:false
  - cmi tpa :4:false
```

CMI VER: 9.6.9.8

### Version Information

```shell
ㅤ
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
