### ISSUE TITLE
FlyAboveRoof worldlimit doesn't actually prevent player movement

### ISSUE THREAD

**Issue by ashquarky** [Zrips/CMI#8440]
### Description of Issue

When using `FlyAboveRoof: false`, a player who flies above the limit will see the "You can't fly so high" message and get pushed back slightly, but they can continue flying up and above the limit with only the occasional and slight pushback.

Can be reproduced on a stock config by enabling the worldlimits and /fly for a non-opped player.

### Version Information

```shell
[18:09:53 INFO]: --------------------------------------------------
[18:09:53 INFO]: CMI: 9.6.10.0 SqLite
[18:09:53 INFO]: CMILib: 1.4.4.9 
[18:09:53 INFO]: Server: Paper(405) 1.20.4-R0.1-SNAPSHOT+
[18:09:53 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[18:09:53 INFO]: Modules -> 58 enabled 1 disabled: votifier
[18:09:53 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: true
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - testWorld:Survival
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:False
  # If player will have cmi.worldlimit.elytra.bypass permission node, elytra flight will not be prevented
  # Players joining worlds with disable elytra flight will get their elytra dismounted if possible
  ElytraFlight:
  - worldName:False
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoof: false
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoofLimitations:
  - world-320
  - world_nether-128
  - world_the_end-256
  # If player will have cmi.worldlimit.god.bypass permission node, god mode wont be changed
  GodMode:
  - testWorld:False
  # Prevents particular entity spawn reasons in defined worlds. All possible reasons: NATURAL, JOCKEY, CHUNK_GEN, SPAWNER, EGG, SPAWNER_EGG, LIGHTNING, BUILD_SNOWMAN, BUILD_IRONGOLEM, BUILD_WITHER, VILLAGE_DEFENSE, VILLAGE_INVASION, BREEDING, SLIME_SPLIT, REINFORCEMENTS, NETHER_PORTAL, DISPENSE_EGG, INFECTION, CURED, OCELOT_BABY, SILVERFISH_BLOCK, MOUNT, TRAP, ENDER_PEARL, SHOULDER_ENTITY, DROWNED, SHEARED, EXPLOSION, RAID, PATROL, BEEHIVE, PIGLIN_ZOMBIFIED, SPELL, FROZEN, METAMORPHOSIS, DUPLICATION, COMMAND, CUSTOM, DEFAULT
  SpawnReasons:
    world:
    - None
    world_nether:
    - None
    world_the_end:
    - None
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
