### ISSUE TITLE
Playtime not registered in database

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#8441]
### Description of Issue

Hello,
I'm using a MariaDB database for my server, and I've just noticed that the game time is not saved in my database even though I've configured this setting: 
```yml
  # When set to true, player play time will be grabbed from user stats file instead of from CMI user data file
  # This can help to get more accurate play time if you have older server and using players stats feature
  PlayTimeFromStats: false
  # Do you want to run auto top playtime updater
  # This is responsible for providing players current top playtimes which gets updated on consistent intervals, useful for placeholders
  PlayTimeAutoUpdater: true
  # When set to true, playtimetop list will be loaded on server startup
  PreloadTopPlaytime: true
  # Do you want to use CMI playtime tracking
  # While this is enabled, player play time will be record for each hour he playied in server
  # This doesnt have effect on rankup or /playtime commands, it will only show more specific playtime by hours when using /cplaytime command
  CMIPlayTimeTracking: false
  ```

### Version Information

```shell
CMI: 9.6.10.0 Velocity CMIB MySQL
CMILib: 1.4.4.9
Server: Purpur(2134) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Activée Vault: 1.7.3-CMI CMI Chat: Activée
Modules -> 31 enabled 28 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, elytraLaunch, bossBarCompass, chatBubble, votifier, headDrop, spawnerCharge, namePlates, homeInteractions, hpBossBar, anvilRenameColor, jail, spawners, paintingEditor, dynamicSigns, disabledEnchants, worldLimits, ranks, sitAnimation, silentChest, totemBehavior
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
