### ISSUE TITLE
Interactive commands bug with off-hand

### ISSUE THREAD

**Issue by MedvedEE** [Zrips/CMI#8443]
### Description of Issue

I have set up a sign shop. When user left clicks on a sign for example, IC is run to check if user can sell it. If they can, IC takes the item from inventory and gives money. But if the item is in off-hand, money is given but item still remains in hand. In the video, I first right click to buy it, then left click to sell it. And then repeat it if the item is in off-hand.
Video : https://imgur.com/a/0rb74bq

### Version Information

```shell
https://imgur.com/a/d94VvgA
```

### Relevant Config Sections

```yaml
shopcactus:
  Locations:
  - Survival;2687;67;-1224
  Commands:
  - check:%jobsr_user_jlevel_Talunik%>=5! click:right! moneycost:5! asConsole! cmi
    give [playerName] cactus 1
  - check:%jobsr_user_jlevel_Talunik%>=5! click:right! check:%cmi_user_balance%<5!
    asConsole! cmi titlemsg [playerName] &cSul pole piisavalt raha! -in:10 -out:10
    -keep:10
  - check:%jobsr_user_jlevel_Talunik%>=5! click:right! check:%cmi_user_balance%<5!
    asConsole! cmi sound entity_villager_no [playerName] -v:0.5
  - click:left! item:cactus:0-1! check:%jobsr_user_jlevel_Talunik%>=5! asConsole!
    money add [playerName] 0.7
  - click:leftshift! item:cactus:0-64! check:%jobsr_user_jlevel_Talunik%>=5! asConsole!
    money add [playerName] 44.8
  - click:rightshift! check:%jobsr_user_jlevel_Talunik%>=5! moneycost:320! asConsole!
    give [playerName] cactus 64
  - check:%jobsr_user_jlevel_Talunik%<5! msg! [playerName] &c&l! &7Selle poe ala kasutamiseks
    pead olema &eTase 5&7 ametis &aTalunik&7. &o(/jobs)
  - check:%jobsr_user_jlevel_Talunik%<5! asConsole! cmi sound entity_pig_ambient [playerName]
    -p:2 -v:0.5
  SignLines:
  - '&7[&6Osta&7/&aMüü&7]'
  - '&bCactus'
  - '&7Ost: &c5 €'
  - '&7Müük: &a0.7 €'
  ReqPerm: false
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
