### ISSUE TITLE
Need help in cooldowns [maybe bug]

### ISSUE THREAD

**Issue by Everts0n** [Zrips/CMI#8458]
How can I make different cooldowns on gm 1 (myself) and gm 1 (another player), I tried this but it doesn't work:
```
Cooldowns:
  Enabled: true
  List:
  - cmi gm 1:5
  - cmi gm 1_:300
```
  
  I also tried other varieties, but nothing works, maybe it's a bug.

**Comment by CloudeLecaw** [comment]
you made sure you dont have the bypass permissions set?
im not sure if this works for the deeper arguments
might it just work for
command  or command with Argument.
so what happens if you try

```
Cooldowns:
  Enabled: true
  List:
  - cmi gm:5
  - cmi gm_:300
 ```
 
   for the /cmi gm command itself.
?
