### ISSUE TITLE
Combat mode doesn't work

### ISSUE THREAD

**Issue by Nunchakin** [Zrips/CMI#8465]
### Description of Issue

When a player attacks another player it doesn't drag them into combat mode, instead there is only visible the bossbar health of that player.
![mc](https://github.com/Zrips/CMI/assets/151460657/d2304fbc-c668-4f23-bc40-f8fb51e437ee)

### Version Information

```shell
[10:37:19 INFO]: --------------------------------------------------
[10:37:19 INFO]: CMI plugin version: 9.6.10.4 SqLite
[10:37:19 INFO]: CMILib: 1.4.5.0
[10:37:19 INFO]: Server: Paper(416) 1.20.4-R0.1-SNAPSHOT-
[10:37:19 INFO]: CMI economy: Zapnuté Vault: 1.7.3-CMI CMI Chat: Zapnuté
[10:37:19 INFO]: Modules -> 57 enabled 2 disabled: tablist, votifier
[10:37:19 INFO]: --------------------------------------------------
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
Combat:
  # Defines combat timer to be used in particular features
  Timer: 30
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: false
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: true
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging players
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c⚔[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: false
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: false
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: true
    AllowedCommands:
    - msg
    - r
    - tell
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false



# Handles player combat system
# Applies for servers from 1.7.x and up
playerCombat: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
