### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by lDoomerl** [Zrips/CMI#8472]
### Description of Issue

If someone will type in the chat something with dot and $ it will spam some s**t
Exapmle: 1.Kla$ 
Result:
![image](https://github.com/Zrips/CMI/assets/136274899/da79ee80-e524-49f4-a12b-b20c46641fdf)

### Version Information

```shell
[13:17:41 INFO]: --------------------------------------------------
[13:17:41 INFO]: Версия плагина CMI: 9.6.10.4 Unknown  SqLite
[13:17:41 INFO]: CMILib: 1.4.5.0 
[13:17:41 INFO]: Сервер: Paper(35) 1.20.2-R0.1-SNAPSHOT-
[13:17:41 INFO]: CMI Экономика: Включено Vault: 1.7.3-b131(CMIEInjector) CMI Чат: Включено 
[13:17:41 INFO]: Модули -> 42 включено и 17 выключено: customMessages, tablist, armorstand, moneyCheque, skin, holograms, noTarget, paintingEditor, rideAnimation, bossBarCompass, deathMessages, disabledEnchants, ranks, playerCombat, votifier, headDrop, sitAnimation
[13:17:41 INFO]: --------------------------------------------------
```

### Errors

```shell
https://pastebin.com/aEyRQxy0
```

### Relevant Config Sections

```yaml
Chat config - https://pastebin.com/Gc6KZ7Rg
ChatFilter config - pastebin don't want tp publish it so I leave it here 

ChatFilter:
  Enabled: false
  Deny:
    ipBlock:
      Enabled: true
      Group: Advertising
      InformConsole: true
      Regex:
      - '[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,|_|\/)\s?([a-zA-Z]{2}|aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel)\b'
      - \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
      ReplaceWith: ''
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4advertising with: &r[message]'
      Commands: []
    mama:
      Enabled: false
      Group: Swearing
      InformConsole: true
      Regex:
      - (мать|маму|мамаш|мамочек|матерей|матери|мaму|мaмy|мамy|мaть|мaтерей)
      ReplaceWith: гараж
      BlockType: none
      includePrivateMessages: true
      msgToStaff: '&4Антипидор&f | &6[playerName] &4мамкоёбер сказал &c«[message]»'
      Commands:
      - asConsole! cmi titlemsg [playerName] &eМать не трогай! -keep:20
    osk:
      Enabled: true
      Group: Swearing
      InformConsole: true
      Regex:
      - (пидор|пидорас|пидорсы|шлюха|залупа|еблан|ебанат|хуйло|шлюхи|шалава|гнида|даун|Zenri)
      ReplaceWith: чел
      BlockType: none
      includePrivateMessages: true
      msgToStaff: '&4Антипидор&f | &6[playerName] &fоскорбляет, пидор сказал &c«[message]&f»'
      Commands:
      - asConsole! cmi titlemsg [playerName] &cБез оскорблений! -keep:20
    polit:
      Enabled: true
      Group: Swearing
      InformConsole: false
      Regex:
      - (путин|зеленский|залужный|ZV|ZOV|ZVO|azov|свинорейх|хохл|русня|русню|москал|москов|узкоглаз|негр|нигер|ниггер)
      ReplaceWith: тут могла быть ваша реклама
      BlockType: none
      includePrivateMessages: true
      msgToStaff: '&4Антипидор&f | &6[playerName] &fполито-пидор, сказал «&c[message]&f»'
      Commands:
      - asConsole! cmi titlemsg [playerName] &cБез политоты и расизма! -keep:20
  # List of regex filter to exlude from block list. Usefull if you want to block all ip/host address but want to allow usage of your own server.
  WhiteList:
  - meltarion.net
  - discord.com/meltarion
  - discord.gg/meltarion
  - https://discord.com/meltarion
  - https://discord.gg/meltarion
  - https://meltarion.net
  - vk.com/meltarion_network
  - https://vk.com/meltarion_network
  - mc.meltarion.net
  - mc.meltarion.ru
  - https://t.me/meltarion_news
  - https://boosty.to/minelandy
  - https://www.patreon.com/meltarion
  - boosty.to/minelandy
  - boosty.to/meltarion
  - patreon.com/meltarion
  - ah view
  DuplicatedMessagePrevention:
    # When set to true, plugin will prevent spaming of same or similar messages in short time range. Can be bypased with cmi.chatfilter.spambypass permission
    Use: true
    # How much in percentage message is counted as same
    Percentage: 80
    # Defines how often in seconds you can send same/similar message
    Interval: 60
    # How many commands you can repeat before stopped for cooldown
    MinAmount: 2
  Caps:
    # When nebaled we will try to prevent chat messages with multiple capitalized letters by defined criteria
    # Can be bypassed with cmi.chatfilter.capbypass permission node
    Filter: true
    # Defines amount of letters we can ignore
    # For example ':DDD' would be made of 2 letters with 3 capitalized letters which would make it 75% capitalized
    IgnoreUnder: 5
    # Amount in percentage of capitalized letters we should not cross over.
    # In example 'GOOD thing' would be 4 capitalized and 5 not, spaces gets ignored, whic makes it 44% capitalized and passes check
    Percentage: 70
    # List of commands you want to perform when player uses too many caps
    Commands:
    - asConsole! cmi titlemsg [playerName] &cНе капси! -keep:20
    # List of messages, excluding color codes, player can use even if it 100% capitalized
    WhiteList:
    - AFK
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
