### ISSUE TITLE
Flight problems + skins

### ISSUE THREAD

**Issue by saxonov80** [Zrips/CMI#8507]
### Description of Issue

The problem has not been resolved regarding the flight mode. When enabling skins, players fall and crash = rejoin the server, instead of staying in their place in flight mode, players fall and crash. We need some kind of solution. I have already written to you about this problem, please consider it again. Thank you.

### Version Information

```shell
[17:27:09 INFO]: ---------------------------------------------- ----
[17:27:09 INFO]: Версія плагіна CMI: 9.6.10.7 Velocity CMIBSqLite
[17:27:09 INFO]: CMILib: 1.4.5.2
[17:27:09 INFO]: Сервер: Purpur(2095) 1.20.2-R0.1-SNAPSHOT-
[17:27:09 INFO]: CMI Економіка: УвімкненоVault: 1.7.3-CMI(CMIEInjector)CMI Чат: Увімкнено
[17:27:09 INFO]: Модулі -> 55 увімкнено та 4 вимкнено: tablist, ranks, votifier, jail
[17:27:09 INFO]: ---------------------------------------------- ----
```

### Errors

```shell
No
```

### Relevant Config Sections

```yaml
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: true
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Possible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - world:survival
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - world:true
  - world_nether:true
  - world_the_end:true
  - world_spawn:false
  # If player will have cmi.worldlimit.elytra.bypass permission node, elytra flight will not be prevented
  # Players joining worlds with disable elytra flight will get their elytra dismounted if possible
  ElytraFlight:
  - worldName:False
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoof: true
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoofLimitations:
  - world-320
  - world_nether-128
  - world_the_end-256
  # If player will have cmi.worldlimit.god.bypass permission node, god mode wont be changed
  GodMode:
  - testWorld:False
  # Prevents particular entity spawn reasons in defined worlds. All possible reasons: NATURAL, JOCKEY, CHUNK_GEN, SPAWNER, EGG, SPAWNER_EGG, LIGHTNING, BUILD_SNOWMAN, BUILD_IRONGOLEM, BUILD_WITHER, VILLAGE_DEFENSE, VILLAGE_INVASION, BREEDING, SLIME_SPLIT, REINFORCEMENTS, NETHER_PORTAL, DISPENSE_EGG, INFECTION, CURED, OCELOT_BABY, SILVERFISH_BLOCK, MOUNT, TRAP, ENDER_PEARL, SHOULDER_ENTITY, DROWNED, SHEARED, EXPLOSION, RAID, PATROL, BEEHIVE, PIGLIN_ZOMBIFIED, SPELL, FROZEN, METAMORPHOSIS, DUPLICATION, COMMAND, CUSTOM, DEFAULT
  SpawnReasons:
    world:
    - None
    world_nether:
    - None
    world_the_end:
    - None
######################################   Skins   ##############################################

Skins:
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: false
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: true
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 1320
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with possible requests
  SkinRequestFrequency: 10
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
