### ISSUE TITLE
ServerSwitch Messages don't work

### ISSUE THREAD

**Issue by KoalaServers** [Zrips/CMI#8517]
### Description of Issue

Showing custom switched server messages don't work even though enabled, and all other bungee functions are working.

### Version Information

```shell
CMI: 9.6.10.7
CMILib: 1.4.5.2
Server: Paper(435) 1.20.4-R0.1-SNAPSHOT
```

### Errors

```shell
No errors present.
```

### Relevant Config Sections

```yaml
config.yml:
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: true
      # When enabled and you have bungeeserver with CMIB on it we will try to detect where player went and we will show switch server message instead of login if possible
      ServerSwitch: true

  
Locale_EN.yml:
  ServerSwitchOut: ' &6[playerDisplayName] &eswitched server to &6[serverName]'
  ServerSwitchIn: ' &6[playerDisplayName] &ecame from &6[serverName] &eserver'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
