### ISSUE TITLE
[message] not working in /msg

### ISSUE THREAD

**Issue by unnamed199cz** [Zrips/CMI#8521]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/69002814/034d746c-aa72-4566-92b1-5d6cca43fac1)

### Version Information

```shell
[18:02:29 INFO]: CMI: 9.6.10.7 SqLite
[18:02:29 INFO]: CMILib: 1.4.5.2 
[18:02:29 INFO]: Server: Paper 1.20.2-R0.1-SNAPSHOT-
[18:02:29 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[18:02:29 INFO]: Modules -> 38 enabled 21 disabled: spawnerProximity, cuffed, mirror, tablist, elytraExploit, elytraBoost, spawners, playerChatTag, elytraLaunch, bossBarCompass, coloredArmor, disabledEnchants, worldLimitsElytra, worldLimits, ranks, playerCombat, selection, votifier, headDrop, spawnerCharge, namePlates
```

### Relevant Config Sections

```yaml
gamerword:
      Enabled: true
      Group: Swearing
      InformConsole: true
      Regex:
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(e(\W|\d|_|)+)+(r(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(e(\W|\d|_|)+)+(r(\W|\d|_|)+)+
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(a(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(a(\W|\d|_|)+)+
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - \b(?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(e(\W|\d|_|)+)+(r(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(e(\W|\d|_|)+)+(r(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(a(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(a(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+(s(\W|\d|_|)+)+
      - (?i)(n(\W|\d|_|)+)+(i(\W|\d|_|)+)+(g(\W|\d|_|)+)+(g(\W|\d|_|)+)+
      ReplaceWith: '&c[Filtered]&r'
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] | &aN-word dropped. &4Shadowmute Enabled\n&cChat
        Filter > [message]'
      Commands:
      - shadowmute [playerName] 31556952
      - cmi mail send dexita_6 &6[playerName] &f> &c[message]
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
