### ISSUE TITLE
Hologram range distance

### ISSUE THREAD

**Issue by ghebia** [Zrips/CMI#8526]
### Description of Issue

iv tryied so many ways, the problem is this one

anytime i change the range and range extra it just not save it 

if i change in gui in game it work ( i set to 128 because i reallyt need this number ) but after plugin reload 

it go back to 64 but in yml it keep the value 128 

i tryied with cmi savel all tryied to edit with sv off manny ways

the holo just not showing up if you go further than 64 blocks away

### Version Information

```shell
[13:56:12 INFO]: --------------------------------------------------
[13:56:12 INFO]: CMI: 9.6.10.7 SqLite
[13:56:12 INFO]: CMILib: 1.4.5.2 
[13:56:12 INFO]: Server: Paper(405) 1.20.4-R0.1-SNAPSHOT-
[13:56:12 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
[13:56:12 INFO]: Modules -> 58 enabled 1 disabled: votifier
[13:56:12 INFO]: --------------------------------------------------
```

### Errors

```shell
no errors
```

### Relevant Config Sections

```yaml
Holograms:
  # Defines in milliseconds how often to check if player entered holograms trigger area
  # Bigger numbers can help slightly lower server load
  # This is not essential to keep in low numbers
  CheckInterval: 2000
  Defaults:
    # Default value for hologram view range
    # This defines from how far holograms will appear for the player or when they will disapear
    viewRange: 200
    # Defines default update interval
    # Bigger this number is better performance we will have
    updateRange: 200
    updateInterval: 1
    # Defines default page change interval
    # When value is set to 0 or lower, pages will not be changed
    pageChangeInterval: 0.0
    # Possible values: down, up
    # Defines if we should place lines up from starting position or down
    placeUp: true








@@@@@@@@@@@@@




1$3:
  Loc: world;291.01;64.98;517.69
  Interval: 1.0
  HoverParticles:
    Count: 1
  Range: 64
  RangeExtra: 64
  Spacing: 0.24
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: LEFT
    TAlpha: 255
    Shadow: true
    Yaw: 90
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 0
    ScaleW: 4.88
    ScaleH: 4.88
    SL: 15
    BL: 15
    IScale: 1.1
    IPitch: -60
    IYaw: 70
  Lines:
  - '{#80ff00}To teleport{#ff004d}:1000$'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
