### ISSUE TITLE
ph! doesn't work when triggered from console?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8528]
### Description of Issue

Hello, I have this custom alias:
```
  gracechecknewbie:
    Cmds:
    - check:%deluxecombat_has_protection%==true#!
    - asConsole! ph! cmi bossbarmsg $1 &cDamage Protection &6ends in %deluxecombat_protection_time_remaining%! &6Disable via &c/grace disable -a:20 -sec:-600 -cmd:"gracechecknewbie $1"
    Perm: true
    Tab: false
```

It normally works (the countdown from %deluxecombat_protection_time_remaining%) when I execute the command standalone from in-game on my own so like /gracechecknewbie <my_name>, but when it's executed from the console, it doesn't work and the timer is stuck on the time it got executed I guess.
![image](https://github.com/Zrips/CMI/assets/18662086/a0d6b5b9-a6b0-442e-8bfc-237e1e5cfe74)

The first one started from console - is stuck
the second one starter from in-game

I tried using ptarget! and so, but it didn't seem to work, any idea on how to fix this issue?
Note, with ptarget! it doesn't even display the bossbar from some reason

### Version Information

```shell
[17:34:24 INFO]: CMI: 9.6.10.7 Unknown  SqLite
[17:34:24 INFO]: CMILib: 1.4.5.1 -> 1.4.5.2
[17:34:24 INFO]: Server: Purpur(2062) 1.20.1-R0.1-SNAPSHOT-
[17:34:24 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[17:34:24 INFO]: Modules -> 46 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, deathMessages, disabledEnchants, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[17:34:24 INFO]: -----------------------------------------------
```

Btw due to this I also created https://github.com/Zrips/CMI/issues/8529, cause it disappears after player reconnects

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
what ph! should be? its no part of specialized commands

**Comment by bobhenl** [comment]
Even with your settings, the counter is stuck (placeholder isn't updated, so it's not dynamic), but when I executed as player by me - like /gracechecknewbie NAME (as me in-game), it worked, but it doesn't seem working when it's executed from EventCommands, that's maybe the issue?
 ``` 
joinServer:
  Enabled: true
  Commands:
  - delay! 8
  - gracechecknewbie [playerName]
 ```
