### ISSUE TITLE
CMI problem with ShopGUI+

### ISSUE THREAD

**Issue by Alvinatorovec** [Zrips/CMI#8536]
### Description of Issue

Hello, i am here for help, with problem with currence on cmi between shopguiplus.. i am using plugins years.. but this problem is relative new, i ask for support for shoguiplus plugin and they told me that problem must be in CMI, on photos are my balance /money and balance on shop but it must be same balance and it is different... what is wrong? thanks for help

![image](https://github.com/Zrips/CMI/assets/162869544/fdd21149-9c65-4e22-8e2f-e47bd28720f7)
![image2](https://github.com/Zrips/CMI/assets/162869544/ca17226a-2e07-4a7c-aca3-8c43918c31ea)

### Version Information

```shell
[18:41:40 INFO]: CMI plugin version: 9.6.10.9 SqLite
[18:41:40 INFO]: CMILib: 1.4.5.2
[18:41:40 INFO]: Server: Paper(450) 1.20.4-R0.1-SNAPSHOT-
[18:41:40 INFO]: CMI economy: Zapnuté Vault: 1.7.3-b(CMIEInjector) CMI Chat: Zapnuté
[18:41:40 INFO]: Modules -> 59 enabled 0 disabled:
```

### Relevant Config Sections

```yaml
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
  Cheque:
    # Determines max amount of cheque player can create
    # Set it to 0 to remove limit
    MaxValue: 1.0E8
    # If set to true player will be required to hold peace of paper to create cheque
    Paper: true
    # When set to true player will be required to have cmi.command.cheque.withdraw permission node to withdraw cheque
    Permission: false
    # Should we allow checque usage in creative mode
    # If you have creative server, keep this at false or players could start duplicating items
    InCreative: false
    # Should we accept old cheque item stacks with non encoded data in them
    # Keep it at false for most security
    AcceptNotEncoded: false
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: true
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: false
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    - debt-
    - debt_
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
    # Set to 0 or lower to disable this feature
    # Time in days of player being offline to exclude from being included in balance top list
    ExcludeInactive: 0
  Global:
    # Starting amount of money players will have
    StartingAmount: 100.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E8
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 1.0
    # Defines if you want to allow payments with fractions
    # if this is disabled then payments will be limited to whole numbers and in case player provides number with fraction we will round number down
    Fractions: false
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: €
    # Format used for displaying money
    MoneyFormat: '###,##0.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # This format is only for amounts which gets defines suffix like '1.23k' while numbers lover than 1k will use MoneyFormat
    shortNumbersFormat: '###,##0.0'
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: false
    # Placing of currency symbol
    Placing: '[money][symbol]'
FileSave:
  # Change this to true only if you have issues with drives I/O and you need to save players files in async mode to lower waiting time for mc server
  Async: false
```

### Relevant Plugins

Vault 1.7.3, ShopGUI+ 1.95.0, CMIEInjector 1.0.2.3, CMILib 1.4.5.2, CMI 9.6.10.9

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
