### ISSUE TITLE
Custom Alias Broke with CMI 9.6.11.0 and 9.6.11.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8548]
### Description of Issue
We use a lot of more specific and bigger custom aliases where we use a lot of checks.
Since two Versions these Custom Aliases broke...why ever.
It looks like the conditions get ignored and custom aliases triggers ALL lines not matter if conditions are true or not.
OR
all conditions after $1 like if $2 was not got ignores and command is fired? But it it tells me the wrong useage line then..
that normaly is triggered if $1==null...

**Note:** This Custom Alias WAS working without issues before the CMI Update.

Also the Line for $2 is posted where the §2 was not emptry
`msg! [playerName]  &b&l$2 &6war Rang:&6 &c&l%parseother_{$2}_{cmi_user_group}% &6und hat jetzt den Rang:&6&2&l$1&6.`
This one... should not even get triggered if $2==null but it was 

![image](https://github.com/Zrips/CMI/assets/12080017/a1d6997b-6d0b-4114-8eee-d0b8b75bee04)

I Also tried with /gruppe admin Cloude_Lecaw to see what happens if $2 is set.. but aggain it triggers to much commands and does not look for my conditions correcly anymore.
![Snag_231fc49](https://github.com/Zrips/CMI/assets/12080017/9f4fe1ed-e6f6-4aa0-a479-103617ec41af)

### Version Information
![Snag_224c402](https://github.com/Zrips/CMI/assets/12080017/100989df-755e-4b34-b81b-a077265d6cfd)

### Errors
Shown in Console: You see all commands got executed... 
```shell
[23:58:29 INFO]: Cloude_Lecaw issued server command: /gruppe admin
[23:58:29 INFO]: Error in command syntax. Check command help.
[23:58:29 INFO]: User groups set!
[23:58:29 INFO]: Error in command syntax. Check command help.
[23:58:29 INFO]: Es wurde kein Spieler mit diesem Namen gefunden!
[23:58:29 INFO]: Es wurde kein Spieler mit diesem Namen gefunden!
[23:58:29 INFO]: Permission "cmi.customalias.staffrank" added!
[23:58:29 INFO]: Es wurde kein Spieler mit diesem Namen gefunden! (nick -> )
[23:58:29 INFO]: Die Tabliste wurde aktualisiert.

[00:40:49 INFO]: Cloude_Lecaw issued server command: /gruppe admin Cloude_Lecaw
[00:40:49 INFO]: User groups set!
[00:40:49 INFO]: User groups set!
[00:40:49 INFO]: Permission "cmi.customalias.staffrank" added!
[00:40:49 INFO]: Permission "cmi.customalias.staffrank" added!
[00:40:50 INFO]: Die Tabliste wurde aktualisiert.
```

### Relevant Config Sections
CustomAlias.yml
```yaml
CustomAlias:
  gruppe:
    Cmds:
    - check:$1==admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! asConsole! pex user $2 group set $1
    - check:$1==admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! msg! $2 &b&l[senderName] &6hat dir den Rang:&6 &2&l$1 &6gegeben.
    - check:$1==admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! msg! [playerName] &b&l$2 &6war Rang:&6 &c&l%parseother_{$2}_{cmi_user_group}% &6und hat jetzt den Rang:&6&2&l$1&6.
    - check:$1==admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! asConsole! pex user [playerName] group set $1
    - check:$1==admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! msg! [playerName] &b&lDu &6warst Rang:&6 &c&l%cmi_user_group% &6und bist jetzt Rang:&6 &2&l$1&6.
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2!=null|%cmi_user_name%! asConsole! pex user $2 add cmi.customalias.staffrank
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2!=null|%cmi_user_name%! asConsole! cmi usermeta $2 add aktuellerstaffrank $1 -s
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2!=null|%cmi_user_name%! asConsole! cmi usermeta $2 add aktuellerstaffrankstatus aktiviert -s
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! asConsole! pex user $2 remove cmi.customalias.staffrank
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! asConsole! cmi usermeta $2 remove aktuellerstaffrank -s
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! asConsole! cmi usermeta $2 remove aktuellerstaffrankstatus-s
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2==null|%cmi_user_name%! asConsole! pex user [playerName] add cmi.customalias.staffrank
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2==null|%cmi_user_name%! asConsole! cmi usermeta [playerName] add aktuellerstaffrank $1 -s
    - check:$1==admin|builder|coowner|dev|guard|mod|owner|senior|testgamer! check:$2==null|%cmi_user_name%! asConsole! cmi usermeta [playerName] add aktuellerstaffrankstatus aktiviert -s
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! asConsole! pex user [playerName] remove cmi.customalias.staffrank
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! asConsole! cmi usermeta [playerName] remove aktuellerstaffrank -s
    - check:$1==gast|gefangener|spieler|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! asConsole! cmi usermeta [playerName] remove aktuellerstaffrankstatus -s
    - check:$1==guard! check:$2!=null|%cmi_user_name%! asConsole! cmi nick {#orange>}$2{#yellow<} $2 -s
    - check:$1==admin! check:$2!=null|%cmi_user_name%! asConsole! cmi nick {#cc2500>}$2{#e6c8b8<} $2 -s
    - check:$1==builder|coowner|dev|gast|gefangener|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2==null|%cmi_user_name%! asConsole! cmi nick %cmi_user_cleannickname% [playerName] -s
    - check:$1==builder|coowner|dev|gast|gefangener|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! check:$2!=null|%cmi_user_name%! asConsole! cmi nick $2 $2 -s
    - check:$1==guard! check:$2==null|%cmi_user_name%! asConsole! cmi nick {#orange>}%cmi_user_cleannickname%{#yellow<} [playerName] -s
    - check:$1==admin! check:$2==null|%cmi_user_name%! asConsole! cmi nick {#cc2500>}%cmi_user_cleannickname%{#e6c8b8<} [playerName] -s
    - check:$1!=null|admin|builder|coowner|dev|gast|gefangener|guard|mod|owner|senior|spieler|testgamer|testvip|tutdone|vip|vipv|vipmini! msg! [playerName] &cDu musst eine gültige Gruppe angeben!\n&b Benutzung&c:&c &c/&cgruppe &c[&cGruppenname&c]&c (Spielername)
    - check:$1==null! msg! [playerName] &cDu musst eine gültige Gruppe angeben!\n&b Benutzung&c:&c &c/&cgruppe &c[&cGruppenname&c]&c (Spielername)\n&e Du bist in der Gruppe:&e &6 &c&l%cmi_user_group%&e.
    - delay! 1
    - check:$1!=null! asConsole! cmi tablistupdate
    Perm: true
    Tab: true
    CustomTabs:
    - 'Admin,Builder,CoOwner,Dev,Gast,Gefangener,Guard,Mod,Owner,Senior,Spieler,TestGamer,TestVIP,TuTDone,VIP,VIPV,VIPmini, [playerName]'
```

###Currentl ONLY Solution
Downgrade to CMI 9.6.10.9 - When Server is downgraded to 9.6.10.9 the custom alias work fine.

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
