### ISSUE TITLE
Incorrect result when returning the value of a papi placeholder in a specialized command.

### ISSUE THREAD

**Issue by GhostHost256** [Zrips/CMI#8558]
### Description of Issue

When using the cmi placeholder command to parse %coinsengine_server_balance_raw_redteam% it works as expected, but when using it the specialized command in an alias check: it does not.

Command:
/cmi placeholder parse %coinsengine_server_balance_raw_redteam%
Result:
%.coinsengine_server_balance_raw_redteam.% by Papi result 1040

Alas:
  team_checkforwin3:
    Cmds:
    - check:%cmi_equationint_{coinsengine_server_balance_raw_redteam}/1%>1000! asConsole! cmi staffmsg &4Red &fYes
    - check:%cmi_equationint_{coinsengine_server_balance_raw_redteam}/1%<1000! asConsole! cmi staffmsg &4Red &fNo
Result:  No

Another Example:
Command: 
/cmi placeholders parse %cmi_equationint_{coinsengine_server_balance_raw_redteam}/1%
Result:
%.cmi placeholders parse %cmi_equationint_1040}/1.% by CMI result 0

### Version Information

```shell
CMI: 9.6.11.2 Unknown SqLite
CMILib: 1.4.5.2
Server: Paper(451) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 31 enabled 28 disabled: spawnerProximity, cuffed, mirror, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, shulkerBackpack, headDrop, spawnerCharge, homeInteractions, hpBossBar, anvilRenameColor, spawners, paintingEditor, dynamicSigns, durabilityLoss, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, silentChest
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
team_checkforwin:
    Cmds:
    - asConsole! cmi staffmsg Checking for winner...
    - delay! 3
    - statement:red! check:%coinsengine_server_balance_raw_redteam%>999!
    - statement:blue! check:%coinsengine_server_balance_raw_blueteam%>999!
    - if:red! asConsole! red_wins
    - if:blue! asConsole! blue_wins
    - if:red! asPlayer! red_world
    - if:blue! asPlayer! blue_world
    - if:red@! asConsole! cmi staffmsg &4Red &fNo
    - if:blue@! asConsole! cmi staffmsg &9Blue &fNo
    - delay! 1
    - asConsole! cmi staffmsg Check complete

  team_checkforwin3:
    Cmds:
    - check:%cmi_equationint_{coinsengine_server_balance_raw_redteam}/1%>1000! asConsole! cmi staffmsg &4Red &fYes
    - check:%cmi_equationint_{coinsengine_server_balance_raw_blueteam}/1%>1000! asConsole! cmi staffmsg &9Blue &fYes
    - check:%cmi_equationint_{coinsengine_server_balance_raw_redteam}/1%<1000! asConsole! cmi staffmsg &4Red &fNo
    - check:%cmi_equationint_{coinsengine_server_balance_raw_blueteam}/1%<1000! asConsole! cmi staffmsg &9Blue &fNo
```

### Relevant Plugins

CoinsEngine 2.2.0.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
