### ISSUE TITLE
Cmi Hologram Error

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#8568]
### Description of Issue

![QQ截图20240327094622](https://github.com/Zrips/CMI/assets/50692210/30f72314-6a1a-4f7f-8bf3-235aa83554ca)
Unable to wrap

### Version Information

```shell
cmi：9.7.0.1
cmilib：1.4.6.1
server：purpur（2160）1.20.4-R0.1-SNAPSHOT
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
排行榜-在线:
  Loc: world;-36.0;116.31;-26.46
  HoverParticles:
    Count: 1
  Range: 8
  RangeExtra: 16
  Spacing: 0.24
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: VERTICAL
    Align: CENTER
    TAlpha: 230
    Shadow: true
    BColor: '{#Black}'
    BAlpha: 125
    SL: -1
    BL: -1
  Lines:
  - '&7[&f&l排行榜&7] &7(&6&l在线&7)'
  - '&7[&c1&7] %ajlb_lb_statistic_hours_played_1_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_1_weekly_value%'
  - '&7[&c2&7] %ajlb_lb_statistic_hours_played_2_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_2_weekly_value%'
  - '&7[&c3&7] %ajlb_lb_statistic_hours_played_3_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_3_weekly_value%'
  - '&7[&c4&7] %ajlb_lb_statistic_hours_played_4_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_4_weekly_value%'
  - '&7[&c5&7] %ajlb_lb_statistic_hours_played_5_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_5_weekly_value%'
  - '&7[&c6&7] %ajlb_lb_statistic_hours_played_6_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_6_weekly_value%'
  - '&7[&c7&7] %ajlb_lb_statistic_hours_played_7_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_7_weekly_value%'
  - '&7[&c8&7] %ajlb_lb_statistic_hours_played_8_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_8_weekly_value%'
  - '&7[&c9&7] %ajlb_lb_statistic_hours_played_9_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_9_weekly_value%'
  - '&7[&c10&7] %ajlb_lb_statistic_hours_played_10_weekly_name% &7- &3%ajlb_lb_statistic_hours_played_10_weekly_value%'
```

### Relevant Plugins

Valut-1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
