### ISSUE TITLE
Hat blocking hat items & enchanted don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8589]
### Description of Issue

Hello, from thie hat block seciton only itemlore option works, others seem to don't work:
```

      # When enable we wont allow to equip items which are not hat type
      NoneHatItems: true
      # When enable we wont allow to equip none hat items with enchant on it
      NoneHatEnchanted: true
```

Give yourselves diamond sword, enchant it (give & enchant command), and then try to put it on the head, and you can, even when it should be blocked due to enchant and because it's not hat type item

So both of these don't work and I don't have any bypass permission

### Version Information

```shell
[19:41:25 INFO]: --------------------------------------------------
[19:41:25 INFO]: CMI: 9.7.0.2 Unknown  SqLite
[19:41:25 INFO]: CMILib: 1.4.6.1 
[19:41:25 INFO]: Server: Purpur(2159) 1.20.4-R0.1-SNAPSHOT-
[19:41:25 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[19:41:25 INFO]: Modules -> 46 enabled 13 disabled: customMessages, mirror, tablist, playerChatTag, deathMessages, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[19:41:25 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Hat:
    Block:
      # When enabled we will not allow to place items into head slot if item has custom lore
      # Doesn't apply to helmet items
      WithLore: true
      # When enable we wont allow to equip items which are not hat type
      NoneHatItems: true
      # When enable we wont allow to equip none hat items with enchant on it
      NoneHatEnchanted: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
By any chance player has access to cmi.inventoryhat.bypass permission node? You can double check permission access with **/cmi haspermission cmi.inventoryhat.bypass Zhax** just incase player inherited bypass permission node from somewhere else

**Comment by bobhenl** [comment]
![image](https://github.com/Zrips/CMI/assets/18662086/cf9f5436-5520-4923-8230-df4d787e3108)
Doesn't have permission, also it's not tab completing the names btw
![image](https://github.com/Zrips/CMI/assets/18662086/feff93ef-5bea-4584-b814-f23e1c61e97f)
![image](https://github.com/Zrips/CMI/assets/18662086/4835ead3-91a8-41c0-bfcb-bd3ed2680bb3)

**Comment by Zrips** [comment]
What is the remaining config for hat command? 
```
  Hat:
    Block:
      # When enabled we will not allow to place items into head slot if item has custom lore
      # Doesn't apply to helmet items
      WithLore: true
      # When enable we wont allow to equip items which are not hat type
      NoneHatItems: true
      # When enable we wont allow to equip none hat items with enchant on it
      NoneHatEnchanted: true
    Allow:
      # When enabled we will allow player to put on mob head without cmi.inventoryhat permission node
      # When disabled player will need to have cmi.inventoryhat to put on mob heads as hats
      MobHeads: true
    # List of materials to be allowed on players head
    WhiteList:
    - bedrock
```
This is the full one. By any chance you have something weird set for whitelist?

**Comment by bobhenl** [comment]
I have only this:
```
  Hat:
    Block:
      # When enabled we will not allow to place items into head slot if item has custom lore
      # Doesn't apply to helmet items
      WithLore: true
      # When enable we wont allow to equip items which are not hat type
      NoneHatItems: true
      # When enable we wont allow to equip none hat items with enchant on it
      NoneHatEnchanted: true
    Allow:
      # When enabled we will allow player to put on mob head without cmi.inventoryhat permission node
      # When disabled player will need to have cmi.inventoryhat to put on mob heads as hats
      MobHeads: true
    # List of materials to be allowed on players head
    WhiteList:
    - bedrock
 ```

**Comment by Zrips** [comment]
So weird, tested it with multiple variations on a clean server, player had no ability to place items on his head without permission and with that setup. Can you test this with CMI only just to be sure that its not another plugin which interferes?

**Comment by bobhenl** [comment]
@Zrips I've tested with only these plugins:
- CMI, CMILib, LuckPerms, PlaceholderAPI, spark, Vault

And it's still happening, even when I gave myself only cmi.command.hat 
and I have these settings there:
```
  Hat:
    Block:
      # When enabled we will not allow to place items into head slot if item has custom lore
      # Doesn't apply to helmet items
      WithLore: false
      # When enable we wont allow to equip items which are not hat type
      NoneHatItems: true
      # When enable we wont allow to equip none hat items with enchant on it
      NoneHatEnchanted: true
    Allow:
      # When enabled we will allow player to put on mob head without cmi.inventoryhat permission node
      # When disabled player will need to have cmi.inventoryhat to put on mob heads as hats
      MobHeads: true
    # List of materials to be allowed on players head
    WhiteList:
    - bedrock
 ```

I tried even reset to the default configuration but it didn¨t work. Btw using the newest Purpur (1.20.4), not sure if it can affect it somehow
