### ISSUE TITLE
placeholder dont get parsed with ptarget when used from Console.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8611]
### Description of Issue
placeholder dont get parsed with ptarget when used from Console.

Here a little example: a custom alias
```
  test_test:
    Cmds:
    - asConsole! ptarget:$1! msg! Cloude_Lecaw Testwert - %cmi_user_meta_pingponggewinn%
    Perm: true
    Tab: true
    CustomTabs:
    - '[playerName]'
  ```
i attached two players a usermeta i called cmi_user_meta_pingponggewinn

Ingame:
`/test_test Player1`             ->   i get the placeholder from Player1    -> OK
`/test_test Player2`             ->   i get the placeholder from Player2    -> OK

now i tried the command from console
`/test_test Player1`             ->   i get the placeholder %cmi_user_meta_pingponggewinn% printed to chat  -> NOT OK  -> should be the placeholder of player1 like in first test.
`/test_test Player1`             ->   i get the placeholder %cmi_user_meta_pingponggewinn% printed to chat  -> NOT OK  -> should be the placeholder of player2 like in first test.
![Snag_39a4a62](https://github.com/Zrips/CMI/assets/12080017/ff0727fb-c9da-4fc3-999c-b4e5fe0c55a3)

### Version Information
![Snag_398b172](https://github.com/Zrips/CMI/assets/12080017/2dfb5d6d-6b26-4f52-84e5-a46bdae777a8)

### Relevant Config Sections
```yaml
The CustomAlias

CustomAlias:
  test_test:
    Cmds:
    - asConsole! ptarget:$1! msg! Cloude_Lecaw Testwert - %cmi_user_meta_pingponggewinn%
    Perm: true
    Tab: true
    CustomTabs:
    - '[playerName]'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
