### ISSUE TITLE
allPlayers! doesnt work if line doesnt start with it.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8623]
### Description of Issue
We made a vanish custom alias. and i tryied to add an all variable
i noticed when allPlayer! is used after the check conditions then it only works one time. instead off to all player

What works:
`allPlayers! cmi vanish [allPlayers] off`

What desnt work:
`check:$1==all! perm:cmi.customalias.admintabfix! allPlayers! cmi vanish [allPlayers] off`

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/33cccd5b-b810-4dd1-bc4c-15e53b3c2af2)

### The CustomAlias we use:
```yaml
  tabfix:
    Cmds:
    - check:$1!=null|%cmi_user_name%|all! perm:cmi.customalias.usertabfix! perm:cmi.customalias.admintabfix@! msg! [playerName] &6Du kannst diesen Befehl nur auf dich selbst anwenden!
    - check:$1==all! perm:cmi.customalias.usertabfix! perm:cmi.customalias.admintabfix@! msg! [playerName] &6Du kannst diesen Teil des Befehls nicht benutzen.
    - check:$1==null|%cmi_user_name%! perm:cmi.customalias.usertabfix! perm:cmi.customalias.admintabfix@! asConsole! cmi vanish [playerName] on
    - check:$1==null|%cmi_user_name%! perm:cmi.customalias.admintabfix! asConsole! cmi vanish [playerName] on
    - check:$1!=null|%cmi_user_name%|all! perm:cmi.customalias.admintabfix! asConsole! cmi vanish $1 on
    - check:$1==all! perm:cmi.customalias.admintabfix! allPlayers! cmi vanish [allPlayers] on
    - delay! 0.1
    - check:$1==null|%cmi_user_name%! perm:cmi.customalias.usertabfix! perm:cmi.customalias.admintabfix@! asConsole! cmi vanish [playerName] off
    - check:$1==null|%cmi_user_name%! perm:cmi.customalias.admintabfix! asConsole! cmi vanish [playerName] off
    - check:$1!=null|%cmi_user_name%|all! perm:cmi.customalias.admintabfix! asConsole! cmi vanish $1 off
    - check:$1==all! perm:cmi.customalias.admintabfix! allPlayers! cmi vanish [allPlayers] off
    - delay! 0.2
    - check:$1==null|%cmi_user_name%! perm:cmi.customalias.usertabfix! perm:cmi.customalias.admintabfix@! asConsole! cmi tablistupdate
    - perm:cmi.customalias.admintabfix! asConsole! cmi tablistupdate
    Perm: true
    Tab: true
    CustomTabs:
    - 'all,[playername]'
```

### Reproduce:
Try /tabfix all with the customalias above. You will see it will only execute it once instead of aspected allPlayers!

A more simple Custom Alias work fine like:
```
  tabfix_all:
    Cmds:
    - allPlayers! cmi vanish [allPlayers] on
    - delay! 0.1
    - allPlayers! cmi vanish [allPlayers] off
    - delay! 0.2
    - asConsole! cmi tablistupdate
    Perm: true
    Tab: true
    CustomTabs:
    - '[playername]'
 ```

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
