### ISSUE TITLE
Totem doesn't work in the end and nether after turn on RemoveFromInventory

### ISSUE THREAD

**Issue by angushushu** [Zrips/CMI#8628]
### Description of Issue

```
Totem:
  RemoveFromInventory: true
  ProtectFromVoid: true
```
Totem in inventory doesn't work as expected in the void of the end and nether.
Expected behavior
- totem triggered
- enter cooldown
- player teleported to respawn point

What happens now:
- player dies
- enter cooldown
- no teleportation
![OKXW$_)D_5QOU I8Q8{VF6K](https://github.com/Zrips/CMI/assets/23127549/438f1f2f-53c8-4569-bf29-4c5f4cb7f3dd)

### Version Information

```shell
folia 1.20.1
cmi 9.7.0.5
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: true
    Time: 10
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: true
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

### Relevant Plugins

cmilib 1.4.6.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
