### ISSUE TITLE
Skin doesn't automatically apply with CMI for an offline server

### ISSUE THREAD

**Issue by mchungy** [Zrips/CMI#8637]
### Description of Issue

Whenever I conduct a server restart, the skin just goes back to the Minecraft Default Skin (Steve) unless the player enters /skin off or /skin (username).

### Version Information

```shell
[18:13:36 INFO]: CMI: 9.7.0.6 SqLite
[18:13:36 INFO]: CMILib: 1.4.6.2
[18:13:36 INFO]: Server: Paper(47) 1.20.4-R0.1-SNAPSHOT-
[18:13:36 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[18:13:36 INFO]: Modules -> 56 enabled 3 disabled: tablist, holograms, cmiPlaytime
```

### Errors

_None_

### Relevant Config Sections

```yaml
Skins:
  # Applies skin to player automatically on his login to server if he doesnt have one already set
  # This will always set to skin by target player name
  AutoApply: true
  # Sets player sking to Steve when turning skin off and lets server to handle it
  # If its false, then skin will be changed to online one
  SteveOnOff: false
  # Requests from player specific permission for that skin cmi.command.skin.perm.[skinName]
  RequireSpecificPerm: false
  # Defines time in minutes how offten we want to update skin information from online Mojang servers
  # Keep in mind that your server can only send 1 request every minute, so keep it at a decent amount, hour or more
  # So if you have this set to 1 hour, then player skin information will be updated if player old skin information is older then 1 hour
  # This only triggers when player joins server or changes skin manually
  SkinUpdateTimer: 1320
  # Defines time in minutes how offten we want to send requests to Mojang servers
  # This is to limit amount of requests in specific time to avoid cluter with possible requests
  SkinRequestFrequency: 1
```

### Relevant Plugins

_None_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
