### ISSUE TITLE
WarmUp bossbar

### ISSUE THREAD

**Issue by FireFrogGGG** [Zrips/CMI#8644]
How to change color of warmup bossbar? I already read wiki, but I don't find anything about this.

**Comment by mrfloris** [comment]
Note sure it's possible? I see the locale has an entry for it, to color the text, but not the bar.
```yaml
  WarmUp:
    canceled: '&eCommand was cancelled due to your movement'
    counter: '!actionbar!&6--> Wait &e[time] &6seconds <--'
    DontMove: '!title!&6Don''t move!!subtitle!&7Wait &c[time] &7seconds'
    Boss:
      DontMove: '&4Don''t move for &7[autoTimeLeft] &4seconds!'
      WaitFor: '&4Wait for &7[autoTimeLeft] &4seconds!'
```
And I do not see a config.yml option for it.
