### ISSUE TITLE
player tagging (with tabcomplete) did not work with CMI chat enabled

### ISSUE THREAD

**Issue by CactusTheGuy** [Zrips/CMI#8655]
### Description of Issue

- player tagging, tabcomplete with @, the color on tagged name and CommandOnTag not working
- CMI chat is enabled
- no error/warning is visible on console when tagging players

Note: Paper(486) 1.10.4-R0.1 is not used due to it break some of my plugins

### Version Information

```shell
CMI: 9.7.1.1 SqLite
CMILib: 1.4.6.3 
Server: Paper(485) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 52 enabled 7 disabled: coloredArmor, hpBossBar, ranks, votifier, shulkerBackpack, paintingEditor, bossBarCompass
```

### Errors

```shell
No error visible on console
```

### Relevant Config Sections

```yaml
1. Chat.yml (line 173 to 190)

  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&b'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound entity_experience_orb_pickup:3:1 [playerName] -s
    - asConsole! cmi toast [playerName] -t:goal -icon:writable_book [senderName] mentioned you!
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false

2. Modules.yml (line 78)

# Handling of player tagging in chat and tabcomplete with @
# Applies for servers from 1.7.x and up
playerChatTag: true
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
