### ISSUE TITLE
Jail wasting food

### ISSUE THREAD

**Issue by LadyUnicornEJG** [Zrips/CMI#8662]
### Description of Issue

Players sent to jail hungry enough to eat can consume food from their hotbar, but no hunger gets restored. This can be done indefinitely, wasting however much food they have on them.

### Version Information

```shell
[08:51:57 INFO]: --------------------------------------------------
[08:51:57 INFO]: CMI: 9.7.2.0 SqLite
[08:51:57 INFO]: CMILib: 1.4.7.1
[08:51:57 INFO]: Server: Paper(485) 1.20.4-R0.1-SNAPSHOT+
[08:51:57 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[08:51:57 INFO]: Modules -> 57 enabled 2 disabled: tablist, votifier
[08:51:57 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 0
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: true
  # Do you want to prevent players damage while he is in jail
  PreventDamage: true
  # Do you want to prevent players hunger while he is in jail
  PreventHunger: true
  Commands:
    # Commands to be performed when player gets jailed
    OnJail:
    - ''
    # Commands to be performed when player gets unjailed
    OnUnJail:
    - ''
  WhiteListedCmds:
  - cmi msg
  - cmi reply
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
