### ISSUE TITLE
Warmup problem!

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8717]
### Description of Issue

Latest  CMI have problem with /spawn command(when using warmup). Not working for non admin players. 
No errors in console.

### Version Information

```shell
CMI-9.7.2.6
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by tgoetzjr** [comment]
up vote

**Comment by eternitymoe** [comment]
Same issue with CMI version:
CMI 9.7.2.6 MySQL
CMILib: 1.4.7.8
on server git-Paper-409 (MC: 1.20.4)

**Comment by Baktus79** [comment]
This is a problem with all commands where warmup is used. The countdown starts but the command is not executed. By turning off the warmup feature or removing the command from the warmup list, the commands work as usual.

**My settings:**
```yaml
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  BossBarInfo:
    Enabled: true
    Color: blue
    Segments: '1'
  List:
  - cmi back:3:false
  - cmi home :3:false
  - cmi warp :3:false
  - cmi spawn:3:false
  - cmi rt:3:false
```
