### ISSUE TITLE
CMI Portal Particle Effects Not Saving

### ISSUE THREAD

**Issue by rynstwrt** [Zrips/CMI#8724]
### Description of Issue

CMI portal particle effects will change when using /portals edit, but when the server restarts or /cmi reload is ran, the particles reset and do not save.

### Version Information

```shell
I am running my Minecraft server on MC version 1.20.4 with CMI 9.7.2.8 and CMILib 1.4.7.8 (both the most recent version).
```

### Relevant Config Sections

```yaml
Here is a sample of a portal in my Portals.yml file. The Sculk Soul effect does not stay.

  survivalshop:
    Loc: -125.0:-60.0:375.0:-123.0:-54.0:375.0
    enabled: true
    effect: Sculk Soul
    color: 8224125
    showParticles: true  
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 30
    commandsWithoutTp: true
    commands:
    - warp [playerName] shop
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
