### ISSUE TITLE
Issue with Opening Menu via Portal

### ISSUE THREAD

**Issue by MCE-MatchaMC** [Zrips/CMI#8726]
### Description of Issue

After creating a teleportation portal using "/cmi portals" and setting the portal trigger command to "openmenu menu.yml [playerName]", upon entering the portal, only special effects are generated without opening the menu as expected.

### Version Information

```shell
Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
Plugin Version: CMI-9.7.2.9、CMILib1.4.7.9
```

### Errors

```shell
No error logs were generated.
```

### Relevant Config Sections

```yaml
world:
  生存大門:
    Loc: -2.0:201.0:23.0:2.0:205.0:23.0
    enabled: true
    effect: Dust
    color: 8224125
    showParticles: true
    kickBack: true
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 20
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - openmenu menu.yml [playerName]
```

### Relevant Plugins

bettergui-9.6-shaded

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
