### ISSUE TITLE
Next and prev buttons of holograms seem not to work anymore

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8734]
### Description of Issue

The next and prev buttons that should show next or prev pages of an hologramm stoped working in the lastest version

![15-05-2024_23-58-42](https://github.com/Zrips/CMI/assets/12080017/432d2d31-74f9-4285-8194-d14284cbac3d)

![15-05-2024_23-59-06](https://github.com/Zrips/CMI/assets/12080017/a342b575-370e-449e-a899-919097eb210f)

### Version Information

```shell
9.7.2.9
```

### Relevant Config Sections

```yaml
The Hologramm

SpawnStatsHologrammNorth#>:
  Loc: world;-84.0;64.4;267.5
  Interval: 1.0
  LOSInterval: 0.2
  PageInterval: 0.2
  HoverParticles:
    Count: 1
  Range: 4
  RangeExtra: 4
  Spacing: 0.24
  Interactable: true
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: CENTER
    TAlpha: 255
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 5
    SL: -1
    BL: -1
  Commands:
  - cmi hologrampages SpawnStatsHologrammNorth [playerName] next
  Lines:
  - '&u&l→→→'
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Does command being triggered when you click on it? As of testing with your example, it looks to be working correctly

**Comment by CloudeLecaw** [comment]
the command is not triggered and also indont see the Animation thatbwas there before.
i have the same commands on the hologram itself (with addition of left or right click condition) there is works when i click on the hologram itself.

**Comment by CloudeLecaw** [comment]
well we dont have so much multipe page hologramms.
i could post the one to you
```yml
SpawnStatsHologrammNorth:
  Loc: world;-84.5;67.5;267.5
  Interval: 1.0
  LOSInterval: 0.1
  PageInterval: 3600.0
  HoverParticles:
    Count: 1
  Range: 4
  RangeExtra: 4
  Spacing: 0.24
  Interactable: true
  NewMethod: false
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: LEFT
    TAlpha: 255
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 0
    SL: -1
    BL: -1
  Commands:
  - '!leftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!rightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  - '!shiftleftclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] prev'
  - '!shiftrightclick! cmi hologrampages SpawnStatsHologrammNorth [playerName] next'
  Lines:
  - '&u&lDie besten Partygamer'
  - '&f&l '
  - '  &f&l1. &e%ajlb_lb_partygames_wins_1_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_1_alltime_value% wins&f&l)'
  - '  &f&l2. &6%ajlb_lb_partygames_wins_2_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_2_alltime_value% wins&f&l)'
  - '  &f&l3. &e%ajlb_lb_partygames_wins_3_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_3_alltime_value% wins&f&l)'
  - '  &f&l4. &6%ajlb_lb_partygames_wins_4_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_4_alltime_value% wins&f&l)'
  - '  &f&l5. &e%ajlb_lb_partygames_wins_5_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_5_alltime_value% wins&f&l)'
  - '  &f&l6. &6%ajlb_lb_partygames_wins_6_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_6_alltime_value% wins&f&l)'
  - '  &f&l7. &e%ajlb_lb_partygames_wins_7_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_7_alltime_value% wins&f&l)'
  - '  &f&l8. &6%ajlb_lb_partygames_wins_8_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_8_alltime_value% wins&f&l)'
  - '  &f&l9. &e%ajlb_lb_partygames_wins_9_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_9_alltime_value% wins&f&l)'
  - '&f&l10. &6%ajlb_lb_partygames_wins_10_alltime_name% &f&l(&e%ajlb_lb_partygames_wins_10_alltime_value% wins&f&l)'
  - '!nextpage!'
  - '&u&lDie glücklichsten Roulettespieler'
  - '&f&l '
  - '  &f&l1. &e%ajlb_lb_roulette_winnings_1_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_1_alltime_value% ⛁&f&l)'
  - '  &f&l2. &6%ajlb_lb_roulette_winnings_2_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_2_alltime_value% ⛁&f&l)'
  - '  &f&l3. &e%ajlb_lb_roulette_winnings_3_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_3_alltime_value% ⛁&f&l)'
  - '  &f&l4. &6%ajlb_lb_roulette_winnings_4_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_4_alltime_value% ⛁&f&l)'
  - '  &f&l5. &e%ajlb_lb_roulette_winnings_5_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_5_alltime_value% ⛁&f&l)'
  - '  &f&l6. &6%ajlb_lb_roulette_winnings_6_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_6_alltime_value% ⛁&f&l)'
  - '  &f&l7. &e%ajlb_lb_roulette_winnings_7_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_7_alltime_value% ⛁&f&l)'
  - '  &f&l8. &6%ajlb_lb_roulette_winnings_8_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_8_alltime_value% ⛁&f&l)'
  - '  &f&l9. &e%ajlb_lb_roulette_winnings_9_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_9_alltime_value% ⛁&f&l)'
  - '&f&l10. &6%ajlb_lb_roulette_winnings_10_alltime_name% &f&l(&e%ajlb_lb_roulette_winnings_10_alltime_value% ⛁&f&l)'
  - '!nextpage!'
  - '&u&lDie besten Sprungparkourmeister'
  - '&f&l '
  - '  &f&l1. &e%ajpk_stats_top_name_1% &f&l(&e%ajpk_stats_top_score_1% jumps&f&l)'
  - '  &f&l2. &6%ajpk_stats_top_name_2% &f&l(&6%ajpk_stats_top_score_2% jumps&f&l)'
  - '  &f&l3. &e%ajpk_stats_top_name_3% &f&l(&e%ajpk_stats_top_score_3% jumps&f&l)'
  - '  &f&l4. &6%ajpk_stats_top_name_4% &f&l(&6%ajpk_stats_top_score_4% jumps&f&l)'
  - '  &f&l5. &e%ajpk_stats_top_name_5% &f&l(&e%ajpk_stats_top_score_5% jumps&f&l)'
  - '  &f&l6. &6%ajpk_stats_top_name_6% &f&l(&6%ajpk_stats_top_score_6% jumps&f&l)'
  - '  &f&l7. &e%ajpk_stats_top_name_7% &f&l(&e%ajpk_stats_top_score_7% jumps&f&l)'
  - '  &f&l8. &6%ajpk_stats_top_name_8% &f&l(&6%ajpk_stats_top_score_8% jumps&f&l)'
  - '  &f&l9. &e%ajpk_stats_top_name_9% &f&l(&e%ajpk_stats_top_score_9% jumps&f&l)'
  - '&f&l10. &6%ajpk_stats_top_name_10% &f&l(&6%ajpk_stats_top_score_10% jumps&f&l)'
  
SpawnStatsHologrammNorth#<:
  Loc: world;-85.0;64.4;267.5
  Interval: 1.0
  LOSInterval: 0.2
  PageInterval: 0.2
  HoverParticles:
    Count: 1
  Range: 4
  RangeExtra: 4
  Spacing: 0.24
  Interactable: true
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: CENTER
    TAlpha: 230
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 0
    SL: -1
    BL: -1
  Commands:
  - cmi hologrampages SpawnStatsHologrammNorth [playerName] prev
  Lines:
  - '&u&l←←←'
  
SpawnStatsHologrammNorth#>:
  Loc: world;-84.0;64.4;267.5
  Interval: 1.0
  LOSInterval: 0.2
  PageInterval: 0.2
  HoverParticles:
    Count: 1
  Range: 4
  RangeExtra: 4
  Spacing: 0.24
  Interactable: true
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: CENTER
    TAlpha: 255
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 5
    SL: -1
    BL: -1
  Commands:
  - cmi hologrampages SpawnStatsHologrammNorth [playerName] next
  Lines:
  - '&u&l→→→'
  ```

**Comment by CloudeLecaw** [comment]
same result with this one:
```yml
TestTestOne:
  Loc: world;1775.1;-49.88;1959.74
  Interval: 1.0
  LOSInterval: 0.1
  PageInterval: 3600.0
  HoverParticles:
    Count: 1
  Range: 4
  RangeExtra: 4
  Spacing: 0.24
  Interactable: true
  NewMethod: false
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: FIXED
    Align: LEFT
    TAlpha: 255
    Shadow: true
    Yaw: 0
    Pitch: 0
    Double: true
    BColor: '{#Black}'
    BAlpha: 0
    SL: -1
    BL: -1
  Lines:
  - Site 1
  - '!nextpage!'
  - Site 2
  - '!nextpage!'
  - Site 3
  - '!nextpage!'
  - Site 4

TestTestOne#<:
  Loc: world;1775.6;-50.22;1959.74
  Interval: 0.1
  PageInterval: 0.1
  HoverParticles:
    Count: 1
  Range: 16
  RangeExtra: 32
  Spacing: 0.24
  Interactable: true
  Commands:
  - cmi hologrampages TestTestOne [playerName] prev
  Lines:
  - '§6Vorherig '
 
TestTestOne#>:
  Loc: world;1774.6;-50.22;1959.74
  Interval: 0.1
  PageInterval: 0.1
  HoverParticles:
    Count: 1
  Range: 16
  RangeExtra: 32
  Spacing: 0.24
  Interactable: true
  Commands:
  - cmi hologrampages TestTestOne [playerName] next
  Lines:
  - §6 Nächste
  ```
