### ISSUE TITLE
Durability alert not working on 1.12.2

### ISSUE THREAD

**Issue by Achent007** [Zrips/CMI#8740]
### Description of Issue

Players doesn't see the message about armor or equipement at low durability but they have the recquired permisison.

[LP] Permission information for cmi.informDurability:
[LP] - default has cmi.informDurability set to true in context server=vanilla-1-20.
[LP] - default has cmi.informDurability set to true in context server=survival.
[LP] - default has cmi.informDurability set to true in context server=skycreep.
[LP] - default has cmi.informDurability set to true in context server=hardcore.
[LP] - default does not inherit cmi.informDurability.
[LP] 
[LP] Permission check for cmi.informDurability:
[LP]     Result: true
[LP]     Processor: common.DirectProcessor
[LP]     Cause: default has cmi.informDurability set to true in context server=skycreep
[LP]     Context: (server=skycreep)

### Version Information

```shell
CMI: 9.7.2.9 Unknown  MySQL
CMILib: 1.4.7.9 
Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT-
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 43 enabled 16 disabled: hpBossBar, launchPad, tablist, moneyCheque, skin, noTarget, jail, elytraBoost, dynamicSigns, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, votifier, headDrop, vanish
```

### Errors

```shell
no errors on console
```

### Relevant Config Sections

```yaml
OnDurabilityLoss:
    # Do you want to inform player when item durability gets lower than set threshold
    # Player should have cmi.informDurability
    Tools:
      Use: true
      Percentage: 2
    Armor:
      Use: true
      Percentage: 2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
