### ISSUE TITLE
Holograms interactable don't work from 9.7.2.9

### ISSUE THREAD

**Issue by RickyLaChow** [Zrips/CMI#8759]
### Description of Issue

While i'm clicking holograms commands don't being executed 

### Version Information

```shell
[21:03:53 INFO]: --------------------------------------------------
[21:03:53 INFO]: CMI: 9.7.2.10 Velocity CMIB  SqLite
[21:03:53 INFO]: CMILib: 1.4.7.11 
[21:03:53 INFO]: Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
[21:03:53 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[21:03:53 INFO]: Modules -> 24 enabled 35 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, playerCombat, shulkerBackpack, cooldown, spawnerCharge, namePlates, homeInteractions, hpBossBar, launchPad, elytraExploit, portals, afk, anvilRenameColor, spawners, paintingEditor, playerChatTag, durabilityLoss, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, warmup, totemBehavior
[21:03:53 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
might add some comment to this one? looks like a simliar issue?....
https://github.com/Zrips/CMI/issues/8734#issuecomment-2118497189

**Comment by RickyLaChow** [comment]
> might add some comment to this one? looks like a simliar issue?.... [#8734 (comment)](https://github.com/Zrips/CMI/issues/8734#issuecomment-2118497189)

I'm not using paging system

```yml
consegna_pizza_1:
  Loc: Prymacity;721.51;71.37;-197.57
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 8
  RangeExtra: 10
  Spacing: 0.24
  SpacingIcon: 1.4
  Interactable: true
  NewDisplay: true
  ND:
    AutoPage: false
    Bill: VERTICAL
    Align: CENTER
    TAlpha: 230
    Shadow: true
    BColor: '{#Black}'
    BAlpha: 125
    SL: -1
    BL: -1
  RequiresPermission: true
  Commands:
  - asPlayer! pizzaboy consegna
  Lines:
  - ' {#D8FF71}ᴄᴏɴsᴇɢɴᴀ ᴘɪᴢᴢᴀ'
  - ' {#EFFFC4}ᴄʟɪᴄᴄᴀ ᴘᴇʀ ɪɴᴛᴇʀᴀɢɪʀᴇ'
  ```

**Comment by RickyLaChow** [comment]
Tested in the new 9.7.2.11 with "use new method" active in Modify Interactions and don't work, but while i disable use new method working fine. 

[11:41:38 INFO]: --------------------------------------------------
[11:41:38 INFO]: CMI: 9.7.2.11 Velocity CMIB  SqLite
[11:41:38 INFO]: CMILib: 1.4.7.12 
[11:41:38 INFO]: Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
[11:41:38 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[11:41:38 INFO]: Modules -> 24 enabled 35 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, playerCombat, shulkerBackpack, cooldown, spawnerCharge, namePlates, homeInteractions, hpBossBar, launchPad, elytraExploit, portals, afk, anvilRenameColor, spawners, paintingEditor, playerChatTag, durabilityLoss, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, warmup, totemBehavior
[11:41:38 INFO]: --------------------------------------------------

**Comment by CloudeLecaw** [comment]
i tried new and old methode for the prev next buttons but without any effect :3

**Comment by Zrips** [comment]
Ok, found some small issue which could be the cause for your issue, if issue persists after next update, let me know. Closing ticket for now.

**Comment by RickyLaChow** [comment]
@Zrips The issue persist i need to use  NewMethod: false for make it work in the new versions 

```yml
consegna_pizza_1:
  Loc: Prymacity;721.51;71.37;-197.57
  ShowParticles: false
  HoverParticles:
    ShowHover: false
  Range: 8
  RangeExtra: 10
  SpacingIcon: 1.4
  Interactable: true
  NewMethod: false
  NewDisplay: true
  ND:
    Bill: VERTICAL
    BColor: "{#Black}"
  RequiresPermission: true
  Commands:
    - asPlayer! pizzaboy consegna
  Lines:
    - " {#D8FF71}ᴄᴏɴsᴇɢɴᴀ ᴘɪᴢᴢᴀ"
    - " {#EFFFC4}ᴄʟɪᴄᴄᴀ ᴘᴇʀ ɪɴᴛᴇʀᴀɢɪʀᴇ"
```

[14:42:34 INFO]: --------------------------------------------------
[14:42:34 INFO]: CMI: 9.7.2.12 Velocity CMIB  SqLite
[14:42:34 INFO]: CMILib: 1.4.7.14 
[14:42:34 INFO]: Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
[14:42:34 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[14:42:34 INFO]: Modules -> 24 enabled 35 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, playerCombat, shulkerBackpack, cooldown, spawnerCharge, namePlates, homeInteractions, hpBossBar, launchPad, elytraExploit, portals, afk, anvilRenameColor, spawners, paintingEditor, playerChatTag, durabilityLoss, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, warmup, totemBehavior
[14:42:34 INFO]: --------------------------------------------------
