### ISSUE TITLE
Drop & Place spawner does not work correctly in 1.20.6

### ISSUE THREAD

**Issue by Siqued** [Zrips/CMI#8791]
### Description of Issue

You can break a zombie spawner but it will not remember the spawnertype
So you will just place a empty spawner. And i do have the correct settings. And works fine on 1.20.4

### Version Information

```shell
CMI: 9.7.2.12 SqLite
CMILib: 1.4.7.14
Server: Paper(89) 1.20.6-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 58 enabled 1 disabled: votifier
```

### Relevant Config Sections

```yaml
FullDisable: false
  Break:
    Enabled: true
    RequiresExactPermission: false
    DropExp: false
    SilkTouchLevel: 1
    BaseDropChance: 100

  Place:
    Enabled: true
    RequiresPermission: false
    RequiresExactPermission: false
```

### Relevant Plugins

CMI Vault

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
