### ISSUE TITLE
CMI Holograms "!nextpage! issue"

### ISSUE THREAD

**Issue by pitruk** [Zrips/CMI#8796]
### Description of Issue

Making an "oldmode" hologram with "!nextpage!", the pages do not change. With "NewDisplay: true", it works fine.

```
battlepassPresentPremiumItem:
  Loc: world;195.5;-30.7;451.5
  Interval: 1.0
  PageInterval: 2.5
  Range: 32
  RangeExtra: 32
  Spacing: -0.06
  NewDisplay: false
  Lines:
  - ICON:NETHERITE_SWORD%customModelData:10076%
  - '!nextpage!'
  - ICON:NETHERITE_PICKAXE%customModelData:10014%
  - '!nextpage!'
  - ICON:NETHERITE_AXE%customModelData:10018%
  - '!nextpage!'
  - ICON:NETHERITE_SHOVEL%customModelData:10014%
  - '!nextpage!'
  - ICON:NETHERITE_HOE%customModelData:10013%
  - '!nextpage!'
  - ICON:NETHERITE_SWORD%customModelData:10038%
  - '!nextpage!'
  - ICON:NETHERITE_PICKAXE%customModelData:10013%
  - '!nextpage!'
  - ICON:NETHERITE_AXE%customModelData:10017%
  - '!nextpage!'
  - ICON:NETHERITE_SHOVEL%customModelData:10013%
  - '!nextpage!'
```

UPDATE:
The ability to change the page by clicking is also no longer available.
```
regulamin:
  Loc: world;189.0;-26.25;457.0
  Range: 32
  RangeExtra: 32
  Interactable: true
  NewDisplay: true
  ND:
    Bill: FIXED
    Yaw: -45
    BColor: '{#Black}'
    BAlpha: 0
    ScaleW: 0.75
    ScaleH: 0.75
    SL: 15
    BL: 15
  Lines:
  - '&8&l▪ #eb4034&lRᴇɢᴜʟᴀᴍɪɴ &8&l▪'
  - '&f&oStrona &a1&f/&c2'
  - _
  - '&4&l1. &fZakaz używania wulgaryzmów,'
  - '&4&l2. &fZakaz spamowania oraz floodowania na chacie,'
  - '&4&l3. &fZakaz obrażania oraz znieważania innych osób,'
  - '&4&l4. &fZakaz udostępniania danych osobowych innych osób,'
  - '&4&l5. &fZakaz nadużywania wielkich liter,'
  - '&4&l6. &fZakaz poruszania tematów erotycznych,'
  - '&4&l7. &fZakaz prowokowania innych osób,'
  - '&4&l8. &fZakaz oszukiwania innych osób,'
  - '&4&l9. &fZakaz podszywnia się pod inne osoby,'
  - '&4&l10. &fZakaz tworzenia multikont,'
  - '&4&l11. &fZakaz reklamowania serwerów,'
  - '&4&l12. &fZakaz wykorzystywania błędów gry oraz serwera,'
  - _
  - <T>&8[&eNastępna strona&8]</T><H>&8[&6&lNastępna strona&8]</H><C>cmi hologrampages
    regulamin [playerName] next</C>
  - _
  - _
  - _
  - '&aGrając na serwerze akceptujesz powyższy regulamin'
  - '&cPełny regulamin znajduje się na &f&ohttps://aximc.pl/regulamin'
  - '&cOstatnia aktualizacja: &f&o--.--.2023r'
  - '!nextpage!'
  - '&8&l▪ #eb4034&lRᴇɢᴜʟᴀᴍɪɴ &8&l▪'
  - '&f&oStrona &a2&f/&c2'
  - _
  - '&4&l13. &fZakaz posiadania wulgarnego nicku,'
  - '&4&l14. &fZakaz posiadania nieodpowiednich skinów,'
  - '&4&l15. &fZakaz używania wspomagaczy,'
  - '&4&l16. &fZakaz tworzenia wulgarnych budowli,'
  - '&4&l17. &fZakaz propagowania treści nazistowskich,'
  - '&ffaszystowskich, rasistowskich oraz komunistycznych'
  - _
  - _
  - _
  - _
  - _
  - _
  - _
  - <T>&8[&ePoprzednia strona&8]</T><H>&8[&6&lPoprzednia strona&8]</H><C>cmi hologrampages
    regulamin [playerName] prev</C>
  - _
  - _
  - _
  - '&aGrając na serwerze akceptujesz powyższy regulamin'
  - '&cPełny regulamin znajduje się na &f&ohttps://aximc.pl/regulamin'
  - '&cOstatnia aktualizacja: &f&o--.--.2023r'
```

**Everything works in version:** CMI-9.7.1.1 / CMILib-1.4.4.9

### Version Information

```shell
[21:51:32 INFO]:                                                 
[21:51:32 INFO]: CMI: 9.7.2.12 Unknown  MySQL
[21:51:32 INFO]: CMILib: 1.4.7.15 
[21:51:32 INFO]: Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
[21:51:32 INFO]: CMI economy: włączone Vault: 1.7.3-CMI CMI Chat: włączone 
[21:51:32 INFO]: Modules -> 51 enabled 8 disabled: spawnerProximity, tablist, ranks, votifier, anvilRenameColor, spawners, spawnerCharge, namePlates
[21:51:32 INFO]:
```

### Errors

```shell
nothing
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
