### ISSUE TITLE
Problems with line breaks in CMI

### ISSUE THREAD

**Issue by ChrisTVH** [Zrips/CMI#8808]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/58376852/e967d009-f55d-40c2-a0b8-c45368ceb3f2)
![image](https://github.com/Zrips/CMI/assets/58376852/4dca061a-778f-4ac3-9394-9b614acff0de)
The line breaks `\n` are seen directly as I show in the images.

### Version Information

```shell
CMI: 9.7.3.1
Database: 9.7.3.0
CMILIB: 1.4.7.15
```

### Errors

```shell
There are no errors in the console.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ChrisTVH** [comment]
The plugin has been updated, I come to confirm that it is still happening :D
![image](https://github.com/Zrips/CMI/assets/58376852/65062bbd-d7de-4ac5-b6a1-e19c9fcb60bf)

**Comment by ChrisTVH** [comment]
This is still broken in the latest updates, as it has taken a long time I have mentioned to you.
![image](https://github.com/user-attachments/assets/95cb9a00-79ce-4032-a537-9df6db1447ef)

@Zrips

**Comment by AnonymousDr** [comment]
I am having the same problem with the default spanish translation
![image](https://github.com/user-attachments/assets/22cfebc2-d3f7-4d76-8bd0-18ab78b45559)

**Comment by ChrisTVH** [comment]
> I am having the same problem with the default spanish translation

I would think it's because of the translation but try putting it with:
- 'text'
- 'text'
and it came out the same, the plugin converts it to \n.

**Comment by AnonymousDr** [comment]
> > I am having the same problem with the default spanish translation
> 
> I would think it's because of the translation but try putting it with:
> 
> ```yaml
> - 'text'
> - 'text'
> ```
> 
> and it came out the same, the plugin converts it to \n.

Yeah, of course, is from the translation. I haven't tried that solution, but I don't think it will work, as it is expecting a String, not a List<String>. Anyways, I've changed the translation. For the sample I shown of the image, I've set this values:

```yml
command:
  help:
    output:
      usage: '&3Comando:&r %usage%'
      cmdInfoFormat: '&6[command] &7► [description]'
      cmdFormat: '&6/[command]&e[arguments]'
      helpPageDescription: '&3Descripción: &7[description]'
      explanation: '&7[explanation]'
      title: '&6&m       &r&6【 &eComandos de CMI &6】&m       &r'
```
