### ISSUE TITLE
/cheque not creating a usable item

### ISSUE THREAD

**Issue by mnfu** [Zrips/CMI#8848]
### Description of Issue

when using /cheque, the result (whether you enable the requirement of paper being needed) is a blank piece of paper.
Related Video on Zrips Discord: https://discord.com/channels/452792793631555594/526402563847880725/1253160704106561577

### Version Information

```shell
[21:46:59 INFO]: --------------------------------------------------
[21:46:59 INFO]: CMI: 9.7.4.0 SqLite
[21:46:59 INFO]: CMILib: 1.5.0.1
[21:46:59 INFO]: Server: Paper(15) 1.21-R0.1-SNAPSHOT-
[21:46:59 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[21:46:59 INFO]: Modules -> 62 enabled 4 disabled: tablist, votifier, nightSpeedup, homeInteractions
[21:46:59 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
    IgnoredUsers:
    - Zrips
  Cheque:
    # Determines max amount of cheque player can create
    # Set it to 0 to remove limit
    MaxValue: 1.0E8
    # If set to true player will be required to hold peace of paper to create cheque
    Paper: false
    # When set to true player will be required to have cmi.command.cheque.withdraw permission node to withdraw cheque
    Permission: false
    # Should we allow checque usage in creative mode
    # If you have creative server, keep this at false or players could start duplicating items
    InCreative: false
    # Should we accept old cheque item stacks with non encoded data in them
    # Keep it at false for most security
    AcceptNotEncoded: false
```

### Relevant Plugins

Vault 1.7.4-CMI (latest from https://www.zrips.net/cmivault/)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
