### ISSUE TITLE
Tablist Placeholders Loading Delay

### ISSUE THREAD

**Issue by razorrider7** [Zrips/CMI#889]
**Description of issue or feature request:**
When using placeholders in the username format in the tab list, the placeholders flash with the placeholder (or sometimes show up as the username only) before turning to what they should display. For example, it shows up as "%vault_prefix%" for a second before turning to "<Sub>" with the following config. This happens for placeholders included in CMI too...

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
TabList:
  # Enable or disable tab list management
  Enabled: true
  # Defines if we want to run tablist updater in async mode
  # While enabled it can increase overall performance but some plugins can have same issues handling async placeholder requests
  Async: true
  UpdateTabListNames: true
  # Enable or disable grouped format tablist's
  # You can save some resources by disabling this if you are not interested in grouped format tablist feature
  # If disabled then this will use only default format and will skip checking for custom one to save some resources if needed
  GroupedEnabled: true
  Updates:
    # automatically updates tab list every x seconds for ALL online players
    # If you are using static Footer and Header you can disable this by setting to -1
    # Consider setting this to -1 if its completely enough to update on player events
    AutoInterval: 5
    OnJoin: true
    OnLeave: true
    afkStateChange: true
    OnWorldChange: true
    OnDeath: false
    OnTeleport: false
    OnNickChange: true
  # PlaceholderAPI supported for any custom variable you want to insert into this
  # In adition CMI will handle some placeholders without PlaceHolderAPI
  # Full list can be checked ingame with /cmi placeholders
  GeneralFormat:
    PlayerName: '%vault_prefix%[playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
      - '&f------------------------------------'
  # Defines custom formats to be used for players.
  # Any player which have cmi.tablist.[number] permission node will use defined grouped format in tablist
  # Id should be a number and in case player has more than one, bigger number id will be used
  # You can have as many groups as you want by increasing increment
  # If player has more than one permission node, then biggest one will be used
  GroupFormat:
    '1':
      PlayerName: '&2{&r[playerDisplayName]&2}'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
        - '&7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
    '2':
      PlayerName: '&c[&r[playerDisplayName]&c]'
      Header:
        '1':
        - '&f------------------------------------'
        - '&7Online &f%server_online%&7/&f%server_max_players%'
        - '&f------------------------------------'
      Footer:
        '1':
        - '&f------------------------------------'
        - '&7Money: &f%vault_eco_balance_formatted% &7Time: &f%server_time_HH:mm:ss%'
        - '&f------------------------------------'
```

**Cmi Version (using`/cmi version`):** 
```
[13:40:28 INFO]: --------------------------------------------------
[13:40:28 INFO]: CMI plugin version: 8.0.17.0-> 8.0.18.0
[13:40:28 INFO]: Server version: Paper(314) 1.13.1-R0.1-SNAPSHOT
[13:40:28 INFO]: Vault version: 1.6.11(+)
[13:40:28 INFO]: --------------------------------------------------
```
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
[13:55:33 INFO]: This server is running Paper version git-Paper-319 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:55:33 INFO]: Previous version: git-Paper-314 (MC: 1.13.1)
[13:55:33 INFO]: Checking version, please wait...
[13:55:34 INFO]: You are running the latest version
