### ISSUE TITLE
Silk touching spawners broke in 1.21?

### ISSUE THREAD

**Issue by alfredcort** [Zrips/CMI#8890]
### Description of Issue

I've had a server going for a while on 1.20.4 where mining/picking up spawners worked flawlessly. In 1.21, when mining a spawner, it now states that you have a 0% drop chance (it works correctly and shows the correct chance% when the player is OP). Are there any permission changes? I've not seen anything in the changelogs.
<img width="586" alt="Screenshot 2024-07-02 at 21 09 43" src="https://github.com/Zrips/CMI/assets/72607588/d5280e83-fa51-4def-9ccb-3c85fc772572">

### Version Information

```shell
CMI: 9.7.4.2 SqLite
CMILib: 1.5.0.4 
Server: Paper(2252) 1.21-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 65 enabled 1 disabled: tablist
```

### Relevant Config Sections

```yaml
Spawners:
  FullDisable: false
  Break: spawner
    Enabled: true
    RequiresExactPermission: false
    DropExp: false
    SilkTouchLevel: 1
    BaseDropChance: 0
  Place:
    Enabled: true
    RequiresPermission: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
