### ISSUE TITLE
Totem Cooldown not working

### ISSUE THREAD

**Issue by InvalidTeslaa** [Zrips/CMI#8915]
### Description of Issue

the Totem cooldown isnt correctly working. There is the message of that the player is in totem cooldown with bossbar and all other, but the totem use event dont get cancelled

Also totems prevent the member from dying in void which i have disabled

https://cdn.letsgrief.net/2024%2F07%2F03%2Faef6f8e1-3300-4872-a250-b5018cc63390.mp4

### Version Information

```shell
https://cdn.letsgrief.net/2024/07/07/99e2e1b0-45a0-43de-afbe-c1633704e71f.png
```

### Relevant Config Sections

```yaml
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: true
    Time: 120
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: false
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
