### ISSUE TITLE
'/cmi reload' do not reloading a shedules.yml on purpure 1.20.4

### ISSUE THREAD

**Issue by insidethehearts** [Zrips/CMI#8925]
### Description of Issue

When i make changes in 'Schedules.yml' i must to restart my server.
The '/cmi reload' not reloading this file.

On paper core '/cmi reload' works (tested by support request)
But on my purpure 1.20.4 i must to restart server.

### Version Information

```shell
CMI - 9.7.4.4
CMILib - 1.5.0.6
```

### Errors

```shell
No error messages in console
```

### Relevant Config Sections

```yaml
restart:
  Enabled: true
  PerformOn:
    FirstTimeFrame:
      Hour: 01
      Minute: 10
  Commands:
  - bossbarmsg all Перезагрузка сервера через [autoTimeLeft] -sec:-590 -c:red
  - delay! 590
  - save-all
  - titlemsg all &cПерезагрузка через &410 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &49 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &48 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &47 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &46 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &45 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &44 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &43 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &42 &cсекунд
  - cmi sound BLOCK_LEVER_CLICK -all -s
  - delay! 1
  - titlemsg all &cПерезагрузка через &41 &cсекунд
  - stop
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
