### ISSUE TITLE
Jail whitelist command does not work

### ISSUE THREAD

**Issue by DaJMaN4** [Zrips/CMI#8966]
### Description of Issue

Jail whitelist command does not work, I whitelisted command /helpop and players cannot use it while being jailed.

### Version Information

```shell
[15:17:28 INFO]: CMI: 9.7.4.7 SqLite
[15:17:28 INFO]: CMILib: 1.5.0.9 
[15:17:28 INFO]: Serwer: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
[15:17:28 INFO]: CMI ekonomia: Włączone Skrytka: 1.7.3-CMI CMI Chat: Wyłączone 
[15:17:28 INFO]: Moduły -> 53 aktywne 13 nieaktywne: hpBossBar, customMessages, tablist, holograms, playerChatTag, deathMessages, worldLimitsElytra, worldLimits, selection, votifier, cooldown, headDrop, vanish
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 800
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: -1
  # When set to true jail time will decreese while player is offline
  # When set to false jail time will only be counted while player is online
  CountWhileOffline: false
  # When set to true jail time will not decreese if player gets into afk mode while being jailed
  # When set to false, time will pass normally
  NoAfk: false
  # Do you want to prevent players damage while he is in jail
  PreventDamage: true
  # Do you want to prevent players hunger while he is in jail
  PreventHunger: true
  Commands:
    # Commands to be performed when player gets jailed
    OnJail:
    - ''
    # Commands to be performed when player gets unjailed
    OnUnJail:
    - ''
  WhiteListedCmds:
  - helpop
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
