### ISSUE TITLE
Question or Suggestion] Interactiv Commands with req. money or xp?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#897]
i created some interactive commands attached on some Buttons and signs
i want that the Player is only be able to use the Buttons/sign with the interactiv commands if he has the amount of Money. like a moneycheck

is this possible? if not can it be added?
Also a check for XP may be nice idea…
How this could look in the config:

```
Test:
  Location:
  - ==: org.bukkit.Location
    world: NSD
    x: 482.0
    y: 74.0
    z: 90.0
    pitch: 0.0
    yaw: 0.0
  Commands:
  - cmi time night NSD
  - cmi gm Cloude_Lecaw 1
  SignLines:
  - Test
  - ' '
  - ' '
  - ' '
  Cost: 10
  Exp: 0
```
