### ISSUE TITLE
Totem Colldown

### ISSUE THREAD

**Issue by InvalidTeslaa** [Zrips/CMI#8973]
### Description of Issue

The change to CMis totem handling make it now not useable anymore, always on die it say im on cooldown

### Version Information

```shell
https://cdn.letsgrief.net/2024/07/23/82b1625d-f3e8-418d-8cbb-e196dfe15e37.png
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: true
    Time: 20
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: false
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

### Relevant Plugins

AngelChest v13.1.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
