### ISSUE TITLE
rankup not fully operational

### ISSUE THREAD

**Issue by nate981120** [Zrips/CMI#8982]
### Description of Issue

when the player rankup
cmi dont cost player money
then it is not executed the command 'points give [playerName] 1500'

### Version Information

```shell
9.6.10.7
```

### Relevant Config Sections

```yaml
超忍:
  Enabled: true
  MoneyCost: 1000000
  ExpCost: 25000
  DisplayName: '&f㊬'
  AutoRankup: true
  RankupConfirmation: true
  Commands:
  - lp user [playerName] parent add 超忍
  - maxhp set [playerName] 160
  - points give [playerName] 1500
  StatsRequirements:
  - BlocksMined:deepslate_diamond_ore:500
  - BlocksMined:prismarine:2000
  - BlocksMined:bone_block:1000
  - BlocksMined:soul_soil:500
  - BlocksMined:sponge:100
  - BlocksMined:deepslate_redstone_ore:1000
  - PlayerKills:100
  - Walk:50000
  - Fly:40000
  - HorseTravel:20000
  - Travel:150000
  - MonsterKills:phantom:50
  - MonsterKills:elder_guardian:20
  - MonsterKills:silverfish:150
  - MonsterKills:blaze:100
  - MonsterKills:cave_spider:100
  - PlayTime:900000
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
