### ISSUE TITLE
Kits conditions not use other perms

### ISSUE THREAD

**Issue by moda84** [Zrips/CMI#8991]
### Description of Issue

Kits conditions not use other perms.

My kit:

```
MinerL:
  CommandName: MinerL
  Delay: 604800
  MoneyCost: 200.0
  Conditions:
  - mtlevel.donate.l
  - mtlevel.perk.miner
  Items:
    '28':
      v: 3953
      type: IRON_PICKAXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        enchants:
          minecraft:efficiency: 3
          minecraft:unbreaking: 2
    '29':
      v: 3953
      type: DIAMOND_SHOVEL
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        enchants:
          minecraft:efficiency: 3
          minecraft:unbreaking: 2
    '30':
      v: 3953
      type: PUMPKIN_PIE
      amount: 16
```
 But player can get it only if have cmi.kit.minerl,
 but if player have cmi.kit.minerl and no have any perms of list of conditions, then player can claim kit.

### Version Information

```shell
CMI: 9.7.4.8 SqLite
CMILib: 1.5.0.9
Server: Paper(2273) 1.21-R0.1-SNAPSHOT-
CMI economy: Disabled Vault: 1.7.3-b0-folia CMI Chat: Disabled
Modules -> 63 enabled 3 disabled: tablist, votifier, skin
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
