### ISSUE TITLE
PlayerkillPlayer Event not working

### ISSUE THREAD

**Issue by LPPRR123** [Zrips/CMI#8995]
### Description of Issue

PlayerkillPlayer Event not working

### Version Information

```shell
CMI 9.7.4.8 BungeeCord CMIB  SqLite
CMILib: 1.5.0.9
Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
CMI economy: disabled Vault: 1.7.3-b131 CMI Chat: disabled 
Modules -> 64 enabled 2 disabled: tablist, votifier
```

### Errors

```shell
Totally not working.
```

### Relevant Config Sections

```yaml
playerKillPlayer:
  Enabled: true
  Commands:
  - broadcast! say test
  SourceCommands: []
```

### Relevant Plugins

no relevant plugins tested only with CMI and CMILibs

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
