### ISSUE TITLE
Warnings are not given to the player

### ISSUE THREAD

**Issue by ZarsQv** [Zrips/CMI#9004]
### Description of Issue

Then I warn an player via _/cmi warn_
And check the warns with _/cmi warnings_ 
There no warnings will be applied to the player

### Version Information

```shell
CMI: 9.7.4.8
CMILib: 1.5.1.0
```

### Relevant Config Sections

```yaml
Warnings:
  Default:
    LifeTime: 0
    Points: 1
    DefaultReason: '&cНарушение правил сервера'
  Categories:
    mc1:
      LifeTime: 0
      Points: 1
      DefaultReason: mc1
    mc2:
      LifeTime: 0
      Points: 1
      DefaultReason: mc2
    mc3:
      LifeTime: 0
      Points: 1
      DefaultReason: mc3
    mc4:
      LifeTime: 0
      Points: 1
      DefaultReason: mc4
    mc5:
      LifeTime: 0
      Points: 1
      DefaultReason: mc5
    mc6:
      LifeTime: 0
      Points: 1
      DefaultReason: mc6
    mc7:
      LifeTime: 0
      Points: 1
      DefaultReason: mc7
    mc8:
      LifeTime: 0
      Points: 1
      DefaultReason: mc8
    mc9:
      LifeTime: 0
      Points: 1
      DefaultReason: mc9
    mc10:
      LifeTime: 0
      Points: 1
      DefaultReason: mc10
    mc11:
      LifeTime: 0
      Points: 1
      DefaultReason: mc11
  Perform:
    '5':
    - cmi tempban [playerName] 30d &cВы забанены за достижение 5 предупреждений!
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
