### ISSUE TITLE
CMI Ranks resetting users

### ISSUE THREAD

**Issue by KoalaServers** [Zrips/CMI#9008]
### Description of Issue

Occasionally some users will have their rank reset back to default. 

- We base our ranks off votes, and use the appropriate LP commands.
- When users ranks are reset - they are ranked back up quickly as CMI detects their vote count as the config.
- Can confirm it is a CMI Ranks fault as it is CMI that looses their vote and then runs our Ranks.yml config.

### Version Information

```shell
9.7.4.8
```

### Errors

```shell
No errors.
```

### Relevant Config Sections

```yaml
dingo:
  Enabled: true
  DisplayName: '{#monsoon>}ᴅɪɴɢо{#armadillo<}'
  DefaultRank: true
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - wallaby
wallaby:
  Enabled: true
  DisplayName: '{#meteor>}ᴡᴀʟʟᴀʙʏ{#straw<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 20
  NextRanks:
  - wallabyplus
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted 20 times! &7Ranked up to {#meteor>}ᴡᴀʟʟᴀʙʏ{#straw<}
  - asConsole! lp user [playerName] parent settrack votetrack wallaby
  StatsRequirements:
  - AccountAge:172800
wallabyplus:
  Enabled: true
  DisplayName: '{#meteor>}ᴡᴀʟʟᴀʙʏ＋{#straw<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 40
  NextRanks:
  - kangaroo
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a40 times! &7Ranked up to {#meteor>}ᴡᴀʟʟᴀʙʏ＋{#straw<}
  - asConsole! lp user [playerName] parent settrack votetrack wallabyplus
  StatsRequirements:
  - AccountAge:345600
kangaroo:
  Enabled: true
  DisplayName: '{#thatch>}ʀоо{#goldtips<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 60
  NextRanks:
  - kangarooplus
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a60 times! &7Ranked up to {#thatch>}ʀоо{#goldtips<}
  - asConsole! lp user [playerName] parent settrack votetrack kangaroo
  StatsRequirements:
  - AccountAge:518400
kangarooplus:
  Enabled: true
  DisplayName: '{#thatch>}ʀоо＋{#goldtips<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 80
  NextRanks:
  - emu
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a80 times! &7Ranked up to {#thatch>}ʀоо＋{#goldtips<}
  - asConsole! lp user [playerName] parent settrack votetrack kangarooplus
  StatsRequirements:
  - AccountAge:691200
emu:
  Enabled: true
  DisplayName: '{#frenchpass>}ᴇмᴜ{#bostonblue<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 120
  NextRanks:
  - emuplus
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a120 times! &7Ranked up to {#frenchpass>}ᴇмᴜ{#bostonblue<}
  - asConsole! lp user [playerName] parent settrack votetrack emu
emuplus:
  Enabled: true
  DisplayName: '{#frenchpass>}ᴇмᴜ＋{#bostonblue<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 160
  NextRanks:
  - croc
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a160 times! &7Ranked up to {#frenchpass>}ᴇмᴜ＋{#bostonblue<}
  - asConsole! lp user [playerName] parent settrack votetrack emuplus
croc:
  Enabled: true
  DisplayName: '{#silk>}ᴄʀоᴄ{#keylimepie<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 200
  NextRanks:
  - crocplus
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a200 times! &7Ranked up to {#silk>}ᴄʀоᴄ{#keylimepie<}
  - asConsole! lp user [playerName] parent settrack votetrack croc
crocplus:
  Enabled: true
  DisplayName: '{#silk>}ᴄʀоᴄ＋{#keylimepie<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 320
  NextRanks:
  - redback
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a320 times! &7Ranked up to {#silk>}ᴄʀоᴄ＋{#keylimepie<}
  - asConsole! lp user [playerName] parent settrack votetrack crocplus
redback:
  Enabled: true
  DisplayName: '{#red>}ʀᴇᴅʙᴀᴄᴋ{#lonestar<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 440
  NextRanks:
  - redbackplus
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a440 times! &7Ranked up to {#red>}ʀᴇᴅʙᴀᴄᴋ{#lonestar<}
  - asConsole! lp user [playerName] parent settrack votetrack redback
redbackplus:
  Enabled: true
  DisplayName: '{#red>}ʀᴇᴅʙᴀᴄᴋ＋{#lonestar<}'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 560
  NextRanks:
  - taipan
  DefaultRank: false
  Commands:
  - broadcast! %cmi_user_nickname% &7Voted &n&a560 times! &7Ranked up to {#red>}ʀᴇᴅʙᴀᴄᴋ＋{#lonestar<}
  - asConsole! lp user [playerName] parent settrack votetrack redbackplus
```

### Relevant Plugins

Vault 1.7.3-CMI, VotingPlugin, NuVotifer

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
