### ISSUE TITLE
Info alias does not fill player names

### ISSUE THREAD

**Issue by unnamed199cz** [Zrips/CMI#9010]
### Description of Issue

/info as alias, either normal, or customalias does not fill the name
Im not the only one having this issue, I asked on discord and helper gecko10000 had same issue

### Version Information

```shell
[09:26:39 INFO]: CMI: 9.7.4.9 SqLite
[09:26:39 INFO]: CMILib: 1.5.1.0 
[09:26:39 INFO]: Server: Paper(124) 1.21-R0.1-SNAPSHOT-
[09:26:39 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[09:26:39 INFO]: Modules -> 54 enabled 12 disabled: coloredArmor, disabledEnchants, worldLimitsElytra, mirror, worldLimits, tablist, ranks, playerCombat, elytraExploit, headDrop, playerChatTag, bossBarCompass
```

### Errors

```shell
No errors
```

### Relevant Config Sections

```yaml
Customalias  
info:
    Cmds:
    - cmi info $1  (or $1-, both wont work)

alis in settings
  # /cmi iteminfo $1-
  /iteminfo:
    Enabled: true
    Tab: true
  #
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by unnamed199cz** [comment]
![image](https://github.com/user-attachments/assets/9c3bbac0-7097-40b5-879d-63e57d5dcfe4)
this worked as fix most prolly

**Comment by Zrips** [comment]
Issue would be with having multiple commands with same name processing tab complete. If you want to use /info command in custom alias you will need to disable one in alias.yml to avoid issues with that. Same thing can happen when you have different plugins controlling command with that name. When that happens you can try modifying tabcompletes with ingame editor or add it into file itself which would look something like
```
  in:
    Cmds:
    - cmi info $1
    CustomTabs:
    - '[playerName]'
    - staticTabCompleteWord
```
or add/enable "AddTabs" option
`    AddTabs: true`
Its always best to test new commands by setting their name to something what is not used anywhere else, just to be sure that it doesn't have interference
