### ISSUE TITLE
Holograms limited characters using old display method.

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#9012]
### Description of Issue

Holograms with a long name get cut off using default display method.
Old method:
![image](https://github.com/user-attachments/assets/4843cf04-f78c-4f1d-937b-9a88051a16de)
New method:
![image](https://github.com/user-attachments/assets/0db89f11-8512-4aac-b8bd-ec866f9768b0)

### Version Information

```shell
[18:41:33 INFO]: CMI: 9.7.4.9 Unknown  SqLite
[18:41:33 INFO]: CMILib: 1.5.1.0 
[18:41:33 INFO]: Server: Paper 1.21-R0.1-SNAPSHOT-
[18:41:33 INFO]: CMI economy: ᴅɪꜱᴀʙʟᴇᴅ CMI Chat: ᴅɪꜱᴀʙʟᴇᴅ 
[18:41:33 INFO]: Modules -> 63 enabled 3 disabled: customMessages, tablist, moneyCheque
```

### Relevant Config Sections

```yaml
Egg-ceptionalCrate:
  Loc: Spawn;-130.5;37.61;42.5
  Range: 8
  RangeExtra: 16
  Lines:
  - ICON:egg
  - '{#EDAAFF}🐇 {#EDAAFF>}&lEgg-ceptional Crate{#FFF89A<} {#FFF89A}🐇'
  - '&r'
  - '&7(Expired)'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
