### ISSUE TITLE
Removing Warns when relogging the plugin

### ISSUE THREAD

**Issue by ElielMato** [Zrips/CMI#9015]
### Description of Issue

Hello, I want to say that in the last CMI update, I had several problems with my servers. Because the users' warns are not saved. When I place a warn and my server is restarted or the plugin is re-logined, the warn is not saved.

### Version Information

```shell
Versión de CMI: 9.7.4.9
Versión de CMILib: 1.5.1.0
```

### Relevant Config Sections

```yaml
Warnings:
  Default:
    LifeTime: 7776000
    Points: 1
    DefaultReason: '&7Violated server rules'
  Categories:
    Swear:
      LifeTime: 7776000
      Points: 3
      DefaultReason: '&7Swearing'
  Perform:
    '3':
    - cmi tempban [playerName] 3d Acumulacion de Warns
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
