### ISSUE TITLE
cmi rt sometimes teleports players just a few blocks or teleports them into water.

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#904]
The title says it all.

**Comment by CloudeLecaw** [comment]
Setup your randomteleport Option?

**Comment by CloudeLecaw** [comment]
RandomTeleportation:
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
```
    world:
      Enabled: true
      MaxCoord: 1000
      MinCord: 500
      CenterX: -300
      CenterZ: -500
```


This example means. your Center of your world is at -500x and -300z

if you use cmi rt then you get teleported minmum 500 Blocks radius away from this Center
but maximum 1000 Blocks away from this Center.
