### ISSUE TITLE
I cant add a variable like specified mob killing

### ISSUE THREAD

**Issue by Mcdikmen** [Zrips/CMI#9101]
### Description of Issue

I cant add a variable like specified mob killing. And there is no any error about it.

![image](https://github.com/user-attachments/assets/970651bd-ee73-44cd-b9a3-775b5349f9a1)
![image](https://github.com/user-attachments/assets/0a3e8e7a-a312-4ef3-a8d2-2ec8a59631fd)

### Version Information

```shell
[23:10:16 INFO]: CMI: 9.7.5.7 SqLite-> 9.7.5.5
[23:10:16 INFO]: CMILib: 1.5.1.3
[23:10:16 INFO]: Sunucu: Paper(149) 1.20.6-R0.1-SNAPSHOT-
[23:10:16 INFO]: CMI ekonomisi: Enabled Kasa: 1.7.3-CMI CMI sohbeti: Enabled 
[23:10:16 INFO]: Modüller -> 64 Etkin 2 Devre dışı: tablist, votifier
```

### Errors

```shell
No error.
```

### Relevant Config Sections

```yaml
# Main server folder spigot.yml and check that stats saving prevention its set to false stats->disable-saving: false
# Player will get default rank group depending on set permission node cmi.rank.[groupName]
# Not enabled ranks will be ignored
# DisplayName section is optional and it will be used to represent rank ingame. This is NOT defining required permission node and you still need to use node name to rankup to this rank
# DefaultRank section defines if player can be assigned to this rank if he dont have any. There can be more than one default rank, and depending on permision node, first rank will be assigned to that player when needed
# PermissionRequirement section defines list of permissions player should have to rankup to that rank. Optional - For each permission node you can add its name which will be shown in /cmi rankinfo with : In example cmi.command.fly:Fly
# McMMORequirement section defines list of McMMO skills and levels player should have to rankup to that rank.
# AureliumRequirement section defines list of Aurelium skills and levels player should have to rankup to that rank.
# AuraSkillsRequirement section defines list of Aura skills and levels player should have to rankup to that rank.
# McMMO and Aurelium sections can use skill name as Power to indicate total sum of all skills
# JobsRequirement section defines list of Jobs and levels player should have to rankup to that rank.
# ItemRequirement section defines list of items player should have to rankup to that rank. Items will be taken after succesfull rankup from players inventory.
# AutoRankup section defines if player will be auto ranked to this rank if possible. Keep in mind that if there is more than one legit rankup, player will have to confirm to which rank he wants to rankup
# RankupConfirmation section defines if you want to add additional confirmation for this rankup. Usefull to avoid unintentional rankups. Keep in mind that autorankup will request confirmation for rankup to this rank even if there is only one legit rankup option
# NextRanks is list of possible next ranks from this rank. Can be one or can be dozens. Keep in mind that each rank requirements will be shown in chat and it can clutter quite allot if there is bunch of them at once
# MoneyCost defines how much player will have to pay to rankup to this rank
# ExpCost defines how much player will have to pay in exp to rankup to this rank
# Votes defines how much player will need to have votes to rankup to this rank
# Commands is list which will be performed on rankup. Can be additional actions, like message broadcast or anything alse
# Main section is StatsRequirements and it can have allot of different values in it:
#   In general format goes like this [mainStat](:optionalSubStat):amount
#   In example MonsterKills:100 will require from player to have 100 monster kills while MonsterKills:Zombie:100 will require to have 100 zombie kills. Both of them can be used if needed.
#     List of possible requirement and basic explanations:
#       Distance in blocks:
#         Travel - travel in total
#         Walk - has to walk
#         Sneak - has to sneak
#         Sprint - has to sprint
#         Swim - has to swim
#         Fall - has to fall
#         Climb - has to climb
#         Fly - has to fly
#         Dive - has to walk under water
#         MinecartTravel - has to travel with minecart
#         BoatTravel - has to travel with boat
#         PigTravel - has to ride pig
#         HorseTravel - has to ride horse
#         ElytraTravel - has to fly with elytra
#       Time in sec:
#         PlayTime - total play time
#         FromLastDeath - from last death
#         SneakTime - sneak time
#       Amounts:
#         GameQuit - how many times player left game
#         Jump - jump count
#         DamageDealt - total damage made
#         DamageTaken - total damage taken
#         Deaths - count of deaths
#         MobKills - total amount of mobs killed by player
#         PlayerKills - total amount of players killed. Indirect kills dont count
#         ItemEnchanted - amount of enchanted items
#         AnimalsBred - animals bred
#         FishCaught - fish caught
#         TalkedToVillager - times talked to villager
#         TradedWithVillager - traded with willager
#         CakeSlicesEaten - cake slices eaten
#         CauldronFilled - cauldron filled
#         CouldronUsed - couldron used
#         ArmorCleaned - times armor cleaned (leather armor)
#         BannerCleaned - times banner cleaned
#         BrewingstandInteractions - brewingstand interactions
#         BeaconInteractions - beacon interactions
#         CraftingTableInteractions - crafting table interactions
#         FurnaceInteractions - furnace interactions
#         DispenserInspected - dispenser inspected
#         DropperInspected - dropper inspected
#         HopperInspected - hopper inspected
#         ChestOpen - chest open
#         TrappedChestTriggered - trapped chest triggered
#         EnderchestOpened - enderchest opened
#         NoteblockPlayed - noteblock played
#         NoteblockTuned - noteblock tuned
#         FlowerPotted - flower potted
#         RecordPlayed - record played
#         SleeptInBed - sleept in bed
#         ShulkerBoxOpened - shulker box opened
#         ItemDropped - defines amount of dropped items. If specific item is not defined, then total amount is used
#         ItemPickups - defines amount of picked up items. If specific item is not defined, then total amount is used
#         BlocksMined - defines amount of blocks mined. If specific block is not defined, then total amount is used
#         BlocksPlaced - defines amount of blocks placed. If specific block is not defined, then total amount is used
#         ItemBreaks - defines amount of broken items. If specific item is not defined, then total amount is used
#         ItemCrafts - defines amount of crafted items. If specific item is not defined, then total amount is used
#         ItemsUsed - defines amount of item usage. like mining with pickaxe. If specific item is not defined, then total amount is used
#         MonsterKills - defines amount of monster kills. If specific monster is not defined, then total amount is used
#         KilledBy - defines amount of deaths by monster. If specific monster is not defined, then total amount is used

I:
  Enabled: true
  DisplayName: '&2[I]'
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - II
II:
  Enabled: true
  DisplayName: '&2[II]'
  AutoRankup: true
  RankupConfirmation: true
  StatsRequirements:
  - MonsterKills:zombie:10
  - PlayTime:10800
  - FromLastDeath:3600
  ItemRequirement:
  - wool:10
  - wheat:64
  Votes: 5
  NextRanks:
  - III
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Branch1 rank!
  - lp user [playerDisplayName] permission set simyaci.standi.kullanimi true
III:
  Enabled: true
  DisplayName: '&2[III]'
  AutoRankup: true
  RankupConfirmation: true
  StatsRequirements:
  - MonsterKills:zombie:10
  - PlayTime:10800
  - FromLastDeath:3600
  ItemRequirement:
  - wool:10
  - wheat:64
  Votes: 5
  NextRanks:
  - IV
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Branch1 rank!
  - lp user [playerDisplayName] permission set simyaci.standi.kullanimi true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
