### ISSUE TITLE
Teleports that don't work are not giving any feedback

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#9109]
### Description of Issue

If a teleport fails, presumably for being "unsafe" players are not getting told... they simply fail to teleport.  No mention of an unsafe location, nor of anything else.  No offer of /tpbypass.  Just the player doesn't `move.`
Examples:
/home (name of home) - some homes just nothing happens
/patrol - if the player being patrolled is under water, in lava, etc, patrol says it is patrolling them but the admin doesn't actually move

Other plugins tps are also failing at times, usually silently, and only when CMI is installed.  These are intermittent failures... sometimes they work.. then they stop working for everyone and then they start again.  I do not know what causes the failures and, since they are intermittent, I cannot be sure they are related to CMI.   Noting that they generally don't say they are failing, either, though /desc  and /asc do -- they say no free space found (even when there is one... and sometimes moving to a different part of the block fixes them)
Examples:
/t spawn (towny town spawn command)
/n spawn (towny nation spawn command)
/thru (worldedit command)
/asc (worldedit command)
/desc (worldedit command)

### Version Information

```shell
[12:56:26 INFO]: --------------------------------------------------
[12:56:26 INFO]: CMI plugin version: 9.7.5.8 MySQL
[12:56:26 INFO]: CMILib: 1.5.1.3 
[12:56:26 INFO]: Server: Paper(52) 1.21.1-R0.1-SNAPSHOT+
[12:56:26 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[12:56:26 INFO]: Modules -> 58 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[12:56:26 INFO]: --------------------------------------------------
```

### Errors

```shell
No console errors, nor any player feedback.  Fails silently
```

### Relevant Config Sections

```yaml
<  Teleport:
    # Players need to have cmi.safeteleport permision node to be placed in a safe location when teleporting to target location
    # When true then while checking for safe location, we will try to determin it going down and if it fails, then up from target location
    # When set to false, then first of all location above target location will be checked, then down
    SafeLocationDownThenUp: true
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 5
    # When this set to true each time player teleports to any destination he will be teleported to spawn point
    # This is to prevent from people knowing to which direction you have teleported too
    # As everyone noticed, teleportation doesnt actually teleport you, but moves to targetdestination in short time
    ToSpawnBefore: false
    # Set to true if you want to use tp commands as /cmi tp [WhoYouWantToTeleport] [WhereToTeleport] when its false, its /cmi tp [whereToTeleport] [WhoYouWantToTeleport]
    SwitchPlaces: true
    CurrentLoc:
      # Applies for tpa, tpahere and tpaall only
      # If set to true then player will be teleported to current player position after accepting teleport request
      # If set to false then player will be teleported to player at which teleport request was issued
      tpa: true
      # Applies for tpahere only
      tpahere: true
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 100
    Tpa:
      # Defines time in seconds for accepting tpa or tpahere requests
      Time: 60
      # Defines time in seconds for player being teleported after tpa or tpahere is being accepted
      Warmup: 2
      # Defines if player can move when tpa or tpahere is being accepted
      Move: false
      # Defines time in seconds for blocking player teleport offers after denying their request
      Block: 120
      # Distance in blocks for max teleportation range
      # Set to 0 if you want to disable it
      # Having it at any positive number will prevent players requesting teleportations to player in other wolds in adition to limiting it by range between players
      # Can be bypassed by player having cmi.command.tpa.max.[blockcount] permission node
      MaxDistance: 0
    TpaHere:
      # Distance in blocks for max teleportation range
      # Set to 0 if you want to disable it
      # Can be bypassed by player having cmi.command.tpahere.max.[blockcount] permission node
      MaxDistance: 0
    Tp:
      # Defines time in seconds for bypassing prevented teleportation to unsafe location
      Bypass: 15
    # When set to true adds accept and deny buttons when sending tpa or tpahere requests
    DenyConfirm: true
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in his inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: false
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    # Back location will not be triggered if player teleports closer than defined amount of blocks
    BackMinDistance: 5
    # When set to false we will not include teleport location when teleporting around with worldedit compass
    # When set to true we will include each teleport action, even if you simply jumped around with compass
    BackWithWE: true
    # List of worlds to which players can't return using the /back command
    BackBlackList:
    - pvp
    - NewPvP
>
```

### Relevant Plugins

Towny 0.100.3.12, Worldedit 7.3.6

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
