### ISSUE TITLE
ExploitPatcher Riptide not limited to pweather

### ISSUE THREAD

**Issue by Lhoto** [Zrips/CMI#9110]
### Description of Issue

In config.yml, the setting for Riptide under ExploitPatcher states that the setting will disable usage of riptide when pweather is rainy and the server is sunny. This is not the case, as both myself and one of our players gets the relevant message (about currently being unable to use the trident) during normal sunny weather without pweather involved. This leads to issues with interacting with things such as doors/buttons/etc with the trident in-hand.

You can replicate this while the setting is true by having just normal sunny weather (no /pweather involved) and trying to use a riptide trident. As soon as the setting is set to false, this behavior goes away.

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.5.8 SqLite-> 9.7.5.9
CMILib: 1.5.1.3 
Server: Paper(2299) 1.21.1-R0.1-SNAPSHOT+
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 61 enabled 5 disabled: chatBubble, shulkerBackpack, moneyCheque, headDrop, kits
--------------------------------------------------
```

### Relevant Config Sections

```yaml
(config.yml)

ExploitPatcher:
  # When enabled we will not allow usage of riptide while player has pweather set to rain while players world is in sunny state
  Riptide: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
