### ISSUE TITLE
AFK kick feature not working

### ISSUE THREAD

**Issue by Achent007** [Zrips/CMI#9120]
### Description of Issue

Hello!
Since some days i have my players on the afk state but got never kicked and they have the permission `cmi.command.afk.kickOutIn.600` and on the config i have this :

### Version Information

```shell
CMI: 9.7.5.9 Unknown  MySQL
CMILib: 1.5.1.3 
Server: Paper(40) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Désactivé(e) CMI Chat: Activé(e) 
Modules -> 41 enabled 25 disabled: spawnerProximity, cuffed, tablist, moneyCheque, elytraBoost, elytraLaunch, bossBarCompass, chatBubble, playerCombat, votifier, headDrop, spawnerCharge, vanish, timedCommands, launchPad, elytraExploit, jail, spawners, flightCharge, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, totemBehavior
```

### Relevant Config Sections

```yaml
:
  Enabled: true
  TitleMessage: true
  SubTitleMessage: true
  PreventJumping: true
  PreventDamage: false
  CheckInterval: 2
  StopPlayTime: true
  AutoAfkIn: 300
  AutoAfkCmds: []
  ManualAfkCmds: []
  AfkLeaveCmds: []
  AutoKickIn: 600
  RepeatingAutoKickInterval: 600
  RepeatKickCommand: false
  AutoKickCmds:
  - cmi server Lobby-01 [playerName]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
