### ISSUE TITLE
heal command give you nightvision for one secound...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#9126]
### Description of Issue
When the /heal command is used you gain night vision effect for one secounds.
Also you see in chat that you got this effect :3

![02-09-2024_23-46-15](https://github.com/user-attachments/assets/0aecc595-215e-4fb4-abcd-5e2f46735dce)

### Version Information
![{FDF4A69D-6127-4F0A-BA5B-EF6853B4E64A}](https://github.com/user-attachments/assets/4c354b4d-5b13-4de5-89c7-aa26ab9f3db5)

### Relevant Config Sections
```yaml
heal:
  RemoveNegative:
    # Do you want to remove negative potion effects from player on heal
    use: true
    List:
    - bad_omen
    - blindness
    - confusion
    - fatal_poison
    - harm
    - hunger
    - instant_damage
    - mining_fatigue
    - nausea
    - poison
    - slow
    - slowness
    - slow_digging
    - unluck
    - weakness
    - wither
```

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
