### ISSUE TITLE
Shulker Backpack not opening with rightclick, only shift rightclick

### ISSUE THREAD

**Issue by itisRas** [Zrips/CMI#9127]
### Description of Issue

The Shulker Backpack feature where you can open a shulker box from inside your inventory or the hotbar by rightclicking is not working. It only works when I shift rightclick. 

I tested it in the following situations:
1. No permissions as OP (Allowed to open with shift rightclick in inventory and from hotbar)
2. Not OP, with cmi.openshulker true (Only opened with shift rightclick in inventory)
3. Not Op, with cmi.openshulker true and cmi.openshulker.shift true (Allowed to open with shift rightclick in inventory and from hotbar)
4. Not Op, with cmi.openshulker false and cmi.openshulker.shift true (Only opened with shift rightclick from hotbar)
5. Not Op, with cmi.openshulker false and cmi.openshulker.shift false (Didnt open)

### Version Information

```shell
[Server] INFO --------------------------------------------------
[Server] INFO CMI: 9.7.5.9 MySQL
[Server] INFO CMILib: 1.5.1.3 
[Server] INFO Server: Paper(40) 1.21.1-R0.1-SNAPSHOT+
[Server] INFO CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[Server] INFO Modules -> 64 enabled 2 disabled: flightCharge, votifier
[Server] INFO --------------------------------------------------
```

### Errors

```shell
No Errors
```

### Relevant Config Sections

```yaml
CMI Config:

ShulkerBoxes:
  # When set to true, players will not have option to open shulker boxes while in combat
  # Combat timer can be defined under combat section
  PreventInCombat: false
  # Money cost to open shulker box, if player doesn't have enough money then we will not allow to open shulker box from inventory
  # Setting this to 0 will disable money requirement
  # This can be bypassed with cmi.openshulker.free permission node
  CostToOpen: 0.0

CMI Modules:

# Handles shulker box as backpacks
# Applies for servers from 1.11.x and up
shulkerBackpack: true
```

### Relevant Plugins

All the Plugins on my server: CMI, CMILib, LuckPerms, Vault (CMI recompiled version), WorldEdit, WorldGuard

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
