### ISSUE TITLE
afk get not unfak on moving in defined checktime...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#9135]
### Description of Issue

Well i said it.. when you just walk with WASD (no mouse movement) then the afk will not end withing the devined checktime
https://streamable.com/g62vm5
looks like its random until it finishes on movement with WASD

### Version Information
![05-09-2024_21-47-48](https://github.com/user-attachments/assets/b4eed3b6-2698-47f1-a2ed-e8f98e40219e)

### Relevant Config Sections
```yaml
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: false
  # When enabled shows random subtitle message
  SubTitleMessage: false
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 2
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 600
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName]
    wurde durch zulanges rumstehen AFK gesetzt.</H>
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - 'cmi ctellraw all <T>&6[playerDisplayName] &eist jetzt AFK.</T><H>[playerDisplayName]
    hat folgenden Grund angegeben: %cmi_user_afk_msg%</H>'
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi ctellraw all <T>&6[playerDisplayName] &eist nicht mehr AFK.</T><H>[playerDisplayName]
    war AFK wegen %cmi_user_afk_msg% für %cmi_user_afk_for%.</H>
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: 300
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &eDu wurdest wegen langen AFK gekickt [time]
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - InAllenWeltenAktiv
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Prevents players from being  pooled around while player is in afk mode
  PreventHook: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on camera movement
  DisableOnLookAround: true
```

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
