### ISSUE TITLE
Unknown source appears when using the itemsadder events feature

### ISSUE THREAD

**Issue by NanShang126** [Zrips/CMI#9136]
### Description of Issue

Unknown source appears when using the itemsadder events feature
Executing CMI spawn {player} through itemsadder events. execue_commands appears
`Unknown CMI command source (CONSOLE) spawn {player}`

### Version Information

```shell
CHI: 9.7.5.3 
CHILi6: 1.5.1 1
server: paper(2301)1.21.1-R0.1-SHAFSHOT+
```

### Relevant Config Sections

```yaml
itemsadder 
items:
  test:
    display_name: test
    resource:
      material: COAL
      generate: true
      textures:
        - "minecraft:item/diamond.png"
    events:
      interact:
        right:
          execute_commands:
            cmd1:
              command: 'cmi spawn {player}'
              as_console: true
              delay: 0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
