### ISSUE TITLE
ItemRenaming option

### ISSUE THREAD

**Issue by bladeRR** [Zrips/CMI#9137]
### Description of Issue

Hello, I am using the ItemRenaming using custom names for the items, as we can see in the example of : - iron_sword:(Maltes Schwert) , you should not be able to change the name or edit it, but the problem is when you delete the custom name, because it allows you to change the name of the object which should not happen. Attached is a short video of the problem

https://youtu.be/whuhaXSJ-x4

List:
  - GOLD_NUGGET:([A-z]+ (?i)\w*spawner)
  - chest
  - gold_nugget
  - goldnugget
  - iron_sword:(Maltes Schwert)

### Version Information

```shell
[04:54:07 INFO]: --------------------------------------------------
[04:54:07 INFO]: Versión de CMI: 9.7.5.9 Unknown 
Base de Datos: SqLite► 9.7.6.1
[04:54:07 INFO]: Versión de CMILib: 1.5.1.3 
[04:54:07 INFO]: Versión del Servidor: Paper(130) 1.21-R0.1-SNAPSHOT-
[04:54:07 INFO]: Economía de CMI: Activado | Vault: 1.7.3-CMI | Chat de CMI: Desactivado 
[04:54:07 INFO]: Módulos: 64 activados y 2 desactivados (votifier | kits)
Archivo de Idioma: v21.10.16
Traducido por: C4BR3R4 (c4br3r4.es)
[04:54:07 INFO]: --------------------------------------------------
```

### Errors

```shell
no errors in console
```

### Relevant Config Sections

```yaml
ItemRenaming:
  # When set to true, players will be denyied from renaming defined items in anvil or with itemname command
  # Option to define specific name by using regex format
  # Can be bypassed with cmi.anvil.itemrename.bypass
  Prevent: true
  # When set to true item renaming will be disabled in general, with anvil or command independent of renamed material
  # This can be bypassed with previous permission node
  GlobalDisable: false
  # Defines maximum length of item name excluding color codes for itemname command
  # Set it to 0 if you want to remove restrictions
  MaxLength: 64
  # List of materials followed with optional regex code which can prevent specific naming, like renaming mob spawners into another type while still allowing renaming spawner into anything else
  List:
  - GOLD_NUGGET:([A-z]+ (?i)\w*spawner)
  - chest
  - gold_nugget
  - goldnugget
  - iron_sword:(Maltes Schwert)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
