### ISSUE TITLE
Occasional bug picking up spawners

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#9155]
### Description of Issue

I have gotten several reports of people having a charge available, but when they mine a spawner, they can't and their timer resets.
I let people check their spawner cooldown with this custom command:

```
  silkspawner:
    Cmds:
    - statement:ready! check:%cmi_user_charges_time%==-
    - if:ready@! msg! [playerName] {#A180D0}ʏᴏᴜ ʜᴀᴠᴇ {#BDB0D0}%cmi_user_charges_time%
      {#A180D0}ʟᴇꜰᴛ ᴏɴ ʏᴏᴜʀ ꜱɪʟᴋ ꜱᴘᴀᴡɴᴇʀ ᴄᴏᴏʟᴅᴏᴡɴ.
    - if:ready! msg! [playerName] {#A180D0}ʏᴏᴜ ʜᴀᴠᴇ ɴᴏ ᴀᴄᴛɪᴠᴇ ᴄᴏᴏʟᴅᴏᴡɴ. ɢᴏ ᴍɪɴᴇ ᴀ
      ꜱᴘᴀᴡɴᴇʀ!
    Perm: true
```

And if that command says they can mine a spawner, and they actually attempt to mine one, it says they've already used up all their charges and their cooldown resets to 24 hours, which is the cooldown we sat.

Quote from staff of our server:
`A few players have brought this up now including xxx, xxxx & Myself, when doing /silkspawner it says you are able to break the spawner but when you try the spawner doesnt break and it resets the timer to 24h, i will try to get a video if it happening as it is rather sporadic when it happens or when it doesnt - To clarify, it doesnt happen every single time, sometimes it works as intended and you can break spawners`

### Version Information

```shell
--------------------------------------------------
[20:58:28 INFO]: CMI: 9.7.6.2 Unknown  SqLite-> 9.7.6.2
[20:58:28 INFO]: CMILib: 1.5.1.3 
[20:58:28 INFO]: Server: Paper 1.21.1-R0.1-SNAPSHOT-
[20:58:28 INFO]: CMI economy: ᴅɪꜱᴀʙʟᴇᴅ CMI Chat: ᴅɪꜱᴀʙʟᴇᴅ 
[20:58:28 INFO]: Modules -> 63 enabled 3 disabled: customMessages, tablist, moneyCheque
[20:58:28 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Could you provide your setup for spawner charges from config file?

**Comment by Yertled** [comment]
> Could you provide your setup for spawner charges from config file?

```
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # ATTENTION! cmi.dropspawner will be required to get spawner dropping for the player
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: false
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 100
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: false
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
    # If set to false, then player will need to have basic cmi.placespawner permission to place any type of spawner
    RequiresExactPermission: false
  Interact:
    Spawner:
      # When set to true, players trying to change spawner with monster egg will require appropriate permission node
      # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
      RequiresPermission: true
    TrialSpawner:
      # When set to true, players trying to change trial spawner with monster egg will require appropriate permission node
      # In example: player should have cmi.trialegginteract.pig to change spawner into pig, or cmi.trialegginteract.zombie to change into zombie spawner
      RequiresPermission: false
  # If set to true, spawners will have chance to be dropped when destroying with tnt
  TnTExplosionDrop:
    use: false
    # Chance in percentage for spawner to drop
    Chance: 30
  # If set to true, spawners will have chance to be dropped when destroyed by creeper
  CreeperExplosionDrop:
    use: false
    Chance: 30
  Charges:
    # When enabled players will be assigned to particular spawner charges group who have cmi.spawners.charge.[groupName] permission node
    # Players will be limited to how many spawners they can mine
    # StartingCharge will determine how many charges they will have on first time joining group
    # MaxCharge will limit to how many charges you can have at one time
    # Cooldown determines how often new charge will be given
    # Bonus is optional and it will determine by how many seconds to lower cooldown for next charge when placing spawner
    # Option to bypass limitations with cmi.spawners.charge.bypass
    Use: true
    # If set to true when player runs out of spawner charges spawner will be destroyed without droping it
    BreakWithoutCharge: false
    List:
      Allay:
        Use: true
        StartingCharge: 1
        MaxCharge: 1
        Cooldown: 86400
      Advanced:
        Use: false
        StartingCharge: 3
        MaxCharge: 6
        Cooldown: 3000
        Bonus: 10
  Proximity:
    # Allows to limit how tight spawners can be placed from each other
    Use: true
    # Radius in blocks from placed block. Max range is 16
    # Can be bypassed with cmi.spawners.proximity.bypass
    Range: 16
```
