### ISSUE TITLE
ICs wont work if conntect to Citicenz

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#9156]
### Description of Issue
When you have an IC and connect it to a citizens and use left right shiftright and shiftleft you can see it will not work
if this IC is attached to a citicenz
looking in the IC file i see they are connected...
Here a video
https://streamable.com/lx0tyf

### Version Information
![11-09-2024_21-44-39](https://github.com/user-attachments/assets/ddf25d66-6b0c-4c3c-9a43-0a419074bae0)

### Errors
None in the console

### Relevant Config Sections
The IC:
```yaml
TestTestTest:
  Locations:
  - world;1782;-54;1926
  - world;1788;-54;1933
  NPC:
  - 321_18007036-50d1-23e6-bec0-b85eda0fdc75_18007036-50d1-43e6-bec0-b85eda0fdc75
  Commands:
  - click:left! hasitem:stone-32! item:stone-32! asConsole! cmi money give [playerName] 32 -s
  - click:right! hasitem:stone-32! item:stone-32! asConsole! cmi money give [playerName] 32 -s
  - click:leftshift! hasitem:stone-64! item:stone-64! asConsole! cmi money give [playerName] 64 -s
  - click:rightshift! hasitem:stone-64! item:stone-64! asConsole! cmi money give [playerName] 64 -s
  - delay! 0.2
```

The Citizen NPC:
```yaml
  '321':
    metadata:
      cached-skin-uuid: 454e83a0-fc86-42f1-aba4-954b060f4558
      cached-skin-uuid-name: hanspeter
      nameplate-visible: 'true'
      swim: true
    name: Hans Peter
    uuid: 18007036-50d1-43e6-bec0-b85eda0fdc75
    traits:
      owner:
        uuid: f24df990-9c6b-4f32-938a-4c91a26d31f4
      location:
        bodyYaw: 43.265472
        world: world
        x: 1785.4526
        y: -54.0
        z: 1930.4362
        yaw: 43.2655
        pitch: -44.7876
      type: PLAYER
      skintrait:
        signature: c2QHO4E/W03qmPfjMQaHO6qxrwrxbK/neNn4gxKDCBkIB2fsYwAPMRORi21swxjug/kLx7b1qup2/gtM3hswN4eRTNInwZaadzyGi7IMIfVPr1o8kEpAaQAeY1P/BiNCjt+RHH6aV/Zt/tNDk+mYWJpFhkv5SSKQqocriwdDe1jpw9wqW2uADqy6KU9oIVWwZ2bAm05eYGu4SzIRhhN6hc3d1PbPXwusmFeo8rNoNbIh/vs27LbQ3j5khITMR5gWXoJs2hnEK4nN3ZcixlhPddBtemVMx19hYBDSog0gPcLhCXXY3pr1fP+h6JxRTLSrNmY8QKKnHsM7Pw6thXa3Og+bPYqj8Mku9ojbcj8kByfMD13imworRNx6dJeineVzV2NBrHJlECwo2v7QMXxKbu1YXGc2aLyIk636ZUYmNmR31ANEZM7HD7/YUDknRL+pewKlwAQ+8qdXzA4KMbzj64k4gaq9lnJNWG/yAML54Unl+K2Vm+6hxHCbnFITalUAe1KJStaJQSiLRNRTEHYVNUgCjM5Wrw0ZzCDC8aiZ3PHOFLnat+u9DjD2kuhclHKD9lmnnFXjk/Jq4WF56YeUR+E5394xWtk1BEEpbLMcf/XK6Hf5NB5tIcT8UDf+Xoi8fvHV7dHGCj57qfOGB0f0VuuaunxbArhv/+X3PVrNupI=
        textureRaw: ewogICJ0aW1lc3RhbXAiIDogMTY4MjYyODkzNTQ4NywKICAicHJvZmlsZUlkIiA6ICI0NTRlODNhMGZjODY0MmYxYWJhNDk1NGIwNjBmNDU1OCIsCiAgInByb2ZpbGVOYW1lIiA6ICJIYW5zUGV0ZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJjMmJjM2E1YmExNTM3NzA3NjhhNmI4ZWMzOTUzNzlmNmQxMmI0NDNhNWVhOWVmOThkNGI0MWZmZGM4NWRhZiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9
      lookclose:
        range: 5.0
        randomPitchRange:
          '0': 0.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      text:
        talk-close: true
        random-talker: true
        realistic-looking: true
        speech-bubbles: true
        text:
          '0': Hallo <player>
          '1': Hiho <player>
          '2': Allo Allo <player>
      spawned: true
      hologramtrait:
        direction: BOTTOM_UP
    traitnames: type,lookclose,mounttrait,spawned,scoreboardtrait,owner,hologramtrait,rotationtrait,skintrait,text,location,inventory
    navigator:
      speedmodifier: 1.0
      avoidwater: false
      usedefaultstuckaction: true
```

### Relevant Plugins
Citizens_2.0.35-Build3558

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
