### ISSUE TITLE
First Spawnpoint not working after update

### ISSUE THREAD

**Issue by Yertled** [Zrips/CMI#9164]
### Description of Issue

Ever since I updated to 9.7.6.2, brand new players spawn in the overworld, and not in our spawn world. 
Proof in console:
`[06:32:13] [Server thread/INFO]: .Litery3466[/x.x.x.x] logged in with entity id 899916 at ([world]31.5, 66.0, -46.5)`

I don't want them to spawn in "world", but in "Spawn"

### Version Information

```shell
[10:25:28 INFO]: --------------------------------------------------
[10:25:28 INFO]: CMI: 9.7.6.2 Unknown  SqLite
[10:25:28 INFO]: CMILib: 1.5.1.3 
[10:25:28 INFO]: Server: Paper 1.21.1-R0.1-SNAPSHOT-
[10:25:28 INFO]: CMI economy: ᴅɪꜱᴀʙʟᴇᴅ CMI Chat: ᴅɪꜱᴀʙʟᴇᴅ 
[10:25:28 INFO]: Modules -> 63 enabled 3 disabled: customMessages, tablist, moneyCheque
[10:25:28 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```
Spawn:
  # Forces players to login in defined spawn point when logging into server
  # Can be bypasses with cmi.spawnonjoin.bypass permission node
  SpawnOnJoin: false
  # List of worlds which should be ignored and players joining in those servers will not be teleported to appropriate spawn point but will login at their log out location
  IgnoredWorlds: []
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  # TeleportFrom will indicate list of worlds from which player should be teleported to this spawn point
  Main:
    World: Spawn
    X: 0.5
    Y: 65.0
    Z: 0.5
    Pitch: -3.20971E-5
    Yaw: -89.98206
    RespawnLocation: false
    Rng: 0
    TeleportFrom: []
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    Location: Spawn;0.5;65.0;0.5;-89.98;0.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
