### ISSUE TITLE
Custom Time

### ISSUE THREAD

**Issue by MeisterVox** [Zrips/CMI#9189]
### Description of Issue

It always happens when I restart the server that the custom time disappears from the other worlds. The entry only remains in the main world.
And when I am in Vanish, the AFK still takes effect and displays a message that I am now AFK.
Permission for AFK was not set.

### Version Information

```shell
CMI Plugin Version: 9.7.6.4 SqLite
CMILib: 1.5.1.4
Server: Paper(105) 1.21.1-R0.1
```

### Errors

```shell
Nothing
```

### Relevant Config Sections

```yaml
lobby:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90

#### This part will be removed
   # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    CB1:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 6900
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 300
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 1500
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 300
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    fb1:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 7080
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 120
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 1680
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 120
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    bautest:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    parkour:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    FarmWelt:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 6900
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 300
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 1500
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 300
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
