### ISSUE TITLE
Problems with hex colors

### ISSUE THREAD

**Issue by ChrisTVH** [Zrips/CMI#9197]
### Description of Issue

- Well, it turns out that by default CMI has some options in CMILIB, where it explicitly replaces the hex color codes that come unformatted as #rrggbb to the one it supports.
- So since I stopped using CMI Chat, I disabled these checks since my current chat plugin uses minimessages and everything was fine until I upgraded to the latest version of CMI.
- It doesn't affect the use of hex colors at all, but every time I put a <#rrggbb> it raises an error in the console that wasn't there before.

### Version Information

```shell
- CMI 9.7.6.4
- CMILIB 1.5.1.4
- Server version Paper(118) 1.21.1-R0.1-SNAPSHOT-
```

### Errors

```shell
https://mclo.gs/DL9Z4zL
```

### Relevant Config Sections

```yaml
Colors:
  # When enabled plugin will try to detect simplified hex color codes like #f6f6f6 or #ff6 in adition to {#f6f6f6} and {#red}
  # Keep in mind that this adds extra checks and simplified format will not support gradients or named colors so you will still need to use more complex format for those
  OfficialHex: false
  # When enabled plugin will try to detect quirky hex color codes like &#f6f6f6 or &#ff6 in adition to {#f6f6f6} and {#red}
  # Keep in mind that this adds extra checks and quirky format will not support gradients or named colors so you will still need to use more complex format for those
  QuirkyHex: false
```

### Relevant Plugins

Carbon chat - 3.0.0 Action: # 2949

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
