### ISSUE TITLE
Not working AFK (preventmobspawning)

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9203]
### Description of Issue

I allowed players in AFK mode to do everything, but disabled the feature responsible for spawning mobs from spawners. It doesn’t work for hostile mobs or passive mobs. I tried different settings, both True and False, but nothing seems to work.

### Version Information

```shell
cmi version
[14:13:11 INFO]: --------------------------------------------------
[14:13:11 INFO]: Версия плагина CMI: 9.7.6.5 SqLite
[14:13:11 INFO]: CMILib: 1.5.1.4 
[14:13:11 INFO]: Версия сервера: Purpur(2321) 1.21.1-R0.1-SNAPSHOT-
[14:13:11 INFO]: CMI Экономика: Вкл Версия Vault: 1.7.3-CMICMI Чат: Выкл 
[14:13:11 INFO]: Модули -> 32 включено 34 отключено: spawnerProximity, cuffed, customMessages, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, elevator, chatBubble, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, hpBossBar, anvilRenameColor, jail, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, disabledEnchants, worldLimitsElytra, ranks, silentChest
[14:13:11 INFO]: --------------------------------------------------
>
```

### Relevant Config Sections

```yaml
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: true
  # When enabled shows random subtitle message
  SubTitleMessage: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: false
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 120
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds: []
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds: []
  LeaveCmds:
    # Defines commands to be performed when player leaves afk mode after he entered it manually
    Manual: []
    # Defines commands to be performed when player leaves afk mode after he entered it automatically
    Auto: []
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: -1
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds: []
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  # Disables afk on interaction
  DisableOnInteract: false
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Prevents players from being  pooled around while player is in afk mode
  PreventHook: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: true
  # Disables afk on inventory click
  DisableOnInventoryClick: false
  # Disables afk on item drop
  DisableOnitemDrop: false
  # Disables afk on command usage
  DisableOnCommand: false
  # Disables afk on public chat message
  DisableOnPublicChat: false
  # Disables afk on private chat message
  DisableOnPrivateChat: false
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on camera movement
  DisableOnLookAround: false
  # Disables afk on fishing when you catch fish
  DisableOnFishing: false
  # Disables item pickup while afk
  DisableItemPickup: true
  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: true
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: false
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: true
```
```


### Relevant Plugins

Latest (CMI)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
