### ISSUE TITLE
Auto-rankup not working

### ISSUE THREAD

**Issue by RegencySolid** [Zrips/CMI#921]
**The auto rankup feature doesn't work**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Earth:
  Enabled: true
  DisplayName: "&aEarth"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Water
Water:
  Enabled: true
  DisplayName: "&bWater"
  AutoRankup: true
  Votes: 5
  PermissionRequirement:
  - "pootopia.rank.water"
  NextRanks:
  - Air
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &bWater&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:18000"
Air:
  Enabled: true
  DisplayName: "&fAir"
  AutoRankup: true
  Votes: 10
  PermissionRequirement:
  - "pootopia.rank.air"
  NextRanks:
  - Fire
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &fAir&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:54000"
Fire:
  Enabled: true
  DisplayName: "&cFire"
  AutoRankup: true
  Votes: 15
  PermissionRequirement:
  - "pootopia.rank.fire"
  NextRanks:
  - Obsidian
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &cFire&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:90000"
Obsidian:
  Enabled: true
  DisplayName: "&5Obsidian"
  AutoRankup: true
  Votes: 20
  PermissionRequirement:
  - "pootopia.rank.obsidian"
  NextRanks:
  - Ice
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &5Obsidian&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:180000"
Ice:
  Enabled: true
  DisplayName: "&bIce"
  AutoRankup: true
  Votes: 40
  PermissionRequirement:
  - "pootopia.rank.ice"
  NextRanks:
  - Wind
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &bIce&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:360000"
Wind:
  Enabled: true
  DisplayName: "&fWind"
  AutoRankup: true
  Votes: 60
  PermissionRequirement:
  - "pootopia.rank.wind"
  NextRanks:
  - Volcanic
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &fWind&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:540000"
Volcanic:
  Enabled: true
  DisplayName: "&6Volcanic"
  AutoRankup: true
  Votes: 80
  PermissionRequirement:
  - "pootopia.rank.volcanic"
  NextRanks:
  - Yin
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &6Volcanic&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:720000"
Yin:
  Enabled: true
  DisplayName: "&8Yin"
  AutoRankup: true
  Votes: 100
  PermissionRequirement:
  - "pootopia.rank.yin"
  NextRanks:
  - Yang
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &8Yin&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:1080000"
Yang:
  Enabled: true
  DisplayName: "&fYang"
  AutoRankup: true
  Votes: 125
  PermissionRequirement:
  - "pootopia.rank.yang"
  NextRanks:
  - Spectrum
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &fYang&7!"
  - "asConsole! cmi sound ui_toast_challenge_complete [playerName]"
  StatsRequirements:
  - "PlayTime:1440000"
Spectrum:
  Enabled: true
  DisplayName: "&cS&6p&ee&ac&bt&9r&5u&dm"
  AutoRankup: true
  Votes: 150
  PermissionRequirement:
  - "pootopia.rank.spectrum"
  Commands:
  - "asConsole! lp user [playerName] promote promote"
  - "asConsole! cmi broadcast [playerDisplayName] &7has ranked up to &cS&6p&ee&ac&bt&9r&5u&dm&7 which is the final rank!"
  - "asConsole! cmi sound ui_toast_challenge_complete -all"
  StatsRequirements:
  - "PlayTime:1800000"

```

---

**8.0.19.0** 

**Spigot** 

**1.13.1**

**Comment by RegencySolid** [comment]
@Zrips Any update on this? seems like it would be looked at being one of the bigger features of the plugin.

**Comment by Zrips** [comment]
More information will be needed. Like what you have set for 
```
Ranks:
  AutoRankUp:
    # Defines how often in seconds plugin will check for possible player rankups
    # Set it to 0 or less to disable auto rankup checks
    Delay: 60
    # EXPERIMENTAL. When set to true, player rankup checks will be done in async mode
    # In case of errors related to this feature being turned on, turn it off and report issue with error log to github
    Async: false
```
Will close this one, if issue still a thing, reopen this ticked or make new one.
