### ISSUE TITLE
/home and /back teleports with rounded y-coordinate

### ISSUE THREAD

**Issue by kikelkik** [Zrips/CMI#9216]
### Description of Issue

When teleporting with `/home` or `/back`, the destination coordinates are as follows:
* x: exactly as set (e.g. 123.5483)
* y: rounded to integer number (e.g. 64), even if the location was set to 64.5000
* z: exactly as set (e.g. 123.5483)

We expect the y coordinate to be as set, consistent to x and z.

### Version Information

```shell
CMI version 9.7.4.7

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
```

### Errors

- no errors

### Relevant Config Sections

```yaml
Optimizations:
  Teleport:
    SafeLocationDownThenUp: true
    Invulnerability: 5
    ToSpawnBefore: false
    SwitchPlaces: true
    CurrentLoc:
      tpa: true
      tpahere: true
    JumpDefault: 50
    Tpa:
      Time: 60
accepted
      Warmup: 0
      Move: true
      Block: 120
      MaxDistance: 0
    TpaHere:
      MaxDistance: 0
    Tp:
      Bypass: 15
    DenyConfirm: true
    BlackListedItems:
      Enabled: false
      EnabledFor:
        tp: false
        tpa: false
        tpahere: false
        warp: false
        home: false
        spawn: false
      List:
      - Diamond
      - DiamondBlock
      - DiamondOre
      - ironore:5
    BackMinDistance: 0
    BackWithWE: false
    BackBlackList:
    - none
```

### Agreements

- [X] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
