### ISSUE TITLE
Bug with placeholders & AFK module

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#9230]
### Description of Issue

Hello,
I use placeholder with placeholder in the AFK module.
I've set the `%cmi_user_afk_for%` placeholder in this module, and the placeholders is doesn't parsed in the new version.

But in the previous version **(9.7.6.7)**, it's work good.

### Version Information

```shell
CMI: 9.7.6.8 Unknown  MySQL
CMILib: 1.5.1.5 
Server: Leaf 1.21.1-R0.1-SNAPSHOT-
CMI economy: Activée Vault: 1.7.3-CMI CMI Chat: Désactivée 
Modules -> 36 enabled 31 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, elytraBoost, elytraLaunch, serverLinks, bossBarCompass, chatBubble, votifier, headDrop, spawnerCharge, namePlates, homeInteractions, hpBossBar, anvilRenameColor, spawners, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, teleportWith, disabledEnchants, worldLimitsElytra, worldLimits, ranks, sitAnimation, silentChest, totemBehavior
```

### Relevant Config Sections

```yaml
AutoAfkCmds:
  - asConsole! cmi sound block_note_block_harp -p:2 -v:0.3 [playerName] -s
  - perm:cmi.command.afk.kickbypass@! msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu
    es désormais {#E6D545}AFK{#CCCCCC}, tu seras envoyé au {#E6D545}Lobby {#CCCCCC}dans
    {#E6D545}10min{#CCCCCC}.
  - perm:cmi.command.afk.kickbypass! msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu
    es désormais {#E6D545}AFK{#CCCCCC}.
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - asConsole! cmi sound block_note_block_harp -p:2 -v:0.3 [playerName] -s
  - perm:cmi.command.afk.kickbypass@! msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu
    es désormais {#E6D545}AFK{#CCCCCC}, tu seras envoyé au {#E6D545}Lobby {#CCCCCC}dans
    {#E6D545}10min{#CCCCCC}.
  - perm:cmi.command.afk.kickbypass! msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu
    es désormais {#E6D545}AFK{#CCCCCC}.
  LeaveCmds:
    # Defines commands to be performed when player leaves afk mode after he entered it manually
    Manual:
    - msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu es de {#E6D545}retour{#CCCCCC}
      après {#E6D545}%cmi_user_afk_for%{#CCCCCC}, bon jeu !
    - asConsole! cmi sound block_note_block_harp -p:2 -v:0.3 [playerName] -s
    # Defines commands to be performed when player leaves afk mode after he entered it automatically
    Auto:
    - msg! [playerName] {#FFC520}&lH &8» {#CCCCCC}Tu es de {#E6D545}retour{#CCCCCC}
      après {#E6D545}%cmi_user_afk_for%{#CCCCCC}, bon jeu !
    - asConsole! cmi sound block_note_block_harp -p:2 -v:0.3 [playerName] -s
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
