### ISSUE TITLE
Global chat work in jail

### ISSUE THREAD

**Issue by PystoyPlayer** [Zrips/CMI#9231]
### Description of Issue

[Video](https://cln.sh/3WqGJZ53)
Jailed users can still chat in global

### Version Information

```shell
[21:21:40 INFO]: --------------------------------------------------
[21:21:40 INFO]: Версия плагина CMI: 9.7.6.10 BungeeCord CMIB  SqLite
[21:21:40 INFO]: CMILib: 1.5.1.5 
[21:21:40 INFO]: Версия сервера: Purpur(2062) 1.20.1-R0.1-SNAPSHOT-
[21:21:40 INFO]: CMI Экономика: Enabled Версия Vault: 1.7.3-b131(CMIEInjector)CMI Чат: Enabled 
[21:21:40 INFO]: Модули -> 62 включено 5 отключено: tablist, ranks, votifier, skin, elytraBoost
[21:21:40 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Jail:
  # Defines in milliseconds how often to check if player leaves jail area
  # Bigger numbers can help slightly lower server load
  CheckInterval: 500
  # Defines default jail time when time is not povided with command
  DefaultTime: 300
  # Chat range in blocks while player is in jail
  # Set to 0 to allow talking
  # set to -1 to prevent talking in general while jailed
  ChatRange: 15

Chat:
  Ranged:
    # Defines range of regular messages to travel
    # Set to -1 to disable range restriction
    General: 100
    # Defines range of shout messages to travel
    # Shout messages should start with ! and player should have cmi.chat.shout permission
    # GeneralRange should be enabled
    # set to 0 to shout across all worlds, -1 to disable
    Shout: 0
    # Defines cost for each shout message
    ShoutCost: 0
    # List of message range limits
    # Player count fallowed by range
    # Player amount defines from how many we should use this range
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by PystoyPlayer** [comment]
fixed with
```
  Commands:
    # Commands to be performed when player gets jailed
    OnJail:
    - 'lp user %player_name% permission set cmi.chat.shout false'
    # Commands to be performed when player gets unjailed
    OnUnJail:
    - 'lp user %player_name% permission unset cmi.chat.shout'
```
