### ISSUE TITLE
Condense giving incorrect items

### ISSUE THREAD

**Issue by DarrienZ** [Zrips/CMI#9237]
### Description of Issue

 I don't know why, when I use /condense ironingot, it keeps giving me an ItemsAdder custom block.

### Version Information

```shell
CMI: 9.7.6.11 Velocity CMIB
CMILib: 1.5.1.6
SqLite-> 9.7.6.10 
Server: Fufferfish(19) 1.21-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI 
CMI Chat: Enabled Modules--> 64 enabled 3 disabled: tablist, votifter, cmiPlagtime
```

### Errors

```shell
No error
```

### Relevant Config Sections

```yaml
endium_block:
enabled: true
permission: cupendium
display_name: SaBlock of Endium
resource:
generate: true
material: PURPLE_CONCRETE
textures:
- minerals/blocks/endium_block.png specific_properties:
block:
placed_model:
type: REAL_NOTE
break_particles: BLOCK
hardness: 50
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
