### ISSUE TITLE
Unknown CMI command source (FeedbackForwardingSender)

### ISSUE THREAD

**Issue by manul694** [Zrips/CMI#9256]
### Description of Issue

CMI don't work with my autodonate plugin

### Version Information

```shell
9.7.6.2
```

### Errors

```shell
Unknown CMI command source (FeedbackForwardingSender) give rxuzzze89 spawner:cow 1
```

### Relevant Config Sections

```yaml
# By default we will not allow Rcon type commands, if you have your server properly setup to accept remote console commands safely and you have a need then you can enable it
AllowRconCommands: true
# When enabled Rcon feedback message will not include color codes for cleaner display
CleanRconCommands: false
```

### Relevant Plugins

1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
