### ISSUE TITLE
WarmUp section

### ISSUE THREAD

**Issue by daveq96** [Zrips/CMI#9257]
### Description of Issue

Using CMI Warmup option in config doesn't show any message or title.
I created cooldowns to commands like spawn, warp etc. for 5 secs but when I use them, nothing appears but after 5s im getting teleported normally. Even adding "tpaWarmup" doesn't show any message, only showing particles. I want the same message like using tpa command, because when i use the tpa command it shows normally the message (Warmups/DontMove) about dont move and seconds.

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.7.2 Velocity CMIB  SqLite
CMILib: 1.5.2.0 
Serwer: Purpur(2324) 1.21.1-R0.1-SNAPSHOT-
CMI ekonomia: Włączone Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Włączone 
Moduły -> 66 aktywne 1 nieaktywne: votifier
--------------------------------------------------
```

### Relevant Config Sections

```yaml
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  BossBarInfo:
    Enabled: false
    Color: blue
    # Options: 1, 6, 10, 12, 20
    Segments: '1'
  List:
  - cmi warp :5:true:tpaWarmup
  - cmi home :5:true:tpaWarmup
  - cmi spawn:5:true:tpaWarmup`

Messages:

    DontMove: '!title!&c&lᴛᴇʟᴇᴘᴏʀᴛᴀᴄᴊᴀ!subtitle!&7Teleportacja nastąpi za: &f[time]
      sekund'`
```

### Relevant Plugins

Vault: 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
