### ISSUE TITLE
Stop spawner dropping

### ISSUE THREAD

**Issue by lDoomerl** [Zrips/CMI#9264]
### Description of Issue

The option doesn't work properly. I set `After: 1` in cfg so it's will be `1` for common player, and then I give perm `cmi.dropspawner.stopafter.5` to another LP group so they can get 5 spawners, but they are not. They can dig only 1 or 2(bug?) instead of 5. 

### Version Information

```shell
> cmi version
[17:20:31 INFO]: --------------------------------------------------
[17:20:31 INFO]: Версия плагина CMI: 9.7.7.4 Unknown  SqLite
[17:20:31 INFO]: CMILib: 1.5.2.1
[17:20:31 INFO]: Сервер: Pufferfish(21) 1.21.1-R0.1-SNAPSHOT-
[17:20:31 INFO]: CMI Экономика: Включено Vault: 1.7.3-b131(CMIEInjector) CMI Чат: Включено 
[17:20:31 INFO]: Модули -> 51 включено и 16 выключено: customMessages, tablist, armorstand, moneyCheque, skin, noTarget, paintingEditor, rideAnimation, bossBarCompass, deathMessages, disabledEnchants, ranks, playerCombat, votifier, headDrop, sitAnimation
[17:20:31 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors in console.
```

### Relevant Config Sections

```yaml
Spawners:
  # If you experiencing issues with spawner handling, set this to true to avoid any spawner manipulations from CMI side
  # This will disable features like, spawner placement, spawner drops, spawner charges and so on
  FullDisable: false
  Break:
    # ATTENTION! cmi.dropspawner will be required to get spawner dropping for the player
    # Enable or disable spawner handler for spawner break
    # If enabled player will get spawner if using silktouch pickaxe and have cmi.dropspawner permission node
    # If player has cmi.dropspawner.nosilk permission node, player is not required to use silk touch pickaxe to get droped spawner
    Enabled: true
    # If set to true, player will need to have particular permission node to break and get particular spawner.
    # In example: player should have cmi.dropspawner.pig to break pig spawner and get it dropped, or cmi.dropspawner.zombie to get zombie spawner
    RequiresExactPermission: false
    # When set to false, exp will not be dropped from broken spawner independent if spawner it self is being dropped
    # When set to true exp will be dropped only if spawner is not
    DropExp: false
    # Minimal silktouch level required to get spawner back
    SilkTouchLevel: 1
    # Number in percentage from 0 up to 100 for a spawner to be dropped when you break one
    BaseDropChance: 100
    StopDropping:
      # Enable or disable spawner dropping stopping after certain amount of spawners being mined
      Enabled: true
      # Number of spawners player is able to actually mine before its drop chance is set to 0
      # This is based on players statistics records of mined spawners in total, this INCLUDES failed drops as well, so adjust acordingly
      # Permission as cmi.dropspawner.stopafter.§c[positivevalue]§c can be used to define limit with permission node instead
      After: 1
      # When enabled drop change will slowly drop down based on previous set value and how many spawners player has mined
      # This will not go lower than 1% of drop chance until previous set value is reached
      Linear: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
