### ISSUE TITLE
Baltop causing crash (yes again)

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#927]
I thought the baltop issue was solved. So I enabled baltop again for players. After about 10 times executions of the command `/Baltop` it caused another crash!

**ERROR**
https://hastebin.com/gotujibedo.md

**CONFIG SECTION:**
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 1.0E8
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - 10 players, names deleted for privacy reasons
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
  Global:
    # Starting amount of money players will have
    StartingAmount: 0.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E8
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: €
    # Placing of currency symbol
    Placing: '[symbol][money]'
```

---

Cmi Version 8.0.19.0

Paper version git-Paper-335 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

CMIEInjector 1.0.2.1
Vault 1.7.1
