### ISSUE TITLE
Unknown CMI command source (FeedbackForwardingSender - FeedbackForwardingSender)

### ISSUE THREAD

**Issue by manul694** [Zrips/CMI#9287]
### Description of Issue

My autodonate plugin is incompatible with the update, which introduced command source whitelisting. Even adding commands to the whitelist doesn’t resolve the issue. Please add an option to completely disable this feature, as it doesn’t enhance security. A hacker could simply use RCON access to get operator privileges and grant items in-game.

### Version Information

```shell
--------------------------------------------------
Версия плагина CMI: 9.7.7.5 Unknown  MySQL-> 9.7.7.8
CMILib: 1.5.2.2
Версия сервера: Purpur(1985) 1.19.4-R0.1-SNAPSHOT-
CMI Экономика: Включено Версия Vault: 1.7.3-b131(CMIEInjector)CMI Чат: Выключено 
Модули -> 62 включено 5 отключено: tablist, ranks, votifier, skin, sitAnimation
--------------------------------------------------
```

### Errors

```shell
[15:08:35 INFO]: Unknown CMI command source (FeedbackForwardingSender - FeedbackForwardingSender) give fynjy1111 spawner:blaze 1
[15:08:38 INFO]: Unknown CMI command source (FeedbackForwardingSender - FeedbackForwardingSender) broadcast Игрок fynjy1111 купил товар "Спавнер блейзов" на нашем сайте. Информация: /donate. Поддержи проект и ты!
```

### Relevant Config Sections

```yaml
AllowRconCommands: true
CustomCommandSender:
- FeedbackForwardingSender
- FeedbackForwardingSender - FeedbackForwardingSender
- EasyPayments
# When enabled Rcon feedback message will not include color codes for cleaner display
CleanRconCommands: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
