### ISSUE TITLE
Portals not working consistently

### ISSUE THREAD

**Issue by Zero-Escape** [Zrips/CMI#9297]
### Description of Issue

Some of my CMI portals do not teleport players consistently. For example, I have a a large area portal at the bottom of a pit, so that when players fall down they get teleported back up. Its seems to be a total guessing game on whether or not a player will be teleported or not when they fall into the portal region.

I saw this issue was also reported by Github post #5774

Some relevant information:
- I use Velocity but in this use case my portal does not cross network, only teleports a few blocks away from portals location
- I use the MyWorlds plugin for multiverse world navigation, but again this use case stays within one area
- I use GeyserMC for bedrock support, but issue affects java players just as much as bedrock
- I have experienced this same issue on a variety of different use cases of CMI portals on various servers

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.6.2 SqLite-> 9.7.7.9
CMILib: 1.5.1.3 -> 1.5.2.2
Server: Paper(130) 1.21-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 64 enabled 2 disabled: ranks, votifier
--------------------------------------------------
```

### Errors

```shell
No errors to report
```

### Relevant Config Sections

```yaml
MiniGames:
  SpleefPitBottom:
    Loc: -117.0:5.0:-53.0:-81.0:15.0:-16.0
    enabled: true
    effect: Dust
    color: 8224125
    showParticles: false
    safeLoc: MiniGames;-98.43;82.0;-51.3;-1.21;1.18
    Tp: MiniGames;-98.51;82.0;-51.14;1.64;6.59
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 300
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
