### ISSUE TITLE
info's hover placeholders not working

### ISSUE THREAD

**Issue by ddtpp** [Zrips/CMI#9316]
### Description of Issue

plugins/CMI/Translations/Locale_EN.yml

row 1769

here is the issue: the hover related to the "/info" command does not support any placeholder, i've made sure it doesn't by asking support to an admin in the official discord server of the plugin. 

### Version Information

```shell
[15:02:27 INFO]: --------------------------------------------------
[15:02:27 INFO]: CMI: 9.7.7.10 SqLite
[15:02:27 INFO]: CMILib: 1.5.2.2 
[15:02:27 INFO]: Server: Paper(130) 1.21-R0.1-SNAPSHOT+
[15:02:27 INFO]: CMI economy: Disabled CMI Chat: Enabled 
[15:02:27 INFO]: Modules -> 66 enabled 1 disabled: votifier
[15:02:27 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
plugins/CMI/Translations/Locale_EN.yml

row 1769

    info:
      feedback:
        uuid: '&eLeft click to paste uuid into chat box'
        ouuid: '&eShift + left click to paste online uuid into chat box'
      newName: '&6[playerName]'
      newBalance: '&7(&e[balance]&7) '
      newDisplayName: '&7Display name: &r[playerDisplayName]'
      newNameHover:
      - '[playerDisplayName]'
      - '[nick]'
      - '[group]'
      - '[title]'
      - '[onlineoffline]'
      - '[playtime]'
      newIp: '&fIP '
      newIpHover:
      - '[ip][country]'
      - '[ping]'
      - '[firstLogin]'
      newNameHoverNick: '&7Nick: &f[nick]'
      newNameHoverGroup: '&7Group: %luckperms_groups%'
      newNameHoverTitle: '&7Prefix: &f[prefix] &7Suffix: &f[suffix]'
      newNameHoverIp: '&7Ip: &f[ip]'
      newNameHoverPing: '&7Ping: &f[ping]'
      newNameHoverCountry: ' &7[country] &f(&2[countryCode]&f) [city]'
      newFirstLogin: '&7First login: &6[firstLogin]'
      newPlaytime: '&7PlayTime: &6[time]'
      newOnline: '[state] for: &6[logoff]'
      newOnlineStateOn: '&2Online'
      newOnlineStateOff: '&7Offline'
      newUUID: '&fUUID '
      newUUIDHover: '&7UUID: &6[UUID]'
      newOUUIDHover: '&7OnlineUUID: &6[OUUID]'
      newTurnedOnColor: '&a'
      newTurnedOffColor: '&7'
      newOp: 'OP '
      newGod: 'God '
      newFly: 'CanFly&6([flying]&6) '
      newFlying: Flying
      newFlyHover: '&7Fly speed: &6[flyspeed]'
      newFlyTemp: '&7Temporary fly: &6[time]'
      newFlyCharge: '&7Flight charge: &6[charge]'
      newElytraFlyHover: '&7Flying with elytra'
      newGodHover: '&7TempGod for: &e[time]'
      newNoDamageHover: '&7No Damage Ticks for: &e[time]'
      newSneaking: Sneaking
      newSprint: Sprinting
      newWalkSpeed: '&7Walk speed: &6[walkspeed]'
      newGameMode: '&fMode: &6[gameMode] '
      newGameModeHover:
      - '[sprint]'
      - '[sneaking]'
      - '[walkspeed]'
      - '[hp]'
      - '[air]'
      - '[hunger]'
      - '[saturation]'
      - '[exp]'
      newHp: '&7HP: &6[hp]&e/&6[maxhp]'
      newAir: '&7Air: &6[leftAir]&e/&6[totalAir]'
      newHunger: '&7Hunger: &6[food]&e/&620'
      newSaturation: '&7Saturation +&6[saturation]&e'
      newExp: '&7Exp: &6[totalexp]&7exp -> &6[currentexp]&e/&6[needexp] &e(&6[level]&7lvl&e)'
      newPos: '&fPos '
      newPosHover: '&6[world] (&e[x]&6:&e[y]&6:&e[z]&6)'
      newAfk: 'AFK '
      newAfkHover: '&6Afk for last: [time]'
      AfkInHover: '&6Afk in: [time]'
      newBed: '&fBed '
      newBedHover: '&6[world] (&e[x]&6:&e[y]&6:&e[z]&6)'
      newDeath: '&fDeath '
      newDeathHover: '&6[world] (&e[x]&6:&e[y]&6:&e[z]&6)'
      newBack: '&fBack '
      newBackHover: '&6[world] (&e[x]&6:&e[y]&6:&e[z]&6)'
      newRespawn: '&fRespawn '
      newRespawnHover: '&6[world] (&e[x]&6:&e[y]&6:&e[z]&6)'
      inv: '&fInv '
      ender: '&fEnder '
      newSee: '◕‿◕ '
      newSeeHover: '&6Can see you'
      newSeeHoverNot: '&2Can''t see you'
      vanished: '(V) '
      vanishedHover: '&6Vanished'
      newBanned: 'Banned '
      newBannedHover:
      - '&7Banned by: &e[name]'
      - '&7Left: &e[left]'
      - '&7For: &e[reason]'
      newMuted: 'Muted '
      newMutedHover:
      - '&7Left: &e[left]'
      - '&7For: &e[reason]'
      newShadowMutedHover: '&4Shadow mute'
      newCuffed: 'Cuffed '
      newJailed: 'Jailed '
      newJailedHover:
      - '&7Jail: &e[jail]'
      - '&7Cell: &e[id]'
      - '&7Left: &e[time]'
      - '&7Reason: &e[reason]'
      newHomes: '&fHomes: &e[count] '
      newMail: '&fMail: &e[count] '
      newWarnings: '&fWarnings: &e[count] '
      newAlert: 'Alert '
      newAlertHover:
      - '&7Left: &e[left]'
      - '&7For: &e[reason]'
      newChatRoom: 'ChatRoom '
      newChatRoomHover:
      - '&7ChatRoom: &e[name]'
      - '&7Users in: &e[count]'
      List:
      - '&e------------- [enableColor]Enabled [disableColor]Disabled&e -------------'
      - '&e| [name][balance][UUID][ip]'
      - '&e| [OP][god][fly][gameMode][afk][see]'
      - '&e| [banned][muted][cuffed][jailed][alert][chatroom]'
      - '&e| [pos][bed][respawn][death][back][ender][inv]'
      - '&e| [homes][mail][warnings]'
      - '&e-----------------------------------------'
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
