### ISSUE TITLE
ChatFilter.yml BlockType: others does not work with cross-server chat

### ISSUE THREAD

**Issue by Dagrond** [Zrips/CMI#9323]
### Description of Issue

When I have set chatfilter with option BlockType: others, the message is blocked only in server the player is currently, but still sends that message to other servers (via cmiV). Works fine with BlockType: all but that is not the case.

### Version Information

```shell
CMI: 9.7.7.12
CMILib: 1.5.2.3
CMI-V 1.0.1.2
Purpur 1.21.1
```

### Relevant Config Sections

```yaml
ChatFilter.yml
    swearing1:
      Enabled: true
      Group: Swearing
      InformConsole: true
      Regex:
      - \bass\b|\basshole
      BlockType: others
      includePrivateMessages: true
      msgToStaff: '&4!&6[playerName] &4is swearing'

Chat.yml
  Bungee:
    Messages: true
    PublicMessages: true
    StaffMessages: true

Player a needs to be on server #1 (without swear bypass perms)
Player b needs to be on server #2 (those 2 servers should have connected chat)

Player a swears, the message is only shown to him on server #1, but still shown to everyone on server #2

I hope I've described it well.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
