### ISSUE TITLE
[Request] AFK Reason for Players

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#933]
if you go AFK and set a Reason for beking afk
/afk OnToilet

it would be nice if the "Announcer" could print out this reason if given

also in the langfile you have this
```
afk:
  'on': '&6AFK'
  'off': '&7Playing'
  left: '&6[playerDisplayName] &eis no longer AFK'
  MayNotRespond: '&ePlayer may not respond, he is AFK'
  MayNotRespondStaff: '&eStaff memeber is AFK and may not respond. Try contacting
    us throw discord'
```
It would be nice if you also could add the AFK Reason placeholdere here so also the player that tries to whisper the other Player can see the reason.

so /afk (reason) would make more sense like **/afk be back in 30 mins.**

If someone whisper the player now. he would see the reason.

currently this is only seeable in afkcheck...
