### ISSUE TITLE
Various bugs in latest version (anvil, combat tag, warmups)

### ISSUE THREAD

**Issue by ErikSzabo** [Zrips/CMI#9340]
### Description of Issue

1. **cmi.anvil.colors permission stopped working after updating to latest CMI/CMILib**
2. Mob combat tag suddenly enabled itself and there isn't any config to disable it (it didn't worked before).
3. Additionally even if you disable BlockedCmds in mob combat tag, it still treats it as enabled
4. Warmup for /cmi spawn and /spawn does not work. (it works for other things as you can see in the config)

### Version Information

```shell
[13:44:13 INFO]: --------------------------------------------------
[13:44:13 INFO]: CMI: 9.7.8.0 SqLite
[13:44:13 INFO]: CMILib: 1.5.2.3
[13:44:13 INFO]: Server: Paper(132) 1.21.1-R0.1-SNAPSHOT+
[13:44:13 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[13:44:13 INFO]: Modules -> 66 enabled 1 disabled: votifier
[13:44:13 INFO]: --------------------------------------------------
```

### Errors

```shell
No erros in console
```

### Relevant Config Sections

```yaml
Warmup config
  List:
  - cmi warp :3:false
  - cmi home :3:false
  - cmi spawn :3:false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
1. There was a mention with one of the updates indicating that from that point to use colors on anvil will need same permission node as it does for itemname command, as this is basically same action, item renaming, so you will need to give appropriate permission node to the players on top of anvil colors, that permission node is just to separate itemname command from anvil renaming. So giving `cmi.colors.itemname.green` permission node will allow usage of &a or {#green} color codes
2. Check combat.yml file, there should be option for Mob combat labeled as "IncludeVictim" which you can enable or disable. When its disable then combat mode will not enable when mob attacks you, only when you attack monsters
3. Will need actual example of your mobs setup here, as it should be ignored if you set it to false at BlockCommands section. Can't reproduce your issue here
4. You have extra space for spawn command, only use that space if you want to add warmup for commands with sub variables, for example "/cmi home myTinyHome" would trigger warmup of 3 seconds, while just doing "/cmi home" would not, in this case you should use 'cmi spawn:3:false' for the spawn command which will trigger warmup independent how many variables you provide which is more correct behavior for that command

**Comment by ErikSzabo** [comment]
Thank you, 1 and 4 now working!

But regarding the mob combat tag, there isn't individual IncludeVictim toggle for just mobs, it is affecting both player and mob combat. BlockCommands is also set to false for mob combat, but it doesn't let me use commands. For now I changed IncludeVictim to false, but that is not ideal for player combat.

Here is the original config I tested with:

```yml
Combat:
  # Defines combat timer to be used in particular features
  Timer: 15
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: false
  # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
  # If set to false then only attacker will be marked for pvp mode
  IncludeVictim: true
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging players
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c⚔[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: false
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: false
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: true
    AllowedCommands:
    - msg
    - r
    - md leave
    - leave
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: false
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: false
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: false
    # When enabled we will include damage from environmental damage into mob combat timer
    # This can include damage from cactus, magma blocks, suffocation, burning, fall damage and similar
    IncludeEnvironment: true
    # When enabled we will show damage numbers in a form of holograms when damaging mobs
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c❤[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pve.godBypass permission node
    noGodDamage: false
    # Informs player that he cant damage mobs while in god mode
    noGodDamageInform: false
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: false
    AllowedCommands: []
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
```
