### ISSUE TITLE
Playtime rewards not given automatically sometimes

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9341]
### Description of Issue

Hello, I have strange question or issue.

My playtime rewards aren't given automatically for some reason.
```yml
apply:
  DisplayName: "&f1d playtime - able to apply as helper"
  AutoClaim: true
  Description:
  - "&2Play at least 1d of /playtime, link"
  - "&2your game acc with /discord, and get"
  - '&2a chance to apply for a helper rank!'
  PayFor: 86400
  Commands:
  - asConsole! lp user [playerName] parent add canapply
 ```

but maybe only sometimes, is there something wrong with it?
![image](https://github.com/user-attachments/assets/bbb7c480-d6e2-4204-904f-8e486f8a5bda)

am I missing some permission for them, or?

### Version Information

```shell
[14:13:43 INFO]: CMI version 9.7.8.0
[14:13:43 INFO]: Powerful server management tool
[14:13:43 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[14:13:43 INFO]: Author: Zrips
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
