### ISSUE TITLE
AFK timer still not automatically kicking people (after recent patch)

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/CMI#9368]
### Description of Issue

Seems like the same issue is still occurring 

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.7.10 SqLite-> 9.7.8.2
CMILib: 1.5.2.2 -> 1.5.2.5
Server: Pufferfish(15) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled 
Modules -> 48 enabled 19 disabled: spawnerProximity, hpBossBar, tablist, armorstand, moneyCheque, portals, holograms, elytraBoost, spawners, dynamicSigns, rideAnimation, elytraLaunch, bossBarCompass, flightCharge, ranks, votifier, sitAnimation, spawnerCharge, vanish
--------------------------------------------------
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
:
  Enabled: true
  TitleMessage: true
  SubTitleMessage: true
  PreventJumping: true
  PreventDamage: true
  CheckInterval: 10
  StopPlayTime: true
  AutoAfkIn: 600
  AutoAfkCmds:
  - cmi sound entity_villager_no %player_name%
  ManualAfkCmds:
  - cmi sound entity_villager_no %player_name%
  LeaveCmds:
    Manual:
    - ''
    Auto:
    - ''
kicked after AutoAfkIn+AutoKickIn seconds
node where bigger value takes priority
  AutoKickIn: 900
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
What do you have set for AutoKickCmds section? Entire file would be best to have best way in debugging why it doesn't work for you. If you have set some sort of kick command under AutoKickCmds section, try testing it by changing it to something different, like 'cmi msg [playerName] You got auto kicked' or anything similar to test out if this gets triggered for you in general. Keep in mind that player with cmi.command.afk.kickbypass will not be kicked out, so make sure that they don't have access to this permission node

**Comment by hotspuraz** [comment]
The `AutoKickIn: 900` setting should work regardless of manual commands I have set, no?

```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: true
  # When enabled shows random subtitle message
  SubTitleMessage: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: true
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 10
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 600
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi sound entity_villager_no %player_name%
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi sound entity_villager_no %player_name%
  LeaveCmds:
    # Defines commands to be performed when player leaves afk mode after he entered it manually
    Manual:
    - ''
    # Defines commands to be performed when player leaves afk mode after he entered it automatically
    Auto:
    - ''
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: 900
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - cmi kick [playerName] &bYou have been kicked for idling more than [time] -s
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # Prevents players from being  pooled around while player is in afk mode
  PreventHook: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: false
  # Disables afk on inventory click
  DisableOnInventoryClick: false
  # Disables afk on item drop
  DisableOnitemDrop: false
  # Disables afk on command usage
  DisableOnCommand: false
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: false
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on camera movement
  DisableOnLookAround: false
  # Disables afk on fishing when you catch fish
  DisableOnFishing: false
  # Disables item pickup while afk
  DisableItemPickup: false
  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: false
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: true
    # Usually responsible for spawning in iron golems
    VillageDefence: true
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false
```

**Comment by hotspuraz** [comment]
Config without the comments:
```
Afk:
  Enabled: true
  TitleMessage: true
  SubTitleMessage: true
  PreventJumping: true
  PreventDamage: true
  CheckInterval: 10
  StopPlayTime: true
  AutoAfkIn: 600
  AutoAfkCmds:
  - cmi sound entity_villager_no %player_name%
  ManualAfkCmds:
  - cmi sound entity_villager_no %player_name%
  LeaveCmds:
    Manual:
    - ''
    Auto:
    - ''
  AutoKickIn: 900
  RepeatingAutoKickInterval: 300
  RepeatKickCommand: false
  AutoKickCmds:
  - cmi kick [playerName] &bYou have been kicked for idling more than [time] -s
  DisabledWorlds:
  - oneTestWorld
  - secondTestWorld
  DisableOnInteract: true
  SmartInteractCheck: true
  AntiAfkMachines: true
  PreventHook: true
  PreventPushing: false
  DisableOnInventoryClick: false
  DisableOnitemDrop: false
  DisableOnCommand: false
  DisableOnPublicChat: true
  DisableOnPrivateChat: false
  DisableOnMove: true
  DisableOnLookAround: false
  DisableOnFishing: false
  DisableItemPickup: false
  PreventMobSpawning:
    Enabled: false
    Natural: false
    Spawners: true
    VillageDefence: true
  DisableExpPickup: false
  ```
