### ISSUE TITLE
Bossbar msg with '-t:-1' argument to create an infinite lasting bossbar doesn't work

### ISSUE THREAD

**Issue by SenorFlamingo** [Zrips/CMI#9375]
### Description of Issue

The specifiek -t:-1 argument doesn't work to create an infinite lasting bossbar on the player's screen. It won't show at all.

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.8.2 Unknown  SqLite
CMILib: 1.5.2.5 
Server: Paper(131) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Ingeschakeld Vault: 1.7.3-CMI CMI Chat: Uitgeschakeld
```

### Relevant Config Sections

In EventCommands.yml:
```
joinServer:
  Enabled: true
  Commands:
  - perm:serverboost.nowactive! cmi bossbarmsg [playerName] -p:100 -a:1 -s:10 -t:99999
    -c:purple -n:serverboost {#d766ff}&l&o☀ SERVERBOOST ACTIEF ☀
```
The above example works for a long lasting bossbar, but this doesnt:
```
joinServer:
  Enabled: true
  Commands:
  - perm:serverboost.nowactive! cmi bossbarmsg [playerName] -p:100 -a:1 -s:10 -t:-1
    -c:purple -n:serverboost {#d766ff}&l&o☀ SERVERBOOST ACTIEF ☀
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
