### ISSUE TITLE
mobheads

### ISSUE THREAD

**Issue by surrreal-killer** [Zrips/CMI#9379]
### Description of Issue

mobheads doesnt seem to be working, i set all the values to 100% chance and still no heads are dropping when i kill stuff. tried friendly and unfriendly mobs.

### Version Information

```shell
--------------------------------------------------
12/28 12:42:13 PM [Info] CMI: 9.7.8.2 SqLite
12/28 12:42:13 PM [Info] [17:42:13 INFO]: CMILib: 1.5.2.4 -> 1.5.2.5
12/28 12:42:13 PM [Info] [17:42:13 INFO]: Server: Paper(4) 1.21.4-R0.1-SNAPSHOT+
12/28 12:42:13 PM [Info] [17:42:13 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
12/28 12:42:13 PM [Info] [17:42:13 INFO]: Modules -> 66 enabled 1 disabled: votifier
12/28 12:42:13 PM [Info] [17:42:13 INFO]: --------------------------------------------------
```

### Errors

```shell
no errors in console
```

### Relevant Config Sections

```yaml
just an exert :

LootMobBonus:
  Enabled: false
  Lvl1: 5.0
  Lvl2: 15.0
  Lvl3: 30.0
# Defines if you want to use default head lore which will be used in case head doesnt have defined lore
useDefaultHeadLore: true
# Default lore used when head doesnt have defined head lore set
defaultHeadLore:
- '&7Killed by &6[playerName]'
PlayerHead:
  # Defines if you want to use player head lore
  UseLore: true
  # Lore used for player head drops
  # Global variables can be used for simple identification who was killed and who killed player
  # Aditionally placeholders can be used too, but we will use victim as source for their translation if placeholder requires source player
  Lore:
  - '&7Killed by &6[playerName]'
HeadHandling:
  Maintain:
    # Defines if we should maintain heads custom name when head is placed and then broken
    # Vanilla minecraft will remove any custom information about head when you place it, this can help out to maintain data
    Name: false
    Lore: false
    Enchants: false
# Custom heads of every entity
# You can have as many custom heads as you want
# Format is [dropChance]:[texture]
# Drop chance is for that particular head
# While you have separate global drop chance for particular entity type
# Strongly recommend to have at least one head at 100% as in another case there will be a chance to not get a head even if player should
# You can find custom textures online
# If you have more then one possible head for one entity type, then it will be randomized
# Custom mob head can be defined by using format like [chance]:[HeadName]:c-[options]:lore{"[lore]"}:[texture]
# More information and some better examples can be found at www.zrips.net/cmi/extra/custom-mob-heads/
# Optionally you can shorten out texture string by removing first part which is eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv which by itself will be added automatically if not present
EntityHeads:
  elder_guardian:
    DropChance: 100
    LowerWithEachDrop: 100
    Heads:
    - 100:Default:MWM3OTc0ODJhMTRiZmNiODc3MjU3Y2IyY2ZmMWI2ZTZhOGI4NDEzMzM2ZmZiNGMyOWE2MTM5Mjc4YjQzNmIifX19
  wither_skeleton:
    DropChance: 100
    LowerWithEachDrop: 100
    Heads:
    - 100:Default:Nzk1M2I2YzY4NDQ4ZTdlNmI2YmY4ZmIyNzNkNzIwM2FjZDhlMWJlMTllODE0ODFlYWQ1MWY0NWRlNTlhOCJ9fX0=
    - 100:Default:ZjVlYzk2NDY0NWE4ZWZhYzc2YmUyZjE2MGQ3Yzk5NTYzNjJmMzJiNjUxNzM5MGM1OWMzMDg1MDM0ZjA1MGNmZiJ9fX0=
    - 100:Default:NDk2YmM4ZWJkNGUxM2Y0OTZkOGQ3NGM1NjVkZDU2ZTk5YTRhZjJlMmVhN2EyN2E5NmMxYWJkMjg0MTg0YiJ9fX0=
  stray:
    DropChance: 100
    LowerWithEachDrop: 100
    Heads:
    - 100:Default:NzhkZGY3NmU1NTVkZDVjNGFhOGEwYTVmYzU4NDUyMGNkNjNkNDg5YzI1M2RlOTY5ZjdmMjJmODVhOWEyZDU2In19fQ==
  husk:
    DropChance: 100
    LowerWithEachDrop: 100
    Heads:
    - 100:Default:Nzc3MDY4MWQxYTI1NWZiNGY3NTQ3OTNhYTA1NWIyMjA0NDFjZGFiOWUxMTQxZGZhNTIzN2I0OTkzMWQ5YjkxYyJ9fX0=
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
