### ISSUE TITLE
`%cmi_user_rt_cooldown%` doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#9396]
### Description of Issue

Hello,
The placeholder `%cmi_user_rt_cooldown%` doesn't work, and i don't understand why :/

Also, do you think it's possible to add a different cooldown per world and a new placeholder with this? For example: `%cmi_user_rt_<world>_cooldown%`.

### Version Information

```shell
CMI: 9.7.8.3 Velocity CMIB MySQL
CMILib: 1.5.2.6
Server: Leaf 1.21.3-R0.1-SNAPSHOT-
CMI economy: Désactivée Vault: 2.9.0 CMI Chat: Désactivée
Modules -> 38 enabled 29 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, elytraBoost, elytraLaunch, serverLinks, chatBubble, votifier, headDrop, decoratedpot, spawnerCharge, vanish, namePlates, homeInteractions, hpBossBar, anvilRenameColor, spawners, dynamicSigns, playerChatTag, disabledEnchants, worldLimitsElytra, worldLimits, ranks, firstJoinMessages, silentChest, totemBehavior
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
RandomTeleportation:
  # How long force player to wait before using command again.
  Cooldown: 3
  # How many times to try find correct location for teleportation.
  # Keep it at low number, as player always can try again after delay
  MaxTries: 60
  # List of biomes to exclude from random teleportation
  ExcludedBiomes:
  - ocean
  - deep_ocean
  - deep_cold_ocean
  - deep_lukewarm_ocean
  - deep_frozen_ocean
  - the_end
  - the_void
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will no longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: false
  Worlds:
    # World name to use this feature. Add another one with appropriate name to enable random teleportation
    Recolte:
      Enabled: true
      # Amount of times we should try to find valid location. This is mostly directly correlates with amount of chunks we will check
      # If set to 0 we will use default MaxTries set at the top of file
      MaxTries: 0
      Range:
        # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 blocks between defined center location
        # For example having centerX at 2000 and centerZ at 3000 while MaxRange is set to 1500 we will teleport player between x:500;z:1500 and x:3500;z:4500 coordinates
        Max: 4000
        # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
        Min: 100
      Center:
        X: 0
        Z: 0
      # Shape of area player can be teleported into. If your map is square shaped then keep this at false
      Circle: false
      # With this option we will only attempt to teleport player on highest block and ignore any cave teleportations
      # Exception when you have Ignore.Leaves set to true which will attempt to place player under the tree leaves if there is any empty space
      SurfaceOnly: true
      # When enabled player will be able to random teleport at specied world while being in another one
      FromAnotherWorld: true
      # When enabled player will be required to have (cmi.randomteleport.recolte) permission node to random teleport inside this world
      RequireWorldPermission: false
      YLimits:
        # Location detection limitations on Y axis. If you want to minimize teleportations underground then you can set this value to 63
        # Higher limitations might increase time needed to find valid one
        Min: 63
        Max: 320
      Ignore:
        Water: true
        Lava: true
        Leaves: true
        PowderSnow: true
        # List of floor materials we should ignore when random teleporting
        Materials: []
        # List of biomes we should ignore when random teleporting
        # Keeping it empty will include all of them
        # If this is empty and ExcludedBiomes contains set biomes then we will use it
        Biomes: []
      # List of biomes we should look for when random teleporting
      # If this contains biome names then we will ignore Ignore.Biomes section
      PreferredBiomes: []
    Nether:
      Enabled: true
      MaxTries: 0
      Range:
        Max: 2000
        Min: 100
      Center:
        X: 0
        Z: 0
      Circle: false
      SurfaceOnly: true
      FromAnotherWorld: true
      RequireWorldPermission: false
      YLimits:
        Min: 37
        Max: 119
      Ignore:
        Water: false
        Lava: true
        Leaves: false
        PowderSnow: false
        Materials:
        - BEDROCK
        Biomes: []
      PreferredBiomes: []
    End:
      Enabled: true
      MaxTries: 0
      Range:
        Max: 2000
        Min: 1000
      Center:
        X: 0
        Z: 0
      Circle: false
      SurfaceOnly: true
      FromAnotherWorld: true
      RequireWorldPermission: false
      YLimits:
        Min: 47
        Max: 72
      Ignore:
        Water: false
        Lava: false
        Leaves: false
        PowderSnow: false
        Materials:
        - chorus_block
        Biomes: []
      PreferredBiomes:
      - END_HIGHLANDS
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
