### ISSUE TITLE
FirstSpawn Not available

### ISSUE THREAD

**Issue by 1821698021** [Zrips/CMI#9401]
### Description of Issue

I wrote the map and coordinates on FirstSpawn so that players who enter the server for the first time won't be born here

### Version Information

```shell
cmi 9.7.8.3
cmilib 1.5.2.6
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
FirstSpawn:
    Use: true
    World: spawn
    X: 687.4642731141707
    Y: 222.0
    Z: -170.47340387002046
    Pitch: 1.5000033
    Yaw: 0.75210553
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
