### ISSUE TITLE
cmi ranks 

### ISSUE THREAD

**Issue by Blurry1980** [Zrips/CMI#9402]
Hello, I need some advice. I have set up ranks in the ranks.yml file and I need the player to automatically progress to the next rank after completing certain tasks. In LuckPerms, I have the following groups: default, explorer, adventurer, chronicler, protector, warrior, guardian, resurrected, hero, legend. However, the automatic rank-up isn't working, and it doesn't assign the group in LuckPerms.

```
Newbie:
  Enabled: true
  DisplayName: '&7Cestovatel'
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - pruzkumnik
  StatsRequirements:
  - PlayTime:25000
  - travel:4000
  Commands:
  - broadcast! &7[playerDisplayName] &eleveled up to Průzkumník rank!
  - lp user [playerName] parent remove default
  - lp user [playerName] parent add pruzkumnik
  MoneyCost: 0
  ExpCost: 70
Pruzkumnik:
  Enabled: true
  DisplayName: '&9Průzkumník'
  AutoRankup: true
  RankupConfirmation: false
  Votes: 40
  NextRanks:
  - dobrodruh
  MoneyCost: 1500
  ExpCost: 90
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Dobrodruh rank!
  - lp user [playerName] parent remove pruzkumnik
  - lp user [playerName] parent add dobrodruh
  StatsRequirements:
  - travel:12000
  - MonsterKills:zombie:300
  - MonsterKills:slime:40
  - MonsterKills:wolf:80
Dobrodruh:
  Enabled: true
  DisplayName: '&aDobrodruh'
  DefaultRank: false
  AutoRankup: true
  RankupConfirmation: false
  NextRanks:
  - kronikar
  MoneyCost: 2500
  ExpCost: 120
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Kronikář rank!
  - lp user [playerName] parent remove dobrodruh
  - lp user [playerName] parent add kronikar
  StatsRequirements:
  - travel:15000
  - blocksmined:3000
  - blocksmined:diamond_ore:60
  - MonsterKills:1500
Kronikar:
  Enabled: true
  DisplayName: '&2Kronikář'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 3000
  ExpCost: 200
  NextRanks:
  - ochrance
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Ochránce rank!
  - lp user [playerName] parent remove kronikar
  - lp user [playerName] parent add ochrance
  StatsRequirements:
  - travel:20000
  - MonsterKills:zombie:600
  - MonsterKills:slime:100
Ochrance:
  Enabled: true
  DisplayName: '&4Ochránce'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 4000
  ExpCost: 300
  NextRanks:
  - valecnik
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Válečník rank!
  - lp user [playerName] parent remove ochrance
  - lp user [playerName] parent add valecnik
  StatsRequirements:
  - Swim:14000
  - SneakTime:3800
  - MonsterKills:3500
Valecnik:
  Enabled: true
  DisplayName: '&3Válečník'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 5000
  ExpCost: 400
  NextRanks:
  - strazce
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Strážce rank!
  - lp user [playerName] parent remove valecnik
  - lp user [playerName] parent add strazce
  StatsRequirements:
  - walk:25000
  - HorseTravel:4000
  - ItemsUsed:15000
  - PlayerKills:15
Strazce:
  Enabled: true
  DisplayName: '&dStrážce'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 6000
  ExpCost: 550
  NextRanks:
  - vzkriseny
  Commands:
  - broadcast! &6[playerDisplayName] &eleveled up to Vzkříšený rank!
  - lp user [playerName] parent remove strazce
  - lp user [playerName] parent add vzkriseny
  StatsRequirements:
  - blocksmined:10000
  - MonsterKills:6000
  - ItemsUsed:30000
Vzkriseny:
  Enabled: true
  DisplayName: '&5Vzkříšený'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 7500
  ExpCost: 700
  NextRanks:
  - hrdina
  Commands:
  - broadcast! &4[playerDisplayName] &eleveled up to Hrdina rank!
  - lp user [playerName] parent remove vzkriseny
  - lp user [playerName] parent add hrdina
  StatsRequirements:
  - blocksmined:15000
  - MonsterKills:8000
  - ItemsUsed:40000
Hrdina:
  Enabled: true
  DisplayName: '&6Hrdina'
  AutoRankup: true
  RankupConfirmation: false
  MoneyCost: 10000
  ExpCost: 900
  NextRanks:
  - legenda
  Commands:
  - broadcast! &2[playerDisplayName] &eleveled up to Legenda rank!
  - lp user [playerName] parent remove hrdina
  - lp user [playerName] parent add legenda
  StatsRequirements:
  - blocksmined:30000
  - MonsterKills:15000
  - ItemsUsed:30000
Legenda:
  Enabled: true
  DisplayName: '&1Legenda'
  AutoRankup: true
  NextRanks: []
  StatsRequirements:
  - walk:100000
  - MonsterKills:25000
  - blocksmined:60000
  Commands:
  - money give [playerName] 100000
```

**Comment by CloudeLecaw** [comment]
can you paste this to pastebin or simliar or post it as Code?
you might see your format got crazzy corrupted by just pasting it.

**Comment by Zrips** [comment]
What do you have as an output for **/ranklist** and next rank information when you do something like **/cmi rankinfo Pruzkumnik** for the next rank in line. All fields should be green for it to rankup and there is default 60 second delay between rankup rechecks to lower load and avoid constant checking of rankup when it should only happen once in a while

**Comment by Blurry1980** [comment]
> What do you have as an output for **/ranklist** and next rank information when you do something like **/cmi rankinfo Pruzkumnik** for the next rank in line. All fields should be green for it to rankup and there is default 60 second delay between rankup rechecks to lower load and avoid constant checking of rankup when it should only happen once in a while

I redid it a little bit. I have made a track in Luckperms and added groups from default to highest. And it still doesn't work to automatically move the player to the next rank after the conditions are met.

```
default:
  Enabled: true
  DisplayName: '&7&l[Cestovatel]'
  DefaultRank: true
  AutoRankup: true
  StatsRequirements:
  - PlayTime:28800
  - walk:16000
  NextRanks:
  - pruzkumnik
pruzkumnik:
  Enabled: true
  DisplayName: '&9&l[Průzkumník]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:57600
  - travel:40000
  - chestOpen:3000
  - blocksmined:diamond_ore:80
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &6Průzkumník&a!
  - eco give [playerName] 600
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] diamond 15
  - lp user %player_name% promote
  NextRanks:
  - dobrodruh
dobrodruh:
  Enabled: true
  DisplayName: '&a&l[Dobrodruh]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:86400
  - Swim:15000
  - Sneak:7000
  - blocksmined:20000
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &eDobrodruh&a!
  - eco give [playerName] 1000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] diamond_sword 1
  - lp user %player_name% promote
  NextRanks:
  - kronikar
kronikar:
  Enabled: true
  DisplayName: '&2&l[Kronikář]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:129600
  - Sneak:7000
  - ItemCrafts:2500
  - ItemEnchanted:3000
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &2Kronikář&a!
  - eco give [playerName] 2000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] enchanted_book 4 {StoredEnchantments:[{id:"mending",lvl:1}]}
  - lp user %player_name% promote
  NextRanks:
  - ochrance
ochrance:
  Enabled: true
  DisplayName: '&4&l[Ochránce]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:172800
  - MonsterKills:20000
  - MonsterKills:pillager:300
  - MonsterKills:ravager:80
  - MonsterKills:vex:50
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &bOchránce&a!
  - eco give [playerName] 2500
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] golden_apple 10
  - cmi give [playerName] diamond_sword 2
  - lp user %player_name% promote
  NextRanks:
  - valecnik
valecnik:
  Enabled: true
  DisplayName: '&3&l[Válečník]'
  AutoRankup: true
  MaxHomes: 4
  StatsRequirements:
  - PlayTime:216000
  - MonsterKills:creeper:600
  - MonsterKills:skeleton:400
  - MonsterKills:stray:300
  - MonsterKills:witch:150
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &3Válečník&a!
  - eco give [playerName] 3000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] diamond_helmet 1
  - cmi give [playerName] diamond_chestplate 1
  - lp user %player_name% promote
  NextRanks:
  - strazce
strazce:
  Enabled: true
  DisplayName: '&d&l[Strážce]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:259200
  - MonsterKills:ghast:700
  - MonsterKills:blaze:500
  - MonsterKills:hoglin:300
  - MonsterKills:wither:150
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &2Strážce&a!
  - eco give [playerName] 5000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] enchanted_golden_apple 4
  - lp user %player_name% promote
  NextRanks:
  - vzkriseny
vzkriseny:
  Enabled: true
  DisplayName: '&5&l[Vzkříšený]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:302400
  - PlayerKills:25
  - DamageTaken:1500
  - Deaths:200
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &dVzkříšený&a!
  - eco give [playerName] 10000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] totem_of_undying 10
  - lp user %player_name% promote
  NextRanks:
  - hrdina
hrdina:
  Enabled: true
  DisplayName: '&6&l[Hrdina]'
  AutoRankup: true
  StatsRequirements:
  - PlayTime:345600
  - MonsterKills:phantom:500
  - MonsterKills:shulker:300
  - MonsterKills:silverfish:150
  - MonsterKills:ender_dragon:10
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &9Hrdina&a!
  - eco give [playerName] 15000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] netherite_sword 2
  - lp user %player_name% promote
  NextRanks:
  - legenda
legenda:
  Enabled: true
  DisplayName: '&1&l[Legenda]'
  AutoRankup: true
  Commands:
  - msg! [playerName] &aGratulujeme! Nyní jsi získal hodnost &8Legenda&a!
  - eco give [playerName] 20000
  - cmi effect [playerName] minecraft:firework_rocket 1
  - cmi give [playerName] nether_star 30
  NextRanks: []

```
