### ISSUE TITLE
Chat ignoring settings with ClickHoverMessages

### ISSUE THREAD

**Issue by BlindMag** [Zrips/CMI#9410]
### Description of Issue

Chat is sending regardless of disabling it on all servers when Bungee is set to true from 1.21.4 to servers 1.20.4. Chat listener is lowest for cmi, highest for chc. It's also not respecting the permission node cmi.command.chat false.
CHC listener is set to high to handle chat and works between the lower server versions.
Disabling the bungee setting in the config does stop chat from sending.

### Version Information

```shell
cmi 9.7.8.3 lib 1.5.2.6
purpur - 1.20.4
```

### Relevant Config Sections

```yaml
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: true
  # When set to true player names from entire bungee network will be included into tab complete
  NamesInTabComplete: true
  # When enabled player can return to previous server when using /back comand instead of being teleported to previous location on that server
  # This only applies if player came to this server without teleporting around
  BackToPreviousServer: false

Chat:
  ModifyChatFormat:
    # Will try to modify chat to display it in defined format
    # If this is disabled and you have 3rd party plugin handling chat messages, consider disabling ClickHoverMessages section too if you notice any problems with chat formatting
    Enabled: false
    # Priority of public message format listener
    # Changed priority will only take effect on full server restart. Possible options: LOWEST, LOW, NORMAL, HIGH, HIGHEST
    # Default: NORMAL
    Priority: lowest
    # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
    # To change default hover over messages seen on sent message, go to your locale file to Chat section
    ClickHoverMessages: false
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.
