### ISSUE TITLE
"Sorry. You can't use that Command in this World!" when adding additional lines to  CustomAlias

### ISSUE THREAD

**Issue by ArZorMC** [Zrips/CMI#9440]
### Description of Issue

Im trying to add some additional funtionallity to the spawn command so I did the following:
In CMI/Settings/Alias.yml i set Spawn to the following:
  spawn:
    Enabled: false
    Tab: false

Then in CMI/CustomAlias/CustomAlias.yml i added the following:
  spawn:
    Cmds:
    - cmi spawn
    - asConsole! cmi effect [playerName] speed 60 -s

When players use the command /spawn they are still teleported and given speed to the command works, but the player is told in chat "Sorry. You can't use that Command in this World!"

### Version Information

```shell
https://github.com/user-attachments/assets/5baca328-9a44-48fa-afcc-7c3fb46dfa56
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
spawn:
    Cmds:
    - cmi spawn
    - asConsole! cmi effect [playerName] speed 60 -s
    - asConsole! cmi bossbarmsg [playerName] -cancel:ResourceOverworld
    - asConsole! cmi bossbarmsg [playerName] -cancel:ResourceNether
    - asConsole! cmi bossbarmsg [playerName] -cancel:ResourceEnd
    - asConsole! cmi bossbarmsg [playerName] -cancel:Arena
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
