### ISSUE TITLE
CMI Import will not save essentials imported balances

### ISSUE THREAD

**Issue by MihneaShaff** [Zrips/CMI#9458]
### Description of Issue

Hello, i have a weird issue regarding balances

cmi importfrom essentials balance does temporarily set the balances to the according values, though it goes away on a restart for the players that haven't joined since cmi was added. cmi importoldusers was ran and on a second run it adds 0 new users. i have tried running with:
1. cmi-vault
2. cmi-vault & cmieconinjector
3. cmieconinjector

if i try to manually set a balance to a player that didn't join since cmi was added, it will aswell get reset on a server restart
economy is enabled and of course, i used cmi saveall after importing.

No console errors. Here's how essentials player flatfile database looks like. The last Essentials version used was latest (1.21.0)
```
teleportenabled: true
teleportauto: false
godmode: false
muted: false
jailed: false
ip-address: redacted
afk: false
socialspy: false
npc: false
powertoolsenabled: true
accepting-pay: true
baltop-exempt: false
timestamps:
  lastteleport: 0
  lastheal: 0
  mute: 0
  jail: 0
  onlinejail: 0
  logout: 1719673502563
  login: 1719673197259
money: '5000.0'
last-account-name: redacted
lastlocation:
  world: a9fbd6a3-2381-417f-9a48-39978f02120b
  world-name: world
  x: 0.0
  y: 122.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
logoutlocation:
  world: fa338e7c-fcb1-44a1-933b-bd0425914c6a
  world-name: spawn
  x: 101.9731
  y: -27.0
  z: 96.97581
  yaw: 11.465225219726562
  pitch: 10.644302368164062
```
Everything else converted successfully, only problem being the money.

### Version Information

```shell
[05:13:46 INFO]: --------------------------------------------------
[05:13:46 INFO]: CMI: 9.7.9.2 SqLite
[05:13:46 INFO]: CMILib: 1.5.2.6 -> 1.5.2.9
[05:13:46 INFO]: Server: Pufferfish(27) 1.21.3-R0.1-SNAPSHOT+
[05:13:46 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[05:13:46 INFO]: Modules -> 60 enabled 7 disabled: tablist, armorstand, ranks, playerCombat, votifier, vanish, bossBarCompass
[05:13:46 INFO]: --------------------------------------------------
```

### Errors

```shell

```

### Relevant Config Sections

```yaml

```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
