### ISSUE TITLE
Combat tag not activating when attacking slimes and magma cubes

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#9463]
### Description of Issue

Players who attack slimes and magma cubes are not being put in combat tag mode.  
Other mobs do cause combat tag.

### Version Information

```shell
[09:46:02 INFO]: --------------------------------------------------
[09:46:02 INFO]: CMI plugin version: 9.7.9.2 MySQL
[09:46:02 INFO]: CMILib: 1.5.2.9 
[09:46:02 INFO]: Server: Paper(113) 1.21.4-R0.1-SNAPSHOT+
[09:46:02 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[09:46:02 INFO]: Modules -> 59 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[09:46:02 INFO]: --------------------------------------------------
```

### Errors

```shell
none
```

### Relevant Config Sections

```yaml
:
  # Defines combat timer to be used in particular features
  Timer: 4
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: false
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
    # If set to false then only attacker will be marked for pvp mode
    IncludeVictim: false
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging players
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c⚔[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: false
    AllowedCommands:
    - msg
    - r
    - tell
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: false
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
    IncludeVictim: false
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When enabled we will include damage from environmental damage into mob combat timer
    # This can include damage from cactus, magma blocks, suffocation, burning, fall damage and similar
    IncludeEnvironment: false
    # When enabled we will show damage numbers in a form of holograms when damaging mobs
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c❤[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pve.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage mobs while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - fly
    - cmi fly
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
