### ISSUE TITLE
[Request] Placeholder for AFK in Config to design it in Tab:

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#948]
When Looking at the Tablist it would be nice if we had a placeholder that works together with AFK
When Player is AFK the placeholder is Activ - If not AFK the Placeholder would have no effect (not acitv or simply "empty")

Example:
**Setup for config.yml**
```
#this placeholder can be used with [PlayerAFK] in tablist
PlayerAFKPlaceholder: '&7&o'
```

```
**TabConfigfor config.yml**
  GeneralFormat:
    PlayerName: '[prefix][PlayerAFK][playerDisplayName]'
    Header:
      '1':
      - '&f------------------------------------'
      - '&7Welcome to the Server'
      - '&7Online &f%server_online%&7/&f%server_max_players%'
      - '&f------------------------------------'
    Footer:
      '1':
      - '&f------------------------------------'
      - '&7%player_world% &f%player_x%:&7%player_y%:&f%player_z%'
      - '&7Money: &a%cmi_user_balance%$ &7Time: &6%server_time_HH:mm%'
      - '&f------------------------------------'#
```

What would happen in this example?:
If Player wents AFK the PlayerAFK placeholder is activ and sets the Colorcode &7&l
infront of the playerDisplayName so Show it in gray italic
When the Player is not AFK then his playerName is shown normal becuase the Placeholder is not active (or empty) then.

The Setup of the AFK Placeholder also could be a word like AFK listet behind the playername if he is AFK...This placeholder would give multiple ways of designing  the AFKstate in the Tablist

_Some more Examples_

>     PlayerName: '[prefix][playerAFK][playerDisplayName]'
>     PlayerName: '[prefix][playerDisplayName] [PlayerAFK]'
