### ISSUE TITLE
Chat priority isn't working?? double messages

### ISSUE THREAD

**Issue by Sh0ckAdv** [Zrips/CMI#9483]
### Description of Issue

No matter how much I change the priority from 'chat.yml', the message is still sent to aman2 chats, for example 'SuperiorSkyBlock2' if you give /is chat, it is sent to the public chat and the island chat. 

I also tried with default configs in aman2 plugins, in vain.

### Version Information

```shell
[18:04:26 INFO]: --------------------------------------------------
[18:04:26 INFO]: CMI: 9.7.9.3 SqLite
[18:04:26 INFO]: CMILib: 1.5.2.9 
[18:04:26 INFO]: Server: Paper 1.21.1-R0.1-SNAPSHOT-
[18:04:26 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[18:04:26 INFO]: Modules -> 66 enabled 1 disabled: votifier
[18:04:26 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors.

https://prnt.sc/lf47H3MU8t8t
```

### Relevant Config Sections

```yaml
ModifyChatFormat:
    # Will try to modify chat to display it in defined format
    # If this is disabled and you have 3rd party plugin handling chat messages, consider disabling ClickHoverMessages section too if you notice any problems with chat formatting
    Enabled: true
    # Priority of public message format listener
    # Changed priority will only take effect on full server restart. Possible options: LOWEST, LOW, NORMAL, HIGH, HIGHEST
    # Default: NORMAL
    Priority: NORMAL
    # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
    # To change default hover over messages seen on sent message, go to your locale file to Chat section
    ClickHoverMessages: true
```

### Relevant Plugins

SuperiorSkyBlock2 [2024.4] 

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
