### ISSUE TITLE
Holograms failing to appear

### ISSUE THREAD

**Issue by Gayytis** [Zrips/CMI#9499]
### Description of Issue

I have 3 holograms, after creating them and getting away, then coming back, they disappear and do not appear again.

https://github.com/user-attachments/assets/906ecb49-8385-4694-a858-ed3cceacc18b

### Version Information

```shell
CMI: 9.7.9.4 SqLite
CMILib: 1.5.3.3
Serveur: Paper(173) 1.21.4-R0.1-SNAPSHOT+
CMI economy: Activé Vault: 1.7.3-CMI CMI Chat: Activé
Modules -> 44 activés 23 désactivés: spawnerProximity, signEdit, mirror, launchPad, tablist, versionCheck, skin, elytraBoost, spawners, dynamicSigns, elytraLaunch, bossBarCompass, coloredArmor, flightCharge, disabledEnchants, worldLimits, votifier, shulkerBackpack, spawnerCharge, vanish, namePlates, timedCommands, homeInteractions
```

### Errors

```shell
There is no errors in the console.
```

### Relevant Config Sections

```yaml
khepri:
  Loc: spawn;-390.5;107.2;-431.5
  NewDisplay: true
  Lines:
  - '&7&m------------------'
  - '&e&l» &4&lKhépri &e&l«'
  - '&7&m------------------'
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
