### ISSUE TITLE
Warnings are not working as they should

### ISSUE THREAD

**Issue by Teleriann** [Zrips/CMI#9503]
### Description of Issue

As you can see in my configuration, I have configured warning in a way that when player reached 4 warns he gets 2 weeks of jail time, 8 warns 4 weeks etc...

First 4 warnings are working just fine, player gets jailed as he should. But then in the 5th warn player gets jailed for 2 weeks again. On warn 6 and 7 nothing happens, warn just applyes and on warn 8 player gets jailed for 4 weeks as he should but then again on warn 9 he gets jailed again... you get the point.

The second issue with warnings is them being removed after the reload. When server restarts all of the warning are still there. I have CMI connected to the MySQL. When you perform reload command warnings are actually still inside of the database but when I perform /cmi warnings <nickname> there are not any. Then when you warn that user again all of the warnings disappear from the DB and only that actual one is there.

### Version Information

```shell
[01:37:11 INFO]: --------------------------------------------------
[01:37:11 INFO]: CMI: 9.7.9.5 MySQL
[01:37:11 INFO]: CMILib: 1.5.3.4 
[01:37:11 INFO]: Server: Paper 1.20.4-R0.1-SNAPSHOT-
[01:37:11 INFO]: CMI economy: Povoleno CMI Chat: Povoleno 
[01:37:11 INFO]: Modules -> 51 enabled 16 disabled: spawnerProximity, tablist, armorstand, skin, elytraBoost, spawners, elytraLaunch, flightCharge, worldLimitsElytra, chatBubble, ranks, firstJoinMessages, votifier, spawnerCharge, namePlates, totemBehavior
[01:37:11 INFO]: --------------------------------------------------
```

### Errors

```shell
There are no errors.
```

### Relevant Config Sections

```yaml
Warnings:
  # Should be always present. This will be used when category of warning isint being defined when warning player
  Default:
    # Time in seconds for how long this warning applies to player
    LifeTime: 31536000
    # Warning point amount player receives for warning
    Points: 1
    # Default reason used when reason is not provided when warning player
    DefaultReason: '&7Porušení pravidel'
  Categories:
    Swear:
      LifeTime: 86400
      Points: 1
      DefaultReason: '&7Swearing'
    Grief:
      LifeTime: 86400
      Points: 1
      DefaultReason: '&7Griefing'
    Bug:
      LifeTime: 86400
      Points: 1
      DefaultReason: '&7Using bugs'
    Cheat:
      LifeTime: 86400
      Points: 1
      DefaultReason: '&7Using cheats'
  Perform:
    '4':
    - cmi jail [playerName] 2w r:Dosáhl 4 varování!
    '8':
    - cmi jail [playerName] 4w r:Dosáhl 8 varování!
    '12':
    - cmi jail [playerName] 8w r:Dosáhl 12 varování!
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
