### ISSUE TITLE
Upon death, inventories don't always save (for years)

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#9525]
### Description of Issue

When players die, their inventory is supposed to be saved. However, for several years, there have been issues with this. Not all players are affected—some only have one save slot despite it being configured to 15, for instance, while others' inventories are not saved at all upon their death

### Version Information

```shell
[13:13:08 INFO]: --------------------------------------------------
[13:13:08 INFO]: CMI: 9.7.8.3 Velocity CMIB  MySQL-> 9.7.10.0
[13:13:08 INFO]: CMILib: 1.5.3.4 
[13:13:08 INFO]: Server: Paper(318) 1.20.2-R0.1-SNAPSHOT-
[13:13:08 INFO]: CMI economy: Activé Vault: 1.6.10(+) CMI Chat: Activé 
[13:13:08 INFO]: Modules -> 57 enabled 10 disabled: spawnerProximity, mirror, tablist, votifier, skin, elytraBoost, spawnerCharge, namePlates, playerChatTag, bossBarCompass
[13:13:08 INFO]: --------------------------------------------------
```

### Errors

```shell
no errors
```

### Relevant Config Sections

```yaml
inv:
  # Do you want to save the player's inventory on his death
  SaveOnDeath: true
  # When set to true, empty inventories (no items in inventory) will not be saved on players death
  IgnoreEmpty: true
  # If set to true then player should have cmi.saveinv permission node for inventory to be saved on death
  RequiresPermission: false
  # How many inventories, we will keep for each player
  SavedInventories: 20
  restore:
    # Set to false if you don't want to restore hp state on inventory load with /cmi invload command
    HP: false
    # Set to false if you don't want to restore players experience points
    XP: true
    # Set to false if you don't want to restore food state
    Food: true
    # Set to false if you don't want to restore saturation level
    Saturation: true
    # Set to false if you don't want to restore potion effects
    Potions: true
    # Set to false if you don't want to restore items
    Items: true
    # List of materials we should not save
    # Keep in mind that you might need to include all materials for colored items, like wool or shulker boxes
    BlackListedItems:
    - ''
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
