### ISSUE TITLE
Hover message appears twice

### ISSUE THREAD

**Issue by LitcherHUN** [Zrips/CMI#9527]
### Description of Issue

When someone types, and moves right after, one hologram stays behind, and one follows the player. When they stand still, the background gets darker since the holograms stack. The one following the player is colored, the one staying behind is gray.
Server restart did not help

![Image](https://github.com/user-attachments/assets/41f1c95d-f071-4a94-b744-aba0c9e7b5b3)

### Version Information

```shell
[13:13:34 INFO]: --------------------------------------------------
[13:13:34 INFO]: CMI: 9.7.10.2 SqLite
[13:13:34 INFO]: CMILib: 1.5.3.5
[13:13:34 INFO]: Server: Purpur(2389) 1.21.4-R0.1-SNAPSHOT+
[13:13:34 INFO]: CMI economy: Kikapcsolva Vault: 1.7.3-b131 CMI Chat: Engedélyezve
[13:13:34 INFO]: Modules -> 52 enabled 15 disabled: hpBossBar, mirror, tablist, moneyCheque, jail, eventCommands, bossBarCompass, flightCharge, disabledEnchants, ranks, playerCombat, votifier, shulkerBackpack, headDrop, timedCommands
[13:13:34 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors anywhere
```

### Relevant Config Sections

```yaml
ChatBubble:
  # Do you want to enable chat bubbles for public messages
  # Each player can disable this with /options command personally
  PublicMessages: true
  # Priority of chat bubble listener
  # Changed priority will only take effect on full server restart
  # Possible options: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
  # Default: MONITOR
  Priority: LOW
  # How high we should show chat bubble
  Offset: 2.5
  # Base time in seconds for chat bubble to be visible
  ShowFor: 5
  # Maximum time bubble will be shown for
  MaxShowFor: 10
  # Extra seconds to be added for each letter in a message
  # This will allow to have shorter times for short messages and increase it for longer ones
  ExtraTime: 0.02
  # Scale of chat bubble, default 1
  PlateScale: 1
  # Line width before wraping text to new line
  LineWidth: 255
  Background:
    # Default Color code, this could be overriden if text itself was colorized
    # Leave it empty for default transparent color
    # Example of color code: {#black}
    Color: '{#black}'
    # Value between 0 and 1 where 0 means no background color and 1 is fully opaque
    Opacity: 0.5
  # Do you want to add text shadow
  Shadow: false
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
