### ISSUE TITLE
FirstSpawn issues

### ISSUE THREAD

**Issue by 1821698021** [Zrips/CMI#9531]
### Description of Issue

I used Multiverse-Core to create a new world, and then I entered /setFirstSpawn in this new world to set the spawn point for new players. However, new players are not being teleported here when they join the server. I have reported this issue before, but it still hasn't been fixed. Please fix it, thank you!

### Version Information

```shell
paper-1.20.1
cmi-9.7.10.2
cmilib-1.5.3.5
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
Spawn:
  # Forces players to login in defined spawn point when logging into server
  # Can be bypasses with cmi.spawnonjoin.bypass permission node
  SpawnOnJoin: false
  # List of worlds which should be ignored and players joining in those servers will not be teleported to appropriate spawn point but will login at their log out location
  IgnoredWorlds: []
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  # TeleportFrom will indicate list of worlds from which player should be teleported to this spawn point
  Main:
    Location: ''
    RespawnLocation: false
    Rng: 0
    TeleportFrom: []
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    Location: ziyuan;28.01;75.0;14.33;-71.1;10.04
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
