### ISSUE TITLE
Lag -> Home Manager

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9542]
### Description of Issue

Hello, there seems to be lag according to the home manager, as well

![Image](https://github.com/user-attachments/assets/5d24e549-bda9-4997-947b-b469d783ea66)
https://spark.lucko.me/rpnPzuFP6n

![Image](https://github.com/user-attachments/assets/4d0fd3b1-cf81-4399-b53b-fb0db97e9e8b)

### Version Information

```shell
[14:28:16 INFO]: --------------------------------------------------
[14:28:16 INFO]: CMI: 9.7.10.3 SqLite
[14:28:16 INFO]: CMILib: 1.5.3.5 
[14:28:16 INFO]: Server: Purpur(2408) 1.21.4-R0.1-SNAPSHOT-
[14:28:16 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[14:28:16 INFO]: Modules -> 54 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[14:28:16 INFO]: --------------------------------------------------
```

### Errors

```shell

```

### Relevant Config Sections

```yaml

```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
What is the home count limit? And what type of icons are being used for home visualization?

**Comment by bobhenl** [comment]
my config:
```yml
Homes:
  # When enabled we will require player to click on ingame chat to confirm home location override in case home with same name already exist
  # This can be dirrectly confirmed with /cmi sethome [homeName] -override
  Confirmation: true
  # This defines max slot number player could provide while creating home with /sethome [homeName] [slotNumber]
  MaxGuiSlots: 99
  Gui:
    # Open gui when using /cmi home command if you have more then one home in your saved list
    Use: true
    # When enabled we will create more complex home UI with extra buttons and options while keeping this disabled we will simply list homes in a row
    Complex: true
    Options:
      # When enabled we will expand area for homes from 10 to 28
      Expanded: false
      # Keep it empty if you want to use global infill material
      Border: ''
      # Material around homes when its not in expanded state
      Infill: WHITE_STAINED_GLASS_PANE
      InfoButton:
        # Extra button to be used in case you want to provide any aditional information when clicking on it
        Use: false
        Slot: 1
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ==
        Commands:
        - closeinv!
      CloseButton:
        Use: true
        Slot: 9
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNjYmY5ODgzZGQzNTlmZGYyMzg1YzkwYTQ1OWQ3Mzc3NjUzODJlYzQxMTdiMDQ4OTVhYzRkYzRiNjBmYyJ9fX0=
        Commands:
        - closeinv!
      bedButton:
        Use: true
        Slot: 4
        Material: LIGHT_BLUE_BED
      homeButton:
        Use: true
        Slot: 5
        Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJkN2E3NTFlYjA3MWUwOGRiYmM5NWJjNWQ5ZDY2ZTVmNTFkYzY3MTI2NDBhZDJkZmEwM2RlZmJiNjhhN2YzYSJ9fX0=
      deathButton:
        Use: true
        Slot: 6
        Material: TOTEM_OF_UNDYING
      backButton:
        Use: true
        Slot: 7
        Material: BONE
      prevButton:
        Slot: 46
      middleButton:
        Slot: 50
      nextButton:
        Slot: 54
  # Homes groups to define max amount homes player can have. Permission: cmi.command.sethome.[groupname]
  # If players home group if not find then amount will be set to 1
  # To have unlimited homes use cmi.command.sethome.unlimited permission
  # In addition to this you can use simple numeric permission node cmi.command.sethome.[number] which will define max number of homes player can have
  Groups:
    Newbie: 2
    Advanced: 3
    Vip: 5
  # Requires cmi.bedhome permission node
  # When set to true by interacting with bed, regular home location will be created
  # When set to false vanilla bed home location will be set
  BedInteraction: true
  # When set to true, you can only set home location when you shift click a bed
  onlyShiftBed: false
  # Removes bed location when home location was created by clicking on that bed
  RemoveBedLocationOnBedBreak: true
  # When enabled, plugin will check if player can break block in that area before creating new home location
  # This allows to prevent setting homes in protected areas
  # Can be bypassed with cmi.command.sethome.bypass
  CheckBlockBreak: true
  # Name for default home location. By default its "Home"
  DefaultName: Home
  # Name for bed location. By default its "Home"
  # Different name can be used to identify home location set by interacting with a bed from home location created with command
  DefaultBedName: Bed
  # Defines what characters you can use in your home names
  ValidNameRegex: '[^a-zA-Z0-9\-\_]'
  WorldLimits:
    # When enabled home creation will be limited by defined criteria
    # This can be bypassed if you have cmi.command.sethome.bypasslimit permission node
    Use: true
    Groups:
      endfight:
        # Amount of homes you can have in this world home group. Setting to 0 would basically disable home creation in this world. Setting to lower than 0 will ignore this world group entirely
        Amount: 0
        # World list where this limit should apply to. Multiple worlds can be defined if you want to group them up
        Worlds:
        - endfight
      Example1:
        Amount: 3
        Worlds:
        - testWorld
      Example2:
        Amount: 5
        Worlds:
        - testWorld2
        - testWorld3
```
(icons are there)
and starting from 2 sethomes up to 15 max
