### ISSUE TITLE
EventCommand is halted when delay! is used in the custom alias called

### ISSUE THREAD

**Issue by TheDogg** [Zrips/CMI#9567]
### Description of Issue

I enabled an eventcommand for "joinserver" I call my custom alias (relevant config section below for the custom alias) as follows:

```
joinServer:
  Enabled: true
  Commands:
  - check:%cmi_user_metaint_staffmode%==1! asConsole! staffmode off [playerName]
```

all the commands of the custom alias gets executed up until the `delay! 10` and nothing after that gets executed when the play joins the server.

### Version Information

```shell
[15:26:24 INFO]: --------------------------------------------------
[15:26:24 INFO]: CMI: 9.7.11.1 MySQL
[15:26:24 INFO]: CMILib: 1.5.4.1 
[15:26:24 INFO]: Server: Paper(190) 1.21.4-R0.1-SNAPSHOT-
[15:26:24 INFO]: CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[15:26:24 INFO]: Modules -> 63 enabled 4 disabled: signEdit, flightCharge, spawners, kits
[15:26:24 INFO]: --------------------------------------------------
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
Custom Alias

staffmode:
    Cmds:
    - statement:check1! check:$1==On!
    - if:check1! asConsole! cmi toast $2 -t:task -icon:barrier Staff Mode Enabled
    - if:check1! asConsole! cmi usermeta $2 add staffmode 1 -s
    - if:check1! asConsole! cmi invsave $2 1
    - if:check1! asConsole! cmi clear $2
    - if:check1! asConsole! cmi god $2 true
    - if:check1! asConsole! cmi fly $2 true
    - if:check1! asConsole! lp user $2 parent add moderator
    - if:check1! asConsole! cmi bossbarmsg $2 -cw:0.05,10,yellow,red Staff Mode -c:red
      -s:1 -t:-1 -n:StaffBossBar
    - statement:check2! check:$1==Off!
    - if:check2! asConsole! cmi toast $2 -t:task -icon:barrier Staff Mode Disabled
    - if:check2! asConsole! cmi fly $2 false
    - if:check2! asConsole! cmi clear $2
    - if:check2! asConsole! cmi invload $2 $2 1
    - delay! 10
    - if:check2! asConsole! cmi god $2 false
    - if:check2! asConsole! lp user $2 parent remove moderator
    - if:check2! asConsole! cmi usermeta $2 add staffmode 0 -s
    - if:check2! asConsole! cmi bossbarmsg $2 -cancel:StaffBossBar
    Tab: true
    CustomTabs:
    - On,Off [playerName]
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
