### ISSUE TITLE
TimeSpeed not working

### ISSUE THREAD

**Issue by emerysteele** [Zrips/CMI#9573]
### Description of Issue

TimeSpeed doesn't seem to be working. Set day to 2400 seconds. But day still only lasting default 10 minutes (600 seconds)

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.11.1 BungeeCord CMIB  MySQL
CMILib: 1.5.4.1 
Server: Spigot(4475) 1.21.5-R0.1-SNAPSHOT-
CMI economy: Disabled CMI Chat: Enabled 
Modules -> 66 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
n/a
```

### Relevant Config Sections

```yaml
Time:
  # Defines preset time
  Day: '12:00'
  Night: '24:00'
  Morning: 06:00
  Dusk: '18:00'
  AutoTime:
    # Time in seconds time in game will be adjusted to match real
    # Keep it at arround one minute
    Interval: 60
    # Enables by default smooth sun transition to new time
    # You can always override this setting with -smooth variable in time command
    Smooth: true
    # Speed of smooth transition
    # 100 will mean that sun moves 100 times faster than usual until it reaches target time
    SmoothSpeed: 100
    # Worlds effected by autotime adjustment
    Worlds:
    - ''
  # Allows you to change vanilla time speed to your own liking and needs
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 2400
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 300
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
