### ISSUE TITLE
Issues with CMI and Censura plugins

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#9582]
### Description of Issue

Hi, im having problems when using CMI and Censura (https://github.com/YouHaveTrouble/Censura) plugins. 
Censura is a plugin that allows you to easily block words/characters... in chat, signs etc... something that doesnt CMI chat filter really have.

The problem is only with hangling chat messages that Censura flags as invalid, but CMI still sends the message.

Im trying to prevent usage of characters (such as ⁂) that have some textures assigned to them via resource pack.

### Version Information

```shell
CMI plugin version: 9.7.11.1 SqLite
CMILib: 1.5.4.1
Server: Paper(225) 1.21.4-R0.1-SNAPSHOT+
CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: enabled
Modules -> 43 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ran
ks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
Censura settings which prevents usage of ⁂ anywhere except chat

filter:
  rp:
    action:
      - "command: cmi ctext censura %player%"
    match:
      - ⁂: "contain"
```

### Relevant Plugins

Censura 2.2.1

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
