### ISSUE TITLE
placeholder check not working with CustomAlias when trigger by cmi schedule

### ISSUE THREAD

**Issue by LPPRR123** [Zrips/CMI#9600]
### Description of Issue

```
CustomAlias:
  bupiao:
    Cmds:
    - check:%md_dungeon_name%==jiandanzhiwu! mi give MATERIAL MENPIAO_MYSL1 $1- 1
```

```
bupiaoceshi:
  Enabled: false
  Commands:
  - allPlayers! bupiao [allPlayers]
  - allPlayers! say [allPlayers]
```

If I run the command /bupiaoceshi <playername>, the placeholder check work
If I run /cmi schedule bupiaoceshi, only "say [allPlayers]" work, the "allPlayers! bupiao [allPlayers]" not work.

### Version Information

```shell
CMI: 9.7.10.3 BungeeCord CMIB  SqLite-> 9.7.12.3
CMILib: 1.5.3.5 -> 1.5.4.2
Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
CMI economy: 禁用 Vault: 1.7.3-b131 CMI Chat: 禁用
Modules -> 65 enabled 2 disabled: tablist, votifier
```

### Errors

```shell

```

### Relevant Config Sections

```yaml

```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This is more tricky to handle. Your specific case could be solved by doing something like this
```
CustomAlias:
  bupiao:
    Cmds:
    - asConsole! mi give MATERIAL MENPIAO_MYSL1 $1- 1
```
```
bupiaoceshi:
  Enabled: false
  Commands:
  - allPlayers! ph! check:%md_dungeon_name%==jiandanzhiwu! bupiao [allPlayers]
```

Main points here are to avoiding translating placeholders with `ph!` before it gets to command processing for each player and do actual check inside scheduler command and not alias

Alternatively you can do this, which is somewhat simpler and keep same format for scheduler commands.
```
CustomAlias:
  bupiao:
    Cmds:
    - asConsole! ptarget:$1! check:%md_dungeon_name%==jiandanzhiwu! mi give MATERIAL MENPIAO_MYSL1 $1- 1
```
```
bupiaoceshi:
  Enabled: false
  Commands:
  - allPlayers! bupiao [allPlayers]
```
In this case scheduler command remains as it was, but alias command gets extra ptarget:$1! variable which will set target player from provided first variable, which originates from scheduler command and [allPlayers] variable, after which you can do same general checks you want and perform command

Both options should be valid, tho second one might be more intuitive
