### ISSUE TITLE
Players Spawn At /Spawn World On Server Restart

### ISSUE THREAD

**Issue by TylorTurner** [Zrips/CMI#9612]
### Description of Issue

I am trying to figure out what's going on, I have set up event join commands to remove players out of certain world when logging in, for some reason these players are getting kicked to spawn after a server restart (when they log in).

### Version Information

```shell
1.5.4.3
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
joinServer:
  Enabled: true
  Commands:
  - delay! 2
  - ifinworld:viking! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:hijacked! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:nuketown! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:bedwars! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:heaven! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:paintball! cmi spawn [playerName]
  - delay! 0.2
  - ifinworld:creative! cmi spawn [playerName]
  - delay! 0.2
  - attribute [playerName] minecraft:generic.max_health base set 20
  - delay! 0.2
  - perm:healthboost.sign! attribute [playerName] minecraft:generic.max_health base
    set 24
  - delay! 0.2
  - perm:healthboost.stream! attribute [playerName] minecraft:generic.max_health base
    set 24
  - delay! 0.2
  - contains:[playerName]=>.! attribute [playerName] minecraft:generic.max_health
    modifier remove 00000000-0002-c9eb-0000-0000000f113d
  - delay! 0.2
  - contains:[playerName]=>.! attribute [playerName] minecraft:generic.max_health
    base set 40
  - delay! 0.2
  - lp user [playerName] parent remove cancelspeccarry
  - delay! 0.2
  - lp user [playerName] parent remove suicidedown
  - delay! 0.2
  - lp user [playerName] parent add default
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
