### ISSUE TITLE
playerWorldChange and/or fly is bugged.

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#9618]
### Description of Issue

I have this playerWorldChange in EventCommads.yml
`check:%luckperms_inherits_group_subscriptionrank%==yes! check:%cmi_user_canfly%==False!
    ifinworld:Spawn! asConsole! cmi fly [playerName] true`
Which will give players with the rank mentioned fly in just the spawn world and as you can see from the screenshot it says fly has been enabled for them by the server, but the player doesn't actually get fly. Either it's bugged or I'm doing something wrong.

![Image](https://github.com/user-attachments/assets/3163cc2d-0174-4204-bd3a-105917731967)

### Version Information

```shell
[13:22:41 INFO]: --------------------------------------------------
[13:22:41 INFO]: CMI: 9.7.13.0 SqLite
[13:22:41 INFO]: CMILib: 1.5.4.3 
[13:22:41 INFO]: Server: Leaf(359) 1.21.4-R0.1-SNAPSHOT-
[13:22:41 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[13:22:41 INFO]: Modules -> 50 enabled 17 disabled: hpBossBar, customMessages, tablist, moneyCheque, elytraBoost, playerChatTag, elytraLaunch, bossBarCompass, flightCharge, deathMessages, chatBubble, firstJoinMessages, votifier, headDrop, sitAnimation, namePlates, timedCommands
[13:22:41 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors in console.
```

### Relevant Config Sections

```yaml
playerWorldChange:
  Enabled: true
  Commands:
  - check:%luckperms_inherits_group_trainee%==yes! check:%cmi_user_canfly%==False!
    ifinworld:Spawn! asConsole! cmi fly [playerName] true -s
  - check:%luckperms_inherits_group_subscriptionrank%==yes! check:%cmi_user_canfly%==False!
    ifinworld:Spawn! asConsole! cmi fly [playerName] true -s
  - check:%cmi_user_gamemode%==Survival! check:%cmi_user_canfly%==True! ifinworld:Spawn@!
    asConsole! cmi fly [playerName] false -s
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This can happen if you have multiple plugins trying to update players fly mode at same time, potential simplest solution would be to just add slight delay, so it would look like
```
playerWorldChange:
  Enabled: true
  Commands:
  - delay! 0.1
  - check:%luckperms_inherits_group_trainee%==yes! check:%cmi_user_canfly%==False!
    ifinworld:Spawn! asConsole! cmi fly [playerName] true -s
  - check:%luckperms_inherits_group_subscriptionrank%==yes! check:%cmi_user_canfly%==False!
    ifinworld:Spawn! asConsole! cmi fly [playerName] true -s
  - check:%cmi_user_gamemode%==Survival! check:%cmi_user_canfly%==True! ifinworld:Spawn@!
    asConsole! cmi fly [playerName] false -s
```
Which would delay checks and allow all of this to be applied slightly later and allow for player to fully be teleported to new world
