### ISSUE TITLE
LoginCustom and LogoutCustom Not Changing

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#962]
**Description of issue or feature request:**
I modified the wording of the Login and Logout messages but nothing was changing, the default message remained. 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  LogoutCustom: ' &3K&9A&3L&9A&3T&9I&3K&9O&3: &3[playerDisplayName] &3left the game'
  LoginCustom: ' &3K&9A&3L&9A&3T&9I&3K&9O&3: &3[playerDisplayName] &3joined the game'

```

---

**Cmi Version (using`/cmi version`):** 
8.0.19.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper 297

**Comment by Zrips** [comment]
check config file and set it to something like
```
Messages:
  Login:
    # If set to true, login message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding join messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom login message will be used. cmi.messages.disablelogin can be used to disable message for player
      Use: true
  Logout:
    # If set to true, logout message wont be shown
    Disabled: false
    # Defines number of players from which to automatically start hiding logout messages
    # Set to -1 to disable this
    AutoHideFrom: -1
    Custom:
      # If set to true, custom logout message will be used. cmi.messages.disablequit can be used to disable message for player
      Use: true
```
