### ISSUE TITLE
totem cd

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9621]
```
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: false
  # Require permission node for totem to be taken from inventory
  # RemoveFromInventory should be set to true and if this enabled player will need cmi.totem.frominventory
  RequirePermission: false
  Cooldown:
    # When this set to true player can use totem only every X second's
    Use: true
    Time: 300
  Warmup:
    # When this set to true player can use totem to have X amount of second's, during which he can die and be resurected
    # Totem will be consumed durring activation and wont be returned even if resurection is not used during warmup time
    Use: false
    Time: 10
  # If player falls into void while having totem, he will be teleported to respawn location and totem gets consumed
  ProtectFromVoid: false
  Effects:
    # Time in seconds effect needs to be applied to the player. Set it to 0 if you want to disable it
    Regeneration: 45
    FireResistance: 40
    Absorbtion: 5
```

EXCLUDE WORLD??
