### ISSUE TITLE
Hologram Placeholder Parsing Issue

### ISSUE THREAD

**Issue by NyhmsQuest** [Zrips/CMI#9624]
### Description of Issue

Noticed a strange issue, if I add # in front of `%topper_villager_trades;top_rank%` the rank stops displaying, but if I removed the # it shows.
Screenshot with # right before the placeholder making the placeholder disappear.
![Image](https://github.com/user-attachments/assets/a67af862-480b-4577-b519-57c253315167)
Screenshot with a space between the # and the placeholder making it show and work again.
![Image](https://github.com/user-attachments/assets/be8b0986-dba1-445f-b5b8-1a53949d807a)

This is the full line`&7#%topper_villager_trades;top_rank% &f#%player_name% &7- &b%statistic_traded_with_villager%`

This is what the developer said about this issue when I reported it to him, he believes it's an issue with CMI
![Image](https://github.com/user-attachments/assets/c6ee5167-b86b-47b7-8419-94d3d244c168)

Another placeholder that has problems being parsed is this one:
`&7#1 &f%topper_time_since_death;top_name;1% &7- &b%topper_time_since_death;top_value;1;time:pattern=d'd' H'h' m'm' s's'&type=duration&unit=seconds%`
Here is a screenshot of how it looks.
![Image](https://github.com/user-attachments/assets/abac9381-c8d3-47b4-a5f5-14c62bfbbc70)

This is what the developer of Topper said about this:

> Then it could be a problem with the way your hologram plugin handles placeholders. Your plugin may have accidentally replaced the `&u` in the placeholder before parsing the placeholder. I'm using DecentHologram and it works in my test server

### Version Information

```shell
[06:22:23 INFO]: --------------------------------------------------
[06:22:23 INFO]: CMI: 9.7.14.0 SqLite
[06:22:23 INFO]: CMILib: 1.5.4.3 
[06:22:23 INFO]: Server: Leaf(359) 1.21.4-R0.1-SNAPSHOT-
[06:22:23 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[06:22:23 INFO]: Modules -> 50 enabled 17 disabled: hpBossBar, customMessages, tablist, moneyCheque, elytraBoost, playerChatTag, elytraLaunch, bossBarCompass, flightCharge, deathMessages, chatBubble, firstJoinMessages, votifier, headDrop, sitAnimation, namePlates, timedCommands
[06:22:23 INFO]: --------------------------------------------------
```

### Errors

```shell
No errors in console.
```

### Relevant Config Sections

```yaml
TopTimeSinceDeath:
  Loc: Spawn;-124.75;72.5;-44.5
  Interval: 60.0
  Range: 16
  NewDisplay: true
  ND:
    Bill: FIXED
    TAlpha: 255
    Yaw: 90
    BAlpha: 0
  RequiresPermission: true
  Lines:
  - Time Since Death Leaderboard
  - '&7#1 &f%topper_time_since_death;top_name;1% &7- &b%topper_time_since_death;top_value;1;time:pattern=d''d''
    H''h'' m''m'' s''s''&type=duration&unit=seconds%'
  - '&7#2 &f%topper_time_since_death;top_name;2% &7- &b%topper_time_since_death;top_value;2%'
  - '&7#3 &f%topper_time_since_death;top_name;3% &7- &b%topper_time_since_death;top_value;3%'
  - '&7#4 &f%topper_time_since_death;top_name;4% &7- &b%topper_time_since_death;top_value;4%'
  - '&7#5 &f%topper_time_since_death;top_name;5% &7- &b%topper_time_since_death;top_value;5%'
  - '&7# %topper_time_since_death;top_rank% &f%player_name% &7- &b%statistic_time_since_death%'
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
