### ISSUE TITLE
Settings/Combat

### ISSUE THREAD

**Issue by livxbox5** [Zrips/CMI#9641]
### Description of Issue

I set everything up in the configs. 
I hit a player, he's in battle mode. 
he can leave the server and all the stuff is saved (stuff doesn't fall out when leaving the server).

### Version Information

```shell
[17:55:16 INFO]: --------------------------------------------------
[17:55:16 INFO]: Версия плагина CMI: 9.7.14.2 SqLite
[17:55:16 INFO]: CMILib: 1.5.4.4
[17:55:16 INFO]: Версия сервера: Paper(103) 1.21.5-R0.1-SNAPSHOT-
[17:55:16 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMI(CMIEInjector)CMI Чат: Включено
[17:55:16 INFO]: Модули -> 66 включено 1 отключено: votifier
[17:55:16 INFO]: --------------------------------------------------
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
Combat:
  # Defines combat timer to be used in particular features
  Timer: 15
  # When enabled we will allow for players to be damaged in safe zone if they are tagged for pvp
  safeZoneDamage: true
  Player:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # This will disable players fly mode which will result in player dropping down and will disable option to start flying
    # This can be bypassed by player performing fly command if he has access to it and commands durring combat are not blocked
    # Can be bypassed with cmi.pvp.PFlyBypass permission node
    DisableFlight: true
    # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
    # If set to false then only attacker will be marked for pvp mode
    IncludeVictim: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pvp type combat
    ShowBossBar: true
    # When enabled we will show damage numbers in a form of holograms when damaging players
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c⚔[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pvp.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage players while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pvp type combat
    BlockCommands: true
    AllowedCommands:
    - cmi msg
    - cmi reply
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
  Mob:
    # If set to true, then player who gets placed into combat mode will get its fly mode disabled
    # Can be bypassed with cmi.pvp.MFlyBypass permission node
    DisableFlight: true
    # If set to true, then attacked player will be included into combat mode even if he doesnt fight back
    IncludeVictim: true
    # If set to true player whose fly mode got disabled will not suffer fall damage, once
    DisableFallDamage: true
    # When set to true player will see boss bar message indicating how long until combat mode ends
    # This only applies for pve type combat
    ShowBossBar: true
    # When enabled we will include damage from environmental damage into mob combat timer
    # This can include damage from cactus, magma blocks, suffocation, burning, fall damage and similar
    IncludeEnvironment: true
    # When enabled we will show damage numbers in a form of holograms when damaging mobs
    ShowDamageNumbers: true
    DamageNumbersFormat: '&c❤[damage]'
    # Prevents damage from players with god mode enabled
    # Can be bypassed with cmi.pve.godBypass permission node
    noGodDamage: true
    # Informs player that he cant damage mobs while in god mode
    noGodDamageInform: true
    # When set to true players will be only able to use commands defined in the list
    # This only applies for pve type combat
    BlockCommands: true
    AllowedCommands:
    - cmi msg
    - cmi reply
    # When set to true AllowedCommands become black list which will define which commands player cant use
    MakeBlackList: true
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
