### ISSUE TITLE
first spawn feature does not work

### ISSUE THREAD

**Issue by siulung201314** [Zrips/CMI#9658]
### Description of Issue

I have set the first spawn location.
It only works on op.
Op can spawn at first spawn position when first joining the server.
However, players cannot spawn at the first spawn position. (eg. inside the building)
They spawn on the top of the building

There is no other plugins(eg. Multiverse-Core) that have the first spawn feature.
Therefore, only CMI control the players' first spawn position.

### Version Information

```shell
CMI 插件版本: 9.7.13.0 Velocity CMIB  SqLite-> 9.7.14.3
CMILib: 1.5.4.4 
Server: Purpur(2416) 1.21.4-R0.1-SNAPSHOT-
CMI economy: 禁用 Vault: 1.7.3-b131 CMI Chat: 啟用
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
Spawn:
  # Forces players to login in defined spawn point when logging into server
  # Can be bypasses with cmi.spawnonjoin.bypass permission node
  SpawnOnJoin: false
  # List of worlds which should be ignored and players joining in those servers will not be teleported to appropriate spawn point but will login at their log out location
  IgnoredWorlds: []
  # Defines players spawn point after death if set to true, if not, then it will be used only for /cmi spawn command
  # RespawnLocation will indicate if you want to use this location as possible respawn point for player after death
  # TeleportFrom will indicate list of worlds from which player should be teleported to this spawn point
  Main:
    Location: world;0.5;110.0;0.5;-180.0;0.0
    RespawnLocation: true
    Rng: 0
    TeleportFrom: []
  # Defines players first spawn point when he logs into server for the first time
  FirstSpawn:
    Use: true
    Location: world;0.5;110.0;0.5;-180.0;0.0
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
