### ISSUE TITLE
bug about Custom Mob Heads when EntityType use Chinese name in cmilib

### ISSUE THREAD

**Issue by Baige41** [Zrips/CMI#9665]
### Description of Issue

when EntityType use Chinese name in cmilib
Custom Mob Heads will become steve's head

![Image](https://github.com/user-attachments/assets/bc3839e8-814f-481a-b7d4-ce43ca474e2f)

### Version Information

```shell
cmi 9.7.14.4
cmilib 1.5.4.3
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
#CMILib/Translations/Locale_CN.yml

EntityType:
    acacia_boat: Acacia boat
    acacia_chest_boat: Acacia chest boat
    allay: 悦灵
    area_effect_cloud: Area effect cloud
    armadillo: Armadillo
    armor_stand: Armor stand

#
CMI/Settings/CustomHeads.yml

EntityHeads:
  allay:
    DropChance: 1
    LowerWithEachDrop: 80.0
    Heads:
    - 100:&b悦灵:YmVlYTg0NWNjMGI1OGZmNzYzZGVjZmZlMTFjZDFjODQ1YzVkMDljM2IwNGZlODBiMDY2M2RhNWM3YzY5OWViMyJ9fX0==
```

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.
