### ISSUE TITLE
[Issues] login and logout meassage missing for owners

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#990]
We have an owner and admin rank on our Server.

both haveing the owners starpermission. '*'
We are using pex

Problem: If they Login or LogOut we cant see this in Chat.
What we tryed is to negate the permission before the starpermission what usually should work. but in CMI it does not..anny clue what we can do? :3

```
  op:
    options:
      default: false
      prefix: '&4'
      suffix: '&c'
    permissions:
    - cmi.tablist.2
    - -cmi.messages.disablelogin
    - -cmi.messages.disablequit
    - '*'
```
