### ISSUE TITLE
[Bug] - Config Sign Option do not work?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#991]
In The Config These SignOptions can be found:
```
Signs:
  # Defines in milliseconds how often to check if player entered sign trigger area
  # Bigger numbers can help slightly lower server load
  # This is not essential to keep in low numbers
  CheckInterval: 5000
  # List of colors to be translated from one to another to avoid unreadable text
  TranslateColors:
  - '&6-&8'
  - '&e-&f'
  - '&7-&8'
```

Shouldn't &6 &e &7 should replaced with the other Colorcode to avoid unreadable?

![image](https://user-images.githubusercontent.com/12080017/47076079-353eb300-d1fe-11e8-9a01-87f6477a3d21.png)

Well they are not replaced
Else it would look like this:..
![image](https://user-images.githubusercontent.com/12080017/47076248-94042c80-d1fe-11e8-9f81-bc7c41b2f779.png)
